### ISSUE TITLE
Enhance "Add..." button functionality in the dashboard

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1001]
## Abstract & Motivation

When a user doesn't have any exchange /  blockchain / manual balances, a button appears urging the user to add something. This button currently just takes the user to the relevant page (api keys / accounts & balances). The button should do more. It should:
- take the user to the specific page where the action can be performed, and/or
- present the user with a modal allowing the user to add content without leaving the dashboard

## Specification

In some cases work will be required in the linked pages to allow linking to a specific section (or tab, if a page will be broken up into navigable parts).

TBD

**Comment by LefterisJP** [comment]
Hey @kelsos what do you think of this one? Should we go ahead and do something like that? I have been pushint it ahead for way too many releases.

**Comment by kelsos** [comment]
The second part might be a bit trickier but we can try the linking part sure
