### ISSUE TITLE
Sign the OSX .dmg by enrolling as a verified apple developer

### ISSUE THREAD

**Issue by kamescg** [rotki/rotki#1005]
## Abstract

Sign the bundled package, so I don't get the following error when installing.

![image](https://user-images.githubusercontent.com/3408362/82125623-f9fac200-975b-11ea-87a0-8860c9988325.png)

**Comment by LefterisJP** [comment]
Hey @kamescg thanks for the issue!

You can override this in OSX. We have a mention for this in our docs: https://rotki.readthedocs.io/en/latest/installation_guide.html#osx

As for signing the package and avoiding this warning, we would need an Apple developer ID which afaik isn't free. Is there any other way to sign the package and avoid this warning?

None of our core team uses OSX so any help with this would be appreciated.

**Comment by kamescg** [comment]
Yes - I use the workaround to install the application.

Personally if I were to consider a purchasing a premium version I would probably expect the company (or product team)to verify with Apple. That being said, it might not be worth the time/effort if no one is concerned.

Just thought I would bring it your attention as it might be dissuade certain users from installing the application.

**Comment by LefterisJP** [comment]
> Just thought I would bring it your attention as it might be dissuade certain users from installing the application.

That's very true and thanks for the heads up. User retention is a good reason to see if we can do something about it.

I had heard something about opensource programs being allowed to enroll in the Apple developer program free of charge so we may look if that is an option.

If not we may have to bite the bullet and get it. But for a small business trying to bootstrap itself there is no expense that can be considered insignificant.

**Comment by LefterisJP** [comment]
Hey @kelsos how hard would it be for this to be integrated with our CI, assuming we enroll into the Apple developer program? Can we try before enrolling or should we first enroll and then try?

**Comment by kelsos** [comment]
https://dev.to/rwwagner90/signing-electron-apps-with-github-actions-4cof I found this in the past and this is how it is supposed to be done.

**Comment by LefterisJP** [comment]
So if I get us the Developer ID Installer, and Developer ID Application certificates you can handle the rest I guess? If so I will put it in the milestone and find out how to enroll today.

**Comment by kelsos** [comment]
Yes you do what is required for the company account/id and then we can see how you can add my Developer account so I can take care of the rest
