### ISSUE TITLE
Support Coinbase Asset Conversions

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#1007]
## Abstract

In addition to the transaction types "Buy" and "Sell", Coinbase seems to have the tx type "Convert". Conversion happens when you trade one asset directly for another, e.g. DAI for ETH. It will not be returned in the Buys and Sells Endpoints.

## Motivation

Depending on the jurisdiction, "Converts" are taxable events and must be imported as such.

## Specification

Unfortunately, Coinbase doesn't seem to have a "converts" endpoint (analogous to "buys", "sells"). Maybe this needs to be implemented with the "transactions" endpoint (and because that returns "buys" and "sells" as well, maybe querying "transactions" is enough for everything).

PDF export lists them as "Convert":
![image](https://user-images.githubusercontent.com/46244227/82151697-13376780-985d-11ea-82ab-767fc5eed3ff.png)

**Comment by LefterisJP** [comment]
Hey @coinyon thanks for the issue.

When we first made the coinbase driver for Rotki such a transaction type did not exist.

What do you mean convert something for something else? I don't see this in their API documentation: https://developers.coinbase.com/api/v2#transactions

The transaction types currently available according to the API are:

```
send - Sent bitcoin/bitcoin cash/litecoin/ethereum to a bitcoin/bitcoin cash/litecoin/ethereum address or email (documentation)
request - Requested bitcoin/bitcoin cash/litecoin/ethereum from a user or email (documentation)
transfer - Transfered funds between two of a user’s accounts (documentation)
buy - Bought bitcoin, bitcoin cash, litecoin or ethereum (documentation)
sell - Sold bitcoin, bitcoin cash, litecoin or ethereum (documentation)
fiat_deposit - Deposited funds into a fiat account from a financial institution (documentation)
fiat_withdrawal - Withdrew funds from a fiat account (documentation)
exchange_deposit - Deposited money into Coinbase Pro
exchange_withdrawal - Withdrew money from Coinbase Pro
vault_withdrawal - Withdrew funds from a vault account
More to be added soon
```

If you have an account that has a "convert" event can you try querying the `transactions endpoint and see if you get results for it? If that works then their API docs need to be updated but at least the problem can be addressed.

**Comment by coinyon** [comment]
I have an account with some "converts", which don't appear in the buy/sell endpoints. I'll check if they appear in the transactions endpoint...

**Comment by coinyon** [comment]
I investigated a bit, and in the `transactions` API the type is called `trade`.

So after buys and sells we should query transactions endpoint and filter for trade.

```
{'amount': {'amount': FVal(XXXX), 'currency': 'ATOM'},
 'created_at': 'XXXX',
 'description': None,
 'details': {'payment_method_name': 'DAI Wallet',
             'subtitle': 'DAI Wallet verwenden',
             'title': 'Umgerechnet in Cosmos'},
 'id': 'XXXX',
 'instant_exchange': False,
 'native_amount': {'amount': FVal(XXXX), 'currency': 'EUR'},
 'resource': 'transaction',
 'resource_path': 'XXXX',
 'status': 'completed',
 'trade': {'id': 'XXXX',
           'resource': 'trade',
           'resource_path': 'XXXX'},
 'type': 'trade',
 'updated_at': 'XXXX'}
```

**Comment by coinyon** [comment]
And then there is the corresponding trade in the other currency:
```
{'amount': {'amount': FVal(XXXX), 'currency': 'DAI'},
 'created_at': 'XXXX',
 'description': None,
 'details': {'payment_method_name': 'DAI Wallet',
             'subtitle': 'DAI Wallet verwenden',
             'title': 'Umgerechnet von Dai'},
 'id': 'XXXX',
 'instant_exchange': False,
 'native_amount': {'amount': FVal(XXXX), 'currency': 'EUR'},
 'resource': 'transaction',
 'resource_path': 'XXXX',
 'status': 'completed',
 'trade': {'id': 'XXXX',
           'resource': 'trade',
           'resource_path': 'XXXX'},
 'type': 'trade',
 'updated_at': 'XXXX'}
```

**Comment by LefterisJP** [comment]
Are buys/sells also included in the transactions endpoint? It would really be better to use only one endpoint rather than 3

**Comment by LefterisJP** [comment]
Hey @coinyon since this is a nasty omission for coinbase users I would like to also include it in v1.5.0. I have my hands full right now with makerdao vaults. If you can implement it, that would be great!

If not I will have to do it after everything else is done.

**Comment by coinyon** [comment]
Sorry, can't promise I'll have the time. I'll let you know in case I pick it up.

And yes, buys & sells are included in the transactions endpoint as well, so querying that might be enough.

**Comment by LefterisJP** [comment]
@coinyon Thanks. Should not be that hard, if instead of writing a mocked test you test with your actual account. I don't have any good coinbase data to test with.

If you don't manage to make it by 1.5.0 perhaps we can push it to a patch release after it.

**Comment by LefterisJP** [comment]
Pushing this to v1.5.1

**Comment by yabirgb** [comment]
I've found that the resource link for transactions are not working. Things like the fees for the conversion are not available although I believe you can calculate them combining information of both wallets since amount in one wallet miss the amount in the other wallet by an amount that might be the fee.

**Comment by LefterisJP** [comment]
closed by #2660

**Comment by coinyon** [comment]
Thank you! :heart:

**Comment by coinyon** [comment]
Hm this is ignored by rotki as far as I can see:

```
2021-04-04 22:27:43 ERROR Conversion with id ... doesnt have two transactions. [{'id': '...', 'type': 'trade', 'status': 'completed', 'amount': {'amount': '...', 'currency': 'DAI'}, 'native_amount': {'amount': '...', 'currency': 'EUR'}, 'description': None, 'created_at': '...', 'updated_at': '...', 'resource': 'transaction', 'resource_path': '/v2/accounts/...', 'instant_exchange': False, 'trade': {'id': '...', 'resource': 'trade', 'resource_path': '/v2/accounts/...'}, 'details': {'title': 'Umgerechnet in Dai', 'subtitle': 'ETH Wallet verwenden', 'header': '... umgerechnet', 'health': 'positive', 'payment_method_name': 'ETH Wallet'}}]
```

**Comment by yabirgb** [comment]
@coinyon Do you also get duplicate conversions?

**Comment by LefterisJP** [comment]
Perhaps you guys can speak in discord to share a minimum amount of data to see why this happens.

**Comment by coinyon** [comment]
@yabirgb With current `develop` branch I get no errors anymore. It might be that https://github.com/rotki/rotki/pull/2679 solved my issue. So it's ok for now.

**Comment by LefterisJP** [comment]
It's quite possible. It could not find the matching trade for the conversion due to not getting all pages!
