### ISSUE TITLE
Premium statistics: Show to the user what's the range at which we got data for each graph

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1017]
## Problem Definition

At the moment the premium statistics allow any time range to be given. This is not optimal since it can confuse the user and some times if an invalid time range is given the graph may also not work properly.

![2020-05-20-204228_1103x163_scrot](https://user-images.githubusercontent.com/1658405/82484668-8ac5fa80-9ada-11ea-8c46-37c747970445.png)

## Task

To fix the above problem we should show to the user the range we have for each graph and not allow any dates outside of that range.

**Comment by kelsos** [comment]
@LefterisJP do we consider that fixed? (we still have to do a deployment ofcourse)

**Comment by LefterisJP** [comment]
Hmm this yeah. As I told you in discord perhaps not sure if the time range shown above the graph is required. But lacking any other way of showing the range of data perhaps it's actually a good idea. Closing this.
