### ISSUE TITLE
API and Usage Doc documentation needs to be added for Change Password Functionality

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1019]
## Abstract

https://github.com/rotki/rotki/pull/978 was implemented to address https://github.com/rotki/rotki/issues/763 (allow user to change their password), however the API and Usage Guide were not updated.

## Spec

Update the relevant files and be sure to include clear instructions accompanied by screenshots in the Usage Guide.
https://github.com/rotki/rotki/blob/develop/docs/api.rst#handling-user-creation-sign-in-log-out-and-querying
https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst

**Comment by LefterisJP** [comment]
I will pick this up and also update more stuff for v1.5.0
