### ISSUE TITLE
Support BCH blockchain onchain balance querying

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1028]
## Abstract

Add Bitcoin cash (BCH) blockchain support so that users can enter their BCH on chain addresses.

## Task

Do it. Probably will need to query something like blockchain.info for the prices. Will need to be careful to differentiate all over the codebase between bitcoin and bitcoin cash addresses as the sam address can exists in both chains. Need to make sure there is no mistaken assumptions anywhere.

**Comment by 7ql** [comment]
blockchair.com would probably be the most independent service provider to query. @Har01d

**Comment by 7ql** [comment]
Btw why was the label removed? Wasn't this a priority feature request?

**Comment by LefterisJP** [comment]
It was a mislabel.

**Comment by LefterisJP** [comment]
Backend done by: https://github.com/rotki/rotki/pull/4297

Frontend remains.
