### ISSUE TITLE
Check DSR and vaults for 0x714696C5a872611F76655Bc163D0131cBAc60a70

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1032]
## Problem Definition

Checking DSR for `0x714696C5a872611F76655Bc163D0131cBAc60a70` seems to give an error when querying logs.

`Did not find corresponding vat.move event for pot join. Skipping ...`

Also vaults work fine, but events are duplicated between vaults. The log query is probably too encompassing.

@isidorosp: Can you post the pictures you posted in discord and also the vault links in oasis along with the duplicated events? 

## Task

Figure out why and see if it can be fixed.

**Comment by isidorosp** [comment]
Vault links:
https://oasis.app/borrow/8632
https://oasis.app/borrow/8543

Backend-error for taxable event
https://media.discordapp.net/attachments/683245846070165504/714110019372580905/unknown.png

Image with duplicate/mixed events + timing order discrepancy in vault 8632
https://media.discordapp.net/attachments/683245846070165504/714138190864449606/unknown.png?width=1293&height=368

(note, there are also mixed/duplicate events in vault 8543 as well)
![image](https://user-images.githubusercontent.com/27592/82758506-417def80-9de7-11ea-9a0d-fa14e9d5e29b.png)

**Comment by LefterisJP** [comment]
https://github.com/rotki/rotki/pull/1042 should fix this.

Here is an image showing what was wrong and triggered the bug in the DSR. Which caused rotki to omit the 0 amount event.

![image877](https://user-images.githubusercontent.com/1658405/83082343-71492380-a083-11ea-88db-e2dfdc156d06.png)
