### ISSUE TITLE
Install roboto mono

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1034]
## Abstract

We should install the mono version of our main font in order to increase legibility and proper alignment of content in certain scenarios.

## Specification

https://www.npmjs.com/package/typeface-roboto-mono install, require it where we require roboto, use it in classes where a mono font is required to line things up properly in data tables / cards / etc.

**Comment by LefterisJP** [comment]
Is that something we can do for 1.6.0 or should we just push further?

**Comment by isidorosp** [comment]
Can leave it for later.

**Comment by LefterisJP** [comment]
Taking this out of milestones as it's not a requirement.
