### ISSUE TITLE
Main currency balances shouldn't be converted

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#1053]
## Problem Definition

Manually tracked EUR balance, main currency set to EUR shows two different values. So there seems to be some conversion going on in the background, whereas it shouldn't.

Example:
![image](https://user-images.githubusercontent.com/19181985/83357026-17d64280-a36a-11ea-818a-0c5cdc817ca7.png)

**Comment by isidorosp** [comment]
Hey @kilrau!

Could you please specify exactly which screen + table you are seeing this in? It's possible it's fixed in the in-progress 1.5.0 release as we identified a few places where "double conversion" was happening (e.g. EUR -> USD -> EUR).

**Comment by kilrau** [comment]
> Could you please specify exactly which screen + table you are seeing this in?

Accounts & Balances -> Balances (lowest category where all manually tracked balanced appear)

> It's possible it's fixed in the in-progress 1.5.0 release as we identified a few places where "double conversion" was happening (e.g. EUR -> USD -> EUR).

That sounds precisely what was happening. 

> Alternatively if you can run the client from source, can you see if the issue still persists on the latest develop branch?

I am happy to run a 1.5RC linux .appimage :)

**Comment by isidorosp** [comment]
Thanks for the quick reply =) 

> > Could you please specify exactly which screen + table you are seeing this in?
> 
> Accounts & Balances -> Balances (lowest category where all manually tracked balanced appear)

Yes, I think we've addressed this one. At least on my end I just made a dummy entry for 100 EUR and it looks correct.
![image](https://user-images.githubusercontent.com/27592/83357323-042bdb80-a36c-11ea-918d-7f09feca90c4.png)

> > Alternatively if you can run the client from source, can you see if the issue still persists on the latest develop branch?
> 
> I am happy to run a 1.5RC linux .appimage :)

I'll leave that to @lefterisjp =). I'll mark this issue as in progress and if we get confirmation when you get a chance to test / the update comes out we can close it.

**Comment by LefterisJP** [comment]
Hey @kilrau I assume you are using the last release (v1.4.2) right?

The problem should be there for that version. It's fixed in develop (reported in https://github.com/rotki/rotki/issues/957) and should make it in the next version v1.5.0.

@isidorosp I just noticed we did not add a changelog for this bug :)

**Comment by isidorosp** [comment]
Hey @kilrau can you confirm that this is fixed on your end as of 1.5.0?

**Comment by kilrau** [comment]
Dang, sorry for the delay. Yes this is fixed in 1.5.0! Closing :tada:
