### ISSUE TITLE
Add a component to render string percentages

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1057]
## Abstract

AmountDisplay is used for numbers, but in certain cases the backend provides values that are string percentages (e.g. "35%"). A new component should be create to render these, taking into account that the rendered value should adopt to `privacyMode` and `scrambleData` props found in AmountDisplay.

**Comment by LefterisJP** [comment]
Are you working on this @isidorosp as I see you scheduled it for v1.5.0?

**Comment by isidorosp** [comment]
> Are you working on this @isidorosp as I see you scheduled it for v1.5.0?

I haven't had a chance to start work on it yet. We could push to 1.6 I guess and these specific instances of percentages just won't conform to privacy/scramble mode for the time being.

**Comment by LefterisJP** [comment]
Pushing it to v1.6.0 (can also go in a patch, but not a priority)

**Comment by LefterisJP** [comment]
Pushing this yet again. If this is not something you guys want then please move it to the backlog.

**Comment by kelsos** [comment]
The initial component can be simple and it won't be to much of work. I will do that after we finish with the trades, it won't take much.

**Comment by LefterisJP** [comment]
@kelsos if you can make it please change the milestone. Remember it's not just trades but also deposit/withdrawals and the ethereum transactions view
