### ISSUE TITLE
Evaluate which 400 backend errors could move from the dialogs to the input forms

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1089]
## Abstract

Originally we would show all backend validation errors as modal dialogs. 
We have seen that we can customize marshmallow to return proper information on which field the validation failed on. 

We should evaluate in which cases it makes sense to move these errors from modal dialogs to the input fields themselves. 

One potential place for doing that would be the account creation and login dialog

### Tasks
- [ ] Check the various forms and make a list of the ones that need this treatment

**Comment by LefterisJP** [comment]
Hey @kelsos haven't we already started doing that in multiple places?

**Comment by kelsos** [comment]
Yes, we did but not all of the places support it I will have to check the forms and see which places support it and which not.
And maybe create specific issues for each.

**Comment by LefterisJP** [comment]
> Yes, we did but not all of the places support it I will have to check the forms and see which places support it and which not.
> And maybe create specific issues for each.

Okay great, Agreed. And then let's close this, since these generic issues tend to be open forever and never looked at again.

**Comment by kelsos** [comment]
I cannot think of a place where we would need this right now. I am gonna close the issue and we can open specific issues if something comes to our attention.
