### ISSUE TITLE
Adding a generic update button to include manually added coins / balances

### ISSUE THREAD

**Issue by Greekcc** [rotki/rotki#1092]
## Abstract

Hi there - I see value in adding an update button that will refresh the balances for the manually added tokens as well. 

## Task

1. Add a button to refresh manually added balances
2. Have a timer in the frontend to requery manually added balances and update the frontend state in specific intervals.
3. Once that's done think and perhaps make another issue to extend this strategy to the entire portfolio

**Comment by adrien-be** [comment]
+1

**Comment by LefterisJP** [comment]
@kelsos Could we add this to v1.7.0 along with the trades/deposits withdrawals and transactions views? Or push for 1.8?

**Comment by kelsos** [comment]
It should be doable, do we want only the button? or do we add also the automatic refresh mechanism?

**Comment by LefterisJP** [comment]
For now only the button. Automatic refresh can be something to be done later. And could also be triggered by the backend somehow,.
