### ISSUE TITLE
Active tab in Settings has the wrong text color

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1109]
## Problem Definition

The active tab in the settings sub-pages is not using the correct text color (should be white)
![image](https://user-images.githubusercontent.com/27592/85621372-8060c880-b665-11ea-80e8-e33d25841341.png)

**Comment by isidorosp** [comment]
@LefterisJP I must have fixed this already in some of the PRs already pushed to develop, but in `develop` it looks fine. Can you confirm on your end as well?
![image](https://user-images.githubusercontent.com/27592/85622059-8d31ec00-b666-11ea-9fd0-6f02778b972f.png)

**Comment by LefterisJP** [comment]
Yes in develop it's fixed. The reason I pointed it out in the chat is that in v1.5.0 this is broken but will be fixed in next release.

**Comment by isidorosp** [comment]
Fixed in develop.

**Comment by LefterisJP** [comment]
Love these kind of issues. "Already fixed" :smile:
