### ISSUE TITLE
Keep ENS metadata for addresses and show ENS names of an address in the UI

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1115]
## Abstract

This is a continuation of https://github.com/rotki/rotki/issues/530.

Rotki currently accepts ENS addresses as input for ethereum account additions. The ENS name resolves to an address and is later forgotten.

We should keep any possible ENS names associated with the address either since we know it resolves due to additions or through reverse resolution (also known as primary ens name) and show them as tags or labels in the account.

## Tasklist

- [ ] We should add a way for the frontend to ask the backend which addresses support ENS. So an API endpoint that can be given a list of addresses and return a list of ENS names (reverse resolution) or vice versa.
- [ ] Then the frontend should have a setting to show ENS names instead of hex addresses and if that setting is on it should do just that.

**Comment by emansipater** [comment]
Strongly in support of this feature.

**Comment by yabirgb** [comment]
For this one... do we have already any table for metadata about an address? By looking at the DB schemas I don't see any.
Also if the ENS NFT is transfered this information should be updated but maybe is something that can be done in #982
