### ISSUE TITLE
Add substantial events to networth graph

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1118]
## Abstract

The net-worth graph is currently a nice way to see an overall picture of the changes in net value, but sometimes there's extra info necessary to explain certain "jumps" in the data. As an example, if you add an exchange where you already have a large balance, this would cause the graph to spike upwards which might otherwise be understood to be a gain in positions.

The graph could be embellished with additional "events" that could be filtered on/off to help a user interpret their history (e.g. withdrawals, additions of addresses/exchanges, etc.).

Such functionality would be predicated on the backend continually fetching and updates something like "all events / trades" in the background, so that the graph can pull from both the netvalue call and this all events call to overlay both sets of data. This data could also be used to make a timeline of events for the user which would also be a nice statistical component.

**Comment by LefterisJP** [comment]
I am going to close this. It was not a bad idea when first mentioned.

But now with snapshots being editable to fix any such discrepancies, it makes no sense to have an audit log of events such as added an exchange or a new chain to show why spikes in the graph happened.

In addition when we present a historical graph from processed events, this becomes even less important.
