### ISSUE TITLE
Use metamask to easily import accounts on rotki

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1122]
## Abstract

Enable a way to use metamask to import account addresses to rotki

> If your desktop app could briefly host a page and open the user’s browser to it, you could ask the user selects all the accounts they want to share.
Caveat: at the moment they will need to then select each of those accounts, for compat reasons. Adding a “expose all at once” soon.
https://twitter.com/danfinlay/status/1279112773234917376?s=20

## Motivation

It makes it easier for users to import their accounts to rotki

**Comment by LefterisJP** [comment]
@kelsos As discussed perhaps put a description of how it can be done here. Perhaps we can also ask a community member to do this.
