### ISSUE TITLE
Make the periodic client query customizable

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#114]
The periodic client query right now happens only once every minute.

Code is [here](https://github.com/rotkehlchenio/rotkehlchen/blob/5a8dbc8d73e85f33a4de1505bbeb1698424e4089/ui/utils.js#L130)

- Make this value customizable
- Have a minimum periodic query limit. i.e. should never be more frequent than once per minute

**Comment by djibix** [comment]
Hi @LefterisJP, I started to have a look at this issue but it looks like the code has changed a lot since that time.
I can't find the function "setup_client_auditor"
Is this issue still open? if yes can you update the link to the code?

**Comment by LefterisJP** [comment]
Oh wow that's a rather old issue. Kudos for digging it up.

So it's still valid from what I can see. It concerns the [periodic_query](https://github.com/rotki/rotki/blob/0c6af0ee9a5e94da91db8aff703a259d4e7f8e04/rotkehlchen/api/rest.py#L1120) endpoint. The frontend calls it from here: https://github.com/rotki/rotki/blob/0c6af0ee9a5e94da91db8aff703a259d4e7f8e04/frontend/app/src/services/monitoring.ts.

I guess you could make this a frontend-only setting since this affects only how the frontend queries the backend. But it should not be more frequent than the current querying.

For more info on the frontend pinging @kelsos

**Comment by djibix** [comment]
I see 3 different timer values in the code (5s, 2s, 6m). Do they each need a setting? otherwise which one?
https://github.com/rotki/rotki/blob/0c6af0ee9a5e94da91db8aff703a259d4e7f8e04/frontend/app/src/services/monitoring.ts#L22-L39
Thanks

**Comment by kelsos** [comment]
> I see 3 different timer values in the code (5s, 2s, 6m). Do they each need a setting? otherwise which one?
> 
> https://github.com/rotki/rotki/blob/0c6af0ee9a5e94da91db8aff703a259d4e7f8e04/frontend/app/src/services/monitoring.ts#L22-L39
> 
> Thanks

Hey @djibix only the first one (5s) is involved in the periodic checking the other two are for different things

**Comment by kelsos** [comment]
Closed by #1871
