### ISSUE TITLE
Sorting ETH accounts by name doesn't work

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1140]
## Problem Definition

I clicked the Account header to sort my ETH accounts by name, but as you can see it does not correctly sort them alphabetically: 

![image](https://user-images.githubusercontent.com/100738/87227462-02a1fa00-c393-11ea-9825-4df750d3492b.png)

### System Description

Rotki 1.5.0 on openSUSE Tumbleweed

**Comment by LefterisJP** [comment]
I suspect it may be sorting them by hex address as the name is another field which is just shown to the user for convenience here.

So sorting may need some additional logic here. Sort by hex address is no label (name) is given but use the label is one is given.

Right @kelsos? This could also be an easy fix?

**Comment by kelsos** [comment]
Yes we are probably do sort the by hex and no it should not be hard to customize sorting to take into account the labels

**Comment by LefterisJP** [comment]
@kelsos We could give an easy win if we include it by v1.6.0, right? Should not be hard to schedule it (even if 1.6.0 happens after 20th of July when I am back from vacation).

Are you comfortable with scheduling this for 1.6.0?

**Comment by kelsos** [comment]
Yes sure

**Comment by isidorosp** [comment]
@kelsos I think I can pick this up in the Accounts & Balances revamp.

**Comment by kelsos** [comment]
Sure go ahead

**Comment by aspiers** [comment]
This is still sorting by the hex address in 1.11.0.  Please can we reopen?

**Comment by kelsos** [comment]
@aspiers The way it is currently implemented it can be either the hex or the name since they are in the same field.

**Comment by kelsos** [comment]
We need to think of a way to mix the sorting depending on whether the name exists or not.

**Comment by aspiers** [comment]
[**@kelsos**](https://github.com/kelsos) commented on [January 12, 2021 7:04 PM](https://github.com/rotki/rotki/issues/1140#issuecomment-758871303 "2021-01-12T19:04:55Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers) The way it is currently implemented it can be either the hex or the name since they are in the same field.

I don't follow.  It's completely ignoring the name for me and only sorting by hex.

**Comment by kelsos** [comment]
> [**@kelsos**](https://github.com/kelsos) commented on [January 12, 2021 7:04 PM](https://github.com/rotki/rotki/issues/1140#issuecomment-758871303):
> 
> > [@aspiers](https://github.com/aspiers) The way it is currently implemented it can be either the hex or the name since they are in the same field.
> 
> I don't follow. It's completely ignoring the name for me and only sorting by hex.

Yes what I mean is the current implementation would be limited to one or the other not both at the same time. We need to figure a different way and introduce a custom implementation to support both.

**Comment by aspiers** [comment]
OK thanks.  So please can you reopen this?

**Comment by LefterisJP** [comment]
Aha so you want first by hex and then by name @aspiers ?

**Comment by kelsos** [comment]
I need to think of a way to approach the sorting so that you can have either option

**Comment by aspiers** [comment]
[**@LefterisJP**](https://github.com/LefterisJP) commented on [January 12, 2021 7:13 PM](https://github.com/rotki/rotki/issues/1140#issuecomment-758875702 "2021-01-12T19:13:26Z - Replied by Github Reply Comments"):
> Aha so you want first by hex and then by name [@aspiers](https://github.com/aspiers) ?

No I want sorting by name.

Sorting by hex doesn't seem very useful to me.  If people want to locate an account by hex then it would be friendlier to let them do a hex search instead rather than force them to visually scan down a sorted list.  I suppose if they have another list of sorted hex addresses it could be a semi-useful way of visually comparing the two lists.  But there would be friendlier ways of doing that too, like exporting the address list to the clipboard so that you could paste into a file and then run `diff` to compare it with the other list.

**Comment by kelsos** [comment]
@LefterisJP what do you think would it make sense in your opinion to just do a by label sorting and completely ignore the hex sorting?

That would be really quick to introduce.

**Comment by LefterisJP** [comment]
> @LefterisJP what do you think would it make sense in your opinion to just do a by label sorting and completely ignore the hex sorting?
> 
> That would be really quick to introduce.

Yes that would be what I also expect should happen. I thought we already did that since this issue was closed, but apparently I never tested/used it.

But just looked at develop and indeed @aspiers is right that it's missing. So if you can just do by label sorting and completely ignore the hex that's fine.

But not every address will have a label. In that case what will you do?

**Comment by kelsos** [comment]
They will probably be at the end or start depending on the sorting selection.

**Comment by kelsos** [comment]
I will pick it up in the morning. it should be simple enough.

**Comment by aspiers** [comment]
Thanks guys! :-) :clap:

**Comment by aspiers** [comment]
This still does not work properly; please can you reopen?  When I click on the Address column header, it weirdly cycles between not two but *three* different sorting modes, none of which correctly sort according to the account label:

![vokoscreenNG-2021-02-25_18-20-48](https://user-images.githubusercontent.com/100738/109198661-66e4c300-7796-11eb-85fd-1af358c1dbef.gif)

**Comment by kelsos** [comment]
Yes, the modes are 3 indeed, it is ascending/descending and default (data order).

@aspiers I see that this is not in the ethereum balances but in the assets table, so it's a new issue.

**Comment by aspiers** [comment]
Just curious - what is the idea behind having a data order?  I've never seen this before.

**Comment by kelsos** [comment]
The data order is basically the order the data have in the underlying array so, you can have an ascending or descending order, but if you don't set it, it will display the data as they are ordered in the source dataset.

**Comment by aspiers** [comment]
Sure, I understand that, but my question was: what is the point of supporting that?  What is the use case?

**Comment by kelsos** [comment]
> Sure, I understand that, but my question was: what is the point of supporting that? What is the use case?

Well, it's actually pretty simple. Vuetify's data table by default behaves like this, it doesn't enforce a sorting selection. You have to override the configuration if you want to always have a sorting option selected. So it's not supporting it per se, rather that was the default and we didn't have any complaints or issues with that so far.

I cannot think of a specific use case of why would we prefer it this way over enforcing a selection, I am not sure if @LefterisJP was a different opinion on that. Looking into vuetify's configuration, it looks simple enough to make a sorting selection required.

**Comment by aspiers** [comment]
Ah, I see.  My instinct is that given this is different to every single other sortable table UI I've ever seen, unless there's a concrete reason for keeping it, it is more likely to confuse users than help them.  But maybe there is a good use case and I'm just missing it.

**Comment by aspiers** [comment]
Filed as #2452.

**Comment by LefterisJP** [comment]
I will respond in the filed issue
