### ISSUE TITLE
[website] usage guide and FAQ both need to be MUCH easier to find

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1141]
https://rotki.readthedocs.io/ is not yet linked from https://rotki.com/.  This is SUPER important for attracting new people. I suggest putting it somewhere near the "Get Rotki!" section, at least definitely before the "Like the project?" because people have to learn how to use it before they will decide whether they want to contribute.

Also, the FAQ link on the homepage is WAY too hard to find - the text is tiny, and it's hidden away in the bottom right corner of a lonnnng page.  So I would suggest putting large icons for the docs and FAQ together in the same place somewhere.

**Comment by aspiers** [comment]
Of course it's entirely up to you guys, but I would gently suggest that the cost:reward ratio is so good on this one that it should be done sooner rather than later ;-)

**Comment by LefterisJP** [comment]
A lot of things on our plate and it's vacation time :wink: 

We want to "soon" prioritize a good redesign of the website. Perhaps until then this can be done.

I can take care of it but not really sure how it should look like. Any ideas also @isidorosp ?

**Comment by aspiers** [comment]
What I had in mind should be achievable in 10 minutes, e.g.

1. Find two icons, for the docs and FAQ, which match the style of the existing icons for `Contribute` / `Donate` etc.
2. Add a new section entitled "Learn more" just above "Like the project?", and put the two new icons in that, linking to https://rotki.readthedocs.io/ and https://rotki.readthedocs.io/en/latest/faq.html respectively.

IMHO this is such a significant improvement to the home page that it doesn't make sense to delay it until you have time for a redesign.  The docs and FAQ are already really good, so it seems crazy to me that they are so hard to find.  If you want to build the community quickly, it's *really* important that all this info is easy to find.  The list of basic and Premium features on the home page are great, but they are only enough to get people interested to find out more.

But of course, vacation is also important ;-)

BTW I think the home page is already pretty good so a redesign doesn't seem that important to me anyway ;-)

**Comment by LefterisJP** [comment]
Deployed this in the production website just now: https://rotki.com/

![2020-07-26-163411_751x471_scrot](https://user-images.githubusercontent.com/1658405/88481808-dfb04200-cf5d-11ea-9411-09e8e48abe63.png)

If you think that's sufficient feel free to close the issue. I also agree it's a very big win to link the docs from the website.

> BTW I think the home page is already pretty good so a redesign doesn't seem that important to me anyway ;-)

Haha you must be the only person saying that. People have said pretty bad things about that site. And it's mostly mea culpa as I have zero design capabilities and we never got any design help for the website.

**Comment by aspiers** [comment]
> If you think that's sufficient feel free to close the issue.

Perfect, thanks!

> Haha you must be the only person saying that. People have said pretty bad things about that site. And it's mostly mea culpa as I have zero design capabilities and we never got any design help for the website.

Haha, well I have zero design capabilities too ;-)  OK, it might not be the most beautiful, but it (now) gets the job done and that's the most important thing.  To my eyes the worst thing currently is the excessive vertical spacing between sections.  Maybe that is another thing which could be fixed in 10 mins?
