### ISSUE TITLE
[website] suggestions to improve Premium page

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1142]
This feedback is based on my experience as a newcomer deciding whether to sign up for Premium.

I visited https://rotki.com/products/ and found that the expanding feature details button is too easy to miss. It would be better if the premium features were all visible on page load, and then you can click on each one for more details.

In particular, the point in the data sync feature "The data is encrypted with your password and we can not read it." is SUPER important (since your main USP is that you are privacy preserving), so IMHO it should be made much more prominent.

You should also give details of:

1. how the encryption works,
2. why you cannot read the encrypted data, and
3. whether the code has been independently audited by security experts. If it hasn't been audited yet, that's totally fine since you are a relatively new project, but in that case it would be really good if the site could state what plans you have to get an independent audit in the future.

**Comment by LefterisJP** [comment]
> I visited https://rotki.com/products/ and found that the expanding feature details button is too easy to miss. It would be better if the premium features were all visible on page load, and then you can click on each one for more details.

The main reason it's like that is that the user would have to scroll way too much down initially to see the prices. Perhaps the best approach would be eventually to add all premium feature details to its own page and have a link there.

**Comment by aspiers** [comment]
[**@LefterisJP**](https://github.com/LefterisJP) commented on [August 9, 2020 10:22 AM](https://github.com/rotki/rotki/issues/1142#issuecomment-671028764 "2020-08-09T09:22:08Z - Replied by Github Reply Comments"):
> > I visited [rotki.com/products](https://rotki.com/products/) and found that the expanding feature details button is too easy to miss. It would be better if the premium features were all visible on page load, and then you can click on each one for more details.
> 
> The main reason it's like that is that the user would have to scroll way too much down initially to see the prices.

That is because currently it's a single column with a lot of space wasted.  You could change it to two columns, or to an image carousel, or some other more space-efficient layout.  You could also make the screenshots smaller.

But even if you don't change the layout, the main problem is that the expanding button isn't that obvious - the up arrow doesn't clearly show that it can expand.

> Perhaps the best approach would be eventually to add all premium feature details to its own page and have a link there.

I guess... I'm not convinced this would be better but I could be wrong ;-)

**Comment by kelsos** [comment]
The same here, I am gonna create an internal issue to keep the feedback in mind and close this issue
