### ISSUE TITLE
[UI] don't show 0 notification count

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1143]
When there are no notifications, I see:

![image](https://user-images.githubusercontent.com/100738/87227594-0e41f080-c394-11ea-99f8-464ffa8bde38.png)

To improve the UI/UX experience, the red circle should only be used when there are unread notifications, ie. the count is greater than 0.  Otherwise the use of red unnecessarily draws attention to it when no action is required.

**Comment by yairash** [comment]
Hey! can i work on this?

**Comment by LefterisJP** [comment]
@yairash sure if you know vue.js and can build the app we would love the help!

**Comment by yairash** [comment]
@LefterisJP Oops, didn't notice it is vue.js ... i'll have to give up on this one! appreciate the willingness anyway thanks!

**Comment by yairash** [comment]
@LefterisJP on it!

**Comment by yairash** [comment]
Hey guys, so i made some changes in the code to solve this(locally of course) is there anyway i can test it before a pull request?

**Comment by isidorosp** [comment]
Hey yairash, do you mean in terms of writing tests or just running the app locally? If you mean just running it locally then you can follow the instructions on building/running from source here:
https://rotki.readthedocs.io/en/latest/installation_guide.html

**Comment by yairash** [comment]
Hey, I believe i fixed the issue, but since its my first commit im not sure how should i pull a request. 
I would really appreciate which steps should i follow? should i create a new branch? and if so, should i name it in a particular way?
Really appreciate the help!

**Comment by LefterisJP** [comment]
Just create  a new branch, push in your fork and github will prompt you to open a pull request here. If you have not created a PR before check this: https://opensource.com/article/19/7/create-pull-request-github

**Comment by yairash** [comment]
> Just create a new branch, push in your fork and github will prompt you to open a pull request here. If you have not created a PR before check this: https://opensource.com/article/19/7/create-pull-request-github

Thank you!
