### ISSUE TITLE
[UI] consider simplifying or restructuring menubar / sidebar

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1144]
From a UI/UX perspective, I find the combination of the menubar and sidebar somewhat confusing.  This is especially noticeable when the sidebar is closed:

![image](https://user-images.githubusercontent.com/100738/87227704-c53e6c00-c394-11ea-9a5d-05772894dd46.png)

as then the burger icon doesn't make it obvious that there is so much stuff hidden behind clicking it.  But also when it's open, to me it's not obvious what the logic was for deciding which items can be found in one vs. the other.

![image](https://user-images.githubusercontent.com/100738/87227667-86101b00-c394-11ea-8d57-0c463c134fd8.png)

I would recommend getting an expert in usability (not me!) to take a quick look at it and give some recommendations how to make them more intuitive.

**Comment by isidorosp** [comment]
In 1.6.0 the menubar is "minified" when closed (as opposed to disappeared) unless your viewport is really small, in which case it will overlay like in your second screenshot when opened. In general if you make your app a bit wider the menubar on the left should show "inline" as opposed to overlayed.

**Comment by aspiers** [comment]
Yeah I noticed that after filing this.  It's definitely helpful, but I think there is more room for improvement here still ;-)

**Comment by aspiers** [comment]
This was the action I recommended:

> I would recommend getting an expert in usability (not me!) to take a quick look at it and give some recommendations how to make them more intuitive.

but more than happy to discuss.  I'll be in Amsterdam for 10 days from tomorrow, will any of you guys be there?!

**Comment by LefterisJP** [comment]
> This was the action I recommended:
> 
> > I would recommend getting an expert in usability (not me!) to take a quick look at it and give some recommendations how to make them more intuitive.
> 
> but more than happy to discuss. I'll be in Amsterdam for 10 days from tomorrow, will any of you guys be there?!

Unfortunately nobody from the team will be in Amsterdam. The timing is pretty bad for us.

And yes we do plan to get someone to go over both UX and UI issues of the app.

**Comment by aspiers** [comment]
[**@LefterisJP**](https://github.com/LefterisJP) commented on [April 16, 2022 9:32 PM](https://github.com/rotki/rotki/issues/1144#issuecomment-1100750414 "2022-04-16T20:32:14Z - Replied by Github Reply Comments"):
> Unfortunately nobody from the team will be in Amsterdam. The timing is pretty bad for us.

Ah that's a shame. Hopefully catch you another time!

> And yes we do plan to get someone to go over both UX and UI issues of the app.

Cool, look forward to seeing the results of that :-)
