### ISSUE TITLE
[UI] Accounts & Balances is too long / not navigable

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1145]
The "Accounts & Balances" is long, so it requires a lot of scrolling.  I recommend either breaking it up so that each section ("Blockchain Balances", "Fiat Balances" etc.) becomes an individual page, or at least there should be navigation in the sidebar so that with one click you can jump between sections.

**Comment by aspiers** [comment]
One negative side-effect of this issue is that it's not intuitive to find where to add a new account. Even though it's right at the top, the only indication of this is the "ADD" button which is easily missed.  Also, adding new accounts is not (in the long-term) the most common thing a user would want to do, so it does not make sense to have it at the top of this page taking up a bunch of space.  I suggest hiding the form behind a separate plus icon.  Again it would really be worth getting a UI/UX expert to look at this though.

**Comment by LefterisJP** [comment]
Yes this is something we definitely want to do. That page contains too many things at the moment and also as you said it's too long if you add many accounts.

> Also, adding new accounts is not (in the long-term) the most common thing a user would want to do, so it does not make sense to have it at the top of this page taking up a bunch of space. I suggest hiding the form behind a separate plus icon. Again it would really be worth getting a UI/UX expert to look at this though.

Good point!

**Comment by kelsos** [comment]
One of the ideas is to split the page to sections using tabs like we did we settings and API keys. 

Also recently I was wondering if it makes sense to start moving the edit/add dialogs into modals instead of always displaying the form. And have an Add button that the user can press to open the modal.

**Comment by isidorosp** [comment]
> One of the ideas is to split the page to sections using tabs like we did we settings and API keys.
> 
> I also was wondering recently, if it makes sense to start moving the edit/add dialogs into modals instead of always displaying the form. And have an Add button that the user can press to open the modal as aspiers suggested :)

This is exactly something I've been working on (not code-wise, just thinking it out and doing some mockups by hand). I think it makes sense but also to move the "exchanges" setup into accounts & balances. Basically there would be 1 tab corresponding to each "source" of balances (exchanges, blockchain, manual). If we move the edit/add functionality into dialogs that's also going to make implementing an "omnibox" (like a search box that can navigate you to place / open certain dialogs) a lot easier.

**Comment by isidorosp** [comment]
Hey @aspiers . I've done some work on this in #1160. I'm not sure if you've gotten a dev environment setup and can play with the PR yet or not, but I've also included images in the PR description. Would love some feedback from you since you opened this issue!

**Comment by aspiers** [comment]
@isidorosp Wow thanks, that was quick!  The screenshots in #1160 look great!  I haven't set up a dev environment yet but I should be able to at some point.  How long might it be until this is included in a new release?

**Comment by isidorosp** [comment]
@aspiers if All goes well we plan to release 1.6.0 this week!

cc @LefterisJP , @kelsos

**Comment by aspiers** [comment]
Actually I just managed to set up a dev environment, but that's awesome that 1.6.0 is coming so quickly!

**Comment by aspiers** [comment]
As soon as I figure out how to solve #1187 to import my portfolio via Rotki Premium, I'll be able to test this.
