### ISSUE TITLE
FR: support Bitpanda exchange

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1146]
Selfishly, this would be really helpful to me ;-)  But it's a major exchange so it would benefit other users too.

**Comment by isidorosp** [comment]
@aspiers If you'd like to get your feet wet with this, this is a good PR to draw from:
https://github.com/rotki/rotki/pull/811

**Comment by aspiers** [comment]
Just looking a bit closer at this ... Seems that Bitpanda's API is very simple: https://developers.bitpanda.com/platform/

**Comment by aspiers** [comment]
Any thoughts on which other exchange API this would be most similar to, in order to minimise the amount of work required?  It's vaguely possible I could work on this at some point.

**Comment by LefterisJP** [comment]
All exchanges follow the same interface. You need to implement three main functions. One for balances, one for trades, one for asset_movements (deposits/withdrawals).

Now as to how the exact endpoints look on the side of the exchange it does not really matter. They all are quite different.

**Comment by aspiers** [comment]
Thanks for the info.  Would you recommend writing the tests first, or initially testing against the real API endpoint and then writing the tests after it's better understood how the API works?z

**Comment by LefterisJP** [comment]
100% unequivocally the second. If you have access to API keys you are in a privileged position. At this point when implementing exchanges I am thinking of always asking users for a read-only api key. Makes things so much easier, and the process much much faster.

Main reason being I have not yet seen an exchange whose docs are truthful, or accurate enough.

**Comment by aspiers** [comment]
OK thanks, very useful to know :)

**Comment by afrosamuraiy** [comment]
I would also like the bitpanda API to work with rotki.

**Comment by schamama** [comment]
Bumping this, I would also like the bitpanda API to work with rotki.

**Comment by branciard** [comment]
Bumping this, I would also like the bitpanda API to work with rotki. (personal preferred exchange because PSAN | AMF agreement)

**Comment by inpercima** [comment]
I would also like the bitpanda API to work with rotki. Before knowing about rotki i wrote my own app (https://github.com/inpercima/cryptocheck), but I think rotki is absolutely awesome and the future. :100:

**Comment by LefterisJP** [comment]
Hey @inpercima thanks a lot for the +1 and for the kind words. Also interesting to see how many people want this exchange. We don't ignore you guys. It will be done at some point soon.

> Before knowing about rotki i wrote my own app (https://github.com/inpercima/cryptocheck), but I think rotki is absolutely awesome and the future. 100

Cool! Since you are also a dev we do have a discord chat where there is channels both for users and for developers: https://discord.gg/aGCxHG7

If you are interested in helping out it's all opensource. We would love the help!

**Comment by aspiers** [comment]
@LefterisJP I am still interested in the idea of a pair programming session on this, where someone on the Rotki team guides me through the basics of this, and we record a video in case it can be of help to others who want to hack support for other exchanges.

**Comment by LefterisJP** [comment]
Hey @aspiers I recall. I personally have zero time at the moment for something like this. Perhaps @yabirgb could help with this in the near future as he has already implemented at least one exchange interface.

**Comment by yabirgb** [comment]
@aspiers Yes sure! I might not have perfect knowledge of the codebase but surely enough to help with the implementation. Just ping me in discord whenever you want :)

**Comment by aspiers** [comment]
We chatted in Discord and are hoping to meet up soon :-)

**Comment by magicdude4eva** [comment]
Would be great to include BitPanda as supported Exchange - since it recently raised another $250m and has now a valuation of $4bn it is certainly something one should not ignore.

Thanks for the great software - tested it and immediately signed up for premium.

**Comment by LefterisJP** [comment]
Implement it's a matter of 1 day of concentrated work (probably more if split over various days). I need someone to send me an api key with real data to test. Otherwise implementation is really error prone.

Who can do that? You can DM it in discord: https://discord.com/invite/aGCxHG7

**Comment by magicdude4eva** [comment]
@LefterisJP - I will DM you a Bitpanda API key with read rights.

**Comment by LefterisJP** [comment]
> @LefterisJP - I will DM you a Bitpanda API key with read rights.

Hey thanks a lot! We will not work on it right at this moment as it won't make it into the next release, but the one after the next it's possible. And yes with an API key we can make bitpanda the next exchange to add support for.

**Comment by antonionardella** [comment]
On a note, there is the [Bitpanda](https://bitpanda.com) and [Bitpanda Pro](https://exchange.bitpanda.com) exchange.
One is a broker, the other an exchange.

It would be great to enable both in Rotki and also to be able to read the transactions between the two platforms when one send funds from one platform to the other

I can also spare some API key for both platforms

**Comment by magicdude4eva** [comment]
Thanks @LefterisJP  for the great work - truly amazing working with you and making this happen. Can't wait to see this feature :-)

**Comment by LefterisJP** [comment]
We will probably need a new issue for Bitpanda PRO as it's a different exchange!

**Comment by afrosamuraiy** [comment]
> We will probably need a new issue for Bitpanda PRO as it's a different exchange!

Yes. The exchange is actually the more important one.

**Comment by LefterisJP** [comment]
Please open an issue for it then :)
