### ISSUE TITLE
FR: clicking an asset type should always jump to a page with info about that asset

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1147]
Asset types (e.g. BTC, ETH, fiat, or an ERC20 token) appear in several places, e.g.:

- Dashboard > balance per assets:

![image](https://user-images.githubusercontent.com/100738/87227992-464a3300-c396-11ea-9c52-b2d0f31a1149.png)

- Accounts & Balances:

![image](https://user-images.githubusercontent.com/100738/87228021-64b02e80-c396-11ea-94f6-3470380393ca.png)

If I click on one of these (e.g. USDC) then it should show me a page with info about all my USDC holdings.

**Comment by aspiers** [comment]
I would recommend looking at a few other products to see how the kinds of views they support, and the navigation between them, e.g. https://coinstats.app/en/portfolio - you can definitely steal some good ideas ;-)

**Comment by isidorosp** [comment]
Closely related to https://github.com/rotki/rotki/issues/1111

**Comment by isidorosp** [comment]
We've wanted to do this for a while but there's a few big things that would need to be done before this is possible on the front-end:
* Making all trades available and keeping them updated in the background (right now this is only done upon creation of a Tax Report)
* Grouping all possible "sources" (blockchain, manual, exchange, etc.) by asset in the front-end.

**Comment by LefterisJP** [comment]
Shouldn't this and #1111 be merged?

**Comment by aspiers** [comment]
Yes, sorry for the duplicate.

**Comment by LefterisJP** [comment]
@spolrot also asked for this in #1111

**Comment by LefterisJP** [comment]
This should be fixed by v1.14.0.
