### ISSUE TITLE
[website] "EDIT PROFILE" button should be renamed

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1148]
On https://rotki.com/home/, there is a red "EDIT PROFILE" button.  However "edit" is not really the right word to describe what it does.  It should be "UPDATE PROFILE" or "SAVE" or similar.  The word "edit" is typically used to transition from a read-only or other view into a read-write view, and that's not what it is doing here.

**Comment by LefterisJP** [comment]
Thanks for the feedback @aspiers. I agree that "update profile" sounds better. It's done.

**Comment by aspiers** [comment]
Cool thanks!
