### ISSUE TITLE
Show which Aave assets are also deposited as borrowing collateral

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1166]
## Abstract

At the moment in Aave Rotki assumes all assets are deposited also as borrowing collateral in the borrowing page.

This needs to change as the user can specify which assets to be used as collateral.

There is a call in the aave docs that contains this info (TODO: Fill it in the issue)

## Task

Do it.

**Comment by isidorosp** [comment]
The two aave methods that return `usageAsCollateralEnabled` are:
* https://docs.aave.com/developers/developing-on-aave/the-protocol/lendingpool#getuserreservedata
* https://docs.aave.com/developers/developing-on-aave/the-protocol/lendingpool#getreserveconfigurationdata

**Comment by isidorosp** [comment]
If we move to using a sub-graph as another potential data-source for Aave, it looks like the sub-graph has this detail as well.

https://thegraph.com/explorer/subgraph/aave/protocol

**Comment by LefterisJP** [comment]
We don't need to rely on only one source. We can get from multiple ones. Problem with subgraphs is that it will all eventually need to work only with premium due to the payment part

**Comment by LefterisJP** [comment]
This is not really useful from rotki's perspective, so closing it.
