### ISSUE TITLE
[UI] make icons more self-explanatory with tooltips

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1186]
The icons at the top of the UI are not all immediately self-explanatory.  For example, I could only figure out what the second one from the left did by clicking on it.  Of course, one way of trying to address this might be to tweak the icons.  But probably no matter how good the icons, there will always be people who don't figure out what they all are.  So I think it would be great if a tooltip appeared over every icon when you hover the mouse over it, briefly explaining what clicking that icon does.

**Comment by LefterisJP** [comment]
Hey @aspiers thanks for the issue. By top you mean top right corner?

**Comment by aspiers** [comment]
No I mean both top left and top right.

**Comment by LefterisJP** [comment]
Thanks. I think this may be a good idea. Not sure if it won't crowd it too much but probably it will be fine.

We should schedule this for v1.7.0

**Comment by aspiers** [comment]
Thanks but how would tooltips crowd anything?  They only appear when you hover over the icon.

**Comment by LefterisJP** [comment]
I meant depending on the amount of text. But yes this is probably a non-issue. Disregard :+1:
