### ISSUE TITLE
rename "Allow data sync with Rotkehlchen Server" toggle button

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1193]
There is a toggle button "Allow data sync with Rotkehlchen Server" - I think it should be renamed to "Allow data sync with Rotki Premium" or similar, because people won't know what Rotkehlchen is.  This is also consistent with the rename of the directories and files storing config / state / logs.

Originally mentioned in #1187.

**Comment by LefterisJP** [comment]
In latest develop this was changed to "Allow data sync with Rotki Server" after you feedback in #1187. Do you believe that is sufficient?

**Comment by aspiers** [comment]
Yup sounds good!
