### ISSUE TITLE
Allow forced unidirectional DB syncing for premium

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1194]
[As discussed on Discord](https://discord.com/channels/657906918408585217/683245846070165504/735540973920190576), in the case where Rotki Premium is used for syncing between multiple machines, and somehow the local and online versions of the data are not all in sync, it would be helpful if the user had ways to:

- download the online version of the data and force an overwrite of the local version
- upload the local version of the data and force and overwrite of the online version

These could be buttons in the same place where online syncing is enabled, i.e. API Keys > Rotki Premium.  Of course they would require confirmation dialogs warning the user, so that the user knows exactly what the result of the action will be before they explicitly approve it.

**Comment by aspiers** [comment]
To be *really* safe, the confirmation dialog could require the user to type "Yes I am sure" or similar, to force them to think carefully before approving the force sync.

**Comment by LefterisJP** [comment]
That's a very good point as we discussed in Discord. Scheduling tentatively for 1.7.0 but we will see where it ends up.

**Comment by LefterisJP** [comment]
Should not be super hard. Let's see if I can push it in 1.8.2 (if not then 1.9.0). Wish we had more people to help us go faster :)

**Comment by kelsos** [comment]
@LefterisJP Is this issue only frontend or do we need also changes on the backend?
