### ISSUE TITLE
Can't click on triangle at right-hand side of filter fields

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1198]
There are a bunch filter fields in the Accounts & Balances section which each have a downwards-pointing triangle at their right-hand side.  When clicking in the filter field, a dropdown appears and the triangle rotates 180 degrees to point upwards.  This is nice, but it doesn't work when clicking directly on the downwards-pointing triangle - in that case nothing happens.  This violates standard UI conventions and is confusing (and presumably easy to fix).

**Comment by isidorosp** [comment]
Hey @aspiers, is this on the most recent `develop` branch or the 1.5.0 release?

**Comment by aspiers** [comment]
It's on `develop`

**Comment by isidorosp** [comment]
Reproduced. This is a bug. We are using the same vuetify component that is working elsewhere (e.g. `defi/lending`) so not sure why this is happening.

**Comment by aspiers** [comment]
It might just be some simple CSS issue...
