### ISSUE TITLE
Currency values should include currency symbol

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1199]
In Accounts & Balances, the columns reflecting asset value in fiat are shown as numbers, which means they are not visually distinct from token amounts.  For example if the ETH column showed `100.00` then the "Total USD value of account's assets" column might show something like `26,206.72`, but it would be visually clearer if it had the `$` symbol either before or after the `26,206.72`.

**Comment by LefterisJP** [comment]
@kelsos and @isidorosp what do you think about this?

If we were to take this approach we would need to have the equivalent symbol for each fiat currency the user is using.

**Comment by kelsos** [comment]
That is really easy to do. Sure why not.

**Comment by LefterisJP** [comment]
Hey @kelsos so if this is easy to do can it go in v1.7? Or should I push it?

**Comment by kelsos** [comment]
it should be an easy thing, Do we do that for all the amount-inputs?

**Comment by LefterisJP** [comment]
for all the ones that have fiat values I guess?

**Comment by LefterisJP** [comment]
As discussed in our call moving this to next release
