### ISSUE TITLE
Consider using MetaMask/eth-contract-metadata as source of altcoin data

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1200]
It looks like you are maintaining your own list of altcoins.  You might be able to save some effort by reusing this:

https://github.com/MetaMask/eth-contract-metadata/

although be aware that the maintainers have stated that they will not continue to maintain it going forwards, instead relying on EIP 747.

**Comment by LefterisJP** [comment]
Hey @aspiers there are multiple lists of tokens.

Kleros has one, ethereum lists has one: https://github.com/ethereum-lists/tokens defitracker has one e.t.c.

All these are lists of ethereum tokens only. The rotki list is a list of all crypto and fiat assets. It's not only limited to ethereum. We have disambiguated many tokens by having unique identifier for each token (most of the times it's the symbol except for when the symbol is used by other tokens). And most importantly we maintain mappings of these tokens to each exchange and to each price oracle we communicate with.

Those two last parts and especially the last one is the hardest and why we maintain our own list. We need to source data from other lists from time to time and hopefully make this as automated as possible. There was a first but very imperfect attempt to automate the process of adding tokens by sourcing data from coinpaprika, cryptocompare, and coinmarketcap here: https://github.com/rotki/rotki/tree/develop/tools/asset_aggregator

**Comment by aspiers** [comment]
Sounds good!
