### ISSUE TITLE
Changing local password should come with warning if Premium syncing is enabled

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1201]
In Settings > User & Security, there is an option to change the local account password (or at least I assume it is the local password - I didn't want to risk trying it after my recent password issues!)

Based on my [learnings from #1187](https://github.com/rotki/rotki/issues/1187#issuecomment-662363292), when data syncing across machines via Premium is enabled, presumably this would break the syncing.  So I think there should be a warning about this.

**Comment by LefterisJP** [comment]
That' a very good point and should be easy to handle on the front-end.
