### ISSUE TITLE
Rotki failed to start

### ISSUE THREAD

**Issue by davbre** [rotki/rotki#1209]
## Problem Definition

I start Rotki v1.6.0 (linux AppImage) and get the message:

**The Python backend crashed. Check rotkehlchen.log or open an issue in Github.**

Here's the log output:

```
Rotki Electron Log initialization
2020-07-24T17:53:05.075Z: Determining if we are packaged by seeing if /tmp/.mount_rotki-bzx1WL/resources/rotkehlchen_py_dist exists
2020-07-24T17:53:05.085Z: Starting packaged python subprocess: /tmp/.mount_rotki-bzx1WL/resources/rotkehlchen_py_dist/rotkehlchen-1.6.0-linux --api-port 4242 --api-cors app://* --logfile /home/david/.config/rotki/logs/rotkehlchen.log
2020-07-24T17:53:05.098Z: The Python sub-process started on port: 4242 (PID: 24184)
2020-07-24T17:53:05.797Z: The Python sub-process exited with signal: null (Code: 255)
```

Note that the above info comes from the file rotki_electron.log (as opposed to rotkehlchen.log as per the message).

### System Description
```
Linux tux 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Rotki 1.6.0
```

**Comment by davbre** [comment]
Also the link in the release page https://github.com/rotki/rotki/releases/download/v1.6.0/rotki-linux_x64-v1.6.0.tar.xz returns a 404.
(Posting it here instead of writing another issue.)

**Comment by LefterisJP** [comment]
Hey @davbre thanks for the issue. 

> Also the link in the release page https://github.com/rotki/rotki/releases/download/v1.6.0/rotki-linux_x64-v1.6.0.tar.xz returns a 404.

Thanks for the heads up. Removed it from the release as v.1.6.0 does not have a tar archive.

---

Now about your original problem this is strange. You are getting this right after starting Rotki, and before logging into the user, right?

What does `/home/david/.config/rotki/logs/rotkehlchen.log` say?

**Comment by TechupBusiness** [comment]
I have the same issue here on Ubuntu 18.04. Same Problem and same log file content.

My log file is also named: `rotki_electron.log` (not `rotkehlchen.log` as you requested, there is no file with this name)

```
Rotki Electron Log initialization
2020-07-24T19:17:40.270Z: Determining if we are packaged by seeing if /tmp/.mount_rotki-6SGyoM/resources/rotkehlchen_py_dist exists
2020-07-24T19:17:40.298Z: Starting packaged python subprocess: /tmp/.mount_rotki-6SGyoM/resources/rotkehlchen_py_dist/rotkehlchen-1.6.0-linux --api-port 4242 --api-cors app://* --logfile /home/user/.config/rotki/logs/rotkehlchen.log
2020-07-24T19:17:40.311Z: The Python sub-process started on port: 4242 (PID: 14999)
2020-07-24T19:17:41.113Z: The Python sub-process exited with signal: null (Code: 255)
```

Is there another logfile? 

Yes it happens right after the start:
![image](https://user-images.githubusercontent.com/38460054/88427617-9217c600-cdf3-11ea-91a2-8d38b432bc8a.png)

**Comment by davbre** [comment]
@LefterisJP - when it starts up it says "Connecting to backend" then goes straight to the screen posted by @TechupBusiness.

The file /home/david/.config/rotki/logs/rotkehlchen.log doesn't exist. The folder `/home/david/.config/rotki/logs` contains a single file `rotki_electron.log` , and I posted the contents of that in the original message above.

**Comment by LefterisJP** [comment]
Okay guys thanks. So @TechupBusiness is in Ubuntu 18.04 and you @davbre are in which distro?

I will investigate. Must be something strange with how the binary was built this time. It works in Windows and OSX according to some users who tested and also the Linux appimage works for me in both of my Linux systems. But they are both ArchLinux.

**Comment by davbre** [comment]
As per original message above, it's Ubuntu 18.04 as well:
```
Linux tux 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Rotki 1.6.0
```

**Comment by LefterisJP** [comment]
All right. I don't have an Ubuntu machine to test right now.
So here is the tar archive for the exact same Appimage. https://we.tl/t-wIJj1dDxcq

Can one of you download it, untar it and run the backend on its own?

From the root directory of the untarred object run: `./resources/rotkehlchen_py_dist/rotkehlchen-1.6.0-linux`

Hopefully this will throw an exception and we will see what is wrong.

If all you see is `Rotki API server is running at: 127.0.0.1:5042` then it's running fine.

**Comment by davbre** [comment]
I get the following at the terminal:

<code>
[5540] Error loading Python lib '/tmp/_MEI4zd8hS/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI4zd8hS/libpython3.7m.so.1.0)
</code>

**Comment by LefterisJP** [comment]
All right I think I know what's happening. We used a newer machine in order to generate the binaries this time. And the glibc >= 2.29 requirement must be due to this.

Ubuntu >= 19.04 should work but Ubuntu 18.04 does not have glibc >= 2.29 by default.

Can you try this Appimage and tell me if it works? https://we.tl/t-6OQNCOPafJ

**Comment by LefterisJP** [comment]
I was pretty sure that the problem was the way the binary was generated. So we pushed a very small patch release v1.6.1 out just for this issue (including 2 more small bugfixes). Hopefully it solves your problem guys: https://github.com/rotki/rotki/releases/tag/v1.6.1

Tell me if it works for you. If it does we can close this issue.

**Comment by davbre** [comment]
v1.6.1 works for me. Thanks for the fix!

**Comment by TechupBusiness** [comment]
For me too! Thanks!
