### ISSUE TITLE
If invalid data is provided to the OTC trades menu then don't clear all fields.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1216]
## Problem Definition

As @davbre pointed out in [this](https://github.com/rotki/rotki/issues/1212#issue-665581857) issue if an invalid data entry is provided into a field of the OTC trades menu, then the all fields are cleared.

This should not be happening and only the mistaken field should be cleared.

## Task

- [ ] Identify which field caused the error by parsing the response results. Related: https://github.com/rotki/rotki/issues/1089
- [ ] Clear only the field/s that got the invalid entry/ies and keep the rest

**Comment by isidorosp** [comment]
This should be fixed by #1238 as I totally redid how the validation of the form works there (validation errors are now shown inline on each specific field). Nothing is cleared unless you "close" the add/edit trade dialog.

**Comment by LefterisJP** [comment]
Kelsos should also look at that PR. Just mention the issue in the PR too so that we know this is fixed by the PR. I will also have a look later.
