### ISSUE TITLE
Implement a global searchbox

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1219]
## Abstract

I would love for us to implement a "searchbox" into the top bar for power users. This shouldn't just search for information but also let offer you some pre-determined possible actions (think of the extensions that you could add to firefox's omnibox,

However, this is a lot of work and something that will likely need to be split across multiple versions (not just PRs) as there are a lot of dependencies as well as a possible need to restructure how we organize some "master data" in the front-end.

Some ideas for the feature-set:

Basic:
* Ability to enter the search-box and exit via hotkeys (e.g. `CTRL+/` focuses the searchbox, `Esc` closes it)
* Ability to search to navigate to any page and sub-page in the site
* Ability to search and navigate to any balance "source" (blockchain balances / exchange balances / manual balances) and then pre-filter the relevant page by the relevant query. E.g. typing in "kraken" if I have a connected kraken exchange should take me to the Exchange Balances sub-page with the "kraken" exchange selected.

Slightly more complicated (has dependencies on other features):
* Ability to search and navigate to any account summary page (by account number, account label, chain or account tags)
* Ability to search for any assets that are supported by `rotki`. If it is an asset that we have a balance in, show the overall balance in the asset and then allow clicking enter to take the user to the asset overview page (asset overview page does not exist). If we do not have a balance in it, we can at least show an overall "info" page about an asset (we can get this info from cryptocompare / coingecko / whatnot).
* Basically invoke any action that has to do with creating or editing via the search box as opposed to clicking, e.g. "add a new blockchain account", "add a new connected exchange", "edit a manual balance", etc.
* Allow for quick price lookups (e.g. `price of ETH` --> `306 USD`).

More complicated:
* Ability to search for a setting and change it on the fly via a command-line like interface, e.g.:
Type in "format precision" and you get something like:
`[General Settings] Format Precision: 2`
Going to this entry and clicking enter or "tab" will make the "2" editable and then clicking enter again will save the setting. For more complex settings that can't just be edited like this, clicking enter can take you to the settings page.
* Allow for super-fast currency conversion (since we already have the data), e.g. `what is 302.5 ETH in EUR?` or `what is my <ANY_ASSET> balance in JPY?`

**Comment by LefterisJP** [comment]
It's a nice idea but at the moment a "good to have". If more people ask for this we can consider.

But as you said such a feature would need to also be broken down into multiple subtasks and be implemented gradually. So we should keep this as master issue and create subtasks and prioritize accordingly if we end up doing it.

**Comment by lukicenturi** [comment]
I think the basic abilities listed above is not really hard, I'm gonna try on it @kelsos

**Comment by kelsos** [comment]
For this maybe we can create an issue for the advanced part and closes this since the basic functionality is already implemented. What do you think @lukicenturi

**Comment by LefterisJP** [comment]
Isn't this already done @kelsos ? Can we close?

**Comment by kelsos** [comment]
The basic part of the issue is already done. There are some more complicated suggestions, but they are non-trivial I am not sure if it makes sense to spend time and resources to implement them.
