### ISSUE TITLE
Assure release binaries integrity by providing hashes of produced binaries

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1225]
## Abstract

At the moment there is no way for the users to confirm that the downloaded binary is legit and has not been tampered with. In order to mitigate that we shoudl added hashes of the binaries in the release so that interested users can check the hash against the downloaded binary.

Related:

Sign binaries for OSX with approved certificate: https://github.com/rotki/rotki/issues/1005
Sign binaries for Windows with approved certificate: https://github.com/rotki/rotki/issues/1224

## Task

Add hashes to the produced binaries. A guide containing some nice info is here: https://blogs.itemis.com/en/secure-your-travis-ci-releases-part-1-checksum-with-sha

**Comment by A2be** [comment]
Adding a detail to the requirement for this, that may not be able to be dealt with in a v1.6.2 timeframe so maybe will need to be hived off to later.

Just having the hash for a binary is sufficient for technical users who are hash-educated, github-knowledgeable, and o/s command-level-comfortable to solve the issue.  For me personally, I can get through all those, and "it'll work."

But I'd argue that the requirement, more broadly, for even the non-code- and non-tech-tool-knowledgeable of the rotki users is to try to envision some process whereby **the user can download the hash (in a secure, non-hackable way) and check/confirm the hash against the downloaded binary using some tool or app or mechanism that is easy to use/confirm by non-technical users**, i.e., something not nearly as geeky/technical as the ordinary way that hashes can be checked by the technorati today. 

This seems a problem, and is why many non-technical users of open source code skip the binary security confirmation step; it is simply beyond their capacity to easily accomplish it.

**Comment by LefterisJP** [comment]
There are only two different ways I can imagine this be handled for non-technical users.

(1) We can add a verification guide on our [usage documentation](https://rotki.readthedocs.io/en/latest/usage_guide.html)
(2) For our Windows (#1224) and OSX(#1005) users we need to buy certificated from Microsoft and Apple respectively and sign the binaries with them. This way their respective OS at least tells them that the binary they are going to run is signed with an approved certificate.

**Comment by LefterisJP** [comment]
Hashes are generated and uploaded now. Only thing remaining is to add a docs entry about how a user can verify.

**Comment by LefterisJP** [comment]
@kelsos can you add the doc entry so that we can close this?

**Comment by kelsos** [comment]
For Linux and Mac that should be easy to add, for windows I am not sure

**Comment by LefterisJP** [comment]
Why? There were comments in discord on how to do it. Probably just scroll back and you will see it. Or just google it :smile:

**Comment by kelsos** [comment]
> Why? There were comments in discord on how to do it. Probably just scroll back and you will see it. Or just google it smile

Didn't you have problems with the windows util? and used mingw or something to do that? also I kind of locked out of my VM to test it due to the latest kernel update.

**Comment by LefterisJP** [comment]
See you also got 2 options. Both mingw and the windows util. No I did not fail using the windows util. It just was adding spaces between bytes which for an automatic script did not work nicely. But with the eye you can confirm it's correct, which is enough for a doc entry.
