### ISSUE TITLE
Application Menu on OSX does not show the "Get Rotki Premium" button

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1226]
## Problem Definition

After logging in, if the user is not a premium user the application menu should be re-drawn to show a "Get Rotki Premium" button. On Windows and Linux this appears to work, but not on OSX. Figure out what's going on.

![image](https://user-images.githubusercontent.com/27592/88588634-297d5300-d058-11ea-855c-cf057f33a822.png)

**Comment by isidorosp** [comment]
@CPatchane You're on developing on OSX right? I know perhaps this issue isn't immediately appealing but is there any chance you could look into this one?

As a starting point, you would have to do some digging in `background.ts` on this one.

**Comment by CPatchane** [comment]
@isidorosp I can a look into it, thanks for the context here, do you have a screenshot of what should be the correct display here?

**Comment by isidorosp** [comment]
> @isidorosp Yes, I can a look into it. Thanks for the context here, do you have a screenshot of what should be the correct display here?

Sure I can show you what it looks like on Windows for example.

Before a user logs in, this is what the appbar looks like
![image](https://user-images.githubusercontent.com/27592/89945695-09d25700-dc22-11ea-8ebd-68e091059002.png)

If a user _without_ premium logs in, this is what the appbar looks like after login (the" Get Rotki Premium" button has been added)
![image](https://user-images.githubusercontent.com/27592/89945875-55850080-dc22-11ea-9197-54b9d2b84add.png)

**Comment by CPatchane** [comment]
@isidorosp Your guess was right, it seems that we can't draw a menu item without providing the submenu array (an empty array will give a menu showing `(empty)`). I can't find something about that behaviour in the documentation but I guess it's an OSX limitation here to avoid redirecting from an app bar item.

So I guess the best we can get here should be something like:
<img width="285" alt="Screenshot 2020-08-11 at 22 59 16" src="https://user-images.githubusercontent.com/10224453/89948469-794a4580-dc26-11ea-96bd-69990dbd8f0f.png">
