### ISSUE TITLE
Make the distinction between website account and local account clear

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1239]
## Problem Definition

A problem that we have been seeing quite a lot is that a lot of users mix up the two different account types that they need with Rotki.

1. The local Rotki account, saved in their desktop
2. The website account whose only reason for existence is to buy and manage a premium subscription

We have added warnings prevent people from getting confused about them. 

1.There is a warning at the website account creation.
![2020-07-30-002315_767x244_scrot](https://user-images.githubusercontent.com/1658405/88859888-f58e6300-d1fa-11ea-9274-6fabc88bf006.png)
2. There is an info window at the application's welcome screen
![2020-07-30-002426_687x151_scrot](https://user-images.githubusercontent.com/1658405/88859955-15be2200-d1fb-11ea-9b89-246c358b1b5f.png)

### Terminology

Discord user Cantillon suggested that one of the reasons that probably lead users to confusion is overloading of the same terms `username` and `password` for two very different things.

He suggests that we should consistently use different terms for these two things. This will lead to users not mixing them and at the very least understand we are talking about two different things.

> For example:  maybe "Premium ID" and "Premium website access code"
to leave uname/pw for the app.
>
>Or, vice versa, maybe "Local ID" and "Encryption key" on the app, 
to leave the uname/pw available for your (very standard and typical) website access, that only does the one thing: pay for premium subsctiption.
>
>To be even more clear, and since some users might have >1 Rotki database they intend to keep on their local machine, maybe:
"local DB ID" and "DB encryption key"

### Restrict Website account Creation to only via the APP

@isidorosp had another suggestion. Essentially hide links to account creation so that the user is not able to register at the website by just visiting it.

And to allow account creation only from an iframe inside the application.

## Agreed on approach

TODO: After discussion has concluded the approach should be described here.

## Task

- [ ] Think about, discuss and hone in on a good solution to this problem
- [ ] Execute it

**Comment by LefterisJP** [comment]
I think that removing the "Register" button from the website does indeed make a lot of sense.

There is no user flow where the user should just go to register in the website without actually wanting to buy a premium subscription. am not sure about restricting account creation to the application. But that button should probably go away.

![2020-07-30-003206_700x84_scrot](https://user-images.githubusercontent.com/1658405/88860879-050eab80-d1fd-11ea-93d3-cf19aa500f8a.png)

Then after the user downloads and uses the application he presses "Get Premium", goes to the [products page](https://rotki.com/products/) and there he sees a link to sign in or register. And that should be good enough.

![2020-07-30-003906_830x179_scrot](https://user-images.githubusercontent.com/1658405/88860941-27a0c480-d1fd-11ea-8880-b213ce4f0ce7.png)


I also like the terminology suggestions but that would mean a bit more work. Removing the "Register" button from the front-page sounds like the biggest win we can have with the least amount of effort.

**Comment by LefterisJP** [comment]
@aspiers you have given us very nice feedback on the application and I would be really interested to hear your opinion on this ^

@kelsos when you come back from vacation please also chime in.

**Comment by isidorosp** [comment]
> I think that removing the "Register" button from the website does indeed make a lot of sense.
> 
> There is no user flow where the user should just go to register in the website without actually wanting to buy a premium subscription. am not sure about restricting account creation to the application. But that button should probably go away.
> 
> ![2020-07-30-003206_700x84_scrot](https://user-images.githubusercontent.com/1658405/88860879-050eab80-d1fd-11ea-93d3-cf19aa500f8a.png)
> 
> Then after the user downloads and uses the application he presses "Get Premium", goes to the [products page](https://rotki.com/products/) and there he sees a link to sign in or register. And that should be good enough.
> 
> ![2020-07-30-003906_830x179_scrot](https://user-images.githubusercontent.com/1658405/88860941-27a0c480-d1fd-11ea-8880-b213ce4f0ce7.png)
> 
> I also like the terminology suggestions but that would mean a bit more work. Removing the "Register" button from the front-page sounds like the biggest win we can have with the least amount of effort.

I think this is a good direction. How about something like this: Remove "Register" and "Sign In" and replace them with "Manage Premium" button that we move off to the side instead of located centrally with the rest of the links. Then on that page (which is basically a "Log In to Rotki Premium" page and also has a link to "Create Premium Account") we try to make it a bit more clear that this is for signing into the Rotki Premium account, and a brief explanation/alert of what the difference between the two accounts is. Especially that:
a) Creating a Premium Account before having a local account is not immediately useful
b) The details of one accounts cannot be used to log in to the other, etc.
We can work on creating a different set of terms here to avoid "overloading" of terms like Cantillon suggested. However I would suggest not calling the local password "encryption key". Right now it _happens_ that the local password is also the encryption key, that may not necessarily always be the case (especially if we move to something where like you can use a DID to create an account, the key used for the encryption of data may be something else -- e.g. a specific signed response, or we could use DID details to create a public/private key encryption mechanism).

**Comment by aspiers** [comment]
I think I agree with everything suggested so far.  Great work!  "Premium ID" makes sense, and "Premium website access code" could be shortened to "Premium access code" as it should not be tied exclusively to the website long-term.

See also [#1242 (Clarify local password requirement when setting up 2nd, 3rd, ... machines for Premium syncing)](https://github.com/rotki/rotki/issues/1242).

I also agree with @isidorosp's point that it's probably worth allowing for decoupling the local password from the encryption key at a later date.  This could potentially help with #1242 although I'm not yet convinced about that.

**Comment by LefterisJP** [comment]
I made some of the suggested changes and deployed them in the website: https://rotki.com/

* Removed Register Button. It's now Manage Premium.
* Added descriptive texts to both login and sign up pages and changed the naming so that it always mentions Premium account and not just account.

![2020-08-09_11-19](https://user-images.githubusercontent.com/1658405/89729054-522b2280-da32-11ea-819d-5a7c920bae32.png)

![2020-08-09_11-19_1](https://user-images.githubusercontent.com/1658405/89729058-58210380-da32-11ea-9de3-33a4541c6e05.png)

**Comment by lullis** [comment]
Why is the local account needed at all in the first place? All of the target desktops are based on multi-user operating systems.

**Comment by LefterisJP** [comment]
> Why is the local account needed at all in the first place? All of the target desktops are based on multi-user operating systems.

Because you may want to have multiple users per OS. Plus the password prompt will be there. Users need to encrypt the DB with something.

**Comment by lullis** [comment]
> Because you may want to have multiple users per OS. 

Yeah, but each user running rotki will get their data stored on their own home partition, right? Maybe what you mean is that each user will want to have multiple profiles for tracking different things - like personal finances vs their business?

If that is the case, perhaps it would be simpler to have an UI like Firefox? Every user gets a default profile, and those that want to have more than one database can define at settings via a flag.

> Users need to encrypt the DB with something.

That leads to more questions... :)

If the main purpose of Rotki is to *track* information and analyze public data, then what is exactly that needs to be secured at the database? Everything that I've used so far did not require any private key. Is there anything that can only be tracked if the user provides any kind of private keys?

**Comment by LefterisJP** [comment]
> If that is the case, perhaps it would be simpler to have an UI like Firefox? Every user gets a default profile, and those that want to have more than one database can define at settings via a flag.

That's a good idea. Could you perhaps make a new issue for this? I think we can pursue this.

> If the main purpose of Rotki is to track information and analyze public data, then what is exactly that needs to be secured at the database? Everything that I've used so far did not require any private key. Is there anything that can only be tracked if the user provides any kind of private keys?

Ofcourse! Your entire data history, which accounts you own, public or not, which transactions you made. Once someone gets a hold of your account they will know how much you have and where.

As for keys, yes all of the API keys to contact exchanges are stored in the DB, API keys for external services, API for rotki premium etc.

**Comment by lullis** [comment]
> Your entire data history, which accounts you own, public or not, which transactions you made. Once someone gets a hold of your account they will know how much you have and where.

I am not sure I understand the threat model. If somebody can get access to my laptop, it's game over anyway. Any rootkit or keylogger could capture the password and would break the encryption. For the case where the user's laptop can be stolen (I believe) all modern desktops provide ways to encrypt their home partition or at least to provide an encrypted folder, so we are again at the point where password protecting the database is redundant.

Also, another line of defense available in current OS is to have a keyring that you can use to store secrets. It is also reasonably easy to integrate with the [user's keyring with python in an OS-agnostic way](https://pypi.org/project/keyring/).

What I am trying to say is that, while is nice you are trying to provide this functionality you might be giving yourself more unnecessary work (securing user data in their devices) that can be delegated to better and more capable tools.

**Comment by LefterisJP** [comment]
The database can also backed up outside of the user's machine. Having it password protected provides an extra layer of protection. For premium users it's also optionally synchronized between devices. If it was not encrypted it's trivial to read when stored in our servers.

With this kind of thinking we should not have JSON keystore files for accounts that are password encrypted and just store private keys on disc and just encrypt home partition.

We provide maximum protection for our users regardless of their OS security settings.

Thanks for the feedback. I appreciate the discussion but the encryption of the DB is not up for discussion and I would like to not get off-topic.
