### ISSUE TITLE
Clarify local password requirement when setting up 2nd, 3rd, ... machines for Premium syncing

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1242]
As per #1187, it is currently a little too easy to miss the fact that when setting up more than one machine with Premium syncing between them, the local password needs to be the same on each since it's (currently) used as the local storage encryption key.

When creating a new account, there is an `Enable Premium` checkbox, with a tooltip next to it which warns that the password needs to match the one from the original machine, but this is way too easily missed.  I suggest that this warning is moved to be immediately under the password field.

Another reason for moving this is the user might not even notice the `Enable Premium` checkbox, and assume (correctly) that they can set up Premium later, after creating the account (which they can, in the API Keys panel).

See also #1239.

**Comment by kelsos** [comment]
Adding it as a hint if enable premium is checked should certainly work. Thanks for the suggestion :)

**Comment by aspiers** [comment]
I think the hint needs to be there even when premium isn't *checked*:

>  I suggest that this warning is moved to be immediately under the password field.
>
> Another reason for moving this is the user might not even notice the Enable Premium checkbox, and assume (correctly) that they can set up Premium later, after creating the account (which they can, in the API Keys panel).

**Comment by LefterisJP** [comment]
I believe @kelsos addressed this issue with https://github.com/rotki/rotki/pull/1291.

If that assumption is mistake please re-open the issue and clarify what's missing.

**Comment by aspiers** [comment]
I believe it's a mistake.  This issue is about account creation, whereas AFAICS #1291 only addresses password changes.  I don't have access to re-open this however.

**Comment by LefterisJP** [comment]
@aspiers Hmm then we have misunderstood what you need. Isn't that warning enough in your opinion?

**Comment by aspiers** [comment]
I haven't tried to run the latest code recently so I don't know if the account creation UI has changed to address this, but IIUC #1291 does not touch the account creation UI?

**Comment by LefterisJP** [comment]
No it does not. But what would you like to see in the account creation. Same kind of warning if the user tries to include premium credentials in the new account creation?

**Comment by aspiers** [comment]
I think the existing hint is probably fine but it needs to be visible even when premium isn't *checked*, which is why I wrote: 

> I suggest that this warning is moved to be immediately under the password field.

**Comment by isidorosp** [comment]
We just added yet another warning under the create new user password box https://github.com/rotki/rotki/pull/1312 . At this point we're going to end up with a paragraph of text and a dialog that *has* to scroll in order for a user to create an account which is not very nice UX. Can we come up with a better way of doing this? Should we enlarge the dialog and/or move things around?

**Comment by LefterisJP** [comment]
> I think the existing hint is probably fine but it needs to be visible even when premium isn't checked, which is why I wrote:

Some times communication through github is hard to comprehend :sweat_smile: 
Let me see if I understand what you want to say.

You say that you would like to see the exact same thing that #1291 does but not have it shown only if the user has premium + sync enabled, but instead always show it? So also to: (1) free users (2) premium users without sync enabled.

Why? what does that achieve? Especially for (1). For (2) I can perhaps maybe see that this can be useful if at any point you try to enable syncing in the future or any other copy of your account in another machine has premium sync enabled and this one does not.

**Comment by aspiers** [comment]
[**@LefterisJP**](https://github.com/LefterisJP) commented on [August 11, 2020 4:21 PM](https://github.com/rotki/rotki/issues/1242#issuecomment-671976441 "2020-08-11T14:21:11Z - Replied by Github Reply Comments"):
> > I think the existing hint is probably fine but it needs to be visible even when premium isn't checked, which is why I wrote:
> 
> Some times communication through github is hard to comprehend ![sweat_smile](https://github.githubassets.com/images/icons/emoji/unicode/1f605.png)  
> Let me see if I understand what you want to say.

No worries, yes it can be hard and I'm sure we'll get there ;-)

> You say that you would like to see the exact same thing that [#1291](https://github.com/rotki/rotki/pull/1291) does

No, #1291 is about password changes but this issue is completely unrelated to password changes and is only concerned with account creation.  They are totally different things.  The only thing they have in common is the goal of helping users avoid getting into the situation where they are attempting to sync multiple machines but have a different local password.

When I wrote "the existing hint" I was talking about the one hidden under the `(i)` icon to the right of `Enable Premium`.

> but not have it shown only if the user has premium + sync enabled, but instead always show it?

Ideally we wouldn't *always* show it.  E.g. to avoid confusion from clutter when the account creation view is opened, it could only be visible when the password fields are being edited (i.e. in focus).  Or perhaps the flow could be reordered (see below).

> So also to: (1) free users (2) premium users without sync enabled. Why? what does that achieve? Especially for (1).

Ideally not to (1). 

> For (2) I can perhaps maybe see that this can be useful if at any point you try to enable syncing in the future or any other copy of your account in another machine has premium sync enabled and this one does not.

Yes exactly, or like I said the user might not even notice the `Enable Premium` checkbox because it's below the password fields.  It's safe to assume that most people will read from top to bottom.  So they fill in the Username and Password fields, **by which time the mistake may have already been made.  At that point the current UI has no way of knowing whether the user wants to run Rotki on more than one device.**  That is the underlying problem.

So maybe a better solution is to change the flow: firstly ask the user up front whether they are setting up their first machine, or have already set one up and this is another one.  That could be done with a question like "Is this your first Rotki device?" or "Have you already set up Rotki on another device?" and radio buttons, and hiding the username/password fields until that question is answered.  If they have already set up another device, then *before* displaying the username/password fields you can explain that Premium is the only way to sync devices and ask if they want to use Premium.  If they say they do then you can explain *above* the password fields that they need to make the passwords match.

**Comment by LefterisJP** [comment]
Hey @kelsos We have been moving it from release to release. Do you think it would be a lot of work to do the suggestion by @aspiers in the 2 paragraphs of the last comment above?
