### ISSUE TITLE
Hide "Get Rotki Premium" when Premium is enabled at the same user session

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1243]
After entering the correct API key/secret and enabling data sync, the menu bar still displays "Get Rotki Premium".  To a paid-up user this can be a minor annoyance because it feels like superfluous marketing for something which has already been paid.  So ideally that menu item should just be hidden after Premium is activated.

**Comment by LefterisJP** [comment]
Hmmm this should be hidden normally @aspiers if you are a premium user. Which operating system and version do you still see it in?

**Comment by isidorosp** [comment]
I think the menubar is only update on "logon" (and not during the session if someone connects premium). In other words, the next time you log on this button shouldn't still be there. 

To fix this, it's probably easy to do (just need to set up a new IPC event from renderer to the main process in Electron that will trigger a menu refresh).

**Comment by aspiers** [comment]
Confirming that after restarting it is gone.
