### ISSUE TITLE
Replace Alethio for auto-detection of user tokens

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1251]
## Problem Definition

Currently we are using Alethio to auto-detect which tokens a user owns. If we don't use that, we require users to input tokens to track across all accounts.

Alethio [is shutting down](https://medium.com/alethio/the-future-of-alethio-c4fd511e4c03). They will operate their API until 2020 so we have some time but we need to find a replacement method to auto-detect tokens that the user owns.

### Query Ethscan contract

We can batch queries to the [Ethscan](https://etherscan.io/address/0x86F25b64e1Fe4C5162cDEeD5245575D32eC549db#code) contract per address. We already use it to batch ether balance queries.

The algorithm would look like this in super rough pseudocode:
```
token_addresses = get_addresses_of_supported_ethereum_tokens()
for address in user_addresses:
    result = eth_scan.tokensBalance(tokensBalance(address, token_addresses)
    balances = [x for x in result if x.balance != 0]
```

Depending on the amount of addresses we query we may reach the block gas limit so we should split the above into additional batches if the block gas limit is reached. Mycrypto already does this in their [wrapper](https://github.com/MyCryptoHQ/eth-scan) over the contract.

So this would require: `number_of_splits_of_all_token_addresses` * `number_of_user_addresses` queries. Which is not that bad and would help us get rid of alethio completely.

## Task

- [ ] Figure out the approach (Possibly just go with ethscan batching)
- [ ] If the solution is good enough and universal, remove the owned tokens component and the multiple ways of querying for the user's tokens.

**Comment by LefterisJP** [comment]
There is another reason to prioritize this faster. Seems that aleth.io is providing wrong/old token balances for some addresses/token addresses combinations.

Got one such report by a user and confirmed the problem is aleth.io. Offending token was `WETH`.

**Comment by TripleSpeeder** [comment]
I think I have the same issue with WETH. Rotki still shows me an old balance for WETH, although i have unwrapped them 2 days ago and have 0 balance left.

**Comment by LefterisJP** [comment]
That's 3 users affected. So far seems only `WETH`, but this is already bad enough to include the work in the next patch release.
