### ISSUE TITLE
Include entries in the documentation for needed API key permissions per supported exchange

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#1252]
Assume one is trying to set up an `Exchange API Key` to have Rotki connect with exchange data.

In order to fill out the requested info on one exchange's "**New API Key**" page, one must give specific "Permissions" for just what capabilities and limits on the API data are desired.  I would suggest **Rotki clarify in help text** somewhere which ones, or at minimum, which general classes of permissions, are required to make all Rotki_app functions work wrt obtaining data from an exchange via the exchange API.  (I looked, but cannot find this in existing doc or help info.)

Here's the list of ~34 that a "non-technical user" must wade through, and select yes or no on, for just one exchange, in order to obtain an API key:
```
API v2 permissions

wallet:accounts:create
wallet:accounts:read
wallet:addresses:create
wallet:buys:create
wallet:checkouts:create
wallet:contacts:read
wallet:deposits:read
wallet:orders:create
wallet:orders:refund
wallet:payment-methods:limits
wallet:sells:create
wallet:supported-assets:read
wallet:trades:read
wallet:transactions:request
wallet:transactions:transfer
wallet:user:read
wallet:withdrawals:create
wallet:accounts:delete
wallet:accounts:update
wallet:addresses:read
wallet:buys:read
wallet:checkouts:read
wallet:deposits:create
wallet:notifications:read
wallet:orders:read
wallet:payment-methods:delete
wallet:payment-methods:read
wallet:sells:read
wallet:trades:create
wallet:transactions:read
wallet:transactions:send
wallet:user:email
wallet:user:update
wallet:withdrawals:read
```

**Comment by LefterisJP** [comment]
Each exchange has different permissions list. The coinbase permissions are unfortunately the least user friendly. Normally we need all the "query/audit permissions. We don't act on your behalf. Never do trades or anything.

```
            msg = (
                f'Provided Coinbase API key needs to have {permission} permission activated. '
                f'Please log into your coinbase account and set all required permissions: '
                f'wallet:accounts:read, wallet:transactions:read, '
                f'wallet:buys:read, wallet:sells:read, wallet:withdrawals:read, '
                f'wallet:deposits:read, wallet:trades:read'
            )
```

This is in the code. So all "read permissions"

But perhaps you are correct. We could have a guide per-exchange on what permissions each exchange needs.

**Comment by A2be** [comment]
Thanks for the quick answer.  That'll solve my problem in using Rotki.

I do agree it is a good idea for you to add a bit of doc, perhaps behind one of those stylized letter "i" icons, for info.  Or whatever other line-specific help icon should be used.  And make its content a function of which pulldown "Rotki supported exchange" one has selected.

**Comment by A2be** [comment]
BTW, closing the loop for you and Rotki doc wrt Coinbase: I enabled ALL of the Coinbase permissions that had "read" on the end. 
 That was 15 of the list of ~34 permissions and got a custom key to match those permissions; I also IP limited it just to reduce the attack surface errors were made. (I realize I'll have to update this if/when my ISP rolls my IP address.)
