### ISSUE TITLE
How to remove OCEAN from unsupported Bittrex assets?

### ISSUE THREAD

**Issue by TimDaub** [rotki/rotki#1279]
OCEAN token is currently on rotki's [`UNSUPPORTED_BITTREX_ASSETS`](https://github.com/rotki/rotki/blob/a37d9556d3efbcaf785499febf6b7ad6979da126/rotkehlchen/assets/converters.py#L349-L352). In #1237, I've added it to `data/all_assets.json `.

May I simply remove its entry from `UNSUPPORTED_BITTREX_ASSETS`? Since 02/05/2019, lots of new information has been added to the token. The project is still alive:

- https://coinmarketcap.com/currencies/ocean-protocol/
- https://www.coingecko.com/de/munze/ocean-protocol
- https://oceanprotocol.com/
- https://blog.oceanprotocol.com

**Comment by LefterisJP** [comment]
Yes you can definitely remove it. Cryptocompare supports it and has historical price data.

Should go through those unsupported assets for each exchange at some point and see what else we can find data for. If only we had more resources :smile:
