### ISSUE TITLE
Save Indicator should display that last sync date (if premium sync is enabled)

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1288]
## Abstract

In the case that a user has premium and premium sync is enabled, the save indicator should display the last sync date in addition to the last save date. Currently sync failure is in the logs but does not clearly show up in the app anywhere (e.g. alert/notification/etc), so this would be a good way to help users identify that there may be a sync issue.

**Comment by kelsos** [comment]
@LefterisJP does this also require changes in the backend?

**Comment by LefterisJP** [comment]
Last sync date here would mean when we pushed a new copy of the DB to the server? Or when the server's copy was last modified? We would definitely need some small change to add this but should not be hard.

**Comment by kelsos** [comment]
I would say last time we pushed on the server

**Comment by LefterisJP** [comment]
I agree. This is the `last_data_upload_ts` in the settings then. It's already there.

**Comment by kelsos** [comment]
> I agree. This is the `last_data_upload_ts` in the settings then. It's already there.

Great I will have a look

**Comment by kelsos** [comment]
@LefterisJP would it make sense for this field to also be in the periodic change data?

**Comment by LefterisJP** [comment]
I don't see why. It would only change once at start

**Comment by kelsos** [comment]
> I don't see why. It would only change once at start

That was the crucial information I was missing, that why I asked that :) thank you

**Comment by kelsos** [comment]
> Hey @kelsos I was wrong above. This was for pulling data. for pushing data it can happen once every hour.

OK, so I also have to add it to the periodic check thanks.
