### ISSUE TITLE
Change tooltips in Notification Dropdown to active imperative mood

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1289]
## Abstract

Currently the tooltips describe what clicking the button does as opposed to the action the user will perform by clicking the button. Let's update these so that it's in line w/ the rest of the application and common UI/UX guidelines.

Clears all notifications -> Clear all notifications
Dismisses notification -> Dismiss notification
Copies the notification... -> Copy notification...

**Comment by LefterisJP** [comment]
Definitely don't disagree with doing it. What you suggest does feel better, but do you have any link to these common UI/UX guidelines?

**Comment by isidorosp** [comment]
I'm not sure if there is 1 document we can refer to for all these things, it's just commonly encountered up in various in guidelines around usage of tooltips that they should be concise and, if entail an action, to use the present imperative when possible (examples): https://www.appcues.com/blog/tooltips, https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-tooltips-and-infotips
