### ISSUE TITLE
For tax report, mix of delimiters can happen

### ISSUE THREAD

**Issue by TimDaub** [rotki/rotki#1290]
When generating a tax report, the interface can sometimes show a number like this:

`2345,678.90`

Can happen for:

- General Trade Profit Loss
- Taxable Trade Profit Loss
- Total Taxable Profit Loss
- Total Profit Loss

**Comment by LefterisJP** [comment]
Oh that's interesting. Thanks a lot for the report @TimDaub 

Can you confirm this was seen in develop? Or did you try with v1.6.1?

Hey @kelsos could this be due to what you discovered where we did not use the proper component in the frontend in the tax report?

**Comment by TimDaub** [comment]
> Can you confirm this was seen in develop? Or did you try with v1.6.1?

It happened in develop. Additionally, these errors popped up:

```skipping action at 15/05/2019, 11:08:52 during history processing due to inability to reach an external service at that point in time: Failed to query cryptocompare
```

Not sure they're related...

**Comment by LefterisJP** [comment]
No this is not related @TimDaub I can also confirm this. Cryptocompare is having server trouble right now. We can't do anything about this and we don't yet support querying data from coingecko (it's in the pipeline: https://github.com/rotki/rotki/issues/224) so you will have to wait with this until their servers are okay again.

**Comment by CPatchane** [comment]
Will this issue be fixed by the PR #1269 ?

**Comment by LefterisJP** [comment]
I think it will. Isn't that right @kelsos? Since the proper compoent is also going to be used in the tax report too.

**Comment by CPatchane** [comment]
I guess this is now fixed?

**Comment by LefterisJP** [comment]
yes this should be fixed. But let me add a changelog entry.
