### ISSUE TITLE
Add check for login name contaning only alphanumeric characters on sign up page

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#1297]
## Problem Definition
I signed up on `https://rotki.com/signup/` with login something like `]0A,1M6K#3` and it went fine, but loging into the desktop app gives me an error:
`A username must contain only alphanumeric characters and have no spaces`
<img width="462" alt="Screen Shot 2020-08-08 at 5 15 03 PM" src="https://user-images.githubusercontent.com/15807643/89722141-6db41000-d9d5-11ea-981e-a977f01b64eb.png">

No way to change login in in dashboard, so i have to delete and recreate account again.
Presumably the same criteria should be used when signup and login.

**Comment by LefterisJP** [comment]
@CruiseMan Thank you for trying Rotki out. This is unfortunately a common misconception that people get which we have to address. The website account is not needed and it's not the same as the local account. The only reason you need to make an account in the website is to buy the premium version.

For more info and for ways we are trying to make the distinction clearer for users check: https://github.com/rotki/rotki/issues/1239
