### ISSUE TITLE
Large numbers appear in exported trades.csv

### ISSUE THREAD

**Issue by TimDaub** [rotki/rotki#1302]
Currently, I'm creating tax reports for a specific year. One of the exchanges I'm using is Bittrex.
Rotki presents me with a usable output after generation. However, some of the values in the exported trades.csv file are most likely wrong, as I'm haven't traded these large amounts. Here is an example:

type | location | asset | price_in_EUR | fee_in_EUR | gained_or_invested_EUR | amount | taxable_amount | exchanged_for | exchanged_asset_EUR_exchange_rate | taxable_bought_cost_in_EUR | taxable_gain_in_EUR | taxable_profit_loss_in_EUR | time | is_virtual
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
sell | bittrex | USD | 23475264.75 | 8462.169168 | 8559476.693 | 0.04320853 | 0.04320853 | BTC | 9573.475 | 0 | 8365895.524 | -8563.475 | 14/05/2019 22:43:33 | FALSE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

(numbers are scrambled)

There are other assets where prices seem incorrect too. I'm happy to share more examples privately somehow. For now, it looks like this has specifically to do with the Bittrex exchange.

**Comment by LefterisJP** [comment]
Hey @TimDaub can you find and send me the corresponding log entry from rotkehlchen.log to see the bittrex format of the trade?

**Comment by LefterisJP** [comment]
You can also do so in Discord in a pm. https://discord.gg/aGCxHG7

**Comment by TimDaub** [comment]
Hey, I tried the fix in develop at f399fe9fafcad0407c8782c0b538183a05396f4a
Unfortunately, it did fix the error. I still get this very large result for that particular row...
