### ISSUE TITLE
Display all user ethereum transactions in a single UI component

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1310]
## Abstract

Much like #1085 for trades we need a component where the user can navigate through all of their ethereum transactions per address.

This component would have a filter per address and a filter for a given time range.

Each row would also have the ability to be identified as a particular transaction. For example beloging to uniswap, makerdao, compound e.t.c.

Addresses would be replaced with their labels if we have any. Token addresses should be autodetected and displayed.

Users should be able to have an address book. In there they would name certain addresses (they would not be tracked) and then these addresses would appear with the name instead of the hexadecimal in the transactions list. Rotki will also have its own address book with the most common/well known addresses.

This could either be fully a premium feature or partly premium. Partly would work by limiting the number of transactions shown or by having zero annotations or ability to annotate. Probably both limitations would make sense for non-premium users.

## Task

- [ ] Create an endpoint to query the backend for all ethereum transactions of all addresses or per address.
- [ ] Create the frontend component as described above.

## Related issues

- Periodically query this information instead of all at once - https://github.com/rotki/rotki/issues/968
- Better caching of ethereum tx in the DB - https://github.com/rotki/rotki/issues/1309

**Comment by A2be** [comment]
Yes!  I'm totally uninterested in DeFi, but just doing this on old addresses that have had, on occasion, some activity in years going back to Ethereum 2016 would be super helpful.
