### ISSUE TITLE
Look for and set watchers for DeFi protocols that offer best APY/APR per asset.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1317]
## Problem Definition

Sometimes it's hard to keep up with what's changing in the different offerings and opportunities of DeFi protocols. Where can I get the best APR/APY for my assets right now?

## Solution

We can offer, for our premium users, a watching service that knows the assets they have (in DeFi, in blockchain accounts, in exchanges) and tries to see in which protocols the user can get the best rate at any moment.

User can access this service by a special component in the UI listing the best places they can earn a return per asset they own and how much that would be.

Also in the same place user can set a watcher for a particular asset that would email them when there is a considerably big change in the offered APY/APR for that asset. Say a new opportunity popped up where they can earn +25% APY on the asset while they are only getting 3% right now.

Idea got prompted by [this](https://twitter.com/lemiscate/status/1293256463704641536) tweet.

## Task

- Write backend specification
- Write frontend specification

**Comment by isidorosp** [comment]
Aren't there defi protocols that in theory move your assets around to get the best yield at any point in time? I think that's yearn is supposed to do? Still it would be nice because it would be nice for us to show all different yields across all the different protocols as well, and yearn doesn't support all protocols anyway.

**Comment by LefterisJP** [comment]
> Are there defi protocols that in theory move your assets around to get the best yield at any point in time? 

yeah there is some. Same way as DeFi saver automates with their strategy minting DAI and repaying it. But these are imo super risky, on top of risky protocols, on top of a risky blockchain. Plus they cover only a fraction of the choices, do that for few assets.

I personally like doing these things myself and don't trust the automation and the additional risk. I am sure users would like to also have the choice to do the same and would appreciate a tool that helps them do that.

**Comment by LefterisJP** [comment]
We could actually utilize defi lamma for this: https://defillama.com/yields

They will open an api for these yields. This is what one of their devs told me:

> we don't have a public api (we just launched and atm apis are pretty unstable, so waiting for some stability to open them), but if you are okay with using an api that might just break some day you can use https://1rwmj4tky9.execute-api.eu-central-1.amazonaws.com/poolsEnriched

**Comment by LefterisJP** [comment]
This is pretty much what the folks at https://defillama.com/yields do and they do it greatly. No point going there.
