### ISSUE TITLE
csv export formulae need updates

### ISSUE THREAD

**Issue by davbre** [rotki/rotki#1321]
Rotki v1.6.2

With the addition of 'Location' to the csv export, I believe some of the formulae need updating. For example:

https://github.com/rotki/rotki/blob/4e1d6050b65dece9f002608fe738b09c5fb2b773/rotkehlchen/csv_exporter.py#L229

I think references to columns K and J should be to L and K, i.e.:

`taxable_profit_formula = '=IF(G{}=0,0,L{}-K{})'.format(row, row, row)`

Other examples:
https://github.com/rotki/rotki/blob/4e1d6050b65dece9f002608fe738b09c5fb2b773/rotkehlchen/csv_exporter.py#L104
https://github.com/rotki/rotki/blob/4e1d6050b65dece9f002608fe738b09c5fb2b773/rotkehlchen/csv_exporter.py#L107
https://github.com/rotki/rotki/blob/4e1d6050b65dece9f002608fe738b09c5fb2b773/rotkehlchen/csv_exporter.py#L110
https://github.com/rotki/rotki/blob/4e1d6050b65dece9f002608fe738b09c5fb2b773/rotkehlchen/csv_exporter.py#L276

**Comment by LefterisJP** [comment]
Ah good point. Thanks for reminding us of this.

**Comment by davbre** [comment]
Nice one!
