### ISSUE TITLE
 Add support for FTX

### ISSUE THREAD

**Issue by rawfalafel** [rotki/rotki#1334]
Add the ability to read the current balance and order history on [FTX](https://ftx.com/)

**Comment by adrien-be** [comment]
+1

**Comment by vmavromatis** [comment]
Much much needed! I would start using rotki today if it had this!

**Comment by gl4d** [comment]
+1

**Comment by dannypernik** [comment]
+1

**Comment by LefterisJP** [comment]
Hey guys. Does anyone have a read-only FTX key he can share with us to implement this? If yes please join our discord and DM me. We want to add FTX as the next integration but without an api key with sufficient data implementation is harder: https://discord.gg/aGCxHG7

**Comment by cj4c0b1** [comment]
@LefterisJP If you need any help on that integration , pls let me know.

**Comment by dannypernik** [comment]
@LefterisJP getting "Invite invalid" when following this link.

**Comment by LefterisJP** [comment]
@dannypernik I think this must be something in your side. This is our discord invite and is working fine from what I just checked.

**Comment by dannypernik** [comment]
@LefterisJP you're right, sorry about that. I'm in.
