### ISSUE TITLE
Support yearn.finance vault balance queries

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1336]
## Problem Definition

Support vaults balance query for https://yearn.finance/

## Task

Do it.

**Comment by adrien-be** [comment]
+1

**Comment by LefterisJP** [comment]
Currently rotki does not show if you have something in yearn finance. As a first step for this issue it woudl be to show how much value the user has locked in there.

(Screenshot is from an account that put DAI in CRV yPool, got yCRV and then put it in the yCRV yearn finance vault. Should not show 0 EUR at least for yearn finance.

![2020-08-20_22-45](https://user-images.githubusercontent.com/1658405/90824093-27e13b00-e337-11ea-8eac-c4b6b7bc8118.png)

Then we can perhaps make a different issue for historical analysis which would be a premium feature.
