### ISSUE TITLE
[Premium Registration]: Allow Registration Without Billing Address

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#1343]
## Abstract

Providing a billing address means revealing who you are. 

## Motivation

Many folks in the crypto space care a lot about privacy and those same folks are probably the ones using Rotki. Removing this billing address requirement would make them feel a little more protected.

**Comment by LefterisJP** [comment]
Hey Adrien, I know and we already have it in our "to think" about list ... but at the moment can't find a way around this.

We are a registered business and need to generate invoices for any income we generate. The invoices need a billing address.
