### ISSUE TITLE
[Premium Registration]: Allow Yearly Subscription In Crypto

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#1344]
## Abstract

Paying by bank card or paypal means revealing who you are.

## Motivation

Many folks in the crypto space care a lot about privacy and those same folks are probably the ones using Rotki. Allowing **yearly** premium subscription payment via crypto would allow those folks to remain anonymous. Those who like your product a lot will not mind having to pay for a full year.

**Comment by LefterisJP** [comment]
You can actually pay by crypto already. And you can choose, just like with fiat, any period from 1, 3, 6, 12 months.
![Peek 2020-08-16 10-52](https://user-images.githubusercontent.com/1658405/90330632-9e381300-dfae-11ea-9a92-4ebad8dd51d4.gif)

Do I misunderstand your request or is there anything else you would like to see?

**Comment by LefterisJP** [comment]
Closed this issue as I think we already offer this, unless I completely misunderstand the request.
