### ISSUE TITLE
[Exchange] Add uphold support

### ISSUE THREAD

**Issue by CPatchane** [rotki/rotki#1345]
## Abstract

Add [Uphold](https://uphold.com/) support

**Comment by Michael-A-Heuer** [comment]
Many people I know onboard into Crypto using the Brave Browser because of Brave Rewards.
Although I personally don't like the practice of enforcing a custodial wallet at https://uphold.com it seems to be used quite a lot.
Therefore, I support this request.

**Comment by LefterisJP** [comment]
Uphold has no API unfortunately.

**Comment by Michael-A-Heuer** [comment]
@LefterisJP 
They have one and other Crypto tax services support it already

https://uphold.com/en/get-started/developer

https://uphold.com/en/developer/api/documentation

**Comment by LefterisJP** [comment]
That is not an API in the sense that we can use it as a local application. If you read the page you linked this is one where the application can register with them, not one where the user can create api keys and give it to the application.

This kind of API is only meant to be used by centralized webapps.

**Comment by Michael-A-Heuer** [comment]
Oh, I see... 😬 Thanks for the clarification

**Comment by LefterisJP** [comment]
Perhaps they got CSV exports which we could use instead. Or ... can even email them if they are aware of any way we can implement the integration for a local opensource app.

**Comment by Michael-A-Heuer** [comment]
> Perhaps they got CSV exports which we could use instead. Or ... can even email them if they are aware of any way we can implement the integration for a local opensource app.

I emailed them already

**Comment by cybern0id** [comment]
Hi! I'm so glad to find rotki. I couldn't bear to think about having to submit my financials to a centralised proprietary accounting service and don't relish the thought of wrestling with spreadsheets.... As mentioned by a previous commenter, I was on-boarded via Brave/BAT/Uphold like many I'm sure and so I'd like to see support for Uphold .CSV import implemented if possible.

Uphold now allows export of transactions made in their custodial wallet to a .CSV file. The layout with some sample data is as follows (I've obfuscated my personal data as much as possible - the amounts and rates are not a real reflection of the actual exchange or transfer and I've changed the date-stamps and the transaction IDs):

Date | Destination | Destination Amount | Destination Currency | Fee Amount | Fee Currency | Id | Origin | Origin Amount | Origin Currency | Status | Type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Tue May 26 2020 18:06:28 GMT+0000 | xrp-ledger | 314.642101 | XRP | 2.10E-06 | BTC | 1a2b3c4d-5e6f-1a2b-3c4d-5e6f1a2b3c4d | uphold | 0.00714216 | BTC | completed | out
Wed May 20 2020 02:00:26 GMT+0000 | litecoin | 1.26155562 | LTC | 0.111123 | NANO | 1a2b3c4d-5e6f-1a2b-3c4d-5e6f1a2b3c4d | uphold | 133.362002 | NANO | completed | out
Wed May 13 2020 13:30:04 GMT+0000 |   | 24.65 | GBP |   |   | 1a2b3c4d-5e6f-1a2b-3c4d-5e6f1a2b3c4d | uphold | 24.65 | GBP | completed | out
Sun Mar 29 2020 12:21:44 GMT+0000 | uphold | 24.65 | GBP |   |   | 1a2b3c4d-5e6f-1a2b-3c4d-5e6f1a2b3c4d | uphold | 0.00421 | BTC | completed | transfer
Tue Feb 11 2020 13:13:57 GMT+0000 | uphold | 0.00331961 | BTC |   |   | 1a2b3c4d-5e6f-1a2b-3c4d-5e6f1a2b3c4d | credit-card | 25 | GBP | completed | in
Thu Dec 19 2019 18:40:09 GMT+0000 | uphold | 5.15 | BAT |   |   | 1a2b3c4d-5e6f-1a2b-3c4d-5e6f1a2b3c4d | uphold | 5.15 | BAT | completed | in



Uphold only allows transfer out of their custodial wallet to fiat currency and a limited selection of blockchain networks (BTC, XRP, ETH, LTC to name some) and I'm not sure which naming convention they use for all the "Destination" and "Origin" column entries except for the ones I've used, which are "credit-card", "uphold", "xrp-ledger", "litecoin" and "ethereum".

It would be great to see this implemented or I could have a go myself if someone could point me to the relevant source files. Perhaps the CoinTracking or crypto.com processors could be used as a template and amended easily to work with Uphold?

**Comment by LefterisJP** [comment]
Hey @cybern0id hello!

Thanks for the test data. We would like to get to this at some point but since we are a small team our capacity is really limited.

If you have any python coding capabilities then it would be really cool if you could take a stab at it.

The code you want to look at is the https://github.com/rotki/rotki/blob/c9d06f0c5b1a113754ade6d70e8d0a8dc955ba8e/rotkehlchen/data/importer.py where all external CSV are currently imported from. We should probably also be splitting that into other importing modules as more csv imports are added.

**Comment by arosboro** [comment]
@cybern0id hope you don't mind, I'm going to implement this feature over the next few hours.

**Comment by cybern0id** [comment]
Please do! :) I only started a little and got diverted and because I'm only an amateur coder, I got a little stuck some time ago. I had good intentions but apologise for leaving this so long.

10 Sep 2021 20:49:00 Andrew Rosborough ***@***.***>:
