### ISSUE TITLE
Tax Report Improvements (Asset Price Sources, Asset Price Exports)

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1357]
During the creation of the tax report (or via the accounting settings), users should be able to determine where they would prefer that asset prices are sourced from from. Some example options:
* Mono-source -- user selects that all assets should be retrieved from one source, e.g.: cryptocompare / coingecko / etc. and fail if no asset prices exist from that source
* Mixed-source -- user selects that assets can be retrieved from a variety of sources based on a certain priority, as it's possible that certain asset prices may not be available from each source.
* "Global average" -- user selects that asset price should be averaged for that date/timestamp based on all available source, i.e.
an "average across sources".

Additionally when preparing the tax report in the export options it might not be a bad idea to also export the full data concerning asset prices (including fiat:fiat exchange rates) that we have pulled and include that in the download since sometimes tax authorities might ask for proof of where asset prices were taken from, e.g.
```
-------------------------------------------------------------------------------------
|  asset   |     price in USD  |     timestamp       |      price      |   source   |
-------------------------------------------------------------------------------------
```

**Comment by LefterisJP** [comment]
I meant to create an issue per each one of these options. Each option would be a ton of work.

Anyway this can act as a master issue and we can create subissues.

Needless to say this sounds good, but would be a ton of work so would need to be prioritized properly.

**Comment by LefterisJP** [comment]
The first 2 bullet points are implemented with the price oracle order work. The last one, taking the average of the oracles, is not yet done but I opened a separate issue for it: https://github.com/rotki/rotki/issues/2308

So we can now close this one.
