### ISSUE TITLE
Introduce a default rotki account and keep separate accounts/profiles for advanced users

### ISSUE THREAD

**Issue by lullis** [rotki/rotki#1359]
As discussed on #1239, there is no real need to have a username/password system on rotki's initial screen. It is confusing to users and not really required given that this is a desktop application

## Specification

Below is just a suggestion for how we can keep the user's data secure and improve the UX

 1. Remove the concept of "local account" that requires username/password and simply assume that the program is run under the user's account.
 1. Add the concept of "profiles" as a way to correlate databases to specific data. Most users will have only one profile and this is the one that should be used in by default. If a user wants to have more than one profile (e.g, to separate personal and business reportable data) then they can create on settings. On startup, a "profile selection screen" can be displayed only if the user has more than one profile.
 1. If encrypting the user's database is still desirable, rely on the OS keyring application to generate the encryption key to avoid the user having to deal with yet another password. #4125

**Comment by LefterisJP** [comment]
I like (1) and (2). (3) is OS-specific and probably too much work.

Essentially have the user create a default account at start with a password and then always log him in there. So not given an option to create a new account at start. But instead give them the option to "Enter a password to protect your Rotki data".

And this creates the default user. Each time the app opens the password to unlock it will be asked.

For people who want to maintain multiple accounts do something like the profiles you suggest.

**Comment by LefterisJP** [comment]
We hear the feedback and may indeed revisit this at some point, but it's not a priority right now so closing for now.

May revisit and implement parts of the suggestions though.
