### ISSUE TITLE
Module activation requires restart

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1375]
## Problem Definition

I was trying to activate the `makerdao_vaults` modules from the defi settings but I was getting a module not activated error, while the module was in the settings.

After discussing with @LefterisJP it seems that a restart is required for the defi module to get activated. This is not obvious that it is required.

As a first step, we can mention it in the UI so that the user knows what needs to be done.

### Tasks
TBD

**Comment by LefterisJP** [comment]
This will be handled by solving #1799 as it's, in essence the same issue. (Tell me if you don't agree -- but if you do I am closing this)

**Comment by kelsos** [comment]
Sure, when I opened the issue it made sense based on the discussion we had at the time. Since we re-evaluated the issue it makes absolute sense to close this.
