### ISSUE TITLE
[Coin Support]: Update Ocean Protocol coz of Token Swap

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#1378]
## Abstract

Ocean Protocol swapped its token.

## Motivation

Currently, if one moves the new tokens to an exchange or wallet, Rotki still points to the old contract so it simply takes the incorrect balance to calculate the balance for the given wallet.

## Specification

Old Contract: [0x985dd3D42De1e256d09e1c10F112bCCB8015AD41](https://etherscan.io/address/0x985dd3d42de1e256d09e1c10f112bccb8015ad41)

New Contract: [0x7AFeBBB46fDb47ed17b22ed075Cde2447694fB9e](https://etherscan.io/address/0x7AFeBBB46fDb47ed17b22ed075Cde2447694fB9e)

Read more: https://blog.oceanprotocol.com/ocean-token-swap-completed-new-contract-live-f0768423b3e1

Thanks guys!

**Comment by LefterisJP** [comment]
Will see what we can do and include it in 1.7
