### ISSUE TITLE
Change datatables to use BigDialog for more info and actions (edit, delete) instead of "expand" and buttons

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1381]
This came up while we were discussing trades in discord. Basically currently we have the scenario where certain table rows may have actions (edit / delete) while others might not (e.g. external trades vs exchange trades). Because it will look a bit weird to have no buttons or disabled buttons for some rows, and working buttons for others, and since we already only use single-expand to show more information for rows where there isn't enough space, instead what we can use is use a BigDialog to display a "full info" of relevant data to the user (e.g. all trade fields) and then move the buttons from the table to the BigDialog. This has the added benefit of (a) freeing up some horizontal space and (b) being more small screen-size and (eventually) mobile friendly.

**Comment by LefterisJP** [comment]
We discussed this in the standup today and I am not sure it makes sense at this point. Things may change during the re-design so makes no sense to devote resources now.
