### ISSUE TITLE
Change external URL opening from whitelist only to whitelist + warning

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1385]
As discussed on discord there are certain cases where we may want to allow the opening of links pointing to user-defined URLs via the application. The current approach is that only URLs that confirm to a set of whitelisted URL masks/patterns is allowed, but with user-defined URLs this may prevent a legitimate URL that the user has entered from opening.

Instead of completely disallowing the launching of external non-whitelisted URLs, we should instead show the user a warning asking them to confirm if they wish to open this URL. Whitelisted URLs should continue to open as-is (i.e. without the need for a confirmation).

**Comment by kelsos** [comment]
The whitelist has been removed and now the application will open external links for any https link.
