### ISSUE TITLE
Show the subtype of each query task in the frontend

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1386]
## Problem Definition

As discussed in discord we should show all running tasks and not just the parent tasks for querying trades, or for querying asset movements in the "Running tasks" ui component.

![2020-08-27_23-44](https://user-images.githubusercontent.com/1658405/91498942-ef0a0e80-e8c0-11ea-83bd-83e413dc7e76.png)

@kelsos It should also be for deposis/withdrawals. And generally in other places in the app where multiple tasks are sent.

## Task

Do it

**Comment by kelsos** [comment]
Also for Deposits & Withdraws 
![image](https://user-images.githubusercontent.com/2269732/91618772-981d3b80-e98b-11ea-9cd4-7bd3518612e5.png)
