### ISSUE TITLE
Flying amount tooltip

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1394]
## Problem Definition

![Peek 2020-08-28 23-28](https://user-images.githubusercontent.com/1658405/91618042-ad916600-e989-11ea-8dcc-a515019a4c9d.gif)

## Task

Fix it

**Comment by kelsos** [comment]
@LefterisJP question which field was this tooltip form? because I did a quick check in my working PRs and the tooltip was properly positioned in the ones I had.

**Comment by LefterisJP** [comment]
It was the amount. But not every row. Some random rows in the tax report.

**Comment by LefterisJP** [comment]
I think this is fixed by now @kelsos. have not seen it since. Will close. Reopen if you don't agree.
