### ISSUE TITLE
Introduce DeFi debt as a separate line item in Blockchain Balances

### ISSUE THREAD

**Issue by rawfalafel** [rotki/rotki#1400]
## Abstract

When tallying up balance by token, DeFi collateral and debt are calculated as part of the ETH balance. It would be nice if ETH collateral was part of the ETH balance but **debt** was a separate line item with a negative balance.

## Motivation

Considering that debt is issued with some asset other than ETH, it's confusing that the debt is deducted from the ETH balance. Also, there's no visual indication that collateral and debt in DeFi is used to calculate balances. A separate line item would bring more clarity into how each line item is calculated.

## Specification

IMO, DeFi debt of every token type should be added as a separate line item with negative balance. DeFi collateral could perhaps just be part of the token type's line item instead of a separate line item. If so, it would still be nice if a tooltip explained how much of the token is used as collateral.

**Comment by LefterisJP** [comment]
Note to implementer: Introduce DB upgrade for timed_balances in the DB to differentiate between asset and liability.
