### ISSUE TITLE
Separate icon from price query from coingecko for some types of assets

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1405]
## Problem Definition

There is some assets, especially most of the yearn vault ones (link to PR here), that have a `"coingecko"` entry in `all_assets.json` that is intentionally not correct. For example `yUSDC` points to `usd-coin` so that the icon of the underlying asset, that is USDC is pulled from coingecko.

At the moment for all of these no price queries happen from coingecko as they are all handled specially and we don't query prices from coingecko yet, only icons.

But a solution needs to be found so that the icon source of coingecko can be separated from the price source of coingecko (or lack of price from coingecko).

## Task

Think and find a solution

**Comment by rishabhRsinghvi** [comment]
Please assign this to me

**Comment by LefterisJP** [comment]
We "solved this" by removing the continious periodic coingecko query.

The question of finding another source of icons is open.
