### ISSUE TITLE
Location filter in History page should only show valid locations

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1414]
Currently the location filter in the History page shows all locations, regardless of whether the user has data in those locations.

E.g. you can see Bitmex below even though I do not have Bitmex connected or any Bitmex data in my account
![image](https://user-images.githubusercontent.com/27592/91823772-09821600-ec3a-11ea-9bd1-c9fba14f528b.png)

A location should only be shown as option if any of the following is true:
* The location is a connected exchange
* The location contains balances
* The location has associated historical trades/transactions

**Comment by LefterisJP** [comment]
Hey @kelsos for this do you think it could be accomplished only on the frontend side? Since it also keeps a state I guess it's possible.

**Comment by kelsos** [comment]
It should be possible, at the moment all the state should be cached in the frontend
