### ISSUE TITLE
Re-order Navigation Menu entries for usability

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1415]
## Abstract

We should order the navigation menu in logical groupings and in some sense of most used -> least used vertically:

Current order:
![image](https://user-images.githubusercontent.com/27592/91825027-fb34f980-ec3b-11ea-8e7e-3c2d28226257.png)

Proposal:
Dashboard
Accounts & Balances
History (maybe swap with DeFi)
DeFi (maybe swap with History)
Statistics
Tax Report
(maybe a divider here?)
API Keys
Import Data

**Comment by LefterisJP** [comment]
Sounds good to me. Should be easy to do and especially the api keys/import data at the bottom with a separator makes sense
