### ISSUE TITLE
When Rotki Premium keys expire or are made invalid (e.g. regenereated), indicate that to the user upon login

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1417]
## Abstract

Currently, if the user logs into rotki and in the interim his/her premium keys have either expired or been made invalid (e.g. regenerated), the backend will log the rejection message and delete the existing keys from the DB.
```
rotkehlchen.premium.sync: Could not authenticate with the rotkehlchen srver with the API keys found in the Database. Error: Rotkehlchen API key was rejected by server
```
When the user logs in they will encounter the "rotki premium" dialog box, which might also lead to confusion.

In such a case we probably shouldn't remove the keys, but instead show that there are keys registered but not currently working.

We should come up with a way to indicate to a user whose last logon was a valid premium logon that the keys have expired or that there is a problem and link them to the Manage Premium section of rotki.com so that they can investigate or renew their subscription.

**Comment by LefterisJP** [comment]
I think this is handled by https://github.com/rotki/rotki/pull/2039/

A user got the previous error when his subscription expired and asked for support. He renewed it and then the warning goes away. The warning will go away if you remove the expired api keys too.
