### ISSUE TITLE
Date Format Options

### ISSUE THREAD

**Issue by MysticRyuujin** [rotki/rotki#1418]
Most, if not all, dates in Rotki are in the format of "DD/MM/YYYY" however, not all regions use this date format.

I'd recommend either adopting the ISO standard of "YYYY-MM-DD" or making dates a regional setting or custom setting like the currency settings.

Thanks!

**Comment by LefterisJP** [comment]
Thanks for the issue @MysticRyuujin 

WE should perhaps for all of these provide some per-region defaults.

But isn't customization from settings already possible?

![2020-09-01_17-41](https://user-images.githubusercontent.com/1658405/91874453-8a610200-ec7a-11ea-87b7-bdd4d2b1c63f.png)

**Comment by MysticRyuujin** [comment]
Ah, crap, you're right. I didn't even notice.

**Comment by LefterisJP** [comment]
Hey np, neither did I at first as I have not used this ever myself as defaults are what I am used to :stuck_out_tongue:
