### ISSUE TITLE
Opensource format and implementation for turning ethereum transaction data into chain of events

### ISSUE THREAD

**Issue by bengii** [rotki/rotki#1419]
## Abstract

The emergence of Defi and growing prevalence of agents such as zapper.fi provide excellent user experience by abstracting away the details of  sequenced, performant smart contract executions that make accurate historical accounting very challenging. How to create a shared truth around what occured across multiple evolving platforms? This problem was solved in telephony via a standard CDR (call data record) format that is agreed globally on what telephony events happened between A to B for how long, call quality etc. 

## Motivation

how to address the problem you described earlier:

Create a standard reporting format/template for chained transactions or "zaps". Lead by example, create the format with one partner (hint: zapper please!) then help a second partner to write an adapter for their existing export format such that the output is delivered in the standard reporting format - do it one partner at a time - (did I mention start w/ zapper?)

Then whenever partners change their export format they can just update their adapter also......

## Specification

ahem..... zapper already provide a CSV export example so perhaps scope the problem / assess difficulty by writing an adapter for that in such a way that it delivers to Rotki in a format that is efficient.

**Comment by LefterisJP** [comment]
Hey @bengii thanks for the issue.

I am not sure what exactly is it that you are asking for though. Can you maybe specify what it it that you would like rotki to do for you?

From reading what you wrote I understand you would like us to support the importing of zapper.fi CSV export format?

**Comment by bengii** [comment]
you are correct, I am asking for 
1) importing of zapper.fi CSV format and I am also wondering 
2) is it useful to prototype a standardized template or record format for inporting/ exporting chains of transactions

**Comment by LefterisJP** [comment]
I see. Thanks for the clarification!

So for (1) it's actually tricky. We also detect the same transactions. We just don't **yet** convert them and show them to the user same way they do.

If they are using an opensource converter of an ethereum transaction to a "chain of events" then we would gladly use it too. Just simply trusting their data is against the ethos of what we do here at rotki where auditability and accountability is paramount.

Our plan for all these is to gradually roll out support for all DeFi protocols and DeFi exchanges as we have already done with Maker and Aave. To achieve that we utilize data from many ethereum nodes and in the near future probably thegraph indexers.

For (2) yes it would be. Actually not just a template. But some kind of opensource library that could turn normal ethereum transaction data into this chain of "events". Also a "standardized format" for such a thing.

**Comment by bengii** [comment]
Excellent! As the time the tax year closes I reckon that (2) would be a super contribution to the ecosystem... And a great brand awareness opportunity. CSI Defi... Piecing together what happened the defi-day before...

**Comment by LefterisJP** [comment]
This is essentially what the new transaction decoders whose first iteration is coming in v1.24.0 are going to be doing. So this is the same as the solved issue #1477 so closing.
