### ISSUE TITLE
Create a database of address names and use it in rotki

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1420]
## Abstract

Rotki has various sources of data that could be used to build a user's "address book". This address book could then be used to add extra information to data that we present in the application. These sources include:
* Blockchain accounts entered by the user (data exists)
* Blockchain addressses/accounts in connected exchanges (data exists but perhaps we don't collect it in this way)
* Known addresses for popular platform smart contracts (not tokens, but contracts) (not yet supported) (e.g. ENS, UniSwap)
* 3rd party accounts that could be manually added by the user (not yet supported)
* _add more sources here_

Essentially we can use this information to provide clarity to the user when they are viewing different content within the application. For example, if they're looking at Exchange Deposits / Withdrawals, the `from address` or `to address` could be checked against the address book, and if they exist we would show the label that the user has indicated for the address as opposed to the address hash. Likewise this could be applied for transactions with known platforms/smart contracts, or incoming/outgoing transactions from/to addresses that the user has identified and labeled manually (e.g. the user might have identified & labeled accounts that belong to friends/family, a product they are paying for (rotki), etc.).

We should also determine to what extent we can integrate information from DID providers such as 3box its evolution such as cutting edge identity frameworks such as identity index (https://twitter.com/identityindex) etc.

This functionality would eventually serve as the backbone for enriching the application with "business-minded" functionality such as the identification the accounting of customers and vendors (together with the double entry work we will do), or analytical functionality by tagging addresses and transactions and thus allowing the user to analyzing things like cash flows, budgeting, etc.

EDIT:
Note: I can't imagine we can tackle this as a "one and done" issue, so I propose we keep this as a general high-level issue and open and link specific issues as we identify and work against them.

**Comment by LefterisJP** [comment]
Thanks for making the issues. This is something really needed.

> Blockchain addressses/accounts in connected exchanges

What do you mean by this?

**Comment by isidorosp** [comment]
> Thanks for making the issues. This is something really needed.
> 
> > Blockchain addressses/accounts in connected exchanges
> 
> What do you mean by this?

In an exchange when we make a deposit, we deposit it to an address provided by the exchange. Most exchanges (if not all) offer functionality to generate new addresses, but some users don't use this a lot. Regardless, we can use these addresses to populate the user's address book.

For example, if we are depositing from an ethereum account we own into binance, we would see the deposit in Binance but we should also technically see this transaction under "ethereum transactions". It would be super helpful for the user if in that transaction the `to_address` would show automatically that this was a binance deposit address. (another way we could achieve this is if if the exchange also provided the tx hash then we could cross-reference against the ethereum tx hashes that we have).

**Comment by LefterisJP** [comment]
> In an exchange when we make a deposit, we deposit it to an address provided by the exchange. Most exchanges (if not all) offer functionality to generate new addresses, but some users don't use this a lot. Regardless, we can use these addresses to populate the user's address book.

We can achieve this in a best-effort way by:

1. Extracting deposit addresses from exchanges that support it in the deposits/withdrawal api endpoints.
2. Crawling etherscan for all exchange deposit addresses.

(2) may be stupid since most of the times it's like: user's address -> user's generated deposit address -> exchange owned hot walet

**Comment by LefterisJP** [comment]
We now have a hard-coded mapping of addresses to names in the app. We should augment it as part of this issue, to be saved as part of the DB (user or or global -- maybe global?) and be customizable by the user.

**Comment by aspiers** [comment]
Sounds great. BTW I am working on a privacy-preserving blockchain addressbook browser extension. Once it's released, it would probably make sense to figure out some kind of integration between the two :-)

**Comment by kelsos** [comment]
I was thinking more of a hybrid approach where you also have a private address book that is not shared.

**Comment by aspiers** [comment]
Yes, using Etherscan etc. is terrible for privacy.  The approach I am considering for my extension is indeed a hybrid approach, and I agree Rotki would benefit from this too.

The plan I have is that the address book is effectively a combination of sections (e.g. "work", "personal", "family", "DeFi", ...).  Some of these sections are simply registered as URLs pointing to remote address, which can be periodically or manually refreshed.

Other sections are simply text blobs allowing easy copy and paste (e.g. for easy sharing via Discord, email etc.).

For each section's contents, the same simple raw text format is used: one address and label per line.

This allows each user to have sections in their personal address book:

- pointing to lists of addresses for:
  - each of the projects they are involved in or care about
  - some for commonly used tokens (in a similar way to https://tokenlists.org/)
- for personal wallets, multisigs etc. and other addresses which should remain private

And then both Rotki and my browser extension have the option of supporting a feature to toggle on/off per section of the reverse mapping from addresses to names.

**Comment by LefterisJP** [comment]
> I was thinking more of a hybrid approach where you also have a private address book that is not shared.

Sure we can do that. The rotki api and the UI should show to the user which is which though.

> using Etherscan etc. is terrible for privacy. 

Etherscan would just be used as a source for a massive blob of labels. No privacy would be lost.

**Comment by aspiers** [comment]
[**@LefterisJP**](https://github.com/LefterisJP) commented on [May 30, 2022 4:45 PM](https://github.com/rotki/rotki/issues/1420#issuecomment-1141295088 "2022-05-30T15:45:02Z - Replied by Github Reply Comments"):
> > using Etherscan etc. is terrible for privacy.
> 
> Etherscan would just be used as a source for a massive blob of labels. No privacy would be lost.

Privacy would be lost if private / sensitive addresses and corresponding labels are uploaded to Etherscan: even when using private notes within my own Etherscan account, I'm still having to trust Etherscan not to read my private notes.  And in the trustless world of web3, of course that's a very poor situation to be in.

So there has to be a place users can store private / sensitive addresses without trusting third parties.  This is where local-only storage comes in.  The fact that Rotki runs locally rather than in the cloud, thereby supporting local-only storage and achieving trust minimization, is one of many reasons it's so awesome ;-)

**Comment by isidorosp** [comment]
> [**@LefterisJP**](https://github.com/LefterisJP) commented on [May 30, 2022 4:45 PM](https://github.com/rotki/rotki/issues/1420#issuecomment-1141295088):
> 
> > > using Etherscan etc. is terrible for privacy.
> > 
> > 
> > Etherscan would just be used as a source for a massive blob of labels. No privacy would be lost.
> 
> Privacy would be lost if private / sensitive addresses and corresponding labels are uploaded to Etherscan: even when using private notes within my own Etherscan account, I'm still having to trust Etherscan not to read my private notes. And in the trustless world of web3, of course that's a very poor situation to be in.


There's no intent/question of ever uploading anything to etherscan. Just to download the etherscan "public labels" database and store it in rotki. The question was whether to store this in the rotki global database (per-computer) or the per-user database, and what makes most sense (the "hybrid approach") is to store "public" labels in the global database and then private (user-specific) labels in the user database.

**Comment by aspiers** [comment]
Gotcha, thanks for the clarification.

No, they don't offer that.  I guess technically it would be possible to do that and still retain the main point of the feature, which is to do reverse mapping of addresses to labels when you are exploring transactions, addresses etc.  If the notes were encrypted, their backend wouldn't be able to perform the mapping, but it could be done by decrypting the notes and performing the mapping all in the browser, without the backend having to access to the notes.  But that's quite a bit more work to implement (and actually much closer to what my extension does).
