### ISSUE TITLE
Automatic user login / password

### ISSUE THREAD

**Issue by gwenvador** [rotki/rotki#1424]
It would great to have an option to save the username/password at startup window. That would save some time and being on a private computer the environment is quite safe. If saving full credentials is a security issue at least entering automatically the username should be considered.

**Comment by isidorosp** [comment]
Related to https://github.com/rotki/rotki/issues/1359 (default account auto-selected)

**Comment by LefterisJP** [comment]
Thank you for your feedback @gwenvador. I completely agree. As @isidorosp already stated we are planning to address this with #1359.

Would that be enough for your requirements? If that is so is it fine with you if we close this issue and keep only #1359?

**Comment by gwenvador** [comment]
Yes I searched quickly for the same issue and could not find it. Excited to see there is work on this. I will close the ticket.
