### ISSUE TITLE
PoolTogether data in Defi Overview is not correct

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1429]
## Problem Definition

PoolTogether (https://app.pooltogether.com/) data is not correctly represented in the Defi overview. This is because the zerion SDK seems to return "PLT" as the token (which rotki recognizes as "Plutus Defi"), so it's returning an incorrect crypto icon and value in the user's profit currency.
![image](https://user-images.githubusercontent.com/27592/92018221-27906900-ed55-11ea-8c1a-948e738d8f03.png)

The real token depends on which pool (DAI or USDC) the user has deposited their funds into thus should be returned as plDAI or plUSDC, which are locked in value 1:1 to DAI and USDC respectively. Therefore the correct valuation here would be 45 plDAI = 45 USD = ~38 EUR.

Even if zerion returned the correct token names, though, the downside is that these tokens are not listed on coingecko or cryptocompare as they're not really "tradeable tokens" -- just proxies for DAI and USDC, so we cannot grab the icons and prices automatically. We will probably need to create aliases plDAI for DAI and plUSDC for USDC and then include the icons manually? 

Another option of course is that we develop our own submodule (e.g. using their subgraph https://thegraph.com/explorer/subgraph/pooltogether/pooltogether or by querying the relevant contracts) and ignore the zerion results for pooltogether.

More resources:
https://defimarketcap.io/protocol/pool-together
https://etherscan.io/accounts/label/pooltogether

**Comment by LefterisJP** [comment]
@isidorosp This probably should go along with https://github.com/rotki/rotki/issues/1120, and the "more resources" links should also go there.

But let me see if until full pool together support is possible we can do something in between for what we show in the DeFi overview. Let me check zerion's adapter contract. Can you DM me the address you used so that I can test?
