### ISSUE TITLE
Change typography-related html tags not "supported" by vuetify to vuetify classes

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1431]
We sometimes use elements (`<h1>` etc.) that aren't technically supported by the styling that vuetify applies. We should update all instances of this usage to use the classes that vuetify supports.

e.g.
`<h1>content</h1>` -> `<span class="text-h1">content</span>`

See:
https://vuetifyjs.com/en/styles/text-and-typography/

**Comment by LefterisJP** [comment]
@kelsos @isidorosp is this fixed?

**Comment by kelsos** [comment]
In some places yes. I need to do a check across the frontend though

**Comment by LefterisJP** [comment]
Just want to either have it scheduled for a milestone or closed ;)
