### ISSUE TITLE
Add support for Bitcoin xpubs

### ISSUE THREAD

**Issue by pereztechseattle** [rotki/rotki#1444]
Adding manual Bitcoin balances one address at a time is not ideal, obviously.  It would be better if I could enter my xpub address and Rotki could then look up all my addresses and UTXOs combined.

**Comment by LefterisJP** [comment]
Hey @pereztechseattle I hear you, I really do. It's taking a bit longer than we expect since we are very low on resources but many people have asked for this feature: https://github.com/rotki/rotki/issues/808

**Comment by pereztechseattle** [comment]
Oops, I didn't see that ticket.  Cool.  Maybe I can pitch in and help then.  :)
