### ISSUE TITLE
Allow the frontend to request cached data

### ISSUE THREAD

**Issue by bengii** [rotki/rotki#1448]
## Problem Definition

 If Rotki app can't contact the exchange the exchange API call stops. And even if we got cached data, which we do they are not returned.

This results in no trades found/displayed under History -> closed orders

### Description
The frontend should be able to request the cached balances/trades etc that have long-running requests.
This could be done by a `from_cache` parameter during the request.

The idea is that the frontend first performs this from cache request to show the user the previous known state and then it starts the actual fetching of the new data. 

This way the frontend already shows the last known state along with the different loading bars to indicate that this state is not final.

This means that the user will be able to already see information while long-running operations run instead of waiting for everything to complete before seeing anything.

**Comment by kelsos** [comment]
Related information: https://github.com/rotki/rotki/issues/2409 and https://github.com/rotki/rotki/issues/1706
