### ISSUE TITLE
exchange API call failure: "Timestamp for this request is outside of the recvWindow."

### ISSUE THREAD

**Issue by bengii** [rotki/rotki#1449]
## Problem Definition

Exchange data not showing on balances / dashboard

### System Description

Note: I removed timestamp and other identifiers in following message.....

Note: my windows PC system has properly sync'd date/timestamp.....

Question: Binance only allows 90day retrieval - is this somehow related? Strange how it just started when previously everything was OK

Binance API request failed. Could not reach binance due to Binance API request https://api.binance.com/api/v3/account?recvWindow=10000&timestamp=Xxxxxxx&signature=[removed data from this posting] for account failed with HTTP status code: 400, error code: -1021 and error message: Timestamp for this request is outside of the recvWindow.

**Comment by LefterisJP** [comment]
Did you by any chance try the clock sync solution as suggested in the support channel?
https://discordapp.com/channels/657906918408585217/745172610240872508/752632155586297867

**Comment by LefterisJP** [comment]
No response in months. Closing.
