### ISSUE TITLE
Introduce pagination to improve ethereum transaction loading

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1451]
## Problem Definition

Currently, all transactions are parsed by the frontend when the requests complete. This can cause a performance issue due to parsing a huge amount of entries. 

Introducing pagination and filtering to the backend can help alleviate this problem by reducing the size of the response parsed each time.

**Comment by aspiers** [comment]
This would be great.  Please can you add a `performance` label to this (and to any other performance related issues)?

**Comment by LefterisJP** [comment]
@aspiers very good point. Done. I am not sure which other issues affect performance but will keep an eye for it now that we got the label.

**Comment by kelsos** [comment]
We certainly need to think about the performance part. And maybe also keep in mind what happens if the backend and frontend are not in the same machine or network.

**Comment by kelsos** [comment]
We should push for this for 1.17 I have been checking this issue because it annoys me a lot and I can see the javascript heap going up to 1.5GB while loading transactions.

Checking the transactions view the requirements at the moment are 
filtering by account(maybe accounts? we only show a single account at the moment) and the actual pagination

**Comment by LefterisJP** [comment]
Sure. It's already scheduled for that so let's do it :)

**Comment by kelsos** [comment]
Moving to the next milestone.
