### ISSUE TITLE
Show which Compound assets are also deposited as borrowing collateral

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1452]
## Problem Definition

Currently, rotki assumes all assets are deposited also as borrowing collateral in the borrowing page for Compound.

We need to provide information in the API so that the frontend can properly calculate the total collateral.

### Tasks
- [ ] Introduce backend properties
- [ ] Update frontend collateral calculation

**Comment by isidorosp** [comment]
The same is also true for Aave (although currently via Zerion we do not know which deposited assets have been enabled for collateral and which haven't). Perhaps we can get this from the aave subgraph (it seems to have various `usageAsCollateral` properties in the sub-graph).

**Comment by kelsos** [comment]
@isidorosp https://github.com/rotki/rotki/issues/1166

**Comment by isidorosp** [comment]
> @isidorosp #1166

😓 Corona-brain
