### ISSUE TITLE
Take into account DeFi balances that are not showing in the Dashboard but do show in the Defi Overview

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1456]
## Problem Definition

The Dashboard shows only tokens for which we can query the direct balance of the user. Anything else is not shown there. There is a number of balances in DeFi protocols such as for example YFI in ygov that are show in DeFi overview but don't show in the dashboard.

## Task

Find the right way to show all DeFi overview balances in the dashboard without double counting anything.

**Comment by aaronmboyd** [comment]
Came here to open this same issue. Portfolio valuation is one of the major uses of this software and it's odd your DeFi balances are not on the main dashboard.

Additionally, there already _is_ duplication. For example, holding SNX tokens in an address will make them get added to the main dashboard _and_ the DeFi dashboard totals.

I would possibly even suggest a larger refactoring to remove the DeFi designation completely. What is considered DeFi? What isn't? Just focus on a streamlined process for adding liquidity pool tokens and their real values and unclaimed yields to the one main screen, ala Zapper. 

(Or just rename it to a designation like "indirectly held" tokens, which means your tokens are in a staking/governance/vault of some sort, and your ownership is noted by LP tokens.)

**Comment by LefterisJP** [comment]
Hey @aaronmboyd thanks a lot for the feedback! We definitely want to better streamline this.

As for what the dashboard shows it's described in the issue's first post:

>The Dashboard shows only tokens for which we can query the direct balance of the user.

---

> Additionally, there already is duplication. For example, holding SNX tokens in an address will make them get added to the main dashboard and the DeFi dashboard totals.

The DeFi overview is auto-detecting things that your addresses have in various protocols for which we have not added explicit support. We use the Zerion DeFi adapter contracts to achieve this. As they add more things, more things appear in your DeFi dashboard.

Having duplication from the DeFi overview to the dashboard overview is okay. The problem is the balances that are detected in DeFi overview and are not taken into account in the overall balances.

But perhaps we should filter out some of the things that the zerion adapter detects as it may overdo it a bit such as SNX or Chi gas token auto detection as DeFi is indeed odd.

> Just focus on a streamlined process for adding liquidity pool tokens and their real values and unclaimed yields to the one main screen, ala Zapper.

We will consider this feedback but Rotki is not just ethereum DeFi. We support cexes, multiple blockchains etc.
What you described here is DeFi (liquidity providing, Dexes, yearn vaults etc.). That is why we have the separate DeFi component.
