### ISSUE TITLE
Use account names when listing Ethereum transactions

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1465]
In the Ethereum transactions view, the From and To columns just show addresses:

![image](https://user-images.githubusercontent.com/100738/93016960-f0278500-f5bc-11ea-91c5-81fe2c509fe1.png)

This is pretty useless - it would be much better if it mapped them to the account labels provided by the user.

**Comment by isidorosp** [comment]
This is a part of https://github.com/rotki/rotki/issues/1420

**Comment by LefterisJP** [comment]
Hey @aspiers thanks a lot for taking the time to point out this feature request.

I would not really call it useless. It's the most basic form of a transaction viewer. Can't start with a fully customizable transaction viewer. We are building features in an iterative manner.

 But exactly as @isidorosp pointed out we have improvements mapped out for it. Would it be okay with you if later I close this issue and merge it with #1420?

**Comment by aspiers** [comment]
[**@LefterisJP**](https://github.com/LefterisJP) commented on [September 13, 2020 1:08 PM](https://github.com/rotki/rotki/issues/1465#issuecomment-691663435 "2020-09-13T12:08:50Z - Replied by Github Reply Comments"):
> Hey [@aspiers](https://github.com/aspiers) thanks a lot for taking the time to point out this feature request.
> 
> I would not really call it useless. It's the most basic form of a transaction viewer. Can't start with a fully customizable transaction viewer. We are building features in an iterative manner.

Agreed - definitely not totally useless ;-) And of course iterating is the right approach.

> But exactly as [@isidorosp](https://github.com/isidorosp) pointed out we have improvements mapped out for it. Would it be okay with you if later I close this issue and merge it with [#1420](https://github.com/rotki/rotki/issues/1420)?

Sure, I hadn't seen that one.  Thanks!
