### ISSUE TITLE
Frontend: Divide compound related COMP rewards between lending and borrowing

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1468]
## Problem Definition

At the moment COMP rewards are shown both in lending and in borrowing. And they all appear in both components. Issue followup after: https://github.com/rotki/rotki/pull/1457

## Task

We should find a way to show the lending related COMP rewards in the lending component and the borrowing related COMP rewards in the borrowing component

**Comment by kelsos** [comment]
@LefterisJP I am not sure if I remember correctly, but I remember discussing that the rewards have the same txhash as a redeem for lending and a repay for borrowing? Is that correct?

**Comment by LefterisJP** [comment]
They should, yes.

**Comment by LefterisJP** [comment]
Hey @kelsos this is an old forgotten frontend (only?) issue. Let's do it.

**Comment by kelsos** [comment]
It has been a long time but this was not frontend only. We had no way to see if a COMP reward was received because of lending or borrowing so we showed that in both.

Also, I am not sure how this will play now if we move to decoders for the events.

**Comment by LefterisJP** [comment]
Hm ... you can't know actually. So whenever I claim comp rewards, it's rewards accumulated at the comptroller. So yeah then this does not make sense. Perhaps just somehow show that it's both from lending and borrowing in the frontend?
