### ISSUE TITLE
Classify ethereum transactions and their events

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1477]
## Abstract

Followup from https://github.com/rotki/rotki/issues/1310

At the moment when we show an ethereum transaction we simply show the input data. It would really be beneficial to try and show more information by decoding the input data and figuring out what it is. A token transfer, a deposit to a known protocol, withdrawal, repayment etc.

Fetching the receipt for each transaction would also help a lot here to go through the logs.

Slightly related to https://github.com/rotki/rotki/issues/1420

#### 1 - Transactions
We already have all transactions for each user account

#### 2 -  Receipts
Fetch all transaction receipts for all saved user transactions. This is going to be slow! So it should be done in the background and perhaps as a long running task. Add it in a prior release so that for existing users the data is already there. Issue: https://github.com/rotki/rotki/issues/1615

#### 3 - Transaction classification schemas

Create and manage schemas for transaction types. @blurpesec of mycrypto who has also worked on this problem provided some such schema examples in a [discord](https://discordapp.com/channels/657906918408585217/683245846070165504/768602192735109131) conversation.

```json
{
	"schema": {
		"key": "topics",
		"type": "topics",
		"topics": [
			"0x06239653922ac7bea6aa2b19dc486b9361821d37712eb796adfd38d81de278ca"
		]
	},
	"meta": {
		"name": "UNISWAP_V1_DEPOSIT",
		"priority": 3
	}
}
```

```json
{
	"schema": {
		"key": "from",
		"type": "addresses",
		"addresses": [
			"0xea674fdde714fd979de3edf0f56aa9716b898ec8"
		]
	},
	"meta": {
		"name": "ETHERMINE_MINING_PAYOUT",
		"priority": 5
	}
}
```
#### 4 - Classify transactions

For each transaction try to match it to a schema from the list of known schemas and classify it. Same thing should happen for each individual event of a transaction. As for example a single transaction could be a call to a contract that bundles (like zaps do) a lot of different transactions to one. In such cases we would need to show each different sub event.

#### 5 - Add that metadata in the DB

Add all the classification metadata in the DB after classifying transactions and their events

#### 6 - Add the metadata to API

Add the metadata in the ethereum transactions endpoint. For each transaction that has not yet been classified an appropriate entry should be returned. WE should distinguish transactions in 3 modes: Classified, Not classifiable, Not processed yet

###  Frontend 

@kelsos this is all you. With the metadata you will need to show a name for each transaction's type, what is happening, what is being transfered e.t.c.

This should all be part of the classification schema (rules still TBD)

### Data acquisition
Getting data from steps 1 and 2 at the moment would only work well with etherscan for (1) and any web3 node for (2). Still will be slow. Would be nice to find a reusable way to get them faster. Perhaps trueblocks can help here? 

### Classification
This is the nice part for reusability. I think that this is a part that many projects would benefit from. There are some closed source projects that already do some transaction classification but having an opensource and reusable way of doing it is what we at ethereum should be doing.

The way to make this reusable would be to agree on a set of schemas for classification and on the algorithm of doing it. And then we would probably have different implementations. Rotki would have python, others go etc.

**Comment by gnidan** [comment]
Had an idea for implementation approach...

Truffle maintains our [@truffle/decoder](https://www.npmjs.com/package/@truffle/decoder) package that should be pretty portable for use here. This would support decoding both the transaction's function+arguments as well as events.

This package exposes two decoding modes: decoding ABI information only, and decoding with full Solidity type information (where relevant). This would likely depend on access to Etherscan to fetch ABI information (and/or full Solidity source, for that decoding mode).

I'll take a look tonight to see how straightforward it'd be to integrate this package. Will follow up with any questions, or if I have any findings to report.

**Comment by LefterisJP** [comment]
Interesting.

But that would require integration in the frontend from what I understand. The rotki frontend is simply the UI + some state. The bulk of the work happens in the python backend. The proper solution would need to go there I think.

Interesting I did not know you could fetch abi+code from etherscan: https://etherscan.io/apis#contracts
Is there any other source for contract ABIs? Especially lately Etherscan has been throwing lots of 503s and don't want to increase our reliance on it more.

Btw if it's a token address we support we can recognize it since we got a list of supported assets (big file): https://github.com/rotki/rotki/blob/develop/rotkehlchen/data/all_assets.json

And then you can just use the ERC20 ABI for any interaction with any of these addresses. I guess similar approach can be taken for the most popular DeFi protocols and DeXes and then maybe 90% of all use cases would be covered?

Would love to know what approaches other trackers have followed ... but they are all closed source ^^

**Comment by gnidan** [comment]
> The bulk of the work happens in the python backend. The proper solution would need to go there I think.

Ah, darn. I was hoping this would be something that could live on the frontend, because I'm not sure how to get @truffle/decoder running inside Python.

> Is there any other source for contract ABIs?

There's [Sourcify](https://github.com/ethereum/sourcify), but I doubt it has anywhere near the amount of data that Etherscan has.

> And then you can just use the ERC20 ABI for any interaction with any of these addresses.

I was hoping to avoid hard-coding specific ABIs for specific addresses, but that might just be my bias (I helped build a high-quality decoder and hate settling for anything less :)

**Comment by LefterisJP** [comment]
> Ah, darn. I was hoping this would be something that could live on the frontend, because I'm not sure how to get @truffle/decoder running inside Python.
>I was oping to avoid hard-coding specific ABIs for specific addresses, but that might just be my bias (I helped build a high-quality decoder and hate settling for anything less :)

I love people who are proud of their creation! We should try to find a way to utilize this in the backend. Would it be really hard to port the logic to python?

I mean for the purposes of this issue we can go in steps and start with something simpler and build up from there as usual. But I am also asking for the long run.

**Comment by gnidan** [comment]
> We should try to find a way to utilize this in the backend. Would it be really hard to port the logic to python?

It'd be quite a tall ask to port it to Python - just take a look at [the @truffle/codec lib directory](https://github.com/trufflesuite/truffle/tree/develop/packages/codec/lib) - there's a lot there! Note that this is built on top of the findings in the [Data Representation in Solidity](https://ethdebug.github.io/solidity-data-representation/) paper, so theoretically one could do the same but in Python.

I found a couple non-long-term solutions: there's [PyMiniRacer](https://github.com/sqreen/PyMiniRacer), which adds Python bindings for the V8 engine, and I also found [pyduktape](https://github.com/stefano/pyduktape), which bundles some other JS interpreter for Python use. But... blech! It's really a shame. 

I'm happy to proceed with a frontend-based short-term solution, but I agree that it's ugly and "the wrong solution". I'll hold off for now unless you are interested.

Thanks!

**Comment by gnidan** [comment]
I haven't looked into existing Python-based decoders, but those might be workable and provide quick value. That sounds like probably a better approach, since it's probably more trouble to integrate @truffle/decoder than it's worth (unless you really want storage info or support for ambiguous event decodings, etc.)

**Comment by LefterisJP** [comment]
Updated the OP after our discussion @blurpesec

**Comment by emansipater** [comment]
Definitely in support of this, though of course it is a huge and somewhat open-ended task

**Comment by Michael-A-Heuer** [comment]
Some events that just happen once on a fixed date could be curated in a database (as mentioned in #2302).
An example are airdrops. 
Moreover, such special events can also be related to exchanges and the data imported from them. 
An example is the SAI to DAI migration in Maker that took place
[on Coinbase on a fixed date](https://help.coinbase.com/en/coinbase/trading-and-funding/cryptocurrency-trading-pairs/dai-faq). Not knowing that this has happened creates conflicting account balances.

**Comment by bohendo** [comment]
> Would love to know what approaches other trackers have followed ... but they are all closed source ^^

Mine's open 😃 

Receipts are necessary, I compiled the tx+receipt into a slightly abstract `EthTransaction` type: https://github.com/bohendo/finances/blob/main/modules/core/src/chainData.ts#L275

And then I parse those into more abstract & generic `Transactions` (includes an array of `Transfers`): https://github.com/bohendo/finances/blob/main/modules/core/src/transactions/eth/index.ts#L69

The `EthTransaction` -> `Transaction` conversion depends on a handful of app-specific parsers eg here's where the MakerDAO one categorizes borrow `Transfer`s: https://github.com/bohendo/finances/blob/main/modules/core/src/transactions/eth/maker.ts#L640

& re classifying transactions: you're right that one tx can take many different actions, that's why I split them up into separate transfers. These transfers (or your equivalent) are prob what you'd want to categorize instead of the entire transaction.

PS I just hardcode the ABIs in the src code, it's never going to change so I don't think this'll cause trouble later plus I want to eliminate as many run-time network calls as possible.

**Comment by LefterisJP** [comment]
Hello @bohendo thanks a lot for the links! Appreciate it. It's nice to see someone else also takes an opensource approach.

We will write our approach here in this issue at some point in more detail. As you can see from the first discussion in the issue it's rather similar.

But we also would like to abstract away the schemas logic and probably put it out of the repo so that anyone can create their own translation schemas for any protocol/app in the future.

**Comment by LefterisJP** [comment]
if we ever need to try and match 4 byte hex to potential function sigs this is useful: https://github.com/ethereum-lists/4bytes

**Comment by joshuavial** [comment]
I've had a look through https://www.trufflesuite.com/docs/truffle/codec/modules/_truffle_codec.html and https://docs.etherscan.io/api-endpoints/contracts#get-contract-abi-for-verified-contract-source-codes and it makes me think about a subset of this feature which makes the ethereum history human readable

### backend
1. call etherscan api to get the abi for a contract if known
2. make a stand alone node script which receives an abi and transaction data and returns a machine readable summary
3. call the node script with an os.system call and save the summary alongside the transaction data
4. modify existing backend api to return the machine readable summary as well as current data

### frontend
1. format the machine readable summary so the user has some idea what the history item is

This could act as a stepping stone for the classification work - I'm thinking it could be a simple modal popup where a user can enter a manual transaction which then becomes linked to that item. The UI could then mark the item as classified and a user could work their way down the transaction history list to get everything classified.

How would you feel about having a standalone node script as a dependency for a backend task @LefterisJP ?

**Comment by LefterisJP** [comment]
Hey @joshuavial there is no need to mix node with the backend. The backend is all in python.

As for your description, yes this is exactly what this ticket is for. But we don't do it with truffle's codec but in python and in a best effort approach over all transactions we find trying to classify them in a human readable way (or not if we can't).

And this will evolve over time with the classifier being smarter and better as the approach gets better. We just need to have a simple version (target is ERC20 transfers) out first.

**Comment by joshuavial** [comment]
Copy that - the eth-abi library I found at https://eth-abi.readthedocs.io/en/latest/eth_abi.html#module-eth_abi.decoding looked like it had a lot less features than ethers or truffle but I get that you want to keep your backend in one language.

**Comment by gnidan** [comment]
I knew we should've written @truffle/codec in Rust 😭

**Comment by shayzluf** [comment]
@LefterisJP how about using [etherscan api call for erc20 tx](https://api.etherscan.io/api?module=account&action=tokentx&contractaddress=0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2&page=1&offset=100&sort=asc&apikey=YourApiKeyToken) and [this one](https://api.etherscan.io/api?module=account&action=tokennfttx&contractaddress=0x06012c8cf97bead5deae237070f9587f8e7a266d&page=1&offset=100&sort=asc&apikey=YourApiKeyToken) for NFT txs and match with txhash in the ethereum transaction list

**Comment by LefterisJP** [comment]
Hey @shayzluf this is being worked on in multiple ways at the moment.


Unfortunately etherscan does not find all address appearances, but if the user has no other option (such as trueblocks) it's the only thing we can do. The NFT API in etherscan is new! I did not know it. It woudl also come in handy.

Additionally token transfers alone do not solve the problem of detecting what happened as there is a lot of other transaction types that do not evolve tokens and still constitue an action.

**Comment by shayzluf** [comment]
> 

I thought of it as an intermediary step to have more information on an ethereum transaction while you work on the long term solution.

**Comment by LefterisJP** [comment]
So for the frontend guys, here is few combinations of events as of this writing:

- type: transfer subtype: none -> internal transfer between owned accounts
- type: spend subtype: none -> spend an asset by sending it somewhere
- type: receive subtype: nonde -> receive an asset from somewhere
- type: spend subtype: fee, counterparty: gas -> burn gas for a transaction
- type: informational subtype: approve -> token approval
- type: receive subtype: airdrop -> claim/receive an airdrop
- type: informational subtype: approve -> token approval
- type: trade subtype: spend -> the sending part of a token swap/trade
- type: trade subtype: receive -> the receiving part of a token swap/trade


In many cases when the counterparty exists and is not an ethereum address then it represents a protocol. Like 1inch-v1, aave-v1 etc.
