### ISSUE TITLE
No option to delete an Exchange Account?

### ISSUE THREAD

**Issue by pereztechseattle** [rotki/rotki#1488]
## No option to delete an Exchange Account

I created a Coinbase exchange account.  I want to remove it now, but I don't see an option to do so.

**Comment by LefterisJP** [comment]
Hey @pereztechseattle thanks for trying out Rotki!

This is a bug. And you are right.

There is a way to do it, and it also used to be there, but I can confirm it's not possible from the UI anymore. We will fix it soon and push it in the next release.

**Comment by LefterisJP** [comment]
Ah wait no no no. I may have spoken too fast @pereztechseattle. I checked an old account without any api keys.

If you go to the api keys and select the exchange you want to remove, does it not work?

![2020-09-17_23-57](https://user-images.githubusercontent.com/1658405/93532578-9cf95d80-f941-11ea-956b-be5bc1ad7d53.png)

**Comment by pereztechseattle** [comment]
![image](https://user-images.githubusercontent.com/16297286/93542779-b9c86d80-f90e-11ea-8bc1-2c3a945af38b.png)

I tried that, but there's no "Remove" option like you show there.  I thought maybe clicking the exchange logos would bring up more options but they don't seem clickable.

Thanks.

**Comment by pereztechseattle** [comment]
FYI: MacOS Catalina 10.15.6 (19G73)

**Comment by pereztechseattle** [comment]
N/mind!  Ok, I just got it.  You have to select the exchange in the dropdown first.

**Comment by LefterisJP** [comment]
Yeah I see from your comments also that there can definitely be some UI improvements here too. Thanks for this!
