### ISSUE TITLE
Feature Request: Disable login

### ISSUE THREAD

**Issue by pereztechseattle** [rotki/rotki#1489]
## Abstract

This product would be more user-friendly if there were no login screen.

## Motivation

I'm more likely to forget this login than anything.  It's totally unnecessary on my local machine.

## Specification

A simple on/off build option would be nice.

**Comment by LefterisJP** [comment]
Hey @pereztechseattle thanks for the nice feedback!

The password is not unnecessary. It's as unnecessary as the password of your ethereum account that encrypts your private key into the keystore json file. Sure you could just keep the raw private key around in your system but that's just completely unsafe.

All your data are kept locally and this is VERY sensitive data that needs to be protected. This password is the key to this encryption.

That said the whole experience can definitely be improved. And there are some nice ideas in this issue which we would like to follow: https://github.com/rotki/rotki/issues/1359#issuecomment-675548098

Do you feel that with the implementation of those ideas your feedback would also be mirrored? If so can I close this issue and move it all there?

**Comment by pereztechseattle** [comment]
What private key?  I've definitely never given Rotki any private key or seed phrase or anything like that.

**Comment by pereztechseattle** [comment]
Ohhhhhhh.... you mean Exchange API keys?

I see.  In that case, I'd still like an option to disable this.  For one, the API keys I'm giving Rotki are read-only.

Anyway, an additional username to me is overly cumbersome and I'm more likely to lock myself out than anything else.  Just my 2 satoshis.

I guess you can close this.

**Comment by LefterisJP** [comment]
Yeah I mean the exchange keys and all other keys that the application, but also all the pulled trades, your accounts your history etc.

If you use all of the app's features someone who gets the unencrypted DB can get an entire view of your financials which is bad.

But yeah we can and will improve this as per the ideas in the other issues.
