### ISSUE TITLE
Add support for the Balancer protocol

### ISSUE THREAD

**Issue by cuokochi** [rotki/rotki#1492]
## Abstract
Would like to see more comprehensive analytic support and tax reporting tools for top Defi apps, especially for apps that have been around for a longer period of time ( vs current farming craze). 

## Motivation
As a long term investor, what attracted me to Rotiki was the need for privacy enhanced tax reporting and analytic tool. I think this is what will ultimately give Rotki an edge compared to apps such as zerion/Zapper.fi (good for portfolio tracking not so much for detailed analytics nor tax reporting) and Tokentax( good for taxes but I’m concerned about potential lack of privacy. Also no comprehensive analytics).
Uniswaproi.com is a great example of an analytic app but with narrow focus on uniswap, no tax reporting tool and pricing is somewhat “too rich” for medium size investors.  

## Specification
No technical specifications. I’m not a programmer. Would love to see enhance analytics and tax reporting for Balancer, Tokenset, curve, uniswap, maker, yearn, maker, compound, aave, snx…

**Comment by LefterisJP** [comment]
Thanks a lot for the feedback cuokuchi!

I read the description of the issue and was wondering what you meant. But then I read the title and I guess you are the person who requested balancer support.

So let's keep this issue for balancer. I may edit the description a bit to add a specification later when we go to implementation.

> analytics and tax reporting for Balancer, Tokenset, curve, uniswap, maker, yearn, maker, compound, aave, snx…

Maker is there. Aave is there. Profit/loss and historical report for both (premium users only)

Yearn vaults is coming next release. Compound lending and borrowing too. Historical event analysis and profit/loss report will be premium only.

For the rest we will indeed prioritize them. There is an issue for Tokensets already: https://github.com/rotki/rotki/issues/1010.

Could you make on for Synthetix? Or anything else you think you may need? We will try to prioritize according to our resources and what most people ask for.

**Comment by cuokochi** [comment]
Hello Lefteris, 
Yes. I'm the same person who requested adding support for Balancer on twitter. 
I had issues trying to process payment with a credit card. The "pay now" button was inactive when I got to the next page. I was able to process payment with dai. I received an invoice confirming payment has been received. 

"The payment was completed via a transaction of 112.42534255DAI. Transaction hash:0xc0288002d1f590b9a9867d3f5067c4916a732ae1453ec745764e1cc089fdf636"
However, when I click on the statistics page on the app, I keep getting " No premium subscription noted..."








Also looking at the defi page I can see there's work in progress and I'm really excited about the prospects for this app. It accurately captures my positions in yvaults and ygov.
I noticed on the curve tab, 4.59 crvrenwsbtc displays a value of 4.61USD instead of ( 4.59 * current price of BTC)
It does a great job of displaying unlocked CRV available for claim from vesting but not;1. CRV available for claim from gauges2. Vote locked CRV





Thanks
Chimezie Okochi 

    On Saturday, September 19, 2020, 11:12:45 AM PDT,  Karapetsas <notifications@github.com> wrote:  
 
 


Thanks a lot for the feedback cuokuchi!

I read the description of the issue and was wondering what you meant. But then I read the title and I guess you are the person who requested balancer support.

So let's keep this issue for balancer. I may edit the description a bit to add a specification later when we go to implementation.


analytics and tax reporting for Balancer, Tokenset, curve, uniswap, maker, yearn, maker, compound, aave, snx…


Maker is there. Aave is there. Profit/loss and historical report for both (premium users only)

Yearn vaults is coming next release. Compound lending and borrowing too. Historical event analysis and profit/loss report will be premium only.

For the rest we will indeed prioritize them. There is an issue for Tokensets already: #1010.

Could you make on for Synthetix? Or anything else you think you may need? We will try to prioritize according to our resources and what most people ask for.

**Comment by LefterisJP** [comment]
@cuokochi Let's keep this issue about Balancer labs. For support questions it's better to join discord: https://discord.gg/aGCxHG7 and ask a question in the support channel. Please do so and we can help you further there.

I am going to delete your comment since it contains some personal information for you and this is github, a public forum.

**Comment by cuokochi** [comment]
Oh my! Wasn't aware of that. Thanks for deleting. 
 

    On Sunday, September 20, 2020, 12:36:45 AM PDT, Lefteris Karapetsas <notifications@github.com> wrote:  
 
 


@cuokochi Let's keep this issue about Balancer labs. For support questions it's better to join discord: https://discord.gg/aGCxHG7 and ask a question in the support channel. Please do so and we can help you further there.

I am going to delete your comment since it contains some personal information for you and this is github, a public forum.

**Comment by emansipater** [comment]
Is that pull request still being worked on?

**Comment by LefterisJP** [comment]
It was the developer test for @vnavascues, our new team member. It will be finished in the milestone that balancer needs to go in.
