### ISSUE TITLE
Allow per protocol reset of DB data in Defi deposits

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1498]
## Problem Definition

![2020-09-21-104840_234x220_scrot](https://user-images.githubusercontent.com/1658405/93748782-19699600-fbf9-11ea-8ce2-9df786905f94.png)

Right now only AAve data are resettable in the "Deposits" DeFi section. All protocols for which `reset_db` option exists in the API should be possible here and additionally the user should be able to select a single, or a selection of protocols to reset. Shouldn't force reset all as this may take ages.

## Task

Do it

**Comment by kelsos** [comment]
### Note
- Make the protocols to reset selectable in the confirmation popup.
- Make the loading action work with selected protocols for reset.
