### ISSUE TITLE
Go through all ethereum.get_logs() calls and remove unnecessary deserialization

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1499]
## Abstract

After streamlining the return of ethereum.get_logs() between web3 and etherscan (https://github.com/rotki/rotki/pull/1483/commits/e4af64c3eff9a8e8012c45280557e3f9abb43e7f) we no longer need all those deserialization calls for each log key that may be different between each differt type of source as that's now done in the get_logs() call itself.

## Task

Go through it and clean up

**Comment by wschwab** [comment]
Does this mean just finding each instance of `ethereum.get_logs` and taking out a deserialization call? If so, could you give me one example from the codebase so I'd know what I'm looking for?

**Comment by LefterisJP** [comment]
Hey @wschwab it is a little more complicated than that. You have to visit all the calls, and see any deserialization calls around it and check if they are already done properly inside the get_logs.  I will probably address it right now myself.
