### ISSUE TITLE
Rotki failed to start due to address already in use

### ISSUE THREAD

**Issue by coblee** [rotki/rotki#1500]
## Problem Definition

The app won't start and shows me a failed to start error with this error:

[92790] Failed to execute script rotkehlchen-script

Traceback (most recent call last):
  File "build/rotkehlchen/rotkehlchen-script.py", line 2, in <module>
  File "rotkehlchen/__main__.py", line 37, in main
  File "rotkehlchen/server.py", line 54, in main
  File "rotkehlchen/api/server.py", line 249, in start
  File "gevent/baseserver.py", line 323, in start
  File "gevent/pywsgi.py", line 1478, in init_socket
  File "gevent/server.py", line 180, in init_socket
  File "gevent/server.py", line 192, in get_listener
  File "gevent/server.py", line 288, in _tcp_listener
OSError: [Errno 48] Address already in use: ('127.0.0.1', 4242)
Rotki API server is running at: 127.0.0.1:4242

### System Description

I'm running this on a Mac OSX 10.15.6

**Comment by LefterisJP** [comment]
Hey @coblee thanks for trying Rotki out.

Which version is it? Is it the latest one? v1.7.0?

Sounds as if you have another instance of the app running underneath.

Can you do 

```
ps aux | grep rotki
kill -9 PIDOFPROCESS
```
Where pidofprocess is the PID returned by the `ps`.

The issue sounds similar to a very old one which should now be fixed: https://github.com/rotki/rotki/issues/767

**Comment by coblee** [comment]
No, I don't have another instance of it running. Maybe the port conflicts with another application I have running on the same port.

**Comment by coblee** [comment]
yes, it's the latest version

**Comment by LefterisJP** [comment]
> No, I don't have another instance of it running. Maybe the port conflicts with another application I have running on the same port.

That could be an explanation. Can you maybe [check](https://stackoverflow.com/a/4421674/110395) if any other application uses 4242 in your system?

**Comment by coblee** [comment]
Nothing comes up searching for anything listening on 4242.

**Comment by coblee** [comment]
I found another way to list the apps and found out it's CrashPlan's service. I killed that and now it works. Thanks.

**Comment by LefterisJP** [comment]
Glad to see you solved this. My question is, how did it work? Is there something we can do on Rotki's side to make this not happen even if someone runs this CrashPlan?

We still got the issue of conflicting port that we have to fix. @kelsos do you know which issue it was?

**Comment by coblee** [comment]
Maybe you can have different ports you can use if the first one doesn't work.
