### ISSUE TITLE
Allow ability to hide/ignore balances of some coins

### ISSUE THREAD

**Issue by coblee** [rotki/rotki#1501]
## Abstract

My ethereum address got sent some tokens that I don't care about. They are worth pennies. Please add the ability to hide and ignore these tokens so it won't show up in my dashboard.

## Motivation

This will make the dashboard much cleaner. Maybe just add a right click to hide coin option. And a settings to manage hidden coins. You may even reuse the settings in accounting section that lets you ignore coins for accounting.

## Specification

If the feature is techical in nature please write as detailed as possible a specification of what needs to be built.

**Comment by LefterisJP** [comment]
Hah that's interesting. So the ignored assets for accounting does not reflect in the dashboard assets? We can do that definitely.

**Comment by coblee** [comment]
Hiding these assets from the dashboard would solve my problem. I nice to have is ability to right click and hide. But that's not necessary and might even create more headaches if it's too easy to accidentally hide a coin.
