### ISSUE TITLE
Allow negative balances (e.g. for bank accounts or loans)

### ISSUE THREAD

**Issue by philhug** [rotki/rotki#1513]
## Abstract

Bank accounts can have negative balances. It is currently not possible to enter such balances in rotki.

## Motivation

Allow tracking of all assets including negative ones.

## Specification

```
Change api/v1/encoding.py
class ManuallyTrackedBalanceSchema(Schema):
-    amount = PositiveAmountField(required=True)
+   amount = AmountField(required=True)
```

**Comment by LefterisJP** [comment]
Hey @philhug thanks a lot for the issue. So do I understand correctly you want to track negative balances in the manually tracked balances?

And this is for things such as overdraft, right?

**Comment by philhug** [comment]
yes, like overdrafts, liabilities, crypto- oder other loans

**Comment by LefterisJP** [comment]
For crypto loans and other liabilities we don't have them as negative numbers. We don't show it yet (it's calculated under the hood) but should do it for this issue: https://github.com/rotki/rotki/issues/1400. You can also see each liability (say compound, aave, maker) if you go to the corresponding section.

For general non-overdraft liabilities we should perhaps add a special type of manually tracked balance that would be "liability" and it would go under the liabilities section of the dashboard when #1400 is implemented. Would that make sense?

**Comment by kilrau** [comment]
> For general non-overdraft liabilities we should perhaps add a special type of manually tracked balance that would be "liability" and it would go under the liabilities section of the dashboard when #1400 is implemented. Would that make sense?

Makes sense and highly interested in this feature too!

**Comment by kilrau** [comment]
Since DeFi liabilities have an own section in the overview now (btw should hide if there are no entries imo), I think it's time to give users the option to manually enter liabilities either simply as negative numbers or via drop-down under "Manual balances".
