### ISSUE TITLE
Celsius Support

### ISSUE THREAD

**Issue by VoR0220** [rotki/rotki#1516]
## Abstract

Add support for Celsius App 

## Motivation

It would be nice for people who refuse to join the DeFi revolution in full to be able to see how their celsius funds are holding up and bring that into the general reporting mix.

**Comment by LefterisJP** [comment]
Is it this app: https://celsius.network/ ?
The only API I found is this: https://developers.celsius.network/

Would have to look it up a bit more. But it works like other exchanges do, right? Just need the user (you) to give an API key to Rotki?

**Comment by VoR0220** [comment]
I would imagine so. I haven't dove in. I just know that it's pretty popular and rotki would benefit from adding this.

**Comment by VoR0220** [comment]
https://developers.celsius.network/swagger/

seems like there's only like 2-3 calls that you would need to really worry about.

**Comment by episk** [comment]
Was going to request Celsius integration, but I see you're already set to go basically.

If this still can be of any help, [here's how the user generates the API.](https://developers.celsius.network/createAPIKey.html) with 4 optional parameters.

Here's the current UI with in better image quality.
![ui-cel](https://user-images.githubusercontent.com/17725761/113500700-ac23af80-950f-11eb-9f83-578b8c37f9dd.png)

The generated API is  actually a standard UUID `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` so theres no public/private pair and the placeholder doesn't really show that. Getting any data out might require "partnership" but this is definitely something Celsius would implement in a heartbeat. While it's centralized custody, they are quite loud when it comes to bashing banks.

(and sorry if this is all super basic stuff, just wanted to help) :)

**Comment by LefterisJP** [comment]
Hey all. If you guys would like to see Celsius support could one of you join discord and provide us with a read-only key for testing? 

I sent an email to Celsius partners support to see if this can be achieved. The problem I see from their docs is that any such partnership assumes a centralized website. We can't really ship a private key with the application.

**Comment by LefterisJP** [comment]
This is not possible to do. The API key integration can not work with rotki due to being centrally controlled and they want their "partner" apps to be centralized.

Is there a CSV? If there is a CSV then it would be possible to import data from there. IF not then it's not possible to integrate with Celsius.

@VoR0220 @episk can you export data from celsius via CSV? If yes can you provide example data files?

**Comment by LefterisJP** [comment]
Removing this from milestones until more information can be provided/found in how it can be implemented.

**Comment by jimsjoh** [comment]
@LefterisJP users can export to csv, example attached

[transactions-export-97xyx53y-xyx5-48xy-x3y9-80xy025668x3.csv](https://github.com/rotki/rotki/files/7173813/transactions-export-97xyx53y-xyx5-48xy-x3y9-80xy025668x3.csv)

**Comment by LefterisJP** [comment]
Celisus has declared bankruptcy. No further integrations make sense.
