### ISSUE TITLE
Allow adding price for a token/asset if no price can be found

### ISSUE THREAD

**Issue by Souptacular** [rotki/rotki#1520]
## Abstract

If a price for a token or asset cannot be automatically found, give the user the ability to enter the price manually. This issue combines well with [this other issue](https://github.com/rotki/rotki/issues/1519) to allow for custom Ethereum tokens.

## Motivation

Custom tokens are sometimes small enough to not be listed on traditional exchanges, or, they will eventually get listed, but are not yet. I want to be able to record my transactions after they happen on exchanges like Uniswap who allow for custom token listings, but may not have great interfaces for the traditional price of the token until it becomes more popular.

## Specification

Here is an example of an interface I have used to accomplish this in a different program.

![Example](https://user-images.githubusercontent.com/3460120/94322525-74342200-ff58-11ea-805f-c6fe28342dfd.gif)

**Comment by LefterisJP** [comment]
Thank you for making the issue Hudson and especially for showing an example interface of how adding a custom price for a timestamp could look like in the UI.

**Comment by LefterisJP** [comment]
Okay so for this issue we would need:

1. A new api endpoint that adds custom prices per asset, per timestamp. Timestamp can be any time in the past or can also be current price which should be a special value. I think in this case the endpoint can be the same for both cases.
2. Adding those would essentially save in the price_history directory where the caches of coingecko and cryptocompare are:
    - For time + price:  the mapping of timestamp asset pair, timestamp and price
    - For current price: The mapping of asset pair and price.
3. When a current price is queried from the inquirer, first the inquirer should look if the asset pair has a custom price given by the user in any such file
4. When a historical price is queried from the price historian, the price historian should first look if the asset pair has a custom price, and if the custom price's timestamp has an entry in there. It's an open question how to have the data in the file arranged. How can we map time, timerange to price?
5. The frontend (@kelsos ) should make a nice UI in the frontend for the user to add this data in. Keep in mind we will also have the ability in the future to add custom tokens too (https://github.com/rotki/rotki/issues/1519) and perhaps even more custom data. So a dedicated area to add custom data would make sense.

Also we can in the future prompt the user to input a custom price for a date/timestamp when the backend has not found a price. Related: https://github.com/rotki/rotki/issues/1797
