### ISSUE TITLE
When adding accounts, a leading space leads to an error not recognizing valid address

### ISSUE THREAD

**Issue by spaceblankey** [rotki/rotki#1523]
## Problem Definition

If there is a leading space (common when copy/pasting) before an address, the interface will report an error that it is an invalid address.

Suggest removing any leading spaces automatically so user does not get confused or frustrated

### System Description

error: Given value 34...juE is not a valid bitcoin address
```

**Comment by LefterisJP** [comment]
Thanks @spaceblankey. This will go in the upcoming v1.8.1 small release.

**Comment by joeylnguyen** [comment]
Hello! I would like to take this issue. Is there anything I should keep in mind before getting started?

**Comment by kelsos** [comment]
Hey, @joeylnguyen I don't have anything specific in mind. I would probably just trim any whitespace on input/paste.

**Comment by LefterisJP** [comment]
Hey @joeylnguyen if you are not going to pick this up within the next day then we will probably just fix it ourselves since we would like this to go in the release.

**Comment by joeylnguyen** [comment]
Hey @LefterisJP, apologies for not getting on this sooner. I will have this done by today!

**Comment by joeylnguyen** [comment]
Hey @LefterisJP, I started working on this today, but I'm running into issues with setting up the dev env. Unfortunately, I'm not sure if I can troubleshoot and implement the fix for this issue by your release schedule. If it's in your best interest to unassign me and fix yourselves, then please do so. Apologies for not tackling sooner, otherwise this could've been avoided.

**Comment by LefterisJP** [comment]
No problem and no need to apologize. It's really an easy issue for us that's why I wanted to leave it out there a bit to see if someone would pick it up.

@kelsos also handle this today then

**Comment by kelsos** [comment]
@LefterisJP Sure, @joeylnguyen could you also please let us know what issues did you run during the environment setup? It would be good to know to improve our development guide.
