### ISSUE TITLE
Accounts & Balances click to see account breakdown

### ISSUE THREAD

**Issue by GregTheGreek** [rotki/rotki#1531]
## Abstract

When a user is on the accounts & balances page and a token has a balance, the the user should be able to click on one of the tokens to see a breakdown of which accounts contain that specific token.

## Motivation

Allows users to quickly see a breakdown of which accounts are holding a specific token.

## Specification

n/la

**Comment by LefterisJP** [comment]
Hey @GregTheGreek thanks for the feedback! Would you say that https://github.com/rotki/rotki/issues/1147 accurately describes what you are looking for too?

**Comment by GregTheGreek** [comment]
yep! Will close!
