### ISSUE TITLE
Couldn't enter BCAP (Blockchain Capital) manual amount.  app reported an error

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#1538]
## Problem Definition

Provide a description of what is the current problem and why you are raising this issue.
If it's a bug please describe what was the unexpected thing that occured and what was the
expected behaviour.

Rotki also logs debug information to the `rotkehlchen.log` file. Please attach it to the
issue as it may help us find the source of the issue faster.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v geth && geth version
command -v parity && parity --version
command -v rotki && rotki version
[ -d .git ] && git rev-parse HEAD
```

**Comment by LefterisJP** [comment]
Hey @JezSan I am sorry but I do not understand what you tried to do or what the error was. Can you add some details in the issue? You seem to have not altered the template.

**Comment by JezSan** [comment]
hey Lefteris, I tried to use 'add manual balance' to add some BCAP tokens to my account, and it was throwing up an error.  but I tried again just now and it worked, so I don't know what it was, and it may have been a temporary problem.

**Comment by LefterisJP** [comment]
Hm I see. Thanks for letting us know and glad it worked out in the end.

Is it okay with you if we close the issue then since it's non-actionable from our side without any more information? You can re-open if you see it again and provide us with the exact error so we can track down any potential bugs.
