### ISSUE TITLE
uniswap liquidity status, showing what tokens are in your LP account and their current value

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#1543]
## Abstract

Please describe by example what problem you see in the current Rotki implementation that you would like addressed.

## Motivation

In this section please describe how you propose to address the problem you described earlier. Try to include example use cases that showcase the value of your proposal.

## Specification

If the feature is techical in nature please write as detailed as possible a specification of what needs to be built.

**Comment by LefterisJP** [comment]
Hey @JezSan thanks for the issue but please write in the issue description and not just leave the template as it is.

I am closing this as duplicate though: https://github.com/rotki/rotki/issues/717

We hope to have this done in version 1.9.0.
