### ISSUE TITLE
Rotki dark mode (or selectable color scheme) in the UI

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1549]
## Abstract

It's quite interesting that multiple users have requested the option to have some sort of dark mode or even selectale color schemes for the UI. There is some sort of fascination with crypto users and dark mode.

This is definitely something we can add as extra in our premium service.

## Task

Do it. @kelsos **when you find time** spec the issue out what it would need to be done in the UI and also for it to be premium only. Milestone is at the moment arbitrary and non-binding

**Comment by markoprljic** [comment]
Can we tag this as "Design" as well?

**Comment by emansipater** [comment]
Strongly in support of this feature.  Dark mode is extremely useful when working at night or just to save power on my laptop in general.

**Comment by dlehenky** [comment]
New premium user and Gitcoin donor: This is a must for me :) Vision issues, especially at night, make bright backgrounds very difficult. Really looking forward to this feature addition!

**Comment by kelsos** [comment]
I will have to move it to the next release since there is a bit more work that I expected originally.

**Comment by lukemulks** [comment]
Premium customer; very exciting seeing this feature merged!

**Comment by dlehenky** [comment]
Me too! Gonna wait for the release, though.
