### ISSUE TITLE
Show total balance for each XPUB account

### ISSUE THREAD

**Issue by coblee** [rotki/rotki#1560]
## Abstract

In the `BTC per account balances` section, show the sum of the BTC and fiat values of all the addresses belonging to the XPUB account. Right now, it shows BTC and fiat values for each address, but shows nothing for the parent XPUB entry.

## Motivation

For XPUB accounts that have a lot of addresses, it's useful to collapse all the addresses. And having the sum of all the coins in the parent entry will be very useful.

## Specification

If the feature is techical in nature please write as detailed as possible a specification of what needs to be built.

**Comment by coblee** [comment]
Can consider only showing the sum if that XPUB entry is collapsed.

**Comment by LefterisJP** [comment]
Good point. We will do this. Thanks for the issue!
