### ISSUE TITLE
Introduce xpub information to the GET /api/1/blockchains/BTC

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1563]
## Problem Definition

This is about GET `/api/1/blockchains/BTC`

The endpoint currently returns an array of the following objects:

```Typescript
interface AccountData {
  readonly address: string;
  readonly label: string;
  readonly tags: string[];
}
````
It would be good to include the xpub information in the data. Also if possible it would be great if we could somehow also provide these xpubs that have no detected accounts.

### Task
- Include information

**Comment by LefterisJP** [comment]
Related to: #1558
