### ISSUE TITLE
Binance Failed Query

### ISSUE THREAD

**Issue by wchance** [rotki/rotki#1568]
## Problem Definition
When ever trying to sync I get the following error

Failed query for Binance: Error: Binance API request https://api.binance.com/api/v3/myTrades?symbol=WAVESTUSD&fromId=0&limit=1000&recvWindow=10000&timestamp=1602022079864&signature=a7f7e7eaf822d7e89817d0e05eb2c8f7c20c03a7f5a0a740c035e880fc8031fb for myTrades failed with HTTP status code: 400, error code: -1022 and error message: Signature for this request is not valid.

### System Description

Windows 10 with Rokti v1.8.1

**Comment by LefterisJP** [comment]
Hey @wchance thanks a lot for using Rotki and for opening this issue.

Let's see how we can help you. Some questions.

1. Is this the first time you are using Rotki?
2. Have you used binance and Rotki before?
3. Does it work when you restart?
4. What are the API key permissions you gave to the API key you created in Binance? Below is an example of the needed ones.

![2020-10-07_00-27](https://user-images.githubusercontent.com/1658405/95266702-fca5a300-0833-11eb-8288-dcd6780b5d8a.png)

Also can you perhaps share with us the log (not in here, but via discord DM: https://discord.gg/aGCxHG7) of the rotki run where this happened? You can find the location of the logs from the top "Help" menu. Help -> Logs directory. And give us the `rotkehlchen.log` file.

**Comment by wchance** [comment]
> Hey @wchance thanks a lot for using Rotki and for opening this issue.
> 
> Let's see how we can help you. Some questions.
> 
> 1. Is this the first time you are using Rotki?
Yes
> 2. Have you used binance and Rotki before?
No
> 3. Does it work when you restart?
No, I got the same error and also have a new issue "Sync Error" Detected remote database BUT with older modification timestamp.
![image](https://user-images.githubusercontent.com/7815792/95267537-7ffad080-0803-11eb-84a4-ffd8a49af1d1.png)
> 4. What are the API key permissions you gave to the API key you created in Binance? Below is an example of the needed ones.
I am setup correctly.
> 
> ![2020-10-07_00-27](https://user-images.githubusercontent.com/1658405/95266702-fca5a300-0833-11eb-8288-dcd6780b5d8a.png)
> 
> Also can you perhaps share with us the log (not in here, but via discord DM: https://discord.gg/aGCxHG7) of the rotki run where this happened? You can find the location of the logs from the top "Help" menu. Help -> Logs directory. And give us the `rotkehlchen.log` file.
I will reach out in discord.

**Comment by LefterisJP** [comment]
> No, I got the same error and also have a new issue "Sync Error" Detected remote database BUT with older modification timestamp.

This is fine. You have a premium account and have activated the DB sync.This is not an error, we have to change the Title of that message. It's an informational message. It's just telling you that there is a different DB in the Rotki remote server with different metadata and asking you if you want to replace the local copy.

You can just say no. Also if you don't need to sync between different machines you should probably just disable the premium sync option.

> Have you used binance and Rotki before?
> No

This makes me think that it's a mistake with copying of the API key or something like that.

**Comment by LefterisJP** [comment]
@wchance If I recall correctly you said in discord that your problem is solved. If that is so can we close this issue?
