### ISSUE TITLE
Change the premium DB sync message to not call itself an Error

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1569]
## Problem Definition

When syncing the DB of a premium user with the server at the start there is almost always going to be this message.
![2020-10-06_23-51](https://user-images.githubusercontent.com/1658405/95268181-198fa580-0837-11eb-80e0-50fbd021b6d5.png)

Since we don't know if the user wants to keep the local or the remote DB when they have sync open we have to ask. Can't make a decision based on size and timestamp alone.

But when asking we should not display this as an error. Users [think](https://github.com/rotki/rotki/issues/1568#issuecomment-704591121) that something bad happened.

## Task

- [ ] Change the title of the pop up. It should not be an error. It's an informational message asking for a user choice.
- [ ] Display the different data better. It's just a very long string and is hard to read at the moment. The string is populated and sent from the backend. Tried to add `"\n"` from the backend but that did not work.

**Comment by kelsos** [comment]
Like we discussed for the second task it would be preferrable to return the values in some kind of payload, and let the frontend handle the message itself

**Comment by LefterisJP** [comment]
I can look into the payload thing.

**Comment by kelsos** [comment]
Good I will start the color-changing part and we can sync later on that front

**Comment by LefterisJP** [comment]
This is fixed by #1580
