### ISSUE TITLE
Create transaction decoder for ygov.finance

### ISSUE THREAD

**Issue by mariodigital** [rotki/rotki#1574]
The[ ygov.finance Governance 2 Contract](https://etherscan.io/address/0xBa37B002AbaFDd8E89a1995dA52740bbC013D992) seems to be missing from the DeFi "Deposits" page. It does show up under Overview...

![image](https://user-images.githubusercontent.com/12964883/95330800-5c8a6100-08a9-11eb-9000-f64da4091d27.png)
![image](https://user-images.githubusercontent.com/12964883/95330927-8774b500-08a9-11eb-922b-b2145b0f44de.png)

**Comment by LefterisJP** [comment]
Yeah this is not a bug. We just don't support ygov historical stuff yet. What you see in the overview is the overview of the account provided by current balances of what our system can detect. For historical stuff in the deposits/borrowing and generally the details part it requires extra work on our side for each protocol.

So we can add yfi governance there too once we can prioritize in. Should not be hard.

**Comment by LefterisJP** [comment]
@yabirgb when doing the yearn stuff do you think yfi governance can also be included? I don't recall details anymore but isn't it easy to add?

**Comment by yabirgb** [comment]
I'll have a look but I believe is not in the graph. But when adding v2 I'm going to investage more on this

**Comment by yabirgb** [comment]
The governance contract is not in the graph so will need to be queried in its own

**Comment by LefterisJP** [comment]
I am changing this issue, since we move away from the "DeFi" view to simply write a transaction decoder for this ygov contract
