### ISSUE TITLE
Update documentation for Windows build/development

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1581]
## Problem Definition

Breakdown the learnings and information from building the windows CI script, and update and the Windows installation/develop guide.

**Comment by LefterisJP** [comment]
Hey @kelsos is this still needed? Did you add docs already? What exactly did you have in mind for the issue?

**Comment by kelsos** [comment]
No, I didn't. It requires me to go step by step and describe what you need to do in order to be able to build the app in Windows

**Comment by LefterisJP** [comment]
Still open @kelsos. Moving it to next milestone.

**Comment by kelsos** [comment]
As we discussed until we get rid of the part of building SQLcipher and pysqlcipher for windows this is overly complicated due to the requirements to build the two mentioned dependencies.

It will be simplified with #2740 though
