### ISSUE TITLE
Allow designation of a blockchain transaction as income or as expense

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1596]
## Abstract

Right now in order to specify an ethereum transaction as an expense or income, a user has to add a new "manual trade". That's definitely suboptimal UX.

It would be really nice if the user could click on a blockchain transaction in the UI and add it as either an expense or an income.
Income should further be subdivided into normal income and dividends as per [this](https://github.com/rotki/rotki/issues/1596#issuecomment-732463955) comment.

Probably [https://github.com/rotki/rotki/issues/1477] needs to also have been implemented beforehand to know what the transaction actually does.

Related issue: https://github.com/rotki/rotki/issues/1662 (allow addition of income/loss/expense as manual actions)

## Task

![2020-10-16_10-01](https://user-images.githubusercontent.com/1658405/96229417-2af35300-0f97-11eb-99f0-6b6d78cbfc9f.png)

- Add a new button in each transaction in the UI which will allow the user to add things to the transaction. Perhaps add tags, add names, and for the purpose of this issue, designate it as income or expense.
- New api endpoint to add metadata to a blockchain transaction.
- Implement the logic of classifying a blockchain transaction as income or expense and generally having metadata for each transaction in the backend.
- Take into account income/expenses in the accounting/tax report

**Comment by dankrad** [comment]
This may only be relevant for a small minority of users, but if it's easy to do, further dividing income into normal income and dividends would be beneficial. Many jurisdictions differentiate between the two.

**Comment by LefterisJP** [comment]
@dankrad Thanks a lot for the contribution to the issue. Will add it to the OP. Having 1 additional type should not be a problem and if it helps even 1 user it's worth it.

**Comment by jamesmorgan** [comment]
I think this is super important. 

It would be good, for me anyway, to be able to tag a few different types of options, some of my specific use cases:

 * sender address - e.g. a specific client pays me X ETH for doing Job Y
 * being able to track payments from a contract address - e.g. NFT sales from OpenSea or KnownOrigin
 * being able to label spends in some form - e.g. my Rotki premium purchase as a business expense

Thanks for a wicked product and looking forward to the future enhancements

**Comment by LefterisJP** [comment]
Related issue:  https://github.com/rotki/rotki/issues/1662

**Comment by Michael-A-Heuer** [comment]
The centralized tax software accointing.com works with a tax consulting company and has come up with a quite extensive list of classifications.
Classifications for income transactions would be
- add funds (if you transferred it from an account you own)
- income
- swap
- lending income
- mining
- master node
- initial coin offering (ICO)
- over the counter trade (OTC)
- margin gain
- bounty
- gift received
- airdrop
- hard fork
- gambling income

and for expenses
- remove funds (if you transferred it to an account you own)
- payment
- swap
- fee
- gift sent
- over the counter trade (OTC)
- gambling use
- margin fee/loss
- interest paid
- lost (private keys are gone)

By specifying how these transaction types are treated tax-wise, the user could adapt the tax software to a specific legislation.

**Comment by LefterisJP** [comment]
I think this should have https://github.com/rotki/rotki/issues/1477 as a prerequisite, since we need to decode and understand what a transaction does if we are to designate it as anything

**Comment by LefterisJP** [comment]
This is now done. All transactions are editable and can be classified as income or expense. By default money out to external accounts is expenses. Money in from other accounts is income. Other/external means not tracked/owned by the user.

**Comment by dankrad** [comment]
Amazing, thank you!
