### ISSUE TITLE
Can't open rotki v1.8.2 in OSX < 10.15

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1636]
## Problem Definition

Since changing the build process to have the binaries generated by Github actions, since they use a Catalina VM for OSX the generated binary apparently can't run on anything with a version lower than Catalina.

Error looks like this:

```
[674] Error loading Python lib '/var/folders/t0/dyflx2wx0tv8hm2cvhgpp0sc0000gn/T/_MEIXStvFQ/libpython3.7m.dylib': dlopen: dlopen(/var/folders/t0/dyflx2wx0tv8hm2cvhgpp0sc0000gn/T/_MEIXStvFQ/libpython3.7m.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /var/folders/t0/dyflx2wx0tv8hm2cvhgpp0sc0000gn/T/_MEIXStvFQ/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/t0/dyflx2wx0tv8hm2cvhgpp0sc0000gn/T/_MEIXStvFQ/libintl.8.dylib
```

## Task

Try to fix this as we are excluding users who have not (or can not) upgrade to Catalina from using Rotki

**Comment by Billyjameshowell** [comment]
Running OSX 10.13.6 and getting the same error
