### ISSUE TITLE
Support pickle finance historical profit queries

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1652]
## Abstract

Support historical queries of pickle finance: https://pickle.finance/
 
Docs: https://docs.pickle.finance/  (WIP)
## Task

Do it

**Comment by LefterisJP** [comment]
This would be handled by proper accounting on jars. So with the decoders this should be okay? @yabirgb

**Comment by yabirgb** [comment]
@LefterisJP Decoders will take care of the accounting part but another missing piece here is the historical prices. For that you need to get the "state of the pool" to get the price. That can be done with an archive node, otherwise you need to manually add the price for the pickle assets

**Comment by LefterisJP** [comment]
> @LefterisJP Decoders will take care of the accounting part but another missing piece here is the historical prices. For that you need to get the "state of the pool" to get the price. That can be done with an archive node, otherwise you need to manually add the price for the pickle assets

Yes I see. The archive node is going to be one of the next problems we face, for a lot of stuff. We need a way to query archive state for all users, even those that do not have their own archive node.

But still this is a different issue:

https://github.com/rotki/rotki/issues/2227
https://github.com/rotki/rotki/issues/1738


So for this one you think we can close or leave open until other stuff are implemented?

**Comment by yabirgb** [comment]
Since It is stuff related to how we get prices and not the accounting itself and we already have decoders for this events I'll just close the issue
