### ISSUE TITLE
Support jar/farms current balance queries for pickle.finance :cucumber: 

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1656]
## Abstract

They got their own system for farming with the jars and the farms. Understand how it works and then support proper balance queries for all.

https://pickle.finance/jars
:cucumber: 

Docs: https://docs.pickle.finance/  (WIP)

## Task

Do it.

**Comment by LefterisJP** [comment]
@yabirgb you interested in doing this at some point? Otherwise I will close this as a bit too specific.

**Comment by yabirgb** [comment]
@LefterisJP Yes, for me would be useful. If it is out of scope for our resource right now I can also do it in my free time
