### ISSUE TITLE
Import native segwit xpubs from ledger live

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1664]
## Problem Definition

Users have reported inability to import native segwit bitcoin xpubs from ledger live.

## Task

It seems that importing a native segwit xpub from ledger live somehow has a different format than the ones we tested with from electrum and wasabi. Ask around and try to figure out why that is the case. Perhaps also test with an actual ledger device.

Once figured out make the proper adjustments to the code to also import those xpubs.

**Comment by aspiers** [comment]
This problem affects me.  I have a Ledger Nano X and am happy to act as a debugging proxy ;-)

**Comment by vnavascues** [comment]
Hi, below an example of derivation path provided by Ledger Live:
```json
{
  ...
  "freshAddressPath": "44'/0'/0'/0/1",
  ...
}
```

Rotki will fail processing it at `rotkehlchen/chain/bitcoin/utils.py::is_valid_derivation_path()` for the following reasons:

- It does not start with `m`.
- It contains hardened nodes (`'`).

It will work with `"m/44/0/0/0/1"`.

**Comment by LefterisJP** [comment]
Hey @vnavascues forget about derivation path. We are not using it apart from really arcane cases.

The user needs to provide an account xpub, without any derivation path. They need to find out what their account xpub is. By not providing any derivation path and choosing the correct xpub type it should work.

FYI: A derivation path with `'` means hardened path which means you need to have the private key to derive anything.

**Comment by JezSan** [comment]
Is segwit xpub importing working?   I cant get it to work.   trying to import my xpub as exported out of a ledger nano using the Live app.  the legacy xpub works but the segwit one doesnt.  and the error message it gives is very unhelpful.

**Comment by LefterisJP** [comment]
Better wait until next version to iron out some bugs @JezSan. But specifically for Ledger live they seem to have a different kind of xpub. We don't yet have a ledger to test.

But users in our discord have successfully reported importing native segwit ones from ledger live by first using this tool https://jlopp.github.io/xpub-converter/ to convert them to zpub or ypub.

**Comment by aspiers** [comment]
[**@LefterisJP**](https://github.com/LefterisJP) commented on [November 8, 2020 2:29 PM](https://github.com/rotki/rotki/issues/1664#issuecomment-723584756 "2020-11-08T14:29:02Z - Replied by Github Reply Comments"):
> Better wait until next version to iron out some bugs [@JezSan](https://github.com/JezSan). But specifically for Ledger live they seem to have a different kind of xpub. We don't yet have a ledger to test.

Well you kind of do, because I offered to help using mine ;-)

> But users in our discord have successfully reported importing native segwit ones from ledger live by first using this tool [jlopp.github.io/xpub-converter](https://jlopp.github.io/xpub-converter/) to convert them to zpub or ypub.

I tried zpub but it didn't work yet.  However I don't know if I should be using zpub or Zpub or ypub or Ypub, and also whether I should import as P2PKH, P2SH-P2WPKH, or WPKH, because I have no clue what the differences are.  If there is any simple answer to this it would be appreciated :-)

**Comment by LefterisJP** [comment]
@aspiers perhaps let's take it in discord. But if you recall I tagged you in a convo with Charlie Lee where he made it work for his case by turning it into a zpub via lopps converter. zpubs are WPKH (native segwit). ypubs are P2SH-P2WPKH and xpub is the legacy one (P2PKH)

**Comment by aspiers** [comment]
Reporting in Discord that I still can't get this working: https://discord.com/channels/657906918408585217/745172610240872508/1312400124353187890
