### ISSUE TITLE
Support yearn finance v2 vaults

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1666]
## Abstract

Yearn finance current (v1) vaults are fully supported by Rotki. We need to also add support for the upcoming v2 vaults. That is both current balance tracking support and also historical profits and events history for premium users.

Mildly related: https://github.com/rotki/rotki/issues/1655

## Motivation

Yearn is one of the most core protocols in DeFi and their system has to be supported by Rotki. V2 vaults are what everyone will be switching to once they are officially published (~2 weeks from now).

## Specification

Offer the exact same functionality we have for yearn v1 vaults also for v2 vaults.

This is the interface in python from looking at their source: https://github.com/iearn-finance/yearn-exporter/blob/master/yearn/vaults_v2.py#L25-L40

Vaults v2 registry: https://twitter.com/vasa_develop/status/1351154987368390658

**Comment by lex-node** [comment]
just here to bump this & suggest supporting yearn v2 vaults = )

**Comment by LefterisJP** [comment]
Hey @lex-node back when the issue was made the v2 vaults were planned but not released yet. Are they out now? I guess yes from your bump

**Comment by lex-node** [comment]
> Hey @lex-node back when the issue was made the v2 vaults were planned but not released yet. Are they out now? I guess yes from your bump

they are released! 
![image](https://user-images.githubusercontent.com/22785114/108061159-c3184c00-700c-11eb-9597-1c9a65bdb264.png)

**Comment by bloxster** [comment]
Hi, looking forward to this issue to be solved.

**Comment by yabirgb** [comment]
@bloxster Yesterday I continued with my research following the tips that @LefterisJP gave me and found a subgraph https://thegraph.com/explorer/subgraph/salazarguille/yearn-vaults-v2-subgraph-mainnet?query=Get%20all%20Accounts from an user that yearn forked https://github.com/yearn/yearn-vaults-v2-subgraph

Tomorrow I'll try to prepare a draft for this

**Comment by LefterisJP** [comment]
So let's try to see if this can make it in v1.16.0. No promises but who knows.

**Comment by lex-node** [comment]
> So let's try to see if this can make it in v1.16.0. No promises but who knows.

@LefterisJP you are a machine!

**Comment by aaronmboyd** [comment]
Bump for this, yearn is a massive part of the ecosystem and Curve base + yearn auto-compounding is a pretty common pattern.

**Comment by lex-node** [comment]
> Bump for this, yearn is a massive part of the ecosystem and Curve base + yearn auto-compounding is a pretty common pattern.

Yeah agreed--or even just add latest version of backscratcher (yvBOOST - ETH v2), the yvBOOST / ETH pool on Sushiswap and the backscratcher pickle farm; the other v2 vaults are not as important.

**Comment by aaronmboyd** [comment]
Are you de-scoping my other v2 vaults?! =P

**Comment by yabirgb** [comment]
I want to restart work on this on Friday/Weekend. The implementation will track all/most of the v2 vaults. 

The logic will query for all the vaults using the graph but will need to be a premium feature. Doing it without the yearn v2 graph would be very difficult to maintain due to the nature of this vaults

**Comment by LefterisJP** [comment]
Yes this is a premium feature. No worries. Guys we want to do this. As mentioned many times in Twitter. We are a really small team, so please have patience. To help us spread the word about rotki. Get us more users.

**Comment by aaronmboyd** [comment]
> Yes this is a premium feature. No worries. Guys we want to do this. As mentioned many times in Twitter. We are a really small team, so please have patience. To help us spread the word about rotki. Get us more users.

I have been spreading the word! =)
