### ISSUE TITLE
Add BlockFi Transaction Import

### ISSUE THREAD

**Issue by dylancaponi** [rotki/rotki#1674]
## Abstract

Blockfi can export a CSV of deposit, transactions, interest payments, and bonus payments.
This is a request for a custom import of the BlockFi CSV into Rotki.

## Motivation

Users who have funds in BlockFi would probably appreciate this import ability.

## Specification

Example of CSV formatting:
Cryptocurrency | Amount | Transaction Type | Confirmed At
-- | -- | -- | --
ETH | 0.18089801 | Interest Payment | 2020-10-01 03:59:59
BTC | 0.00332231 | Interest Payment | 2020-10-01 03:59:59
BTC | 0.00532472 | Bonus Payment | 2020-09-15 23:59:59
ETH | 10.24809122 | Deposit | 2020-08-13 16:12:02

**Comment by LefterisJP** [comment]
Hey @dylancaponi thanks for the issue. Do they have an API in Blockfi? We strongly prefer integrating with an exchange or similar service via an API as CSV formats can change.

What are these payments exactly? I have never used BlockFi so have no idea. Is there any place to describe all possible values of the CSV and what they represent so that we can understand what to import them as?

**Comment by dylancaponi** [comment]
I’ve been nagging them about building an API but there’s no ETA.

The payments are interest payments for making your crypto available to loan through them. There are bonus payments for signup promotions and referrals.

I can make a list of all values I’ve seen but not sure if that would really be all of them.

Maybe I could just import this transaction by transaction?

**Comment by davidhildebrand** [comment]
This option would also be useful for [Nexo](https://nexo.io/), which similarly does not yet offer an API despite frequent requests, but does currently permit CSV exports with the following formatting:
`TransactionID,Type,Currency,Amount,Description,OutstandingLoanValue,DateTime`

**Comment by LefterisJP** [comment]
Hey @davidhildebrand thanks for the comment. It would be a different thing though so if you want to request a CSV import of Nexo please make another issue and post there the spec you wrote.

We don't support CSV imports at the moment from most places since they take time to implement and change often, while apis generally don't change. But if enough people request something we generally tend to devote time to do it.

Prioritising is hard with such a small team :sweat_smile:

**Comment by davidhildebrand** [comment]
> It would be a different thing though so if you want to request a CSV import of Nexo please make another issue and post there the spec you wrote.

Sorry about that!  Just split this out into a separate issue.

> We don't support CSV imports at the moment from most places since they take time to implement and change often, while apis generally don't change. But if enough people request something we generally tend to devote time to do it.
> 
> Prioritising is hard with such a small team 😅

Completely understandable!  Thanks for all that you do.  I'm new to rotki, but impressed so far.

**Comment by yabirgb** [comment]
Hello @dylancaponi ! I'm getting this implemented into rotki. Could you confirm if blockfi let's you export two files one with the information you provided and another one with trades? Also is it possible to set any other date format in BlockFi as for your knowledge? I've seen a different format but might be old information.

**Comment by dylancaponi** [comment]
@yabirgb Thanks for looking into this!

Yes there are two exports.
No, I have not seen date format options.

**Trades:**

Trade ID | Date | Buy Quantity | Buy Currency | Sold Quantity | Sold Currency | Rate Amount | Rate Currency | Type
-- | -- | -- | -- | -- | -- | -- | -- | --
dddddddd-ssdd-dddd-dsds-ddddsdssssdd | yyyy-mm-dd hh:mm:ss | 6404.6 | usdc | 42.23878904 | ltc | 151.6284 | usdc | One Time

Notes:
- not sure what the other `Type` options are here
- d = digit, s = string but i'm sure transactions id formats vary

**Transactions:**

Cryptocurrency | Amount | Transaction Type | Confirmed At
-- | -- | -- | --
LTC | -42.23878904 | Trade | 2021-02-05 11:45:58
USDC | 6404.6 | Trade | 2021-02-03 11:45:58
ETH | 0.56469042 | Interest Payment | 2021-01-30 23:59:59
BTC | 0.00052383 | Referral Bonus | 2020-12-02 23:59:59
ETH | -3 | Withdrawal | 2020-11-21 16:59:31
ETH | 0.48385358 | Bonus Payment | 2020-09-16 21:59:59
BTC | 1.11415058 | Deposit | 2020-07-20 12:10:55

Notes:
- Seems like trades show up in both
- Tried to include every `Transaction Type` I've seen

**Comment by yabirgb** [comment]
@dylancaponi Thank you for your fast response! Yes I've seen that trades are also reflected in both files. So everything should be fine. As soon as Lefteris finishes a refactor in the backend I'll be able to make a PR for my changes. Should be included in the next release :)

**Comment by LefterisJP** [comment]
@yabirgb you can start the PR but one of us will have to rebase. Probably you. Won't be that hard I guess/hope, after looking at the changes.
