### ISSUE TITLE
Add valuedefi.io integration

### ISSUE THREAD

**Issue by dylancaponi** [rotki/rotki#1675]
## Abstract

I'd like to see valuedefi.io (previously yfv.finance) integrated. Their token was [YFV](https://www.coingecko.com/en/coins/yfvalue) (support ends in two days) and now [VALUE](https://www.coingecko.com/en/coins/value-liquidity).
They've had many lucrative pools and vaults and have now expanded to providing Farming as a Service (FaaS) for new projects.
It would be amazing to see yields/rewards from this project be calculated on rotki.

## Motivation

Zapper.fi has integrated some of their pools.
TVL is $81M at time of writing.
Has had $200M+ TVL for extended periods.
In the world of DeFi this has been a pretty long lasting project so it may continue to be relevant for a while yet.

## Specification

I'm not sure where to begin on specs but pools here link out to their respective contracts:
main site: https://valuedefi.io/
legacy pools: https://valuedefi.io/legacy

**Comment by LefterisJP** [comment]
Hey Thanks @dylancaponi for putting this in our radar. We will keep this protocol in mind. We have a long backlog for DeFi projects and currently prioritize by popularity and user requests. So adding this to our backlog as something to do.

As a sidenote we support both $YFV and $VALUE and we have it noted as a swap: https://github.com/rotki/rotki/blob/06fd64b38993fa60bd455985613dc1b8141dc594/rotkehlchen/data/all_assets.json#L12939

**Comment by dylancaponi** [comment]
Thanks @LefterisJP.

For anyone reading this who wants to see valuedefi added please thumbs up this issue.

**Comment by LefterisJP** [comment]
This project seems dead. Zero TVL. Nothing new in Twitter for almost 2 years. Nothing new in Github. Crickets in discord. So not something we can devote resources on.
