### ISSUE TITLE
Enable user to force-refresh balance queries.

### ISSUE THREAD

**Issue by kascheri12** [rotki/rotki#168]
## Problem Definition

Note: @LefterisJP edited this issue to add more information for a generic solution that will satisfy force querying of all types of balances.

Original Request by @kascheri12:

> Need a way to force refresh exchange balances.
>
> I made a trade on exchange, new balances were not reflected in rotkehlchen until quit/reopen.
>
>I tried using Command+R and logging in again. I tried navigating to different pages (User Settings, Tax Report, etc) and then back to Dashboard but balances didn't change. Balances were finally updated once I quit, relaunched, and logged in.

We need a way to be able to ask for a force refresh of balances of each location independently at any point in time. And this should also ignore the cache (?).

### Frontend Work
- Add force refresh buttons on top of the dashboard's boxes for each exchange
- Add force refresh buttons on top of the dashboard's boxes for blockchain balances
- (Maybe?) add force refresh button for blockchain balances also on the user settings page.

### Backend Work

Add an option to all the above endpoints to ignore the cache checks.

**Comment by LefterisJP** [comment]
Hmmm that's interesting. There is a cache so that we don't make too many RPC calls to exchanges, but that should be max 10 minutes. Did you wait more than 10 mins or just restarted before that?

**Comment by kascheri12** [comment]
No, definitely didn't wait 10 minutes.

**Comment by LefterisJP** [comment]
But anyway this should be configurable as you said.

**Comment by LefterisJP** [comment]
Edited the original description of the issue to make the scope a bit more generic and specify what needs to be implemented.
