### ISSUE TITLE
Support for Australian exchanges

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#1682]
## Abstract
Support for Australian cryptocurrency exchanges (https://www.btcmarkets.net/, https://www.independentreserve.com/ etc).

## Motivation
In order to make Rotki more useful for Australian users, support for the main Australian cryptocurrency exchanges is needed. Especially for tax calculations.

## Specification
BTCmarkets API - https://api.btcmarkets.net/doc/v3
Indepdentreserve API - https://www.independentreserve.com/products/api
Coinspot API - https://www.coinspot.com.au/api
CoinJar API - https://docs.exchange.coinjar.com/trading-api/

**Comment by LefterisJP** [comment]
Hello @drgonzo31 thank you so much for using Rotki and for making the issue!

Would love to make the life of our Australian users easier.

But in this issue you are asking for integration of 4 different exchanges. Which is 4 different features to be implemented. Would it be possible to make another 3 issues, one for each exchange? Also could you prioritize them? If you only could get one which one is the biggest? We don't have too many resources so we need to prioritize based on exchange popularity and userbase.

**Comment by drgonzo31** [comment]
Yes I can. I'll do that now.

**Comment by LefterisJP** [comment]
Thank you @drgonzo31 !
