### ISSUE TITLE
Show staked ETH2 balance

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1694]
## Abstract

Detect if the user has staked any ETH and show it.

Think if this should be premium only or not.

## Spec

It's easy. Just check log events for `DepositEvent` on the staking contract: https://etherscan.io/address/0x00000000219ab540356cbb839cbe05303d7705fa#code

**Comment by emansipater** [comment]
Even better would be to track actual gains/losses on the beacon chain itself, Rotki would be perfect for that.  You would have to use the API from something like beaconcha.in or wait until the beacon chain node API is fully nailed down though.

**Comment by LefterisJP** [comment]
Sure ofcourse but that's another issue entirely. 1.9.0 will most probably, 99.999% be here before phase 0 launch. Step by step.
