### ISSUE TITLE
Support v2 1inch DEX aggregator

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1697]
## Abstract

Pretty much same as https://github.com/rotki/rotki/issues/1680 ... but for their new contract. Version 2: https://1inch-exchange.medium.com/introducing-1inch-v2-defis-fastest-and-most-advanced-aggregation-protocol-c42573dc3f85

Perhaps this issue can be merged with #1680 if implementation is not too different.

## Task

Figure out what's needed and if this needs to be worked on as a different issue or not.

**Comment by yabirgb** [comment]
I've noticed that if 1inch routes the trade through uniswap it will appear in the uniswap graph. When addressing this we have to take care of possible duplicates

**Comment by a7e8** [comment]
I also need this otherwise the profit/loss report is missing some trades.

**Comment by LefterisJP** [comment]
yes so do I and quite a few more users. @yabirgb we should probably schedule all versions of 1 inch (atm there are 3) in 1 go in probalby v1.20.0 or 21 release.

**Comment by yabirgb** [comment]
Did we get information of a nice way to retrieve trades information from 1inch?

**Comment by LefterisJP** [comment]
This is also done in v1.24.0 with the new decoders as we will ship with decoders for both v1 and v2.
