### ISSUE TITLE
Optimize ethereum addresses balance query by separating balances query from token detection

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#1705]
## Abstract

Need a faster way of showing current value of the asset portfolio.

## Motivation

ingesting the user's database is a slow process.  with hundreds of ethereum and bitcoin accounts, it can take a long time (many minutes).    But much of the time, the asset list hasn't changed, just the values have.  And we'd like a fast way of seeing the current value of the portfolio.

So if the local db would cache the list of assets, then it'd be nice to just be able to hit a button to see a revaluation of the existing asset list, with the latest values.  or, ideally, there would be an option where it would continually revalue the list of assets every x seconds/minutes.

Also, for UI purposes, it should be able to start up immediately, using the previously known list of assets, but show in the UI that it might be stale data.   it can do a refresh in the background, but for UI purposes, show the last known values (with an indication (eg an icon) showing that they might be stale)

## Task [by lefteris]

In order to speed up queries, we need to separate the balance querying from the token detection.

By default if the tokens of the user have been queried at least once, then all the addresses should only be queried for all the user's tokens.

Detection of tokens should not run again unless explicitly asked.

Also would make sense to move it to a background running task: https://github.com/rotki/rotki/issues/968 running on idle time

**Comment by LefterisJP** [comment]
Hey @JezSan thanks a lot for the issue. Could you perhaps make a second issue for 

> Also, for UI purposes, it should be able to start up immediately, using the previously known list of assets, but show in the UI that it might be stale data. it can do a refresh in the background, but for UI purposes, show the last known values (with an indication (eg an icon) showing that they might be stale)

I think it's a good idea but it's a different task to speeding up ethereum queries.

---

I would like to keep this issue for the ethereum balance querying. As discussed in discord what I assume makes it so slow for you is the fact that tokens are auto-detected for all addresses the first time and then auto-detection happens again next time you open it (if this is after 24 hours..

As you suggest what would make sense is to remember which tokens were detected, only query their balances, and:

1. Force auto-detection of token at balance query via the UI
2. Have the choice when to autodetect again customizable by the user. It currently is a hardcoded 24 hours.


Also a sidenote: Are you using your own node? If you use your own node queries should be considerably faster.

**Comment by JezSan** [comment]
Not currently using my own node.

Just etherscan with an api key.

Yes, im sure my own node would be faster but not currently running one.  Maybe I should point it at our ‘work' one.

**Comment by LefterisJP** [comment]
Added some comments on what to do to achieve this in the OP

**Comment by LefterisJP** [comment]
I will take the backend of this and #2124 together for next release.

**Comment by LefterisJP** [comment]
This is now implemented in develop and will roll out in 1.26.0.
