### ISSUE TITLE
Fing a meaningful way to split the backend tests.

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1714]
## Abstract

Currently, the backend tests are taking around ~20min regardless of CI or the local machine. Tests seem to run in a single thread. Find a way to split and parallelize tests when it makes sense. Keeping in mind that any integration tests that rely on the same remote end point should be in the same batch to avoid introducing an unessessary load in the services we depend on.

Unit tests and tests that don't rely on third party services for example could be safely parallelized

## Motivation

Reduce the total runtime of the test, both locally and on CI.

**Comment by LefterisJP** [comment]
> Currently, the backend tests are taking around ~20min regardless of CI

Heh ... good old times

**Comment by yabirgb** [comment]
I splitted them in two groups here https://github.com/rotki/rotki/pull/5507 The division I made is the one that minimizes the time of exectuion with only 2 machines at the same time.

Lefteris proposed a different split approach but it will be slower with our current structure in the test folder. I'll close this issue for now and we can revisit in the future
