### ISSUE TITLE
Blockstacks (STX) #74 CMC is not being recognized

### ISSUE THREAD

**Issue by satorishat** [rotki/rotki#1718]
## Abstract

Please add the possibility to manually add Blockstacks Tokens [https://www.coingecko.com/en/coins/blockstack] as they're not being recognized.

## Motivation

Blockstacks is a top100 coin, currently sitting at #74.

**Comment by LefterisJP** [comment]
Hey @satorishat. Thanks for taking the time to write a request in Github.

Here you go: https://github.com/rotki/rotki/pull/1723

It will be included in the next release.
