### ISSUE TITLE
Add eth2 stake deposit events to the DB

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1721]
## Abstract

Add eth2 stake deposit events to the DB. Follow up from https://github.com/rotki/rotki/pull/1719

## Task

- Add deposit events to the DB and retrieve them when querying for events, so that not the entire range is queried and some time is saved
- Add a test where we query 2 times and make sure DB is used and results are correct

**Comment by kelsos** [comment]
Fixed by #1748
