### ISSUE TITLE
Speed up uniswap unit tests

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1736]
## Problem Definition

The uniswap unit tests seemed a bit slow to me compared to other unit tests. I think it's because in each test you instantiate the uniswap fixture: https://github.com/rotki/rotki/blob/c0e01b71a8da1de2debb50e91f992add599013fe/rotkehlchen/tests/unit/uniswap/conftest.py#L22

Underneath that also instantiates a Graph object. For each Graph instantiation a roundtrip to the graph server needs to be made.

## Task

To fix that just mock away the uniswap's Graph object for the unit tests. If I am not mistake no graph queries are made in those tests.

**Comment by vnavascues** [comment]
This issue is related with #1727, in fact it could removed and keep it all here.
The first endpoint implementation didn't use fake injection, therefore the graph was mocked in the test suite.
