### ISSUE TITLE
Query an archive node for getting the balances within/at a specific time range/block

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#1738]
## Abstract

The number of endpoints/features that require querying the addresses' balances within/at a specific time range/block for a more accurate profits report has increased. A list of the current affected endpoints below:

- GET trades history (for MakerDAO vaults history)
- GET Aave history
- GET Compound history
- GET MakerDAO DSR historical report
- GET Uniswap events history
- GET Uniswap trades history
- GET Yearn vaults history

Related issue: #1729

**Comment by LefterisJP** [comment]
The way to do this would be to:

1. Have an archive node available for premium users (expensive option)
2. Detect if the user's own node is archive and then do archive queries to it

**Comment by LefterisJP** [comment]
I am gonna close this in favor of #2227
