### ISSUE TITLE
Support querying multiple schemas via Graph instance

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#1739]
## Abstract

It seems subgraphs are limited to 1000 entries per schema per response. Nonetheless there is no limit in the amount of schemas the query has. For instance, **GET Uniswap events history** endpoint could benefit from requesting `mints` and `burns` events at the same time instead of requesting twice. At the moment there are unknowns about the benefits of this strategy once The Graph moves to a paying service, e.g. charged per query, charged per schema, indexed queries being cheaper, etc.

**Comment by LefterisJP** [comment]
Closing as we are moving away from the graph
