### ISSUE TITLE
Do not use isisnstance to check an asset is a token

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1741]
## Problem Definition

Related to #1740 -- the reason for the AAVE double counting.

We were using `isinstance()` checks to see that an asset is an ethereum token.
https://github.com/rotki/rotki/blob/f3d5f9d12aa29207add9cc902db44dead4cb5ea7/rotkehlchen/chain/manager.py#L772-L776

That will only work if the asset was initialized with the `EthereumToken()` constructor. But if it was initialized with the superclass of `Asset()` that will not detect it's an ethereum token.

## Task

Go through the code and do not use `isinstance` checks for `EthereumToken` detection tests. Instead use `x.asset_type == AssetType.ETH_TOKEN` for an asset or token `x`

This is an easy one -- just as a reminder. If nowhere else we use it then this can be closed.

**Comment by vnavascues** [comment]
@LefterisJP when you say "go through the code" you mean all the backend? If so, these results?
![image](https://user-images.githubusercontent.com/14769962/99988102-26e1fe80-2da9-11eb-8b90-e59cbf100089.png)

**Comment by LefterisJP** [comment]
> @LefterisJP when you say "go through the code" you mean all the backend? 

Well yeah, the backend is the only python thing we have.

Read the issue it explains why this check is a problem and what needs to be fixed. So you need to check all occurences and see if ti makes sense to change.

**Comment by djibix** [comment]
@vnavascues: I did not see you asked questions about this issue. I worked a bit on it but I am not near to having a solution. So feel free to work on it, I'll be interested in seeing what you come up with.

You can see my latest commit above. I basically tried to replace
isinstance(x, EthereumToken)
by
x.asset_type == AssetType.ETH_TOKEN
everywhere in the project, without really understanding what I was doing...

The linter does not pass, errors are as follows:
"EthereumToken" of "Union[EthereumToken, UnknownEthereumToken]" has no attribute "serialize_as_dict"
"UnknownEthereumToken" of "Union[EthereumToken, UnknownEthereumToken]" has no attribute "asset_type"

I'll try to come back later on this one... keep me posted!

**Comment by vnavascues** [comment]
> > @LefterisJP when you say "go through the code" you mean all the backend?
> 
> Well yeah, the backend is the only python thing we have.
> 
XD, what I meant was if it was only related with the AAVE module. I'm gonna address it.

**Comment by vnavascues** [comment]
@LefterisJP I think this can be closed, nowhere else we are checking `isinstance(<Asset>, EthereumToken)`. As per the picture attached above:
- **Uniswap module**: only uses EthereumToken and UnknownEthereumToken (with hindsight my bad for using `assets/asset` naming).
- **trades.py (AMMSwap class)**: only uses EthereumToken and UnknownEthereumToken.
- **blockchain.py (_get_token())**: expects as an argument either a str (the symbol) or an <EthereumToken>. In case of passing a symbol it will try to instantiate EthereumToken, otherwise `isinstance(<EthereumToken>, EthereumToken)`.

**Comment by vnavascues** [comment]
@djibix Thanks for trying to address this one. The solution to the issue is not as straight as replace every `isinstance(object, EthereumToken)` reference with `object.asset_type == AssetType.ETH_TOKEN`, but only the ones where the object was instantiated via Asset class (type Asset). For instance in the Uniswap module, the `asset` objects are instantiated via `EthereumToken` or `UnknownEthereumToken`, and even more, <UnknownEthereumToken> does not have the property `asset_type`. Hope this test adds some clarity:
```python
def test_issue():
    from rotkehlchen.assets.asset import Asset, EthereumToken
    from rotkehlchen.assets.unknown_asset import UnknownEthereumToken
    from rotkehlchen.constants.ethereum import ZERO_ADDRESS
    from rotkehlchen.serialization.deserialize import deserialize_ethereum_address
    from rotkehlchen.typing import AssetType

    asset_eth = Asset('WETH')
    ethereum_token_eth = EthereumToken('WETH')
    unknown_ethereum_token_faith = UnknownEthereumToken(
        ethereum_address=deserialize_ethereum_address(ZERO_ADDRESS),
        symbol='FAITH',
        decimals=18,
        name='Faiththereum',
    )

    # Asset
    assert isinstance(asset_eth, Asset)
    assert type(asset_eth) == Asset
    assert not isinstance(asset_eth, EthereumToken)  # Problem
    assert asset_eth.asset_type == AssetType.ETH_TOKEN  # Solution

    # EthereumToken
    assert issubclass(EthereumToken, Asset)
    assert isinstance(ethereum_token_eth, Asset)
    assert isinstance(ethereum_token_eth, EthereumToken)
    assert type(ethereum_token_eth) == EthereumToken
    assert ethereum_token_eth.asset_type == AssetType.ETH_TOKEN

    # UnknownEthereumToken
    assert not issubclass(UnknownEthereumToken, Asset)
    assert not isinstance(unknown_ethereum_token_faith, Asset)
    assert not isinstance(unknown_ethereum_token_faith, EthereumToken)
    assert isinstance(unknown_ethereum_token_faith, UnknownEthereumToken)
    with pytest.raises(AttributeError):
        assert unknown_ethereum_token_faith.asset_type
```

**Comment by djibix** [comment]
@vnavascues I appreciate your taking time to explain that, thanks!

**Comment by LefterisJP** [comment]
> @LefterisJP I think this can be closed, nowhere else we are checking `isinstance(<Asset>, EthereumToken)`. As per the picture attached above:
> 
> * **Uniswap module**: only uses EthereumToken and UnknownEthereumToken (with hindsight my bad for using `assets/asset` naming).
> * **trades.py (AMMSwap class)**: only uses EthereumToken and UnknownEthereumToken.
> * **blockchain.py (_get_token())**: expects as an argument either a str (the symbol) or an . In case of passing a symbol it will try to instantiate EthereumToken, otherwise `isinstance(<EthereumToken>, EthereumToken)`.

Indeed. We can close this. I even found a problem in the logic and created a method for asset called `is_eth_token()` in my current branch. That commit should close the issue.
