### ISSUE TITLE
Add uniswap LP balances in dashboard and per chain account

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1744]
## Problem Definition

This is just a small reminder for us.

- Backend: Make sure that all uniswap LP balances are queried and included in the dashboard and per account and total blockchain balances. Format should be identifier: "UNIV2LP_TOKEN0_TOKEN1".
- Frontend: Have a regex to parse that and show the TOKEN0 TOKEN1 pool icon instead of trying to find the icon in all_assets.json

**Comment by hjorthjort** [comment]
Could a card be added in the dashboard under `Assets` with the different pooled assets as well? Would be nice to split them from wallet assets, both to think about risk and for accounting purposes.

**Comment by LefterisJP** [comment]
Perhaps in a redesign of the dashboard (this would be a different issue) where we add more categories. For now we got assets and liabilities.

For more detailed view of the assets you go into the DeFi LP view for the moment.

**Comment by LefterisJP** [comment]
Same thing needs to be done for Balancer
