### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by GregTheGreek** [rotki/rotki#1745]
## Abstract

The ability to select multiple addresses/accounts and delete them from the dashboard.

## Motivation

I was playing with the metamask feature, and ended up importing 10+ addresses that i didn't want to track. It would be nice UX to be able to bulk delete them.

## Specification

N/A

**Comment by LefterisJP** [comment]
That should be easy to add. Right @kelsos ? We already got a list as input in the backend for account deletion.

**Comment by kelsos** [comment]
Yes the input is a list, so we can introduce the ability to select and delete multiple accounts on the UI

**Comment by LefterisJP** [comment]
Scheduling it for the release after 1.9 then.

**Comment by GregTheGreek** [comment]
:+1:
