### ISSUE TITLE
Uniswaps trades in trade history should provide a link to the DEX trades

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1750]
## Abstract

DEX trades provide more information for the uniswap trades that is not available in the trades history. There should be a way to make the user navigate to the DEX Trades detail from the trades history.

**Comment by kelsos** [comment]
I have been thinking a bit on this issue and providing a link to the DEX Trades detail from history is not an easy task to undertake. 

Instead I was thinking that we could show any extra DEX trade information when expanding the dex trade itself.

**Comment by LefterisJP** [comment]
> I have been thinking a bit on this issue and providing a link to the DEX Trades detail from history is not an easy task to undertake.
> 
> Instead I was thinking that we could show any extra DEX trade information when expanding the dex trade itself.

This does not make sense. The swap itself has already all needed information. The link to the trade would be to be able to see the trade itself that goes in accounting and to also ignore it.

If it's not easy just push it to a further milestone.

**Comment by kelsos** [comment]
> > I have been thinking a bit on this issue and providing a link to the DEX Trades detail from history is not an easy task to undertake.
> > Instead I was thinking that we could show any extra DEX trade information when expanding the dex trade itself.
> 
> This does not make sense. The swap itself has already all needed information. The link to the trade would be to be able to see the trade itself that goes in accounting and to also ignore it.
> 
> If it's not easy just push it to a further milestone.

First, you cannot currently ignore or unignore dex trades. There is no such functionality in the DEX trades table.
Second, there is a checkbox in the trades (also for Dex Trade entries) but it doesn't seem to work. 

Also, I am not really sure that navigating to another page, and then automatically switching to the page of the table the swap is, and then scrolling to the row where the entry is, makes more sense than just showing the extra data underneath and making the ignore/unignore work also for dex trades in the trades table.

**Comment by LefterisJP** [comment]
> First, you cannot currently ignore or unignore dex trades. There is no such functionality in the DEX trades table.
Second, there is a checkbox in the trades (also for Dex Trade entries) but it doesn't seem to work

There is in the trades table. Which is why I am mentioning this here.

> Also, I am not really sure that navigating to another page, and then automatically switching to the page of the table the swap is, and then scrolling to the row where the entry is, makes more sense than just showing the extra data underneath and making the ignore/unignore work also for dex trades in the trades table.

Let's discuss this in the standup. Or in the standup 2 weeks from now as this is just not important at the moment.

**Comment by kelsos** [comment]
It seems that it is getting close to a year that we keep pushing this issue.

I am re-reading the following comment I made and I am pretty sure that I was not clear enough.

> I have been thinking a bit on this issue and providing a link to the DEX Trades detail from history is not an easy task to undertake.
> 
> Instead I was thinking that we could show any extra DEX trade information when expanding the dex trade itself.

What I meant was instead of providing a link from the trade's table to the dex-table to instead show the extra dex trade information when expanding the history->trade table entry for a dex trade.

Like I mentioned before linking from a table to another table doesn't make much sense.

**Comment by LefterisJP** [comment]
> It seems that it is getting close to a year that we keep pushing this issue.
> 
> I am re-reading the following comment I made and I am pretty sure that I was not clear enough.
> 
> > I have been thinking a bit on this issue and providing a link to the DEX Trades detail from history is not an easy task to undertake.
> > Instead I was thinking that we could show any extra DEX trade information when expanding the dex trade itself.
> 
> What I meant was instead of providing a link from the trade's table to the dex-table to instead show the extra dex trade information when expanding the history->trade table entry for a dex trade.
> 
> Like I mentioned before linking from a table to another table doesn't make much sense.

All right so how hard is this to do? This issue has been open and assigned to you for a very long time @kelsos. Can you either quickly implement it if it's easy or just push to a milestone when you think we can tackle it?

**Comment by LefterisJP** [comment]
After talk with @kelsos (in real life!!!!!!!1111oneoneone :smile: )

this probably does not make sense as is, since the DEX trades are going to go away, and probably be replaced by decoded events. So closing the issue.
