### ISSUE TITLE
SNX in Blockchain balances incorrect

### ISSUE THREAD

**Issue by satorishat** [rotki/rotki#1755]
## Problem Definition

My SNX holdings are displayed incorrectly. The amount is exactly double of what my actually holdings are. I removed the address & re-entered it - same. All my other holdings are displayed correctly. 
I have removed the address, cleared cache, closed & restarted rotki, re-entered address - still same, double the SNX amount.

### System Description

Operating system: Linux Manjaro
Rotki version: 1.8.3

**Comment by LefterisJP** [comment]
Hey @satorishat thanks a lot for the issue!

Thankfully this is known and is already fixed in develop. Fix is going to be deployed in v1.9.0 very very soon.

The issue where this was first reported is here: https://github.com/rotki/rotki/issues/1740 so closing this as a duplicate.
