### ISSUE TITLE
Native segwit bitcoin xpub from wasabi wallet missing addresses

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1759]
## Problem Definition

A user has tried to import a native segwit bitcoin xpub from wasabi wallet and it is missing some addresses. We have to figure out what is the difference in the address generation and handle it properly.

## Task

Figure out the problem and solve it.

**Comment by kilrau** [comment]
Also have this issue with my wasabi native segwit xpub

**Comment by kilrau** [comment]
Happy to help debugging, if you guys still have problems to reproduce :v:

**Comment by LefterisJP** [comment]
Renaming this since the original issue with the legacy xpub from trezor is solved. This is about Wasabi wallet now.

@kilrau How can we proceed in debugging this with you? Without the xpub I don't know how I can reproduce.

Digging around I saw this: https://zksnacks.gitbook.io/wasabidoc/docs/using-wasabi/restoreelectrum

Notice the guidance to increase the gap limit to `100`. Could that be the reason? I recall that with some xpub (I no longer can find it) I reproduced this once and changing the gap limit did not help, but perhaps in this case it will?

Perhaps it would make sense to make this configurable and give you a nightly to test.

**Comment by kilrau** [comment]
> Perhaps it would make sense to make this configurable and give you a nightly to test.

I have no experience with different gap limits, but yes that sounds like a good option i am happy to run this nightly against a copy of my environment where it's missing addresses (just remember that I'd need a nightly Appimage that runs on Ubuntu)

**Comment by LefterisJP** [comment]
This issue is going to be re-used for the problem of users having their xpubs address derivation not derive new addresses properly after initial derivation that @JezSan noticed.

If the original issue of addresses with wasabi persists even with the derivation gap limit change then please open another issue.

The problem seems to be that we derive the initial addresses at Rotki and then any non-used addresses from the derived ones are never seen again since the highest derived index is taken.

**Comment by kilrau** [comment]
Finally resolved for me (Wasabi) with the latest release - great work! @LefterisJP

**Comment by LefterisJP** [comment]
@kilrau oh well that's pretty cool! I was not sure if this would also solve your issue but I am super happy it did. Keep in mind if you start missing addresses again restart rotki.

We are going to work on better ways to update the addresses from the backend without restart, right at the time of detection.
