### ISSUE TITLE
Repeat graph queries when the response is non fatal

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1761]
## Problem Definition

Repeat graph queries in a continious backoff manner if the response says that the service is overloaded, instead of just failing.

## Task

Do it

**Comment by vnavascues** [comment]
@LefterisJP I will try to see if `RequestsHTTPTransport.retries` does the job:
https://github.com/graphql-python/gql/blob/v2.x/gql/transport/requests.py#L31

Definitely not the `Client.retries`:
https://github.com/graphql-python/gql/blob/v2.x/gql/client.py#L28

**Comment by vnavascues** [comment]
`RequestsHTTPTransport` uses the standard [HTTPAdapter `max_retries`](https://github.com/graphql-python/gql/blob/v2.x/gql/transport/requests.py#L68).

[It is already tested](https://github.com/graphql-python/gql/blob/b42fe08b34a779133b012a6b123d66959e009bbf/tests/test_client.py#L41) in the library.

And t[hese would be the logs after each try](https://github.com/graphql-python/gql/blob/v2.x/gql/client.py#L94).

If you agree on the status codes (500, 502, 503, 504), backoff factor (0.1) and logs message, we could just try to use it. How many retries would you like considering the number doesn't count the first request?

**Comment by LefterisJP** [comment]
Fixed by #1811
