### ISSUE TITLE
User grouping of exchange trades

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#1768]
## Abstract

Add user grouping of multiple exchange trades in the Rotki app History/Trades display

## Motivation

User mental abstraction of their (often) multiple execution trades on centralized exchanges into a single human action (the choice to buy or sell a trade pair) would aid user comprehension of the history of their crypto accounts.  

The current display on Rotki will show each small/automated exchange trade made by the automated-order-filler on a crypto exchange to fill an order as a single line entry in the History/Trades list screen.  That _is what a computer does in the backgroiund to match trades on an order book_; it is _not how human brains think_ and abstract the single trade they chose to make.  This makes it much more difficult for a user to grok what is, to them, a seemingly much smaller number of trades they actually made, historically.

## Specification

**PREMIUM** ONLY:  Implement a way to optionally group multiple lines of output History/Trades into a single aggregated line for that set of trades executed.  Could optionally use color /or/ greying of the background to better show groups of trades that ought to hang together.  Could show the summary/aggregated trade amount and effective price of the trade in lieu of the manyTradesDetailedView, and optionally expand to show the full detail, once a user has grouped their trades as they wish.

Any such user work on the Rotki DB data would of course be persistent only in the current data store.  If a user started over, or PULLed their data in from scratch, I would imagine these aggregated user-selected groupings would be lost.

**Comment by LefterisJP** [comment]
So this is not easy to do. It's a "good to have".

From what I understand we would need to keep per-exchange information of what "fills" belong to a specific trade and then group them together.

This is hard todo since this information is not available for most exchanges, plus we currently have no way to account for this in the way rotki is written.

**Comment by A2be** [comment]
I think you have misunderstood the suggestion. 

Not suggesting the Rotki app auto-magically account for all this based on CEX exchange data.

Rather, just an option in the Rotki app UI front-end for a **user** to, say, group n particular fills together.  
E.g., if a Rotki user swaps 1 ETH for a bunch of foobar tokens, and the exchange spreads that into a dozen fills from their order book, then the user could somehow click to connect all 12 fills to that 1 ETH that was used to buy them, and get a much nicer report in the accounting record which would simply reflect the average price of the dozen trades and a net amount of foobar purchased for the 1 ETH put into the trade.

Makes it easier to think about the <50 things I'll do in a year if this _single human decision_ (swap x of abc token for y of def token at p price) is reflected as a single entry in my accounting; rather than have my Rotki spreadsheet show it to me as >500 trades at the end of the year.  (a dozen fills times the <40+ trades I'll make)
(which also leads to my tax accountant charging for more time to deal with 500 rather than 50).

So, win/win. 
And simply an option for the premium user.  Default is the behavior you have today.

**Comment by LefterisJP** [comment]
Closing as this is not a priority and we have other things to focus on. May revisit if more interest is shown by more users.
