### ISSUE TITLE
Display unrealised pnl in dashboard

### ISSUE THREAD

**Issue by adrienlacombe** [rotki/rotki#1769]
## Abstract

I can't find my unrealised pnl (profits and losses) anywhere, it would be nice to see it.

## Motivation

This gives an idea of the profits or losses that would occur if all positions would be to be close right now. It is fairly easy to deduct an approximate value of the taxes on it.

## Specification

N/A

**Comment by adrienlacombe** [comment]
Any question, comment let me know.

**Comment by LefterisJP** [comment]
Do you mean something like https://github.com/rotki/rotki/issues/701?

Essentially an overlay of all positions for each asset, calculating the cost basis for each asset and then displaying if you are a profit, at a loss and by how much?

**Comment by adrienlacombe** [comment]
Yes, thank you, I didn't find this issue earlier because it doesn't state that it need to show the unrealized profit or loss, this is key, this is why I would update a little bit the way #701 is described even though the idea is there.

**Comment by adrienlacombe** [comment]
Also, my enhancement requests is a trading view, not an accounting view, I don't really care about taxes here. Also I would like to be abme to change the start date and end date to ocmpute this unrealized p/l.

**Comment by LefterisJP** [comment]
Yeah this is exactly what that issue is for! Exactly what you described. It's something we definitely need. As a trader, or holder or whatever you need this information.

**Comment by adrienlacombe** [comment]
Great news! Thank you vm. I'll comment there :)
