### ISSUE TITLE
Binance API: Some assets not reflected in v1.8.3

### ISSUE THREAD

**Issue by Rhamni1988** [rotki/rotki#1776]
## Defi staked assets not showing up in v1.8.3

When using the Rotki portfolio tracker with the Binance API, Rotki does not display my full holdings. Specifically, what is missing are BNB tokens held under 'DeFi staking' on https://www.binance.com/en/my/wallet/account/saving. I hold no other assets under DeFi Staking, so not sure if it's all of them or just BNB. Other balances appear to be accurate, both in the main wallet and locked under 'Earn'. Problem was present in previous builds as well.

## Logs

No error messages, no logs.

### System Description

Operating system: Windows 10 Home, 18363
Rotki version: v.1.8.3

**Comment by LefterisJP** [comment]
Hey @Rhamni1988 sorry for not responding to this issue sooner. It fell through the cracks.

I suppose you refer to https://www.binance.com/en/defi-staking?

By looking at their API docs I guess this is it: https://binance-docs.github.io/apidocs/spot/en/#get-flexible-product-position-user_data. Should not be hard to add.

Will schedule this in one of the next releases.

**Comment by Rhamni1988** [comment]
>I suppose you refer to https://www.binance.com/en/defi-staking?

That's the one!

Sounds great.

Other than that, there are a few other assets on Binance that Rotki doesn't recognize, as it gives me error messages for each when I start the client. These are BETH, SCRT, JEX and BCX. Of these, BETH is the important one, as it's Beacon ETH/ETH 2.0, the token you get when you lock and stake ETH on Binance.

Anyway. Loved the changes for 1.9.0, with the tracking of performance over time.

**Comment by LefterisJP** [comment]
All right. Thanks a lot for letting us know. Will have a look. `BETH` is `ETH2` for Rotki so this should be solved by simply mapping it properly.

For more real-time chat you can also join our discord server: https://discord.gg/aGCxHG7
