### ISSUE TITLE
Show the selected accounting settings with which the user's tax report is generated

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1792]
## Abstract

As per feedback given in https://github.com/rotki/rotki/issues/1783 it would be nice to have transparency in the tax report UI. Essentially somehow show the accounting settings in the actual tax report page so that it's obvious with what settings it is made.

## Task

Do it

**Comment by kelsos** [comment]
The settings should already be in the frontend right? so my guess is that this could be a fully frontend issue. 
Do you have anything specific in mind on how this would look like?
