### ISSUE TITLE
Add new accounting method: Average cost basis

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1793]
## Abstract

As per the feedback given in #1783 we should add a new way of calculating the accounting in tax report. A cost average basis, apart from fifo and lifo.

> Yes, to be more precise, the average value of all your units of a given asset. So go through an example:
> buy 1 ETH at 100 $. Your tax base is now 100 $
> buy 1 ETH at 200 $. Your tax base is now 150 $ for your 2 ETH
> Sell 0.5 ETH at 400 $. Your profit would be 200 $ - 75 $ = 125 $. The remaining ETH still have the same tax base of 150 $
> Buy another 0.5 ETH at 500 $. The tax base would now be (1.5150$ + 0.5500$) / (1.5 + 0.5) = 237.50$

## Task

Do it

**Comment by adrienlacombe** [comment]
Yes, this is the way to go for France for instance.

**Comment by adrienlacombe** [comment]
Sweden as well as according to discussion on Discord.
