### ISSUE TITLE
Support for Core Vaults

### ISSUE THREAD

**Issue by TheWanderer1983** [rotki/rotki#1796]
## Abstract

Core is a DeFI product used by the community. It has a number of vaults.  
https://www.cvault.finance/

Adding more support for DeFi products will make Rotki more useful to the community. 
## Specification
https://github.com/cVault-finance

**Comment by LefterisJP** [comment]
Thank you @drgonzo31 for taking the time to write an issue!

We will consider the addition of Core Defi vaults when we find some dev cycles.

**Comment by LefterisJP** [comment]
Closing this as not planned for now. The protocol seems to have almost zero activity.
