### ISSUE TITLE
Logging verbosity setting should persist across sessions

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1798]
## Abstract

Currently the logging verbosity resets every time the application is restarted / closed, back to `Critical`. Instead it should persist across sessions.

## Motivation

It's annoying to have to re-set the logging verbosity every time.

## Specification

In theory this could perhaps be done "frontend-only" with the "frontend settings" configurations, but it may also make sense for it to be a normal backend setting (in theory logging / errors have two sources, either the backend or the "client", which in the future could be more than just the electron frontend). Up to you guys on how to approach.

**Comment by LefterisJP** [comment]
Not required for v1.9.1 but if you could put it in @kelsos it would be cool
