### ISSUE TITLE
Display proper placeholder screens when a module is deactivated

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1800]
## Problem Definition

As @isidorosp observed, when a module is deactivated for Uniswap related screens, while no request leaves the frontend, the UI shows a loading screen that does not complete. 

This is the wrong placeholder screen to show when a module is not activated by the user
Investigate which Defi areas require a module deactivated placeholder screen

### Tasks

- [x] Investigate in which areas a placeholder screen is needed and make issues for that
- [x] Introduce a placeholder for Liquidity Pools & Dex Trades #1801

**Comment by LefterisJP** [comment]
Adding it to a milestone and the dev kanban so we don't lose this.
