### ISSUE TITLE
User should be able to select default timeframe in dashboard & timeframe should persist during session

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1810]
## Abstract

A few improvement suggestions for the dashboard chart:
1. The user's choice of selected timeframe should persist throughout the session (e.g. if I set it to "1W" and then browse away and back to Dashboard, it should be on "1W")
2. The user should be able to select their "default" timeframe (i.e. what is shown at startup)
3. The user should be able to enable/disable specific timeframes if they don't want to see buttons for all 6 (and I guess you can add more options such as 6M, 2Y, etc.)

## Specification

Can probably just use the front-end settings that kelsos created for this.

**Comment by LefterisJP** [comment]
Hey @kelsos this sounds like added value to the user, right? Tentantively putting at 1.10 just so it's not lost. Actual implementation is your call.

**Comment by kelsos** [comment]
>     3\. The user should be able to enable/disable specific timeframes if they don't want to see buttons for all 6 (and I guess you can add more options such as 6M, 2Y, etc.) 

I will open a new issue about that
