### ISSUE TITLE
Can't add Binance API due to clock Sync issue

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#1820]
## Problem Definition
Trying to add my Binance API to the Rotki gives me the following error:
"The setup of binance failed due to: Local system clock is not in sync with binance server. Try syncing your system's clock"

## Logs
Log file is empty.

### System Description

Operating system:  Windows 10 Home
Rotki version: rotki-win32-v1.9.0

**Comment by LefterisJP** [comment]
Hey @drgonzo31. There is already an issue for this and it seems it's a common problem when your local system time is not configured properly in Windows: https://github.com/rotki/rotki/issues/1449

https://discordapp.com/channels/657906918408585217/745172610240872508/752632155586297867

As per that issue check the solution to sync your clock posted by @isidorosp in our discord. For more clock sync problems just ask in our discord.
