### ISSUE TITLE
Refreshing balances should derive new xpubkey addresses and check to see if there were deposits

### ISSUE THREAD

**Issue by coblee** [rotki/rotki#1830]
## Abstract

When you refresh balances, you should check to see if there were coins sent to new addresses of xpubkeys

## Motivation

People with xpubkeys will occasionally deposit coins to new derived addresses. It's important that refreshing balances catches those.

**Comment by codyday318** [comment]
ltc1q0kkcn5dmlhzgkqpgtenzp69vwnvhpu3pnpqatz Charlie I sent 13 litecoins to you for a giveaway and have not received anything what do I need to do please help me

**Comment by LefterisJP** [comment]
This is easy. Let's just implement it in next release
