### ISSUE TITLE
Loading forever

### ISSUE THREAD

**Issue by koeppelmann** [rotki/rotki#1832]
## Problem Definition

The Loading wheel keeps spinning forever and the total $ amount shows only a fraction of what it should.

## Logs

Getting this error message:
Error at querying blockchain balances: The backend query task died unexpectedly: {'code': -32005, 'message': 'query returned more than 10000 results'}

### System Description

Operating system: MacOs 11.0.1
Rotki version: 1.9.0

**Comment by LefterisJP** [comment]
Hey @koeppelmann is this with infura or with your own node? If this is with Infura, it's the same issue as this: https://github.com/rotki/rotki/issues/1787

It's fixed in develop, and a release containing it is coming out within day/s.

**Comment by LefterisJP** [comment]
This "should be" fixed in v1.9.1: https://github.com/rotki/rotki/releases/tag/v1.9.1
