### ISSUE TITLE
Eth2 staking view fixes

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1852]
## Problem Definition

There is a few things we need to fix in the Eth2 staking view for premium users.

![2020-12-03_01-23](https://user-images.githubusercontent.com/1658405/100947568-2c0c1f80-3506-11eb-9497-3ef1f4fd2f28.png)

1. At the `earned` column we need to also add the amount of ETH earned, not only the USD/EUR equivalent.
2. The APR seems to be wrong. @kelsos as discussed something may be wrong with the calculation. Perhaps we can have a call to clarify. But for example performance_1d returns: `0.015073283` ETH, then if you project this to 365 days to get the APR you get: `(0.015073283*365)/32` = `0.171929634219` = ~`17.1%` APR

## Task

@kelsos Do it

**Comment by kelsos** [comment]
@LefterisJP I certainly do not remember discussing about this `*365` before. I am guessing month and week follows a similar rule?

**Comment by LefterisJP** [comment]
I guess it does. Please use the validator we test with as local only test data to see how it looks like.

**Comment by LefterisJP** [comment]
This is done and merged in premium components. Don't add a changelog. I think I will add all eth2 staking fixes in one changelog commit later if that's fine with you.

**Comment by kelsos** [comment]
Sure we can do that :+1:
