### ISSUE TITLE
Find a way to cleanup the temporary folder after the user downloads the report.zip

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1853]
## Problem Definition

Followup to PR #1848 

For the download of the CSV reports a temporary folder is created. Then the CSV reports are added into a temporary zip and the temporary zip is downloaded. The temporary zip is never cleanup in the context of the request/response because at this point the file is not yet sent to the client.

We need a way to clean up the temporary zip and remove the folder after the file has been served to the user.

#### For context:
- https://stackoverflow.com/questions/13344538/how-to-clean-up-temporary-file-used-with-send-file

**Comment by LefterisJP** [comment]
@kelsos is this going to be worked on at some point? Should we put it in a mlestone? I totally forgot about this since it's not in a milestone.

**Comment by kelsos** [comment]
It is still a problem that we should take care of. I don't know if @yabirgb could help with this. I will leave the scheduling to you.

**Comment by yabirgb** [comment]
Okey! I once made something similar. When I finish what I have in hands I can give it a try. Maybe for 1.19?

**Comment by kelsos** [comment]
Sure sounds good if @LefterisJP also agrees

**Comment by LefterisJP** [comment]
> Okey! I once made something similar. When I finish what I have in hands I can give it a try. Maybe for 1.19?

I guess this is still not done @yabirgb

There is a TODO about this in the code: https://github.com/rotki/rotki/blob/5bb6ac710534b2a6d1fe35ab10864f28b0174023/rotkehlchen/accounting/export/csv.py#L237

**Comment by rishabhRsinghvi** [comment]
please assign this too to me, I love backend.
