### ISSUE TITLE
Support Aave v2

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1857]
## Abstract

Aave released v2: https://medium.com/aave/the-aave-protocol-v2-f06f299cee04

We should see what work is needed and support it in Rotki.

Subgraph: https://thegraph.com/explorer/subgraph/aave/protocol-v2 

## Task

https://docs.aave.com/developers/change-from-v1-to-v2

Spec it out and do it

**Comment by yabirgb** [comment]
Closed by #3144
