### ISSUE TITLE
Add support for Bitstamp crypto transactions

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#1863]
As per [Bitstamp API v2 documentation](https://www.bitstamp.net/api/), the JSON returned by the user transactions endpoint does not include any chain-related data (e.g. txid, address). This data is obtained by requesting the crypto transactions endpoint.

Be aware the crypto transactions endpoint is not paginated like the user transactions one (e.g. it has no `since_id`).
 
Related #1856 and more specifically: https://github.com/rotki/rotki/pull/1856#discussion_r536031605

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/7096
