### ISSUE TITLE
Move the processing ts out of periodic data query

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1865]
## Abstract

At the moment there is a periodic query that happens quite often. The tax report processing timestamps are included there. And they are only used whenever a tax report is made.

https://github.com/rotki/rotki/blob/f3a795e0a3061751db22e6ebfcf7d4701488878d/rotkehlchen/rotkehlchen.py#L946-L956

This is bad since data that is useless 99% of the time is going back and forth all the time. And since if we want to give more information about the tax report to the user we would need to add even more data there.

## Task

This should change. We should remove these from the periodic query.

Instead a new endpoint `/history/progress` should be created which would contain those and it would be queried by the frontend in a predetermined interval and only when a tax report is happening.

Additionally we should add some more information there that can be shown to the user to inform them why they are waiting for so long. For example divide the process into stages, and even have a small description of each stage and action.

@kelsos what do you think?

**Comment by kelsos** [comment]
Yes, it would make more sense to have a specific API for that.  Let's go for it :+1:
