### ISSUE TITLE
Curve.fi not showing veCRV holdings

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#1869]
## Problem Definition
Curve pools are showing Rotki, but none of the locked veCRV holdings are showing up.

### System Description

Operating system: Windows 10.
Rotki version:  rotki-win32-v1.9.1

**Comment by LefterisJP** [comment]
Hey @drgonzo31 thanks for the issue. That is because we have not added support for veCRV yet.

We are going to add it to our next release. Thank you for point it out
