### ISSUE TITLE
Please can you put the current version number on your website download page

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#1877]
## Abstract

its not clear on your web site which is the current version.

## Motivation

how to know if there's an update if youre not reading the GitHub pages.  the web site needs to be clearer, especially on the download page.

**Comment by kelsos** [comment]
Hey @JezSan if you are using an older version of rotki the easiest way to know that there is a newer version is the application itself. You should have an indicator about an update being out after logging in.

![image](https://user-images.githubusercontent.com/2269732/101470463-5286ec00-3946-11eb-9eae-ac54fc1688e2.png)

Other than that we can certainly improve on that.

I will take care of adding it to the website and @LefterisJP maybe also it makes sense to add some info/about dialog that opens from the login screen where you can see the current version and also if there is an update out?.

**Comment by LefterisJP** [comment]
Thanks for answering @kelsos. But still as you said good point to put the latest version also on the website at the downloads section. You gonna take care of that?

**Comment by kelsos** [comment]
@JezSan would something like this work?

![image](https://user-images.githubusercontent.com/2269732/101539511-ef757380-399e-11eb-9b9c-8602d915ecd5.png)

**Comment by JezSan** [comment]
Awesome

**Comment by LefterisJP** [comment]
This is done
