### ISSUE TITLE
Create a small about screen/dialog

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1881]
## Problem Definition

There is no easy way to find the version of the app before logging in. The idea is to introduce a small dialog that can be opened on demand by the user to check the basic information or the availability of updates.

It could be something like that:
![image](https://user-images.githubusercontent.com/2269732/101621607-45393280-3a16-11eb-9f02-b6cf2c14e4d1.png)

### Task
- Introduce an about dialog 
- Add button on the login screen for when the application is running outside electron
- Add option in the help menu of the application

**Comment by chevdor** [comment]
It may be a good place to also mention where the data is located.

**Comment by LefterisJP** [comment]
Ah yes, we should, much like we do with the logs. @kelsos can you also do it when you address this?

**Comment by kelsos** [comment]
Don't we already have the logs at the menu though?

**Comment by LefterisJP** [comment]
We do but the location is indeed different ;)

**Comment by chevdor** [comment]
In the case of Rotki, you probably want to log: 
- the UI version 
- the Backend version
- the platform

and make is a fields easy for the user to copy/paste the info in new issues.

**Comment by isidorosp** [comment]
> In the case of Rotki, you probably want to log:
> 
> * the UI version
> * the Backend version
> * the platform
> 
> and make is a fields easy for the user to copy/paste the info in new issues.

You can also just make a link that auto-populates data into an issue. e.g.
https://github.com/rotki/rotki/issues/new?title=foo&body=test%20issue%0D%0A```%0D%0Asys%0D%0Ainfo%0D%0Ahere%0D%0A```

Will require a bit of digging to see how you can send all the right special characters for md markup via a URL parameter but I think it's doable.

**Comment by kelsos** [comment]
The copiable information idea I certainly like. I also did something similar in other projects I worked on before. It certainly brings benefits.
