### ISSUE TITLE
Add an easy way to list all addresses that hold a certain coin / ERC20 token

### ISSUE THREAD

**Issue by bakkdoor** [rotki/rotki#1884]
## Abstract

It would be nice to see e.g. all Ethereum addresses that hold a certain ERC20 token.
Right now I can't find a way to easily see where my coins are currently. It only shows a total from all accounts configured in the app. Would be nice if you could just click a button next to a coin in the dashboard that then displays a listing of all the addresses, either in a new screen or injected right into the dashboard somehow. Whatever works best.

## Motivation

I can see I still have some ERC20 token somewhere but I don't know what address. This would help with finding out what address I have tokens in. It would be a lot more convenient than having to go through all of your address manually.

**Comment by LefterisJP** [comment]
Hey @bakkdoor that is a very good feature request. So good in fact we already have an issue for this. 

Does https://github.com/rotki/rotki/issues/1147 satisfy the same requirements you are setting here? If so can we close this?

**Comment by bakkdoor** [comment]
Yeah, will close this. Thanks.
