### ISSUE TITLE
Staking addresses not displaying consistent data

### ISSUE THREAD

**Issue by tgerring** [rotki/rotki#1905]
Currently, the events related to my staking deposits are appearing exactly as expected in the "Events" section in the "Staking" tab, however, I simultaneously see the message "No accounts with Eth2 staking were detected." despite addresses appearing in the filter. Additionally, "Blockchain Balances per Asset" shows "Staked ETH in Phase 0" to reflect a partial balance.

**Comment by LefterisJP** [comment]
@tgerring 

> Additionally, "Blockchain Balances per Asset" shows "Staked ETH in Phase 0" to reflect a partial balance.

This is probably due to https://github.com/rotki/rotki/issues/1888 which is fixed in develop and will be included in v1.10.0 to be published very soon.

> I simultaneously see the message "No accounts with Eth2 staking were detected." 

Where do you see this message? Perhaps wait until v1.10.0 (maybe even today) and then try again?

**Comment by kelsos** [comment]
@LefterisJP it yes #1888 is the most probable cause. Since the inflight amounts are not returned, if you have no accounts that are past this initial period then you will get this message.

**Comment by tgerring** [comment]
Thanks all, this certainly seems like it's impacting me, I will wait for the updated version and report back.

**Comment by tgerring** [comment]
The [latest release](https://github.com/rotki/rotki/releases/tag/v1.10.1) seems to fix this problem. Balances are now showing as anticipated!

**Comment by kelsos** [comment]
Thank you for confirming @tgerring. I am glad it got resolved :)
