### ISSUE TITLE
TokenSet Eth address doesn't show TokenSet Value

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#1912]
The eth address only shows eth in the address and some attached DAI. It does not register the value of the TokenSet itself.

Operating system: Win 10
Rotki version:

**Comment by LefterisJP** [comment]
Hey @Blackswan122 tokensets are not yet supported: https://github.com/rotki/rotki/issues/1010

So this is not a bug but more a feature request to support them for which we already got #1010. Would it be okay to close the issue and keep only that one?

**Comment by Blackswan122** [comment]
Yeah fine thanks... I thought it was just another Eth address though.

**Comment by LefterisJP** [comment]
No they are not unfortunately.
