### ISSUE TITLE
Let Me In!

### ISSUE THREAD

**Issue by MysticRyuujin** [rotki/rotki#1917]
## Abstract

When logging in, if you fill in the password first, and then fill in the username, the sign in button is still disabled. I have to click back into the password field or somewhere else in order for the sign-in button to activate.

![image](https://user-images.githubusercontent.com/8877131/102362598-330d4600-3f7a-11eb-932e-b0aa73a67377.png)

## Motivation

Because it's a minor annoyance :slightly_smiling_face: 

## Specification

:man_shrugging:

**Comment by LefterisJP** [comment]
hahahahaha love the issue name.

Thanks @MysticRyuujin.

@kelsos when you have time take a look at this. It's definitely frontend only.

**Comment by kelsos** [comment]
Perfect timing @MysticRyuujin I am doing some maintenance work on the login screen already :D

**Comment by LefterisJP** [comment]
Should be fixed by #1921. Will be included in next release.
