### ISSUE TITLE
Add Power Index Pool Token (PIPT) from PowerIndex

### ISSUE THREAD

**Issue by GiraeffleAeffle** [rotki/rotki#1925]
## Abstract

PIPT is a Balancer Pool and DeFi Index consisting of the following 8 Token in the equal share of 12.5% 

AAVE
YFI
SNX 
CVP
COMP
wNXM
MKR
UNI 

https://powerindex.io/#/mainnet/

## Motivation

It is possible to be diversified and it is possible to stake the PIPT Token itself or in combination with ETH to get the CVP Token.

### Contract

https://etherscan.io/token/0x26607ac599266b21d13c7acf7942c7701a8b699c

### Coingecko 

https://www.coingecko.com/en/coins/power-index-pool-token

**Comment by LefterisJP** [comment]
WE don't yet support balancer pools like that, but if it's a normal ERC-20, and has coingecko/cryptocompare entry we can add it. Is it this one? https://www.coingecko.com/en/coins/power-index-pool-token

The contract address seems to match.

**Comment by LefterisJP** [comment]
done
