### ISSUE TITLE
Add Yearn Ecosystem Token Index (YETI)

### ISSUE THREAD

**Issue by GiraeffleAeffle** [rotki/rotki#1927]
## Abstract

YETI is a DeFi Index consisting of the following 8 Token with shares of: 

YFI 35%
SUSHI 17%
CREAM 8%
AKRO 8%
COVER 8%
KP3R 8%
CVP 8%
PICKLE 8%

https://powerindex.io/#/mainnet/

## Motivation

It is possible to be diversified and it is possible to stake the YETI itself or in combination with ETH to get the CVP Token.

### Contract

https://etherscan.io/address/0xb4bebD34f6DaaFd808f73De0d10235a92Fbb6c3D

### Coingecko 

https://www.coingecko.com/en/coins/yearn-ecosystem-token-index

**Comment by LefterisJP** [comment]
done
