### ISSUE TITLE
Force restoring a database after adding api keys doesn't work.

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1928]
## Problem Definition

This requires an empty account without premium or a fresh account without premium set up during the account creation.
After logging into this account, if you go to the API keys page and insert the premium keys and then try to force sync (download) a backed-up database, this will fail with an error that says that the user doesn't have premium.

Performing a logout and re-login seems to resolve the issue.

**Comment by LefterisJP** [comment]
Fixed by #2307
