### ISSUE TITLE
Introduce documentation about defi settings

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1940]
## Problem Definition

Introduce documentation entries on the defi section.

- How a user can disable specific protocols
- How a user can select specific addresses per protocol

**Comment by LefterisJP** [comment]
We can probably also link this video there. Completely forgot we made it: https://www.youtube.com/watch?v=dG--4ZK7mIY

**Comment by LefterisJP** [comment]
Or this: https://www.youtube.com/watch?v=T07FtLGt69c (but the previous one is newer)
