### ISSUE TITLE
Unexpected percent finished on tax report

### ISSUE THREAD

**Issue by tjayrush** [rotki/rotki#1946]
## Problem Definition

I ran a tax report for 1/1/2020 to 18/12/2020 and it seemed to work fine. I then tried running for 1/1/2016 to 31/12/2016 and I saw this screen. The report seems to have worked fine, but the percentage complete seems wrong.

![image](https://user-images.githubusercontent.com/5417918/102668101-18dd8e80-4159-11eb-84e2-409ef57b418f.png)

### System Description

Mac OS

Operating system:  Mac
Rotki version: 1.10.1

**Comment by LefterisJP** [comment]
Ah yes the super complete percentage :)

This is a bug that seems to have surfaced in some situations. Thanks for the issue. The steps you provided may help reproduce, pin down and fix!

**Comment by chevdor** [comment]
I am seeing that one very often but seldom on the first "cold" where the progress seems to be reported ok.
I do see the problem however on subsequent runs.
