### ISSUE TITLE
Use a 24 hours clock

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#1949]
## Abstract

Use a 24 hours clock instead of  AM/PM to avoid mistakes.

## Motivation

AM/PM is rather confusing (https://www.npl.co.uk/resources/q-a/is-midnight-12am-or-12pm#:~:text=Midday%20and%20midnight%20conventions&text=It%20is%20often%20said%20that,morning%20and%2012pm%20is%20midday.&text=Times%20in%20the%20first%20hour,given%20as%2012%3A47%20pm.)

If I click on the "now" button, Rokti shows me a 24h formatted time (using my locals settings likely):
![image](https://user-images.githubusercontent.com/738724/102697192-4a775800-4234-11eb-835f-ae595eed2e7b.png)

The date/time picker however goes back to the confusing AM/PM clock:
![image](https://user-images.githubusercontent.com/738724/102697158-ed7ba200-4233-11eb-8bdc-3609a2e52ebe.png)

Ask yourself what you click if you want from Monday midnight (first hour of the monday) to Monday midnight (last hour of the day) using those AM/PM options....

## Specification

Use a 24h clock. It helps avoiding errors.

**Comment by LefterisJP** [comment]
Oh yes! I would love this. I hate the AM/PM notation. @kelsos I guess this is configurable in the datetime component in the frontend? Can you easily handle this?

**Comment by kelsos** [comment]
It should be, I will have to check
