### ISSUE TITLE
Let user define start of their tax year and offer a few presets

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#1950]
## Abstract

For most, users will use Rotki to process taxes for a given fiscal year. That probably depend based on the users country and preferences though. As a result, the freedom given by the date and time picker is a little too much. 

## Motivation

Since users usually calculate taxes yearly, having the ability to request "Year 2020" instead of 01.01.2020 @ 0:00 -> 31.12.2020 @ 24:00 makes it much simpler and void other potential issues (see #1949).

## Specification

Let the user define the day of year where the tax period start: <start_day>.
Offer preset timeframes for the Tax Report where Rotki generates dates and time:
- from <start_day> @ 0:00
- to <start_day> +1y @ 24:00

The current pickers and date/time could be left as is at first and become an "advanced" option later.

**Comment by LefterisJP** [comment]
@kelsos has also mentioned this. He wanted to add presets like we do with the networth graph. So 1y, 3m, 1m etc.

Users may also need to report in a quarterly basis, not only year.

Also many users I have talked to (me included!) want profit/loss report in a custom date range to analyze how they have been doing. But yes agreed this could be sort of a more advanced option.

**Comment by LefterisJP** [comment]
@kelsos I am scheduling it blindly for next release, but you schedule it for when you can. I just put it in to make sure we don't forget about it and because we had a discussion about exactly what @chevdor is asking very recently.

**Comment by kelsos** [comment]
I wanted to add this for soooo long 😁

**Comment by LefterisJP** [comment]
Unfortunately this did not make it in 1.11.0. Pushing to 1.12.0. Should be an easy addition in the frontend.

**Comment by kelsos** [comment]
I am on it so it will be in the next release

**Comment by chevdor** [comment]
No worries and thanks for considering it.

**Comment by kelsos** [comment]
Small tease

![image](https://user-images.githubusercontent.com/2269732/103371071-d5770e80-4ace-11eb-9f48-66fa36b6a065.png)

I found having to deal with the custom selection as a default pretty annoying, to be honest. This was every time single time I was going to the screen :D

**Comment by chevdor** [comment]
I don't have much comment here, I find it very good.
You show only the last 5 years, that sounds good to me. The ordering suprised me but it makes sense as you did IMO.
Splitting in Quarter probably makes sense.

Cherry on top would be to remember the users choice for the next time.

**Comment by kelsos** [comment]
Good idea I will add it to the todo list
