### ISSUE TITLE
Backup/restore of the user data / preferences

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#1952]
## Abstract

Adding several accounts and exchanges into Rotki can be a lenghty process.
Most "less technical" users will not be able to generate a DB backup/dump. Most users will NOT know where the data is located on disk.

## Motivation

Backups are important adn time savers...
Such a backup will be useful for users to recover their Rotki after losing data or migrating to a new device.

## Specification

Since most of the relevant Rotki data is in the SQLlite db, a partial dump/backup of the DB is likely sufficient.
Any data that can be downloaded again (such as rates, transactions, etc... does not need to be backed up). Settings however, accounts, echange keys, should be backed up.

A basic approach would be to:
- lock the db to ensure that no write can occur
- dump/export the relevant data (=everything but what can be downloaded)
- make sure to include a file containing information about the backed up environment such as the schema version maybe? as well as the Rotki versions and some information about the backup itself: is it encrpyted ? (see below)

Make a zip of the whole thing and call it a day :)

To simplify the restore, I would suggest to NOT support any kinda of merging. If the db file exists, it can be renamed with a timestamp and the new restored DB file takes it place.

Open questions: should the backup encrypted (IMO yes but it requires the users to properly backup their passwords as well...) or should the user have an option to not ecrypt the backup and potenitally expose the API keys of the exchanges.

**Comment by LefterisJP** [comment]
This feature already exists for premium users: https://rotki.readthedocs.io/en/latest/usage_guide.html#sync-data-with-rotki-server

We already do an encrypted backup of the DB and store it in our servers (opt-out by default) for premium users.

And yes it's already encrypted and I would not like to expose unencrypted information as there is way too many things that could leak and lead to a disaster.

I don't see any value implementing this for free users as it's one of the features our paid users actually like (and have saved their  asses a few times when they reinstalled their OS and lost their data)

If the already implemented feature satisfies the requirements please close the issue.

**Comment by chevdor** [comment]
Gotcha, I am not yet acquainted with the premium features list.
Since you have it already, I am closing this request.

**Comment by LefterisJP** [comment]
Thanks @chevdor. Btw I know you don't like discord, but even Kusama has one! :smile: 

For easier more frequent chatting you can also hop in there. Many of us are online there quite often: https://discord.gg/aGCxHG7

**Comment by chevdor** [comment]
AFAIK Kusama has a "bridged" one so I can keep with using decentralized and open source solutions :-p
