### ISSUE TITLE
Add Swiss franc CHF support

### ISSUE THREAD

**Issue by philhug** [rotki/rotki#1955]
## Abstract

Add Swiss franc (CHF) support to rotki.

**Comment by LefterisJP** [comment]
Hey @kelsos can you handle this?

For some reason CHF is missing from the frontend code here:
https://github.com/rotki/rotki/blob/799ff8d6a407fe170761cb929499d3bec37b8954/frontend/app/src/data/currencies.ts

We got it in the supported FIAT currencies in the backend code:
https://github.com/rotki/rotki/blob/799ff8d6a407fe170761cb929499d3bec37b8954/rotkehlchen/constants/assets.py#L3-L32

Also check if after adding CHF they are in sync or if more are missing.

Any ideas for a way to keep those lists in sync?

**Comment by kelsos** [comment]
No idea, try to not forget the frontend when we add currencies in the backend?
