### ISSUE TITLE
Update ManualBalances table and form to show location icons

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1960]
## Abstract

It seems that while the manual balances card on the dashboard will show icons for the locations, but the location selector and the manual balance form will not.

### Task

- [x] Update the manual balance form
- [x] Update the manual balance table

### Notes

This might require a bit of rethinking on how the trade locations/trade location data work.

**Comment by LefterisJP** [comment]
Ah indeed nicely spotted @kelsos. Please schedule it for a release. IF you think 1.11.0 is practical do so. I am not sure how much time this would take so leaving it up to you.

 If not, push it for 1.12.0.

I am also adding it to our kanban.

**Comment by kelsos** [comment]
I will have to look at it after merging the extraction PR. I currently am taking a look through all the places I changed/modified during the extraction to at least make sure that something obvious is not off. And also noting any other places that might need change/update.

**Comment by kelsos** [comment]
What is interesting is that I implemented this at some point, but I completely missed updating the issue.
