### ISSUE TITLE
Track ETH2 validators daily income for taxes

### ISSUE THREAD

**Issue by tfelix** [rotki/rotki#1993]
## Abstract

Currently I can only see the total income for a ETH2 validator. As far as I know, taxes for staking reports are required to be tracked on a regular basis (daily, maybe weekly) for tax reports at the end of the year. As an example what could be needed as a basis for tax reporting would be:

Validator 0xABC
Income per Day
01.01.2021: 0.01 ETH @ 730 €/ETH -> 7.3 €
02.01.2021: 0.02 ETH @ 710 €/ETH -> 14.2 €
03.01.2021: 0.01 ETH @ 700 €/ETH -> 7.0 €

Total Income is then the sum of all the daily income.

## Motivation

The current support for ETH2 staking is nice but I dont think it is enough to support proper tax reporting at the end of the year. At first tests with the premium subscription I could also not see validator income appearing in the generated tax report. If it apears it sould be calculated on a daily, at least on a per weekly basis to keep track of price fluctuations during the course of the year.

## Specification

The requirements would be:
- Calculate or query per validator income on a daily basis from beacon chain
- Keep track of the average ETH price of a particular day
- Calculate the daily income for a validator and use this to report it on tax report

**Comment by LefterisJP** [comment]
Thank you for the issue @tfelix.

This is something we definitely want to and will add eventually.

The settings here should be customizable as always since the way staking accounting works, especially for ETH2 where it's locked and untradeable, varies depending on user jurisdiction.

**Comment by Giladio** [comment]
This will most definitely be a great feature. 
If possible to make this a client-side query and not just an API endpoint, so we can just print it out straight from the terminal it would be great. Also if the output can print out all validators retro-actively this will be amazing.

Thanks!

**Comment by LefterisJP** [comment]
I think a first implementation of this can be sufficient for most users by implementing: https://github.com/rotki/rotki/issues/2379

And once done and usable we can probably open a separate issue for autodetection by an API or by asking own node instead of needing to import a CSV. But step by step.

**Comment by tfelix** [comment]
Better then nothing of course and as a first implementation surely okay but its of little value to the user as taxes must usually be paid in fiat, so only tracking the daily income in ETH of the validator would not really help the user a lot (ok might be helpful if the user has a lot of validators running). But the outcome basically would be:

With this feature request proposal: Export from Rotki -> user is done.
With #2379 alone: User exports CSV from Rotki, users must visit coinmarketcap.com and get historical ETH exchange rates and downloads this CSV, combine both CSVs in Excel manually, multiply ETH earnings with fiat rates to get earnings in fiat -> user is done

**Comment by LefterisJP** [comment]
Oh no @tfelix ofcourse rotki would automatically calculate all this for you. We would calculate the equivalent ETH price at all timestamps and include it in the PnL report. It's detailed in the issue above.

**Comment by LefterisJP** [comment]
This is also done via #2379 and will be in v1.15.0. For improvements or other data sources additional issues can be opened.
