### ISSUE TITLE
cryptocompare error

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2011]
Uprade Cryptocompare account?

Skipping action at  07/02/2017, 14:52:40 during history processing due to inability to reach an external service at that point in time: Failed to query cryptocompare for: "https://min-api.cryptocompare.com/data/v2/histohour?fsym=DELETED=USD&limit=2000&toTs=1364198400". Error: You are over your rate limit please upgrade your account!. Check the logs for more details

Now got 20 ofthese whilst doing tax return

### System Description

Operating system: 
Rotki version:

**Comment by LefterisJP** [comment]
This means your ip got rate limited by cryptocompare. When querying tax report for the first time or after a very long time it makes a lot of queries to the cryptocompare API which very often results in rate limiting.

Try again a bit later. Or get a cryptocompare API key. It should eventually work fine though. Tax reports are caching historical price queries so after a few tries it will no longer give you this error.

We already are aware of this issue and are working to mitigate it. Check related issues below.  For more questions hop on our discord or write here.

Related issues:
Also query coingecko for historical prices - https://github.com/rotki/rotki/issues/224
Relieve tax report pressure by running tasks on idle time - https://github.com/rotki/rotki/issues/968
