### ISSUE TITLE
Tax 'Export CSV' button instead does not work (v 1.11.0) 

### ISSUE THREAD

**Issue by plutoegg** [rotki/rotki#2012]
## Problem Definition

After generating a tax report, I want to export a CSV containing the report. When clicking 'Export CSV' it opens a window to Open a CSV instead of allowing me to save a new one. 

<img width="1045" alt="Screenshot 2021-01-02 at 09 36 21" src="https://user-images.githubusercontent.com/22115014/103454648-09744e80-4cde-11eb-9748-8ff5f0e3cc10.png">

### System Description

Mac Catalina

Operating system: 
Rotki version:

**Comment by LefterisJP** [comment]
Hey @plutoegg that is actually a window to select a directory onto which to export a number of csvs. It's strange that in OSX there is no prompt saying to "Select a directory". In Windows and Linux there is.

Will see if we can make it more explicit.
