### ISSUE TITLE
Option to selectively ignore trades, deposits, and ETH transactions

### ISSUE THREAD

**Issue by Michael-A-Heuer** [rotki/rotki#2015]
## Abstract

Currently, it is not possible to ~~(partially)~~ ignore trades, deposits, and Ethereum transactions.
This is a helpful feature to correct tax reports (e.g. if currency was bought for third persons).

## Motivation

I bought ETH for a friend on an exchange and send it to his wallet. This messed up my subsequent tax report calculations.
Accordingly, an option to ignore/exclude specific trades/transactions from the tax report calculation would be helpful.

~~In my case, the ETH amount I bought for a friend was part of a larger trade I made.  
Accordingly, a relative correction would be handy.~~

## Specification

To realize this feature, the user could
1.  identify the trade from the `History > Trades > Closed Orders` list
2. click an `ignore_trade` checkbox ~~specify a `correction_factor` (on the interval `[0,1)`)~~  in the dropdown menu (where you can already annotate the trade) 

~~The `correction_factor` is multiplied with the `amount` and the `fee`of the trade.~~ All subsequent calculations can proceed normally.
~~For example, with `correction_factor=0.123`,  87.7% of the trade is ignored in the calculation.~~

Analogously, this should be possible for the items in the `History > Deposits & Withdrawals` and `History > Ethereum Transactions` lists.

**Comment by Michael-A-Heuer** [comment]
I realized, that the simpler option is sufficient.

**Comment by LefterisJP** [comment]
Hey @Michael-A-Heuer as discussed in discord here is an intermediate solution that you will be able to use immediately (soon as the PR https://github.com/rotki/rotki/pull/2025 is merged) before the whole thing is properly implemented.

The way to use it is:

1. Open up rotki with your account
2. Download [httpie](https://httpie.io/). If you know how to do it with curl it's also good, but htttpie is easier at least for me.
3. Make sure you can access the rotki api from another terminal. Type `http GET http://localhost:4242/api/1/users`. The port should be `4242` as this is the default port for production. If the above does not work ping me on discord.
4. Get all currently ignored trades by `http GET http://localhost:4242/api/1/actions/ignored`. This should return an empty list at the moment.
5. Go to rotki's trade history and find the "link/id" of each trade you want to ignore.
6. After you gather all the trades you want to ignore formulate the api call like this: `http PUT http://localhost:4242/api/1/actions/ignored action_ids:='["AAAA-BBB-CCCCCCCC-ZZZZ-DDDDDDD1609807719.0817","BBBB-JXXXX-YYYYYY-AAAA-IIIIIII1609806934.7499"]'. This should return a list of all ignored assets after the addition.
7. At this point run `http GET http://localhost:4242/api/1/actions/ignored` and make sure the above are returned. If yes, then it worked and you can run the tax report. It should ignore all trades with the given id.

In case you want to delete any of the action ids then you can do the same call but replace `PUT` with `DELETE`. Like so: `http DELETE http://localhost:4242/api/1/actions/ignored action_ids:='["AAAA-BBB-CCCCCCCC-ZZZZ-DDDDDDD1609807719.0817","BBBB-JXXXX-YYYYYY-AAAA-IIIIIII1609806934.7499"]'`

**Comment by LefterisJP** [comment]
After #2025 we still need:

- api doc entries
- turn that identifier into the unique identifier of the action and get it
  provided by the frontend from the UI
- Make it also work from deposit/withdrawals and ETH transactions

**Comment by LefterisJP** [comment]
As discussed in the standup it makes sense to move this to 1.12.0 as not too much work is left and it's useful.

**Comment by LefterisJP** [comment]
Fixed by #2081
