### ISSUE TITLE
Remove unused setting historical_data_start

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2017]
## Problem Definition

With the current work I am doing in the cryptocompare query the `historical_data_start` setting is no longer needed. It was only used as a way to know how far back to query for prices of each asset to save time. Now that the cryptocompare histohour queries are moving to a background task we will just get all available data.

## Task

Remove the setting.

**Comment by GeorgeJoLo** [comment]
Hello! I have never tried something. This seems good for me. How could I take care of it?

**Comment by LefterisJP** [comment]
Hello @GeorgeJoLo.

You would have to try and and read the code and remove the settting from all places where it exists. But it's a bit more complicated since it should depend on an unopened PR I am working on.

If you remove it from all places where it is used though I can adjust. A PR that does something similar by removing another setting is here: https://github.com/rotki/rotki/pull/2004
