### ISSUE TITLE
Add MIR airdrop to the supported airdrops

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2018]
## Abstract

The new feature doesn't pick up the MIR Mirror Airdrop of 220 MIR if an address had 100 UNI in it.
## Motivation

This airdrop wasn't small $260 per address  
https://airdrops.io/mirror-protocol/#:~:text=%20%20%201%20Visit%20the%20Mirror%20Protocol,and%20Coinbase%20will%20be%20available%20soon.%20More%20

**Comment by yabirgb** [comment]
I tried this some time ago doing a query in the bigquery for ethereum but didn't success. The other day I found this repo that might be useful.  https://github.com/Mirror-Protocol/mirror-airdrop

**Comment by yabirgb** [comment]
Closing this issue as there is no official CSV provided with all the addresses eligible for the airdrop. If this CSV is provided we can reopen it
