### ISSUE TITLE
Crypto.com location is displayed in key accounts list

### ISSUE THREAD

**Issue by CPatchane** [rotki/rotki#2023]
## Problem Definition

Rotki handles Crypto.com app transactions only via the csv import. It doesn't handle the Crypto.com exchanger for now.
But when we want to add a new account keys, we can find it in the choices list.
<img width="1021" alt="Screenshot 2021-01-05 at 13 29 19" src="https://user-images.githubusercontent.com/10224453/103646632-45b3e300-4f5a-11eb-9d56-035955ff5a56.png">

### System Description

Operating system: MacOS
Rotki version: 1.11.0

**Comment by LefterisJP** [comment]
@kelsos This is a bug in the frontend, as the exchange is supported only as a location due to the CSV but should not be in the import of API keys as they don't have an API.
