### ISSUE TITLE
Tokensets balance not collected does Rotki already support Tokensets?

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2027]
I have a Tokensets address but Rotki only picks up the eth and Dai but not the Tokenset itself.....the part that actually matters

I'm not even sure if Rotki supports Tokensets

**Comment by LefterisJP** [comment]
Rotki does not support tokensets yet. The issue is here: https://github.com/rotki/rotki/issues/1010

**Comment by LefterisJP** [comment]
@Blackswan122 for questions like that, if we support something yet or not it's much easier if you ask around in discord first: https://discord.gg/aGCxHG7
