### ISSUE TITLE
Add Haven Protocol (XHV) as a supported asset

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#2033]
## Abstract

Add asset support for Haven (XHV).

Haven is a privacy blockchain protocol similar to Monero.
https://www.coingecko.com/en/coins/haven
https://www.cryptocompare.com/coins/xhv/overview

**Comment by isidorosp** [comment]
No idea how I didn't see it but it's already included. Awesome =D

**Comment by LefterisJP** [comment]
I love the issues that close themselves :D
