### ISSUE TITLE
Please add NRG (Energi)

### ISSUE THREAD

**Issue by havrancek** [rotki/rotki#2034]
As a possible ETH challenger, NRG has big plans with crypto infrastructure... in their roadmap, there is EnergiX exchange and are working with Defi already, it would be very appreciated

https://www.energi.world

thank you in advance

**Comment by LefterisJP** [comment]
@vnavascues When adding NRG please also add:

- XED
    * https://www.cryptocompare.com/coins/xed/overview
    * https://www.coingecko.com/en/coins/exeedme
- TVK
    * https://www.cryptocompare.com/coins/tvk/overview
    * https://www.coingecko.com/en/coins/terra-virtua-kolect

Should not take more than 5 mins

**Comment by LefterisJP** [comment]
Done by #2038
