### ISSUE TITLE
Incorrect profit calculation perhaps caused by unrecognized Binance BTC deposit 

### ISSUE THREAD

**Issue by davidebaldini** [rotki/rotki#2035]
## Problem Definition

A deposit of about 0.06 BTC into Binance is reported by Rotki as an amount equal to 0 BTC. This might cause an excessive profit to be calculated for the subsequent sell operation of these BTC into USDT.

This is a screenshot of the tax report CSV exported by Rotki:
[removed]

Between rows 120 and 124 incl. of the spreadsheet, these operations are reported in what I believe is the correct chronological order:

* 120: buy 0.016 BTC from Kraken
* 121: buy 0.051 BTC from Kraken
* 122: withdraw approx 0.06 (0.016 + 0.051) BTC from Kraken into my owned wallet. Amount withdrawn is not reported by Rotki.
* 123: deposit approx 0.06 (0.016 + 0.051) BTC into Binance from my same wallet. Amount deposited is not reported by Rotki.
* 124: sell approx 0.06 BTC for USDT on Binance. Something is wrong with the calculated profit derived from this operation.

### Log file

Log file is empty at the moment. At the time the CSV was exported, the log complained about two missing data points from Binance in 2018. No other issue was reported. I may regenerate the log if needed.

### System Description

Operating system: debian 10.7
Rotki version: 1.11.0

**Comment by LefterisJP** [comment]
Hey @davidebaldini thanks for the issue!

Deposits are not taken into account in the tax report so this should not affect anything in the calculation.

When you go into the history tab and locate that same deposit and how much BTC does it show? Hover over the amount as they are rounded to the 2 decimal digits by default.

> Amount withdrawn is not reported by Rotki
> Amount deposited is not reported by Rotki.

It should be in the history tab, where you see your deposit and withdrawals. For the accounting purposes it is not taken into account and therefore not shown. The only thing that is taken into account is the loss from the fees from withdrawals. So for 122 you paid ~10.79 EUR in BTC for the withdrawal fee and that is counted as an expense.

> Something is wrong with the calculated profit derived from this operation.

What is wrong? Are you in Germany? It seems that you are using the default settings of assets not being taxable after holding for 1 year with a FiFo order.

In order to get a lot more information from logs you would need to run rotki in debug mode to have the logs populated: https://rotki.readthedocs.io/en/latest/contribute.html?#id2

**Comment by davidebaldini** [comment]
Thank you for the information. I re-checked the historical logs from my exchanges and I believe the profit computed by Rotki for operation #*124* from the above spreadsheet is incorrect. To clarify the issue:

* on December 29th, before I executed operation #*120*, I had no BTC deposited on any exchange nor on any other wallet of any kind;
* operation #*120* and #*121* exchanged all FIAT available on Kraken into BTC;
* operation #*122* withdrew the BTC just purchased from Kraken into my hot wallet, whose addresses are registered with Rotki; after this withdrawal, no FIAT remained on Kraken, and only 1.9µBTC (currently about 0.05€) remained on Kraken;
* operation #*123* deposited all BTC in my possession into Binance, on which no BTC were present before this deposit;
* operation #*124* sold the BTC just deposited in return of USDT; after this sell I no longer owned BTC on any exchange or wallet.

The purchase did execute on Kraken at approx. 26,250 BTC/USD split in two orders, one in USD, the other in EUR, as shown in screenshot; however, both #*120* and #*121* report `paid_asset` as `EUR`. 
![kraken_history](https://user-images.githubusercontent.com/8339909/103846307-1a3a1100-509e-11eb-96da-413e8ee5d13f.png)

The sale executed on Binance at approx. 26,870 BTC/USDT
![binance_history](https://user-images.githubusercontent.com/8339909/103846847-56ba3c80-509f-11eb-8440-296fb4326684.png)

Coarsely, the effective profit I realized is about 2% (26,870 / 26,250) or 35 USDT minus fees, but #*124* reports 250€.

----

> When you go into the history tab and locate that same deposit and how much BTC does it show? Hover over the amount as they are rounded to the 2 decimal digits by default.

The withdrawal from Kraken and subsequent deposit on Binance are both recorded with the correct amount (~ 0.06 BTC). However, the Binance trades don't appear under the `trades` tab:

![rotki_history](https://user-images.githubusercontent.com/8339909/103848184-190ae300-50a2-11eb-8a73-a69c42ae0e29.png)

----

Complete log file under debug mode after producing a tax report: 
[rotkehlchen.log](https://github.com/rotki/rotki/files/5779444/rotkehlchen.log)

Rotki's notifications bell reported several errors among:

* "Error at periodic client query: timeout of 30000ms exceeded"
* "During trade history query we got:The backend responded with a 404 not found error for task 6: Create tax report. History report is probably not complete."
* "Error: timeout of 30000ms exceeded"

**Comment by LefterisJP** [comment]
Hey @davidebaldini thanks for the detailed report.

> During trade history query we got:The backend responded with a 404 not found error for task 6: Create tax report. History report is probably not complete

If you see this then that means that the entire operation should not be trusted as somewhere an error was encountered. You should try again until it works. We are working on improving the resilience of the accounting section to avoid these kind of errors as much as possible.

> Complete log file under debug mode after producing a tax report:

I will take a look at the log file. I removed the log after downloading from your post as it probably contains sensitive information about you. For stuff like that it's better done in private in discord: https://discord.gg/aGCxHG7

> however, both #120 and #121 report paid_asset as EUR.

You are looking at the ledger entries in kraken. You should be looking in the orders history, that is what rotki pulls (the completed ones).

> However, the Binance trades don't appear under the trades tab:

I noticed that you are on the free version. Perhaps you are hitting the limit? If not then try to purge the binance cache and query them again. Go to Settings -> Data & Security -> Select binance and then click on purge exchange cache.

-----

If I understand correctly you seem to expect Rotki to calculate profits in a LiFo order? That is not the case. Rotki calculates profits on a FiFo order. Lifo is still to be implemented: https://github.com/rotki/rotki/issues/44

Also unless you have changed the settings it considers that after holding a token for 1 year (in FiFo order) its selling is not taxable.

**Comment by davidebaldini** [comment]
Thank you for the clarifications. Operation #*120* and #*121* are represented by the two topmost rows in the following screenshot; one is quoted in EUR, the other in USD. Both have status `canceled` but did execute almost all their volume and were canceled by Kraken due to "out of funds", so only rounding error dust remained unexecuted.

![kraken_order_history](https://user-images.githubusercontent.com/8339909/103884726-445ff300-50df-11eb-9517-2bebeadecdf9.png)

> If I understand correctly you seem to expect Rotki to calculate profits in a LiFo order? 

If I understand, for operations #'120' thru #'124' FIFO or LIFO should not make a difference, as I owned no other BTC before #'120', and I sold all BTC at #'124' on the same day I purchased them.

**Comment by LefterisJP** [comment]
Looking at the logs I see trade timestamps even as far back as for example February 2017 in Kraken.

I guess you are putting only a certain period of time in the tax report, right? But Rotki always has to check your entire history to establish a cost basis for each asset and then it calculates profit/loss only from the trades of the given period. But it does go through the entire history to establish the cost basis in a FiFo basis.

Otherwise if for example you have a sell of BTC now that you bought 3 years ago in Kraken and we only check this year we would not know how much you bought it for.

**Comment by davidebaldini** [comment]
> I guess you are putting only a certain period of time in the tax report, right?

Correct, only the fiscal year 2020.

----

Could you please delete your edit from the revision history of https://github.com/rotki/rotki/issues/2035#issuecomment-755866390 ? 
Thanks!

**Comment by LefterisJP** [comment]
> Could you please delete your edit from the revision history of #2035 (comment) ?

I did not know you could do that like this. It's now done.

Generally join our discord and ping there in DMs for private data like this.

> Correct, only the fiscal year 2020.

yeah so as I said in https://github.com/rotki/rotki/issues/2035#issuecomment-756100642 it seems that there must be remaining Bitcoin from before during the cost basis calculation. So it uses earlier buys in FiFo order from which the difference is calculated. So for selling that BTC you got 1811 UST which is around 1472 EUR. And rotki sees that you paid for this BTC ~1221 EUR.  This prices comes from the cost basis of everything you have bought-sold in all years in a FiFo order, not only in 2020.

**Comment by davidebaldini** [comment]
Thanks for your explanation.

> it seems that there must be remaining Bitcoin from before during the cost basis calculation.

I'm aware of how FIFO and LIFO are intended to work. Rotki incorrectly believes that there is residual BTC from earlier operations preceding operation #*120*, but there is no residual BTC at #*120*, only some "dust" amount of 1.9*10<sup>-6</sup>BTC (~ 0.05 €). 

So, as you suggested, I'll try to purge the cache and regenerate the tax report.

As for the issue in https://github.com/rotki/rotki/issues/2035#issuecomment-756054406, Kraken's order history lists one of the two transactions with a quote in USD, but Rotki lists both in EUR. Maybe I should open a separate bug report for this?

**Comment by LefterisJP** [comment]
> I'm aware of how FIFO and LIFO are intended to work. Rotki incorrectly believes that there is residual BTC from earlier operations preceding operation #120, but there is no residual BTC at #120, only some "dust" amount of 1.9*10-6BTC (~ 0.05 €).

I see. This is really hard to debug with a huge list of actions like this. From the logs I see a big list of actions and being residual BTC from early years.

> As for the issue in #2035 (comment), Kraken's order history lists one of the two transactions with a quote in USD, but Rotki lists both in EUR. Maybe I should open a separate bug report for this?

I think this is due to the main currency being in EUR. But would need to confirm after taking a deeper look in the code. But sure you can open a separate issue to track it.

**Comment by LefterisJP** [comment]
Closing the issue due to lack of specific information to debug further.
