### ISSUE TITLE
Introduce help/info about required permissions when adding an exchange

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2037]
## Problem Definition

There is no documentation or information on what exchange permission the user has to use when creating an API key for an exchange.

The suggestion is to add a help/hint area in the frontend so that users can see directly what permissions are required.

@LefterisJP you wrote something about finding the permissions in code and docstrings right?

### Task

- [ ] Add permission list in the UI

**Comment by LefterisJP** [comment]
> @LefterisJP you wrote something about finding the permissions in code and docstrings right?

Yes.

There is also something that both a user and I myself noticed with Kraken.

If you are activating a kraken API key and you just created it, it needs about 30 seconds to actually respond properly from the API. If you immediately create it and just put it in rotki, kraken will say it's invalid. So a message to the user that if they just created the api key in kraken they should wait 30-60 seconds would be good.
