### ISSUE TITLE
Add GRT support for tracking delegation and delegation and indexing rewards.

### ISSUE THREAD

**Issue by step21** [rotki/rotki#2044]
## Abstract

Similar to other defi products, it would be great if delegating to and by indexers could be included in rotki.

## Motivation

Assuming that there are several current or potential users of rotki that have GRT or will have it in the future, this seems useful to have.

## Specification

I would assume that the basic data structures and queries necessary are similar to defi products. As such, maybe their implementations could be used? (I am not familiar with defi code in rotki to say whether this is feasible)
this might help a bit https://github.com/aditya-manit/grt-rewards-calculator

**Comment by LefterisJP** [comment]
you are speaking specifically for GRT, right? Each protocol would need different work.

**Comment by step21** [comment]
Yeah, sorry, this is for GRT / thegraph only.

**Comment by yabirgb** [comment]
Adding a bit +1 to this issue

**Comment by step21** [comment]
Thanks. I'd love to get back to it but have to finish other things first.

**Comment by LefterisJP** [comment]
Would love if someone made this

**Comment by step21** [comment]
I started from scratch on this. (after a long break) But no estimate yet. Maybe I’ll do an early WIP PR next week and then this can keep me on track. (Assuming no conflicting commitments)

**Comment by LefterisJP** [comment]
Fixed by #6712, #6720 and #6733

**Comment by step21** [comment]
cool, nice to see this :)
