### ISSUE TITLE
Auto Update Mechanism

### ISSUE THREAD

**Issue by froid1911** [rotki/rotki#2046]
## Abstract

It would be awesome to have an autoupdater for latest rotki releases.

## Motivation

Right now the users have to download the latest rotki release from github or through brew (1.11 not released at brew?).
This seems very complicated. An auto update mechanism could help to bring the latest features to the users without they have to do something.

## Specification

Could this help?
- https://www.electronjs.org/docs/tutorial/updates

**Comment by LefterisJP** [comment]
We really want to do this at some point.

I thought we had an issue but seems we don't?

@kelsos do we have another issue? Probably not. How hard would it be to implement this? You had given it some thought in the past.

**Comment by kelsos** [comment]
OSX requires signing in order to work:  https://www.electron.build/auto-update
For Windows I am not sure if it will work with the portable executable, we might need to switch to installer.
For Linux I have no idea.

**Comment by LefterisJP** [comment]
So in short non-trivial and would require work, right? There is no other issue so we should keep this?

But we need to schedule this at some point. It's going to really improve user experience.

**Comment by kelsos** [comment]
I have to check if there are other issues. While I checked it and we discussed it a couple of times, I don't remember if we ever opened an issue.

**Comment by froid1911** [comment]
I didnt found any other issue, which also surprised me :D

**Comment by kelsos** [comment]
@froid1911 It is one of these issues we keep discussing with @LefterisJP repeatedly but then forget to open the issue itself :) Thanks for opening

**Comment by kelsos** [comment]
@LefterisJP I am moving it to v1.15.0
