### ISSUE TITLE
Security Data Issues - Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [rotki/rotki#2049]
## Problem Definition
BITTREX_API_SECRET in clear text

Hi ,

url : https://github.com/rotki/rotki/blob/b2cf2775647a1f1abf3c944cb54e3514ccbaba31/frontend/app/cypress.env.json
https://github.com/rotki/rotki/blob/b2cf2775647a1f1abf3c944cb54e3514ccbaba31/frontend/app/.env.test

![image](https://user-images.githubusercontent.com/46863888/103933917-c9252e00-512c-11eb-92e6-5d243dd89f27.png)

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by LefterisJP** [comment]
@shaybenb thanks for opening the issue and letting us know but this is just an empty account with no balances, just to test bittrex's API. It is for testing purposes in the CI and poses no security threat.

But really appreciate that you took the time to warn us! Hope you stay around and check at one of our many issues and help us.
