### ISSUE TITLE
Add support for Celsius token (ERC20)

### ISSUE THREAD

**Issue by efnats** [rotki/rotki#2051]
## Abstract

Add support for Celsius ERC20 tokens

## Motivation

the only reason why I like to see it is because I am interested in the token ;)

## Specification

It is an ERC20 token. https://www.coingecko.com/de/munze/celsius-network-token

**Comment by LefterisJP** [comment]
Hey @efnats this got merged last night and should already be visible in the app

**Comment by efnats** [comment]
😍😍😍

That went really fast! Thank you!!!

Am Fr., 8. Jan. 2021 um 10:39 Uhr schrieb Lefteris Karapetsas <
notifications@github.com>:
