### ISSUE TITLE
See asset split per account

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#2058]
## Abstract

When I want to get an overview of what account holds what asset and how much, I must check all my wallets manually. It would be nice if I could see at a glance in Rotki how assets are distributed.

## Motivation

I have a few different accounts on Ethereum. Some common assets (like ETH and DAI) are split over several of them, and I'd like to see how they are divided across all my accounts. And some more rare assets (like UNI) are only in one or two accounts, and I'd like to be able to see which one, so I can fetch the correct wallet quickly when I want to trade or check something about the transactions, for example.

## Specification

Under Accounts & Balances > Blockchain balance, make the balances collapsible, and show them per account. Like how the different addresses under a Bitcoin xpub are presented.
<img width="1543" alt="Screenshot 2021-01-08 at 2 08 45 PM" src="https://user-images.githubusercontent.com/8545447/104019108-413a3500-51bb-11eb-9d17-14d9bd6702d6.png">

**Comment by kelsos** [comment]
@hjorthjort The eth accounts are collapsible and you should be able to see what a single account has

**Comment by hjorthjort** [comment]
Oh, now I see it. But the collapsing arrow is at the "wrong" end of the line, which is why I missed it I guess :)

**Comment by kelsos** [comment]
The function is a bit different that is why. But I am assuming that since this issue was about that exact functionality we can close it right?

**Comment by hjorthjort** [comment]
Still, it would be nice to be able to do the "reverse lookup", and see the accounts per assets, not just the other way around. It's less important now that you showed me this feature, obviously.

**Comment by LefterisJP** [comment]
> Still, it would be nice to be able to do the "reverse lookup", and see the accounts per assets, not just the other way around. It's less important now that you showed me this feature, obviously.

It's really important. We want to do this and I know that @kelsos also has some cool ideas in that respect. I think the issue for the reverse you are referring to is: https://github.com/rotki/rotki/issues/276

**Comment by hjorthjort** [comment]
Yep, this is a duplicate of that. Didn't find it when searching. We can
close this as duplicate.

Lefteris Karapetsas <notifications@github.com> schrieb am Fr., 8. Jan.
2021, 3:26 PM:
