### ISSUE TITLE
Address deprecated warnings

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#2061]
Running the unit tests we constantly get the following warnings:

`eth_utils`
```
rotkehlchen/typing.py:5
/rotkehlchen/typing.py:5: DeprecationWarning: The eth_utils.typing module will be deprecated in favor of eth-typing in the next major version bump.
    from eth_utils.typing import ChecksumAddress
```
`imp`
```
../../.virtualenvs/rotki/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py:15
.virtualenvs/rotki/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
```
`abc`
```
../../.virtualenvs/rotki/lib/python3.7/site-packages/flask_restful/__init__.py:17
.virtualenvs/rotki/lib/python3.7/site-packages/flask_restful/__init__.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Mapping
```
Fix them

**Comment by vnavascues** [comment]
It seems `imp` warning comes from `astroid` lib, and the `abc` one from `Flask-RESTful`

Imp warning
https://github.com/PyCQA/astroid/blob/c9fd1934e9c49d9052f64439fc7ea82026bce00f/ChangeLog#L14

abc warning
https://github.com/flask-restful/flask-restful/issues/851
https://github.com/flask-restful/flask-restful/pull/835

Rotki uses:
astroid==2.4.2
Flask-RESTful==0.3.7

**Comment by LefterisJP** [comment]
So for the last thing to close we are waiting until https://github.com/PyCQA/astroid/pull/857 makes it into a release I guess?

**Comment by LefterisJP** [comment]
We may end up waiting for a long time. Their last release in in last year's April :sweat_smile:

**Comment by LefterisJP** [comment]
There is nothing more actionable from our side here as we just need to wait for a new astroid release which would fix the last warning. Closing the issue.
