### ISSUE TITLE
Introduce websocket support for backend to frontend communication

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2062]
## Problem Definition

The current version of the application uses polling to fetch any messages, check for updates in progress or dates. 
The suggestion is to keep polling as a fallback and implement WebSockets support so we can directly notify the frontend of any changes in the state. 

For example:

Instead of polling for pending tasks we could directly notify the frontend to fetch the data for a completed task.
Instead of polling for messages, or progress, or some other automated action (maybe the backend automatically fetched fresh data. The backend can push notifications to the frontend for state changes so that the frontend can refresh or redraw.

## Tasks
- [ ]  Introduce a WebSocket server
- [ ]  Implement frontend support (fallback to polling on connection failure)

**Comment by LefterisJP** [comment]
I am moving this to v1.19.0 to at least start work on it. We can introduce it and then slowly start using it.

**Comment by kelsos** [comment]
> I am moving this to v1.19.0 to at least start work on it. We can introduce it and then slowly start using it.

Yes we don't have to move everything at once, we can start implementing stuff case by case and keep adding as we go.
