### ISSUE TITLE
Possibility of "close to tray"

### ISSUE THREAD

**Issue by havrancek** [rotki/rotki#2064]
Hey guys,
i would like to be able to close Rotki into tray and see a changing icon, for example, a green arrow pointing up, a red arrow pointing down would be sufficient for now
thanks in advance

**Comment by LefterisJP** [comment]
Hey @havrancek thanks a bunch for the issue. It's an interesting request. We will see what we can do.

@kelsos you mentioned it may be possible with the electron app, right?

**Comment by kelsos** [comment]
@LefterisJP -> https://www.electronjs.org/docs/api/tray

**Comment by LefterisJP** [comment]
Hey @kelsos so doing this only for the electron app should not be hard right? It's one of these things we have been pushing constantly but is it because it's hard? Or some tricky implementation detail? Or just not a priority?

Naturally would only be in electron and not docker mode.

**Comment by kelsos** [comment]
If nothing changes I still plan to tackle this issue. I did have a preliminary look already. I need to figure out how to reference the icon from background.ts but other than that it should not be hard no.
