### ISSUE TITLE
as a fan of Chocolatey, could you implement this feature?

### ISSUE THREAD

**Issue by havrancek** [rotki/rotki#2066]
Hi guys, again,
my request is about a way of updating rotki. There is this web: https://chocolatey.org/ which is a fine a subtle way of keeping your software up-to-date. Is it possible for rotki to become part of chocolatey package update service?
thanks in advance

**Comment by LefterisJP** [comment]
Hey @havrancek. Thanks for the issue. There are many package managers per OS and then again many different OSes. If I am not mistaken chocolatey is for Windows.

Adding rotki to a package manager can be done by anyone, since it's a community project: https://docs.chocolatey.org/en-us/create/create-packages

**Comment by kelsos** [comment]
Yes chocolatey is for windows and it is the most popular if I am not mistaken. Our CI build script for windows actually uses chocolatey to setup the build environment.

**Comment by LefterisJP** [comment]
So @kelsos is this something we can do easily?

Or should we just push it to the community, since anyone can add packages to package managers? As the CI build master it's your call.

If we push it please close this issue.
If we do it, plan on how and implement.

**Comment by kelsos** [comment]
I have never created a chocolatey package so I wouldn't know how to do it. 
If someone from the community has the experience and would like to provide some help that would be awesome.

**Comment by LefterisJP** [comment]
Closing this issue as we don't have the capacity to create and/or maintain a chocolately package at the moment. If someone from the community would like to do it that would be awesome.
