### ISSUE TITLE
Remove ICN

### ISSUE THREAD

**Issue by froid1911** [rotki/rotki#2110]
## Problem Definition

I still own ICN from 2017, but cant move it according to Iconomi.
From my perspective this is scam and scammers shouldnt get any attention.
Would be great if we remove it. If you want I can create a pull request.
 
## Logs

![image](https://user-images.githubusercontent.com/1188574/104816213-e7201c00-5819-11eb-9901-b516f98e9cd4.png)

### System Description

Operating system:  Mac
Rotki version: every

**Comment by froid1911** [comment]
https://github.com/rotki/rotki/pull/2111

**Comment by LefterisJP** [comment]
ICN token was deprecated back in 2018 and you were supposed to convert it: https://medium.com/iconominet/icn-conversion-process-begins-5b6e32443d9f. Perhaps you still can. It's better to ask them directly.

Rotki is a completely neutral application and passes no judgement on any project. There is no reason to remove a token at any point. Especially if it has trading history for a user. And I hope you understand that we can't remove a token if someone deems it a scam.

Plus removing is more complicated than just removing from the list. You would need to also run a new DB upgrade and go through all user entries that may have had ICN and remove them too,or else the users who owned ICN at any point would experience crashes.

If you don't want to see it I think you can ignore it from the settings.

**Comment by froid1911** [comment]
I asked them, but they can not do anything. 
I understand your point. Thank you for explanation.

**Comment by LefterisJP** [comment]
> I asked them, but they can not do anything

That really sucks.

**Comment by froid1911** [comment]
Yes. Thats why I do not want to support anything related to them. I hope you understand that.

**Comment by LefterisJP** [comment]
I do. If you do not want to see the token put it in ignored tokens and it should be ignored.
