### ISSUE TITLE
Edit timezone for date fields

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2121]
## Abstract

When editing dates e.g. in the ledger actions, the timezone is set implicitly from the device you are using.

I would like to be able to customise the timezone directly without having to change the timezone of the device I'm using.

## Motivation

This is useful if you live in a different timezone than when the event took place.

## Specification

I'm not sure if you would use the timezone code e.g. GMT or just an offset for this input field. For the developer to decide.

**Comment by LefterisJP** [comment]
So @kelsos would setting a user timezone other than the system one be easy? A frontend-setting alone would probably be sufficient so this can be a completely frontend task.

**Comment by kelsos** [comment]
There is no api for working with timezones directly as far as I am aware. But I could find a couple of hacky ways that it can be done.
The short answer is it's not trivial.

**Comment by LefterisJP** [comment]
Okay then don't prioritize it right now if it's not trivial. I thought this would be easy. We can do it but probably a bit later as we have a lot of other stuff to do too.
