### ISSUE TITLE
Incorrect Timezone offset: GMT +1

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2122]
## Problem Definition

My computer is set to London GMT timezone.

When I create a ledger action it shows the event having the timezone "GMT +1". GMT in winter is not +1, it's 0 offset, same as UTC.

## Logs

n/a

### System Description

Operating system: Mac OS X
Rotki version: 1.12.1

**Comment by LefterisJP** [comment]
@kelsos any idea here? Why would timezone be off here? Some DST setting?

**Comment by a7e8** [comment]
I tried replicating in a node REPL the same functions you're using but that wasn't the issue.

**Comment by kelsos** [comment]
Did you try the same on chrome's dev tools console? This is the closest environment you can get.

In my experience so far I have seen that the date adjusts automatically for DST. So if I pick a date that was in summer this will appear in DST but if I pick a date in winter it will appear in non-DST format, which would make sense.

**Comment by a7e8** [comment]
You're right this was a date in the summer so it's correct.
