### ISSUE TITLE
Toggling gas costs and asset movement fees 

### ISSUE THREAD

**Issue by jordansgithubftw** [rotki/rotki#2126]
## Problem Definition

Between generating two profit/loss reports I toggled off gas costs and asset movement fees to simplify. Second report still showed the gas costs and asset movement fees. This is not an urgent error but maybe reporting it could be of use in the future.

### System Description

Operating system: Ubuntu 20.04.1 LTS
Rotki version: v.1.12.1

**Comment by vnavascues** [comment]
@jordansgithubftw Thanks for reporting to us this, we found the issue and it will be fixed.

It seems to us that the reports are well generated according to the toggled settings (including or not the `asset_movements.csv` and `tx_gas_costs.csv`), but the UI summary indicators (i.e. green tick and red cross) are misleading and do not reflect the current settings state.

**Comment by LefterisJP** [comment]
Fixed by #2135
