### ISSUE TITLE
Importing Kraken's ETH2 staking rewards via API

### ISSUE THREAD

**Issue by jordansgithubftw** [rotki/rotki#2127]
## Abstract

Current withdraws, deposits, and transactions properly show when importing via Kraken's API. It would be nice to show the weekly rewards as part of income in the profit/loss report.

## Motivation

Rotki currently has ETH2 staking for self-ran validators which is very nice. Expanding the field of stakers would draw in new premium users and/or better support current ones.

**Comment by LefterisJP** [comment]
Hey @jordansgithubftw I guess this request is part of https://github.com/rotki/rotki/issues/569, so general support for staking in Kraken, right?

**Comment by LefterisJP** [comment]
I am closing this as a duplicate of #569
