### ISSUE TITLE
Allow user to customize order of price querying oracles

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2131]
## Abstract

At the moment both for historical prices and for current prices we check:

1. Cryptocompare
2. If that fails we check Coingecko
3. If that also fails we bail

This is a nice way but not failsafe as we just saw with NXM current price being wrong in cryptocompare but fine in coingecko. Resulting in all users getting the wrong price of NXM.

## Task

- [ ] Allow customization of order or price oracles query.
- [ ] Have a different setting (value can be the same) for current price and for historical price

**Comment by davidebaldini** [comment]
In view of #2137, wouldn't it be practical to retrieve all prices from all sources, and cross-compare them to automatically exclude any gross outliers? This way the user wouldn't be required to define any static order for querying the data providers, which possibly prevents the situation where all providers return some incorrect datum at different timestamps.

**Comment by LefterisJP** [comment]
Hey @davidebaldini even with only the current sources this would increase the running time of everything by a factor of 3x-4x due to the extra api queries and the api rate limits of each query. And we want to add even more sources so no that is really not practical to be doing by default. Rotki can already be quite slow at times so introducing what you propose would make it unbearable.

Perhaps there could be some kind of cross comparing setting you could turn on, but for that you would also need to figure out what to do in case of too big a difference, like ask for user input, or take the average etc.
