### ISSUE TITLE
During profit/loss report generation fill out % during history pulling

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2134]
## Abstract

The % during profit/loss report stays for a very long time at 0% making users wonder what is happening. The reason for this is that we only modify it when we go to the action processing part. For each action we go through we send its timestamp to the frontend.

But the bulk of the time is spent in the pulling of history. For that reason we should really find a way to report also the time spent in the pulling of history to the user.

## Task

Find a way to report history pulling to the user during profit/loss generation too. This should probably be combined with this: https://github.com/rotki/rotki/issues/1865

**Comment by kelsos** [comment]
Maybe we could do the whole calculation in the backend and return the percentage instead?

**Comment by LefterisJP** [comment]
> Maybe we could do the whole calculation in the backend and return the percentage instead?

yes I think this would make more sense.

**Comment by LefterisJP** [comment]
This is done via https://github.com/rotki/rotki/pull/2141 and https://github.com/rotki/rotki/pull/2154
