### ISSUE TITLE
Add useful metadata to csv-format tax reports

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#2145]
## Abstract

In v1.12.2, I love the new feature you implemented in the Tax Report:  "Show the selected accounting settings with which the user's tax report is generated #[1792](https://github.com/rotki/rotki/issues/1792)"  It is useful.

This information does not, however, seem to be recorded / encoded into the .csv report output, which would make it unavailable to me in my long-term archives of tax report history.  More importantly, it would also NOT be visible/accessible to any tax professional a Rotki user might consult with on jurisdiction-specific tax questions, typically by sending them the Rotki-generated csv data.

## Motivation

Without this feature recorded / encoded in the .csv data blob/output, the accounting settings will be lost from a long-term archive where the csv data is stored.
It would also NOT be visible/accessible to a tax professional a Rotki user might consult with on jurisdiction-specific tax questions, typically by sending them the Rotki-generated csv data.

## Specification

Add a row, or a few rows, of CSV meta data to the top of each csv output file, perhaps keyword/value pair, for each of the accounting settings, perhaps with a URL to where in the doc each setting is documented.

Optional, but useful:  explicit date-time-group, with both UTC and Local time zone, logged in that meta data of the time the report was generated, 
and what tax years (quarters?) it was covering in the tax report

**Comment by LefterisJP** [comment]
Hmm the problem here is the csv format does not cater for metadata. But what we could do is, since these are exported in a directory, we could add a "settings.json" with all the settings the exported report was ran in. Would that make sense for you?

**Comment by A2be** [comment]
That would probably be fine.  I'm not technical any longer, but as I recall, JSON is like the earlier/older XML syntax, and was explicitly designed to be parse-able by computer code and also readable by human.  So I can grok it in that format.

But one question for you/Rotki_product_owner to consider is: "**what format makes the most sense for the (hopefully many) accounting professionals who will one day touch and interact with Rotki accounting data?**  Not sure, but JSON might intimidate some of them, and thus be less helpful to Rotki adoption.  So...,, perhaps JSON for the most capable technical audience **AND** a brief txt file for the humans who are not technical _might_ be in order.  Your call.

I ideate. You triage, and you decide.

**Comment by LefterisJP** [comment]
I am adding this to the next release as part of the summary in the CSV export. If you activate a summary in the export you get both these settings, the rotki version and a summary of pnl per event type as requested by #3279 

![2021-08-02_16-20](https://user-images.githubusercontent.com/1658405/127876482-59a531c9-95cd-44e2-b169-449ff26af2be.png)
