### ISSUE TITLE
CSV export date format doesn't respect the set option

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2146]
## Description

The CSV has a preset format for date rendering. This should be customizable via the date format option.
Also, it would be nice if the user has the option to export the CSV with the dates being in local time instead.

A thing to keep in mind is that we might need to pass the locale from the frontend in the future in case the frontend runs in a different place with different settings than the backend.

### Tasks
- [x] Fix format
- [x] Implement option

**Comment by LefterisJP** [comment]
@kelsos too many RPGs man
![2021-01-22_22-08](https://user-images.githubusercontent.com/1658405/105547005-5310f180-5cfe-11eb-8a9e-0472a36d46f3.png)
