### ISSUE TITLE
Wrong reference for edgeless (EDG) in coingecko / Support Edgeware

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#2147]
https://github.com/rotki/rotki/blob/741223806dffd968c9fdccef4780117aaa005f60/rotkehlchen/data/all_assets.json#L4081

This should be 'edgeless'.

I also would like to have Edgeware in Rotki. But both tokens have the symbol EDG. How do you typically solve this?

**Comment by LefterisJP** [comment]
This is a bug then. Coingecko should have been `"edgeless"`. Thanks for finding this out.

Would you like to handle it?

As for how to handle tokens with same symbol it's easy. Just add the other one, edgeware in this case, with identifier "EDG-2" and make a new entry. We have plenty of -2 or even -3 entries in our `all_assets.json`.

**Comment by coinyon** [comment]
Already on it
