### ISSUE TITLE
Introduce caching for SQLCipher on Github actions e2e/backend tests

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2152]
## Description

At the moment we fetch and compile SQLCipher on each run. Since the SQLCipher version doesn't change every single day this could potentially reduce the runtime/build time by some time when running e2e tests or backend tests.

### Task

- [ ] Introduce caching of the SQLCipher dependency based on the runner os/sqlcipher version combination

**Comment by LefterisJP** [comment]
Hey @kelsos has this been already addressed by any chance?

**Comment by kelsos** [comment]
No it is still pending

**Comment by LefterisJP** [comment]
All right then please @kelsos schedule it for a milestone as it's one of these that I think we will forget about :)

**Comment by LefterisJP** [comment]
After talking with @kelsos closing this in favor of https://github.com/rotki/rotki/issues/2740
