### ISSUE TITLE
Keep lowecase rotki as consistent name across code and docs

### ISSUE THREAD

**Issue by michael1011** [rotki/rotki#2167]
When installing Rotki via the `.deb` file (thank you for adding that btw :+1:), the name of the entry in the application overview of Gnome does not start with an uppercase character.

![Screenshot from 2021-01-23 14-39-16](https://user-images.githubusercontent.com/8138838/105579855-556c5d80-5d89-11eb-9bed-1780e8c27e56.png)

~I have not tested any other desktop environments.~

**Comment by LefterisJP** [comment]
Hey @michael1011 thanks for the issue! So the thing here is that lowercase is the name we use in many places for the app. Including the appimage binary. But indeed at some places we also use uppercase (R)otki making this incosistent.

We need to decide on one representation and use it consistently.

**Comment by michael1011** [comment]
The first line of the README says `Rotki` with an uppercase R, so I was wondering whether that was intentional.

Feel free to close this issue if you already have another one for making this consistent.

**Comment by LefterisJP** [comment]
We should change the first line of the readme then. Good point :)

We don't really have an issue for keeping it consistent but we can keep this one.

**Comment by LefterisJP** [comment]
So to close this issue someone should just go through the code and change most Rotki to rotki
