### ISSUE TITLE
Fetching watchers Error: Request failed with status code 500

### ISSUE THREAD

**Issue by sardoru** [rotki/rotki#2169]
## Problem Definition

None of the balances seem to load. Error fetching balances. 

Operating system:  MacOS Big Sur Version 11.1
Rotki version: 1.12.2

**Comment by sardoru** [comment]
Also showing this:

Error at querying blockchain balances: The backend query task died unexpectedly: Could not find a suitable TLS CA certificate bundle, invalid path: /var/folders/p7/6h6dq83x0811b4_7shbtv26r0000gn/T/_MEI1oWknT/certifi/cacert.pem

**Comment by LefterisJP** [comment]
Hey @sardoru thanks for the report. This does not give us any information though.


 Can you please run rotki with debug logs on ([see here for how](https://rotki.readthedocs.io/en/latest/contribute.html#run-rotki-in-debug-mode)) and post any exceptions you see here? And maybe even send the log to me in a DM via discord https://discord.gg/aGCxHG7

**Comment by sardoru** [comment]
Seems its working now, I'll close this. Thank you!
