### ISSUE TITLE
Change inquirer.find_price() to support special symbols that are only queried on-chain and are tied to USD value

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#2195]
Feature #2194 introduces `find_price(from_asset, to_asset, ignore_cache)` in Inquirer, but it does not support yet special symbols (e.g. yaLINK). Currently the logic of the special symbols is [tied to USD](https://github.com/rotki/rotki/blob/develop/rotkehlchen/chain/ethereum/defi/price.py#L128).

**Comment by LefterisJP** [comment]
This should be simple enough to achieve.

We would need to move(or copy? -- would need to see uses) all the "special case" detection from `find_usd_price()` to the `find_price()` function.

If the `from_asset` is a special case, then we find the from/to price by first finding the USD price and then going from USD to the `to_asset`

**Comment by yabirgb** [comment]
At the moment we have improved the inquierer to find prices based on special protocols for assets and other special properties of assets
