### ISSUE TITLE
SubstrateManager update type registry during instantiation

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#2196]
Currently SubstrateManager is not [updating the type registry](https://github.com/polkascan/py-scale-codec#using-the-type-registry-updater-in-your-application). We must get up-to-date the codecs of the chains.

At some point they will be [available via the metadata endpoint.](https://github.com/paritytech/substrate/issues/7971) and there won't be any need to update them as per described in this issue.

Why is important?

> It is essential to keep these type registries up to date, there is for example an upcoming change for Kusama where the Address and LookupSource types will be changed (MultiAddress support) and this will break all signed extrinsics if not updated..

**Comment by LefterisJP** [comment]
When is that update going to happen? We need to know to know when to schedule this fix.

**Comment by vnavascues** [comment]
It seems not until March according to the issue comments

**Comment by LefterisJP** [comment]
Still need it soon then. This is a month. Needs to be in one of the next 3 releases, assuming we do 1 tomorrow and one every 2 weeks.

When you say update the type registry it essentially means to update the json? We need to see how these json are stored also then and what happens with pyinstaller and if this happens in runtime then where would the app store them.

**Comment by vnavascues** [comment]
> Still need it soon then. This is a month. Needs to be in one of the next 3 releases, assuming we do 1 tomorrow and one every 2 weeks.
> 
> When you say update the type registry it essentially means to update the json? We need to see how these json are stored also then and what happens with pyinstaller and if this happens in runtime then where would the app store them.

Until the codecs don't come via the metadata endpoint, we need to add [this call](https://github.com/polkascan/py-scale-codec#using-the-type-registry-updater-in-your-application) when the server starts. According to Arjan, it retrieves the latest type registry presets from Github and replaces the local ones on disk. The advantage is that you don't have to rely on the latest update of both Polkascan libraries. Agree with your doubts re pyinstaller and storage.

**Comment by vnavascues** [comment]
[Good news](https://github.com/polkascan/py-substrate-interface#keeping-type-registry-presets-up-to-date)

I've tested the new version of py-substrate-interface (v.0.11.16) and its new argument `use_remote_preset` and it works. Although it has required to amend some exception messages.

Pending to address why now some tests in `test_susbtrate_utils.py` fail. It seems that `is_valid_substrate_address` returns True for a substrate public address (which does not have the ss58 2 format).  `ss58_decode` could be misbehaving.
