### ISSUE TITLE
Publish SHA256 checksums for Windows

### ISSUE THREAD

**Issue by benjaminion** [rotki/rotki#2201]
## Abstract

I would like to use the checksum provided to verify the integrity of my Windows executable download. However, the checksum appears to be SHA512, which is not available as standard on Windows.

## Motivation

Checksums are already provided, which suggests that they have value when they work. Providing a format I can't check, however, has no value.

## Specification

These are the checksums available by default through the right-click menu

![image](https://user-images.githubusercontent.com/20796281/106277414-f5663300-6230-11eb-825d-00a89287589f.png)

The `*` option provides the following checksums:

```
Name: rotki-win32-v1.12.2.exe
Size: 82072533 bytes (78 MiB)
CRC32: 4BF1C6E4
CRC64: 3660086CB3BB76E7
SHA256: 0582A89521A007F0F94E75EC8DC0D0ABF21C0AC24D1B766C7D403C51D98978EA
SHA1: 6967415926130746D75BE3DB8FBD5150B121EB9F
BLAKE2sp: A5A896B978B39B1EAD8C308010B8943AB27DF2AF3AE68F4FCB61C59BC24D89CD
```

I suggest SHA256 as a reasonable choice.

OS version: Windows 10 Pro 1909, build 18363.1316

**Comment by isidorosp** [comment]
I think that menu is not default windows, but installed together the 7-zip application. In windows you can use the `certutils` cmd line program or `Get-FileHash` in Powershell. E.g.:
![image](https://user-images.githubusercontent.com/27592/106278527-22b7de80-623b-11eb-882d-e84ff534e839.png)

**Comment by benjaminion** [comment]
True, thanks for that.

Nonetheless, the default for `Get-Filehash` is SHA256, so the request still stands. It's good to make this really, really easy, and I know I will end up having to google the `Get-Filehash` options syntax every time I update Rotki as-is.

**Comment by LefterisJP** [comment]
Hey @benjaminion hello!

Is it somehow standard to publish sha256 in Windows? For your usecase you seem to want because your setup with 7zip caters to it, but the way we made it is sha512 across the board for all OSes.

And the intended program to do this is Windows is certutils which as @isidorosp shows accomplishes that.

@kelsos would changing to sha256 for one OS be hard/advisable?

**Comment by benjaminion** [comment]
Hey, @LefterisJP!

> Is it somehow standard to publish sha256 in Windows?
I honestly don't know. I am trying not to be too much of an expert on Windows, and generally use it under duress. But that probably reflects the average user. Not only power users ought to be able to verify checksums :-)

The ultimate solution is for the Windows binaries to be properly signed by yourselves. I presume that would avoid the "**Windows protected your PC**  Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk." Pop-up I get when I run a new version of Rotki, with a nice "Don't Run" button at the bottom. But I understand that this is not an easy or cost-effective process.

In the end, choice of checksum is not a huge issue for me, but it's just a little bump that I ran over today.

**Comment by kelsos** [comment]
> I honestly don't know. I am trying not to be too much of an expert on Windows, and generally use it under duress. But that probably reflects the average user. Not only power users ought to be able to verify checksums :-)

7zip that adds the menu is one of the many third-party archive managers. It seems to be quite popular but assuming that this reflects the average user seems a bit of a stretch, at least without any concrete numbers of the percentage of Windows users having 7zip installed.

On the other hand, both the cmd (certutil) and powershell are by default installed in every windows installation. While slightly more technical they don't require the user to install any third-party software on their machine to run a checksum verification. 

Do we have detailed instructions on how to verify the checksum on windows? if not we should.

**Comment by LefterisJP** [comment]
> Do we have detailed instructions on how to verify the checksum on windows? if not we should include them in the documentation.

Yes we do have a super small guide: https://rotki.readthedocs.io/en/latest/installation_guide.html#verifying-integrity

> The ultimate solution is for the Windows binaries to be properly signed by yourselves. 

Indeed. I know exactly what you mean. We will handle this at some point. It's in our roadmap: https://github.com/rotki/rotki/issues/1224

Reasons it has not been done yet is the extra costs and also the work required to figure out a way to include this process safely in the CI. Won't be doing these stuff by hand.

If we see more people asking for sha256 in Windows we may consider it but at the moment it's probably not worth any changes, especially considering our huge backlog and the small team size.

Is it okay with @benjaminion if I close this issue?

**Comment by benjaminion** [comment]
> Is it okay with @benjaminion if I close this issue?

Sure 🙂
