### ISSUE TITLE
Move to backend module information from hardcoded values

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2203]
## Description

Endpoints have been added to provide names for modules along with the ids. 

### Tasks
- [ ] Introduce a simple id to icon mapping with some default fallback
- [ ] Simplify code

**Comment by LefterisJP** [comment]
Damn this issue hurts. Since then a lot more stuff have been added that need to be provided by the backend to the frontend and not be duplicating data between both places. Moving it again.

**Comment by LefterisJP** [comment]
I am closing this. Some mapping have moved. For other specific ones we either move them when we find them or make separate issues for them.
