### ISSUE TITLE
Adex staking APR is no longer calculated at all (shows 0%)

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2214]
## Problem Definition

Adex staking APR is no longer calculated correctly. It always shows a 0% while it should not.

Shows
![2021-01-29_23-43](https://user-images.githubusercontent.com/1658405/106335803-ca5dfc80-628d-11eb-91cb-f830a8311b86.png)

Should have:

![2021-01-29_23-58](https://user-images.githubusercontent.com/1658405/106335842-df3a9000-628d-11eb-966e-917b74200e9f.png)

## Task

Fix it

**Comment by vnavascues** [comment]
@LefterisJP  looking at the current implementation, a 0% happens given the following cases:
A. Fee-rewards API request fails, `[]` is assigned and `_get_tom_pool_incentive()` returns apr ZERO.
B. Fee-rewards API does not fail, but in `_get_tom_pool_incentive()` `now > period_ends_at` (ADX pool).

Option B could happen if the fee-rewards API was returning two ADX channels, the current and the legacy one. The latter had a periodEnd < now. Nowadays the API does not include the legacy channel.

The AdEx refactor I'm working on prevents A (fee-rewards API data is required) and B (discards the legacy channel, as their implementation does).
