### ISSUE TITLE
Add new current price Oracle - Uniswap

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2216]
## Abstract

For ethereum tokens we can query their uniswap price directly from uniswap itself with on-chain calls.

Related: #2217 

## Task

- [ ] Figure out how to calculate a given price from uniswap for a given pair. If the pair does not exist then closest pair should be found and a conversion made.
- [ ] Add a new current price oracle for Uniswap and add it to the given oracles so that the user can customize its priority.

**Comment by yabirgb** [comment]
Interesting readings related to this topic:

- https://uniswap.org/docs/v2/core-concepts/oracles/
- https://uniswap.org/docs/v2/smart-contract-integration/building-an-oracle/

**Comment by LefterisJP** [comment]
This should not be too hard to add

**Comment by LefterisJP** [comment]
This should also be done by #4118
