### ISSUE TITLE
Rotki duplicates manual balances with the "blockchain" location tag upon restart

### ISSUE THREAD

**Issue by jimjimvalkema** [rotki/rotki#2223]
## Problem Definition

After the update of 1.13.0 rotki will duplicate any old and new balances that are manually added with the "Blockchain" location tag after a restart. 
The balances duplicate them self from: accounts & balances / manual balances, to:  accounts & balances / blockchain balances.
These extra balances show up on the dashboard and at accounts & balances / blockchain balances.

## How to reproduce
1. go to manual balances at accounts & balances / manual balances
2. click + (add) choose any name, any coin, any amount and change the location from "External" to "Blockchain" 
3. restart rotki
4. "profit" 😉

## Logs
TBA

### System Description
Average gaming pc with i5. 
Running my local geth node.

Operating system: Linux (ubuntu)
Rotki version: 1.13.0 (.deb)

**Comment by LefterisJP** [comment]
This looks like a frontend issue and is easy to reproduce. @kelsos somehow it seems that the manual balance with location blockchain is also counted in the blockchain accounts & balances section and as such ends up being counted 2 times in the dashboard.

**Comment by LefterisJP** [comment]
It was a backend problem after all.

https://github.com/rotki/rotki/blob/3317409503ec714fcf08335f453157c8008e526e/rotkehlchen/rotkehlchen.py#L762-L763

Here we are taking a reference to totals and later down modify it. The return balance functions should never have returned a reference but a copy. So the linked PR #2233 should fix it.
