### ISSUE TITLE
Allow to run specific OS test

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2229]
## Abstract

OSX tests don't run by default and only run on nightlies. But now the OSX tests fail on nightly: https://github.com/rotki/rotki/runs/1799338362?check_suite_focus=true

So we should have the ability to request a specific OS test in order to test that all works fine.

This came up due to OSX specific failures here: https://github.com/rotki/rotki/runs/1799338362?check_suite_focus=true

## Task

Do it.

**Comment by kelsos** [comment]
The plan for this is to allow custom tags `[osx]`, `[linux]` when one of these tags are detected in commit messages it will only run the specified backend tests but it will skip other tasks. 

To better support for running specific tests we could do a `[osx=rotkehlchen/tests/api/]` for example to run the API tests.

**Comment by LefterisJP** [comment]
Does this issue make sense any more @kelsos? With having OSX run only on nightly?
