### ISSUE TITLE
 Add support for $PERP

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2234]
Please add support for $PERP token

Contract 0xbc396689893d065f41bc2c6ecbee5e0085233447

https://perp.fi/
https://twitter.com/perpprotocol
https://medium.com/@perpetualprotocol
https://www.coingecko.com/en/coins/perpetual-protocol

Thanks a lot

**Comment by adrien-be** [comment]
Note that Perpetual Protocol just past $1 Billion volume only 6 weeks after launch. So it might soon become very demanded by many people, if that can help with prioritizing...

**Comment by LefterisJP** [comment]
Hey @adrien-be no worries we will add both this and you other request. Adding tokens is easy. There is no question of prioritizing. All you need to do is ask and we will add it.

**Comment by adrien-be** [comment]
Good to know :) Still loving the project and just renewed my membership. Its stopped for some mysterious reason
