### ISSUE TITLE
Properly adjust size on bigger screens for dashboard etc

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2239]
## Problem Definition
Also make sure that numbers don't wrap

### Task 
Fix the issue

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/2247 

Funny that even after merging to develop this is not auto closed.

**Comment by kelsos** [comment]
Yes if you merge PRs to a non-default branch and then merge that to the default it won't work. It would only work if the commits had the close message.
