### ISSUE TITLE
Multiple fallback options for historical crypto prices - Add Coingecko

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#224]
## Problem Definition

As can be seen in a recent [tweet](https://twitter.com/LefterisJP/status/1070034686137827328) I made it seems that Cryptocompare will phase out their public API and enforce API key authentication. That presents a problem for apps like rotkehlchen that will have to force their users to get an API key just to get historical price data.

Edit: Vlad from cryptocompare [tweeted](https://twitter.com/vcealicu/status/1070084623286308864) they will still keep the public API around without API key authentication for tens of thousands of requests per month.

This issue aims to find ways to allow more options for rotkehlchen users while also allowing them to input a cryptocompare API key if they so desire.

Related issue for current prices is [here](https://github.com/rotkehlchenio/rotkehlchen/issues/92)

## APIs for historical crypto prices

- [Cryptocompare](https://min-api.cryptocompare.com/pricing): Has public API but will get rate limited and users are encouraged to authenticate via api key. Users would need to go to the website, register, get API key and then input it in Rotkehlchen.
- [Coin gecko](https://www.coingecko.com/api): Has historical prices for many coins and the API is public and open.
- [Coinpapricka](https://coinpaprika.com/api/): Public API. Has historical data.
- [Coinmarketcap](https://pro.coinmarketcap.com/api/v1#operation/getV1CryptocurrencyOhlcvHistorical): Also requires authentication via api key. Users would need to go to the website, register, get API key and then input it in Rotkehlchen.

## Task

- [ ] Refactor the [price historian](https://github.com/rotkehlchenio/rotkehlchen/blob/855a4004b97c8ad6cb49579a9dbc11f33254988d/rotkehlchen/history.py#L184) so that it has multiple querying backends and can choose depending on availability any of the known APIs for historical prices shown in the previous section. For this issue only add coingecko.
~~- [ ] Allow addition of cryptocompare and coinmarketcap api keys per user via the UI.~~ -> Coinmarketcap needs one, if we add it but scoping it out of this issue
~~- [ ] Create two fallback API keys for cryptocompare and coinmarketcap that would be shared by all users to which rotkehlchen would fallback if the public API call fails.~~ -> Not needed. Coinmarketcap is not going to be added as part of this issue.
- [ ] Add tests for all the above.

**Comment by tmlee** [comment]
You might want to consider our public open api at https://www.coingecko.com/api
Happy to answer any questions or concerns

**Comment by LefterisJP** [comment]
@tmlee Thanks a lot for popping in. Definitely will add it as an option then. The most important thing is to not let the app without a way to fetch historical prices so the more options there are the better.

**Comment by vcealicu** [comment]
As I said on Twitter, we won't change it but it makes sense to have a few fallback options. Redundancy on API feeds makes sense.

**Comment by LefterisJP** [comment]
> As I said on Twitter, we won't change it massively and there will always be free IP limits as well but it makes sense to have a few fallback options. Redundancy on API feeds makes sense.

Thank you @vcealicu . I noted that in the issue and really appreciate it. I expect to have a refactored Price Historian with multiple API backends and cryptocompare being the default first choice.

**Comment by LefterisJP** [comment]
This issue is changed to be specifically for coingecko and to make it as a fallback/secondary option for crypto prices.

Coinmarketcap is scoped out. So is coin paprika.

**Comment by LefterisJP** [comment]
Some extra info for when we integrate with coingecko.

Our friends at mycrypto have a list of all EVM tokens/chains and their mapping to coingecko here: https://mycryptoapi.com/api/v1/assets.json

We can use this to easily create a mapping between all eth tokens to coin gecko ids when querying their API.

We can also use coingecko, not only for pricing but also to retrieve icons for each asset.
