### ISSUE TITLE
Rounding errors in prices

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#2258]
## Problem Definition

The price of assets in terms of itself are not exactly 1. See images.

![DeepinScreenshot_select-area_20210202112220](https://user-images.githubusercontent.com/8545447/106586639-01136b80-6549-11eb-85d3-8cf044ba6316.png)
![DeepinScreenshot_select-area_20210202112206](https://user-images.githubusercontent.com/8545447/106586644-01ac0200-6549-11eb-88fb-c432259cf2bf.png)
![DeepinScreenshot_select-area_20210202112132](https://user-images.githubusercontent.com/8545447/106586646-02449880-6549-11eb-9ef6-06cab4cf427d.png)
![DeepinScreenshot_select-area_20210202112033](https://user-images.githubusercontent.com/8545447/106586648-02449880-6549-11eb-819d-bd7b413e6c19.png)
![DeepinScreenshot_select-area_20210202111658](https://user-images.githubusercontent.com/8545447/106586649-02449880-6549-11eb-9d05-2ed4b2cf6a2c.png)

### Steps to reproduce

1. Add an asset (for example ETH, BTC, EUR, USD, etc.) either as a manual balance or by using an address.
2. Set the "Profit Currency" to that asset.
3. Refresh prices.

Expected result: Price of that asset is exactly 1.

Actual result: Rounding error.

### System Description

Operating system: NAME="Ubuntu" VERSION="20.04.1 LTS (Focal Fossa)"
Rotki version: 1.13.0

**Comment by LefterisJP** [comment]
Oh good find. Thanks a lot @hjorthjort. We will handle it

**Comment by LefterisJP** [comment]
Should be fixed y #2266
