### ISSUE TITLE
Add a hint in the rate of external trades

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2265]
## Problem Definition

Add a hint in the rate? To explain what it is if buy is selected and also what it is if sell is selected?

So for example:

    Buy ETH with BTC for 0.05 BTC per ETH
    Sell 10 ETH for EUR for 1000 EUR per ETH.

Not sure where this could be put to look nice to the user but I think it would be a tremendous value add.

### Task
- [ ] Add hint

**Comment by kelsos** [comment]
It is really hard to find a place where this would look nice and not out fo place

**Comment by LefterisJP** [comment]
@kelsos don't we already have such a thing with the way the tables are written?

**Comment by kelsos** [comment]
> @kelsos don't we already have such a thing with the way the tables are written?

Yes, we have it on the tables, but if I recall correctly this comment you made was about the form itself when adding new external trades and not about the table itself. I did try a couple of times but I couldn't get it to look nice, to be honest. 

Maybe it would make sense to either close it or re-evaluate it in the future.

**Comment by LefterisJP** [comment]
Ah yes this is for the form. Would be cool to have it there. Is it that hard to do?

**Comment by kelsos** [comment]
If we want it to look nice yes, I did a few tries but it didn't look good
