### ISSUE TITLE
Add support for $TORN token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2268]
Please add support for $TORN token

Contract 0x77777feddddffc19ff86db637967013e6c6a116c

https://tornado.cash/
https://twitter.com/TornadoCash
https://medium.com/@tornado.cash
https://discord.com/invite/TFDrM8K42j
https://t.me/TornadoCashOfficial
https://torn.community/
https://github.com/tornadocash

**Comment by LefterisJP** [comment]
Hey @adrien-be it should already be supported: https://github.com/rotki/rotki/blob/09c58699f11d356b65b48d5c6cfd4fca4720858c/rotkehlchen/data/all_assets.json#L11803

**Comment by adrien-be** [comment]
You are right :)

**Comment by LefterisJP** [comment]
Pheww ... thought there may have been some funny bug where TORN was not showing. Closing then!
