### ISSUE TITLE
Generic CSV import template + Optional platform specific formats

### ISSUE THREAD

**Issue by bitofit** [rotki/rotki#2270]
## Abstract
First time users of Rotki are coming from a variety of tax reporting/trading tools which (mostly) export to CSV and new platforms are popping up every day.  

To support the widest range of new users as possible, Rotki should establish its own CSV import format so users can manually format the data themselves which would allow importing _from any platform_.  Once completed, platform specific import features can be created for the top platforms.

## Motivation
**Problem** - Currently, users with abundant trade history on other platforms (bitcoin.tax for example) can't switch to Rotki unless their platform is supported for data import.

**Solution** - Offer a generic CSV import template so users can format the data themselves.  This enables importing from _any_ platform.

## Specification
On the Import Data screen, you would have 2 options:
1. Select a supported platform to import from
2. If your platform is not supported (yet) download _rotki_trade_history_template.csv_ which has pre-defined column headers so you can format the data yourself and import

**Comment by LefterisJP** [comment]
> If your platform is not supported (yet) download rotki_trade_history_template.csv which has pre-defined column headers so you can format the data yourself and import

I would say for this to just show the template in the UI with a good explanation of each column. No need to download an one line csv file. What do you think?

**Comment by bitofit** [comment]
Sure that'd be fine

**Comment by sampsojp** [comment]
I agree, this would be very nice to have. Please make it happen.

**Comment by a7e8** [comment]
I also agree this would be nice to have. Would help import staking rewards without Rotki having to support those chains directly.

**Comment by prophecynine** [comment]
This feature alone dictates whether or not rotki is useable. It's the difference between a premium account or just using some other service.

**Comment by LefterisJP** [comment]
> This feature alone dictates whether or not rotki is useable. It's the difference between a premium account or just using some other service.

Rotki has many many different types of users. And for each user a different feature is what makes it a killer app. Thanks for +1 your feedback on this issue. Noted.

**Comment by prophecynine** [comment]
I guess I should say 'for me' this is the key feature. Although I suspect there's a large group of users that would benefit from this.

**Comment by bplunkert** [comment]
I am surprised this feature does not already exist. It's clearly a blocker for myself and probably most other users (since exchange support is quite limited). How are users currently importing transactions from unsupported exchanges?

**Comment by LefterisJP** [comment]
> I am surprised this feature does not already exist. It's clearly a blocker for myself and probably most other users (since exchange support is quite limited).
> 
> How are users currently importing transactions from unsupported exchanges? Is there a way? If not, I think this should be prioritized over supporting any particular exchange. Then some more of us might have time freed up and be more able to contribute code to support new exchanges.

It's true this should be prioritized more than any single exchange at the moment. We are busy with some big arhchitectural changes in regards to on-chain and EVM transactions.

But we should pick this up afterwards too.

Naturally if any of you are a dev and want to help us here PRs are not just welcome but super super appreciated.

We have a discord server where we are and can sync at (have DMs open as there is a captcha challenge): https://discord.com/invite/aGCxHG7
