### ISSUE TITLE
Build error on arm64 (Raspberry Pi 400)

### ISSUE THREAD

**Issue by tgerring** [rotki/rotki#2280]
## Problem Definition

Attempting to build Rotki from scratch (due to lack of aarch64 binaries) and running into a few build issues. I have made it as far as the use of `deasync` when running `npm ci` by following the following modifications to the existing documentation:

1. Preinstall `build-essential` or similar compiler toolchain
1. Preinstall `libssl-dev` so `LDFLAGS="-lcrypto"` finds the correct library
1. Needed to build off sqlcipher tagged `v4.3.0` to include updates to their build scripts to correctly detect Pi
1. Need to `npm install -g node-gyp` before build process reaches deasync package, as an aarch64 binary is not available

## Logs

```
4024 info run deasync@0.1.20 install { code: 1, signal: null }
4025 info run electron-chromedriver@11.0.0 install { code: 0, signal: null }
4026 timing build:run:install:node_modules/electron-chromedriver Completed in 13046ms
4027 timing reify:rollback:createSparse Completed in 17679ms
4028 timing reify:rollback:retireShallow Completed in 0ms
4029 timing command:ci Completed in 127681ms
4030 verbose stack Error: command failed
4030 verbose stack     at ChildProcess.<anonymous> (/snap/node/3665/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
4030 verbose stack     at ChildProcess.emit (node:events:378:20)
4030 verbose stack     at maybeClose (node:internal/child_process:1067:16)
4030 verbose stack     at Socket.<anonymous> (node:internal/child_process:453:11)
4030 verbose stack     at Socket.emit (node:events:378:20)
4030 verbose stack     at Pipe.<anonymous> (node:net:665:12)
4031 verbose pkgid deasync@0.1.20
4032 verbose cwd /home/tgerring/dev/rotki/frontend/app
4033 verbose Linux 5.8.0-1013-raspi
4034 verbose argv "/snap/node/3665/bin/node" "/snap/node/3665/bin/npm" "ci"
4035 verbose node v15.8.0
4036 verbose npm  v7.5.1
4037 error code 1
4038 error path /home/tgerring/dev/rotki/frontend/app/node_modules/deasync
4039 error command failed
4040 error command sh -c node ./build.js
4041 verbose exit 1
```

### System Description

Operating system: Raspberry Pi 400 / Ubuntu ARM64
Rotki version: develop branch

**Comment by kelsos** [comment]
Hey @tgerring is it running on raspbian? I have a raspberry with running arch I could try to backup and install it to give it a try. 

Also I need to check if everything is OK with these versions of node and npm. Our builds are with the 12.x lts and npm 6.

I am not sure if the docker image would help also.

**Comment by tgerring** [comment]
Thanks @kelsos it would be interesting to see what your Pi comes up with.

I decided to try and build deasync manually to see where the problem might be, and it appears there's an issues around the `node-addon-api` package. I first tried to install this globally, but deasync woudl not build. When I installed it with npm locally, build went as expected.

Switching back to my rotki/frontend/app directory, I manually ran `npm i node-addon-api` and *BAM* I ended up with an error log almost identical to the one posted above.

So now, I am wondering why installation of `node-addon-api` succeeded in the deasync directory, but not in the rotki one?

**Comment by kelsos** [comment]
@tgerring can you try removing the vue-cli plugin for cypress and give it a try again

https://github.com/rotki/rotki/blob/7185b79a23391f54163a62171a7f9ace42a6cf2d/frontend/app/package.json#L68

It seems that cypress doesn't have pre-compiled binaries for aarch64 and it will cause issues, even if you pass through deasync it will fail to download cypress.

**Comment by tgerring** [comment]
Interesting that is where you ended up, as I had tracked down the usage of deasync as part of vuejs/vue-jest v3.0.7 (it is removed in versions 4.x and 5.x)

I tried to remove the `cli-plugin-e2e-cyprus` line above from package.json and then `npm i` but ended up with same error :(

It's a bit surprising how much "open source" is downloaded binaries

**Comment by kelsos** [comment]
@tgerring If I find some time I will use the aarch64 qemu to emulate a rpi3b (I think I can't emulate 4) and install ubuntu to give it a try.

**Comment by tgerring** [comment]
Thanks @kelsos. I don't think the issue is with Arch vs Ubuntu so much as arm64 support in dependencies at this point. My comment about binaries was directed at the likes of these dependencies that have no "compile from source" fallback.

After reading a bit more about how `devDependencies` works, I decided to try `npm install --production` with the following output:

```
ubuntu@ubuntu:~/dev/rotki/frontend/app$ npm install --production

> rotki@1.13.2 postinstall
> electron-builder install-app-deps

sh: 1: electron-builder: not found
npm ERR! code 127
npm ERR! path /home/ubuntu/dev/rotki/frontend/app
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-02-10T16_01_33_214Z-debug.log
```

`tail`ing the log shows me this:
```
3508 verbose stack Error: command failed
3508 verbose stack     at ChildProcess.<anonymous> (/snap/node/3665/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3508 verbose stack     at ChildProcess.emit (node:events:378:20)
3508 verbose stack     at maybeClose (node:internal/child_process:1067:16)
3508 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3509 verbose pkgid rotki@1.13.2
3510 verbose cwd /home/ubuntu/dev/rotki/frontend/app
3511 verbose Linux 5.8.0-1006-raspi
3512 verbose argv "/snap/node/3665/bin/node" "/snap/node/3665/bin/npm" "install" "--production"
3513 verbose node v15.8.0
3514 verbose npm  v7.5.1
3515 error code 127
3516 error path /home/ubuntu/dev/rotki/frontend/app
3517 error command failed
3518 error command sh -c electron-builder install-app-deps
3519 verbose exit 127
```

I was going to try building electron-builder from source locally, but my machine locked up and after about 4 hours of it not responding, I pulled the plug :( I will give it another go and see if I can't get it to recognize the command and get one step further.

**Comment by kelsos** [comment]
At least on armv7 on rpi2 I manage to get the npm ci complete successfully by installing the dev packages + removing cypress, so maybe some of these dependencies have armv7 32bit support but not aarch64? I will need to setup the VM to investigate more.

I even managed to start a build but I have to limit the worker's ram because rpi2 has only 1gb and the worker by default gets 2gb

**Comment by tgerring** [comment]
Installing electron-builder globally  (`sudo npm install -g electron-builder`) fixed the issues with running `npm install --production`.

I then ran `npm install`, but I ended up with the `node-gyp` error. I tried to delete cli-plugin-e2e-cypress and re-run, but the result is the same:

```
553 verbose stack Error: command failed
3553 verbose stack     at ChildProcess.<anonymous> (/snap/node/3665/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3553 verbose stack     at ChildProcess.emit (node:events:378:20)
3553 verbose stack     at maybeClose (node:internal/child_process:1067:16)
3553 verbose stack     at Socket.<anonymous> (node:internal/child_process:453:11)
3553 verbose stack     at Socket.emit (node:events:378:20)
3553 verbose stack     at Pipe.<anonymous> (node:net:665:12)
3554 verbose pkgid deasync@0.1.20
3555 verbose cwd /home/ubuntu/dev/rotki/frontend/app
3556 verbose Linux 5.8.0-1015-raspi
3557 verbose argv "/snap/node/3665/bin/node" "/snap/node/3665/bin/npm" "install"
3558 verbose node v15.8.0
3559 verbose npm  v7.5.1
3560 error code 1
3561 error path /home/ubuntu/dev/rotki/frontend/app/node_modules/deasync
3562 error command failed
3563 error command sh -c node-gyp rebuild
3564 verbose exit 1
```

**Comment by m-roberts** [comment]
Running `docker buildx build --platform linux/arm/v7 .` also causes this `deasync` install error.

Would LOVE to run this on ARM, but don't really know how to replicate the steps described above - what needs to be done to install the dev packages + remove cypress?

**Comment by kelsos** [comment]
hey @m-roberts I just removed cypress from the `package.json` file to test. What I would like to do would be to actually provide prebuild images for rotki for armv7 and aarch64 architectures so that there is not need for our users to build from scratch.

**Comment by step21** [comment]
Based on my experience building packages for conda, I would suggest to only focus on arm64. Apart earlier ones being memory constrained, especially if you need compiled c packages for node packages or similar you will be in a world of hurt. My best guess would be that it is likely a node/npm version problem.

**Comment by m-roberts** [comment]
> hey @m-roberts I just removed cypress from the `package.json` file to test. What I would like to do would be to actually provide prebuild images for rotki for armv7 and aarch64 architectures so that there is not need for our users to build from scratch.

Would it make sense to create a new Issue to track this?

**Comment by schklom** [comment]
> 
> 
> hey @m-roberts I just removed cypress from the `package.json` file to test. What I would like to do would be to actually provide prebuild images for rotki for armv7 and aarch64 architectures so that there is not need for our users to build from scratch.

If it helps, I have a setup to automatically update and publish arm images for some repos I like that don't offer them, using GitHub Actions.
Look at the Rotki file in my [repo](https://github.com/schklom/Mirror-workflows/tree/main/.github/workflows). (I tried to run your Dockerfile with arm there, and it failed).

### Quick explanation about the file's jobs, in case the file isn't clear enough :)
The `schedule` is commented out, because the build doesn't work so there is no point.
`get_commits` job retrieves latest commit and records it for next job.
`repo_sync` job copy-pastes the original repo, if its latest commit (from job before) is different from the commit id in a file. If it updates, the file with the commit id is updated.
`build_push` job is quite explicit: it builds using QEMU (you can choose platforms via the `Set up QEMU` part), then pushes to DockerHub.

**Comment by kelsos** [comment]
Yes, @schklom there are a few problems in the Dockerfile setup, (it works only on x64_64 but some setup is missing for arm) that I am trying to figure out when building on arm. I will check your setup.

Ideally, we would like to solve the issues and provide official images for Linux on at least armv7 and arm64.

**Comment by schklom** [comment]
@kelsos My setup can only help with automating the build+publish process, and can build on more than arm7 and arm64.
Unfortunately, I have no idea how to solve your Dockerfile situation.

The project seems amazing, and since you're trying to publish on more platforms, I thought it would be a waste to keep this setup to myself.
I hope you manage to solve the Dockerfile issue, I will use it when you do :)
