### ISSUE TITLE
TNT Tierion shows wrong value

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2283]
TNT Tierion calculates to a value of $4.12 per token  instead of $0.00623

Operating system: Window 10
Rotki version: 1.13.0

**Comment by LefterisJP** [comment]
The mapping is wrong on our side. Will fix. Thanks for reporting!

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/2284
