### ISSUE TITLE
Improve the asset details page

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2289]
## Problem Definition

The issue here is for brainstorming and collecting ideas for ways to improve the page.

In v1.14.0 a new basic asset details page will be added in the application. We discussed with @LefterisJP on how to improve this page.

- Include coingecko/cryptocompare information about the asset (#4457)
- Include some kind of price history for the asset. For example use chart data. Example: https://api.coingecko.com/api/v3/coins/aave/market_chart?vs_currency=eur&days=7&interval=daily (#4454)
- Provide a more details breakdown of how the asset is distributed in an specific account. E.g. the account has a total of 100DAI that is 40 on the chain, 20 in a vault, 20 in compound and 20 in Aave. (#4455)
- Serve the data from a backend api endpoint

**Comment by CruiseMan** [comment]
Overlapping

![Screen Shot 2021-06-26 at 11 31 48 PM](https://user-images.githubusercontent.com/15807643/123535257-84d81b00-d6d7-11eb-8a8e-506aa6b9e41f.jpg)

**Comment by LefterisJP** [comment]
Hey @CruiseMan I am quite sure this is because you have edited the number of decimals points for fiat. It should normally be only 2 in which case this should not happen.

I will wait for more input from @kelsos though.

**Comment by kelsos** [comment]
Yes the overallaping can happen for either really big numbers or a lot of decimal characters, I will have to look at it to see if there is a way around, maybe decrease the text size a bit the more characters you have down to a hard limit..

Can you open an issue @CruiseMan since this is not the proper issue for it.

**Comment by LefterisJP** [comment]
@kelsos this issue no longer sounds actionable. Or do I misunderstand?

 Do you have the result of brainstorming in other issues? If yes, then I guess we can close this?

**Comment by kelsos** [comment]
No there are no issues created we can create issues based on the points above and close this.
