### ISSUE TITLE
Bitstramp trades are not read correctly

### ISSUE THREAD

**Issue by baltcoinh** [rotki/rotki#2295]
## Problem Definition

Operations involving btc trades in Bitstamp are incorrectly valued, giving values some orders of magnitude above the real ones.

## Logs

I will send a detailed log to Lefteris via Discord DM for confidentially reasons.

### System Description

Operating system: Windows 10 19041.746
Rotki version: 1.13.0

**Comment by LefterisJP** [comment]
I got logs from the user and I think I can figure out what is wrong. It's again, just like with the deposit/withdrawals an error in the way we deserialize the trades.

**Comment by LefterisJP** [comment]
Should be fixed by #2313
