### ISSUE TITLE
Filter statistics based on exchange, on-chain, etc...

### ISSUE THREAD

**Issue by GregTheGreek** [rotki/rotki#2303]
## Abstract

The statistics page is great for seeing overall assets, but it would be nice to filter between exchanges and on-chain assets.

## Motivation

Knowing P/L between exchanges and on-chain accounts would be extremely useful in the event that a user may be holding the same token on different mediums. 

## Specification

n/a

**Comment by LefterisJP** [comment]
Hey @GregTheGreek thanks for taking the time to write an issue. Let me see if I get it right.

You can see a graph of netvalue per location in the statistics. Is that not sufficient? So what you are asking is to take the per asset net value graph and further split it into per location graphs?

**Comment by GregTheGreek** [comment]
Right. I'm curious to see if a purchase on coinbase of eth was profitable vs that on chain

**Comment by LefterisJP** [comment]
Hmm but this will not be accomplished by filtering the graph like that. I mean ETH is fungible. You may have moved that ETH around at any point and we won't/can't know.

**Comment by GregTheGreek** [comment]
hmm i see

**Comment by GregTheGreek** [comment]
closing since itslogistically a nightmare
