### ISSUE TITLE
PieDAO Balanced Crypto Pie shows wrong amount in Dashboard

### ISSUE THREAD

**Issue by TripleSpeeder** [rotki/rotki#2314]
## Problem Definition

I have some PieDAO Balanced Crypto Pie (https://www.piedao.org/#/pie/0xe4f726adc8e89c6a6017f01eada77865db22da14) on one of my accounts. The amount and fiat value of BCP is displayed correctly in the DEFI overview page. But on the Dashboard the amount and resulting fiat value is doubled.

BCP contract on etherscan:
https://etherscan.io/token/0xe4f726adc8e89c6a6017f01eada77865db22da14#balances 

### System Description
Operating system: Arch Linux
Rotki version: 1.13.1

**Comment by TripleSpeeder** [comment]
Same problem exists for the DEFI++ index (https://www.piedao.org/#/pie/0x8d1ce361eb68e9e05573443c407d4a3bed23b033)

**Comment by LefterisJP** [comment]
Fixed by ab20816 and confirmed by the user
