### ISSUE TITLE
add stETH (Lido Staked Ether)

### ISSUE THREAD

**Issue by jimjimvalkema** [rotki/rotki#2315]
## Abstract
Lido has a staking pool that allows you to trade your stacking position as a erc20. This token is currently not tracked on rotki.

## Motivation
To keep track of users staking positions on lido.

## Specification
The stETH token is also traded on defi. This means that stETH can be worth less then 1 ETH since withdrawals aren't enabled but deposits are.
Some users might prefer the stETH price on defi (me 😊) while others would like to represent it as plain ETH. 
I anticipate that most prefer the stETH price so adding a option to switch might be niche (but cool).

details stETH: https://blog.lido.fi/steth-the-mechanics-of-steth/
coingecko: https://www.coingecko.com/en/coins/lido-staked-ether

**Comment by LefterisJP** [comment]
jijim asks, jimjim gets

**Comment by jimjimvalkema** [comment]
that was fast haha. you guys are awesome!
