### ISSUE TITLE
Support Fulcrum iDai etc. tokens

### ISSUE THREAD

**Issue by TripleSpeeder** [rotki/rotki#2317]
At https://app.fulcrum.trade/lend you can lend various tokens, resulting in owning "i"-tokens. 

Would love to see at least the popular ones supported in Rotki:
- iDAI (https://etherscan.io/token/0x6b093998d36f2c7f0cc359441fbb24cc629d5ff0)
- iUSDC (https://etherscan.io/token/0x32e4c68b3a4a813b710595aeba7f6b7604ab9c15)
- iUSDT (https://etherscan.io/address/0x7e9997a38a439b2be7ed9c9c4628391d3e055d48)

**Comment by LefterisJP** [comment]
Hey @TripleSpeeder. Thanks for the issue.

The problem with those is the price. Are their prices supposed to be 1-1 to their non i equivalents? If so then this is doable.

Otherwise we would need some sort of price oracle and I don't see them in coingecko or cryptocompare.

**Comment by TripleSpeeder** [comment]
Unfortunately fulcrum works with an increasing token price. For each lender the contract records the current tokenprice at lending/minting time. When lender wants to swap back to the underlying asset, the contract calculates the returned amount based on the price delta from minting time to "now".

**Comment by LefterisJP** [comment]
If you know of either an API that offers it or an exact guide on how to calculate the price of an address we can still try it.

**Comment by TripleSpeeder** [comment]
It looks like this is rather straightforward. All iToken contracts have one method `assetBalanceOf` which returns the current balance of the underlying tokens. So if i lend 100 DAI and made 10% gain, the method `assetBalanceOf` will return 110, indicating I made 10 DAI profit and can withdraw/unlend up to 110 DAI.

Here is the documentation: https://docs.bzx.network/fulcrum-integration/lending#assetbalanceof-address

**Comment by RomanHiden** [comment]
> If you know of either an API that offers it or an exact guide on how to calculate the price of an address we can still try it.
I am one of the engineers working for bzx protocol. each iToken has a function `iToken.tokenPrice()` that will return price compared to underlying. initially its 1:1 but because iTokens are interest bearing this price is growing constantly

**Comment by LefterisJP** [comment]
I am closing this for now as it makes no sense to devote resources as the project seems dead after having had at least 3 different hacks.
