### ISSUE TITLE
Rotki failed to start on Linux Mint 18.3

### ISSUE THREAD

**Issue by thosvarley** [rotki/rotki#2328]
## Problem Definition

I downloaded the .deb installer for rotki, which installed fine, but when I attempted to open it, I got the following error message:

> [543] Error loading Python lib '/tmp/_MEIAp8ZgS/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIAp8ZgS/libpython3.7m.so.1.0)

### System Description

Operating system: Linux Mint 18.3 'Sylvia'
Rotki version: v1.13.2

**Comment by LefterisJP** [comment]
Hey @thosvarley thanks a lot for your issue. Can you try the appimage of the same version and tell us if it works or not. This would help pin down the issue more.

**Comment by thosvarley** [comment]
The AppImage returned the same error:

>[5282] Error loading Python lib '/tmp/_MEIhHkXtB/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIhHkXtB/libpython3.7m.so.1.0)

**Comment by LefterisJP** [comment]
All right so then this must be some kind of problem with that particular Linux Mint's glibc as we have this confirmed running properly in Ubuntu, Debian and Archlinux. 

@kelsos any idea what can be done here to investigate?

The only thing I can imagine is that the system's glibc is older than the glibc of the Ubuntu image we use to generate our binaries (Ubuntu 18.04). And this indeed seems to be the case (https://www.linuxmint.com/rel_sylvia_cinnamon.php) as Linux Mint 18.3 is based on Ubuntu 16.04.

The most obvious solution for you @thosvarley would be to (1) upgrade your distro to a more recent version. Then this problem should go away. It's based on a very old version of Ubuntu. Or you can (2) build and run by source. It's super easy in Linux. Guide is here: https://rotki.readthedocs.io/en/latest/installation_guide.html#id8

@kelsos is there any way to make our appimages/deb binaries to play well with older glibc versions?

**Comment by thosvarley** [comment]
Thanks, this is the kick in the pants I needed to get around to updating to the newest version of Mint - I will let you know how things look after the update.

**Comment by kelsos** [comment]
@LefterisJP I am not sure what we can do in this case. ubuntu 16.04 on which mint 18.3 is based is entering eol by April 30, 2021
and this seems to be the case for 18.3. that reminds me though that we should pin the CI at least for builds to ubuntu 18.04 just to be safe. According to the warnings, the ubuntu-latest tag will move to the newest 20.04 lts.

**Comment by LefterisJP** [comment]
Since there has been no response in the issue, I will consider it as solved by upgrading. If that is not the case let us know by commenting here.
