### ISSUE TITLE
Implement a more robust deserialize_ethereum_address

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#2334]
The current implementation of `deserialize_ethereum_address` does not check the input string is a valid Ethereum address.
```python
def deserialize_ethereum_address(symbol: str) -> ChecksumEthAddress:
    return ChecksumEthAddress(HexAddress(HexStr(symbol)))
```

Ideally it should call `to_checksum_address` (from eth_utils) and raise a DeserializationError if the input string can't be checksum.

Evaluate the implications of a change in the function logic (i.e. which callers don't handle DeserializationError) and find a way to make it work.

The current logic of `deserialize_ethereum_address` is still useful for quick annotating a string as a `ChecksumEthAddress` (especially in the test suite), so try to keep it somewhere.

**Comment by LefterisJP** [comment]
This is no longer valid. We have two such methods.

1. `deserialize_ethereum_address()` does indeed deserialize and calls `to_checksum_address()` which is a bit heavier
2. `string_to_ethereum_address` which is just typecasting
