### ISSUE TITLE
Investigate why rotki shows no error message when trying to create an existing account

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2347]
## Problem Definition

I tried to create an existing account, and the frontend just took me back to the login screen without any error.

###
- [ ]  Investigate the reason behind this.

**Comment by LefterisJP** [comment]
Hey @kelsos is this still relevant?

I think not. At least in 1.18.0 I don't see this problem.

![2021-06-22_12-14](https://user-images.githubusercontent.com/1658405/122907472-78f4fd80-d353-11eb-86dc-0d928461cdc3.png)

**Comment by kelsos** [comment]
No, it is not relevant anymore. I probably forgot to close the issue when I fixed it.
