### ISSUE TITLE
Untracking option of auto-imported asset from the portfolio.

### ISSUE THREAD

**Issue by ebarakos** [rotki/rotki#2351]
## Abstract

Option for removing tracking of auto-imported coins/tokens.

## Motivation

Sometimes, due to lack of proper market data, some prices might not be accurate. This happens especially in old/deprecated/dead tokens with tiny market information. One example is SPX Sp8de token, reporting a huge price while the token is actually dead/dust. In this case, it would be good if the user can select to untrack the specific asset.

**Comment by LefterisJP** [comment]
Hello ebarakos.

> t would be good if the user can select to untrack the specific asset.

you can add it to the ignored assets from your settings. Does this not work?

> One example is SPX Sp8de token

If it's dead the price should be zero. If we get a wrong price for a token, dead or not we should investigate. Let me have a look about that.

We will also add the option to enter custom prices for assets at some point soon which is related.

**Comment by ebarakos** [comment]
Ah, I am sorry, I have missed this setting. That's exactly what I was looking for. Maybe then just move this option somewhere else? In order to be more accessible through the dashboard, e.g. while clicking on the asset. But anyways, thanks for resolving this!

**Comment by kelsos** [comment]
@LefterisJP after the next release we could add the ignoring part as a shortcut to the asset details page.
