### ISSUE TITLE
Import Buy Crypto History Binance

### ISSUE THREAD

**Issue by ShelleyMa** [rotki/rotki#2362]
Purchases via Visa/Mastercard do not appear in transaction history.

It would be useful for tax purposes to have this information imported for profit/loss reports, or to be able to manually add such transactions, as this is likely how a lot of users make their initial purchase of USDT, etc.

**Comment by schamama** [comment]
_Bumping this issue listed for version v1.17.0._

Indeed, transactions listed under Binance "Buy Crypto History" menu (https://www.binance.com/en/my/wallet/exchange/buysell-history) containg the sub-menus "Buy, Sell, Convert, Binance Access" do not appear to be imported into rotki. At least, none of my "conversions" get imported into rotki. As a consequence, the profit/loss report contains plenty comments of the type "Incomplete cost basis information for spend."

**Comment by LefterisJP** [comment]
you can always add them as manual trades until we can manually import them. It would help if one of you can provide us with an api key from Binance that actually contains data for this type of trade (via a DM in discord: https://discord.gg/aGCxHG7) so we can test

**Comment by schamama** [comment]
Sure, I dropped you a DM via discord.

**Comment by yabirgb** [comment]
Seems that binance doesn't provide this information at the moment as reported here https://dev.binance.vision/t/deposit-history-credit-card-purchases/529 

They have plans to include this but don't provide a ETA https://dev.binance.vision/t/deposit-history-credit-card-purchases/529/10

I'll keep this in the radar and as soon as this is available I'll try to make an implementation for it. Is annoying for other people too

**Comment by schamama** [comment]
Thank you for looking into it and for the quick update here.

Yes, let up hope Binance comes up with a solution to that soon.

**Comment by sbellem** [comment]
Would it make sense to consider file imports in the meantime? It's possible to get an excel file of the purchases made, under the "Orders -> Buy Crypto History" section.

**Comment by LefterisJP** [comment]
Yes this could work. We have an issue for a generic import format here: https://github.com/rotki/rotki/issues/2270

**Comment by sbellem** [comment]
@LefterisJP @yabirgb Should the imported data be reflected in the `Dashboard` and `Accounts & Balances` pages? From looking at the behavior of blockfi, nexo and others, it looks like not, but I don't understand why that is so. Thanks for the help!

**Comment by LefterisJP** [comment]
no this is just historic data. They should appear in the trades I guess since they are buys/sells.

As per the docs [here](https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-historical-events): 

> Currently rotki tracks your balance by querying the different supported protocols, exchanges and blockchains. If you manually add information about a trade your balances will not be updated since trades are not consulted when updating the accounts’ balances. If you want to manually update your balance for an asset please refer to the manual balances section.
