### ISSUE TITLE
Add test that checks all_assets.json for all common keys

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2363]
## Abstract

We need to add a few more tests about the all_assets.json file. At least one that tests that the common keys are available in all assets. They can be missing and we will not find it out unless they are attempted to be used.

## Task

- We have a huge list of all of our supported assets in [this](https://github.com/rotki/rotki/blob/4f5292e0934d7eb375bdc42bb70754f6b44ecb1d/rotkehlchen/data/all_assets.json) file.
- Alll asset entries have a set of keys/attributes. This test is to go through each one of these entries just like [this](https://github.com/rotki/rotki/blob/4f5292e0934d7eb375bdc42bb70754f6b44ecb1d/rotkehlchen/tests/unit/test_assets.py#L139-L144) test does. The test should also be added in that same file.
- And for each entry check that the existing symbols are one of [these](https://github.com/rotki/rotki/blob/4f5292e0934d7eb375bdc42bb70754f6b44ecb1d/rotkehlchen/assets/resolver.py#L206-L221). More specifically check that:
    - All entries have the following keys:
        - symbol -> and it's a string
        - name -> and it's a string
        - type -> and it's a string
        - started -> and its an integer
    - Some entries optionally have:
        - active -> and it's boolean 
        - ended -> and it's an integer
        - forked -> and it's a string
        - swapped_for -> and it's a string
        - cryptocompare -> and it's a string
        - coingecko -> and it's astring
    - If type is ethereum_token so (AssetType.ETH_TOKEN or AssetType.ETH_TOKEN_AND_MORE):
        -  ethereum_address -> and it's a string
        - ethereum_token_decimals -> and it's an integer
  

If any of the above is not true fail the test with an informative error of what went wrong.

**Comment by jamesmccannon02** [comment]
Hi I’m interested in this, never developed on this project and new to open source but could you give me a little more info on what’s required and what assets you are aiming to be testing. Thanks

**Comment by LefterisJP** [comment]
Hello @jamesmccannon02, thanks for your interest. It's a pretty simple issue. In short:

- We have a huge list of all of our supported assets in [this](https://github.com/rotki/rotki/blob/4f5292e0934d7eb375bdc42bb70754f6b44ecb1d/rotkehlchen/data/all_assets.json) file.
- Alll asset entries have a set of keys/attributes. This test is to go through each one of these entries just like [this](https://github.com/rotki/rotki/blob/4f5292e0934d7eb375bdc42bb70754f6b44ecb1d/rotkehlchen/tests/unit/test_assets.py#L139-L144) test does. The test should also be added in that same file.
- And for each entry check that the existing symbols are one of [these](https://github.com/rotki/rotki/blob/4f5292e0934d7eb375bdc42bb70754f6b44ecb1d/rotkehlchen/assets/resolver.py#L206-L221). More specifically check that:
    - All entries have the following keys:
        - symbol -> and it's a string
        - name -> and it's a string
        - type -> and it's a string
        - started -> and its an integer
    - Some entries optionally have:
        - active -> and it's boolean 
        - ended -> and it's an integer
        - forked -> and it's a string
        - swapped_for -> and it's a string
        - cryptocompare -> and it's a string
        - coingecko -> and it's astring
    - If type is ethereum_token so (AssetType.ETH_TOKEN or AssetType.ETH_TOKEN_AND_MORE):
        -  ethereum_address -> and it's a string
        - ethereum_token_decimals -> and it's an integer
  

If any of the above is not true fail the test with an informative error of what went wrong.

**Comment by LefterisJP** [comment]
Let me know if you can do it soon. If not probably someone else will pick it up @jamesmccannon02

**Comment by jamesmccannon02** [comment]
It will probably be next weekend it is done. Leave it open to anyone and if not done I'll pick it up then

**Comment by jamesmccannon02** [comment]
@LefterisJP Which test folder doe i create my .py file in for the test?

**Comment by LefterisJP** [comment]
Hey @jamesmccannon02 as I mentioned above the test should just be one more test in [this](https://github.com/rotki/rotki/blob/4f5292e0934d7eb375bdc42bb70754f6b44ecb1d/rotkehlchen/tests/unit/test_assets.py#L139-L144) file. No need for a new folder or file.

**Comment by jamesmccannon02** [comment]
Upon further investigation, this isn't the right project for me to learn what i need to. I'll leave this to someone else.
