### ISSUE TITLE
Support Smart Contract Wallet in "DEX Trades" Section

### ISSUE THREAD

**Issue by ETHorHIL** [rotki/rotki#2368]
## Abstract

Support Smart Contract Wallet in "DEX Trades" Section

## Motivation

UNISwap trades conducted from an Argent wallet dont show up under "DEX Trades". The address of that wallet can not be selected is apparently not recognized.

**Comment by LefterisJP** [comment]
Hello!

What exactly is a smart wallet in this context? All uniswap v2 address trades should be detected. I am not familiar with how argent works but if it makes a transaction initiated by your address and this address is tracked in rotki it should be detected.

**Comment by ETHorHIL** [comment]
Hey Lefteris, thanks for answering. 

I have added two accounts to "Accounts&Balances" that interacted with uniswap: 
- one EOA
- an Argent account. 
Only the EOA shows up under DEFI->DEX Trades -> Select adresses. 

Argent is essentially a multisig contract. The interaction between the Argent contract and uniswap appears under "internal transactions" in Etherscan, could this be a factor?

**Comment by LefterisJP** [comment]
Closing as smart contract trades like safe or argent should be detected now
