### ISSUE TITLE
New coin request for manual balance asset list

### ISSUE THREAD

**Issue by jebb-m** [rotki/rotki#2369]
Hi there,

I have a few coins in my portfolio which aren't currently available in the manual asset list, I was wondering if it's possible to add them in?

The coins are:
XOR (ERC20 Sora)
BAN (Banano)
VTHO (VeChain)
KCS (ERC20 KuCoin)
BAO (ERC20 Bao Finance)
EWT (EnergyWeb)
GUNTHY (ERC20)

If any/all of these could be added that would be awesome, it's the last thing holding me back from switching to Rotki as my sole portfolio manager! Will be buying premium this week either way, thanks for that hard work!

**Comment by LefterisJP** [comment]
Hey @jebb-m and welcome to the rotki fam!

> VTHO (VeChain)
> KCS 
> EWT (EnergyWeb)

Those should already exist.

For the rest I am adding them in this PR: https://github.com/rotki/rotki/pull/2371

**Comment by jebb-m** [comment]
Awesome, thanks!!
