### ISSUE TITLE
USDT not showing in latest Rotki 

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#2372]
## Problem Definition
USDT is within one of my ethereum addresses but isn't showing in Rotki. Neither in the dashboard or in accounts and balances.

### System Description

Operating system:  Windows 10
Rotki version: rotki-win32-v1.13.3

**Comment by LefterisJP** [comment]
I just tried with a random tether address and it shows just fine. 

Are you 100% sure the address with tether is tracked? Are you sure it's not in a protocol we don't support? Did you maybe just transfer the tether now? If you did that then you will need to refresh balances.

 To help you here I would need the address in question in a DM in discord if any of the above do not work.

**Comment by drgonzo31** [comment]
It's showing up now. Must of been a little delay. I did the transfer a few days ago. It was showing up in mycrypto but not in rotki. I'll close.
