### ISSUE TITLE
Currency location won't restore

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#2380]
## Problem Definition
Currency location settings won't restore when `After` triggered. Expected currency sign `$` to be placed in from of the number when `Before` triggered. 

https://user-images.githubusercontent.com/3277207/108007940-02ff1500-6fb4-11eb-8042-512fee8a4f2d.mov

### System Description

Operating system: macOS Big Sure 11.2.1
Rotki version: 1.13.4.DEV

**Comment by kelsos** [comment]
Hey @kolya182 that is interesting.

It seems that it only affects the settings display while you are changing it. 

If you navigate back and go into settings it will update to the correct position. Also, the setting seems to have the desired effect across the application despite this glitch. 

It should not be overly hard to fix.
Thanks for reporting :)
