### ISSUE TITLE
Pool Together token support

### ISSUE THREAD

**Issue by jebb-m** [rotki/rotki#2381]
I'm getting the following backend message on refresh/load, related to tokens for the PoolTogether platform (PcDAI).
Was wondering if that could be supported at some point?

Message:
"Unsupported asset PcDAI with address 0x334cBb5858417Aee161B53Ee0D5349cCF54514CF encountered during DeFi protocol queries"

Also, I've seen some talk of KuCoin support, any word on when that is likely?

Thanks for all the great work, Rotki definitely deserves way more attention!

**Comment by LefterisJP** [comment]
Hello @jebb-m for questions like that it's much better to just ask in Discord: https://discord.gg/aGCxHG7

> Unsupported asset PcDAI 

This is one of many assets we just don't know about. We never show assets for which we can't find a price and this is why you see this message. If you can find it on coingecko or cryptocompare we can add support for it. If not, we don't know how to get its price. So perhaps if we support the Pool together protocol (https://github.com/rotki/rotki/issues/1120) this will become easy to do? I don't know as I am not familiar with the protocol.

> Also, I've seen some talk of KuCoin support, any word on when that is likely?

Next release. Soon.

> Thanks for all the great work, Rotki definitely deserves way more attention!

Thank you for the kind words :heart:

**Comment by jebb-m** [comment]
Thanks for the explanation, makes sense. Hopefully the protocol will be supported at some point but no biggie for now, I'll just manually add my PT account balances until then.

They did just airdrop their governance token Yesterday (POOL), which appears to be on CoinGecko. Any chance that could be supported in an upcoming update?
https://www.coingecko.com/en/coins/pooltogether

**Comment by jebb-m** [comment]
Sortof related... Could LOTTO also be supported?
https://www.coingecko.com/en/coins/lotto

**Comment by LefterisJP** [comment]
Yes to both. Will be done when #2412 is merged.
