### ISSUE TITLE
Add support for Kusama transactions

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#2385]
## Abstract

Master story #1081
Milestone: 2
Epic: transactions history query

~~Given a Kusama account, query its transactions using an indexer and manage them as rotki does with other supported blockchain transactions, e.g. store them in db, include them in the events history.
The chosen indexer is [Subscan](https://www.subscan.io/), which has an [API](https://docs.api.subscan.io/#introduction) (at the moment it does not require an API key, pending to confirm when it will be enabled).~~

Unless Subscan clarifies whether its API will be open or not, we will request on-chain the transactions.
 
## Specification
1. Break down a Kusama extrinsic, define the essentials from rotki's point of view, e.g. accountability, UX. Do research re substrate/Polkadot/parachains extrinsics and decide whether makes sense or not to store them in a common table with their specific chain ID.
2. Prototype the DB schema.
3. Either remove or disable the Subscan API request for checking the synchronisation of the nodes (`_request_explorer_api()`). Find an alternative way (if possible).
4. Create the KSM transactions endpoint (i.e. at `/blockchains/KSM/transactions/`). Request the extrinsics on-chain using the library py-substrate-interface with the [Parity archive node](https://guide.kusama.network/docs/en/kusama-endpoints#parity-archive-node). This point includes the logic for requesting, processing and storing (dbhandler add/get/delete) the transactions of an account. Further discussion about how to deserialize extrinsics will be required, in particular with the `params` value, which may contain the destinatary as a substrate account (it seems reasonable to store it formatted as ss58 for the particular chain).
5. Create the method that deletes all the Kusama/substrate data of an account.
6. Include the query call into the TaskManager.
7. Add support for Kusama transactions in EventHistorian.
8. Add support for Kusama transactions in ledger actions.

**Comment by LefterisJP** [comment]
Superseded by https://github.com/rotki/rotki/issues/6615
