### ISSUE TITLE
MacOS version dmg 1.14.0 cannot be installed on MacOS 10.14.6 Mohave

### ISSUE THREAD

**Issue by dtolsen** [rotki/rotki#2391]
MacOS 10.14.6 Mohave

Attempting to install rotki-darwin-v1.14.0.dmg results in an error modal stating: 
"rotki-darwin-v1.14.0.dmg” can’t be opened because Apple cannot check it for malicious software."

.zip version loads, but hangs on "connecting to rotki backend" with a loading spinner.

Contact me if I can provide any additional details for debugging.

**Comment by LefterisJP** [comment]
Thank you @dtolsen. We are aware. We are working on a fix. Check the support channel in https://discord.gg/aGCxHG7 for more info.
