### ISSUE TITLE
Loopring balances don't get automatically fetched when adding an API key

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2399]
## Problem Definition

Loopring balances are not automatically refreshed when adding an API key

### Tasks
- [x] Automatically refresh loopring balances when an API key is added
- [x] Notify the user if the module needs activation

**Comment by handelaar2** [comment]
In the release notes it is not mentioned that under settings/defi. the loopring module has to be activated (together with a restart). This will have people wonder why things are not working after adding the api key.

**Comment by kelsos** [comment]
@handelaar2 good mention let me amend the tasks in the description

**Comment by kelsos** [comment]
@LefterisJP do you think it would be a lot of effort to make a module activation/deactivation API for v1.15.0 that doesn't require restart?

For loopring for example this could be automated by adding and removing the API key (no need for a secondary action)

**Comment by LefterisJP** [comment]
As dicussed in discord yes: https://github.com/rotki/rotki/issues/1375

Scheduling both for next release.
