### ISSUE TITLE
Take into account loopring balances in the snapshots

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2401]
## Abstract

At the moment loopring balances are not included in the balance snapshot

## Task

Take them into account in the snapshot. Should be as easy as including them in the get all balances call with the current architecture. But making sure a lock exists.

**Comment by yabirgb** [comment]
Is this issue still relevant or was added in the last release? I've been looking at the code and the code to check for the loopring balances seems to be there. Also I couldn't find references in the repo or the docs for what snapshots exactly are.

**Comment by LefterisJP** [comment]
Hey @yabirgb. It's still relevant.

> Also I couldn't find references in the repo or the docs for what snapshots exactly are.

@vnavascues This is what I also meant. Things like that which is evident for us but not to someone new to the code and the project.

-----

So @yabirgb what this issue is about the [query_balances](https://github.com/rotki/rotki/blob/ac9ca445e357037a375e99217997511e40bfc86e/rotkehlchen/rotkehlchen.py#L748) function that queries all balances and saves a snapshot.

In there we should also query all loopring balances too if the loopring module is activated and include them in the logic of the snapshot saving with location being Loopring. I see that there is no Loopring location type so this would need to be added.
Additionally since the loopring balances query may now be called from multiple greenlets that function should be protected by a lock.

**Comment by yabirgb** [comment]
Is there currently a file of tests for the snapshots? I couldn't find tests on this

**Comment by LefterisJP** [comment]
There is no unit test specifically for this. But the functionality is tested by all tests that deal with all balances query such as this one: https://github.com/rotki/rotki/blob/a275051ac1bccc01a0827003f3c5525cc1dc3540/rotkehlchen/tests/api/test_balances.py#L140
