### ISSUE TITLE
Manual balances not taken into account in premium statistics

### ISSUE THREAD

**Issue by rkalis** [rotki/rotki#2403]
## Problem Definition
In my dashboard I see my exchange balances, blockchain balances and manual balances (with 'blockchain' as their location), as well as the totals of these categories.

On the statistics page manual balances are excluded. I would expect them to be included. Is this expected behaviour?

### System Description
Operating system: macOS 11.1 Big Sur
Rotki version: 1.13.2

**Comment by LefterisJP** [comment]
Hey @rkalis nice to see you here!

What do you mean by that? What do you mean that manual balances are excluded in the statistics page? From which component exactly?

**Comment by rkalis** [comment]
Hey @LefterisJP, loving the product so far!

So initially it was in every component (e.g. netvalue graph showed exchange + blockchain value but not manual, & value distribution excluded any assets with only manual value). I just checked again now and it is displaying everything correctly. 

I entered my manual balances a bit after the others, so I guess that it needed some time to update. I entered manual balances yesterday, and figured I'd wait until today to open an issue in case there was a delay. I gues I just had to wait half an hour longer for it to resolve itself haha!

Is there a predictable delay between entering new balances and the statistics updating? If so it might be useful to display a short message about that on the page.

**Comment by isidorosp** [comment]
Premium Statistics only shows data based on the "balances snapshot" in rotki, which happen according to how often you've set the saving frequency in the user settings (or after a force save via the save status floppy disk button on the toolbar). So, if you've added a manual balance, you won't see it reflected in Premium Statistics until a balances snapshot has been saved (if you don't force save and you have the default save frequency of 24h, you will see manual balances included in your premium states after one day).

**Comment by rkalis** [comment]
Oh I see. That makes sense. I didn't understand that that was what the "balance data saving frequency in hours" meant. Thanks for clearing up my confusion!
