### ISSUE TITLE
Get rid of rlk_json_loads

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2407]
## Abstract

It's time.

Many bugs have been caused by this. Latest one being https://github.com/rotki/rotki/issues/2398

The idea behind it was simple at first, to translate all numbers coming in as `FVal` automatically.

But it makes no sense anymore and is probably adding an unecessary overhead to all external json parsing. Plus creates all this kind of bugs where you expect something to be a string but is an FVal because the string happens to look like a number and we did not force it to be a string.

Currently in the code we follow very strict deserialization protocols all over the place, using appropriate deserialization functions to parse external input. As stated in the comment we should stick to that and get rid of `rlk_decode_value()` and its use via `rlk_json_loads`, `rlk_json_loads_dict`, `rlk_json_loads_list`.

https://github.com/rotki/rotki/blob/eddaec9967b06f3396133c385e8f3d7a2e6162f9/rotkehlchen/utils/serialization.py#L66-L76

## Task

Do it! 

- Should be pretty straightforward but may need quite a few places to change since it's quite ingrained into the codebase.
- It may very well be that something may break with this change since all automatic `Fval` conversion from incoming json will stop. So ... **test this thoroughly**.

**Comment by yabirgb** [comment]
Just to make sure I understood this issue, the idea is to remove all the calls to `rkl_decode_value` by `rlk_json_loads` ( I guess is a mistake and you refer to `rlk_jsonloads`), `rlk_json_loads_dict`(`rlk_jsonloads_dict`) and `rlk_json_loads_list` (`rlk_jsonloads_list`) and use strings instead of `FVal`s?

**Comment by LefterisJP** [comment]
no not exactly. This one is to replace this custom decoding by `rlk_jsonloads` by a simple `json.loads`, perhaps within 2 types functions to satisfy mypy in various place.

The reason for this is we must get rid of the automatic conversion of number-like string that `rlk_jsonloads` always does automatically to `FVal`.

As this has caused multiple errors, and we actually do end up converting/deserializing each dict-object we read from json all around the codebase in specialized functions anyway.

**Comment by LefterisJP** [comment]
I will take this up as I really want this done.
