### ISSUE TITLE
Backup db before updating rotki database to a newer version

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2408]
## Abstract

Introduce a mechanism that keeps a backup of the database before upgrading to the newer version of rotki.

## Motivation
Make it easier to recover in case something goes wrong during the migration or update.
Make it easier to downgrade to the previous version of the application if something is wrong with the newer version (in case of unexpected bugs)

## Specification
Need a way to manage and display existing backups, allow the user to manually or automatically manage them to avoid having a lot of space used in the unneeded backups

**Comment by LefterisJP** [comment]
We actually started doing this for specific versions. It's there for v24->25 and v25->v26. But it's just taking a DB copy before upgrade, timestamp and version in the filename and stays in the directory. We can probably just augment this with a way to manage those from the frontend.

**Comment by kelsos** [comment]
Yes a UI to manage the previous backups would be nice.

**Comment by LefterisJP** [comment]
Closing this too as part of #2768 and #3673
