### ISSUE TITLE
 Add support for $FTT token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2410]
Please add support for $FTT token. This is the token of FTX spot and derivative exchange. SBF's centralized exchange baby.

Contract 0x50d1c9771902476076ecfc8b2a83ad6b9355a4c9

https://www.coingecko.com/en/coins/ftx-token

https://ftx.com/
https://twitter.com/FTX_official
https://medium.com/@ftx
https://www.linkedin.com/company/ftx/
https://t.me/FTX_Official
https://weibo.com/u/7222293679

### Distro, Tokenomics, Token Utility

https://ftx.com/en/ftt
https://ftx.com/en/staking
https://help.ftx.com/hc/en-us/articles/360052410392
https://help.ftx.com/hc/en-us/articles/360027645972-FTX-Token-FTT-FAQ
https://help.ftx.com/hc/en-us/articles/360024479432-Fees

**Comment by LefterisJP** [comment]
You ask you get. Will be merged once #2412 goes in.
