### ISSUE TITLE
History ERC20 transactions

### ISSUE THREAD

**Issue by Kinzowa** [rotki/rotki#2415]
## Abstract

I would be nice to have ERC20 token transfers in the history section. Currently only ETH transfers appear.

## Motivation

Have full visibility of an account history.

**Comment by LefterisJP** [comment]
Hey @Kinzowa. This is a good point. This will be done when we implement https://github.com/rotki/rotki/issues/1477. A general decoding scheme of ethereum transactions. One of the things that decoding would find out, and probably the most common, would be ERC20 transactions.
