### ISSUE TITLE
Wrong password or invalid/corrupt database for user

### ISSUE THREAD

**Issue by mruepp** [rotki/rotki#2425]
## Problem Definition

I am unable to login to rotki after initial install and upgrade to premium

## Logs

1. Downloaded Rotki.
2. Created Account. Local username is my first name. Password is complex.
3. Setup Rotki
4. Went to the website rotki.com. Created an account there, account name is different. Password is different to local password
5. Created API Keys on the website
6. Added API Keys to Rotki
7. Rotki stayed open for about 1h
8. Quit Rotki
9. Opened rotki, tried to login with my local username/password
10. Got Errormessage: "Wrong password or invalid/corrupt database for user". Unable to logon either with local or remote password/user combination
11. Login to Website works

### System Description
Macos Macbook Pro

Operating system: macos big sur 11.2.1
Rotki version: 1.14.1 (newest release as of today)

**Comment by mruepp** [comment]
Moved the rotki folder out of ~/Library/Application Support
Restarted Rotki and created a new user, enabled Premium. Login worked. All settings vanished. When tried to pull the sync from the premium servers, Error - Screenshot occured. All settings lost
<img width="595" alt="Screenshot 2021-02-23 at 19 12 37" src="https://user-images.githubusercontent.com/10906913/108888250-7edc0b80-760b-11eb-84ce-e929c0fb76a9.png">

**Comment by LefterisJP** [comment]
Hey @mruepp in case you did not figure it out yet, the password of the website is only for the website and not for the local account as per the information both when you open the app and when you make an account in the website.

For easy answers to such questions it's probably easier if you join discord: https://discord.gg/aGCxHG7

**Comment by mruepp** [comment]
Thanks, I closed the issue. Was a Problem with the password manager. Wrong password got saved. Thanks
