### ISSUE TITLE
Add Sushiswap support

### ISSUE THREAD

**Issue by JayWelsh** [rotki/rotki#2426]
## Abstract

It seems that Sushiswap transactions are not currently picked up as trades in the profit/loss section of the application

## Motivation

Sushiswap is one of the primary decentralised exchanges and I would imagine that since it is a Uniswap fork, it should take less code to implement this feature than to implement tracking for an entirely different decentralised exchange

## Specification

N/A

**Comment by LefterisJP** [comment]
Hey @JayWelsh thanks a lot for the feature request. We will see what can be done! In the meantime feel free to join our discord chat to keep tabs on our development and also chat with other users: https://discord.gg/aGCxHG7

**Comment by JayWelsh** [comment]
Thanks a lot @LefterisJP, much appreciated! 🌟

**Comment by yabirgb** [comment]
For this one there is a graph that is basically a fork of the uniswap one. Assuming that information in the graphs can be used a lot of code can be shared

**Comment by LefterisJP** [comment]
This should not have been closed. The frontend is not yet done.
