### ISSUE TITLE
Make the selection of visible items per page persist

### ISSUE THREAD

**Issue by tasdienes** [rotki/rotki#2427]
The default is 10 rows per page.  I can't see why anyone would ever want to click through pages with only 10 rows each, when scrolling is much easier.  I'd suggest increasing the default to 100 or more.  Also, it might be nice if the selected value was sticky so you don't have to change it every time you switch pages.  This applies to the Dashboard, as well as other pages that have rows.

### Task
- [x] Remember the user's selection across all the tables in the session
- [x] Remember the user's selection across different sessions.

**Comment by kelsos** [comment]
Hey @tasdienes, making the selection sticky would be easy to do, this would solve the problem you are facing right?

The 100 entries limit per page is due to technical limitations, as increasing the limit more can lead to some serious performance degradation of the frontend.

**Comment by tasdienes** [comment]
Yep, making the selection sticky is a solution. That way one only has to change the setting once.
