### ISSUE TITLE
Can't add Binance API Keys: Local System Clock not in sync

### ISSUE THREAD

**Issue by bemusementpark** [rotki/rotki#2436]
## Problem Definition

I can't add binance API. Kucoin and Coinbase work fine.

## Error Message

"Exchange Setup"

"The setup of binance failed due to: Local system clock is not in sync with binance server. Try syncing your system's clock"

Operating system: OSX 10.15.7 (19H2)
Rotki version: 1.14.1 & 1.14.2

**Comment by LefterisJP** [comment]
Hello @bemusementpark. So you tried with both v1.14.1 and v1.14.2?

Are you sure you local system clock is properly synced?

**Comment by bemusementpark** [comment]
Yes, tried 2 latest versions. I'm not sure it's properly sync'd, but I
didn't get issues adding those other two APIs.
