### ISSUE TITLE
Addresses in asset locations are not ordered by name

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2442]
This still does not work properly; please can you reopen?  When I click on the Address column header, it weirdly cycles between not two but *three* different sorting modes, none of which correctly sort according to the account label:

![vokoscreenNG-2021-02-25_18-20-48](https://user-images.githubusercontent.com/100738/109198661-66e4c300-7796-11eb-85fd-1af358c1dbef.gif)

_Originally posted by @aspiers in https://github.com/rotki/rotki/issues/1140#issuecomment-786106208_

**Comment by LefterisJP** [comment]
Don' think we will actually make v1.14.3, but since this is a bug,scheduled it for there so it goes in the bugfixes branch.

**Comment by kelsos** [comment]
I planned to change it later :)

**Comment by LefterisJP** [comment]
Is this fixed @kelsos ? I don't see a changelog entry.

**Comment by kelsos** [comment]
There was a changelog entry in the linked PR

**Comment by LefterisJP** [comment]
@kelsos lol my local was not rebased on develop. Thanks. I see it now.

**Comment by kelsos** [comment]
It is in develop... the changelog entry.

**Comment by aspiers** [comment]
@kelsos @LefterisJP Is it just me or has the ability to sort Ethereum accounts vanished at some point in the last 2.5 years?  Even though this is a very small simple feature, it has a big impact on usability for me.

![image](https://github.com/rotki/rotki/assets/100738/0f8cda70-4de7-46dc-9866-f23c1bb9d7a3)

**Comment by LefterisJP** [comment]
Hey @aspiers these are best asked in discord. How do you want to sort an address? By lexicographic order of the 0x?

**Comment by aspiers** [comment]
Sorry yes, happy to take this to Discord!  No, I want it sorting by name as originally reported in #1140 - at least when a name is present.  This was already covered in depth by our discussion in #1140 so it may help to revise that thread before discussing further.
