### ISSUE TITLE
Allow addition of trade using quote amount instead of rate

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2446]
You can only specify the rate for a trade. I would like the option for the rate to be calculated based on the quote amount total.

Note: This is how delta works and how the data is displayed when exporting to CSV from delta. Without this option, it creates rounding errors in the report.

For example, if I spend 1001.23 EUR to buy some BTC I would like that information to display in the "Paid in Asset" column of the report accurately. Right now it uses the rate to calculate it, which leads to rounding errors (values with many decimal places). This is because I have to calculate the rate and enter that into rotki, which is then used to convert back to "Paid in Asset".

**Comment by LefterisJP** [comment]
This is not an error as you also specified. It's just that trades in rotki need the rate and the quote amount is calculated from that. If you have to do the opposite, there may be some precision loss.

You are essentially asking for an option of inputting a trade that does the opposite. Enter the quote amount and calculate the rate from it. Is my understanding of the feature request correct?

**Comment by a7e8** [comment]
That's correct it's a feature request. I don't know if this is a common request or not? For the trade in question I don't actually have access to the exact rate that was used anymore (just the amount). And then also because of the difference of how delta works, I put the quote amount (instead of the rate) into rotki and wondered why the report was wrong until I figured it out.

**Comment by a7e8** [comment]
Just looking at the delta app: When you edit a trade you can choose `per coin` or `in total`. The CSV export just has the quote amount though (total).

**Comment by LefterisJP** [comment]
Our internal format uses the trade rate as it's modeled after the first exchanges we integrated with. Changing from one to the other is bound to lose you some precision if the numbers you deal with have too many decimals.

> That's correct it's a feature request. I don't know if this is a common request or not?

No not really, you are the first to ask for it. But I can understand it. I am not sure how we can satisfy it but thanks for opening the issue and making us think about it!

**Comment by a7e8** [comment]
Yes I think in most cases the rate is just derived from the two values of the exchange (so it doesn't really exist). The specific details of the exchange likely vary though as either the rate or the amount will end up being rounded. I think there are arguments for doing it either way.

**Comment by lukicenturi** [comment]
I'm working on this now
