### ISSUE TITLE
Profit and Loss Report - Received in Asset does not take fee of same type into account

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2447]
When adding a trade that has a fee in the same asset e.g. BTC_EUR with a BTC fee. The Received in Asset field does not deduct the fee.

This also means that the amount without the fee subtracted is used for the BTC forks: BCH, BSV.

I could add the fee as a separate Ledger Action (it is a withdrawal fee), but the fork amounts in the report will still be incorrect. It's interesting these appear in the report before the forks happened but I guess this is ok as they're not claimed yet it's just to calculate cost?

Please advise the correct way to enter trades and withdrawal fees. Should the amount equal the amount bought on the exchange, or the amount received after withdrawal (less fee)? Should I put fees in the trade itself or a separate ledger action expense?

**Comment by LefterisJP** [comment]
> It's interesting these appear in the report before the forks happened but I guess this is ok as they're not claimed yet it's just to calculate cost?

yes

> The Received in Asset field does not deduct the fee.

Fees are subtracted as an expense in their equivalent fiat value during accounting. It's probably not reduced if it's in the same asset as one of the two assets in the pair as you saw.

> Please advise the correct way to enter trades and withdrawal fees

Withdrawal fee? I am not sure I understand. What I understand as withdrawal fee is let's say how much binance would charge me to withdraw ETH. This we autodetect from the supported exchanges and handle properly.

As for trades, as I mentioned above the fees are considered as expense and are reduced from the profit of the trade in fiat value.  It's possible we don't reduce the asset in cost basis calculation for the fees. Which I would say if we don't it's something we should do and needs fixing. I will have to take a look to confirm later with a clear head.

If that is the case until it's fixed you can create a separate ledger entry, or wait for a fix of this issue.

**Comment by a7e8** [comment]
I think it may be ok If the received in asset does not deduct the fee. It might be good to introduce an option that enables this per trade though.

The fees should definitely deduct from the cost basis. It would actually help if you exposed the running total balance for each asset so that each trade can be reconciled. If you allow to manually deposit fiat like EUR as well then you can also reconcile fiat balances too.
