### ISSUE TITLE
Error fetching loopring balances when there are multiple addresses

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2451]
## Problem Definition

I added a loopring API Key and I have multiple addresses with assets in loopring. When Rotki tries to fetch the balances from all the addresses it doens't fetch all the loopring balances.

What I expect is the possibility to fetch balances from many accounts in loopring. Probably a solution is to allow more API Keys in the settings for loopring and link them to the accounts but Zerion for example is able to see assets in different accounts.

## Logs

 When Rotki tries to fetch assets from one address that is not the one used for the API Key I get the following alert

`The given loopring API key does not match address 0x3Ba6eB0e4327B96aDe6D4f3b5787XXXXXXXXXX. Skipping its query.`

### System Description

Operating system: Solus (Linux)
Rotki version: develop branch

**Comment by LefterisJP** [comment]
This is a known issue with loopring. We are in contact with them to allow changing this on their end. Other solution would be multiple api keys per user on our side but that is a terrible hack and terrible user experience and we should really just avoid it.

They promised to help with this.

**Comment by yabirgb** [comment]
This can be closed I believe
