### ISSUE TITLE
Consider switching from 3-mode table sorting to 2-mode

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#2452]
As originally noted in [my comment on #1140](https://github.com/rotki/rotki/issues/1140#issuecomment-786106208), clicking on table headers cycles between not two but three different sorting modes:

![vokoscreenNG-2021-02-25_18-20-48](https://user-images.githubusercontent.com/100738/109198661-66e4c300-7796-11eb-85fd-1af358c1dbef.gif)

[**@kelsos**](https://github.com/kelsos) replied on [February 26, 2021 12:47 PM](https://github.com/rotki/rotki/issues/1140#issuecomment-786627122 "2021-02-26T12:47:08Z - Replied by Github Reply Comments"):
> Vuetify's data table by default behaves like this, it doesn't enforce a sorting selection. You have to override the configuration if you want to always have a sorting option selected. So it's not supporting it per se, rather that was the default and we didn't have any complaints or issues with that so far.
> 
> I cannot think of a specific use case of why would we prefer it this way over enforcing a selection, I am not sure if [@LefterisJP](https://github.com/LefterisJP) has a different opinion on that. Looking into vuetify's configuration, it looks simple enough to make a sorting selection required.

and I replied:

> Ah, I see. My instinct is that given this is different to every single other sortable table UI I've ever seen, unless there's a concrete reason for keeping it, it is more likely to confuse users than help them. But maybe there is a good use case and I'm just missing it.

So I'm filing this here for discussion as it's a separate issue to #1140.

**Comment by LefterisJP** [comment]
So let me see if I understand the question. At the moment we have 3 sorting modes, asceding, descending and no mode (defaults to data as they came?).

And the question is if can get rid of the last one?

**Comment by aspiers** [comment]
Yeah exactly.  If there is a use case which justifies keeping it then we can just close this, but I suspect it's currently causing more confusion than value.

**Comment by kelsos** [comment]
Like I mentioned on the other issue, I cannot think of any valid use-case for the default mode. It is only there because this is the default of that data-table component.

**Comment by LefterisJP** [comment]
All right then so if its' possible to remove that it would make sense for our users and for us. So this is a valid request. Schedule it at your convenience @kelsos.

Assuming it's possible.

**Comment by kelsos** [comment]
It seems that there is an option to require sorting. I didn't test it but from the docs it seems that it does what we need. It should be rather small so it will depend on how much time we have before the release.

**Comment by aspiers** [comment]
Great!  No rush - obviously this is a low priority thing, just some nice polish to get even more quality to the UX ;-)
