### ISSUE TITLE
Lefteris Karapetsas should take more vacation.

### ISSUE THREAD

**Issue by Michael-A-Heuer** [rotki/rotki#2455]
## Motivation
Lefteris Karapetsas is working a lot as [his contribution feed clearly indicates](https://github.com/LefterisJP).

He should clearly take some days off to not become buggy or faulty.

## Specification
If enough people support this feature, it can be implemented quite quickly.

**Comment by mavroudisv** [comment]
This issue could always be reopened in the future if the problem reappears.

**Comment by Blackswan122** [comment]
I agree. A temporary Man Maintenance session is required to prevent a total shutdown.

**Comment by aspiers** [comment]
Haha, great of GitHub issue tracker!  @LefterisJP you are doing an absolutely incredible job, hope you are looking after yourself though!  :stuck_out_tongue_winking_eye: :pray:

**Comment by Blackswan122** [comment]
When are we going to get an update on this please?

**Comment by LefterisJP** [comment]
I apologize for the slow response to this issue. Thank you all for your feedbacks and concerns! :heart: 

I am very happy to schedule this for the "Financial sustainability" milestone.

**Comment by LefterisJP** [comment]
I am trying to clean up the issues slowly a bit since we got many open ones. So closing this one.

Love that you guys care for me :heart:
