### ISSUE TITLE
Document History section

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#2463]
AFAICS there are no docs for the History section:

![image](https://user-images.githubusercontent.com/100738/109399360-4bb2b880-793a-11eb-8249-bcf5aaedf3a8.png)

I would expect them to appear under https://rotki.readthedocs.io/en/stable/usage_guide.html?highlight=history#tracking-accounts-and-balances but that only concerns current balances, nothing historical.

**Comment by monem75** [comment]
rename it

**Comment by LefterisJP** [comment]
there is now: https://rotki.readthedocs.io/en/stable/usage_guide.html?highlight=history#historical-events
