### ISSUE TITLE
Validation error on adding manual balance: "Failed to deserialize location symbol. Unknown symbol realestate for location"

### ISSUE THREAD

**Issue by berkes** [rotki/rotki#2468]
## Problem Definition

When adding a manual balance, and choosing "Real Estate" from "location" a cryptic error message appears. 

Expected outcome:
* No error shown.
* An error shown with a descriptive error explaining what I must do to fix it.

Actual outcome:

![Schermafdruk van 2021-02-28 12-00-07](https://user-images.githubusercontent.com/77059/109416629-b9ed8e80-79bf-11eb-93d6-105d460e1d54.png)

`Failed to deserialize location symbol. Unknown symbol realestate for location`

Choosing "External" works.

Editing existing balances and then choosing "Real Estate" gives the same error. 

## Logs

Logs were generated but showed nothing related to this issue. It does include privacy-sensitive data, so I'd prefer not to include those there, unless I know what parts to include here. If required, please let me know what I should look for, to provide the relevant parts of the logs.

### System Description

Operating system: Ubuntu 20.04.2 LTS x86_64 
Rotki version: 1.14.2 (rotki-linux_x86_64-v1.14.2.AppImage)

**Comment by LefterisJP** [comment]
Hey @berkes thank you for opening an issue.

There is no need for additional logs. This is probably enough. Sounds like a bug. Let us investigate and fix. I will write here if there is more information needed but probably not.

**Comment by vnavascues** [comment]
@berkes, this will be fixed in our next release
