### ISSUE TITLE
Unified History section

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#2469]
# Summary

In this issue I highlight some weaknesses of Rotki's current approach to providing views of transaction history, show strengths and weakness of approaches from three commercial rival portfolio trackers, and propose a way Rotki could become better than all of them ;-)

This issue can initially serve as a focal point for discussion on this topic.  If there is agreement that a revamp is justified, then this could be superseded by an epic issue and several smaller issues which split up the revamp into manageable chunks of work.

# Drawbacks of current approach to transaction history

Currently the History section of the app is split into four sections:

![image](https://user-images.githubusercontent.com/100738/109399360-4bb2b880-793a-11eb-8249-bcf5aaedf3a8.png)

(Side notes: IMHO "Ledger actions" is a slightly confusing name as reported in #2464, and also this section is not documented as reported in #2463.)

While it is of course great to be able to filter historical transactions by these four top-level categories, it is not the only way which users will need to be able to slice and dice their history.

Furthermore, the first three of these offer further filtering by "location", but this filtering is limited to centralised and decentralised exchanges, so you can't filter by wallet except for Ethereum.

You also can't filter by a particular token.

Finally, some history is provided *outside* the History section, in DeFi > DEX Trades.  This creates a little bit of extra cognitive load which slightly hurts the overall UX.  I suspect the same is probably true within the Staking section too.

# Example use cases

Here are some example use cases which I think should all be very easy to do in an ideal UI, but which are not currently possible in Rotki:

1. Show me all transactions relating to BTC (e.g. buy/sell/deposit/withdraw/transfer)
2. Show me all transactions relating to an ERC20 token (e.g. buy/sell/deposit/withdraw/transfer)
3. Show me all deposits from an external source into a given wallet or exchange account
4. Show me all deposits and transfers from any source into a given wallet or exchange account
4. Show me all transfers and withdrawals from a given wallet or exchange account
5. Show me all airdrops I received in 2019
6. Show me all income payments I received in the second half of 2020
7. Show me all staking rewards I've ever received
8. Show me all transactions which have a user-provided comment containing a given word

# Summary of proposed design

The basic idea is to create a single general-purpose transaction history querying interface which makes both simple and complex filtering of transactions easy.  It would retain Rotki's existing table format with sortable headers; the only difference would be how the filtering is done.

I've spent a LOT of time using the equivalent transaction history sections in CoinTracker, Accointing, and Koinly, and I think Rotki would benefit from stealing some design ideas from them.  So let's look at them in turn below.

# CoinTracker

![vokoscreenNG-2021-02-27_21-19-00](https://user-images.githubusercontent.com/100738/109400607-8ec45a00-7941-11eb-90bc-9cb2419d3fde.gif)

You can type e.g. `BTC` in the search field to limit to only show transactions relating to Bitcoin.

Selecting one of the options from any of those dropdowns will populate the search field with "advanced" search terms such as:

- `category:sold`
- `has:review`
- `type:airdrop`
- `wallet:037bae8f-b13c-4129-aa82-12905306223a`
- `from:2020-1-1 to:2020-12-31`

and immediately filter the list of transactions to only those matching the given term.

## Pros

- You can build more complex searches by combining filters, e.g. `type:airdrop from:2020-1-1 to:2020-12-31` or `category:trade usdc`.

- The search term is included in the query string of the URL in the browser window's address bar, so you can bookmark specific searches.

## Cons

- Every time you select something from a dropdown, it replaces whatever was previously in the search field, so you can only combine multiple filters manually by typing them into the search field.  Doh!

- It confuses *filtering* with *sorting*, e.g. if you click `order by` and then choose `oldest`, it replaces whatever you previously had in the search field with `order_by:oldest`.  Doh!  Filtering and sorting should be completely separate things!

- There's no way to sort results by a given header (except date via `order by`).

- You can't do a text search for notes / comments.

- The display is not space-efficient, which requires the user to scroll vertically a lot.

- Pagination is fixed to 15 entries per page.

# Accointing

![accointing-3](https://user-images.githubusercontent.com/100738/109404837-de1a8280-7961-11eb-805e-9657abd9bb1d.gif)

As with CoinTracker, we can see that it uses the same idea of a bunch of dropdown menus at the top of the table, providing various filters.

## Pros

- Far better date picker

- Rows are nice compact and space-efficient

## Cons

- Date picker doesn't allow one-click narrowing to a specific year (or tax year).

- There's no way to sort results by a given header (e.g. toggling chronological order vs. reverse chronological).

- There's no way to filter by sender, or by recipient; you can only search for a wallet or exchange which is involved on at least one end of the transaction.

- [Trade orders are shown as unclassified](https://community.accointing.com/t/orders-are-shown-as-unclassified/70)

- To reset an individual filter, you have to select the first option from its dropdown menu, which corresponds to the name of the filter.  That's unintuitive UI design.  It would be better if the name of the filter appears *above* the dropdown, and the first option in the dropdown is `Any` which indicates that the filter is inactive.

- You can only choose between 10/20/30/40/50 entries per page.

- There's no way to bookmark previous filter views.

# Koinly

![koinly](https://user-images.githubusercontent.com/100738/109422615-368a6800-79d4-11eb-9ad7-b1b899cd1565.gif)

## Pros

- Probably the most intuitive UI of the three.

- Has a "Clear filters" button.

- Can sort chronologically in both directions, and by highest gains.

- Clearly groups transactions by day.

- Reasonably space efficient.  (Clicking on a transaction expands it and shows full detail in three separate tabs which is far superior and absolutely blows the competition away - but I'll save that for another time to avoid making this issue impossibly long.)

- The various elements of the filters are included in the query string of the URL in the browser window's address bar, so you can bookmark specific searches.

## Cons

- There's [no way to search for a transaction or specific item](https://discuss.koinly.io/t/ability-to-search-for-a-transaction-or-specific-item/534)

- There's [no way to filter by transfer direction](https://discuss.koinly.io/t/please-allow-filtering-by-transfer-direction/1686), e.g. to only see deposits into a given exchange

- Pagination is fixed to 10 entries per page.

- Searching for a wallet or coin is annoyingly sluggish.

See also this [thread where a user points out some ways in which Koinly's UI is not as good as CoinTracking](https://discuss.koinly.io/t/transaction-page-feature-requests/95).

# Proposed design

Based on the above analysis, I believe that Rotki's current 4-part History section should be replaced by a single view, which adheres to the following points in order to achieve a best-of-breed UX for filtering and navigating transaction history.

Firstly, it should provide the following two methods of filtering the transactions:

1. Dropdown menus which allows filtering by:

    - date range (ideally use something similar to the date pickers of Accointing / Koinly)
    - transaction type (e.g. deposit / withdrawal / internal transfer / swap)
    - transaction labels (e.g. airdrop / fork / income / mining / reward / gift / loss)
    - sender (wallet / exchange / staking pool etc.)
    - recipient (wallet / exchange / staking pool etc.)
    - whether the transaction was added manually

2. A multi-purpose search field which allows searching by:

    - transaction amount
    - transaction currency
    - transaction ID
    - blockchain network (e.g. selecting Ethereum would show not just ETH transactions but all ERC-20 etc.)
    - substrings within a comment on the transaction (where comments can be added manually to existing transactions, and/or imported via API if the source ledger already allows them)
    - advanced search syntax, just like CoinTracker and [GitHub search syntax](https://docs.github.com/en/github/searching-for-information-on-github/understanding-the-search-syntax) both allow.  This search syntax would be automatically populated when using the dropdown filters mentioned above, e.g. filtering by a particular sender would add something like `from:<wallet name>` to the search field.

IMHO these alone would be a huge improvement on what Rotki currently does.  However there are other things which could be added later on to make it even better:

- Provide some mechanism for saving searches for future reuse.  If the CoinTracker / GitHub design is used (i.e. populating the search field with advanced search syntax whenever a filter is applied via one of the dropdown filter menus), then the whole filter is described entirely by what's in the search field, in which case this could be done simply by adding a history dropdown to the search field to reuse previous queries.

- Allow manual edits on individual transactions, e.g. adding a comment to a transaction automatically created from an exchange API or from chain history.

- Allow batch operations on some/all of the displayed transactions.  For example, each transaction could have a checkbox on its left-hand side, so you could select a bunch of transactions by clicking their checkboxes and then perform some action on those.  In that case there could also be a checkbox at the top left of the header for selecting/deselecting all transactions.

- Allow customisation of which columns are visible.  For example some users will want to be able to add comments / descriptions to some of their transactions, in which case it should be possible to include this column in the list view.  Currently it seems that Rotki doesn't support this, so I guess that would come later.

- Allow CSV export of any filtered data set.

**Comment by LefterisJP** [comment]
As mentioned in discord thanks a lot for taking the time to write so many good info and feedack on things we can do to improve.
Will need to read it and digest it properly, so far only skimmed through it.

Do you think that from your actionable sugestions (2) is essentially what @isidorosp had also suggested here? https://github.com/rotki/rotki/issues/1219

Sounds similar.

**Comment by aspiers** [comment]
They're not too similar, I think. Both propose a multi-purpose search box, but this one is entirely focused on filtering transaction history whereas that one seems to be concerned more with providing a new way to navigate the whole app and give access to new features which don't exist yet, like price conversion.  Both have merit but I'd argue that omnibar-like navigation is more of a power user thing and not a very commonly used UI paradigm, so personally I would see that as lower priority especially given that it's already easy to navigate through the app.

In contrast pretty much everyone needs to be able to view transaction history, but there are many possible different use cases for that as shown by the list of examples I have, and currently Rotki only offers a limited set of ways to filter the transaction lists.

**Comment by LefterisJP** [comment]
All right so then I now understand that the powerful mult-purpose search box you envision is specifically for the history section

**Comment by aspiers** [comment]
Exactly, and the drop-down menus would mean that users don't need to learn the advanced search syntax unless they want to use it for more complex use cases. In this respect it would be quite similar to GitHub's approach to issue searching.

**Comment by kelsos** [comment]
Thanks for the detailed proposal @aspiers, I went quickly through it. I will need some time to digest and think about the ideas.

@LefterisJP this would probably be better done on a new endpoint, one that can directly support the filters and pagination.

**Comment by isidorosp** [comment]
I'm was not a fan of having split history into multiple sub-pages, but I understand the need for it based on the current backend/data structure design. 

I can't remember if I've mentioned this in a gh issue before or just via discord, but the way I have envisioned solving for issues like this (and around PnL reporting), and best long-term way to accommodate the various needs that will arise for this data, is to find a way to be able to:
a) open querying of the data to frontends in robust way (e.g. via GraphQL)
b) allow users to create and save (and eventually share within some sort of rotki plugin/module/market type ecosystem) their queries (and subsequent "reports")
c) generate "best-fit" UI elements based on the sort of data that's returned vs a specifically tailored UI (we can still have tailored UIs for the pages that the app ships with)

Obviously the way we are storing data right now is not in some sort of graph-friendly format, but I have seen potentially interesting tools that could be used to achieve something like this, e.g.:
https://github.com/bradleyboy/tuql
https://graphql-mesh.com/docs/handlers/tuql/

Essentially create some sort of layer on the backend that amasses the data and serves it in a robustly queriable way. This somewhat ameliorates the problem of having to restructure all of the backend data to some sort of new model (and to have to create yet another endpoint that we would have to maintain every time something in the underlying data changes), but adds the cost of having to design and maintain this new layer. It's obviously more complicated, would take longer, and a more long-term solution, but if we're talking about things that would set rotki apart from everything else I think this would place rotki in a class of its own from a user-driven  (and eventually community-driven) reporting capability. Eventually if you abstract and create a module out of the "tax algos", you could even combine the custom report module with a custom tax algo module whereby community members (or tax experts) could create, maintain, and possibly even sell via a rotki-marketplace, for different jurisdictions etc.

**Comment by aspiers** [comment]
Can you give an example of the kind of GraphQL query you envision?  It feels to me like the use cases I listed above would all be easily implemented with a simple SQL query on the existing SQLite backend:

    SELECT * FROM ledger_actions WHERE ...

where the `...` is replaced with whichever filter expressions are required by the search query typed in and/or constructed by selecting options from the dropdown menus I described above.  So I'm wondering if a GraphQL approach *might* be slightly overkill for implementing the proposal in this issue.  You wrote:

> Essentially create some sort of layer on the backend that amasses the data and serves it in a robustly queriable way.

but doesn't that already exist in Rotki?  Its SQLite backend should already allow all the queries required to implement this proposal.  Granted, it might require a `JOIN` of one or two other tables, but probably that wouldn't be hard to support either.

However if there are other use cases relating to querying of historical data which a GraphQL interface would fulfil more effectively, then I'd be very interested to hear your thoughts on those.

> Eventually if you abstract and create a module out of the "tax algos", you could even combine the custom report module with a custom tax algo module whereby community members (or tax experts) could create, maintain, and possibly even sell/exchange their "plugins" for different jurisdictions via a rotki-marketplace etc.

I agree, and in fact I think it was mentioned on Discord recently that the team are already thinking in this direction.  However please let's discuss that in a separate issue to avoid this one going off at a tangent ;-)

**Comment by isidorosp** [comment]
> Can you give an example of the kind of GraphQL query you envision? It feels to me like the use cases I listed above would all be easily implemented with a simple SQL query on the existing SQLite backend:
> 
> ```
> SELECT * FROM ledger_actions WHERE ...
> ```
> where the `...` is replaced with whichever filter expressions are required by the search query typed in and/or constructed by selecting options from the dropdown menus I described above.
>
> So I'm wondering if a GraphQL approach _might_ be slightly overkill for implementing the proposal in this issue. You wrote:
> > Essentially create some sort of layer on the backend that amasses the data and serves it in a robustly queriable way.
> 
> but doesn't that already exist in Rotki? Its SQLite backend should already allow all the queries required to implement this proposal. Granted, it might require a `JOIN` of one or two other tables, but probably that wouldn't be hard to support either.

I agree it's overkill if for _only_ this issue, but the point isn't to to set up a graphQL layer just for this specific use case (a history / all transactions dataset) but rather enable a user to query any piece of data from the rotki backend in an easy and consistent way. You can of course implement this specific issue as described with the backend functionality rotki currently has, but it's going to be complex and rigid. Like I said, this would be a longer-term solution to enable tackling a broader set of requirements, not immediately implementable and not limited in scope to this.

On a general note, there's a real non-trivial difference in how much easier it is for a user (and developer) to explore, traverse, and create queries for data via GraphQL than it would be if we just gave them an input box and asked them to build their own SQL queries, for many reasons but even simple things such as the out of the box tools that you can throw on top (e.g. a graphql explorer).

The question becomes how much time/effort do you want to spend implementing something for each specific issue as it comes up versus implementing something that in the long run allows you to more easily address these issues/requests but also gives you more possibilities. I recall having a conversation with the team where I was saying that History should just be one giant filterable data table and I was told that it didn't make sense to do it that way, and here we are.

> However if there are other use cases relating to querying of historical data which a GraphQL interface would fulfil more effectively, then I'd be very interested to hear your thoughts on those.
> 
> > Eventually if you abstract and create a module out of the "tax algos", you could even combine the custom report module with a custom tax algo module whereby community members (or tax experts) could create, maintain, and possibly even sell/exchange their "plugins" for different jurisdictions via a rotki-marketplace etc.
> 
> I agree, and in fact I think it was mentioned on Discord recently that the team are already thinking in this direction. However please let's discuss that in a separate issue to avoid this one going off at a tangent ;-)

Indeed it's not a novel concept, I remember discussing it with Lef sometime in spring last year as well and he had obviously already thought about it. Just pointing out how it all ties together. In my opinion this is where the real potential for rotki lies and probably the best route in terms of possible monetization as well.

**Comment by aspiers** [comment]
[**@isidorosp**](https://github.com/isidorosp) commented on [March 3, 2021 2:10 PM](https://github.com/rotki/rotki/issues/2469#issuecomment-789741127 "2021-03-03T14:10:45Z - Replied by Github Reply Comments"):
> I agree it's overkill if for _only_ this issue, but the point isn't to to set up a graphQL layer just for this specific use case (a history / all transactions dataset) but rather enable a user to query any piece of data from the rotki backend in an easy and consistent way. You can of course implement this specific issue as described with the backend functionality rotki currently has, but it's going to be complex and rigid. Like I said, this would be a longer-term solution to enable tackling a broader set of requirements, not immediately implementable and not limited in scope to this.

I see what you mean.

> On a general note, there's a real non-trivial difference in how much easier it is for a user (and developer) to explore, traverse, and create queries for data via GraphQL than it would be if we just gave them an input box and asked them to build their own SQL queries, for many reasons but even simple things such as the out of the box tools that you can throw on top (e.g. a graphql explorer).

Yes agreed - I've been really impressed by how incredibly easy the standard kind of GraphQL frontend can make exploring APIs.  For example, here's [a frontend for Uniswap V2 swap history](https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2).  The built-in completion and schema documentation gives an almost IDE-like experience to building a query, which is totally awesome.  Rotki's usefulness could maybe explode if this kind of interface was exposed.

> The question becomes how much time/effort do you want to spend implementing something for each specific issue as it comes up versus implementing something that in the long run allows you to more easily address these issues/requests but also gives you more possibilities. I recall having a conversation with the team where I was saying that History should just be one giant filterable data table and I was told that it didn't make sense to do it that way, and here we are.

Hrm interesting, because that's pretty much exactly what I'm effectively proposing in this history too (or at least, that would be the simplest way I can think of implementing backend support for the UI changes I'm proposing).  Would be good to hear from the team why it wouldn't make sense to do this.

> > I agree, and in fact I think it was mentioned on Discord recently that the team are already thinking in this direction. However please let's discuss that in a separate issue to avoid this one going off at a tangent ;-)
> 
> Indeed it's not a novel concept, I remember discussing it with Lef sometime in spring last year as well and he had obviously already thought about it. Just pointing out how it all ties together. In my opinion this is where the real potential for rotki lies and probably the best route in terms of possible monetization as well.

Yup, rather than thinking of Rotki just as a portfolio tracker desktop app, thinking of it as a full *platform* which happens to have its own frontend could result in some very interesting possibilities.

**Comment by pepawel** [comment]
+1 for adding transaction comment/description feature. It is a feature I like in Trezor Suite which makes it easier to understand transaction history. I would love to see it in Rotki.

**Comment by LefterisJP** [comment]
There is a lot of feedback in this issue but I think we should use it as the issue to go towards the unified history section we were discussin. Do you agree @kelsos ?

**Comment by kelsos** [comment]
Yes, it would make sense to use it for this purpose.

**Comment by LefterisJP** [comment]
I am closing this issue as it's now began. Will need to make spin-off issues for the things remaining to go into the unified history section. @yabirgb can you help?

1 for ledger actions
1 for all other exchanges except kraken
1 for manual trades

anything else?

**Comment by aspiers** [comment]
I've created https://github.com/rotki/rotki/discussions/8985 as a follow-up discussion suggesting some further improvements.
