### ISSUE TITLE
Support configurable blockchain explorers

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2472]
## Abstract

The default blockchain explorer for BTC is blockstream.info

I would like to be able to configure the explorer to another e.g. blockchair.com

## Motivation

Because I almost puked.

### Tasks
- [ ] Show the URL as alt when hovering over the link
- [ ] Add the ability to override the default explorer for each supported chain

**Comment by kelsos** [comment]
The motivation :rofl: 

It should require some minor effort but it should not be overly difficult to support.

**Comment by a7e8** [comment]
> The motivation 🤣
> 
> It should require some minor effort but it should not be overly difficult to support.

Just being honest!

**Comment by kelsos** [comment]
> > The motivation rofl
> > It should require some minor effort but it should not be overly difficult to support.
> 
> Just being honest!

Honesty is appreciated :+1:

**Comment by LefterisJP** [comment]
And then we should make it customizable also for ethereum, and the "soon" to come kusama transaction queries.

I understand the request though. I also find blockstream.info UI confusing. It's just the default requested by the user who requested the feature at the time.

So how should it be you think? Offer more selections only? Or also offer custom URL with the transaction hash/code being somewhere in the url? I think both would be cool @kelsos

**Comment by a7e8** [comment]
Whatever you do maybe put the domain into the alt text of the link so you can see where it is going before you click it?
