### ISSUE TITLE
Binance withdrawals don't include fees

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2475]
For all deposits to Binance the transaction fee is listed as zero. I could correct this by manually adding a ledger action, or adding a blockchain balance. However not all blockchains are supported.

Could Rotki take the txid for the asset and query the fee that was paid to make the deposit?

Should I add blockchain balances for the supported assets BTC, ETH and manually add ledger actions for the others?

**Comment by a7e8** [comment]
The Binance withdrawals in Rotki also don't include the fee which is listed in the CSV from Binance.

**Comment by a7e8** [comment]
That's great news it's supported now.

I think it's fine to keep this issue for withdrawal only.

To support deposits fees via the txid from the import you'd have to compare with txid's already tracked in Rotki. Do you want to create a separate issue for this?

**Comment by LefterisJP** [comment]
> To support deposits fees via the txid from the import you'd have to compare with txid's already tracked in Rotki. Do you want to create a separate issue for this?

By default if you have "gas costs" settings on all transactions gas fees are counted. So you can achieve this by activating that setting. And if you want to ignore some transactions from the history you can ignore them and their gas costs would not be included.

**Comment by a7e8** [comment]
> > To support deposits fees via the txid from the import you'd have to compare with txid's already tracked in Rotki. Do you want to create a separate issue for this?
> 
> By default if you have "gas costs" settings on all transactions gas fees are counted. So you can achieve this by activating that setting. And if you want to ignore some transactions from the history you can ignore them and their gas costs would not be included.

You currently only support 3 assets so looking up this information using the txid from Binance would help. All other transactions would have to be manual though. It's just an idea because if you have 100's of transactions and trades, one would like that the balance Rotki calculates at the end for that asset equals the actual balance.

**Comment by LefterisJP** [comment]
> You currently only support 3 assets so looking up this information using the txid from Binance would help

What do you mean by support 3 assets?

We are talking about the ethereum gas fee here, right? So always about ETH. And you want to detect how much ETH was spent as gas for the binance deposits? Then as I said above if you activate the gas cost to count those fees.

This should also reduce the ethereum amount as counted in the cost basis and accounting of what you should have now.
Or ... now that I look at it it should. But is not. Which means I need to push a fix.

**Comment by a7e8** [comment]
Sorry I was not clear - I'm was not talking about Ethereum.

I'm talking about all the other coins e.g. BCH that someone might add to Rotki which Rotki does not support natively like ETH or BTC.

`Could Rotki take the txid for the asset and query the fee that was paid to make the deposit?`
 - This means could Rotki take the txid from Binance and query a block explorer for that asset to get the deposit fee (for blockchains that Rotki doesn't support fully yet).

**Comment by a7e8** [comment]
Do you also need to apply the same cost basis fix (when fee is spent) for other transactions that are not ETH?

**Comment by LefterisJP** [comment]
> This means could Rotki take the txid from Binance and query a block explorer for that asset to get the deposit fee (for blockchains that Rotki doesn't support fully yet).

I now understand what you mean @a7e8. No that's unfortunately not possible for blockchains of which we don't handle transactions. And the only one we do now is ethereum. With soon to come also bitcoin and kusama.

**Comment by a7e8** [comment]
Yeah it was just a hopeful idea because the txid is in the data from Binance.

Perhaps you can allow edits of the entries that are imported so that we can manually add the fees? Otherwise you have two entries, one just for the fee component.

**Comment by LefterisJP** [comment]
> Perhaps you can allow edits of the entries that are imported so that we can manually add the fees?

That's a valid request. A bit more complicated than it sounds since we don't allow editing of any imported data at the moment but it can in theory be done to satisfy this use case. Can you make another issue for this and we keep this one for the specific issue of:

> Is it okay with you if we keep this issue for adding the binance withdrawal fee only? For deposits you can do what I suggested above as binance does not charge (or include in their api) anything extra for deposits.

**Comment by a7e8** [comment]
Sure https://github.com/rotki/rotki/issues/2482

**Comment by a7e8** [comment]
@LefterisJP @yabirgb this does not work. Fee shows as `0.00` for all Binance withdrawals.

**Comment by yabirgb** [comment]
@a7e8 For trades that were already at rotki before the 1.17.1 release fees won't change. Any other withdrawal from now on should have its fee stored. For the old trades to get updated the solution would be deleting the information and retrieve it again. The only way I know is going to the settings and deleting the information for binance. Is there any other way to do it @LefterisJP ?

**Comment by LefterisJP** [comment]
No this is the way. You have to purge and re-pull the information.

**Comment by a7e8** [comment]
Thanks @yabirgb @LefterisJP I can see the fees now!

However I got one small error:

```
ERROR rotkehlchen.exchanges.binance: Error processing a binance deposit/withdrawal asset_movement={'amount': 50, 'transactionFee': 0.65, 'address': '0x0', 'withdrawOrderId': '', 'addressTag': '', 'id': 'x', 'asset': 'MCO', 'applyTime': 1520624790000, 'status': 1}, error=Missing key entry for 'txId'.
```

**Comment by LefterisJP** [comment]
> Thanks @yabirgb @LefterisJP I can see the fees now!
> 
> However I got one small error:
> 
> ```
> ERROR rotkehlchen.exchanges.binance: Error processing a binance deposit/withdrawal asset_movement={'amount': 50, 'transactionFee': 0.65, 'address': '0x0', 'withdrawOrderId': '', 'addressTag': '', 'id': 'x', 'asset': 'MCO', 'applyTime': 1520624790000, 'status': 1}, error=Missing key entry for 'txId'.
> ```

Hmmm that's a first. Seems quite strage to have `id` instead of `txId`. They must have changed something ... again. Binance's API is the worst API we have ever worked with.

Can you make an issue about this one?
