### ISSUE TITLE
Custom location for user data directory

### ISSUE THREAD

**Issue by FrankvanCaspel** [rotki/rotki#2477]
I would love to be able to set a custom directory for the user data, as opposed to the standard data directory (%LOCALAPPDATA%/rotki/data on Windows). 

_Why?_
I want to have automated back-ups of my user data, and putting the data directory in a folder that is synced to my cloud realizes that. This could also tremendously simplify running Rotki on different devices, since the same userdata will automatically be available on both.

**Comment by LefterisJP** [comment]
>  would love to be able to set a custom directory for the user data, as opposed to the standard data directory (%LOCALAPPDATA%/rotki/data on Windows).

That is actually possible in the backend by using the `--data-dir` argument. We don't expose it in the frontend in an easy way though.

The only way I know of is [this](https://rotki.readthedocs.io/en/latest/usage_guide.html#set-the-backend-s-arguments) which is quite hacky and hard to use and probably not tested in a very long time.

@kelsos how do you think we could expose the change of data dir in rotki in a nice but also safe way? 

> This could also tremendously simplify running Rotki on different devices, since the same userdata will automatically be available on both.

We have a syncing mechanism for rotki data in the [premium](https://rotki.com/products/) user subscription which accomplishes that.

**Comment by kelsos** [comment]
We can have these options before logging in to the application, in the same way that we change the log level.

Other than the setting we also have to consider if it makes sense to also copy the data to the new directory.

**Comment by LefterisJP** [comment]
> Other than the setting we also have to consider if it makes sense to also copy the data to the new directory.

Thought about that and think no. Lots of things can go wrong. Perhaps let's just leave this to the user.

**Comment by LefterisJP** [comment]
Hey @kelsos I think this is fixed by fixing https://github.com/rotki/rotki/issues/1902 too. If I am misunderstanding something please reopen.

**Comment by kelsos** [comment]
Yes, with #1902 this should be fixed indeed.
