### ISSUE TITLE
Remember UX setting for 'rows per page' on Dashboard

### ISSUE THREAD

**Issue by FrankvanCaspel** [rotki/rotki#2481]
On the dashboard you can set the number of rows that should be displayed per page in the table of assets:

![afbeelding](https://user-images.githubusercontent.com/17382771/109720682-af431d00-7baa-11eb-878c-5af7f9f44b90.png)

Unfortunately this setting resets every time one navigates away from the dashboard. Pretty minor thing this, but it would be nice if the setting were remembered.

**Comment by isidorosp** [comment]
@FrankvanCaspel I think this is a double of https://github.com/rotki/rotki/issues/2427; if so, please close.

**Comment by FrankvanCaspel** [comment]
Ah yes, apologies. Closed!
