### ISSUE TITLE
No user feedback if saving snapshot task fails

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2483]
## Abstract

If the task to save the snapshot (either the automatic one or the "Force Save" one) fails for whatever reason, let's say an unhandled exception there is an entry in the error logs but there is no user feedback. No messages sent via the `msg_aggregator`.

## Task

The task retrieval should show either success or failure, when the frontend queries for the task. So I think the frontend should be able to show a message when either the saving balances snapshot from "Force Save" or the scheduled one fails.

**Comment by kelsos** [comment]
@LefterisJP I am guessing that this is not a frontend issue since it includes the `msg_aggregator` should I update the issue to indicate this is a backend issue?

**Comment by LefterisJP** [comment]
> The task retrieval should show either success or failure, when the frontend queries for the task. So I think the frontend should be able to show a message when either the saving balances snapshot from "Force Save" or the scheduled one fails.

I was thinking more of a message in the UI. But can also be a message by the msg_aggregator. Have not thought of this issue in detail yet.

**Comment by kelsos** [comment]
I am also adding the backend label since we need to provide a way for the backend to notify the frontend when the snapshot fails.

**Comment by LefterisJP** [comment]
We can do so probably via websockets?

**Comment by kelsos** [comment]
Certainly, that would make sense.

**Comment by LefterisJP** [comment]
Backend part done by https://github.com/rotki/rotki/pull/3680

Now need frontend + changelog. So assigning to @kelsos
