### ISSUE TITLE
Create a proper deserialize_ethereum_address() function

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2486]
## Abstract

It's missing. https://github.com/rotki/rotki/blob/ff9138a796287e8eac7dfb3fa2b03700c657fb51/rotkehlchen/serialization/deserialize.py#L677-L683

## Task

Do it and replace all the places where we got something like:

```python
try:
    to_checksum_address()
except ValueError as e:
        raise DeserializationError(
            f'Invalid ethereum address
        ) from e
```

with that function

**Comment by vnavascues** [comment]
Putting some examples:

**deserialize_ethereum_address() that calls to_checksum_address()**

A trivial replace of the whole [try...except](https://github.com/rotki/rotki/blob/develop/rotkehlchen/chain/ethereum/modules/balancer/utils.py#L66) block with this new function. The function `deserialize_bpt_event` expects/supports `DeserializationErrror`.

Maybe a [non-trivial replacement](https://github.com/rotki/rotki/blob/127f68eb3e8bd0ee190d24796509ab599a5b2b4d/rotkehlchen/chain/manager.py#L814). Here we should check how a `DeserializationError` is handled in the chain of function calls. The `modify_blockchain_accounts`  doscstring does not specify "DeserializationError" among the expected exceptions, so we must be careful. An strategy could be be catching the `DeserializationError` and raising a `RemoteError` (a common pattern in other places).

**deserialize_ethereum_address() that deals with annotation**

This [deserialize_ethereum_address](https://github.com/rotki/rotki/blob/develop/rotkehlchen/tests/unit/test_balancer.py#L15) call has to be replaced with [string_to_ethereum_address](https://github.com/rotki/rotki/blob/develop/rotkehlchen/chain/ethereum/typing.py#L15). Not only is not receiving a string (that represents an address) from an external API (but in our test suite), but also the string is an already checksum address. The purpose of this `deserialize_ethereum_address` call is just to avoid code duplication adding the right annotations.
