### ISSUE TITLE
Add support for $NIF token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2492]
Please add support for $NIF token.

Contract 0x7e291890b01e5181f7ecc98d79ffbe12ad23df9e

https://www.coingecko.com/en/coins/unifty

https://unifty.io/
https://twitter.com/unifty_io
https://t.me/unifty

Tags: NFT, Multichain
Supported Chains: ETH+BSC+xDAI+Matic+Celo

**Comment by vnavascues** [comment]
Done @adrien-be. Thanks for the details!
