### ISSUE TITLE
 Add support for $PGT token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2493]
Please add support for $PGT token.

Contract 0xeaccb6e0f24d66cf4aa6cbda33971b9231d332a1

https://www.coingecko.com/en/coins/polyient-games-governance-token

https://www.polyient.games/
https://docs.polyient.games/
https://www.polyient.io/ - company behind polyient games - an investment group focused on virtual economies
https://dex.polyient.games - NFT focused DEX+AMM - by polyient games
https://www.nftmarketcap.io - by polyient games

note that there is also $PGU from the same project - its a dual token mechnism

**Comment by vnavascues** [comment]
Done @adrien-be
