### ISSUE TITLE
Add support for $RARE token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2497]
Please add support for $RARE token.

Contract 0x93dfaf57d986b9ca77df9376c50878e013d9c7c8

https://www.coingecko.com/en/coins/unique-one

https://www.unique.one
https://twitter.com/UniqueOne_UO
https://uniqueone.medium.com/
https://app.subsocial.network/@uniqueone
https://discord.gg/q9WUgQKShx
https://t.me/unique_one_rare
https://www.instagram.com/uniqueone_ou/
https://github.com/Unique-One-Official

**Tags**: NFT
**Multi-chain**: Ethereum, xDAI and Sora Network (Polkadot)

**Comment by vnavascues** [comment]
Done @adrien-be
