### ISSUE TITLE
Add support for $FOTO token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2498]
Please add support for $FOTO token.

Contract 0xF6eA0E60cee427B90aA36f327eE61d1d4CABC49F

No Coingecko page yet.

$FOTO is the token for Unique.Photo, a project by Unique.One - c.f. [this issue re. Unique.One](https://github.com/rotki/rotki/issues/2497)

https://www.unique.photo/
https://uniquephoto.medium.com/
https://twitter.com/UniquePhoto_
https://t.me/joinchat/GyLiwIyId0CS19_2

**Tags**: NFT
**Multi-chain**: Ethereum, xDAI and Sora Network (Polkadot)

**Comment by vnavascues** [comment]
@adrien-be unfortunately this token does not have data in coingecko nor cryptocompare. Better wait until it is available and we will add it.

**Comment by adrien-be** [comment]
it is now on Coingecko

https://www.coingecko.com/en/coins/unique-photo
