### ISSUE TITLE
 Add support for $AUDIO token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2504]
Please add support for $AUDIO token.

Contract 0x18aaa7115705e8be94bffebde57af9bfc265b998

https://www.coingecko.com/en/coins/audius

The only open-source, open-data audio streaming platform
The best part? 99% of people would have no clue it’s built on blockchain rails.

**Live** since Oct 2020
3M users per month - https://dashboard.audius.org/#/analytics

https://audius.org --> for crypto investors
https://audius.co --> for users
https://medium.com/audius
https://twitter.com/AudiusProject
https://discord.gg/ah5CcqW
https://www.instagram.com/audiusmusic/
https://reddit.com/r/audius

**Comment by LefterisJP** [comment]
This is already in our assets list. Please check if something exists before opening an issue: https://github.com/rotki/rotki/blob/b28603ce998b6bf2d2bbc2ee0f91c45a1d2d57c7/rotkehlchen/data/all_assets.json#L908
