### ISSUE TITLE
Add backlink to beaconcha.in page in daily eth2 validator stats page

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2506]
## Abstract

Since the data is taken from their service a backlink is the least we can do.

## Task

Would probably make sense to have each validator index in the validator index column of the table be a link to the the equivalent stats page. For example for validator index `58958` link to: https://beaconcha.in/validator/58958/stats

**Comment by kelsos** [comment]
That sounds reasonable. Since this is in the premium component part we can just have a patch deployment. It should be easy to do.

**Comment by LefterisJP** [comment]
This is already done thanks to @kelsos
