### ISSUE TITLE
Eth Validator not picking up data

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2509]
The eth validator tab doesn't bring up any info. Balance appears on main page though

**Comment by LefterisJP** [comment]
Hey @Blackswan122 what do you mean by not picking up any data?

Is it continuously loading? Is there any error? Either in the logs or in the UI?

**Comment by LefterisJP** [comment]
Scratch the above. I can reproduce. This is due to upcoming changes in v1.15.0. But it should not have affected v1.14.2. We will fix it.

**Comment by Blackswan122** [comment]
Ok thanks

**Comment by LefterisJP** [comment]
This should now be fixed. Make sure to restart rotkito pick the change up.

Again apologies for causing this during the preparation for v1.15.0.

We have @kelsos to thank for the very swift response on a Sunday no less!

**Comment by Blackswan122** [comment]
Thanks it works again. 

Use my referral link https://platinum.crypto.com/r/m1gq5iu3zf to sign up for Crypto.com and we both get $50 USD :)
