### ISSUE TITLE
Back button needed on some screens (asset detail)

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2515]
## Abstract

There are some screens that can be reached from multiple places e.g. asset detail.

I think it would be useful to include a small back button when in these screens.

## Motivation

Because it feels like it's missing and there's no back button.

**Comment by LefterisJP** [comment]
Good point. I am not sure how hard/easy this is. @kelsos will let us know when he is back.

**Comment by kelsos** [comment]
It shouldn't be hard I guess. You can still go back if you have a 5 button mouse btw.
