### ISSUE TITLE
Binance: $FTT token wrongly identified as FarmaTrust token

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2517]
$FTT token is FTX token https://www.coingecko.com/en/coins/ftx-token

But in Rotki, $FTT is identified as FarmaTrust token https://www.farmatrust.com/

There are cases where two tokens have the same name. They should easily be identified properly nonetheless thanks to the different contract addresses.

Thanks guys for correcting this.

**Comment by LefterisJP** [comment]
What do you mean wrongly identified? We support both:

- Farmatrust: https://github.com/rotki/rotki/blob/1dd5ba9feb8aa81d6b5a5e177a2802aa25e01c3e/rotkehlchen/data/all_assets.json#L5339

- FTX: https://github.com/rotki/rotki/blob/1dd5ba9feb8aa81d6b5a5e177a2802aa25e01c3e/rotkehlchen/data/all_assets.json#L5349

**Comment by adrien-be** [comment]
Because it shows a Farmatrust tokens balance when actually I hold FTX
tokens.

Note that it's from Binance. So maybe it's an issue with Binance API.

**Comment by LefterisJP** [comment]
> Note that it's from Binance. So maybe it's an issue with Binance API.

That's the hint I needed. I now understand what your problem is. And this is the common problem of having tokens with the same symbol across different locations. You need mappings. Since addresses are not anywhere in exchanges. We will fix this.

**Comment by adrien-be** [comment]
Awesome. Thx!
