### ISSUE TITLE
Support Polygon (Matic) layer 2 network

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#2526]
[Polygon](https://polygon.technology/) (formerly [Matic Network](https://matic.network/)) is a layer 2 protocol network for Ethereum which is rapidly gaining adoption.  For example, [Quickswap](https://www.coingecko.com/en/exchanges/quickswap) is a Uniswap fork running on Matic which at the time of writing is [the 18th largest DEX by volume](https://www.coingecko.com/en/dex); however if you exclude all the layer 1 DEXes and PancakeSwap / BurgerSwap which are on BSC (which is not truly decentralised), and Pangolin which is on Avalanche network, then I think it's the most popular layer 2 DEX, or at least in the top 2 or 3.  Given the problems with high gas fees on L1, I expect the popularity of L2 solutions like this will probably grow exponentially.

So it would be great if Rotki supported this network.  This issue can serve as an initial placeholder for tracking the enhancement in case anyone wants to discuss it or start research on how the implementation could be done.  Perhaps the Polygon team would even be willing to issue a grant for someone to work on this.  Either way, this issue could be edited to spec out the work in more detail, like how it's already been done in #1081 for Polkadot/Kusama.

Tokens can be transferred to/from Ethereum mainnet to Matic via https://wallet.matic.network/.

BTW I see that [Zerion has just added support for tracking balances on Matic](https://twitter.com/zerion_io/status/1367528734148886528), so it's technically feasible :-)

**Comment by LefterisJP** [comment]
Really want to havethis too.

But just nore, all these are really big features. Want to support them but we are at our capacity limit. Would have hoped for more external help since we are open source but so far seems it's not happening as much as I hoped.

> BTW I see that Zerion has just added support for tracking balances on Matic, so it's technically feasible :-)

Means nothing unfortunately. With loopring for example they had a special API key for them only with querying super powers which they got through some kind of deal with loopring. We can't have such keys in opensource software as it's public.

Will have to talk with people from Matic/Polygon to see how this can be implemented. Or .... ideally someone from there can just come and write the appropriate module.

**Comment by aspiers** [comment]
Here's [the API docs for getting ERC20 balances via their `matic.js` library](https://docs.matic.network/docs/develop/maticjs/api-reference#balanceOfERC20).

Also their ["Getting Started" section of the docs](https://docs.matic.network/docs/develop/maticjs/getting-started) states the need for a private key for signing transactions, but it doesn't say whether that is optional if you only want to perform read-only operations.  I imagine it *should* be optional but they might have a misguided hardcoded assumption in there that you are going to submit transactions, in which case we could file a bug and/or PR to fix that.

**Comment by WyseNynja** [comment]
Thankfully, Matic is pretty much just Ethereum with different consensus code. Your existing code for connecting to an Ethereum node RPC should be able to talk to the Matic RPC without much change at all. That's how Zerion was able to do it so easily. No proprietary API keys should be needed.

**Comment by adrien-be** [comment]
+1

Related: [issue #2765 "Support Aave on Matic"](https://github.com/rotki/rotki/issues/2765)

**Comment by krupawan5618** [comment]
Just food for thought: another platform that is showing promise with swift integration of multiple L2 solutions is [Debank](www.debank.com). I understand that querying APIs can be a bottleneck in implementation, and I am curious as to how this platform does it.

**Comment by LefterisJP** [comment]
> Just food for thought: another platform that is showing promise with quick integration of multiple L2 solutions is Debank ([www.debank.com](http://www.debank.com)). I understand that querying APIs can be a bottleneck in implementation, and I am curious as to how this platform does it.

Probably same way we will do it. Querying polygon's APIs. But we also may allow user to connect to own polygon node.

As for how does debank or any such centralized platform implement something ... that's a nice question. They are centralized, closed source and proprietary. So no way to know. :smile:

**Comment by adrien-be** [comment]
You can always ping their CTO or Lead Dev on Twitter. You may get a
pleasant surprise :)

**Comment by refex** [comment]
Super noob here. Metamask is able to show balance from Polygon network and it's of course oos. Hopefully their code has some useful insights.

**Comment by hamzahkhan** [comment]
We would love to support this by all means - can we put up a grant for this in an upcoming hackathon? 

cc @LefterisJP @aspiers

**Comment by aspiers** [comment]
Probably preaching to the choir here, but it's interesting to note the growth of Polygon since I first submitted this issue:

- Quickswap has risen from the 18th largest DEX by volume to the 10th largest.
- Sushiswap is now on Polygon and this variant is the 11th largest DEX by volume.
- Two of the top nine sitting above these two are based on BSC, and the other seven are on Ethereum L1.
- The combined daily volume of Quickswap and Sushiswap on Polygon is around $355m, which is more than 1inch, and if a single DEX would place it behind only Mdex BSC, Uniswap, PancakeSwap, and Sushiswap.
- The [current list of dApps etc.](https://awesomepolygon.com/) is pretty impressive.

Until rollups pick up steam, Polygon is probably the most formidable Ethereum sidechain.

**Comment by LefterisJP** [comment]
> We would love to support this by all means - can we put up a grant for this in an upcoming hackathon or gitcoin?
> 
> cc @LefterisJP @aspiers

@aspiers you are indeed preaching to the choir :smile:  Problem is lack of resources at the moment.

> We would love to support this by all means - can we put up a grant for this in an upcoming hackathon or gitcoin?

Hey @hamzahkhan hello! Are you from polygon? The best way to help us here would be if you can find people who would be willing to tackle this without too much hand-holding and maybe even work in our team more long-term. We are hiring also!

**Comment by aspiers** [comment]
@LefterisJP Totally understand. My motivation for mentioning was not to try to persuade you of anything, since I know you are already working at 200% speed on lots of amazing stuff ;-) but just in case at some point you are faced with a decision of whether to prioritise Polygon support above or below other features, maybe this data would help decide one way or the other.

**Comment by guizkane** [comment]
+1

**Comment by luxumbra** [comment]
Would absolutely love to see Polygon support.

**Comment by yabirgb** [comment]
Polygon rpc https://polygon-rpc.com/

**Comment by PabloCastellano** [comment]
Hello. I have started working on this issue from scratch, assuming noone has already started -> https://github.com/rotki/rotki/pull/4725

I'm new to rotki development but I feel like I'm making progress. Any comments are welcome!

**Comment by positonic** [comment]
Let me know if you need help with this, even if only for testing

**Comment by LefterisJP** [comment]
> Let me know if you need help with this, even if only for testing

Hey @positonic, this we are scheduling for 1.29. It's probably really easy for a team member to do as the ground has been laid with the Optimism integration.

**Comment by positonic** [comment]
I'm curious as to why there is an 'ethereum', 'evm' and 'optimism' folder?

<img width="236" alt="image" src="https://github.com/rotki/rotki/assets/10499048/c3593532-ac67-4d82-86c0-6492c7c5b593">

@LefterisJP You mentioned elsewhere that this should be done as optimism has been done, but I'm wondering why all EVM chains can't be treated equivalently?

**Comment by LefterisJP** [comment]
This is done and included in 1.29.

**Comment by positonic** [comment]
Super cool, I'm excited to check it out.... ❤️
