### ISSUE TITLE
Transfer all usage information from release notes to documentation

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2527]
## Abstract

Our documentation is horribly outdated. At the same time we do put considerable effort in having a guide of all new features with screenshots and all in each release's release notes. So we should at least go through all release notes and move all information that is not outdated and is missing from the documentation to the usage guide.

## Task

- [ ] Go through all release notes (most recent first) and move all information that is not outdated and is missing from the documentation to the usage guide

**Comment by yabirgb** [comment]
Closed by https://github.com/rotki/rotki/pull/2717
