### ISSUE TITLE
Asset manager, underlying tokens % always displays under the amount

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2532]
## Problem Definition

Seems like an easily reproducible frontend glitch. Does not seem to depend on size. It always happens. As can also be seen by the screenshot below (where there is ample space between address and amount)

![2021-03-09_23-26](https://user-images.githubusercontent.com/1658405/110546680-19217080-812f-11eb-84a9-33de5cd0b473.png)

## Task

Fix it by making the percentage always display on the right side of the amount.

**Comment by kelsos** [comment]
Notes: 
- Happens on editing not on adding
- the address table seems to overflow

**Comment by LefterisJP** [comment]
Should be fixed by #2546
