### ISSUE TITLE
aCRV token amount shown is double the actual amount

### ISSUE THREAD

**Issue by alifier** [rotki/rotki#2534]
## Problem Definition

The Aave interst bearing CRV tokens are twice the amount shown on the Aave platform or the Etherscan. I think problem started around version V1.14.1

### System Description

Operating system: macOS BigSur
Rotki version: V1.15.0

**Comment by alifier** [comment]
On a related note, I was wondering why aCRV is not here?
https://github.com/rotki/rotki/blob/develop/rotkehlchen/chain/ethereum/modules/aave/common.py

**Comment by LefterisJP** [comment]
By checking it seems that aCRV is only a v2 token. So that's the reason it's not there. The aave module is only for v1. We have not supported v2 yet for deposits/lending/liquidations.

As for the double counting let me have a look.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/2543
