### ISSUE TITLE
Ledger actions from before the requested PnL report period are not counted

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2541]
## Problem Definition

If a user tries to create a PnL report of a certain time period, and that period contains assets whose cost basis was calculated thanks to Ledger Actions from before the time period then this cost basis is not seen.

The reason for this is .... :drum: this line: https://github.com/rotki/rotki/blob/4fd6c0d734d38223f6cc4cf5e0d145da263e3208/rotkehlchen/history/events.py#L131

`start_ts` should be 0, so that all ledger actions are processed, not just the ones inside the query period. Essentially same behavior with all other history event types.

## Task

- [ ] Fix it
- [ ] Write a test for it. A simple one suffices. Add 2 history events. A ledger action giving you 100 ETH at time `X`. A sell of ETH for EUR at time `X + 5`. Do a PnL report from time `X+3` and see that the cost basis is calculated correctly.

**Comment by yabirgb** [comment]
I'm not sure about how to create the test. Since I have to add a sell event I need to work with the `accountant` module and call `accounting_history_process`?

**Comment by yabirgb** [comment]
I'm a bit confused with the test here. Since I need to add the assets movements I'll need to work with the `accountant` (I haven't seen how to do this using `rotkehlchen_api_server`). But to generate the PnL in the range I believe I need to call the `rotkehlchen_api_server` and ask for the history... Is there another way to do this? Using both fixtures creates an error with duplicate accounts

**Comment by LefterisJP** [comment]
You are right to be confused. I did not specify the test nicely in the issue.

I think a unit test of the corresponding function here would be sufficient:

https://github.com/rotki/rotki/blob/8833d0f327a3039cf338d20af03951738f4a0d49/rotkehlchen/history/events.py#L116-L136

Just make sure that it returns ledger actions before the from_ts.

I don't think this is possible to be tested in any other way since we don't test the `EventHistorian::get_history()` anywhere else. The accounting tests take specific history.
