### ISSUE TITLE
Provide in-app help on how to find the coingecko/cryptocompare ids

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2547]
## Abstract

Provide a way for users to get information on how to find the correct coingecko/cryptocompare ids inside the application

## Motivation

Easy access to the information

https://rotki.readthedocs.io/en/latest/contribute.html#get-cryptocompare-asset-identifier

### Task

- Provide a small description with a link to the documentation

**Comment by A2be** [comment]
Two bits of feedback from trying to use the new feature and the v1.15.0 UX:

1) the red-boxed text in the graphic that @LefterisJP provided in the #support channel on Discord earlier today includes the `/` before the text that Coingecko uses in the "identifier".  But it is unclear if the `/` is really required.  (I put it in, as specified in the red box, but Rotki did not seem to "take" i all in and find my tokens.)
2) it is also unclear how a Rotki user would find out what the answer is to the Rotki test question:  "Number of decimals?"

**Comment by kelsos** [comment]
For the decimals and other basic token information a new backend endpoint will be added: https://github.com/rotki/rotki/issues/2574

This way the frontend will query this information automatically for the user.
