### ISSUE TITLE
Rotki.com: Google Tag Manager (GTM) tracker invoked on website

### ISSUE THREAD

**Issue by lukemulks** [rotki/rotki#2562]
## Problem Definition

I observed that there's a third party Google Tag Manager (GTM) tracker that is invoked from the rotki.com webpage. 

![rotki-shield](https://user-images.githubusercontent.com/8979240/111041039-13f04a00-83eb-11eb-906a-9e5db3d738b1.jpg)

Specific request in question: 
`https://www.googletagmanager.com/gtag/js?id=UA-9200591-4`

Would suggest removing this, as it may confuse users that are coming to Rotki for the Privacy. We flag it in Brave, and while some ad blocking extensions have whitelisted GTM, those that do not will flag as a tracker (because it technically is a 3P tracker).

Also, lesser known by most, but GTM permits for custom code execution as a feature, and there have been many reported incidents of abuse from this vector. Definitely not accusing of any foul play here, but am opening the issue because I care about your mission and because the vector has been abused in other contexts, on other sites. 

Keep up the good work. We need more apps that care about Privacy. 
### System Description
Observed in Brave Nightly Channel v1.23.36 on Windows OS

Operating system: 
Rotki version:

**Comment by LefterisJP** [comment]
The website is not really part of our everyday work and was written years ago.

It is undergoing a re-write but really slowly as we don't really have any resources.

Let me have a look @lukemulks and will see what this is. If it's some stray tracker left in the code it will be removed asap.

**Comment by lukemulks** [comment]
Awesome - some site templates embed this mess by default, often without presenting that fact in an intuitive way to the site owner.  

Happy to help validate if you remove and would appreciate a second set of eyes on it.

**Comment by LefterisJP** [comment]
Hey @lukemulks I did find a tracker in the website template and removed it. I think this was nobody's fault but mine though. I probably followed some kind of tutorial years ago when making the website and copied too many things without thinking.

I think it's gone for me. I am also a brave user as you know. I love your product :)

If you can confirm the removal feel free to close the issue.

![2021-03-13_20-39](https://user-images.githubusercontent.com/1658405/111042151-31013900-843c-11eb-90b3-c7993556b180.png)

**Comment by lukemulks** [comment]
Excellent! 

Confirming that all looks good from this end. Closing out and moving forward! Cheers.
![rotki-clean](https://user-images.githubusercontent.com/8979240/111042286-8a904600-83f1-11eb-8ee2-b6f6543ae6e2.jpg)
