### ISSUE TITLE
Documentation button in the toolbar

### ISSUE THREAD

**Issue by bloxster** [rotki/rotki#2564]
## Abstract

Add a "**?**" button on the toolbar taking to the readthedocs documentation.

## Motivation

The documentation on readthedocs it's really well done and should be more easy to reach for a better UX.

## Specification

Could be in the account menu or a button next to the notification bell.

**Comment by isidorosp** [comment]
We discussed in discord that accessing the docs is possible via the `Help -> Usage Guide` menu, but bloxster found that this was a little difficult to find. I don't see why adding a "?" button to the toolbar wouldn't work (we could even make it hideable if we want in the frontend settings).

**Comment by LefterisJP** [comment]
I think the problem here is how the main menu is rendering very differently in MacOS from all other OSes also.
