### ISSUE TITLE
Can't see the Balances of PPAY, YLD, FXF, DOWS, ERN, BONDLY

### ISSUE THREAD

**Issue by discovolantex** [rotki/rotki#2565]
Having added the Metamask Account but can't see the balances of PPAY, YLD, FXF, DOWS, ERN, BONDLY

**Comment by LefterisJP** [comment]
Hello @discovolantex. We will try to add autodetection of those in the next releases. We first have to complete a few technical prerequisites: https://github.com/rotki/rotki/issues/2551

But until then you can also simply add them to your token list manuallly. To check how look at v1.15.0 release notes section on "Customization of the list of supported assets": https://github.com/rotki/rotki/releases/tag/v1.15.0
