### ISSUE TITLE
Add support for XRT

### ISSUE THREAD

**Issue by Luxaedel** [rotki/rotki#2567]
Please add support for the XRT token (whether that's manual balances or automatic)

Contract: 0x7de91b204c1c737bcee6f000aaa6569cf7061cb7

Coingecko: https://www.coingecko.com/en/coins/robonomics-network
Site: https://robonomics.network/

**Comment by LefterisJP** [comment]
Hey @Luxaedel thanks a lot for the issue. We will add automatic detection in the next major release. But until then you can also do it yourself if you use rotki >-= v1.15.0.

We added the ability to add custom ethereum tokens.

Check the release notes for details on how to achieve this: https://github.com/rotki/rotki/releases/tag/v1.15.0

**Comment by Luxaedel** [comment]
Hi there @LefterisJP. I'm using v1.15.0 :) and I did read the patch notes, but I suppose I skipped over the adding custom ethereum tokens bit. Will have another look! Thanks :)
