### ISSUE TITLE
Staking Polkadot on ledger

### ISSUE THREAD

**Issue by TheWanderer1983** [rotki/rotki#2570]
## Abstract
Staking  Polkadot via Ledger live visible in Rotki.

## Motivation
I'm currently staking  Polkadot via ledger live wallet. I would like to see this is rotki with interest for tax purposes.

**Comment by LefterisJP** [comment]
Hello @drgonzo31 this is two very very different feature requests.

Can you edit this one to be for either Cosmos or Polkadot staking and make another one for the other?

**Comment by LefterisJP** [comment]
Superseded by https://github.com/rotki/rotki/issues/6615. Staking in Ledger Live is same as staking via their stakign dashboard. It's all on-chain and can be tracked by rotki.
