### ISSUE TITLE
Add a new async endpoint to query erc20 information

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2574]
## Abstract

To make it easier to add ERC-20 tokens we need a new endpoint to auto-detect any basic information that exists for the added token.

The endpoint will return the following fields if they exist.
- name
- symbol
- decimals

This way the frontend can automatically fill in this information for the user.

**Comment by yabirgb** [comment]
Etherscan has the endpoint to provide information about a token marked as a PRO feature so I will check for other ways to obtain this info

https://etherscan.io/apis#tokens
