### ISSUE TITLE
Rotki failed to start

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#2577]
## Problem Definition

Rotki failed to start
first time it has ever had this problem

`Rotki failed to start
There is a problem with the backend.
Open an issue in Github and include rotki_electron.log and rotkehlchen.log. The backend's output follows below:`

## Logs

[[15848] Failed to execute script rotkehlchen-script

Traceback (most recent call last):
  File "rotkehlchen-script.py", line 2, in <module>
  File "rotkehlchen\__main__.py", line 38, in main
  File "rotkehlchen\server.py", line 55, in main
  File "rotkehlchen\api\server.py", line 309, in start
  File "site-packages\gevent\baseserver.py", line 336, in start
  File "site-packages\gevent\pywsgi.py", line 1545, in init_socket
  File "site-packages\gevent\server.py", line 180, in init_socket
  File "site-packages\gevent\server.py", line 192, in get_listener
  File "site-packages\gevent\server.py", line 288, in _tcp_listener
  File "site-packages\gevent\_socketcommon.py", line 563, in bind
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('127.0.0.1', 4242)
Rotki API server is running at: 127.0.0.1:4242
]()

### System Description

Operating system: Win10
Rotki version: v1.15.0

**Comment by LefterisJP** [comment]
That means another instance of Rotki (or something else) is running at that port.

Make sure no other instance is running.

@kelsos perhaps we can improve on this error, and maybe just use other ports.

**Comment by A2be** [comment]
Ack.  That makes sense.  
Just checked and I had forgotten to shut down the Rotki I opened yesterday.

Would probably be a good idea to detect that for the user and just tell 'em to close one of their instances.

**Comment by kelsos** [comment]
> That means another instance of Rotki (or something else) is running at that port.
> 
> Make sure no other instance is running.
> 
> @kelsos perhaps we can improve on this error, and maybe just use other ports.

There is a port checking mechanism in place that doesn't seem to work on anything but linux.

**Comment by LefterisJP** [comment]
So what do you think we should do about this issue? Simply close it? Or is there any way to detect another rotki is running in Windows and Macos?

**Comment by kelsos** [comment]
> So what do you think we should do about this issue? Simply close it? Or is there any way to detect another rotki is running in Windows and Macos?

Keep it open so I can have a look at what happens on macos/windows maybe I can change something?

**Comment by LefterisJP** [comment]
Should be fixed by #2589
