### ISSUE TITLE
Remove log anonymization setting (backend + frontend)

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#2584]
## Problem Definition
 In Rotki Settings/General Settings, one setting is "Should logs be anonymized?"
 
 I learned recently in the Rotki Discord that logs cannot be completely anonymized.
`you can't ofuscate/anonymize the data. We started an attempt to do thatwith the setting you mentioned but it's too hard to achieve properly. This is one of the main reasons logs are OFF by default`

`most probably for all chains account numbers will be visible. API keys not`

The problem with this is that **with the way the setting is specified, the implication is that _Debug logs CAN BE anonymized_.**

This is an incorrect belief about the security of user data, and should not be transmitted to Rotki users.

### Suggested change
update the front end UI around Settings/General Settings/"Should logs be anonymized?"

- perhaps do it with an info icon that helps explain what Lefteris said in the Discord
- or, perhaps change the UI text to "Should logs be partially anonymized (some identifying information will always be passed)?"

## Logs

UX problem; no logs needed

### System Description

Operating system: Win10
Rotki version: v1.15.0

**Comment by LefterisJP** [comment]
We discussed this in the standup and we will simply just remove this functionality all together.

**Comment by A2be** [comment]
Sounds like a good option.

Will def avoid the implied view that anonymization can happen.
