### ISSUE TITLE
Take Balancer pools join/exits into account in the PnL report for premium users

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2597]
## Abstract

This is the same issue as https://github.com/rotki/rotki/issues/1756 but for Balancer

## Task

Do it

**Comment by LefterisJP** [comment]
This has not been done yet @yabirgb right?

**Comment by yabirgb** [comment]
@LefterisJP no, needs action

**Comment by LefterisJP** [comment]
is this now done via #8944 ?

**Comment by LefterisJP** [comment]
Okay so this should be don with #8994
