### ISSUE TITLE
Balance save snapshots do not save "0 amount" balances, which can cause unexpected behavior in API calls and reporting

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#2613]
## Problem Definition

Basically when a token has a 0 balance/amount, no entry for it is saved during the balance snapshot (this makes sense as you wouldn't want to save a "0" entry for all possible tokens in every snapshot). However, in the cases where a token previously had a balance, that was maybe then sold / transferred / swapped / whatever, there _should_ be a 0 balance saved for any subsequent saves, otherwise you get confusing things in the premium statistics graph, e.g.:

What it looks like:
![image](https://user-images.githubusercontent.com/27592/111897945-25f16e80-8a23-11eb-8128-c783fe19ecf8.png)

What it should look like:
![image](https://user-images.githubusercontent.com/27592/111897950-28ec5f00-8a23-11eb-8c20-3872a4233fc0.png)

One way to fix this is obviously to build balances based on historical transactions, but since this is very far away, in the interim two possible fixes are:
* When saving token balances, if a token has previously had balances > 0, it should save a 0 balance for that token
* Don't save zero balances, but when retrieving token balances, if a token has previously had balance > 0, it should create and return "virtual" 0 balances for any dates after that (until there is a >0 balance again)

Personally I find the top method preferable because I don't like putting "virtual balance logic" in the queries as opposed to in the data itself (i.e. if you implement the 2nd method and then go look at the balances in the db, or try to create a new call at some point in the future, you will have to remember that some of these 0-token balances are virtual).

## Logs

Not needed, verified by Lefteris in discord

### System Description

Operating system: Win10
Rotki version: 1.15.1

**Comment by LefterisJP** [comment]
I will try to take this up and see how it could be done.

**Comment by LefterisJP** [comment]
Hey @isidorosp this was trivial. Went with 

> Don't save zero balances, but when retrieving token balances, if a token has previously had balance > 0, it should create and return "virtual" 0 balances for any dates after that (until there is a >0 balance again)

Since (1) it's easier, (2) does not inflate DB size and (3) will work for all our users from next patch release, no need to create new zero data from now on.

**Comment by isidorosp** [comment]
Sounds good!

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/3542
