### ISSUE TITLE
Please add PNG and ELK from Avalanche Network

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2618]
PNG Pangolin DEFI and ELK Elk Finance are becoming relative on Avalanche Network. Both were airdrops to Avalanche network.Would it be possible to have them added?

**Comment by LefterisJP** [comment]
Sure we will! From next version. Also next version you too will be able to add any custom assets, not only custom ethereum tokens!

**Comment by LefterisJP** [comment]
Note ELK: was not added since it's neither on coingecko or cryptocompare.
