### ISSUE TITLE
Unable to add manual trades involving custom ethereum tokens

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2629]
## Problem Definition

Users are currently unable to include custom ethereum tokens in manual trades. If either one of the pair is a custom token the addition fails

### Example with both tokens being custom

![2021-03-23_11-44](https://user-images.githubusercontent.com/1658405/112134908-81f7f680-8bcd-11eb-9a4e-9313a7f036c8.png)

### Example with 1 token being custom

![2021-03-23_11-44_1](https://user-images.githubusercontent.com/1658405/112134988-96d48a00-8bcd-11eb-9270-4b844c91a426.png)

## Task

Fix it. This is a backend problem which should be fixed at the pair creation time. Another possible fix is to completely remove pair as part of trades. As described in this issue: https://github.com/rotki/rotki/issues/2243

**Comment by yabirgb** [comment]
Failing to query historical/current prices in oracles for assets is enough to block the trade creation?

**Comment by LefterisJP** [comment]
no. This is due to the custom token pair. This will be handled by the work I am doing (I hope)

**Comment by LefterisJP** [comment]
This is fixed in develop
