### ISSUE TITLE
Asset not displaying name in value distribution at statistics 

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2632]
## Problem Definition

I added a custom token to my list of assets and if I review statistics, the name I've chosen is not displayed but the tag
used

![image](https://user-images.githubusercontent.com/5068010/112140871-df437600-8bd4-11eb-8568-9a14e6e74612.png)

### System Description

Operating system: Linux. App Image
Rotki version: 1.15.2

**Comment by LefterisJP** [comment]
Hey @yabirgb, yeah this is a know issue, that needs an upgrade of premium components. Do we have an issue for this already @kelsos ?

**Comment by kelsos** [comment]
From a quick search I can't find something. I will proceed with a fix for that.

**Comment by kelsos** [comment]
@yabirgb can you tell me which graph was it I can see that we did some fix in one of the graphs?

**Comment by yabirgb** [comment]
@kelsos `VALUE DISTRIBUTION BY ASSET`
