### ISSUE TITLE
Tax free period accounting setting does not upgrade until restart

### ISSUE THREAD

**Issue by dannypernik** [rotki/rotki#2647]
## Problem Definition

I hope I'm wrong, but to my unqualified eye, it seems that taxable trade profit/loss is being calculated incorrectly for me. Specifically, the fact that my sale of 1 ETH at $1777.77 adds 0 to `taxable_amount` - when I've had no purchase of ETH for anywhere near that $ amount - concerns me. Am I missing something here? Relatedly, I'm unclear as to the definitions of "General Trade Profit/Loss" and "Taxable Trade Profit/Loss". Happy to share my CSV export if it helps.

### System Description

Operating system: MacOS Big Sur 11.1
Rotki version: v1.15.2

**Comment by LefterisJP** [comment]
Hello @dannypernik! Thanks for using rotki and opening an issue.

There can definitely be bugs in many parts in the code naturally, but from the data you are providing there is no way to debug this. The profit/loss report just calculates results from the data it's fed .. so we would need to know a lot more information as to what data you fed it.

Admittedly our docs need a lot of work and improvements but have you read this section? https://rotki.readthedocs.io/en/latest/usage_guide.html#creating-a-profit-loss-report. It explains some of the concepts. Anything that is unclear please give us feedback to explain it or even open a pull request in the [usage guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) yourself and improve it!

My first uneducated guess would be that you probably have not modified your accouning settings at all and the tax free period of 1 year is on. So the sell is of ETH bought more than a year ago and it's not considered taxable.

For sharing data and/or easier QnA also make sure to join our discord: https://discord.gg/aGCxHG7

**Comment by dannypernik** [comment]
Thank you for the prompt reply, @LefterisJP ! Out of curiosity, is there one place in the code where calculations are defined in the data fields? One easy way to aid understanding would be to add a link to this code in the usage guide. If you can provide the link, I'd be happy to add it to the docs if that would be useful!

As far as my calculation goes, I can confirm that I did edit the tax free period to 0 days. I'll share my export with you on Discord, but that link says "Invite expired". 
![image](https://user-images.githubusercontent.com/3347095/112555643-93d8c580-8d96-11eb-90d8-60da1af2fc9a.png)

**Comment by LefterisJP** [comment]
> Thank you for the prompt reply, @LefterisJP ! Out of curiosity, is there one place in the code where calculations are defined in the data fields? One easy way to aid understanding would be to add a link to this code in the usage guide. If you can provide the link, I'd be happy to add it to the docs if that would be useful!
> 
> As far as my calculation goes, I can confirm that I did edit the tax free period to 0 days. I'll share my export with you on Discord, but the page you linked says "Invite expired".
> 
> ![image](https://user-images.githubusercontent.com/3347095/112555643-93d8c580-8d96-11eb-90d8-60da1af2fc9a.png)

Hello Danny, the code changes fast for any link in the docs to make sense. In the docs we explain what each field is.

As I mentioned in the other thread, this is our never-expiring discord link. It seems to work for others. Could it be something on your side? What's your discord username?

It would be really great if you can make discord work as it would help us chat in a quick manner and share data. Otherwise you can always email support@rotki.com

Apart from the export I would also need you to set rotki to debug mode and send the logs: https://rotki.readthedocs.io/en/latest/contribute.html?#id2

By reading the logs you can also see what rotki does. It's a lot of info in there.

**Comment by dannypernik** [comment]
You're right, I'm now in Discord. Will send you logs there.

**Comment by dannypernik** [comment]
@LefterisJP I believe I've found the specific issue. When I turn off the tax free period, the setting does not update unless I log out. See screenshots below. Interestingly, when I turn the tax-free period on, it updates without a logout.

![image](https://user-images.githubusercontent.com/3347095/112712093-19459e00-8e9b-11eb-8dc8-22822c7592b1.png)
![image](https://user-images.githubusercontent.com/3347095/112712141-7ccfcb80-8e9b-11eb-9a8d-925f2fb8ece8.png)

Happy to send you logs on Discord if you could point me to them for the iOS version. I could not find the help button or logs directory mentioned in the docs.

**Comment by yabirgb** [comment]
Hello @dannypernik ! I have not been able to reproduce the error where you have to logout. Has it happened to you again? Is there any special sequence of steps you took to get this error?

**Comment by dannypernik** [comment]
Hi @yabirgb I was able to reproduce the error. I logged into Rotki, reset the tax free period to 365 days, and logged out. I logged in, ran a PnL report, and got the following (expected) result:

<img width="855" alt="Screen Shot 2021-04-14 at 9 20 17 PM" src="https://user-images.githubusercontent.com/3347095/114805795-3c13f580-9d69-11eb-8946-f5dd3f1dbac7.png">

I then changed the tax free period setting to 0 days, reran the report, and got the following (unexpected) Taxable PnL result:

![image](https://user-images.githubusercontent.com/3347095/114805883-62d22c00-9d69-11eb-98ef-6a71958dcf5a.png)

**Comment by LefterisJP** [comment]
Hey @dannypernik I can confirm and reproduce what you described. It's being fixed in https://github.com/rotki/rotki/pull/2755 and will be included in the upcoming v1.16.0
