### ISSUE TITLE
Support Minimal/Factual Export of the Profit/Loss

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#2659]
## Abstract

Today, the profit losses can be exported as CSV. The export is nice, complete and contains a lot of data.
Some of this data is however not based on facts but also contains Rotki interpretations. While this is great for personal archival, that may not be what a user wants to share while sending a tax report.

## Motivation

Having a 'factual' export would allow guarantying the user that the information is 100% correct and free of interpretation from Rotki, which btw is also based on settings defined by the user. So Rotki could be wrong (bug), but the user could be wrong, resulting on erroneous data produced by Rotki even without any flaw in the Rotki code.

Surely, the current exports can be reduced manually (ie some columns can be removed/hidden) but a factual export (containing less data) would be convenient.

## Specification

The export content is the same than the current report but with many columns reomved.
That would probably leave only (to be confirmed):
- source / exchange
- date
- currency / crypto FROM
- currency / crypto TO
- amount in unit
- amount in EUR

Of course an option would also be to let the user define a custom report and let her/him specify which of the columns to export.

**Comment by chevdor** [comment]
It does in the direction. To be honnest, the main issue I have with the current export (that you should keep in any case) is that I dont feel sending all the data "as is" to a tax office and have to explain about what means colums such as virtual, etc....

So I would prefer to shoot them the facts and let them draw their conclusions. If we disagree, we can then compare the calculations.

I am note sure exactly what the differences regading "Rotki processing" is between this issue/feature and the outcome of #630.

**Comment by LefterisJP** [comment]
The outcome of #630 is just the trades/events/defi stuff. Not processed. No profit/loss calculation. Just the raw data.

Also other things, such as all owned accounts e.t.c. (but in separate exports).

It want to help against locking the user in rotki. So that users can also move their data elsewhere if they so desire. But it can have the same effect you ask for here.

**Comment by LefterisJP** [comment]
I will close this in favor of #630 because as I understand this is asking for a data export of everything without actual processing.
