### ISSUE TITLE
Etherscan and LedgerLive shows different Eth amount than Rotki

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2663]
One of my Blockchain Balance accounts shows 0.47 eth on Etherscan and ledgerLive but 0.59 on Rotki....all synced?

Operating system: Windows 10
Rotki version: Latest

**Comment by a7e8** [comment]
I think part of this might be that Rotki includes the ETH held in a MakerDAO vault?

**Comment by LefterisJP** [comment]
Closing this as non-actionable due to lack of information

**Comment by Blackswan122** [comment]
Sorry I forgot about this... agreed closed.
