### ISSUE TITLE
Connect to Gemini Exchange with Master API Key

### ISSUE THREAD

**Issue by Bwvolleyball** [rotki/rotki#2669]
## Problem Definition

Unable to use a Gemini Master API key with Rotki to view more than 1 trading account in Gemini

## Logs

Failed to query gemini balances: Gemini API request failed. Gemini query at https://api.gemini.com/v1/balances responded with error status code: 400 and text: {"result":"error","reason":"MissingAccounts","message":"Expected a JSON payload with accounts"}

### System Description

Operating system: Docker
Rotki version: 1.15.2

### Additional Descriptions:

I have 2 sub accounts in Gemini, for 2 different reasons, so the only way to see all these balances in Rotki would be to either support a Gemini master API key (which requires the account name passed on all requests), or the ability to configure more than one instance of Gemini in Rotki 😁

**Comment by LefterisJP** [comment]
Hey @Bwvolleyball I think that the real solution here would be to support multiple accounts/api keys per exchange. So I would say that once https://github.com/rotki/rotki/issues/47 is implemented your problem will be solved.

Closing this as a "kind of duplicated" to that issue.

**Comment by Bwvolleyball** [comment]
Thanks for the feedback! Sorry for the duplication 😅

Sounds good to me!

As a workaround to anyone else who finds this, I just made a second Rotki account on my local install.

I can't crunch the numbers from both Gemini accounts at once, but at least I can crunch the numbers on both accounts in some fashion 🙂
