### ISSUE TITLE
Add option to treat ledger actions of type "Expense" as a sell

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#2673]
## Abstract

Currently the user has no way to add arbitrary crypto expenses (like buying a car, buying a NFT, buying something other then a coin) and have it accounted as a "sell".

## Motivation

The user can use Rotki for more accounting cases and also add things manually that are not yet supported.

## Specification

We discussed that in the chat. The idea was to add an option wether expenses are treated as sells. In my opinion, this should be the default.

**Comment by LefterisJP** [comment]
Hey @coinyon trying to organize old issues a bit. I think that with the first iteration of changes coming in v1.24.0 this is going to be the default behaviour for all ledger action expenses, so I am closing this.

**Comment by coinyon** [comment]
Ok great. I'll have a look at it once it is released and reopen the issue if necessary.
