### ISSUE TITLE
Coinbasepro can no longer import all trades

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#2674]
## Problem Definition

My coinbasepro trades are not imported correctly / ignored.

## Logs

1)
```
2021-04-04 22:27:52 ERROR Failed to deserialize a coinbasepro trade. Check logs for details. Ignoring it.
2021-04-04 22:27:52 ERROR Error processing a coinbasepro trade. raw_trade={'id': '..., 'product_id': '...-EUR', 'profile_id': '...', 'side': 'buy', 'funds': '...', 'specified_funds': '...', 'type': 'market', 'post_only': False, 'created_at': '...', 'done_at': '...', 'done_reason': 'filled', 'fill_fees': '...', 'filled_size': '...', 'executed_value': '...', 'status': 'done', 'settled': True}, error=Missing key entry for 'size'.
```

~2)~

**Comment by LefterisJP** [comment]
Coinbase and coinbasepro are completely different apis. So the two should not be related. For (2) perhaps you can speak with @yabirgb who wrote that part. I think he made the assumption a conversion has to have two ids.

For (1) that's strange. Let me have a look. My trades worked fine.

**Comment by coinyon** [comment]
Yea I saw that, this isssue is for Coinbasepro now. I added a comment to #1007

**Comment by LefterisJP** [comment]
All right should be easy enough. Can you test a mini PR to tell me if it fixes the problem for you?

```
Param | Description
-- | --
price | Price per bitcoin
size | Amount of base currency to buy or sell
time_in_force | [optional] GTC, GTT, IOC, or FOK (default is GTC)
cancel_after | [optional]* min, hour, day
post_only | [optional]** Post only flag
``

**Comment by coinyon** [comment]
Yep can do

**Comment by yabirgb** [comment]
Yes, conversions are not properly covered in the API and as @coinyon mentioned in the original issue (and as I could verify myself) conversions have two transactions of type `trade`, both needed to get the all the information about the conversion. 

Tomorrow I'll check if something is special with this trade.

As per the issue with coinbasepro I believe is something different. The most recent change there only skips entries without a date.

**Comment by LefterisJP** [comment]
So @coinyon for CoinbasePro can you check this PR: https://github.com/rotki/rotki/pull/2675

I think, am not sure, that the market trades don't have the `size` key, but do have the `filled_size` key. Can you confirm? Also if you have any limit orders can you check they work fine with this change? To check make sure to purge your DB of coinbase pro history or else it won't be re-queried.

**Comment by coinyon** [comment]
> Missing key entry for 'price'.

There is no `filled_price`, maybe the price has to be calculated from `executed_value`

**Comment by LefterisJP** [comment]
@coinyon their docs are terrible can you give me an example failing entry and tell me exactly what trade you expect it to be? 

If you see a missing key entry for price then that's really strange as it's not supposed to ever be optional
