### ISSUE TITLE
Add support for Fei & ILV

### ISSUE THREAD

**Issue by ericmeltzer** [rotki/rotki#2676]
please add both of these coins. I'm a premium user, that entitles me to some kind of priority attention for this annoying request? I think?

Thanks! I love rotki and would love to support it more than just the yearly fee

**Comment by LefterisJP** [comment]
Hello Eric. We will add them in the new release if you can give me coingecko links. Symbols alone are ambiguous.

As for priority in feature requests, yes indeed requests from premium users are prioritized as opposed to free ones. But, at the same time most of our requests are from premium users, so at that point we just go with the number of people asking for something.

This particular request is easy to handle, so no worries. Just give me the coingecko links to have them in the issue.

**Comment by coinyon** [comment]
And TRIBE as well as you are at it please. It is the DAO token for FEI.

* https://www.coingecko.com/en/coins/fei-protocol
* https://www.coingecko.com/en/coins/tribe

**Comment by ericmeltzer** [comment]
https://www.coingecko.com/en/coins/illuvium

thanks @LefterisJP !

**Comment by ericmeltzer** [comment]
out of curiosity, why not just add 100% of the coins that gecko supports?

**Comment by LefterisJP** [comment]
> out of curiosity, why not just add 100% of the coins that gecko supports?

Adding a new token is not as simple as querying coingecko. There is alot of mapping and metadata (e.g. how it's translated in each exchange -- that need to be maintained)
