### ISSUE TITLE
Profit & Loss Report Generation Error

### ISSUE THREAD

**Issue by osirisprince** [rotki/rotki#2707]
## Problem Definition

After connecting all my exchanges and blockchain wallets, I attempted to run a Profit and Loss Report but received the following error:
**Profit and Loss Report Generation
The report generation was not possible due to an error
An unexpected response was received while generating the profit and loss report. This might indicate an issue with the generation mechanism. Please check the logs for any error messages (you might have to enable debug logging first) and create an issue.
The backend query task died unexpectedly: 'NoneType' object has no attribute 'endswith'**

## Logs

Please see logs attached

### System Description

Operating system: Windows 10
Rotki version: 1.15.2

[rotkehlchen.log](https://github.com/rotki/rotki/files/6289041/rotkehlchen.log)
[rotki_electron.log](https://github.com/rotki/rotki/files/6289042/rotki_electron.log)

**Comment by LefterisJP** [comment]
Hey @osirisprince thanks for the issue. It is a known issue for v1.15.2 and it's fixed in the upcoming release v1.16.0. When it's ready you can download it and the problem should go away.

https://github.com/rotki/rotki/issues/2633

**Comment by osirisprince** [comment]
Awesome. Thanks! When can we look forward to that new release?

**Comment by yabirgb** [comment]
@osirisprince We are working tirelessly to get it out but we can't give an exact date. Our intention is at some point this month.
