### ISSUE TITLE
TRB contract upgrade

### ISSUE THREAD

**Issue by bloxster** [rotki/rotki#2710]
Tellor Tributes (TRB) has changed contract.

Solution: cancel (or ignore) contract 0x0ba45a8b5d5575935b8158a88c631e9f9c95a2e5 and monitor only new contract  0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0

Source: [TRB Migration - 
How to guide for holders](https://medium.com/tellor/trb-migration-fd8ebe320b02)

**Comment by LefterisJP** [comment]
Hello @bloxster thanks for the issue! We will keep it open and track the new contract too in the new release.

For you information you can actually already add it as a manual token addition as explained in the v1.15.0 release notes: https://github.com/rotki/rotki/releases/tag/v1.15.0

And if the swap did not destroy the old tokens you can ignore the old contract by putting the asset in the ignored assets:  https://rotki.readthedocs.io/en/latest/usage_guide.html?#ignored-assets

**Comment by bloxster** [comment]
Hello LefterisJP,
I added the new TRB but hiding the old one also hides my balances on exchange, so to have everything ok i'll wait for the fix. 
Fine with that, thank you for putting it in the next release!
