### ISSUE TITLE
Unsupported asset a3CRV with address 0x… encountered during DeFi protocol queries

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2714]
## Problem Definition

The [aave](https://curve.fi/aave) pool on Curve is not supported by Rotki.

## Logs

```
Unsupported asset a3CRV with address 0x… encountered during DeFi protocol queries
```

**Comment by LefterisJP** [comment]
Will add it in v1.16.0 but we also need to add detection for all of the missing ones as per: https://github.com/rotki/rotki/issues/2456. The latter will happen a bit later though since v1.16.0 is already overdue.

**Comment by a7e8** [comment]
> Will add it in v1.16.0 but we also need to add detection for all of the missing ones as per: #2456. The latter will happen a bit later though since v1.16.0 is already overdue.

You da best

**Comment by LefterisJP** [comment]
> > Will add it in v1.16.0 but we also need to add detection for all of the missing ones as per: #2456. The latter will happen a bit later though since v1.16.0 is already overdue.
> 
> You da best

I am kind of biased here as I also use it :smile: 

![2021-04-15_00-00](https://user-images.githubusercontent.com/1658405/114785969-b2baee00-9d7d-11eb-8371-5b738337b28e.png)


FYI, until it's added you can also add the aTokens you got in there as a manual balance so your overall balance is correct, and once we can properly detect it delete the manual balance entry.

**Comment by a7e8** [comment]
So you add each of the 3 aTokens as a manual balance and then update each time you open Rotki?

I was also adding my Uniswap LP just as a USD balance until it's supported.

**Comment by LefterisJP** [comment]
> So you add each of the 3 aTokens as a manual balance and then update each time you open Rotki?

I don't need that much accuracy. I just added aDAI (since I only made 1 aDAI deposit into the pool). But since they are stablecoins and close to their peg you can keep it simple and add one only (but with the proper amount)

**Comment by LefterisJP** [comment]
Ah this is not done yet. Needs work on the rotki repo too.
