### ISSUE TITLE
Change date to epoch in database sync conflict payload

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2722]
## Problem Definition

When there is a database sync conflict the payload contains the two databases dates as dates instead of epochs.
We should change this to return the epoch and introduce the required changes on the frontend so that it respects the user-specified format. 

> Note: Check if we actually have access to this format at the time.

### Task
Convert it to epoch

**Comment by LefterisJP** [comment]
Hey @kelsos you mean this payload?

```python
        return SyncCheckResult(
            can_sync=CanSync.ASK_USER,
            message=message,
            payload={
                'local_size': data_bytes_size,
                'remote_size': metadata.data_size,
                'local_last_modified': timestamp_to_date(our_last_write_ts),
                'remote_last_modified': timestamp_to_date(metadata.last_modify_ts),
            },
        )
```

**Comment by kelsos** [comment]
@LefterisJP yes, this is it we just need to remove the timestamp_to_date and pass the ts directly to the frontend, so I can handle it directly on the frontend instead.

**Comment by LefterisJP** [comment]
All right @kelsos. So the backend part should be as simple as that then: https://github.com/rotki/rotki/pull/3113

**Comment by LefterisJP** [comment]
Assigning the issue to you @kelsos  for the frontend part. Needs to be done for v1.19.0 since the backend is already changed.
