### ISSUE TITLE
Extract SQLCipher and pysqlcipher building to different repo

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2740]
## Problem Definition

We have pinned versions of SQLCipher, and pysqlcipher that we use.

The build of SQLCipher happens on every build, docker, windows, macos, linux, arm64.
Since we use pinned versions we should create a new repo that builds sqlcipher for all the supported OSes/architectures and maybe publishes the wheels/packages to PyPI

We only need to build these dependencies when there is a change in version, otherwise there is no need to build them every single time since this increases the build times everywhere and complicates the windows development part.

Ideally, it would be nice to include SQLcipher in the python package to make things easier

### Task
- Create a separate repo to handle the building and publishing

**Comment by LefterisJP** [comment]
Changed the title after chatting with @kelsos. He knows what needs to be done and will update the description.
