### ISSUE TITLE
Feature: User should be able to see which accounts a crypto asset is spread to

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#276]
## Abstract

In the dashboard the user can see how much of a particular crypto asset they hold. But at the moment it's not possible to know which accounts these assets are spread to if they are on-chain.

## Motivation

As a user I would like to be able to see across which accounts a particular coin is spread.

## Specification

- Right clicking on an asset on the general dashboard should provide a context menu which will give the user the option to go to the asset's detail
- Going to the asset details will take you to a new page with more information on the particular asset.
    - As this is a new page more info will be added in the future but for now (and for the scope of this issue) most important would be a list of accounts (on-chain and on-exchanges) which hold that asset and how much they hold

**Comment by thibauld** [comment]
+1 I would love to be able to do that too.
