### ISSUE TITLE
Support Aave on Matic

### ISSUE THREAD

**Issue by 0xadri** [rotki/rotki#2765]
Aave is going multichain, starting with Matic. It now has over an Aave-Matic market over $650M worth.

I understand that it cannot be done until issue #2526  "Support Polygon (Matic) layer 2 network" gets solved.

Maybe Aave can help provide more manpower in solving both tickets.

**Comment by LefterisJP** [comment]
Hey @adrien-be thanks a lot for the issue.

Definitely need to support multiple L2s. But I guess the architectural challenge is to support each individual L2 first. Then doing the L2 integration with each DeFi protocol should be easy. So indeed the challenge here is #2526 and the main step to take,
