### ISSUE TITLE
Think on how to handle asset database updates when app already started

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2769]
## Abstract

When the app is running and at the beginning we show the assets update dialog there is an ugly race condition.

The app fires up and starts querying but the user is also going through an assets update. If they start and go through with it then the assets DB will be modified while the balance queries are running.

This may cause lots of funny behavior which will be fixed only once the app restarts. We have to think on how to avoid this.

## Specification

Decide on a way to avoid this and spec it out here.

Potential methods:

1. Force restart the app once the asset database has been updated. (Maybe heavy handed but should work)
2. Wait until the entire asset update process is skipped/finished to start any queries. This may still cause problems if anything is started/worked on by the backend unilaterally but most of the potential problems will go away.

**Comment by LefterisJP** [comment]
Hmmm @kelsos isn't this a non-issue anymore?

> Force restart the app once the asset database has been updated. (Maybe heavy handed but should work)

This is what we are doing.

I don't remember exactly what I meant when I made the issue, but I assume this is what I meant and since we do that I will close it. Let me know if I am missing something obvious.

**Comment by kelsos** [comment]
Yes, that is what we do. Maybe we meant something else, but since it is not clear anymore closing the issue seems reasonable.
