### ISSUE TITLE
Solana price lookup is wrong.

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#2770]
I think you already fixed this SOL lookup for Coingecko but its also wrong when using crypto compare price feed and I just found this out.

if I switch price feed from Coingecko to cryptocompare, it does the price lookups about 100x as fast, but it also gets SOL wrong (and shows it as 1/10th of the actual price)

thanks

-- Jez

**Comment by yabirgb** [comment]
Hello @JezSan ! By any chance your solana comes from binance?

**Comment by JezSan** [comment]
In this case, originally it was bought on binance, but right now the SOL entry in the portfolio is solely as an external balance (because its held in cold storage)

**Comment by JezSan** [comment]
On crypto compare, the Solana coin is

https://www.cryptocompare.com/coins/sol/overview/USD <https://www.cryptocompare.com/coins/sol/overview/USD>

And currently worth approx $36 each.

Whereas you may be mapping to a different coin that also starts with SOL in it, and seems to be worth about $3.

I’ve had a look, on crypto compare and there’s a lot of them so it could easily be mapped to the wrong one.  And I can’t figure out which one it is.

**Comment by LefterisJP** [comment]
Hey @JezSan Can you open the Assets view and give us a screenshot of the SOL entry? Everything is now modifiable by the user so you can fix all these yourself and as such we want to make sure what is what here.

**Comment by yabirgb** [comment]
I couldn't find why the price is the wrong one but indeed our cryptocompare id for this one seems wrong. As Lefteris said you can edit your list of assets and fix this for you. Go to `Manage Assets` > Search for Solana > Click on the pencil for edit > Change cryptocompare for `SOL`

**Comment by LefterisJP** [comment]
As discussed in the standup @yabirgb please add an asset update for Solana in the next assets update for users who won't do this  fix on their own.
