### ISSUE TITLE
Support Uniswap v2 USDC/ETH LP in Dashboard

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2771]
## Problem Definition

The Uniswap v2 LP for USDC/ETH shows in the DeFi section of Rotki but it does not appear at all in the Dashboard.

Contract address: https://etherscan.io/token/0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc

## Logs

n/a

### System Description

Operating system: macOS
Rotki version: 1.16.0

**Comment by LefterisJP** [comment]
Hey @a7e8 this is not specific to that LP token but all of them. The issue is here: https://github.com/rotki/rotki/issues/1744
