### ISSUE TITLE
Blockchain explorer customisation should support all assets

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2772]
## Abstract

Great work on being able to customise the blockchain explorer!

However it's not possible to update this for BCH. In fact there is not even a default for Bitcoin Cash so the links just don't work.

## Motivation

I can't think of a good reason to limit this to the 4 assets that it is currently. Perhaps Rotki should also hardcode some defaults for assets in the top 20 of https://www.coingecko.com/ at least.

## Specification

n/a

**Comment by kelsos** [comment]
Hey @a7e8 

Could you be more specific about which links do not work?
Btw the blockchain explorer customization is not asset-specific, it is blockchain-specific.

**Comment by LefterisJP** [comment]
Closing due to lack of input from submitter. Feel free to add more information and I will reopen again.
