### ISSUE TITLE
Error processing kraken trade -- float timestamp

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2773]
## Problem Definition

I saw this on one of my test accounts. Starting happening today but can't be related to v1.16.0 since Kraken always returned integer timestamps. So they must have changed something on their side.

## Logs

{'ordertxid': 'XXXX', 'postxid': 'XXX', 'pair': 'XXBTZEUR', 'time': 1619057345.6829, 'type': 'buy', 'ordertype': 'limit', 'price': '44196.00000', 'cost': '47.09835132', 'fee': '1.98354', 'vol': '0.00106567', 'margin': '0.00000', 'misc': ''}, error=Failed to deserialize a timestamp entry from a <class 'float'> entry in kraken

## Task

Fix it. Must from now on also account for floating point timestamps in Kraken

**Comment by yabirgb** [comment]
I don't know why the issues are not being closed when the PR are merged as always...

**Comment by LefterisJP** [comment]
@yabirgb it's because the change that has the "fix NUMBER of issue" is still not in develop. No worries. Once bugfixes gets merged to develop it will be. Our main branch is develop. This is how github determines when a bug is fixed.
