### ISSUE TITLE
Better integrate the module support with account addition

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2778]
## Problem Definition

Find a way to better integrate the module filtering for addresses with the account addition.
The scenario is when a user has already a few selected addresses for example on Uniswap and they add a new account. This account will not be queried for Uniswap trades and there is no clear indication anywhere that
the user has to manually go and add allow the account querying for uniswap trades.

Find a way to better integrate the account addition with allowing the addition of the address queried addresses for a module assuming that the module is not whitelisting all the addresses.

### Task
TBD

**Comment by kelsos** [comment]
@LefterisJP if you have any ideas in regards to that please fill in

**Comment by LefterisJP** [comment]
I think that we need to have some kind of list of addresses that are queried at each protocol's UI page.

It does not need to show all, as it may be big. Can be truncated and pressing it would take you to the actual settings page to edit it.

I guess the problem we solve here is to always remind the user that a subset of addresses (unless it's the default of all) is queried so that they may not blame missing data on rotki.

**Comment by yabirgb** [comment]
What I would expect as user will be something like in this image where by default my selected modules are activated in this screen for the account and if I want I can edit this list. Adding this option here makes clear that this account will have the selected modules. Also if the default behavior by default is all deactivated this list can start being empty and before clicking save some modules can be selected
![proposal](https://user-images.githubusercontent.com/5068010/115928524-85a9c200-a486-11eb-9fe2-80b6014c52e8.png)

**Comment by LefterisJP** [comment]
but this would only be for adding new accounts. What about your already existing accounts?

**Comment by kelsos** [comment]
> but this would only be for adding new accounts. What about your already existing accounts?

We also have the issue about showing the queried accounts that you mentioned above, but these are two different things
