### ISSUE TITLE
GoChain coingecko id is wrong

### ISSUE THREAD

**Issue by evilny0** [rotki/rotki#2779]
I believe the coingecko id for GoChain is wrong in the assets configuration. It's set to "tron-go", however it should be "gochain". TRON GO is another project.

**Comment by yabirgb** [comment]
Hello @evilny0 ! Thanks for letting us know, we will update this for the next release. If you haven't yet you can update this asset just for you from the list of assets https://rotki.readthedocs.io/en/latest/usage_guide.html#customization-of-the-list-of-supported-assets
