### ISSUE TITLE
Windows version on the website

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2785]
## Problem Definition

If an user goes to the [rotki.com](rotki.com) page an tries to download the windows version, what is downloaded is the backend only and not the full application.

**Comment by LefterisJP** [comment]
Oh that sucks. @kelsos can you make a quick fix and I will deploy it? I think would be faster if you check it yourself.

**Comment by LefterisJP** [comment]
Couldn't wait and leave this open. Fixed it. The website should now be pointing to the correct windows binary.

**Comment by kelsos** [comment]
Ok, thanks for letting me know. I didn't turn on the computer at all yesterday, I was going to have a look now.
