### ISSUE TITLE
Support FTX subaccounts

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2786]
## Abstract
A user has requested in discord the support for FTX subaccounts. 

## Motivation

A user might have several accounts in FTX but only want some of them to be rotki for different reasons. 

## Specification

To make this possible we need to add make it possible for an user to assign a name or a set of names to a FTX exchange account.

Since for https://github.com/rotki/rotki/issues/47 we are undergoing a rework of how exchanges works it might be interesting to add the option for adding an alias to the different instances of the exchanges and this way we might cover some users.

For users with many FTX subaccounts a better solution has to implemented. Maybe something like in the multiple ETH account addition where we process addresses separated by `,` and then internally store this information in a special column.

Just to make it clear to query FTX subaccounts we need to know the names that the provided key can query.

**Comment by LefterisJP** [comment]
> To make this possible we need to add make it possible for an user to assign a name or a set of names to a FTX exchange account.

There can be no exchange-wide solution for this since not every exchange has sub accounts. The error from the user looks like this:

![unknown (1)](https://user-images.githubusercontent.com/1658405/115968812-e0e8bc80-a539-11eb-948c-2561555e5e1a.png)

So that means that perhaps FTX itself has a way to limit permissions for subaccount, so a permission error can just be ignored and logged in the logs if it mentioned subaccounts?

**Comment by yabirgb** [comment]
> So that means that perhaps FTX itself has a way to limit permissions for subaccount, so a permission error can just be ignored and logged in the logs if it mentioned subaccounts?

In the same request mechanism that we currently have is needed to add a header with the subaccount's name. The issue is that the query for balances makes a query for all of them and this needs to change for a single account balance query.

Somehow in the UI we have to allow the user to provide the names for the subaccounts (since we can't know the name for those) and use them in the queries

https://docs.ftx.com/#subaccounts
https://docs.ftx.com/#get-balances
