### ISSUE TITLE
Kraken API Setup not working

### ISSUE THREAD

**Issue by osirion** [rotki/rotki#2787]
Getting this on trying to add Kraken.

![image](https://user-images.githubusercontent.com/8584135/115990971-6fa31b00-a5c6-11eb-8e1c-0c88fc9023fb.png)

Other exchange worked fine.
Have tried this Kraken API key with another app and works fine.

Spot balances at Kraken are 0
I do however have a staking balance for DOT

**Comment by LefterisJP** [comment]
Hey @osirion I have a suspicion it may be due to Kraken, yet again, changing how their API returns if you have empty balances.

Can you run rotki in [debug](https://rotki.readthedocs.io/en/latest/contribute.html?#id2) mode? And hop on discord and give me the logs via a DM? https://discord.gg/aGCxHG7

**Comment by osirion** [comment]
> Hey @osirion I have a suspicion it may be due to Kraken, yet again, changing how their API returns if you have empty balances.
> 
> Can you run rotki in [debug](https://rotki.readthedocs.io/en/latest/contribute.html?#id2) mode? And hop on discord and give me the logs via a DM? https://discord.gg/aGCxHG7

Done & Done - thanks!

**Comment by LefterisJP** [comment]
Thanks for joining Discord and sending me the logs @osirion!

So from the logs I can see that Kraken is giving you an invalid nonce error.

```
kraken: Kraken API key validation error: EAPI:Invalid nonce
```

That in combination with:

> Have tried this Kraken API key with another app and works fine.

tells me that you are probably actively using that key somewhere else and that causes nonce errors. Kraken, like most exchanges keeps a nonce per api key per request to make sure requests are processed in order. So using a single key in multiple apps can cause problems.

https://support.kraken.com/hc/en-us/articles/360001148023-What-is-a-nonce-window-
https://support.kraken.com/hc/en-us/articles/360001148063-Why-am-I-getting-invalid-nonce-errors-

As per the docs I would suggest creating a separate key for rotki (read only!).

**Comment by osirion** [comment]
Thanks - that did the trick. Apologies for the user error on my end.
