### ISSUE TITLE
Support Binance Locked Staking

### ISSUE THREAD

**Issue by osirion** [rotki/rotki#2788]
Currently Fiat & Spot, ETH 2.0 Staking as well as "Flexible Earn" values are getting pulled through. However, my "Locked Staking" values are not getting pulled through.
I have ADA both in 'Flexible Earn' (pulls through) and two ADA pools in 'Locked Staking' that arent being pulled through. Perhaps a conflict since its multiple ADA values/sources?

Not sure if this is a bug or just hasnt been implemented yet.

**Comment by LefterisJP** [comment]
It's probably not implemented. Binance is adding new things all the time so we need to add support for each of them as users request them

**Comment by jkfliu** [comment]
Hello there, I've just started researching this as well but this info doesn't seem to be available via the Binance API.

Request looks to be still outstanding on their developer forum
https://dev.binance.vision/t/earn-locked-staking/1453/23

**Comment by LefterisJP** [comment]
Hey @jkfliu thanks a lot for taking a look. Damn this api feature is pending for a long time. Hopefully they end up adding it otherwise there is not much we can do on our side.

**Comment by MichaelRyom** [comment]
Not sure if there has been any progress since 2021

if not it seems link others have been able to implement ways to do this
fx. https://www.reddit.com/r/binance/comments/k6b1r7/accessing_earn_with_api/

Binances own swagger https://binance.github.io/binance-api-swagger/
Has an "Simple Earn" section which seems to cover all use cases under the simple earn product line.

I was guided by "support" here, cause I need this feature as well. I only seems to get spot data and nothing from simple earn flexible or locked

**Comment by LefterisJP** [comment]
Hey @MichaelRyom  There has been no progress no.
As I told you via email we need someone to provide an api key with data using this as we don't have any data to test this with.

**Comment by MichaelRyom** [comment]
> Hey @MichaelRyom There has been no progress no. As I told you via email we need someone to provide an api key with data using this as we don't have any data to test this with.

I have replied to the mail

**Comment by LefterisJP** [comment]
We now have an API key. Scheduling for 1.33.0

**Comment by MichaelRyom** [comment]
Seems you nailed it. I have some small inaccuracies, but it comes down to two missing tokens, Pixel and LUNA. ( Just compared all tokens are there and the total value in Rotki matches what is seen in Binance )

![Skærmbillede 2024-02-25 094109](https://github.com/rotki/rotki/assets/10729897/d8e4b455-b465-4959-a3b0-498e9dd3e310)
![Skærmbillede 2024-02-25 094250](https://github.com/rotki/rotki/assets/10729897/e125b6ba-0a50-4fcf-bedb-bbbf2ff88226)

**Comment by LefterisJP** [comment]
Should be done in 1.32.1
