### ISSUE TITLE
Add support for the proof of humanity UBI Token.

### ISSUE THREAD

**Issue by Michael-A-Heuer** [rotki/rotki#2790]
## Task

Add support for the UBI token (https://etherscan.io/token/0xdd1ad9a21ce722c151a836373babe42c868ce9a4)
that people get streamed for creating a digital identity on https://www.proofofhumanity.id/.

**Comment by LefterisJP** [comment]
Will do.

But @Michael-A-Heuer also keep in mind you can also add it locally on your own with all the appropriate settings so that it's used and detected by rotki: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset

**Comment by yabirgb** [comment]
This token doesn't have cryptocompare/coingecko identifiers that I could find.

**Comment by Michael-A-Heuer** [comment]
@yabirgb Oh, that's right. Probably because it's quite new. 
I think it will get listed soon (https://twitter.com/santisiri/status/1384589321429213185).

**Comment by yabirgb** [comment]
> @yabirgb Oh, that's right. Probably because it's quite new.
> I think it will get listed soon (https://twitter.com/santisiri/status/1384589321429213185).

Nice. We'll add it then

**Comment by Michael-A-Heuer** [comment]
Proof of Humanity is onboarding thousands of new users with their universal basic income (UBI).
Many of them also register their families and friends. These new users will have to tax their UBI. 

Rotki could offer full and smooth support specifically for UBI taxation (e.g. recognising the submitter deposit and excluding it from taxation etc.), similar to what is done for DeFi protocols.

Despite the potential to gain new (premium) users, this is also quite some work.
Accordingly, I made a proposal to the Proof of Humanity DAO:

https://snapshot.org/#/poh.eth/proposal/QmbtsnTmeSyY1zxQekgETHLyhFWhEiakuZqHahvEne1je4

**Comment by yabirgb** [comment]
Seems that we will be adding it in the next release https://www.coingecko.com/en/coins/universal-basic-income
