### ISSUE TITLE
Profit and Loss page won't complete

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2793]
Profit and Loss page won't complete it gets stuck at MakerDAO
I have restarted Rotki without success. 
![dao](https://user-images.githubusercontent.com/59722401/116041868-0ecf1d80-a66e-11eb-9ab1-d0bf32c2b7a9.PNG)

**Comment by LefterisJP** [comment]
Hey @Blackswan122 

It takes a long time. It's querying the ethereum node or etherscan for makerdao logs. The first time it runs it will take a lot longer. Leave it running.

Another way around it, which you should do any way, is to customize the defi settings and specify which addresses to query for each protocol. And if you have no addresses using makerdao disable it completed. Docs here: https://rotki.readthedocs.io/en/latest/usage_guide.html#customizing-the-defi-settings

**Comment by Blackswan122** [comment]
Yep that did it. It didn’t take so long before. I’ve narrowed the load down as pointed out. 

Use my referral link https://platinum.crypto.com/r/m1gq5iu3zf to sign up for Crypto.com and we both get $50 USD :)

**Comment by LefterisJP** [comment]
Okay thanks for confirming. Closing then! Enjoy the rest of your day.
