### ISSUE TITLE
Toggle Privacy Mode in Top Bar

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2797]
Right now I have to do 2 clicks to toggle privacy mode. Not exactly the fastest option if I want to quickly hide my balances from unwanted glances.

Adding that "toggle privacy mode" icon in the top bar would solve this.

**Comment by kelsos** [comment]
Hey @adrien-be thanks for opening the issue. There are some exploratory re-designs of the application that already suggested such an approach. It certainly would make things easier.

**Comment by adrien-be** [comment]
Fantastic :) Exciting news
