### ISSUE TITLE
Automatically save Dashboard's row per page

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2798]
Every time I return to the Dashboard view it returns to the default "10 rows" view.

It would be great if whatever change I make to that setting (i.e. change to 25 rows) gets automatically saved for my user.

**Comment by kelsos** [comment]
Hey @adrien-be which version are you using? in 1.16 the rows per page change affects all the tables and should persist across sessions

**Comment by LefterisJP** [comment]
I tested in both v1.16.0 and v1.16.1 and the rows per table persists across session. It should not revent back to 10. Perhaps you were using an older version @adrien-be?

I will close this issue as not reproducible. If you can provide more information on how to reproduce we can reopen.

**Comment by adrien-be** [comment]
Hey, yes I tried again and it works now. I was using an older versiom v1.15.x
