### ISSUE TITLE
Figure out why app.relaunch() doesn't work when exitPyProc is called

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2808]
## Problem Definition

This was observed during the implementation of a relaunch logic for the global.db update process.

https://www.electronjs.org/docs/api/app#apprelaunchoptions

It seems that running 
```Typescript
app.relaunch()
app.exit()
```
only works without terminating the backend processes. This creates a number of problems and it is not the desired outcome.
Attempting to do a `pyHandler.exitPyProc()` before the relaunch to properly terminate the backend process seems to make the `app.relaunch()` command a no-op.

This behavior was observer with the packaged version of the application running on Arch Linux and has not been tested with macOS or windows.

### Task
- Find out why

**Comment by LefterisJP** [comment]
@kelsos what's this about? It's not scheduled anywhere. Can you give a short update on what this is and schedule it at an appropriate milestone?

**Comment by kelsos** [comment]
Initially, we wanted to do a whole application relaunch, but it didn't work.
We are now only restarting the backend instead. I don't know why the original code doesn't work and I don't think I have time to figure out why since the alternative approach seems to work fine.
