### ISSUE TITLE
Figure out a way for users to provide feedback and open feature requests directly from the app.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2810]
## Abstract

It was requested by a user who made some valid points: https://twitter.com/AmryikesName/status/1387788867785400327

- Not every user has or wants to create a github account.
- Some users may want to provide feedback anonymously -- so not tie their github account to rotki and/or crypto.

## Task

Think about it and see what if anything can be done.

Some ideas that came to my mind were to somehow proxy requests via our server which would have credentials for a rotki-feedback github bot. And that could make new issues (easy) or +1 existing ones (hard )

**Comment by kelsos** [comment]
We need to be a bit careful with that, since if something is open to everybody it might invite a lot of spam.

**Comment by LefterisJP** [comment]
> We need to be a bit careful with that, since if something is open to everybody it might invite a lot of spam.

Yes this is true. To be honest I can't think of a way to do this properly without opening ourselves to spam attacks.

Even if not github, anything else would need some sort of spam protection and would be another service that handles feature requests and not happen from inside the app.

I am simply closing this.
