### ISSUE TITLE
Restart app after restore of assets

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2815]
When https://github.com/rotki/rotki/pull/2804 gets merged and develop gets the changes of bugfixes, the restore of assets functionality should use the restart mechanism implemented in https://github.com/rotki/rotki/pull/2809

**Comment by LefterisJP** [comment]
Isn't this implemented @yabirgb ? I am not sure I follow or remember what this was about.

**Comment by kelsos** [comment]
Probably it was about restarting the backend when restoring the assets via the UI which if I am not mistaken seems to be part of the first linked PR?

**Comment by kelsos** [comment]
I am closing the issue, since it is indeed implemented
