### ISSUE TITLE
Refreshing ethereum balances and adding newly detected token does not show price in dashboard

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2817]
## Problem Definition

If a user has some ethereum tokens on the dashboard and had recently moved some new tokens to one of their ethereum accounts a hard-refresh of the ethereum balances is needed to see the new balance due to the 24 hrs cache of detected tokens.

After the refresh, the newly detected token seems to have a NaN price in the dashboard view.

![2021-05-01_00-26](https://user-images.githubusercontent.com/1658405/116760005-1a2a9c00-aa14-11eb-9546-192430af8e6f.png)

Doing a "Refresh prices" fixes this. But I suppose a proper fix would be to see if new tokens are added and fetch their prices as they come.

## Task

Fix it.

**Comment by kelsos** [comment]
## Task
- Introduce a mechanism that can detect asset additions and can run partially price refresh
