### ISSUE TITLE
For some MacOS users rotki is stuck at "connecting to backend"

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2819]
## Problem Definition

This does not happen to all MacOS users. Two MacOS users have so far reported this. The frontend is running and stuck at "connecting to rotki backend".

Looking at the logs one can see that the backend has launched and is running fine. The frontend just never connects. Restarting does not help.

Thanks to some back and forth with the affected user we also know that the backend accepts api queries fine. They made a query to both the `/ping` and the `/version` endpoint succesfully.

### Give a wrong ip to coingecko

The user is technical and tried a few things:

> if i add this line to my /etc/hosts file
`69.171.250.35 api.coingecko.com`
>and clear dns cache
`sudo killall -HUP mDNSResponder`

> app is working.
>I tried that a couple of times back and forth.
>When I have this line, i can see login screen.
>When I remove it, app is always in "connecting" screen.
>And in logs, i have a ping response this time (which i don't see when i remove this new invalid ip address line)
>but now i can make it work after a couple of restarts
>and i see this "ping" line in logs whenever it works
>otherwise it's not wokring
>and it also works sometimes without this facebook ip

From the above it seems like inability to connect to coingecko at start helps (sometimes). This makes no sense to me as the coingecko query should run under a greenlet, so it should be asynchronous.

## Logs

Backend is running. Api server is on. And logs just do the periodic tasks that don't need a logged in user.
[macos_stuck_rotkehlchen.log](https://github.com/rotki/rotki/files/6410387/macos_stuck_rotkehlchen.log)

Frontend is running and has launched the backend.
[macos_stuck_rotki_electron.log](https://github.com/rotki/rotki/files/6410390/macos_stuck_rotki_electron.log)

### System Description

Operating system: Macos Big Sur (and also Mojave)
Rotki version: v1.16.1

## Task

Figure out what's happening and fix it.

**Comment by LefterisJP** [comment]
Could it be related to https://www.javaer101.com/en/article/36375339.html? We need to enable dev tools in MacOS to check.

**Comment by LefterisJP** [comment]
A Discord user who made his own dev build posted the following:

```
Hey guys, looked into the macOS issue a bit, it's stuck for me too on macOS (10.15.6). I've gotten a local build up and running, from my POV it looks like the frontend sends a few /ping requests to the API while the API is still being initialized - resulting in connection refused. It then stops trying for the ping endpoint, sends a few requests to /version, this also fails for the same reason, API not ready yet.
I've been able to verify this is the root cause by setting the amount of retries from 5 to 50, resulting in the login screen appearing correctly. That's in store/store.ts:114 .
Feel free to get in touch with me if you need some help with this issue
```

So it may indeed be a combination of the frontend giving up too fast AND the backend after v1.16.0 initializing a bit slower in MacOS.

**Comment by eth2353** [comment]
Hey it's me, the Discord user! Wanted to give you a rough idea how many connection attempts it takes on my machine to connect to the backend. I've launched my "dev" Rotki a few times and logged the count value from `store.ts` once a successful connection is made.
The count values were in the 2 - 20 range, depending on system load and some other random factors I guess, seems like mostly the connection succeeded at around the 10th attempt: `9, 19, 10, 15, 20, 2, 4, 10, 11, 5, 9, 9, 10, 11, 12, 4, 5, 10, 11, 3, 4, 4, 3, 8`
(This was done on the build branch)
I then tried the bugfixes branch with #2823 applied, to see how much of an impact it has. The count values: `19, 20, 10, 13, 9, 12, 9, 10` - not really conclusive but it seems to have little effect.

Machine used: 2014 Macbook Pro running macOS 10.15.6, I5-4278U, 8GB RAM, SSD - no beast but also not some ancient dinosaur

**Comment by LefterisJP** [comment]
Hey @eth2353 thanks a lot! I did not expect it to have much of a difference. It just defers a task to after login but that task is just spawning something asynchronously which should not really matter.

I don't know what the issue is since this does not happen in Linux. Login is instant there. I suspect as mentioned in #2823 that the main culprit for the slower initialization in MacOS though is the way we handle the Global DB due to the very early initialization of a temporary one and then a cleanup and re-initialization .. all before the full init finishes.

We have an issue to think of a way to improve this too: #2751

But still I have no idea why it would make such a big difference in the initialization between MacOS and other OSes.

Until #2751 is done we will have to also increase the tries needed which is something @kelsos will do.

**Comment by LefterisJP** [comment]
Hey @eth2353 can you try https://github.com/rotki/rotki/suites/2638992101/artifacts/57923072 and tell us if this fixes the timeout problem?

**Comment by eth2353** [comment]
Yes, that fixes it, the login appeared fine 5/5 times I tried.
