### ISSUE TITLE
Rotkehlchen API key was rejected by server

### ISSUE THREAD

**Issue by rkalis** [rotki/rotki#2832]
## Problem Definition

When opening Rotki today, it prompted me to update to Premium, which is odd, since I already have Premium. So I double checked the website which said that my subscription is still active. Then I re-entered my API keys into the app, which displayed the error "Rotkehlchen API key was rejected by server". Then I regenerated new keys on the website and entered the new keys, which resulted in the same error.

Premium was still working yesterday.

### System Description

Operating system: macOS Big Sur 11.1
Rotki version: 1.16.1

**Comment by LefterisJP** [comment]
I could reproduce. We are working on some website maintenance in preparation of eventualy upgrading our infrastructure.

It should now be fine. Please try again. If it's fine close the issue.

**Comment by rkalis** [comment]
Working again. Thanks!
