### ISSUE TITLE
Add support for Liquity DeFi protocol

### ISSUE THREAD

**Issue by tzapu** [rotki/rotki#2836]
This is a newish DeFi protocol with a huge amount of locked value and usage.

https://www.liquity.org/

p.s. rotki is amazing, thank you

**Comment by tzapu** [comment]
actually this is weird, i can see LUSD under liabilities on  the dashboard but nothing under DeFi/Liabilities

**Comment by LefterisJP** [comment]
Hey @tzapu it's not weird. Let me explain why.

We use an aggregator contract that tries to detect balances inside multiple DeFi protocols for each address you track with rotki. That contract is maintained outside of rotki so many protocols are added there fast. Thanks to it we can auto-detect balances for many protocols.

But supporting the protocol with historical data and more protocol specific information would require us to write a specific module for it. Which is what this issue would be for.

**Comment by LefterisJP** [comment]
They have a very interesting decentralized frontend system.

Anyone can run a frontend for users of the protocol and frontends get rewards for deposits made through them: https://docs.liquity.org/faq/frontend-operators

A frontend can choose to kickbak a % of that back to the user. So if rotki ever interfaces with user accounts that could be an interesting thing to play with.

**Comment by bingen** [comment]
+1
Obviously biased, but I would love to see this happen!

**Comment by joshuavial** [comment]
I was spinning up the develop branch and the WIP on this feature was breaking adding a new eth address. I put in a quick fix to prevent the divide by zero error for adding eth accounts that don't have any liquity debt.

The fix needs more work (e.g. handling the case where the user has a collateral balance and no debt) and I am pretty new to python so unsure if this is the right way of solving it but it solved my immediate problem so here it is in case it's useful to someone -  https://github.com/rotki/rotki/compare/develop...joshuavial:fix-liquity-div-zero?expand=1

**Comment by LefterisJP** [comment]
Hey @joshuavial thanks a lot. @yabirgb take note.

One warning on develop. It's always unstable. Never use it with a production DB as it can mess with your database and leave it in a state that's difficult to get out.
