### ISSUE TITLE
Exchange Binance US imported but dispalyed as Binance on Deposits & Withdwawals page

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#2837]
Imported `Binnace US` exchange but it displays as `Binance`. App version 1.16.1
<img width="317" alt="Screen Shot 2021-05-04 at 5 26 34 PM" src="https://user-images.githubusercontent.com/15807643/117085295-e5cb1e80-ad38-11eb-870a-b5f708b05f5a.png">

<img width="452" alt="Screen Shot 2021-05-04 at 5 26 22 PM" src="https://user-images.githubusercontent.com/15807643/117085331-f8ddee80-ad38-11eb-8700-8589b67e1805.png">

**Comment by LefterisJP** [comment]
Hey @CruiseMan thank you for opening the issue. I think I can see why this is happening.

We will fix this!

**Comment by LefterisJP** [comment]
Fixed by #2839. Should be in our next patch release.

**Comment by CruiseMan** [comment]
@LefterisJP How can i donate BNB for this fix ?

**Comment by LefterisJP** [comment]
Hey @CruiseMan. I am happy when you guys are happy :)

 Any help is appreciated. I don't know specifically about BNB but being a steady premium user (https://rotki.com/products/) would definitely help.

Otherwise we got an ETH and BTC donation address here: https://github.com/rotki/rotki/#donations

**Comment by CruiseMan** [comment]
> Hey @CruiseMan. I am happy when you guys are happy :)
> 
> Any help is appreciated. I don't know specifically about BNB but being a steady premium user (https://rotki.com/products/) would definitely help.
> 
> Otherwise we got an ETH and BTC donation address here: https://github.com/rotki/rotki/#donations

Got it https://github.com/rotki/rotki/issues/2846
