### ISSUE TITLE
Got remote error while querying Kucoin trades: Kucoin trades returned an invalid JSON response: Please enable cookies. Error 1015

### ISSUE THREAD

**Issue by Bizzet** [rotki/rotki#2841]
# Got remote error while querying Kucoin trades: Kucoin trades returned an invalid JSON response:
## Please enable cookies.
**Error 1015**
Ray ID: xxxxxxxxxxxxxx • 2021-05-05 13:30:29 UTC
You are being rate limited
### What happened?
The owner of this website (api.kucoin.com) has banned you temporarily from accessing this website.

**Comment by LefterisJP** [comment]
Hello @Bizzet.

It sounds as if either your rotki instance or someone else with the same ip as you queried Kucoin too much. We have never seen such api rate limiting problems with kucoin for any of our users, so it could be that you are using a shared connection or a VPN?

In any case we need more information to debug this. Can you enable debug logs (https://rotki.readthedocs.io/en/latest/contribute.html#id2), run it again and send us the logs via a DM in discord? https://discord.gg/aGCxHG7

**Comment by Bizzet** [comment]
> Hello @Bizzet.
> 
> It sounds as if either your rotki instance or someone else with the same ip as you queried Kucoin too much. We have never seen such api rate limiting problems with kucoin for any of our users, so it could be that you are using a shared connection or a VPN?
> 
> In any case we need more information to debug this. Can you enable debug logs (https://rotki.readthedocs.io/en/latest/contribute.html#id2), run it again and send us the logs via a DM in discord? https://discord.gg/aGCxHG7

@LefterisJP 
Thank you for your amazing response speed.  I didn't even check the thread for an hour because I didn't expect such a quick response. The problem was my VPN! Everything is working great now.

One thing I would like to mention is that it would be great if rotki showed margin liabilities in it's report! I would definitely purchase premium and support the program even more.

**Comment by LefterisJP** [comment]
> Thank you for your amazing response speed. I didn't even check the thread for an hour because I didn't expect such a quick response. The problem was my VPN! Everything is working great now.

Ah -- really happy to hear. Thing with VPNs is shared IP hitting the website which leads to the rate limiting.


> One thing I would like to mention is that it would be great if rotki showed margin liabilities in it's report! I would definitely purchase premium and support the program even more.

Noted! We have not planned them yet, but this is the issue to track I suppose for margin trades: https://github.com/rotki/rotki/issues/1980
