### ISSUE TITLE
Support uniswap v3

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2844]
## Abstract

Support uniswap v3: https://uniswap.org/blog/launch-uniswap-v3/

## Task

Do it. Make sure we got feature parity with v2. The easiest way to achieve that would be to use a subgraph for v3.

There is quite a few subgraphs to choose from. Community hosted: https://thegraph.com/explorer/ Search for uniswap.

**Comment by yabirgb** [comment]
This one seems to be official https://thegraph.com/explorer/subgraph/uniswap/uniswap-v3

**Comment by LefterisJP** [comment]
That was literally not there when I looked :rofl:

**Comment by yabirgb** [comment]
For LP positions the `mint` data from the graph should be enough. For doing without the graph I don't see an easy way of doing it

**Comment by LefterisJP** [comment]
The trades query is done and will be included in v1.17.0

**Comment by a7e8** [comment]
Please also add Uniswap v3 LP to the balances.

**Comment by a7e8** [comment]
> For LP positions the `mint` data from the graph should be enough. For doing without the graph I don't see an easy way of doing it

I don't think it would be enough because you can remove liquidity or collect fees.

**Comment by LefterisJP** [comment]
Closed in favour of #3249
