### ISSUE TITLE
Upgrade to Premium popup still displayed when created user with Premium api key 

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#2846]
Created docker image from commit https://github.com/rotki/rotki/commit/a7ef8be31f8059eeff34509667688a87a63edfc6 and created user for a first time importing api keys i was present with `Upgrade to Premium` popup, expected no to see this as far as Premium keys already were imported during user creation. 

<img width="797" alt="Screen Shot 2021-05-05 at 6 40 03 PM" src="https://user-images.githubusercontent.com/15807643/117230156-fb5d4880-ae0b-11eb-9bc1-0d1d11cb5c6c.png">
<img width="1888" alt="Screen Shot 2021-05-05 at 6 43 32 PM" src="https://user-images.githubusercontent.com/15807643/117230372-79215400-ae0c-11eb-8f24-dbe79a38bab2.png">

Imported api keys second time to activate Premium
<img width="1814" alt="Screen Shot 2021-05-05 at 6 44 45 PM" src="https://user-images.githubusercontent.com/15807643/117230452-a66e0200-ae0c-11eb-9c3a-d1ab8be0be9a.png">

**Comment by LefterisJP** [comment]
Hey @CruiseMan thanks a lot.

Let me see if I understand. Where did you add the premium keys? During account creation? And that did not work?

But then you followed this and it worked? https://rotki.readthedocs.io/en/latest/usage_guide.html#set-up-rotki-premium

**Comment by CruiseMan** [comment]
> Hey @CruiseMan thanks a lot.
> 
> Let me see if I understand. Where did you add the premium keys? During account creation? And that did not work?
> 
> But then you followed this and it worked? https://rotki.readthedocs.io/en/latest/usage_guide.html#set-up-rotki-premium

Correct. Importing apt key during user creation. I hade have to import after user was created and logged in

**Comment by LefterisJP** [comment]
Just to confirm.

1. Creating the account with adding the premium keys at start seems to work for me in electron (did not test docker). For that first session.
2. But if I logout of that account and login again the keys are gone and need to be inserted again. 

I think that narrows it down as to what may be happening so I will check the backend code to figure out the culprit in our little problem.

**Comment by LefterisJP** [comment]
This is fixed by #2858
