### ISSUE TITLE
Introduce searching/filtering for deposits & withdrawals and trades

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#2847]
## Abstract

I have thousands transactions aggregated from multiple exchanges and i need to find one with particular amount, date, asset but no search available to achieve that. Proposing to add 200, 300, 400, 500 amounts or even custom to pull all transactions on one screen. Currently i have to go on each page and search it.

<img width="556" alt="Screen Shot 2021-05-05 at 6 55 12 PM" src="https://user-images.githubusercontent.com/15807643/117231128-1a5cda00-ae0e-11eb-88a0-c8c1634e68df.png">

**Comment by kelsos** [comment]
The 100 is a hard limit due to technical limitations on rendering. Instead of that searching seems like a better approach tbh.

Other than amount, date, asset is there any other field you would have in mind?

**Comment by CruiseMan** [comment]
All fields please. Currently I do classic Excel calculation, but my another issues is to export deposits history. Coinbase doesn’t have this option, so I thought I could import it here and export it to csv but unfortunately

**Comment by CruiseMan** [comment]
What are the technical limitations ?. Are you saying my M1 MacBook Air can handle to render > 100 rows ?

**Comment by kelsos** [comment]
The problem is that not everybody has an M1 MacBook, rotki runs on many different platforms and machines. and these 100 rows have quite a few elements underneath. I have seen when using more than a hundred entries that performance starts degrading. so I would like to avoid this.

**Comment by Cebrain** [comment]
A "Searching" Function would be great.
Or also a Filter Function on the Columns (Action/Base/Quote) would be already helpful
