### ISSUE TITLE
Add scroll to the top button in Deposits & Withdrawals / trades etc.

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#2848]
When click on next page `>` (/history/deposits-withdrawals), expected page to be scrolled to the top, instead it scrolled to the bottom. After i scrolled to the bottom and seen latest dep/with transfers expecting next page take me to the top so i can scroll down and see transaction in their chronological order.

<img width="529" alt="Screen Shot 2021-05-05 at 6 58 15 PM" src="https://user-images.githubusercontent.com/15807643/117231315-863f4280-ae0e-11eb-914b-bb6078fc2ddc.png">

**Comment by LefterisJP** [comment]
Hey @kelsos is this perhaps something browser/docker only? Do you think we can change this behaviour?

**Comment by kelsos** [comment]
I am also a bit against it because we trade a problem for another one. Having the page jump up every time you change a page is not the best experience.

**Comment by LefterisJP** [comment]
>Maybe we could do a scroll to top button there for ease?

I think this would make sense. Could you schedule it for a release? Or else this will stay forgotten.
