### ISSUE TITLE
Value distribution by asset logic

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#2849]
When on `/statistics` page `Value distribution by asset` with default `0` assets to show indicates an erro, when changing to `1` displays `You cannot show more than 0 assets`.
I have `BTC` balance on imported exchanges but asset value is not displayed probably due to short period of time after import(10-30 minutes). But anyway, expected to see some value to the graph. Also `Value distribution by location` is not displayed.
<img width="1895" alt="Screen Shot 2021-05-05 at 7 09 52 PM" src="https://user-images.githubusercontent.com/15807643/117232159-26499b80-ae10-11eb-89f4-e041418bd44d.png">
<img width="894" alt="Screen Shot 2021-05-05 at 7 10 49 PM" src="https://user-images.githubusercontent.com/15807643/117232238-48431e00-ae10-11eb-9cb8-d8aeac35f45e.png">

Exchange balance:
<img width="399" alt="Screen Shot 2021-05-05 at 7 19 49 PM" src="https://user-images.githubusercontent.com/15807643/117232850-8a209400-ae11-11eb-9b6e-270c60d06051.png">

**Comment by kelsos** [comment]
@LefterisJP this means that the snapshot is not complete yet right? maybe I could do something on the frontend in this case?

**Comment by LefterisJP** [comment]
Yes this means there is no snapshot taken yet.
