### ISSUE TITLE
Make exchanges name consistent 

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#2850]
Created docker image from commit https://github.com/rotki/rotki/commit/a7ef8be31f8059eeff34509667688a87a63edfc6

http://localhost:8084/ page
<img width="221" alt="Screen Shot 2021-05-05 at 7 35 24 PM" src="https://user-images.githubusercontent.com/15807643/117234016-b63d1480-ae13-11eb-8f8d-abab7601e27b.png">

  http://localhost:8084/accounts-balances/exchange-balances/
<img width="299" alt="Screen Shot 2021-05-05 at 7 35 54 PM" src="https://user-images.githubusercontent.com/15807643/117234052-ca811180-ae13-11eb-9213-ec14408bda60.png">

http://localhost:8084/history/deposits-withdrawals
<img width="350" alt="Screen Shot 2021-05-05 at 7 36 39 PM" src="https://user-images.githubusercontent.com/15807643/117234115-e4baef80-ae13-11eb-934b-9ff3565595ed.png">

**Comment by LefterisJP** [comment]
@kelsos this is probably something to consider in your frontend changes with the new way exchanges are handled in v1.17.0?

**Comment by kelsos** [comment]
Sure, the reason for that is that most of the older places have not been modified and are still using the identifier in one or another capacity (first character or full capitalization).
