### ISSUE TITLE
Change the order of fetching trades, handle errors gracefully

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2851]
## Problem Definition

External trades and anything that is not dependent on an external API (e.g. crypto.com) should be fetched first when fetching trades to show in the frontend.

Ensure that if any of the external endpoints returns an error the others will continue without any issues.

Make sure that cached entries are not removed when any endpoint has an error.

### Tasks
- Change order.
- Handle errors gracefully

**Comment by LefterisJP** [comment]
Should be fixed by #2863
