### ISSUE TITLE
Way to enable/disable Sync with exchanges

### ISSUE THREAD

**Issue by Cebrain** [rotki/rotki#2853]
## Abstract
At the moment rotki syncs the exchanges every time automatically and you have no direct control about sync.
A way to disable and enable the sync to specified exchanges would be great.

## Motivation

A problem that can occur is that you get IP banned because to many syncs.
So it would be helpful to disable the Balance or Trade sync to the exchanges.

**Comment by LefterisJP** [comment]
Hey @Cebrain thanks for the issue.

This is a valid request. You can remove the exchange and readd it later to avoid that but that's an ugly solution.

Controlling the sync sounds like a good feature to have.

**Comment by Cebrain** [comment]
Another maybe useful feature to set an maximum interval to sync to the exchanges?
For example only sync every 12hours or 24hours, which information also stays active also after a restart/docker reboot.
