### ISSUE TITLE
Re-evaluate login/account creation logic

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2865]
## Problem Definition

A lot of stuff has been retrofit to make things work.
Re-evaluate the logic there and update it.

- Creating a new account with premium credentials should be treated like a login
- Creating a new account should not run any unnecessary requests to the backend
- Allow new user creation with premium, **without** using the synced DB as requested [here](https://github.com/rotki/rotki/issues/3394#issuecomment-909093650).

#### Extra
- Carefully move the code for the settings on login to use the automated converters

### Tasks
- TBD

**Comment by CruiseMan** [comment]
Related issue https://github.com/rotki/rotki/issues/2870

**Comment by LefterisJP** [comment]
Let's also make part of this issue to:

- Allow new user creation with premium, **without** using the synced DB as requested [here](https://github.com/rotki/rotki/issues/3394#issuecomment-909093650).

**Comment by kelsos** [comment]
> Let's also make part of this issue to:
> 
> * Allow new user creation with premium, **without** using the synced DB as requested [here](https://github.com/rotki/rotki/issues/3394#issuecomment-909093650).

A lot of users wanted/tried the same in the past so it absolutely makes sense to implement it as a feature.
