### ISSUE TITLE
Add SAKETOKEN to list of supported asset

### ISSUE THREAD

**Issue by bloxster** [rotki/rotki#2873]
## Abstract

Sakeswap is a DeFi dapp running both on Ethereum and BSC.

## Motivation

I tried to add the coin manually (since BSC is not yet supported) but SAKE is not recognized in the list of supported assets.

## Specification

Ethereum
https://etherscan.io/token/0x066798d9ef0833ccc719076Dab77199eCbd178b0

Coingecko
https://www.coingecko.com/en/coins/sake-token
Cryptocompare
https://www.cryptocompare.com/coins/sake/overview

**Comment by LefterisJP** [comment]
> I tried to add the coin manually (since BSC is not yet supported) but SAKE is not recognized in the list of supported assets.

What failed when you tried? Did you try restarting the app after adding it manually?

**Comment by bloxster** [comment]
I could not get a price, I guess SAKE is not in the list of supported token.

**Comment by LefterisJP** [comment]
If you added the token manually as per [the docs](https://rotki.readthedocs.io/en/latest/usage_guide.html#customization-of-the-list-of-supported-assets) and used the correct coingecko identifier and the asset has a price in coingecko it should work.

You can add anything you want in the list of supported tokens as it's customizable.

That said we can gladly add this particular token in the list in the next update.

Just letting you know that adding it manually also work.
