### ISSUE TITLE
Improve app update experience

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2876]
## Abstract

Improve how updates are presented to the user once (s)he has logged in

## Motivation

After a new release is published the user is prompted in the login screen  with a `download` button. If the user doesn't upgrade s(he) can see a red arrow in the top bar but this opens the release notes instead of the popup with the option to download the update

## Specification

If the user clicks on the red (up pointing) arrow rotki should present a bubble with the option to download the update (as we do in the login screen) but would be also interesting to also link the github release at github

**Comment by LefterisJP** [comment]
Isn't this the same issue as https://github.com/rotki/rotki/issues/2877 ?

**Comment by LefterisJP** [comment]
I am not sure I follow, but if you know what you mean and can fix it sure :smile:

**Comment by kelsos** [comment]
Just a note, the update button there should keep the existing behavior when running outside of electron (e.g. Docker) 
since we can't do an automatic update on docker (at least not the same way we do in electron).
