### ISSUE TITLE
Present new features/highlights to the user after update

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2877]
## Abstract

Currently a user has to read the release notes from github or the docs in order to know what is new. Before the user had to download rotki from the github releases' page but this is not the case anymore. I believe it would be a good idea to present new features to the user from the app

## Motivation

Improve knowledge of the users about new features and solved bugs

## Specification

After a successful release a dialog box should be presented to the user rendering highlight and possible features/bugs. Maybe it is enough by rendering the github's notes on the release but a more specific write just for this might be also be interesting

**Comment by dckc** [comment]
I'm more interested in knowing what's new *before* I upgrade; i.e. I'd like to look at the release notes in order to inform my decision.

I see the release notes are in the help menu; it would be nice if they were also in the "A new version of rotki is available. ..." dialog.

Perhaps what I'm talking about should be a separate issue?

**Comment by LefterisJP** [comment]
No this is good enough. A link to the release notes.

Anything more is too much work and would be duplicating information. Should be trivial to add said link.

**Comment by LefterisJP** [comment]
Hey @yabirgb since you made this issue can you pick it up and do it? A link to the release notes should be trivial and let's just have it done. I hate having so many small issues open and move them milestone from milestone.

**Comment by yabirgb** [comment]
After discussing the idea on discord duplicating information is not a good option and having the
