### ISSUE TITLE
Abstract import of CSV files

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2886]
PR #2783 introduces new external exchanges supported by CSV import. Logic behind them is very similar for some methods. 

# Task

Try to abstract the CSV import methods and reuse code where possible

**Comment by a7e8** [comment]
This would be a great idea to make a standard Rotki import format because then we can automate importing transactions that are not natively supported yet, saving having to enter them all manually.

**Comment by LefterisJP** [comment]
@a7e8 The issue you are looking for is https://github.com/rotki/rotki/issues/2270

I believe @yabirgb made this one in order to remind himself to abstract away common code. Right @yabirgb ?
If so please schedule it for a release or we will forget it.

**Comment by LefterisJP** [comment]
Hey @yabirgb what do you envision for this? The code being abstracted right? Will push it by 2 releases but you can check it out whenever.

**Comment by phenomax** [comment]
+1

**Comment by LefterisJP** [comment]
So @yabirgb can you either close this or describe this further?

**Comment by yabirgb** [comment]
The scope of the issue is to provide an abstraction for the methods in https://github.com/rotki/rotki/blob/develop/rotkehlchen/data/importer.py

They share some logic and was proposed by you to somehow abstract what is possible this behavior.
Maybe will be a good idea to close this issue since the logic could be better refactored when we introduce a syntax for custom imports by users
