### ISSUE TITLE
Migrate binance WAPI endpoints

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2887]
Binance is making changes in their API and wapi endpoints are loosing support. We have to migrate to SAPI endpoints providing similar information.

https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269

# Task

Do it!

**Comment by LefterisJP** [comment]
Is this related to https://github.com/rotki/rotki/issues/2874?

**Comment by yabirgb** [comment]
@LefterisJP I discovered this migration looking for causes for that issue. The migration on the binance side is not finished and don't know if it is the reason for that error.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/3136
