### ISSUE TITLE
Profit/Loss report: Make each transaction with a TX hash clickable to open the TX in a blockexplorer

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#2890]
## Abstract

Make each transaction with a TX hash clickable to open the TX in a blockexplorer

## Motivation

Currently reviewing taxable transactions in the PnL report is cumbersome, as each event/transaction can not easily opened directly from rotki in the block explorer.

## Specification

Make each transaction with a TX hash clickable to open the TX in a blockexplorer

**Comment by LefterisJP** [comment]
Hey @kelsos how hard is it to do this in a generic way? This info is probably already exported as part of the "link" for amm trades and most defi events have a tx_hash and ethereum transactions do have the hash included I think.

**Comment by kelsos** [comment]
If we have the hash it's really easy. You just have to just introduce the hash-link component

**Comment by LefterisJP** [comment]
Happy to report this as done in the upcoming v1.24.0. Check screenshot

![2022-05-21_10-50](https://user-images.githubusercontent.com/1658405/169643978-05782bc2-e0c4-48f1-b12f-3cd0ade31093.png)
