### ISSUE TITLE
Allow "Notes" and "Link" Information to add to csv report

### ISSUE THREAD

**Issue by Cebrain** [rotki/rotki#2891]
## Abstract

It would be great if you could make the notes and link field from transactions exportable in the CSV.

## Motivation

This field can contain important information for the person who recieves the CSV.

## Specification

Adding a Setting/Button to Enable/Disable this in the Accounting Settings field would be already enough.

**Comment by LefterisJP** [comment]
Also make sure for swaps transactions the link is the autogenerated link to the transaction hash

**Comment by KremerMichael** [comment]
Just checking by link we mean the etherscan link? And I'm not sure what notes means in this context?

**Comment by LefterisJP** [comment]
The trades object has both a "link" and a "notes" field. This is to add them in the all_events csv report.

**Comment by KremerMichael** [comment]
Okay gotcha thank you!
