### ISSUE TITLE
Metamask custom chain coins

### ISSUE THREAD

**Issue by quancore** [rotki/rotki#2895]
## Abstract

I do not know whether it is possible to see my altcoins on matemask that uses BSC (Binance Smart Chain) like Safemoon etc.

## Motivation

There are many altcoins like safemoon, bonfire, etc., and thousands of users of them. It would be wonderful to see those coins amounts and the current price according to a swapper or stock (like PancakeSwap, gate.io, etc.)

**Comment by LefterisJP** [comment]
Hey @quancore you can always add manual entries for any asset you want.

If it's listed in coingecko and we don't have it in the assets you can add it manually as shown here: https://rotki.readthedocs.io/en/latest/usage_guide.html#customization-of-the-list-of-supported-assets

And you can add a manual balance like this: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-manual-balances

---

Now to support tracking addresses in other blockchains we would need to address each blockchain individually and we have one issue to track this per chain. Such as for example this for BSC: https://github.com/rotki/rotki/issues/1573

I will close this issue as it's a bit too generic. IF you want to see support for a specific blockchain go +1 on the existing issue. If it does not exist feel free to create one.

Thank you for using rotki!
