### ISSUE TITLE
"Semi" Privacy Mode with only Percentage %

### ISSUE THREAD

**Issue by Cebrain** [rotki/rotki#2901]
## Abstract
Had an idea for an "Semi" Privacy Mode which only shows your assets with percentages, instead of nothing as the current privacy mode.

## Motivation
For sharing with someone some asset information, it would be helpful to show a semi privacy mode with percentages.
So you can show them the correct portfolio but not the amount of your Tokens
Nothing important but maybe helpful and interesting for one or another.

**Comment by kelsos** [comment]
@Cebrain you can go to the settings and enable the scramble mode. You can do so by going to the General Settings, and in the frontend settings. This has the described effect. It will randomize most of the addresses and values

![image](https://user-images.githubusercontent.com/2269732/117939375-442f6880-b308-11eb-8a4f-9f2a920fb475.png)

**Comment by Cebrain** [comment]
@kelsos 
Thanks for response, the only problem with that is, i would like to show the correct % values but not the Amount.
The problem with scramble mode is, that the % values are also randomized.

So when i want to show someone the portfolio how the user splitted the assets, i cant do this in a easy way.

**Comment by LefterisJP** [comment]
@kelsos I guess what the user wants to achieve is something like this flexing by the iconomi users in twitter:

https://twitter.com/ZarmonyMM/status/1392406270137839620
https://twitter.com/cynepnec/status/1392408615005392897

**Comment by kelsos** [comment]
Ok, I am not sure how easy it would be to retrofit that but I will keep the issue open and I will check it
