### ISSUE TITLE
Allow user to change display of %s of holding from total across all holdings (net worth) or total across current grouping shown

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#2918]
## Abstract
Users should be able to customize (either via setting or a toggle on relevant pages) how holdings tables show percentage holdings (i.e. either as % of net value or % of group shown (e.g. assets / liabilities)).

The primary reason for this is because when there are both assets and liabilities there are cases where the % may be confusing to a user if they don't realize that it's across all holdings.

![image](https://user-images.githubusercontent.com/27592/118412782-37aa6780-b69c-11eb-9bc5-67c923b2b66b.png)

See discussion on discord here:
https://discord.com/channels/657906918408585217/683245846070165504/842699266182086656

3rd option: % of total assets (i.e. abs value)

**Comment by LefterisJP** [comment]
Putting this in a milestone so we don't; forget about it. You can feel free to move it further in case you think it's hard.
