### ISSUE TITLE
Privacy by default, when in doubt, ASK

### ISSUE THREAD

**Issue by daodesigner** [rotki/rotki#2921]
## Problem Definition
Expected to respect privacy by default. Actually opts in by default(1) uses IP address for geolocation and stores data on private servers. If that fails and enough of my data wasn't collected,leak my IP to two other paid services instead of asking for the information (2)

## Logs
(1) https://github.com/rotki/rotki/blob/develop/rotkehlchen/db/settings.py#L27
(2) https://github.com/rotki/rotki/blob/develop/rotkehlchen/usage_analytics.py#L112

## Resolution 
Ask for the data you want to collect explicitly (ie. Explicit city inputs, local geo approximation) or at-least inform people you are leaking their IP info to potentially 3 external geolocation APIs with keys tied to this 'privacy' project. Or stop branding yourself as a privacy solution. Do not add more fallbacks as commented.

### System Description
Operating system: All
Rotki version: all releases since November 2019

**Comment by LefterisJP** [comment]
Hello @daodesigner 

Thank you for the issue, for taking the time to read our code and for being vigilant!

I am happy to inform you that you have misread it.

We **do not** opt the user to the usage analytics by default. At user creation the user is asked at a specific step to enable or disable them.

![2021-05-17_09-02](https://user-images.githubusercontent.com/1658405/118445424-b7612200-b6ee-11eb-9e9c-3723b27cdb1a.png)

No rotki user can be created without making this choice.

This choice is given by the frontend here:
https://github.com/rotki/rotki/blob/c80cdaba6b881711a11bf4f96c2382b4c05cb14b/frontend/app/src/services/rotkehlchen-api.ts#L376-L405

and is passed to the backend here:
https://github.com/rotki/rotki/blob/c80cdaba6b881711a11bf4f96c2382b4c05cb14b/rotkehlchen/api/rest.py#L1084

---

Additionally for the people who do opt in, the ip is not taken or stored anywhere. Location is. Along with the following:
```
    analytics['system_os'] = platform.system()
    analytics['system_release'] = platform.release()
    analytics['system_version'] = platform.version()
    analytics['rotki_version'] = get_system_spec()['rotkehlchen']
```

And all this is is to help us understand more about our users. Being a local application and having absolutely no way to know what our users are doing we need some basic information to be able to improve our product and prioritize feature requests.

what OS they use, which jurisdiction they are in (for which accounting settings to prioritize), which rotki version they use etc.
We will probably add more anonymous information in the future at which point we will **reask the user to opt-in**. Or perhaps opt-in per information entry.

Finally for your ip leaking comment, rotki is again a local application that does balance/portfolio tracking for multiple chains and multiple protocols. We are querying a lot of external services as there is no way around this for such a tool. Etherscan, coingecko, cryptocompare, beaconcha.in all the exchanges and more.

Presumably they can keep and log your ip. If you are concerned about this please use rotki via a VPN.

I am going to close this issue. If you have any more feedback or ways you believe we can improve the process please join our discord and chat with us and the rest of our users about it: https://discord.gg/aGCxHG7

Also feel free to open more issues with suggestions.
