### ISSUE TITLE
Set a Coin/Token/Trade locked and dont allow to trade

### ISSUE THREAD

**Issue by Cebrain** [rotki/rotki#2929]
## Abstract

It would be cool to "lock" a token/coin to not allow to trading.

At the moment all tokens will be sold with the FiFo method.
As i saw you are already working on a different method, but i had an idea for maybe a quicker solution to get a part of the feature.

## Motivation

For example, you buy 1 BNB for 500$ with the idea to hold this token for over a year and get the wins tax free.

The problem is now when you buy 1 BNB (550$) on a later date (1 month later) only with the purpose to trade it into another Token, you do the trade with the first BNB and this would be mean you have a profit of 50$, because FiFo will be used.
If Rotki would use the 2nd BNB there wouldnt be any profit.

As i know it would be much harder to use a automatication method to find the best trades for Rotki, so i had the idea what if we could "lock" the first trade/token so this BNB will never be used in another trade. If you want to use the BNB in a trade you need to unlock the token.

I hope you understand what i mean.

**Comment by LefterisJP** [comment]
As discussed in discord what you are looking for is a different accounting strategy. Either:

- [LiFo](https://github.com/rotki/rotki/issues/44)
- [Multiple Depots](https://github.com/rotki/rotki/issues/2438)

Since there are issues for those I will close this one as a duplicate.
