### ISSUE TITLE
Evaluate using proper FK relations using an autoincrement ID

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2937]
## Problem Definition

As per our discussion, I am opening this issue to track the future possibility of updating the DB so that the asset identifier is not copied across tables.

The idea is that the asset table will have an autoincrement integer id column and a unique identifier column where the asset identifier would be used. 

The columns that depend on the identifier instead of copying the identifier as a whole would depend on the FK instead.

This would require changes in the querying and inserting logic.

**Comment by LefterisJP** [comment]
The "not so right way" is implemented right now through: https://github.com/rotki/rotki/pull/2938

**Comment by LefterisJP** [comment]
Closing this as we already have this changed for many tables and it's something we generally try to follow (though may not be done so everywhere)
