### ISSUE TITLE
Evaluate rotating x last logs from the backend end

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2939]
## Problem Definition

Sometimes users will run the application with debugging on, but after restarting the backend logs are overwritten so the users have to way again until the issue happens again before sending logs.

The proposed solution to this is to implement a mechanism that keeps that last x runs of the logs and on every run, it rotates by deleting the oldest log file. The older logs should be gzipped or compressed with any other algorithm in order to reduce the required space.

### Task
- Introduce log rotation

**Comment by LefterisJP** [comment]
Probably we can use the standard python logging functionality for this: https://docs.python.org/3/library/logging.handlers.html#baserotatinghandler
