### ISSUE TITLE
Allow filtering of addresses for the PnL report

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2942]
## Abstract

Allow to select which addresses should be taken into consideration at the moment of doing the profit and loss report  

## Motivation

One user could have an address added to rotki for the portfolio functionality but not want it to be included in the PnL report for different reasons.

## Specification

For some of the modules that we currently support and I've checked, an address is already added to every operation so at the moment of taking the PnL a filter by address could be possible.

**Comment by LefterisJP** [comment]
I am going to consoldiate this with https://github.com/rotki/rotki/issues/6427

As moving PnL to history view and using its filtering will allow this.
