### ISSUE TITLE
Allow Creation of Manual Deposits and Withdrawals

### ISSUE THREAD

**Issue by krupawan5618** [rotki/rotki#2947]
## Abstract

The ability to add manual deposits and withdrawals linked to exchanges.

## Motivation

Some APIs have limited import functionality. For example, in syncing with Binance APIs, ACH deposits are not synced, although they have stated that they are working on this issue. A manual ledger action doesn't allow for a "Withdrawal" or "Deposit" type, and it is not intuitive which ledger category a deposit or withdrawal would fall into from the provided options. Thus, the ability to add manual deposits and withdrawals should be considered.

## Specification

I propose a "+" button in the Deposits and Withdrawals tab that provides this functionality that is consistent with the same design as the "Trades" tab under History.

**Comment by LefterisJP** [comment]
Hey @krupawan5618 thank you for the issue.

With the way rotki is working, there is no need for manual deposit or withdrawals.At the moment the only reason we count deposits and withdrawals to exchanges are their fees. You can achieve the same thing by making a ledger action of type expense.

If we do count deposits/withdrawals to a location in a different way then yes this would make sense, but until then there is no need.
