### ISSUE TITLE
Auto-complete historical trade rate for external trades by querying historical price

### ISSUE THREAD

**Issue by rakanalh** [rotki/rotki#295]
## Abstract

When adding OTC trades, most invoices won't provide you with the rate at which you bought BTC with compared to fiat currency USD / EUR. However, since Rotkehlchen queries Cryptocompare for prices, CC can be queried as soon as the user enters the OTC trade's "time" and "pair" fields.

## Motivation

Forms are usually a bit frustrating. From a UX point of view, we can provide the user with the luxury of having some fields prefilled when needed data are already entered. The automatically populated fields could still be modified but having them prefilled is very nice to have.
The problem we're solving here is that the "rate" field could be automatically populated when the user enters the OTC trade's "time" field and the "pair" field.

**Comment by LefterisJP** [comment]
The problem with this approach is that by definition an OTC trade does not follow the standard rate. An OTC (over-the-counter) trade usually goes at a special rate known only to the user who made it. For example an ICO, a signed deal with a broken for a large purchase e.t.c.

**Comment by rakanalh** [comment]
True... the pre-populated field could just "suggest" the value. You could also argue that people will use OTC trades for entering trades on exchanges not supported by Rotkehlchen such as Coinbase or Kukoin... etc, which means that it could be very useful to have the field populated in case my Invoice does not contain the rate at the point in time where i purchased the cryptocurrency.

**Comment by LefterisJP** [comment]
>  You could also argue that people will use OTC trades for entering trades on exchanges not supported by Rotkehlchen such as Coinbase or Kukoin... etc,

That's also true. It's a good idea.


Sidenote: All these exchanges should eventually be supported. Make issues and someone ... if time allows .. should get them done :)

**Comment by LefterisJP** [comment]
I think with the new addition of the historical price endpoint this should not be that hard to handle on the frontend, right @kelsos ?

**Comment by kelsos** [comment]
Yes, I also think this is doable.

**Comment by LefterisJP** [comment]
Great so let's do it. And if not price, or zero price is returned just do nothing.
