### ISSUE TITLE
Move cursor to `Password` field when `Remember User` was selected

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#2954]
When `Remember User` selected, activate cursor in `Password` to save a click and enter password with out moving courser(press tab) manually.
<img width="859" alt="Screen Shot 2021-05-23 at 2 17 36 AM" src="https://user-images.githubusercontent.com/3277207/119254774-2914f200-bb6d-11eb-854b-3f30db24b72d.png">

**Comment by LefterisJP** [comment]
Hey @kolya182 thanks for the issue!

That sounds like a good idea. Let's ask @kelsos how easy it is to implement.I guess it would not be that hard to do.
