### ISSUE TITLE
Allow to set a max size for log file

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2959]
## Abstract

Allow to set a max file size in arguments for docker container

## Motivation

Since the docker container might be always running in the background file can increase in size quickly.

**Comment by LefterisJP** [comment]
Probably work on this issue can happen at the same time as this: https://github.com/rotki/rotki/issues/2939

**Comment by LefterisJP** [comment]
I think it's the same issue even, as the Rotating file handler can accept a max file size.
