### ISSUE TITLE
Add support for staked assets

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2960]
## Abstract

It would be nice to see staked assets profits like 

- Sushi -> xSushi
- 1inch -> st1inch
- Pickle -> DILL
- #2845

## Motivation

In the current state of DeFI there are many protocols that support staking of assets for rewards. 

## Specification

1. Create an interface for protocols that allow staking
2. Implement logic for each protocol's contracts
3. Add staking stats under Defi > Assets

**Comment by LefterisJP** [comment]
> Create an interface for protocols that allow staking

We already have staking interface. ETH2, Adex.

I don't think we need a generic issue for many staking assets. I would make an issue per staking protocol. Unless I misunderstand something.

**Comment by yabirgb** [comment]
For Adex I haven't checked how it's implemented but if the ETH2 can be reused for me is nice. Then I can create an issue per protocol. Thanks!

**Comment by LefterisJP** [comment]
I don't think any of them can be re-used. Staking is quite protocol specific.
