### ISSUE TITLE
Add Kucoin exchange support

### ISSUE THREAD

**Issue by rakanalh** [rotki/rotki#297]
Kucoin support should be added.

**Comment by LefterisJP** [comment]
One more user from reddit requested this exchange: https://www.reddit.com/r/CryptoCurrency/comments/h85lju/rotki_the_portfolio_tracker_that_respects_your/fuqigby/

**Comment by aspiers** [comment]
I would also greatly appreciate Kucoin support :-)

**Comment by adrien-be** [comment]
+1

**Comment by havrancek** [comment]
me too, please add kucoin

**Comment by bgibbsjr** [comment]
Kucoin support is very important for me. I have 10k+ Kucoin transactions to track and growing.

**Comment by LefterisJP** [comment]
It is evident that the most wanted exchange is Kucoin. We will add support for it first, when we find some cycles to implement the interface for it.

**Comment by LefterisJP** [comment]
Either 1.13.0 or 1.14.0 depends on the accounting improvements progress and Kusama support.
