### ISSUE TITLE
Native support for the Avalanche chain

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2971]
## Abstract

Much like other chains such as BSC and ADA, Avalanche has seen quite a vibrant ecosystem and multiple users have requested integration for it in rotki.

## Task

Integrate Avalance as a native chain in rotki.

**Comment by Jonasslv** [comment]
I started a project to fulfill this task for Avalanche C-Chain (EVM), will be in touch.

**Comment by keo** [comment]
Would love to see X chain and P chain support as well 🙏
