### ISSUE TITLE
Notification popup appears light with light text in dark mode

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2977]
## Problem Definition
![image](https://user-images.githubusercontent.com/2269732/119524886-508ed900-bd7e-11eb-8eac-2066aef89592.png)

That makes the text unreadable
### Tasks
- update css

**Comment by LefterisJP** [comment]
This you fixed directly in master, right @kelsos ?

**Comment by kelsos** [comment]
yes let me close it
