### ISSUE TITLE
Notify user that a user DB upgrade is taking place

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2981]
## Abstract

There are moments in the execution of rotki where the user closing the windows might lead to inconsistent states on the database. The user would need to know that something critical is happening.

## Motivation

A user reported an unusable database. After investigations the conclusion was that he closed the app before the migration in the backend finished due to it affecting several rows.

## Specification

When a migration starts in the backend, the frontend should be notified and alert the user that something critical is undergoing. 
When the operation has finished the user should be notified with a success/error message.

**Comment by LefterisJP** [comment]
@yabirgb what do you imagine for this issue? A websocket message during login for the DB upgrade process and one for its end?

Do you think it's required?

**Comment by LefterisJP** [comment]
> In most of the cases is fast but we have seen upgrades that take a bit longer so I would say is a good thing to have

Yeah but adding 2 extra websocket messages may also make the fast cases slow. Let's see what @kelsos thinks tomorrow.

**Comment by kelsos** [comment]
I don't think the impact would be significant if we sent a message at the start and the end.
As long as we don't do full progress messaging the difference should be negligible.

**Comment by LefterisJP** [comment]
Closing in favor of: https://github.com/rotki/rotki/issues/4975
