### ISSUE TITLE
Can't disable dark mode in browser

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2991]
Video proof

https://user-images.githubusercontent.com/5068010/119801350-ea20cc80-bedd-11eb-9c47-bc0f33d54cb2.mp4

In the browser logs I see this

![image](https://user-images.githubusercontent.com/5068010/119800924-81d1eb00-bedd-11eb-9d7b-73628e61822d.png)

**Comment by kelsos** [comment]
Fixed and deployed
