### ISSUE TITLE
Binance Trades error

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2996]
## Problem Definition

I get this error when fetching trades from Binance. I assumed it was going to be fixed in a new release but it still pops up.

Looks like the retry after value should not be > 60.

## Logs

```
Failed query for Binance: Error: binance API request https://api.binance.com/api/v3/myTrades?symbol=ETHBTC&fromId=0&limit=1000&recvWindow=10000&timestamp=1622154912803&signature=000 for myTrades failed with HTTP status code: 418 due to a too long retry after value (400 > 60)

Failed query for Binance: Error: binance API request https://api.binance.com/api/v3/myTrades?symbol=ETHBTC&fromId=0&limit=1000&recvWindow=10000&timestamp=1622154862685&signature=000 for myTrades failed with HTTP status code: 418 due to a too long retry after value (450 > 60)
```

### System Description

Operating system: Mac
Rotki version: 1.17.1

**Comment by LefterisJP** [comment]
This is the usual binance rate limiting error. Either behind a shared network, VPN or just querying binance too much.

We stop at retry > 60 because at that point it's too long.

The only real solution for trades query is to specify a set of markets to query. This will reduce queries 500x: https://github.com/rotki/rotki/issues/1073

**Comment by a7e8** [comment]
Something must have changed because I used to get the trades fine and now I can't get them at all.

Also because I had to delete the Binance cache (due to the fee now being included in withdrawals) I now don't have ANY Binance trades in Rotki.

It's a bit ridiculous that this is an unsolved problem. Rotki is not pulling any Binance trades now and was masking that it was working by keeping the previously cached data.

**Comment by LefterisJP** [comment]
Rotki is always pulling new data from binance and showing the cached ones before starting a new pull. There is absolutely nothing we can do on our side about binance's terrible API and rate limiting.

The only thing we can and will do is: https://github.com/rotki/rotki/issues/1073
