### ISSUE TITLE
Assets for 1.17.2

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3003]
Etoro euro

- https://www.coingecko.com/en/coins/etoro-euro
- Doesn't seem to have cryptocompare

`0x05ac103f68e05da35e78f6165b9082432fe64b58`

**Comment by yabirgb** [comment]
BlackPool token 

https://www.coingecko.com/en/coins/blackpool-token
`0x0ec9f76202a7061eb9b3a7d6b59d36215a7e37da`

**Comment by LefterisJP** [comment]
> BlackPool token
> 
> https://www.coingecko.com/en/coins/blackpool-token
> `0x0ec9f76202a7061eb9b3a7d6b59d36215a7e37da`

That's also an airdrop afaik. Would be nice to find out a list of eligible addresses

**Comment by LefterisJP** [comment]
Also we should add gitcoin token

https://www.coingecko.com/en/coins/gitcoin

0xde30da39c46104798bb5aa3fe8b9e0e1f348163f
