### ISSUE TITLE
Populate exchange name on `Add an exchange` window when selcted to `Name` field

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#3014]
Faced this inconvenience to type exchange name when adding an exchange
When adding an exchange that already added increment default name e.g: `Coinbase Pro 2`, next one `Coinbase Pro 3`

https://user-images.githubusercontent.com/15807643/120120609-23ae3d80-c153-11eb-9292-dfb0159b32c5.mov

**Comment by LefterisJP** [comment]
Hey @kolya182, that's a nice UX improvement. Thanks a lot. I think we can and should do it.

I guess most people should customize this field to be able to differentiate between various keys but having some sort of auto-suggested name would increase usability.

@kelsos can we put in for v1.18?

**Comment by kelsos** [comment]
Hopefully yes. It doesn't seem like much to implement it so I will add it to the milestone
