### ISSUE TITLE
ERROR: Cannot install -r requirements.txt and -r requirements_docs.txt because these package versions have conflicting dependencies

### ISSUE THREAD

**Issue by sbellem** [rotki/rotki#3015]
## Problem Definition

In a development environment, when installing the Python dependencies from `requirements.txt` and `requirements_docs.txt`, `Flask` and `Sphinx` conflict for the version of `Jinja2`. 

```console
The conflict is caused by:
    flask 2.0.0 depends on Jinja2>=3.0
    sphinx 4.0.1 depends on Jinja2<3.0 and >=2.3
```

## Logs

```console
ERROR: Cannot install -r requirements.txt (line 19) and -r requirements_docs.txt (line 1) because these package versions have conflicting dependencies.

The conflict is caused by:
    flask 2.0.0 depends on Jinja2>=3.0
    sphinx 4.0.1 depends on Jinja2<3.0 and >=2.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

### System Description
Development environment.

Operating system: `debian buster` (`python:3.7` Docker image)
Rotki version: `develop` branch

### Related Issues
Issue filed in https://github.com/sphinx-doc/sphinx/issues/9216
Issue fixed in https://github.com/sphinx-doc/sphinx/pull/9251

### Possible Solution
Upgrade Sphinx to 4.0.2.

**Comment by LefterisJP** [comment]
This is a known issue. That's the reason we have separate docs and dev and production requirements files. To not be stopped by stuff like.

That said if upgrading sphinx fixes that then that's great. Let me check.
