### ISSUE TITLE
Add copy for ETH1 address button in ETH2 staking view

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3020]
## Abstract

I wanted to copy the address ofthe depositor and there was no way, especially since it gets shortened.

Should be simple to add a copy button there.

![2021-05-31_13-57](https://user-images.githubusercontent.com/1658405/120190015-52dab280-c218-11eb-8d14-50f96421a33e.png)

## 

Do it

**Comment by kelsos** [comment]
There is an MR in gitlab that will add this @LefterisJP should I add a changelog?
