### ISSUE TITLE
[docs] Clarify what `remote database` stores

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#3024]
Want to know what data exactly synched to `rotki` server, docs: https://rotki.readthedocs.io/en/latest/usage_guide.html?highlight=remote%20database#sync-data-with-rotki-server ` : `will upload the most up-to-date **data** to rotki Server` ?

**Observation**: I don't remember intentionally enabling `Allow data sync with Rotki Server`, but on next login I was proposed to update local db from remote, opted out and went to `API Keys` menu and disabled data sync, log out. Log in again (change my mind) and enabled sync, log out. Log in again and now with synch enabled I'm no longer see db upgrade option. How do I synch remote on top local as of now ?

**Proposal**: Allow to remove db from https://rotki.com/home/ after data has been synched to rotki server.

<img width="466" alt="Screen Shot 2021-05-31 at 10 35 56 PM" src="https://user-images.githubusercontent.com/3277207/120271777-c30d2680-c260-11eb-93a5-83e3abc611b8.png">

**Comment by LefterisJP** [comment]
> Want to know what data exactly synched to rotki server,

It's the entire user db. But it's encrypted with your password so we can't read it. It's just used as a synching mechanism.

> I don't remember intentionally enabling Allow data sync with Rotki Server, but on next login I was proposed to update local db from remote, opted out and went to API Keys menu and disabled data sync, log out. Log in again (change my mind) and enabled sync, log out. Log in again and now with synch enabled I'm no longer see db upgrade option. How do I synch remote on top local as of now ?

It should be off by default. You must have somehow enabled it. You can disable it from the rotkehlchne premium api keys page.

>How do I synch remote on top local as of now ?

You can force push, force pull from the top left of the menu.

> Proposal: Allow to remove db from https://rotki.com/home/ after data has been synched to rotki server.

Issue here: https://github.com/rotki/rotki/issues/2291

**Comment by LefterisJP** [comment]
If the above answer your question please close the issue. IF you want a specific addition in the docs either tell us what, or also simply open a PR. Best people to improve our docs are you guys, our users!

**Comment by LefterisJP** [comment]
Closing due to lack of feedback.
