### ISSUE TITLE
Add asset allocation `%` on asset details page

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#3025]
Finding very useful to evaluate asset allocation per exchange/wallet/ for privacy/diversification/centralized vs decentralized purpose. Plus utilize blank space.
Example:
<img width="1070" alt="Screen Shot 2021-06-01 at 12 00 57 AM" src="https://user-images.githubusercontent.com/3277207/120280766-f9e93980-c26c-11eb-8b0c-53d728538060.png">

Or basically like here:
<img width="109" alt="Screen Shot 2021-06-01 at 12 26 01 AM" src="https://user-images.githubusercontent.com/3277207/120283359-f2775f80-c26f-11eb-865e-03da8ac04b93.png">

**Comment by LefterisJP** [comment]
Hey @kolya182 this suggestion is for the asset details page, right?

**Comment by kolya182** [comment]
> Hey @kolya182 this suggestion is for the asset details page, right?

Yes

**Comment by LefterisJP** [comment]
Hey @kelsos this should also not be hard to do, right? I definitely see the use case.

**Comment by kelsos** [comment]
Yes sounds easy to do, I am scheduling it for this release.
