### ISSUE TITLE
Improve search relevance results when query asset by symbol or name when adding `Manual Balances`

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#3026]
`Search query:` **BTC**
`Expected result`: **BTC**
`Actual result` **0xBTC**

https://user-images.githubusercontent.com/3277207/120284115-c6a8a980-c270-11eb-9a22-312a7aca84e5.mov

**Comment by LefterisJP** [comment]
Hey @kolya182. I think the issue you are looking for is this: https://github.com/rotki/rotki/issues/2670

Isn't this asking the same thing? Kelsos is working on improving exactly that for the next release.

If it is can you close this as duplicate of that?

**Comment by LefterisJP** [comment]
@kelsos the improvements you make will be in the search bar for all asset input components right?

**Comment by kolya182** [comment]
Closing, dub of #2670

**Comment by kelsos** [comment]
Yes the issue will affect all the asset selection dropdowns
