### ISSUE TITLE
Missing `day` of last premium database sync

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#3027]
Force push local db to rotki server successfully and day displaying now as `%d`
<img width="249" alt="Screen Shot 2021-06-01 at 12 52 42 AM" src="https://user-images.githubusercontent.com/3277207/120287001-ad552c80-c273-11eb-8d2c-b029c6fbc759.png">

After that pulled data down, app logged out(expected probably, doing it for the first time), log in and now `last database premium sync` display date before it was last pushed to the server(see image above)
<img width="244" alt="Screen Shot 2021-06-01 at 12 56 12 AM" src="https://user-images.githubusercontent.com/3277207/120287525-2a80a180-c274-11eb-8d5a-ced91742dfd4.png">

**Comment by kelsos** [comment]
That is weird, and you only had this issue in the push dialog but not anywhere else in the UI? 
we had a few changes in the date-formatter recently but this should affect all the places where you display dates.

I will have to investigate under which conditions this happens.

**Comment by kolya182** [comment]
> That is weird, and you only had this issue in the push dialog but not anywhere else in the UI?
> we had a few changes in the date-formatter recently but this should affect all the places where you display dates.
> 
> I will have to investigate under which conditions this happens.

Only seen it on push dialog so far. After app restart all displays correctly.

**Comment by LefterisJP** [comment]
Fixed by #3046
