### ISSUE TITLE
Total is 0 if xpub dropdown closed - btc blockchain address

### ISSUE THREAD

**Issue by lopezi** [rotki/rotki#3043]
## Problem Definition

In the process of adding btc addresses from ledger (because adding by blockchain do not work, perhaps this is another issue), i came across the suggestion to add the xpub of the addresses from ledger. This way the addresses get loaded into rotki.

The problem is that the total only shows the correct value when the xpub dropdown is open and shows the address. Once you close them the total gets subtracted. Meaning: if you close all xpub dropdowns total is 0. 

### xpub dropdown is open, total is correct

![shows-total](https://user-images.githubusercontent.com/388476/120717097-ea612f00-c4be-11eb-9043-1eda6140afe9.jpg)

### xpub dropdown is closed, total is zero

![total-0](https://user-images.githubusercontent.com/388476/120717187-095fc100-c4bf-11eb-99cd-1ee487985a75.jpg)

### System Description

Operating system: macOS Big Sur 11.4
Rotki version: latest 03.06.2021

**Comment by LefterisJP** [comment]
Thank you @lopezi for opening the issue.

I confirmed it with a test account.

@kelsos Seems like a frontend issue. If it's not too hard a fix perhaps we can just include in v1.17.2? I added it in the milestone.

**Comment by kelsos** [comment]
Let me check, after I finish with the other issues. This seems a bit tricky though

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/3051
