### ISSUE TITLE
At assets update conflict the confirm is barely visible and dissappears in smaller screens

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3054]
## Problem Definition

The main problem is that at the assets update conflict the "Confirm" button is very very far down in the bottom right and it's hidden from the view. I have had 3 users so far DM me asking for help only to tell them that there is a button on the bottom right.

If the screen get smaller it disappears.

https://user-images.githubusercontent.com/1658405/120869333-8447db00-c596-11eb-95c4-52c404bf9525.mp4

## Task

Figure out a way to make it more obvious where the confirm is. Perhaps change the type of button? Perhaps once all choices have been made pop up a "confirm/proceed" in the middle of the screen? Needs a bit of thinking on what the best approach is.

**Comment by kelsos** [comment]
@LefterisJP isn't this what #3621 fixed?
