### ISSUE TITLE
Some NEXO entries in CSV have different datetime format

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3057]
## Problem Definition

A user provided a screenshot

![image](https://user-images.githubusercontent.com/5068010/120938770-df9fd780-c714-11eb-82ec-89a96950fbeb.png)

where the date seems to include also seconds in the format. This is something different from what we had so I suspect that depending on region or something the format might be different

Operating system: 
Rotki version: 1.17.2

**Comment by LefterisJP** [comment]
All right, we can work with that, but if it depends on some settings on the Nexo side perhaps it's also possible for them to configure nexo to export a CSV that v1.17.2 can read?

**Comment by yabirgb** [comment]
I will investigate more tomorrow asking to out users. Just didn't want to forget this

**Comment by yabirgb** [comment]
The user that gave me the data confirmed that was an error when providing me the information and indeed the time column includes seconds

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3064. Will be included either in v1.17.3 or v1.18.0
