### ISSUE TITLE
Inputs in ledger actions

### ISSUE THREAD

**Issue by baltcoinh** [rotki/rotki#3061]
## Abstract

Input ledger actions is a real pain in the a**. It needs to be more user friendly.

## Motivation

When you are in a tax inspection you have to detail very well all the actions you made with your crypto. If you have to manually input them, you have a problem.

## Specification

Location --> Be able to set a default location (for example, an exchange if you want to make a batch of inputs) 
Date --> If only dd/mm/yyyy is filled use 00:00:00 time as default
Asset--> Don't sort alphabetically BTC, ETH, USDT, USDC, USD, EUR. As they are the main assets for pricing they should appear at the beginning of the list. Push tab selects the first asset appearing on the list instead letting the field empty.

**Comment by LefterisJP** [comment]
Hey @baltcoinh thank you for the issue.

> Location --> Be able to set a default location (for example, an exchange if you want to make a batch of inputs)

That sounds like a good idea. @kelsos would it be hard to do?

> Date --> If only dd/mm/yyyy is filled use 00:00:00 time as default

Yes ... I totally get that. That also annoys me too. @kelsos that should be possible right?

> Don't sort alphabetically BTC, ETH, USDT, USDC, USD, EUR. As they are the main assets for pricing they should appear at the beginning of the list. Push tab selects the first asset appearing on the list instead letting the field empty.

We have an issue for this and I am proud to say the fix for this is going to be in v1.18.0!

**Comment by baltcoinh** [comment]
Probably not using ledger correctly. I will truy again and be more clear in my explanation. But yeah, you have summarize the problems very well in the answer, thaks, Lefteris, great job as usual.

**Comment by kelsos** [comment]
Hey, @baltcoinh other than the 3rd part that has a PR already the others are valid suggestions for improvement.

Can you update the issue to be for these two suggestions? I am going to reopen. I will try to put the improvements for v1.18.0 and see if they are easy enough. I think at least the date one should be easy, we already do that elsewhere in the application.

**Comment by kelsos** [comment]
The asset sorting should be vastly improved so out of the issue there are two task

## Tasks

- [ ] Make last location selection persist
- [ ] Allow dates without time specified time to be added
