### ISSUE TITLE
Statistics renderer code pulled remotely could be a liability

### ISSUE THREAD

**Issue by EntropiaFox** [rotki/rotki#3063]
Hello!

First of all I'd like to congratulate you with what by all means does seem like a very slick and comprehensive product- being able to see my portfolio data pulled from all my different sources including exchanges and addresses is a godsend when I used to keep track of everything manually.

I was just about to grab Premium for at least a couple months, especially as I wanted access to the statistics module and a more comprehensive profit/loss statement I could make use of next time I filed for taxes. However, going through the documentation to see exactly what things were locked behind premium and what weren't I stumbled upon something alarming:

https://github.com/rotki/rotki/blob/develop/docs/api.rst#statistics-rendering-code

"Doing a GET on the statistics renderer will return the code to render the statistics if the currently logged in user is a premium user."

If I understand this correctly, this means that the code itself to the statistics renderer is hosted remotely and will only be pulled if you're a premium user, correct? If so, although slightly disappointing that part of the code isn't open source, that's the least of my concerns in this case.

I was admittedly drawn towards Rotki precisely because I wanted to "leak" as little data as possible about my operations and although I can otherwise minimize the queries to services I don't fully trust (for instance, I can audit what goes on with the other endpoints, I can disable syncing as I'm perfectly okay with managing my database locally only and I can simply not set any email notifications) the renderer remains the one thing I can't check. Sure, I could probably whip up something with the data I already have in my database and the endpoints that remain available, but it's rather sketchy my _local_ client would be executing code coming remotely that can change at any moment when everything else is easily auditable API calls except for that. I hope you understand my concerns and I'd like to know if there are any possible plans to address such situation.

**Comment by LefterisJP** [comment]
Hello @EntropiaFox thank you for your interest in rotki and for your question!

The code that is pulled refers to the frontend only. It's the code that does the graphs. It only concerns the UI part of rotki and is one of the ways we try to keep premium closed.

No data leaves your system, it's just rendering them in the premium parts of the app with the data that is already local.

If you have any other questions it's easier to join discord as it's a better medium for QnA: https://discord.com/invite/aGCxHG7

**Comment by kelsos** [comment]
Hey @EntropiaFox as Lefteris mentioned this code that is pulled is only a vue library that contains frontend components.
This library depends on the opensource app itself for any data and it doesn't have any external dependencies, nor does it perform any external calls.

The best way to verify this behavior would be by sandboxing the application and checking what external calls it performs. I am not sure I can suggest a specific solution because this would vary depending on the OS.
