### ISSUE TITLE
Assets for 1.19

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3094]
Add curve assets in pools
```
Unknow asset with address: 0xD71eCFF9342A5Ced620049e616c5035F1dB98620
Unknow asset with address: 0xa47c8bf37f92aBed4A126BDA807A7b7498661acD
Unknow asset with address: 0x0E2EC54fC0B509F445631Bf4b91AB8168230C752
Unknow asset with address: 0x674C6Ad92Fd080e4004b2312b45f796a192D27a0
Unknow asset with address: 0x5BC25f649fc4e26069dDF4cF4010F9f706c23831
Unknow asset with address: 0xdF574c24545E5FfEcb9a659c229253D4111d87e1
Unknow asset with address: 0x1456688345527bE1f37E9e627DA0837D6f08C925
Unknow asset with address: 0x9BE89D2a4cd102D8Fecc6BF9dA793be995C22541```

**Comment by LefterisJP** [comment]
UNIUP and UNIDOWN are currently ignored for binance. 

https://github.com/rotki/rotki/blob/716c433d05f34ea69ef09973510fc3fdef8e5442/rotkehlchen/assets/converters.py#L488-L489

They seem to have no coingecko, but they have cryptocompare data so they could be added.

https://www.cryptocompare.com/coins/uniup/overview
https://www.cryptocompare.com/coins/unidown/overview

**Comment by LefterisJP** [comment]
Also https://github.com/rotki/rotki/issues/3116. Add support for Indian Rupee as a profit currency.

**Comment by LefterisJP** [comment]
Also https://github.com/rotki/rotki/issues/3134. Add support for new cWBTC token.

**Comment by LefterisJP** [comment]
This is done.
