### ISSUE TITLE
Improve Uniswap trades fetching using the graph

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3096]
## Problem Definition

Lefteris reported two transactions that were not executed by him but the receiver was one of his accounts 

https://etherscan.io/tx/0xb256ca16c1f0cef96b5fd94c84860473783ed6e1504792f10c4a8bd8113e60bd
https://etherscan.io/tx/0x54cf3ea57f7f23d53a7bd91c3920027131c6320ee089f7409a84f1c88577a4b0

## Logs

![image](https://user-images.githubusercontent.com/5068010/122549489-d37c1a00-d032-11eb-979f-5920290f9b4f.png)

## Possible solution

Currently when scanning for an account we look in the `from` and `to` field of the swap information since if there are multiple steps in the router the address can appear in both places and some trades where missing before because of this.

A solution would be to see the number of executions made in the transaction and check when there are multiples if the sender is the account we are tracking. This wouldn't imply more queries since all of them should appear when iterating in the results

**Comment by LefterisJP** [comment]
I guess you mean 1.18.1

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3120
