### ISSUE TITLE
Change FTX endpoint used to validate API keys

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3100]
## Problem Definition

Before 1.18 to test that a pair of keys are valid we tried to query the `all_balances` endpoint. This was intended because the keys needed to be able to query all the endpoints.

With the introduction of subaccounts this will fail unless the keys have permission for all the accounts. I didn't detect this since the Keys I used had full permissions but my guess is that this could fail. The endpoint we should query now is https://docs.ftx.com/#get-account-information

**Comment by LefterisJP** [comment]
Ah nice catch @yabirgb. Should be trivial to change.

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3115
