### ISSUE TITLE
Binance API queries fail with HTTP status code 418 due too long retry after value

### ISSUE THREAD

**Issue by sibbl** [rotki/rotki#3107]
## Problem Definition

I'm a new user and started with a fresh DB. I entered by Binance api + secret keys. The keys seem to be valid as my assets show up properly. However, things like the History table won't load at all.

## Logs

> Failed query for Binance: Error: Binance API request https://api.binance.com/api/v3/myTrades?symbol=[...] for myTrades failed with HTTP status code: 418 due to a too long retry after value (360 > 60)
> 
> [...]
> 
> Failed to query binance balances: Binance account API request failed. Could not reach binance due to Binance API request https://api.binance.com/api/v1/exchangeInfo for exchangeInfo failed with HTTP status code: 418 due to a too long retry after value (237 > 60)

### System Description

Operating system: Windows 10 19043.1055
Rotki version: 1.18.0

**Comment by LefterisJP** [comment]
Hello @sibbl! Thank you for the issue.

For questions like that it's probably better to join discord and ask there. As it's easy to answer: https://discord.com/invite/aGCxHG7

To answer your question binance is a very badly engineered exchange and it does not make it easy to load trades history. To solve it here is our approach. Read about it in our docs: https://rotki.readthedocs.io/en/latest/usage_guide.html#binance-binance-us

I assume this answers your problem so I am going to close the issue.
