### ISSUE TITLE
Aave AMM Market Support

### ISSUE THREAD

**Issue by TheWanderer1983** [rotki/rotki#3110]
## Abstract
Aave now supports AMM markets. Rotki doesn't currently support the AMM markets.

## Motivation
Aave is used by the community, support would be great.

## Specification
https://docs.aave.com/developers/v/2.0/deployed-contracts/amm-market

**Comment by LefterisJP** [comment]
The docs link is dead and apparently it's now deprecated and removed even from v2. And does not exist in v3: https://governance-v2.aave.com/governance/proposal/239/

Perhaps we can historically add support if someone does it for the few users who used it but not something to focus on.
