### ISSUE TITLE
Allow access the Rotki Docker Backend with Rotki Windows Client 

### ISSUE THREAD

**Issue by Cebrain** [rotki/rotki#3118]
## Abstract

Allow access from the Rotki Windows Client through the docker backend

## Motivation

It would be a great feature to use the windows client instead of the web browser.
Maybe the performance would also be better instead of the web.

**Comment by LefterisJP** [comment]
Is this a bug? That's why you put it in v1.18.1 @kelsos ?

Is is windows specific?

**Comment by kelsos** [comment]
It is a bug with the cors configuration of the docker image so yes

**Comment by LefterisJP** [comment]
Should be fixed by #3119
