### ISSUE TITLE
Integrate Polkadot Support

### ISSUE THREAD

**Issue by TheSaltyJ** [rotki/rotki#3125]
## Abstract

As there is already Kusama integration, Polkadot support should be quite straight forward as only the Address format changes, the denomination of the tokens and the name of the token. It seems that everything necessary is already in place with Kusama.

## Motivation

It is both low-hanging fruit as well as the Polkadot community is much larger than Kusama, and therefore more users can be reached.

## Specification

Just flip the endpoints, address formats and add the token.

**Comment by jonasW3F** [comment]
I did it myself: https://github.com/rotki/rotki/pull/3197
