### ISSUE TITLE
Provide the instructions on how to install and use SQLCipher 4 on a system that has an older version installed

### ISSUE THREAD

**Issue by jonasW3F** [rotki/rotki#3129]
## Problem Definition

I want to compile Rotki from source and therefore need a new version of sqlcipher. The install script provided is giving trouble. When I am executing the script `install_deps.sh`, I receive the following error output:

`QLCIPHER_EXISTS: 	libsqlcipher.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libsqlcipher.so.0
Deleted temp working directory /usr/rotki/tmp.9kSyjrlAxp`

I already tried to only run the part of the script that clones the github repository of sqlcipher but that also doesn't update the current version (3.26.0).

### System Description

Operating system: Linux Ubuntu
Rotki version: v.1.18.0

**Comment by kelsos** [comment]
Hey, @jonasW3F which version of ubuntu is this? 

@LefterisJP I don't remember the specifics but this script assumes that there is no version of SQLCipher locally installed right?
And we don't have any instructions on how to have both versions of SQLCipher installed at the same time?

**Comment by LefterisJP** [comment]
> Hey, @jonasW3F which version of ubuntu is this?
> 
> @LefterisJP I don't remember the specifics but this script assumes that there is no version of SQLCipher locally installed right?
> And we don't have any instructions on how to have both versions of SQLCipher installed at the same time?

I also don't remember at all, but yes this is what probably happens and that it does not expect both versions co-existing.

**Comment by kelsos** [comment]
I am adding it into my todo for after the 1.19 release (to provide an alternative approach for systems that already have and older version of SQLCipher installed

**Comment by jonasW3F** [comment]
> I am adding it into my todo for after the 1.19 release (to provide an alternative approach for systems that already have and older version of SQLCipher installed

that would so great! I am trying to get rid of the old version of sqlcipher but cannot make it work.

**Comment by LefterisJP** [comment]
Any update on this @kelsos? I guess it goes to next release, right? Maybe can you also rename the issue title to specify which exact problem this issue tries to tackle.

**Comment by kelsos** [comment]
No update, I spend some time on this but I still didn't finish. 
The idea is to modify the install script to be able to install the SQLCipher v4 in a user-specified directory and then start the development mode using the SQLCipher from this user directory
