### ISSUE TITLE
Snapshot of balance per day

### ISSUE THREAD

**Issue by jonasW3F** [rotki/rotki#3130]
## Abstract

I couldn't find any way to ask a question, so probably opening an issue is the only way (maybe consider claiming the /r/rotki community?).

In countries where there is a wealth tax, it is crucial to know the balance on the 31st of December. Aside from profit/loss calculation, I could not find anything related to that (like setting the dashboard to a historic date). Is there some option for that? If not, it should be added as this is a crucial part of doing the taxes.

## Motivation

Having an easy way to collect the account balances on a specific day (e.g., the 31st December) is a crucial part of doing the taxes in countries with wealth tax and therefore should be added in rotki.

## Specification

Having the option to set your dashboard to a specific date in the past.

**Comment by LefterisJP** [comment]
Hey @jonasW3F the best way for questions like that is checking the docs, or joining the discord where we can chat synchronously if we are online and asynchronously if not: https://discord.com/invite/aGCxHG7

> Having an easy way to collect the account balances on a specific day (e.g., the 31st December) is a crucial part of doing the taxes in countries with wealth tax and therefore should be added in rotki.

I totally understand the need for this and would love to offer it in some form eventually but that's actually not easy to accomplish. It completely depends on what protocols, exchanges etc. you have used. And it assumes complete historical accuracy of all data.

We already have issues for this in the following:

- https://github.com/rotki/rotki/issues/1379
- https://github.com/rotki/rotki/issues/2227
