### ISSUE TITLE
Curve finance historical accounting

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3132]
## Abstract

Just like we do with yearn, aaave, compound and more we should have historical accounting of profit/loss and all deposits + withdrawals of curve finance pools for premium users.

## Task

Do it.

**Comment by yabirgb** [comment]
Taking this issue since it will help with #3192

**Comment by yabirgb** [comment]
Curve subgraph is missing information. This block us

https://github.com/curvefi/curve-subgraph/issues/5

**Comment by yabirgb** [comment]
I believe that with the introduction of the decoders we can close this issue. The only thing left might be handling historical prices for curve pools but that is a different issue @LefterisJP

**Comment by LefterisJP** [comment]
But wouldn't we need to have the accountant written properly for them? Decoder and accountant for each?

**Comment by LefterisJP** [comment]
@yabirgb what remains for this?

**Comment by yabirgb** [comment]
@LefterisJP For curve we have the decoders and accountants. WIth the introduction of the defillama oracle we have a way to query prices for curve pools and that makes possible everything so we can close this
