### ISSUE TITLE
unsupported asset cWBTC after upgrade of WBTC-Token in Compound

### ISSUE THREAD

**Issue by capcoolalien** [rotki/rotki#3134]
## Abstract

after upgrading/migrating wBTC to the new version and putting it into Compound the following msg appears in rotki backend:
"Unsupported asset cWBTC with address 0xccF4429DB6322D5C611ee964527D42E5d685DD6a encountered during DeFi protocol queries"

## Motivation

for Defi-Users with upgraded wBTC on Compound this would be very nice.

**Comment by LefterisJP** [comment]
Thanks @capcoolalien we will add it to the assets supported in the next release.

But you can also manually add any assets you want in rotki: https://rotki.readthedocs.io/en/latest/usage_guide.html#customization-of-the-list-of-supported-assets

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3189. Will add a changelog entry in the bumpversion PR.
