### ISSUE TITLE
Update Binance.US api to `v3`

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#3135]
Binance.US has update api endpoint to `v3` https://github.com/binance-us/binance-official-api-docs/commit/0364eff4081f2b65ce508db4fbf7ea77321de47e

From error seems like `exchangeInfo` endpoint requires to pass a symbol, but error doesn't not reflect this:
e.g: https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC
`Failed to query binanceus balances: Binance US account API request failed. Could not reach binance due to Binance US API request https://api.binance.us/api/v1/exchangeInfo for exchangeInfo failed with HTTP status code: 403, error code: no code found and error message: no message found`

<img width="331" alt="Screen Shot 2021-06-28 at 11 55 05 PM" src="https://user-images.githubusercontent.com/3277207/123751167-445dd600-d86c-11eb-8432-19dc9b11e8be.png">

**Comment by LefterisJP** [comment]
lol ... binance is such a shitshow. Deprecating apis without a warning.Thanks for the heads up. We will add it in the upcoming patch release.

**Comment by LefterisJP** [comment]
HEy @kolya182 can you also provide us with debug logs? Would need a bit more information on what happened as the error from the UI does not give much information.

We have both a binance.us and a binance api key and they work fine when we tested them this morning.

**Comment by LefterisJP** [comment]
Also the exchangeInfo endpoint is a public one, that does not require authentication and rotki queries it only once and without any arguments.

v1 works fine: https://api.binance.us/api/v1/exchangeInfo

**Comment by LefterisJP** [comment]
With lack of more information I am gonna assume that this fixes it: https://github.com/rotki/rotki/pull/3136
