### ISSUE TITLE
Windows Installation detected as virus

### ISSUE THREAD

**Issue by rafinskipg** [rotki/rotki#3147]
## Problem Definition
Trying to install windows package gets detected as virus.

"These errors mean that your virus scanning software might have blocked you from downloading a file.

Check your virus-scanning software for details about why the file was blocked."

Version: rotki-win32.v1.18.1.exe

**Comment by kelsos** [comment]
Hey, @rafinskipg can you provide more details of which antivirus is and what the message in the antivirus says?

**Comment by kelsos** [comment]
Btw here is a scan from virustotal https://www.virustotal.com/gui/file/e07c8ca1fa379e51438cf0c886581d4afd0bf04344008c63bba94c8fcd98ce63/detection it seems that Avira has a false positive, are you perhaps using Avira?

**Comment by LefterisJP** [comment]
@kelsos how can we submit to Avira that this is a false positive?

**Comment by kelsos** [comment]
@LefterisJP if this indeed what is happening there is an article [here](https://support.avira.com/hc/en-us/articles/360001163189-How-do-I-submit-suspicious-files-and-URLs-to-Avira-Virus-Lab-)

**Comment by LefterisJP** [comment]
@kelsos What can we do in this issue? Is there some action you can take? Do we need more info from the user? Or should it just be closed as something external from our control?

**Comment by kelsos** [comment]
Without any information for the antivirus that the user is using, we cannot do much. In case of false positives, we just submit the file manually to the antivirus team for review. 

Since 1.18.1 is not the latest release now I am gonna close the issue and if the user still has a problem with a release they can still reply here so we can take care of it.

**Comment by rafinskipg** [comment]
hey guys, sorry, i don't use any antivirus. Is just the windows defender system. It keeps me from installing it. I tested with latest version and keeps failing @kelsos @LefterisJP  

Thanks for taking a look

**Comment by rafinskipg** [comment]
Maybe add this to the docs for windows users https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26?ui=en-us&rs=en-us&ad=us

**Comment by rafinskipg** [comment]
Actually this is the solution that worked, smart screen disable for a file: https://www.windowscentral.com/how-fix-app-has-been-blocked-your-protection-windows-10

**Comment by yabirgb** [comment]
Thanks for letting us know @rafinskipg ! Happy to hear that it worked for you. I'll add this to the guide or the troubleshooting :)

**Comment by Rasukix** [comment]
Also ran into the same issue, just clicked 'close' then 'run anyway'

**Comment by kelsos** [comment]
@Rasukix the situation should start improving slowly, since the last release we started signing our windows binaries show now the app should show `Rotki Solutions GmbH` as the publisher.
