### ISSUE TITLE
Doc: Clarify which decentralized exchange protocols are supported in the Usage Guide

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#3163]
## Abstract

Clarify in the _Usage Guide_ which decentralized exchange protocols are supported for transaction accounting purposes within Rotki.

## Motivation

User wants to learn whether a decentralized exchange protocol is supported in Rotki, so checks Usage Guide.  

As of 7 July 2021, Usage Guide speaks only of "Borrowing" and "Lending"--nothing whatsoever about how Rotki does transaction accounting on decentralized exchange trades.

Specifically, I was looking to see if Swapr was on the list.  But there is no list at all.  I'd recommend having a list.

I asked a question on #support on Rotki Discord, and learned only Uniswap and Balancer trades are handled in Rotki for accounting purposes.  Having a clear list in the Usage Guide would help users, and avoid random questions on the Discord.

## Specification

Add description to Usage Guide of what DeFi decentralized exchange protocols are supported by Rotki.
(supported in the sense of Rotki will handle the accounting of transactions made using those decentralized exchange protocols)

**Comment by LefterisJP** [comment]
Thank you for your time @A2be 

As I answered already in discord you can check the modules section in the settings to see which modules exist.

So @kelsos do you think it makes sense to duplicate these information in the usage guide or leave it for the website features section? Or what do you think is the best approach?

**Comment by kelsos** [comment]
It would probably make sense to duplicate the information if we provide a howto and it is not just a listing of the supported modules without more information.

**Comment by LefterisJP** [comment]
Thank you @kelsos. So what exactly do you mean we put where?

What should we put in the website?
What should we put in the docs and where?

In the end I am afraid we will end up duplicating info. One of the two places should point to the other to avoid that.

**Comment by A2be** [comment]
I understand the problem.  As a team, want to avoid duplicated (and thus, likely, inconsistent) info.

But I don't believe that is the only problem here @LefterisJP 

It seems that you may be talking to two different audiences.  "Modules" ... and such speak to devs, and ppl who grok software architecture, and that s/w "modules" are even a thing.

"Decentralized exchange protocols supported by Rotki" is a different thing, and speaks to end users who may not be technical at all, and are just trying to figure out whether or not there favorite exchange protocol, or one they might experiment with to learn about, is supported from the point of view of the Rotki accounting app.  Crypto accounting made easy!:tm:  Etc.

**Comment by A2be** [comment]
Maybe I could try to learn how to do a user doc edit via GitHub.  Submit whatever it is you call it.  And see if the Rotki team thinks it makes the usage guide better or not. (accept or reject)

(I'm a github noob; usually just use it for bugs, commenting, feature requests.)
