### ISSUE TITLE
Calculate compound prices

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3184]
Inquirer class should be able to calculate compound assets prices the same way we calculate price for curve and yearn vaults

**Comment by LefterisJP** [comment]
What is this exactly? And why is it scheduled for next release? Isn't it a bit too optimistic? Do you mean to calculate compound prices, like cDAI from on-chain. Knowing what's the underlying asset and some kind of formula?

**Comment by yabirgb** [comment]
@LefterisJP Yes  that. I was todo optimistic with it I believe

**Comment by yabirgb** [comment]
> @yabirgb Please check this issue again and tell me when it would make sense to think about it

It shouldn't be difficult to handle. Similar work to what we do for curve tokens. 1.27 I believe is realistic

**Comment by LefterisJP** [comment]
> 1.27 I believe is realistic

:rofl:

**Comment by kelsos** [comment]
> > 1.27 I believe is realistic
> 
> 🤣

Classic software development estimation

**Comment by yabirgb** [comment]
Closing as defillama queries them. Might integrate it in the future https://defillama.com/docs/api
