### ISSUE TITLE
ETH Tokens to track selection needs filtering

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#319]
## Problem Definition

In the UI selection of ETH tokens to track the user is presented with all of the tokens in eth_tokens.json, even the double versions, like `MLN (old)` and `MLN (new)`. There should only be one version of each token, the newest one.

## Task

Clean up the selector UI widget to not include doubles.

**Comment by LefterisJP** [comment]
@kelsos is this going to also be handled during the vue.js? From the demos it seemed like it.

**Comment by kelsos** [comment]
The vue.js filtering will be quite different, based on a keyword. Still, if there is a way to tell the latest one apart we can also implement this kind of filtering. It should be relatively easy.

**Comment by LefterisJP** [comment]
@kelsos can we solve this in develop with the vue.js filtering of tokens?

**Comment by kelsos** [comment]
@LefterisJP I think that at the moment the tokens are just a string with the symbol right? So there is no way to know which one is the latest. If the API provides more information we can adjust the mechanism to filter the results easily though.

**Comment by LefterisJP** [comment]
Okay let me think about it and will ask you if the idea I come up with is viable.

**Comment by LefterisJP** [comment]
This does not need to be implemented. Perhaps the user would want to actually input an event involving the old token.
