### ISSUE TITLE
See if the color generator used for the tags will make sense for the pie charts

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3195]
## Problem Definition

I don't like the colors used in the pie charts (Value distribution by location, and value distribution by asset)

## Task
- [ ] Check if using the code from the tag random color generation can make them better

**Comment by LefterisJP** [comment]
I don't like them either :sweat_smile: 

If the color generator you refer to could help here that would be really cool.

**Comment by kelsos** [comment]
There is an MR that fixes this

**Comment by LefterisJP** [comment]
> There is an MR that fixes this

Kyaaaaahhh! Really?

**Comment by kelsos** [comment]
> > There is an MR that fixes this
> 
> Kyaaaaahhh! Really?

![image](https://user-images.githubusercontent.com/2269732/150155148-cd5909ee-cd8f-44ec-a68b-aa67ae0fc32f.png)

This looks way better than the old one.
