### ISSUE TITLE
Gitcoin icon in docker is giant

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3198]
## Problem Definition

The gitcoin icon looks giant in the browser using the docker images
Resizing the screen also shows it giant

![image](https://user-images.githubusercontent.com/5068010/125818236-e8b1bb64-66c6-45d4-98b0-9042aa882cb0.png)

### System Description

Operating system: Docker on linux
Rotki version: 1.19.0

**Comment by LefterisJP** [comment]
holy fuck

**Comment by LefterisJP** [comment]
Closed by https://github.com/rotki/rotki/pull/3209
