### ISSUE TITLE
Change checks for EVM Addresses

### ISSUE THREAD

**Issue by Jonasslv** [rotki/rotki#3208]
## Abstract
You can't add the same address for different blockchains.

## Motivation
We are doing another EVM support for Rotki, but when we try to track the same Wallet address in different EVM based blockchains it won't let you.

## Specification
Change the address check to _if the address and chain are the same_.
FYI we tried to change the sanity check in the frontend to consider address and chain but the backend raised an error database related.

**Comment by LefterisJP** [comment]
Hey @Jonasslv yes for this to happen we would need to change the way we store EVM addresses in the DB and the data structures of the code. This needs to happen for any EVM based chain to be added, but once this change is done and tested a lot of ways open up.

**Comment by LefterisJP** [comment]
Moving this to 1.21.0. It needs a DB upgrade.

**Comment by LefterisJP** [comment]
Reopening this. This seems to still happen in 1.21.0
