### ISSUE TITLE
The Independent Reserve exchange is misspelled "IndepentReserve"

### ISSUE THREAD

**Issue by yanniedog** [rotki/rotki#3217]

**Comment by LefterisJP** [comment]
Where is this @yanniedog? Where did you see this? A screenshot would help.

**Comment by yanniedog** [comment]
![image](https://user-images.githubusercontent.com/25560742/126036309-cd3e01da-4be8-4309-9723-a3bade65097d.png)

**Comment by LefterisJP** [comment]
Thanks. Will be fixed in next patch release.

**Comment by LefterisJP** [comment]
Done via https://github.com/rotki/rotki/pull/3219

Will be included in 1.19.1
