### ISSUE TITLE
How do you import DOGE accounts on Ledger?

### ISSUE THREAD

**Issue by yanniedog** [rotki/rotki#3218]

**Comment by LefterisJP** [comment]
You do not. We do not support DOGE as a blockchain natively.

You can always add a manual balance for these stuff: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-manual-balances

Generally for questions like that please do not open an issue. Issues are reserved for actual problems or feature requests. IF you want to ask questions hop onto our discord chat and ask away:  https://discord.gg/aGCxHG7

**Comment by yanniedog** [comment]
Well this is an 'actual problem' I'm trying to resolve.

It would be more than reasonable to list the coins/assets you 'natively' support
