### ISSUE TITLE
Add "Dex Trades" section in Defi for docs

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3222]
When reading the usage guide I noticed we are missing a section for Dex Trades. We need one with screenshots.

**Comment by kelsos** [comment]
I took a screenshot but I forgot the entry. so here is the screenshot

![sc_dex_trades](https://user-images.githubusercontent.com/2269732/126048238-de76df6a-4748-4786-8268-709fc031b6e9.png)
