### ISSUE TITLE
In settings: Change the start and end dates of the financial year (eg, July 1st to 30th June)

### ISSUE THREAD

**Issue by yanniedog** [rotki/rotki#3223]
In countries such as Australia, the financial year runs from 1st July to 30th June

**Comment by LefterisJP** [comment]
Hey @yanniedog you can customize the period in the PnL report, you don't need to select the pre-selected yearly periods.
https://rotki.readthedocs.io/en/latest/usage_guide.html#creating-a-profit-loss-report

Does that solve your problem? If yes please close the issue.

**Comment by LefterisJP** [comment]
There has been no answer. Assuming my response addresses the issue for the user.
