### ISSUE TITLE
Choosing ETH as main currency always shows 1 ETH as tooltip of graph

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3236]
## Problem Definition

A user reported this via email.

![bilde](https://user-images.githubusercontent.com/1658405/126404598-672cf717-2c57-492d-b2a4-33e736c9d68e.png)

"Whenever I choose ETH as my main currency the line chart always show my current value as 1 ETH. I've tried reinstalling the app, but the problem persists. Not a big deal, but it's kind of triggering some light OCD. Letting you guys know in case you got a fix."

## Task

Reproduce it and fix it

**Comment by kelsos** [comment]
Fixed by #3237
