### ISSUE TITLE
Feature Request: Add Uniswap V3 LP Positions

### ISSUE THREAD

**Issue by ncitron** [rotki/rotki#3249]
## Abstract

Add Uniswap V3 LP positions to Rotki asset tracking.

## Motivation

Uniswap is one of the most used apps on Ethereum. While V3 is still relatively new, there have been ~10k V3 NFT positions created. Users being able to track their V3 positions would almost certainly be a value-add for the Rotki platform.

## Specification

- Add Uniswap V3 positions under DeFi -> Deposits -> Uniswap V3
    - It might be best to separate Uniswap V2 and V3 sections for clarity
    - Show the NFT ID number
    - Show the composition of the positions (the amounts of each asset)
    - Show the total value of the position
    - Show the price range of the position
- Add total value of V3 positions to the dashboard
- Add historical LP positions and liquidity additions/removals to deposit history
    - Not sure if this part is needed

**Comment by LefterisJP** [comment]
Hey @ncitron thanks a lot for the issue. As you can understand this is quite more complicated due to the way uniswap has implemented LP in v3. But it's ofcourse in our radar. It's already in an issue hee: https://github.com/rotki/rotki/issues/2844

@yabirgb which of the 2 issues wuld you like to keep? The old one is generic with only the LP part left.

**Comment by yabirgb** [comment]
Let's keep this one as it defines what is left

**Comment by isidorosp** [comment]
https://revert.finance/#/about has the best analytics and stats reported for UNI v3 that I've seen, perhaps you could draw some inspiration from there? 
![image](https://user-images.githubusercontent.com/27592/126949938-7f6c06f5-ec8b-4ff7-b618-8f17f3a357fe.png)

I haven't managed to find the code online somewhere though; @mariorz revert is yours right? Is the code available somewhere or would you be interested in helping with the backend work (rotki's backend is in python)?

**Comment by ncitron** [comment]
I wrote a quick tool that uses the Graph to fetch Uniswap V3 info and turn it into a CSV here:
https://github.com/ncitron/uni-v3-position-tracker

It might be a useful reference especially since the math for calculating fees is a little wonky. Fair warning that the code is pretty ugly.

**Comment by yabirgb** [comment]
@ncitron Thank you for that! I've read the code, could follow it and seems correct. This will speed up the implementation for this issue a lot, maybe for 1.20

**Comment by mariorz** [comment]
Thanks @isidorosp! Unfortunately have my plate too full right now to help out. But obtaining the state of Uni v3 position is possible without relying on the graph just by calling the NFT manager and pool contracts, the steps would be:
On the NFT manager contract: 0xc36442b4a4522e871399cd717abdd847ab11fe88

1. Call **_balanceOf_** (with the user account), this will give you the number of existing positions
2. For each one from 0 to result of **_balanceOf_** - 1:
   3. Call **_tokenOfOwnerByIndex_**, again with the user account and the index from the loop
   4.   Call **_tokenByIndex_** wtth the result from step 2
   5.   Call **_positions_** from the result of step 3
   6.   Deterministically generate the pool address from the token addresses in the response from 4. Look at **_computePoolAddress_** method form the univ3 sdk for an implementation
   7.   Call **_slot0_** on the pool contract to get the current state of the pool
   8.   Now you have all the data required to generate the current state of the position using the formulas described in the whitepaper. Here's an implementation in Python from @JNP777 https://github.com/JNP777/UNI_V3-Liquitidy-amounts-calcs/blob/main/UNI_v3_funcs.py 

Hope this helps!
