### ISSUE TITLE
Allow to edit asset from asset general view

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3251]
## Abstract

When you click on one asset in the home page a window with all the accounts holding that asset and historical information is shown 

![image](https://user-images.githubusercontent.com/5068010/127030767-790ef97d-db74-4acd-a611-89a39d2dabca.png)

Allow to edit asset information from this page

## Motivation

Sometimes is needed to update parameters like coingecko/cryptocompare id or the name but you have to go to the list of assets -> search for it -> edit. Is faster is you have it two clicks away

**Comment by LefterisJP** [comment]
yeah that would be a cool addition.
