### ISSUE TITLE
Provide more information on skipped actions and failed price queries

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3253]
## Abstract

We now have the ability to manually add historical prices in rotki if they can not be found. But it can actually be hard to find the price if not enough information can be found for the transaction/event that lead to the problem.

So more information should be provided to the user

## Task

For events that are skipped with the message `Skipping action at` add some kind of identifier. For ethereum it could be transactions, for CEXes ... it should never happen but probably use the CEX id?

For messages: `Could not query usd price for XXX and time YYY when processing EVENT NAME` also add a unique identifier in the error to help user identify it more easily.

**Comment by xtc0r** [comment]
Is there a reason **Skipping action at** uses a human readable time format and **Could not query usd price for** uses unix timestamp? Would it be possible to provide for both / all these notifications humand readable time formats?

**Comment by LefterisJP** [comment]
> Is there a reason

Yes, for developer errors timestamp is what we need. Most errors are not meant to be seen by users. Slowly as things develop some end up being seen by users even though the original intention was not that.

For example this filling of timestamps is not supposed to be manual. We are working on improving this. The form to fill in the price will be pre-filled with the assets and the appropriate time once an error pops up and you will just have to fill in the price.
