### ISSUE TITLE
macOS: Don't exit app on window close

### ISSUE THREAD

**Issue by ulope** [rotki/rotki#3258]
## Abstract

Currently on macOS rotki quits when the main window is closed.
Most other (non-document based) mac apps however keep running in the background and simply hide the window.

## Motivation

Behaving similar to other apps on the system improves UX.

## Specification

- Clicking the red close window button, selecting `Close Window` from the menu or using the Cmd-W shortcut should hide the main window and keep rotki running in the background.
- Clicking the Dock icon should show the window again
- (Optional) Provide a shortcut to show the window. Common in other apps are Cmd-0 (Zero) or Cmd-1.

**Comment by LefterisJP** [comment]
Hey @ulope thanks for using rotki :bow: 

This is a bit funny. We had it like that in the past but it ended up being counter-intuitive for some users who complained and also create some problems.

Original issue here: https://github.com/rotki/rotki/issues/779

@kelsos what do you think?

**Comment by kelsos** [comment]
I think the main reason we had this approach was because of all the other problems that we had when we resumed the session. Currently, we have ways to avoid these issues, as we do in the browser when in docker, where if you refresh the page you don't have to log in. 

My general approach with application behavior is always to try and follow the platform paradigm as it is the least confusing for the platform users due to familiarity.

I am going to put the issue for 1.21

**Comment by ulope** [comment]
Hehe, yeah finally got around to using it. Only took me 4 years or so 🙈 😀 

If I read that other issue right the previous behaviour was to kill the window and create a new one (requiring the user to login again). I agree that that would be pretty unexpected behaviour.

The difference is really about keeping vs. losing state. 
On macOS document based apps (in the wider sense) usually lose state on window close (e.g. browsers, text editors, etc.) while other apps usually retain state and simply hide / show their main window (e.g. Mail, Spotify, Slack, etc.)

**Comment by ulope** [comment]
Looks like this hasn't made it into any of the recent releases yet. Is that intentional?

**Comment by LefterisJP** [comment]
The milestone assigned to this issue is v1.24.0.  It's not released yet.

**Comment by ulope** [comment]
Ah sorry, missed that :)
