### ISSUE TITLE
Can't export CSV from the docker image

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3264]
## Problem Definition

After generating a PnL report the frontend can't export CSVs

## Logs

![image](https://user-images.githubusercontent.com/5068010/127538686-9dee1959-83c1-4ffd-b396-34007de5bb34.png)

### System Description

Operating system: Docker
Rotki version: 1.19.1

**Comment by kelsos** [comment]
The 127.0.0.1,127.0.0.1:8084 doesn't seem correct  🤣

**Comment by LefterisJP** [comment]
Not sure if we will have a v1.19.2 but put it in bugfixes.

**Comment by kelsos** [comment]
@LefterisJP we can move it if needed no worries

**Comment by LefterisJP** [comment]
We always merge bugfixes to develop anyway before the release :)

**Comment by LefterisJP** [comment]
Should be fixed by #3271
