### ISSUE TITLE
Mobile: Not all tabs in history are visible

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3268]
## Problem Definition

![image](https://user-images.githubusercontent.com/5068010/127627021-4e4da31e-d1a0-4326-bf32-e56b9ef90640.png)
### System Description

Operating system: Docker
Rotki version: 1.19.1

**Comment by kelsos** [comment]
Any suggestions on that? the tabs should be scrollable so you can scroll to the last or first but showing them all is not going to work so we need to thing of an alternative approach

**Comment by yabirgb** [comment]
> Any suggestions on that? the tabs should be scrollable so you can scroll to the last or first but showing them all is not going to work so we need to thing of an alternative approach

Maybe a dropdown menu?

**Comment by kelsos** [comment]
Yes, that could be an option. In general I don't really like the tabs at all
