### ISSUE TITLE
Improve csv export for accounting

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#3277]
## Abstract

The current csv exports provides several csv files. It is not clear for the user which one he should use to fill his tax report. In the rotki app there is a good overview in the PnL report but this is not exported into the csv export.

## Motivation

Make the csv export more user friendly to use for tax reports.

## Specification

What I would like to have:

1. One csv report with only the tax relevant things based on the settings in rotki (tax free holding period, staking hold period etc)
2. Improved format of the tax report with a summary/overview at the end like in the rotki app
3. (nice to have) Different languages selectable for the csv export to use the local names for net profit, capital gain etc.
4. (nice to have) Different csv formats to be compatible with 3rd party accounting software. I know suppporting this would lead  to creating a lot of different formats and could break if the 3rd party SW updates their import format. I checked some examples from cointracking and the csv file format is quite simple. I used the german accounting SW WISO which even has a custom button to import the cointracking data.

**Comment by LefterisJP** [comment]
The "one" csv report is always the all_events.csv
All other CSV exports are given for convenience since they contain more information, that is specific to the type of the event that is being exported. For example defi_events has a lot of extra identifying information for defi stuff.

> Different languages selectable for the csv export to use the local names for net profit, capital gain etc.

That would have to come with internationalization of the app. But yes this should be possible, when we internationalize.

> (nice to have) Different csv formats to be compatible with 3rd party accounting software. I know suppporting this would lead to creating a lot of different formats and could break if the 3rd party SW updates their import format. I checked some examples from cointracking and the csv file format is quite simple. I used the german accounting SW WISO which even has a custom button to import the cointracking data.

As you can guess this is hard and depends per the software in question. WISO, quickbooks, xero ... so many tools. For each one of them we would have to have a separate issue and probably support/funding/enough people asking for it to be able to do it.

**Comment by xtc0r** [comment]
In the all_events file there is a column E "taxable amount". A pure taxable event file could be created by filterting this.

For the 3rd party csv format I know it's hard as a lot of 3rd party apps exists.

Here is the header of the csv file WISO can import to give you an impression:

![image](https://user-images.githubusercontent.com/36508484/127717099-0ecc57cc-f235-4f86-998f-2a54243c686b.png)

I understand that this needs to be prioritized based on customer requests.

**Comment by xtc0r** [comment]
I mainly miss to easily find the summary of PnL report back in the csv file:
![image](https://user-images.githubusercontent.com/36508484/127718059-1b091621-6b0d-441a-af68-a40f149b3f48.png)

That's an example how other tools provide a summary in the csv.

![image](https://user-images.githubusercontent.com/36508484/127718477-c52bcd87-b6d9-49a6-9673-91fcad1a65d9.png)

**Comment by LefterisJP** [comment]
> I mainly miss to easily find the summary of PnL report back in the csv file:
> ![image](https://user-images.githubusercontent.com/36508484/127718059-1b091621-6b0d-441a-af68-a40f149b3f48.png)
> 
> That's an example how other tools provide a summary in the csv.
> 
> ![image](https://user-images.githubusercontent.com/36508484/127718537-7b7ebdd6-b071-4170-945d-5e4433bac298.png)

I see. Thanks. Such summaries though turn the file to no longer be a CSV.

A CSV should be a simple file of comma separated values. Having a summary at the end and different lines like that make it an invalid CSV.

What you are looking for is some additional kind of export.

These are sums you should do yourself by summing up the appropriate lines. Perhaps we can give some guidance there, or just append this at the very end and try to see if we can add them. I will have to think and experiment.

Whenever I gave this to my accountant they just added another line at the end after importing to a spreadsheet and did the sumup there.

**Comment by LefterisJP** [comment]
Points 1 & 2 are addressed, some even before v1.24. For the rest still would need some work and better specification of what exactly and how it should be customized but should be doable. But better in different issues.
