### ISSUE TITLE
Add summary in the all_events.csv file

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3279]
## Abstract

As per [this](https://github.com/rotki/rotki/issues/3277#issuecomment-890223525) comment user would like to have a summary of the pnl, much like the one seen in the PnL report at the UI.

![127718537-7b7ebdd6-b071-4170-945d-5e4433bac298](https://user-images.githubusercontent.com/1658405/127719026-ef41d1c3-ea3b-43c3-bdef-742c6044990e.png)

## Task

Try to see if it's possible and if yes do it.

**Comment by xtc0r** [comment]
I compared the summary in all_events.csv and inside the rotki app. It does not match.

**Comment by LefterisJP** [comment]
As discussed in discord this is most probably due to differences in formulas between libre office and gsheets.

We will figure it out and see how we can improve or fix any bugs by filing new issues.
