### ISSUE TITLE
Design feedback/ideas

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#3283]
## Abstract

This Issue tracks various design feedback and ideas.

## Specification

1. Avoid showing user the standard theme after login, if he had selected a custom theme.
2. Information of the portfolio is quite spread over several sub menus. Could we put more information regarding assets, LP pools, staking pools, vaults, validators, masternodes etc in the dashboard? Maybe just give rough net value information and make eacht asset and position clickable to open a detail view for this specific asset / position. Currently to check a CDP the user has to know he has to go to Defi --> Liabilities (not deposit) and then look for the dropdown menu and if he does not know the CDP number he has to try one after the other. Would be better if all CDPs were listed in the dashboard with deposit, borrowed asset, collateral ratio and CDP number. If he clicks it the detailed view would open.
3. Dashboard has a lot of space between the columns of the tables. e.g. Assets table: Asset, Price, Amount.  
4. Exchange, blockchain, manual balances in dashboard: Space between Exchange Balances and amount could be smaller to fit additional pie? chart next to it
5. Space between exchange balances and assets could be smaller
~~6. Remove the title **Dashboard** from the top to save space. It's already highlighted in the navigation menu on the left~~

**Comment by kelsos** [comment]
Thanks again for the feedback @xtc0r we will go through and discuss the feedback and then we will proceed to create actionable items from this

**Comment by kelsos** [comment]
Point 6 was addressed in the mobile PR. most of the titles are now removed.

**Comment by kelsos** [comment]
@lukicenturi do you think we still have actionable points here? if not we should proceed to close the issue

**Comment by LefterisJP** [comment]
Since there has been no answer I will just assume you have moved all points to different issues.

@lukicenturi @kelsos please make sure to answer each other's pings :wink:
