### ISSUE TITLE
Evaluate the idea of adding some basic integration with cryptoscamdb

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3285]
## Abstract

See if it is possible to integrate with CryptoScamDB in a way to provide warnings to the users about possible scam assets.

**Comment by LefterisJP** [comment]
We have already done that. Their api does not work yet properly. When they do we can just update our code. Should we close this @yabirgb ?

**Comment by yabirgb** [comment]
Yes I would just close since the integration is done and the problem is in the data we obtain. Upgrading the code when the V2 comes is enough. Closing it for now
