### ISSUE TITLE
Failed fetching exchange rates

### ISSUE THREAD

**Issue by marcimarc16** [rotki/rotki#3297]
Hi, I'm a newbie, using rotki since yesterday. Today I'm getting this message and the Dashboard won't show the total amount:

> Failed fetching exchange rates: {"currencies": {"6": ["Unknown asset CAD provided."], "9": ["Unknown asset BRL provided."]}}

I haven't even heard of "CAD" or "BRL" before but I deleted a bunch of assets in the tool, hoping to speed things up with that. Could this be the reason for the message?

BR

**Comment by LefterisJP** [comment]
Hello @marcimarc16 and welcome to rotki! Lovely to hear about the experience of new users :)

Deleting assets like that won't help you. And yes the reason for this is you deleted some basic FIAT assets. Please don't do that :sweat_smile: 

The best way around this now is to delete your global DB and let it be recreated. Follow these steps:

1. Close the app.

2. To find the global DB, find the rotki data directory according to this section: https://rotki.readthedocs.io/en/latest/usage_guide.html#rotki-data-directory

And then delete `global_data/global.db

3. Then reopen the app and the problem should go away.

Also for simple questions like that make sure to join our discord chat and ask there: https://discord.gg/aGCxHG7
Keep in mind there is a captcha bot at joining!

Let me know if this solves your issue so we can close it.

**Comment by marcimarc16** [comment]
That worked, thanks a lot. Will keep all assets in the future ;o)

**Comment by LefterisJP** [comment]
Great! Thanks @marcimarc16! And hope to see you in our discord :hugs:
