### ISSUE TITLE
Clicking on assets (base/quote) in a trade should take you to the asset page

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#3304]
## Abstract

In deposits & withdrawals clicking an associated token under `Asset` will take you to that tokens page (I think this is a nice featured & desired). When clicking the tokens in Trades, for example, (either `Base` or `Quote`) nothing happens. We should make this behavior consistent across the app. Similarly, in "trades" perhaps we should be able to click the "Location" and be taken to the relevant section of the app (if there is one), e.g. clicking "Coinbase" in trades would take us to the Coinbase exchange page (usually accessed via the Dashboard).

**Comment by LefterisJP** [comment]
Hey @isidorosp. Thanks for the issue. I think you are right on:

> When clicking the tokens in Trades, for example, (either Base or Quote) nothing happens. We should make this behavior consistent across the app

So perhaps let's keep this issue for this.

Having a navigation action when clicking on Location is not a bad idea but not sure where it should take you (for most locations) so perhaps something to think more about.

**Comment by isidorosp** [comment]
> Hey @isidorosp. Thanks for the issue. I think you are right on:
> 
> > When clicking the tokens in Trades, for example, (either Base or Quote) nothing happens. We should make this behavior consistent across the app
> 
> So perhaps let's keep this issue for this.
> 
> Having a navigation action when clicking on Location is not a bad idea but not sure where it should take you (for most locations) so perhaps something to think more about.

Sure let's think about it and make issues for specific implementation as needed.

I did a quick look and made a draft of the list of tables with an asset listed where in theory the asset could be "clickable" and currently isn't
* DeFi -> Protocols -> History table
* DeFi -> DEX Trades
* DeFi -> Airdrops
* History -> Trades

**Comment by kelsos** [comment]
Can we open a new issue about the location part? since it is a bit more complicated?

**Comment by kelsos** [comment]
The Trades is the easiest and most straightforward one.  

For the others @isidorosp for airdrops you mean the part of the amount display that displays the asset?

![image](https://user-images.githubusercontent.com/2269732/132850955-f7cd2190-b511-43b8-9b6e-ac7291a2efee.png)

And also for dex trades and the protocols history table, I guess clicking on the icon would be the best place to do something like that right?

![image](https://user-images.githubusercontent.com/2269732/132851170-186d58a4-45f2-4c9d-a0ac-1e3a5d3011b6.png)

@LefterisJP any comments?

**Comment by kelsos** [comment]
I am gonna skip airdrops at the moment since it is a bit more complicated to do it.

It requires some extra refactoring since the asset is rendered via the `AmountDisplay.vue` component. We need to be careful so that it doesn't affect all the places where we use the amount display.
