### ISSUE TITLE
Add support for bentobox

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3305]
## Abstract

Add support for sushi's bentobox

## Specification

A subgraph can be used for this https://thegraph.com/legacy-explorer/subgraph/sushiswap/bentobox

**Comment by LefterisJP** [comment]
Is this still alive? Should we close the issue?

**Comment by yabirgb** [comment]
Closing as it is deprecated and it didn't saw much traction https://app.sushi.com/bentobox. We can re-evaluate if someone asks for it
