### ISSUE TITLE
Add support for the new Yearn v2 yvDAI vault

### ISSUE THREAD

**Issue by benjaminion** [rotki/rotki#3306]
## Abstract

Around 4 weeks ago Yearn introduced a new yvDAI v2 vault and encouraged everyone to migrate from the old yvDAI v2 vault. The original yvDAI v2 vault is now deprecated.

I migrated my yvDAI to the new vault and cannot see it in Rotki (v1.20.0, premium subscription).

## Motivation

I wish to see my new yvDAI v2 vault deposit in Rotki.

## Specification

I believe the vault addresses are as follows:
  - Old, deprecated yvDAI v2 vault: 0x19D3364A399d251E894aC732651be8B0E4e85001
  - New yvDAI v2 vault: 0xdA816459F1AB5631232FE5e97a05BBBb94970c95

**Comment by LefterisJP** [comment]
Hey @benjaminion thanks a lot for your issue. We will look it up and put this in the pipeline if indeed it's missing.

Pinging @yabirgb for this.

Should this be a bugfix or is it just missing? I thought we supported all v2 vaults.

**Comment by benjaminion** [comment]
Thanks! I should add that I got this notification in Rotki. Not sure if it is connected with the above or not:

> Ignoring deposit in yearn vaults V2 from DAI to yvDAI because the token is not recognized.

**Comment by yabirgb** [comment]
Thanks for letting us know @benjaminion !
I'm currently not with my laptop but I believe that if you manually add the token to the rotki assets (from the manage assets section) and use `yearn_vaults_v2` in the protocol field it should work. Not sure if you will need to purge data from the yearn_v2 module if some transactions are missing

**Comment by benjaminion** [comment]
OK - will give it a whirl. Thanks.

**Comment by benjaminion** [comment]
Excellent - finally figured it out 🙂 For the record I needed to restart Rotki to get the vault to show up, but all is good now. I used the existing yvDAI assets as a template for the settings.

Thanks for the help. I'll leave this issue open until the new vault is added by default - feel free to close it then.

**Comment by yabirgb** [comment]
Already in the database. Thansk for reporting it
