### ISSUE TITLE
Show Cost Basis in Each Asset in Dashboard

### ISSUE THREAD

**Issue by dcato98** [rotki/rotki#3319]
## Abstract

Add column for cost basis on each asset on the list of assets in the dashboard.

## Motivation

Adding this column would help users quickly evaluate their performance as well as being a really big step towards estimating tax consequences of selling assets. 

This is closely related to issue / feature request #701 which proposes adding columns for 'profit/loss %' and 'tax free after period'.

**Comment by LefterisJP** [comment]
Hey @dcato98! Thanks for the issue man! Isn't it actually exactly the same though as #701? Or what exactly is different between this one and that one?

**Comment by dcato98** [comment]
Oh wow, yes! I wrote this up too quickly - I meant to say "Cost Basis" column. I'm going to edit my original comment and the issue title so your previous comment might not make as much sense.

**Comment by LefterisJP** [comment]
I think that both can be done as part of that issue as once the base requirements for calculating and adding those overlays there are calculated many different numbers could be added on the dashboard.

Anyhow going to leave this open for now and see how development on that feature evolves.

**Comment by LefterisJP** [comment]
closing in favor of #701
