### ISSUE TITLE
Support marking eth2 validators as jointly-held

### ISSUE THREAD

**Issue by gnidan** [rotki/rotki#3324]
## Abstract

Rotki currently accounts for all accounts and positions held by those accounts as held solely by the user. This precludes use cases where a single account may represent assets owned by more than one party (e.g. going halfsies on an Eth2 validator).

## Motivation

For users who participate in jointly-owned accounts, it's not possible to rely on Rotki to provide precise accounting that reflects the user's net holdings. This adds overhead for users seeking accurate reporting: wait for Rotki to load, then add or subtract the right values for each joint position. This is particularly annoying when the underlying asset balance isn't fixed, e.g. for a jointly-held Eth2 validator, one must halve staking rewards each day, etc.

## Specification

As a potential solution, Rotki could expose settings to mark an account as partially-owned, e.g. to say that only 50% of all assets in an account belongs to the user. This could be extended to individual positions, not only entire accounts (but maybe this level of precision is not required).

**Comment by LefterisJP** [comment]
Hmm ... that should not be too hard to implement, just quite a bit of work touching many places.

Weird to hear though. Nobody has ever mentioned/hinted for such a feature before :sweat_smile:

**Comment by gnidan** [comment]
> Nobody has ever mentioned/hinted for such a feature before 😅

I'm not surprised, really. I don't imagine that a lot of people need this feature, and those that do probably wouldn't think to ask. But heck, it'd be really useful... I'm sick of the mental math, and I only have one jointly-held position! (But really, I only dare ask for this feature now that you're really starting to spoil me with how complete Rotki is getting :)

**Comment by LefterisJP** [comment]
The % of an eth2 validator owned will be part of next release (hopefully). Completely forgot there was an issue for this.
