### ISSUE TITLE
Assets 1.21

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3333]
- PERX has an error in the number of decimals `9->18`
- Update yearn assets as per #3306

**Comment by LefterisJP** [comment]
Also don't forget all other issues with the asset label

**Comment by LefterisJP** [comment]
Add:

Oiler: https://www.coingecko.com/en/coins/oiler

**Comment by LefterisJP** [comment]
Add:

Cards:
https://etherscan.io/token/0x3d6f0dea3ac3c607b3998e6ce14b6350721752d9?a=0x144a8708f676de1627f6fd610d77583196b182cc

C3:
https://etherscan.io/token/0xf1a91c7d44768070f711c68f33a7ca25c8d30268?a=0x144a8708f676de1627f6fd610d77583196b182cc

**Comment by LefterisJP** [comment]
Add: 

AXS: https://www.coingecko.com/en/coins/axie-infinity


--- ERC721 ---
But the interface seems to at least comply to ERC20 too
SOCKS: https://www.coingecko.com/en/coins/unisocks

**Comment by LefterisJP** [comment]
Hey @yabirgb Since these assets made it int v1.20.1and not 1.21 do you want to keep these issue and add more assets below here? Or make another one?

**Comment by yabirgb** [comment]
Yes we can keep it. I tag with a :rocket: what has already been done so no problem

**Comment by yabirgb** [comment]
Convex crv has no coingecko id `convex-crv`

**Comment by LefterisJP** [comment]
> Convex crv has no coingecko id `convex-crv`

this you are adding as a todo-fix, right?

**Comment by yabirgb** [comment]
@LefterisJP Yes, just found that I had some and was not being tracked

**Comment by yabirgb** [comment]
https://www.coingecko.com/en/coins/tokenclub

**Comment by yabirgb** [comment]
Closed by #3517
