### ISSUE TITLE
Support new asset: wCFG

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#3339]
**Asset name:** Wrapped Centrifuge
**Asset symbol:** wCFG
**Coingecko link:** https://www.coingecko.com/en/coins/wrapped-centrifuge
**Cryptocompare link:** https://www.cryptocompare.com/coins/wcfg/overview

**Comment by LefterisJP** [comment]
Thank you fren @hjorthjort! Will add it in next assets update.

Question: What's the difference with the normal centrifuge? They differ in price too it seems.

https://coinmarketcap.com/currencies/centrifuge/

**Comment by hjorthjort** [comment]
Looks like the prices correlate really well to me, I assume the differences are basically die to reporting delays from exchanges and DEXes, or arbitrage being slow. 
https://docs.centrifuge.io/use/cfg-bridge/

**Comment by LefterisJP** [comment]
Should be handled by #3363
