### ISSUE TITLE
Docker no Browser Bar Icon

### ISSUE THREAD

**Issue by Cebrain** [rotki/rotki#3340]
## Problem Definition

The Web Browser shows no Icon of Rotki
Would be great if the integrated proxy could show a icon (identification of correct tab would be easier)

### System Description
Docker Container latest Rotki Version
Browser Firefox

Operating system: 
Rotki version: 1.20

First Tab Pinned Rotki Tab, Second Tab normal Tab with Rotki

![image](https://user-images.githubusercontent.com/78339531/129472594-5a3cedc0-6226-4efb-b1a3-bba322ac304a.png)

**Comment by LefterisJP** [comment]
Hey @Cebrain thanks for the issue! That's funny I thought there was one. Would have to check again.

@kelsos don't we have a favicon for docker?

**Comment by kelsos** [comment]
we should have one but maybe there is something wrong with the config?

**Comment by yabirgb** [comment]
> we should have one but maybe there is something wrong with the config?

I've checked in my instance and there is no request for any icon. I believe it never does the request so maybe is missing in the html

**Comment by kelsos** [comment]
> > we should have one but maybe there is something wrong with the config?
> 
> I've checked in my instance and there is no request for any icon. I believe it never does the request so maybe is missing in the html

No this is not what happens. So the icon works fine when using chrome. On the other hand Firefox tries to get the 32x32.png icon, but it tries to load it from the wrong directory.

**Comment by kelsos** [comment]
There is a change that this is some vue-cli configuration issue.

**Comment by kelsos** [comment]
It was a configuration issue with the pwa plugin of vue-cli
