### ISSUE TITLE
Add ICO/IEO/lockdrop

### ISSUE THREAD

**Issue by ohadbachner** [rotki/rotki#3346]
## Abstract

I will like to add a feature that will help you to flow your ico/ieo/lockdrop 
## Motivation

I think that will help many users

**Comment by LefterisJP** [comment]
Hello @ohadbachner, thanks for using rotki!

If I understand what you need correctly, then that feature already exists.

You can add any ICO or airdrop or lockdrop or whatever you want through either a manual trade entry or a ledger action.

Refer to the usage guide for [adding manual trades](https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-manual-trades) or [ledger actions](https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-ledger-actions)

If the above answers your question feel free to close the issue.

**Comment by LefterisJP** [comment]
Closing the issue since without any answer from the user I assume my response is satisfactory.
