### ISSUE TITLE
Rotki doesn't start anymore (SIGTRAP, undefined symbol: g_task_set_name)

### ISSUE THREAD

**Issue by ErikBjare** [rotki/rotki#3348]
## Problem Definition

Rotki no longer starts on my machine since a few weeks back (Arch Linux). It seems to be version-independent (I've tried with versions as old as v1.11) and it used to work fine.

It's probable that the issue is not in Rotki itself, but instead my system config, but I thought I'd make an issue here anyway since I didn't find any similar reported issues.

## Logs

```
$ ./rotki-linux_x86_64-v1.20.0.AppImage
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so

(rotki:452653): GdkPixbuf-WARNING **: 15:07:58.277: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
fish: Job 1, './rotki-linux_x86_64-v1.20.0.Ap…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

The `/usr/lib/gvfs/libgvfscommon.so` file exists, but the `/usr/lib/x86_64-linux-gnu` folder does not. I do however have a `/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache` file.

The suggested command did not work, but I ran the following:

```sh
sudo mkdir -p /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/
gdk-pixbuf-query-loaders | sudo tee /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
```

However, Rotki still crashes, although with a shorter log:

```
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
fish: Job 1, './rotki-linux_x86_64-v1.20.0.Ap…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

### System Description

Operating system: Arch Linux
Rotki version: v1.20 (but the issue is present for older versions too)

**Comment by kelsos** [comment]
Hey, @ErikBjare I am googling about it since I have never encountered this issue before. Let's see if we can figure out something.

It seems like a system configuration issue indeed. Both me and @LefterisJP are also on Arch and we have not encountered the issue before.

**Comment by ErikBjare** [comment]
Well, this is embarassing.

I was running Rotki directly from my downloads folder, which had some `lib*.so` files in it... It runs fine after I moved the executable.

Lesson learned: don't run executables from your downloads folder.

**Comment by kelsos** [comment]
No worries, things like this can happen. I am glad you managed to figure it out though. I know that these situations can be extremely frustrating.
