### ISSUE TITLE
In DeFi deposits dont show yearn vaults if nothing is there

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3352]
## Problem Definition

At DeFi deposit sections if the user's accounts have no yearn vaults deposits then an empty table should not appear there.

![2021-08-19_18-40](https://user-images.githubusercontent.com/1658405/130109249-665e44e9-92e9-44f6-9f3a-ad682ae4b59a.png)

## Task

Fix it. -- put it in 1.20.1 and probably no need to even changelog it.

**Comment by kelsos** [comment]
This change needs to be done in the premium components since this is a self-contained component.
A change in behavior is also needed. 

By default now the component will display a loading bar when loading. With the new approach is should not appear at all unless it has any data.
