### ISSUE TITLE
Unsupported BCHN in Bitfinex is being mistakenly shows as BCH,

### ISSUE THREAD

**Issue by rafaeltcc** [rotki/rotki#3354]
## Problem Definition

Unsupported BCHN in Bitfinex is being mistakenly show as BCH, Bitcoin Cash, making me a rich me for about 10 seconds till I found out the mistake.

## Logs

Found unsupported Bitfinex 1 asset BCHN due to: Found asset BCHN which is not supported.. Ignoring its balance query.

### System Description

Operating system: Linux Arch 
Rotki version: 1.20.0-1

**Comment by LefterisJP** [comment]
Hey rafaeltcc, thank you for the issue. Mappings of symbols from exchanges is always hard as they just use a symbol and there can be clashes as happened here.

So let me understand. Can you point me to coingecko's page of the asset that we are mistakenly mapping to BCH? I can't find an asset with a symbol BCHN in coingecko.

**Comment by seanPhill** [comment]
"BCHN" *is* BCH. The other half of that fork lost the BCH ticker, became (depending on who you talk to) "BCHA" or "BitcoinABC" or "BitcoinCashABC" and recently renamed to **eCash** and moved the decimal place to multiply the apparent balances by 10,000.

**Comment by LefterisJP** [comment]
> "BCHN" _is_ BCH. The other half of that fork lost the BCH ticker, became (depending on who you talk to) "BCHA" or "BitcoinABC" or "BitcoinCashABC" and recently renamed to **eCash** and moved the decimal place to multiply the apparent balances by 10,000.

Oh I see. So bitfinex changed the ticker to BCHN.

![2021-08-23_13-35](https://user-images.githubusercontent.com/1658405/130440794-e9a67065-2476-47b4-93a3-0467c4519479.png)


Great. As you can see only bitfinex and some exchange called ZB uses a different ticker for BCH.

We will need to remap it for that exchange then.

**Comment by LefterisJP** [comment]
Fixed by #3363
