### ISSUE TITLE
Adjust hover tooltip on asset charts to not block graph view.

### ISSUE THREAD

**Issue by chetaget** [rotki/rotki#3411]
## Problem Definition

When looking at the charts for assets in Rotki, the hovering information covers the point you are over in the chart, which makes it hard to look at a certain point and be sure you are on it. Would having that hovering information bind its upper corner (left or right depending on where it is on the page) to the bottom of the cursor be possible ? this should give ample room to view the chart and still display that information ?

Present on both Safari and Brave browser across both Windows and MacOs.

![Screen_Shot_2021-09-02_at_7 51 31_PM](https://user-images.githubusercontent.com/68872377/132077092-82de21e1-1eba-4b8c-8499-a01be4d2932b.png)

Operating system: Windows 10 & MacOs
Rotki version:1.20

**Comment by kelsos** [comment]
MR has been approved for premium components
