### ISSUE TITLE
Allow ledger actions to not be ignored when there is no market price

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#3413]
## Abstract

This is more of an open question than a feature request. How should be deal with ledger actions without market price?

## Motivation

Suppose the user has received some asset when there was no market value of that said asset (because trading has not begun). Currently the added ledger action of the reception gets ignored in the final report, because no market price can be found. Even if the user adds a manual price of 0.0 (which may be impossible via UI), the action gets ignored.

## Specification

I don't know how/if this should be implemented.

**Comment by LefterisJP** [comment]
Ledger actions no longer exists
