### ISSUE TITLE
Export notifications button

### ISSUE THREAD

**Issue by baltcoinh** [rotki/rotki#3415]
## Abstract

When you have been using multiple exchanges, some of them not available in the app, you can find you have a lot of alerts about transactions you have to justify their origin when launching a profit and loss report. A easy to see list of those alerts would be appreciated. Because copy and paste 150 notifications is too copy and paste :)

## Motivation

With this kind of txt or csv file (not sure what format could be more useful) you can find and include manually this ledger, trade transactions in a lot easier way.

## Specification

Simple solution, a button which allows to export all the notifications to a txt file putting a CR,LF between each notification.
Avanced solution, a csv with an initial description field (type of notification), detailed description (type of problem), and if needed asset, quantity date and so on.

**Comment by LefterisJP** [comment]
There is no need to export these notifications. They are all already logged in the debug logs. Simply acivate logs and check out the logs: https://rotki.readthedocs.io/en/latest/contribute.html#id2

If this is good enough for your purposes please close the issue.

**Comment by LefterisJP** [comment]
I take the lack of a response as affirmative so I am going to go ahead and close the issue.
