### ISSUE TITLE
Crypto.com fail import

### ISSUE THREAD

**Issue by schklom** [rotki/rotki#3418]
## Problem Definition

Importing crypto transactions from Crypto.com app gives the error `Invalid CSV format, missing required field: Crypto.com csv missing entry for 'credited'`.
Debit card transactions work fine, but not crypto transactions.

## Logs

[rotkehlchen.log](https://github.com/rotki/rotki/files/7110897/rotkehlchen.log)

### System Description

Operating system: Windows 10
Rotki version:
```
App Version: 1.20.1
Frontend Version: 1.20.1
Platform: win32 x64 10.0.19042
Electron: 13.1.4
```

**Comment by LefterisJP** [comment]
Hey @schklom can you let us know if this is from the mobile app? Only the mobile app is supported for importing.

Also it seems that crypto.com change their format quite often or add new entries oftern. Could this and https://github.com/rotki/rotki/issues/3056 be related @yabirgb? Both are still open issues.

@schklom probably both issues are related. What would really help us is if you can give an example CSV with column names and few example rows here so we can fix it.

**Comment by schklom** [comment]
@LefterisJP I only tried the Windows 10 app so far. Importing the card transactions went well.

Here is an example where almost each line has a different "Transaction Kind" (i think that's all of them).
Timestamps and amounts are not original.
[crypto_transactions_record_20210905_123054.csv](https://github.com/rotki/rotki/files/7111594/crypto_transactions_record_20210905_123054.csv)

PS: Searching "Rotki" on the Play Store and F-droid gives me nothing, where can I find the mobile app? :P

Thanks for the speedy reply :D

**Comment by schklom** [comment]
@LefterisJP After checking, the card transactions also bug, nothing gets actually imported. However, they only give a warning instead of an error:
```
Unknown entrype type "" encountered during cryptocom data import. Ignoring entry
```

**Comment by LefterisJP** [comment]
What do you mean by Windows 10 app? They got a Windows app too? Crypto.com import should only work for the crypto.com mobile app as far as I know. This is the only CSV import we have implement as of now.

![2021-09-05_18-03](https://user-images.githubusercontent.com/1658405/132133510-85c8932c-4735-4091-99a6-df7eb32acf09.png)

If you tried to import a CSV from another app then it would make sense for the import to fail.

**Comment by schklom** [comment]
There's a misunderstanding ^^
I meant the Rotki Windows 10 app, and the mobile Crypto.com app

I thought you meant there was a Rotki mobile app I hadn't heard of

**Comment by yabirgb** [comment]
Thanks @schklom for the report. Will try to take a look tomorrow :)

**Comment by yabirgb** [comment]
@schklom I was trying to import the csv file but the timestamp is in an incorrect format. did you change it? or is crypto.com changing the format?

**Comment by schklom** [comment]
@yabirgb I changed the dates and amounts to avoid making my real data public, but kept the format.
Maybe crypto.com added a space `21/08/2021  11:47:00` compared to last time?

**Comment by yabirgb** [comment]
> @yabirgb I changed the dates and amounts to avoid making my real data public, but kept the format.
> Maybe crypto.com added a space `21/08/2021 11:47:00` compared to last time?

The format we had was `2020-08-11 09:56:14`... this will be a problem :sweat_smile:

**Comment by schklom** [comment]
I am in the EU. Does your format come from the US? ^^

A long-term solution can be to let the user define the date and time format.

**Comment by LefterisJP** [comment]
> I am in the EU. Does your format come from the US? ^^
> 
> A long-term solution can be to let the user define the date and time format.

This not on rotki's side. This is on crypto.com's export. We rely on user reported data in order to figure out how the CSV is formatted. Afaik the other users who use it are also in Europe.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/3424

**Comment by schklom** [comment]
> This not on rotki's side. This is on crypto.com's export.

@LefterisJP Sorry for the necro-post and delay. :P\
I meant you can let the user decide ***the date format rotki will use*** when importing.\
That way, users can change how rotki will read the file.

This would solve the issue of Crypto.com deciding to update its format again.
