### ISSUE TITLE
Support Arbitrum

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#3420]
## Abstract

Get Ethereum Layer 2 (L2) transactions made on Arbitrum One L2 network into trade history

## Motivation

As Arbitrum One picks up steam with their mainnet launch (on 1 Sep 2021) and very generalized universal optimistic rollup EVM on L2--technically a continuation of their beta since they are [leaving the "beta" moniker on until full decentralization](https://offchain.medium.com/mainnet-for-everyone-27ce0f67c85e)--they are already supporting a transaction throughput capability about equal to the entire Ethereum L1 mainnet.  

I imagine there will be a lot of Rotki users who will have accounting data missing until Rotki supports Arbitrum L2 trades.  So that is the motivation.  

(to be prioritized, of course, by the triage ordering of _Team Rotki_ amongst all the many good things to enhance in Rotki)

**Comment by A2be** [comment]
`L2beat.com` is reporting that Arbitrum is up to US$2.3 billion total value locked now, just two weeks after the kickoff on mainnet.  [Arbitrum page on L2beat](https://l2beat.com/projects/arbitrum/)

**Comment by randomishwalk** [comment]
Any update on arbitrum support @LefterisJP?

**Comment by LefterisJP** [comment]
This has been completed and is right now in https://github.com/rotki/rotki/releases/tag/v1.30.0
