### ISSUE TITLE
Binance exchange settings: Accept multiple pairs entered at once

### ISSUE THREAD

**Issue by frysee** [rotki/rotki#3425]
## Problem Definition

Due to the current limitations on importing past trades from binance (#3412), the only reasonable way to get something imported without running into timeouts is by maintaining an explicit allow list (https://discord.com/channels/657906918408585217/745172610240872508/884726268027875398).

The current UI accepts pairs entered one-by-one, offering an autocomplete drop-down that has to be clicked to add the matching pair from an API-queried list to the line edit. This works reasonably well for a handful of pairs, but especially when algorithmic trading is involved there might be 100+ pairs to be entered here. 

I expected to be able to batch-add a number of pairs by pasting a space-separated string with different pairs (e.g. "BTCUSDT ETHUSDT SOLUSDT"), but pressing "Save" only ends with ~~an endless progress bar that only stops when closing the app. In addition to that, the "Cancel" button is also disabled, making it impossible for the user to get out of the "in progress" state.~~ the overlay closing and discarding the entered list of pairs.

Edit: endless progress bar was from Binance API rate-limiting, disregard that.

### System Description

Operating system:  Win10
Rotki version: 1.20.1

**Comment by LefterisJP** [comment]
Hey @frysee thanks for taking the time to write up an issue.

 We will see if this can be implemented on our side. @yabirgb what do you think?

**Comment by yabirgb** [comment]
@yabirgb I implemented that form once that kelsos was not available I believe. It makes sense to have something like in the ethereum address addition where we allow pasting several addresses at the same time. 

About the behaviour with the buttons I don't remember exactly how they work so I would need to take a look.

With a quick talk to clarify a couple of things I can try to go ahead and fix it or leave to @kelsos . I believe is mostly or completely work in the frontend

**Comment by kelsos** [comment]
Does the backend endpoint support multiple pairs? is the limitation only frontend?

**Comment by yabirgb** [comment]
Yes the backend allows multiple at the same time, is more a limitation in the frontend, I used the same selector as in tags and this is slower to select many pairs

**Comment by LefterisJP** [comment]
> Does the backend endpoint support multiple pairs? is the limitation only frontend?

Yep it does. See this endpoint and specifically the `"binance_markets"` key.
