### ISSUE TITLE
Gitcoin API tests are failing since API started rounding results

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3434]
## Problem Definition

![2021-09-09_18-10](https://user-images.githubusercontent.com/1658405/132723177-730b74b9-e950-440f-972c-a793bd99c7b4.png)

The gitcoin queries:

```
DEBUG    rotkehlchen.chain.ethereum.gitcoin.api:api.py:149 Greenlet-0: Querying gitcoin: https://gitcoin.co/api/v0.1/grants/contributions_rec_report/?id=149&from_timestamp=2017-09-25&to_timestamp=2017-09-25
DEBUG    rotkehlchen.chain.ethereum.gitcoin.api:api.py:149 Greenlet-0: Querying gitcoin: https://gitcoin.co/api/v0.1/grants/contributions_rec_report/?id=149&from_timestamp=2021-06-01&to_timestamp=2021-06-10&page=1&format=json
DEBUG    rotkehlchen.chain.ethereum.gitcoin.api:api.py:149 Greenlet-0: Querying gitcoin: https://gitcoin.co/api/v0.1/grants/contributions_rec_report/?id=149&from_timestamp=2021-06-01&to_timestamp=2021-06-10&page=2&format=json
```

Test in question:

https://github.com/rotki/rotki/blob/9e82fa138dc7e82c20fc10220cbe58ba846c0547/rotkehlchen/tests/api/test_gitcoin.py#L20

Example transaction that is rounded up: https://zkscan.io/explorer/transactions/8ee8bfe2d07a0a9192549725aa3d3dcf78b7913a6bf187895c2510fb058ed314

Correct amount:  0.000475 ETH
Returned amount: 0.0005 ETH

Lots of errors like that.

## Task

Make gitcoin fix their API and then unskip the tests.

**Comment by kelsos** [comment]
@LefterisJP this issue doesn't make sense anymore right, considering we removed the Gitcoin API integration?

**Comment by LefterisJP** [comment]
> @LefterisJP this issue doesn't make sense anymore right, considering we removed the Gitcoin API integration?

Yes closing
