### ISSUE TITLE
Cex synchronization

### ISSUE THREAD

**Issue by Morwena0** [rotki/rotki#3448]
I add my binance, ftx and kucoin account. First day everything was fine. But next day it was all gone

Operating system: Windows 10
Rotki version:1.20.1

**Comment by LefterisJP** [comment]
Thank you for the report. But without any errors or any logs we can't help you.

 Both this and your other issue sound like you are having network connectivity issues. Please [enable](https://rotki.readthedocs.io/en/latest/contribute.html?#id2) debug logs, run rotki again and send us the logs. It's best to [join discord](https://discord.com/invite/aGCxHG7) to send them via DM or you email at support@rotki.com.

**Comment by LefterisJP** [comment]
The problem seen by the user was https://github.com/rotki/rotki/issues/3463

Also found some nice changes we can do in kucoin which I already did in bugfixes.
