### ISSUE TITLE
Adding Blockchain Address 

### ISSUE THREAD

**Issue by Morwena0** [rotki/rotki#3449]
Trying to add blockchain address but "Adding ETH Account" never ends. Wait for 6 hours and it was still same.

Operating system: Win 10
Rotki version:1.20.1

**Comment by LefterisJP** [comment]
Thank you for the report. But without any errors or any logs we can't help you.

 Both this and your other issue sound like you are having network connectivity issues. Please [enable](https://rotki.readthedocs.io/en/latest/contribute.html?#id2) debug logs, run rotki again and send us the logs. It's best to [join discord](https://discord.com/invite/aGCxHG7) to send them via DM or you email at support@rotki.com.

**Comment by LefterisJP** [comment]
The problem seen by the user was https://github.com/rotki/rotki/issues/3463.
