### ISSUE TITLE
CTX (CarTaxi Token) wrong price per token

### ISSUE THREAD

**Issue by karvounis** [rotki/rotki#3462]
## Problem Definition

The dashboard shows that the token price for CTX (CarTaxi Token - https://coinmarketcap.com/currencies/cartaxi-token/) is 25 euros per token and the total amount is around 109k euros. However, the price per token is nowhere near the real price of this token but closer to another token listed as CTX which is Cryptex Finance (https://coinmarketcap.com/currencies/cryptex-finance/). Its price at the moment is 29.90$ which is around 25 euros. As you can imagine, the total amount of this token totally distorts the total value of my account.
I was wondering whether Rotki queries the APIs, that gets the prices per token from, with the token symbol like CTX.

**Comment by LefterisJP** [comment]
Hello @karvounis where do you hate this token in? Is it in an exchange and if yes which one?

**Comment by yabirgb** [comment]
Hello @karvounis Thanks for reporting this issue. Indeed the price for this asset is queried from cryptocompare but seems that they changed the ID at some point or we got it wrong at the beginning.

You can edit the asset https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset and replace the cryptocompare id  `CTX` by `CARTAXI`

**Comment by karvounis** [comment]
Hey @LefterisJP, I have this token in my Metamask wallet, not in an exchange.
@yabirgb I will try this solution thank you

**Comment by yabirgb** [comment]
> I updated the CryptoCompare symbol to CARTAXI but still the asset balance remains the same.
> ![Screenshot_20210914_180555](https://user-images.githubusercontent.com/9452845/133283512-3ce8f4f2-6cc5-47f1-be08-e1515ea2717c.png)

It might be the case that we have some kind of cache. Try to force a refresh of prices
![image](https://user-images.githubusercontent.com/5068010/133284022-37b76cec-8376-4053-b489-4a98198b6500.png)

or in case it still doesn't show the correct price, can you try to close and open the again the app?

**Comment by LefterisJP** [comment]
> I updated the CryptoCompare symbol to CARTAXI but still the asset balance remains the same.
> ![Screenshot_20210914_180555](https://user-images.githubusercontent.com/9452845/133283512-3ce8f4f2-6cc5-47f1-be08-e1515ea2717c.png)

Can you try restarting the app also?

Cryptocompare returns 

https://min-api.cryptocompare.com/data/price?fsym=CARTAXI&tsyms=EUR

`0.06343` EUR as the price.

On the other hand I see the price has not updated for years ... so even cryptocompare's oracle may not be very accurate here. And it's also not in coingecko.

**Comment by karvounis** [comment]
Manually editing the CryptoCompare symbol and restarting the app fixed the issue! Thank you @LefterisJP and @yabirgb for your help and extremely fast responses!
