### ISSUE TITLE
Write tests for binance fiat deposits/withdrawals and fiat payments

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3468]
## Abstract

After merging https://github.com/rotki/rotki/pull/3443 there have been no tests written to deserialize fiat/orders and fiat/payments:
https://binance-docs.github.io/apidocs/spot/en/#get-swap-history-user_data

Relevant part of the tests code:
https://github.com/rotki/rotki/blob/2c9ed5d892c4c571b86edb701c80838b9222bff1/rotkehlchen/tests/exchanges/test_binance.py#L590-L598
https://github.com/rotki/rotki/blob/2c9ed5d892c4c571b86edb701c80838b9222bff1/rotkehlchen/tests/exchanges/test_binance.py#L720

## Task

Write them

**Comment by abxsantos** [comment]
Can I work on this issue?

**Comment by yabirgb** [comment]
Hello @abxsantos ! Of course, no one has taken it. If you need any help we have a dev channel in our discord server https://discord.com/invite/aGCxHG7

**Comment by hamzzy** [comment]
@abxsantos  are you still working on this issue.
