### ISSUE TITLE
FR: Add ETH2 validator by public key

### ISSUE THREAD

**Issue by corpetty** [rotki/rotki#3487]
## Abstract

I am currently only able to add an ETH2 validator via its deposit address. I would prefer to add via the public key on the beaconchain. 

## Motivation

I have validators that I track that for one reason or another are not cleanly mapped to a given ETH1 deposit address. I would prefer to track them via their ETH2 validator public key.

**Comment by LefterisJP** [comment]
This is a valid request. Should be dooable with few changes/additions in backend and frontend. We will put it in the backlog @corpetty !

**Comment by LefterisJP** [comment]
Narrator: It was more than a few.

But it's being worked on.
