### ISSUE TITLE
New asset: BANK

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#3496]
**Asset name:** Bankless DAO
**Asset symbol:** BANK
**Coingecko link:** https://www.coingecko.com/en/coins/bankless-dao

**Comment by LefterisJP** [comment]
Hey @hjorthjort this is weird. I would have sworn we have it but indeed I don't see it in the DB. As you know you can add this manually quite easily as it's an ethereum token.

We will add it in next release.

Tagging @yabirgb

**Comment by hjorthjort** [comment]
Yeah, I could have sworn I've seen it, too. Figured you'd want it.

**Comment by yabirgb** [comment]
Closed by #3517
