### ISSUE TITLE
Add support for Arbitrum (Ethereum L2)

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#3505]
## Abstract

It might be good to start thinking about supporting Ethereum Layer 2 networks like [Arbitrum](https://portal.arbitrum.one/).

## Motivation

There's already a lot of projects launched on Arbitrum with more coming soon.

## Specification

n/a

**Comment by LefterisJP** [comment]
Hey @a7e8 we have it in our sights along with other EVM compatible rollups and sidechains. Specifically for arbitrum there is an issue already here: https://github.com/rotki/rotki/issues/3420
