### ISSUE TITLE
ShapeShift incorrect rate causing losses in P&L

### ISSUE THREAD

**Issue by arosboro** [rotki/rotki#3522]
## Problem Definition

The development ShapeShift external exchange location registers trades with the rate in the quote_asset.  Rotki expects rate in base_asset.  To convert divide 1 by the rate given in the CSV artifact.

### System Description

Operating system: Mac OSX 11.6
Rotki version:  1.20.2.DEV

**Comment by LefterisJP** [comment]
Hey thanks for opening an issue for this but there is no reason to open issues for development features :smile:

**Comment by arosboro** [comment]
Sure I wasn't sure what to name the branch for the PR, in the future I will just make it topical.
