### ISSUE TITLE
Keep getting "Found coinbase deposit/withdrawal with unknown asset FET. Ignoring it." error

### ISSUE THREAD

**Issue by pinoli** [rotki/rotki#3546]
## Problem Definition

Hello, this is the first of several issues I constantly encounter in rotki (I love it by the way!)
I connected the Coinbase API and it keeps giving me this message. FET was a coin for Coinbase Learn program, after I got it I immediately swapped it. Even though I hold no FET, I keep getting this message every 5-10 minutes in the notifications panel (the little bell)
![image](https://user-images.githubusercontent.com/30185650/135701767-2a5f9f46-780e-4cd3-a62b-d054edaa3195.png)

I checked the Manage Assets, and FET is there, so I don't understand what's going on.

This problem was present with the previous version as well, but I waited out for the update to see if it'd get solved.
### System Description

Operating system: Windows 10 21H1 19043.1237
Rotki version: 1.21.0

**Comment by LefterisJP** [comment]
You can ignore it. This is just a warning.

**Comment by LefterisJP** [comment]
Actually after looking further it means that FET (Fetch.ai) was not properly detected for coinbase users due to 2 assets with this symbol existing. Fixing it now.

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3551
