### ISSUE TITLE
NFT gallery breaks with special NFT (tbd)

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3552]
## Problem Definition

If one starts traveling the NFT gallery the application freezes and one has to close it an open again. This is caused by specific NFT that needs to be found. I'm on it atm

## Logs

Neither the backend or the electron logs report any issue related to this freeze. The console log shows this

![image](https://user-images.githubusercontent.com/5068010/135713076-d459771c-1d64-4e20-ae23-dcd8c0337074.png)

Took a look at heap memory and was about 30MB. Currently trying to find the NFT that triggers this

### System Description

Operating system: Windows & linux
Rotki version: 1.21.0

**Comment by LefterisJP** [comment]
Fixed by #3557
