### ISSUE TITLE
Assets 1.22

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3563]
- [x] [Spell](https://www.coingecko.com/en/coins/spell-token) `0x090185f2135308bad17527004364ebcc2d37e5f6`

**Comment by LefterisJP** [comment]
We could also do an assets round for the patch release!

**Comment by yabirgb** [comment]
UTK forked to `0xdc9ac3c20d1ed0b540df9b1fedc10039df13f99c` from `0x70a72833d6bF7F508C8224CE59ea1Ef3d0Ea3A38`

**Comment by realkinando** [comment]
I've just noticed that staked [OHM](https://www.coingecko.com/en/coins/olympus) (sOHM from OlympusDao) balances aren't showing. 

Rotki already supports OHM iirc, however, given that 92% of OHM is locked in staking, being able to show rebasing staked OHM balances would be huge plus!

[Staked OHM](https://etherscan.io/token/0x04f2694c8fcee23e8fd0dfea1d4f5bb8c352111f) is convertible 1:1 with OHM, however, it doesn't have it's own Coingecko page.

Thanks guys :)

**Comment by yabirgb** [comment]
> I've just noticed that staked [OHM](https://www.coingecko.com/en/coins/olympus) (sOHM from OlympusDao) balances aren't showing.
> 
> Rotki already supports OHM iirc, however, given that 92% of OHM is locked in staking, being able to show rebasing staked OHM balances would be huge plus!
> 
> [Staked OHM](https://etherscan.io/token/0x04f2694c8fcee23e8fd0dfea1d4f5bb8c352111f) is convertible 1:1 with OHM, however, it doesn't have it's own Coingecko page.
> 
> Thanks guys :)

Hello @realkinando I was going to add the stOHM contracts but seems that they are not token that one account can hold. For rotki to take into account this balances we would need to add at least a minimal support for OHM protocol.

**Comment by Cebrain** [comment]
Hi,
have an request for some tokens

ETH
Metis Token
https://coinmarketcap.com/currencies/metisdao/
https://www.coingecko.com/en/coins/metis-token
0x9E32b13ce7f2E80A01932B42553652E053D6ed8e

StarLink
https://coinmarketcap.com/currencies/star-link/
https://www.coingecko.com/en/coins/starlink
0x8e6cd950ad6ba651f6dd608dc70e5886b1aa6b24

Tokemak
https://coinmarketcap.com/currencies/tokemak/
https://www.coingecko.com/en/coins/tokemak
0x2e9d63788249371f1DFC918a52f8d799F4a38C94

Sovryn
https://www.coingecko.com/en/coins/sovryn
0xbdab72602e9ad40fc6a6852caf43258113b8f7a5

BSC
Catecoin 
https://www.coingecko.com/en/coins/catecoin
0xe4fae3faa8300810c835970b9187c268f55d998f

**Comment by yabirgb** [comment]
Hello @Cebrain ! Thanks for the detailed list. Will add them for the next release :)

**Comment by LefterisJP** [comment]
I spent some time double checking them. All seem to be included. One discpepancy only.

@yabirgb you need to fix METIS token. The symbol is lowercase "Metis" there.
