### ISSUE TITLE
Janky "Asset amount and value over time" graph

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#3586]
## Problem Definition

In v1.21.1, the `Asset amount and value over time` graph has gone weird. 

Instead of graphically displaying a constant `amount in asset` on the y-axis between two points where one infrequently starts up Rotki, the graph is now showing a very confusing set of lines up to that value and back to zero.  Graph is now nearly unusable.

The `Asset value in (selected currency)` is doing the same odd behavior.

### System Description

Operating system: Win10
Rotki version: v1.21.1

**Comment by A2be** [comment]
Example:
![Capture](https://user-images.githubusercontent.com/19943243/136640664-0c734d8c-91db-47bf-8467-f69ef64f8d31.jpg)

**Comment by LefterisJP** [comment]
> Sorry for the duplicate. I looked through github and apparently missed something had been opened on it.

Nah no worries. The name of the issue was esoteric, pointing to the reason in the code that this happened instead of the effect the user would see. Hard to notice from the user point of view.
