### ISSUE TITLE
Uphold has an issue with "Exchanged amount" vs "Received amount"

### ISSUE THREAD

**Issue by arosboro** [rotki/rotki#3591]
## Problem Definition

The CSV provides information to determine the fee and gives the received amount (which is the amount after the fee).

Rotki expects the exchanged amount, which is the amount before the fee was subtracted.  When the fee is entered into rotki, it applies it by reducing the base asset amount (action buy) accordingly.  With the current uphold implementation the received amount in P&L is less than what was actually received resulting in not enough acquisitions at a later date when the full balance is sold.  

To determine this we have to determine the amount of the fee and add it back into the received amount to get to the exchanged amount.  Then when the fee is subtracted by rotki it will correctly show the received amount as the base amount.

### System Description

Operating system: OS X
Rotki version: 1.20.2

**Comment by LefterisJP** [comment]
Hey @arosboro I see we merged a commit from you fixing this. So I will close this issue. Not sure why it did not auto close. If that's wrong please comment here and we can reopen.
