### ISSUE TITLE
Rotki hangs when changing name of an API key

### ISSUE THREAD

**Issue by antonionardella** [rotki/rotki#3624]
## Problem Definition

- Add an API key for an exchange e.g. Bitstamp and save
![image](https://user-images.githubusercontent.com/7383572/137938231-a113507a-82bb-439f-8d0c-55ea18ac440e.png)
- Delete the API key for Bitstamp
- Again add the API key for Bitstamp. Rotki will name it **Bitstamp 1** and save
- Edit the API key for the exchange and rename it to **Bistamp** removing the number **1**
- Rotki hangs and does not save

- Restart Rotki and it is able to save

### System Description

Operating system: Linux
Rotki version: 1.21.2

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3628

**Comment by kelsos** [comment]
> > You only need the double if you trying to assign to a boolean. Single should work in an if clause treating null/undefined/empty string as false.
> 
> Single did not work. I tested it. But it also makes no sense for it to work. You want the if condition to be true only if the ftx sub account field exists, so it goes to the 2nd condition. Otherwise it will go to the 2nd condition with subAccount being null and then the bug happens.

I updated the comment. I had seen the clause wrong sorry. Early morning.
