### ISSUE TITLE
Unsupported asset GEL

### ISSUE THREAD

**Issue by merc-0** [rotki/rotki#3636]
## Problem Definition

Error notification concerning GEL

## Logs

```
Unsupported asset GEL with address 0x15b7c0c907e4C6b9AdaAaabC300C08991D6CEA05 encountered during DeFi protocol queries
```

### System Description

Operating system:  macos
Rotki version: 1.21.2

**Comment by LefterisJP** [comment]
Thank you @merc-0 will put this for next release. In case you were not aware of you can also add assets on your own for your local instance of rotki: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset

**Comment by LefterisJP** [comment]
@yabirgb This is not in the supported assets in v1.22.

`sqlite> SELECT * from ethereum_tokens WHERE address="0x15b7c0c907e4C6b9AdaAaabC300C08991D6CEA05";`

 Please add it and then close this issue:
