### ISSUE TITLE
Add FTX as price oracle

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3642]
## Abstract

FTX offers a public endpoint to query for current prices and historical prices. This source could be useful when coingecko and cc fail to offer prices

## Motivation

FTX has already a numerous number of markets and they public endpoints make easy to query for prices making it a very attractive option. Also people that use FTX would find more precise prices for their trades

## Specification

We already have logic to query FTX endpoints so adding this functionality would require to refactor a bit the code for FTX exchange and allow to make queries without keys. Then we have to create a oracle that makes use of this function to query FTX endpoints.

**Comment by LefterisJP** [comment]
We are not doing that
