### ISSUE TITLE
Update ignore action API response

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3651]
## Problem Definition

This issue regards the following endpoint `GET /api/(version)/actions/ignored`,
along with the ignore/unignore endpoints.

While the [documentation](https://rotki.readthedocs.io/en/latest/api.html#dealing-with-ignored-actions) specifies that some of the GET might include "_" in the keys, this is not what has been observed.

Instead, the endpoint uses the action type as a key when returning the ignored values.

The action types are "trade", "asset movement", "ethereum transaction" and "ledger action".

An example of a response would be:

```json
{
    "result": {"asset movement": ["Z231-XH23K", "X124-JYI"]},
    "message": ""
}
```

The first change would be to properly replace the whitespace in the keys with an `_`. It would be also nice if we could change the values to the plural form since the result is an array of ignored ids.

> Note! since this requires backend it would be better to schedule the task after #3648 has been merged to bugfixes and bugfixes to develop.

**Comment by kelsos** [comment]
@LefterisJP @yabirgb I guess the changes for this are merged so we can close the issue

**Comment by LefterisJP** [comment]
> @LefterisJP @yabirgb I guess the changes for this are merged so we can close the issue

very much yes
