### ISSUE TITLE
Implement backend paginations for trades and deposits/withdrawals

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3653]
## Problem Definition

To improve frontend performance we need to move the pagination/filtering/sorting for the trades along with the deposits withdrawals to the backend.

And then adjust the frontend to use the pagination (similar to how transactions work).

### DEX Trades
At the moment the frontend will fetch both CEX trades and DEX trades then it will transform the DEX trades to the same schema format as CEX trades and merge the results.

If we move the pagination/filtering/sorting to the backend we probably need to make sure that the `GET /api/(version)/trades` endpoint can also return DEX trades in the CEX trade schema format, and also make these trade locations available when filtering by location.

### Filter Suggestions
The frontend will read some of the fields and will suggest values based on the search/keyword for autocompletion.

For the trades, this includes the quote/base asset and the location,
and for the deposits & withdrawals, this includes the asset and location.

The current implementation uses the actual entries in memory to generate these suggestions. With the pagination/filtering/sorting moving to the backend, there are two different approaches we can take.

To ensure that the suggestions match real data a new endpoint would need to be implemented.

Alternatively, we can just use all the trade locations and available assets as a suggestion source. This doesn't need a new endpoint and when the users select a suggestion that doesn't have data they might see an empty result set.

**Comment by LefterisJP** [comment]
For trades we also need to make sure to add filtering as is already done by the frontend but do it in the backend.

![unknown](https://user-images.githubusercontent.com/1658405/144441980-65f1dd84-4ce5-4e40-b064-c67a759c0df9.png)

And for deposits/withdrawals a similar filter

![unknown](https://user-images.githubusercontent.com/1658405/144442058-bcaaff23-389c-4e05-873a-2fcca7d176a7.png)

**Comment by LefterisJP** [comment]
For ledger actions these are the current filters to be moved to the backend:

![2021-12-20_10-51](https://user-images.githubusercontent.com/1658405/146747783-a87c8fd8-7c71-445c-9cd5-7b1ac79f8916.png)
