### ISSUE TITLE
Create a exportable list of manually added assets

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3669]
## Request

Create a exportable list of the assets that were manually added to the globaldb

## Use case

With this feature it would be also possible to fast find the tokens and to recheck everything is still correct (maybe after migrates or other changes of the token)

## Implementation details

A new endpoint should be created so the frontend can query this list and a new csv file could be created consuming this information.

We already query this list at https://github.com/rotki/rotki/blob/9f4e2e97c393ffe3ceb62acdb7d54381884ed854/rotkehlchen/globaldb/handler.py#L1233-L1248

for actionable points that are needed I believe it should be

- [ ] Create a new endpoint to get that list
- [ ] Create a method in the globaldb to implement this logic
- [ ] Create synthetic tests to make sure it works

**Comment by Aragar199** [comment]
@yabirgb Checking if I understand how this will be implemented: 
* Add a new class to rotkehlchen/api/v1/resources.py like `ManuallyAddedAssetResource`
* Add the endpoint with the v1 urls in rotkehlchen/api/server.py

**Comment by yabirgb** [comment]
> @yabirgb Checking if I understand how this will be implemented:
> 
> * Add a new class to rotkehlchen/api/v1/resources.py like `ManuallyAddedAssetResource`
> * Add the endpoint with the v1 urls in rotkehlchen/api/server.py

Hello! Yes those are the steps that you need to follow. The resource should call a function in `rest.py` that should make the needed calls.

I believe the most useful thing would be to generate a `.csv` with all the fields for the assets. You can convert the asset to dict and then the list of dicts saved as CSV.

As per to save the information in CSV files we do so in other places like this https://github.com/rotki/rotki/blob/ecb603444c693c8bc864aa4dda116554c66aa6b1/rotkehlchen/csv_exporter.py#L907 that might be useful as reference.

For this logic maybe the best place to have is in the GlobalDBHandler. Also I believe it would be cool if the information could be returned to the frontend (as a list of identifiers) so this can be displayed inside the app and then a parameter can be added to the url to export it as CSV. To add parameters into routes you just need to add a schema in `encoding.py` and then use it in the resource.

If anything here is not clear please ask me :)
