### ISSUE TITLE
Find if there is a way to proxy the websocket connection through flask.

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3674]
## Abstract

On docker when Nginx is available the `ws` is proxied through Nginx to the backend via a `host:port/ws` scheme. 

In the application itself, the frontend starts the backend and web socket and specifies the ports, thus the frontend is aware of which localhost port the web socket listens to, to connect.

The problem is that this detection is hardcoded, not dynamic and thus it has a few cases that it doesn't really work. 

One of these is when the packaged version of the application attempts to connect to a remote host (docker) the web socket will fail to connect.

Having the backend let the frontend know its web socket listening port won't work in this case since the backend is not aware of the proxy in front.

The idea here would be if possible, that flask would act as a proxy to establish the connection and pass it to the web socket server, eliminating the need for the frontend to be aware of different ways or ports to connect.

**Comment by LefterisJP** [comment]
Hey @kelsos this was scheduled for this release. Is this still a relevant idea you want to pursue? If yes move it to a milestone you think would make sense. Otherwise close it.

**Comment by LefterisJP** [comment]
Pushing this to next version for @prettyirrelevant to check. If something is not clear ask @kelsos
