### ISSUE TITLE
No documented acquisition found...

### ISSUE THREAD

**Issue by tweverett** [rotki/rotki#3689]
When I generate a profit and loss report, I get 191 'No documented acquisition found...' alerts. I'm not sure if this is a bug or if I'm doing something wrong. I only use one exchange, Coinbase Pro, and have 7 API connections, one for each of my 7 Coinbase Pro portfolios. If anyone can point me to a way to fix this, I'd appreciate it. 

I'm a new user. I've tried clearing cache, reseting the database, relaunching the application, but nothing fixes the problem so far.

Operating system: Mac OS 
Rotki version: 1.21.3

Thanks!
Todd

**Comment by LefterisJP** [comment]
Hello Todd. We have an entry in the usage guide exactly for this: https://rotki.readthedocs.io/en/latest/usage_guide.html#no-documented-acquisition-found

Read that and then if you have more questions feel free to pop by our discord: https://discord.com/invite/aGCxHG7
(Note that there is a captcha challenge to enter).

The TL;DR on the error is that rotki can't figure out where something you got was acquired from. So if say you sent 10 ETH to coinbase PRO and then sold it for $40,000 rotki can't know how much you paid for this 10 ETH to calculate your profit. So it takes the full $40k as profit in the result, which is most probably wrong.

This is why there is this error to let you know that you need to tell rotki somehow (through a manual trade most probaly or a ledger action) when and for how much did you buy that 10 ETH.
