### ISSUE TITLE
Allow importing multiple blockchain accounts at the same time

### ISSUE THREAD

**Issue by kobigurk** [rotki/rotki#369]
Implement a method that will allow importing multiple blockchain accounts at once instead of having to specify them one by one.

This could be done in three different ways:

1. Allow mass import from a file. A simple json file would be sufficient. Could also contain tags if #461 is implemented.
2. If this involves ethereum accounts they could also be imported from the local ethereum node if the user has one.

**Comment by LefterisJP** [comment]
Hey @kobigurk no there is not. You need to do them one by one.

**Comment by kobigurk** [comment]
Got it, thanks!

**Comment by LefterisJP** [comment]
But no need to close it. We can turn it into a feature request, if it ever becomes possible and makes sense to implement :)

**Comment by kelsos** [comment]
The initial approach will be to allow multiple comma-separated addresses to be specified by the user
![image](https://user-images.githubusercontent.com/2269732/100486560-ad2d7600-3104-11eb-9161-42c8b47ba8ce.png)
