### ISSUE TITLE
Fails to load RMRK balance from Kucoin

### ISSUE THREAD

**Issue by Swader** [rotki/rotki#3702]
## Problem Definition

Adding a Kucoin account will fail to load one's RMRK balance with the following error:

![image](https://user-images.githubusercontent.com/1430603/141383731-55e071f7-b78f-4b42-ad0c-86c3ff50a006.png)

**Comment by LefterisJP** [comment]
Thanks for the issue @Swader. (Wasn't your username bitfalls?).

It's since we don't support RMRK yet and it's not mapped properly to kucoin.

So @yabirgb let's include that in the upcoming release too.

1. Add support for https://www.coingecko.com/en/coins/rmrk
2. Map it properly in Kucoin

**Comment by Swader** [comment]
bitfalls on twitter, swader everywhere else :)

**Comment by javimurcia** [comment]
I'm still getting this error:
Found unsupported kucoin asset RMRK while deserializing a balance. Ignoring it.

When i originally had that error, i manually created the asset, but the error still persists. And after getting the update and starting from scrath, the error still persist.

This is the current config for the asset
![image](https://user-images.githubusercontent.com/33467841/142506963-fd0f057a-d9c9-40cc-94a6-d2cd9f0f4bd9.png)

**Comment by LefterisJP** [comment]
> I'm still getting this error: Found unsupported kucoin asset RMRK while deserializing a balance. Ignoring it.
> 
> When i originally had that error, i manually created the asset, but the error still persists. And after getting the update and starting from scrath, the error still persist.
> 
> This is the current config for the asset ![image](https://user-images.githubusercontent.com/33467841/142506963-fd0f057a-d9c9-40cc-94a6-d2cd9f0f4bd9.png)

Hey @javimurcia. You are correct. We added the asset in v1.22.0 but it was in the unsupported assets list for kucoin and it was not removed from that list. That's a mistake on our side.

We are about to release v1.22.1. I am gonna sneak the one line fix for that in there. Should be out by end of this week. Btw, at this point you should not need to add the asset manually as it should already be in the asset database.

**Comment by LefterisJP** [comment]
Should hopefully now be fixed by #3734 and included in v1.22.1
