### ISSUE TITLE
Importing Data from Cointracking.info to Rotki

### ISSUE THREAD

**Issue by twooten1105** [rotki/rotki#3711]
## Problem Definition

I am trying to transfer all my trading data from cointracking.info to rotki.

On rotki, it says to import the data from cointracking's CSV export. But on cointracking.info's site, I do not see an option to export 
the data into a .CSV file. I only see html, xml, and JSON.

Any help would be appreciated!

**Comment by LefterisJP** [comment]
Hey @twooten1105 thanks a lot for using rotki!

It seems like cointracking has removed the CSV export from their service. There is nothing easy we can do to fix your issue fast. What I would suggest is:

1. You should try to contact them and ask for support to re-enable it. There is no reason for them to remove it other than make it harder for people like you to leave their platform.
2. Take their JSON and convert it to CSV and try to import it (probably will have failures)
3. We can turn this issue into request for importing JSON from cointracking.info. But we are really pressed for resources at the moment, this is not a priority considering how cointracking changes their stuff all the time. So can't give an estimate when such a thing would be ready.

Other than that if you trading data was in CEXes or DEXes like uniswap/sushiswa/balancer etc. you can just move your addresses and api keys to rotki and it should pull all the data automatically.

**Comment by twooten1105** [comment]
Thanks for the info!

I was trying to figure out what end the issue was coming from.

Looks like it is coming from cointracking's end. I will contact them.

Thanks again for the quick reply

**Comment by twooten1105** [comment]
Wait nevermind.

There is a way to export to CSV on cointracking. 

No need to do anything on your end. Thanks again!
