### ISSUE TITLE
Add support for the paraswap airdrop

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3716]
More information at 

https://medium.com/paraswap/introducing-the-psp-token-to-make-paraswap-even-more-efficient-and-decentralized-c4730e50be72

**Comment by yabirgb** [comment]
This seems to be the list of users https://raw.githubusercontent.com/paraswap/paraswap-rewards-snapshot/master/data/airdrop-users.json

**Comment by LefterisJP** [comment]
Also @bantg made a CSV with the right format ready to be put into our [data repo](https://github.com/rotki)](https://github.com/rotki/data): https://gist.github.com/banteg/f3a1bdb73ec49689823d20e38387a696

Should be really easy for anyone to do this. The only work required is seen in the similar ens airdrop PR: https://github.com/rotki/rotki/pull/3690

That PR also contains unrelated changes (which should be pretty obvious)

**Comment by Aragar199** [comment]
@yabirgb I'd like to take a crack at this. Is there a deadline or just asap?

**Comment by yabirgb** [comment]
Hello @Aragar199! We want it for next release but it won't by before 1-2 weeks I believe. Just work on it as soon as you can :)

**Comment by LefterisJP** [comment]
Also you will probably need to have the PSP asset added. But you can work on this assuming PSP is added and we can add it in another PR.

**Comment by Aragar199** [comment]
Understood! Seems straightforward enough, you can assign it to me. I'm in the discord as well.
