### ISSUE TITLE
API - PUT on /api/1/trades with quote_asset USDT fails

### ISSUE THREAD

**Issue by sushilman** [rotki/rotki#3717]
## Problem Definition

Trying to PUT a trade via API with the following payload fails with the response that USDT is unknown. The similar operation, i.e. adding an external trade, when done via the application works without issues. But fails via API. Is this a bug or am I missing something ? :)

Payload:
```json
{
    "timestamp": 1536990635,
    "location": "external",
    "base_asset": "ETH",
    "quote_asset": "USDT",
    "trade_type": "BUY",
    "amount": "52.992",
    "rate": "0.4798",
    "fee": 0.0635,
    "fee_currency": "USDT",
    "notes": "Exchange: Liqui"
}
```

Curl command:
```
curl -X PUT \
  http://localhost:4242/api/1/trades \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:4242' \
  -H 'User-Agent: PostmanRuntime/7.11.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 262' \
  -d '{
    "timestamp": 1536990635,
    "location": "external",
    "base_asset": "ETH",
    "quote_asset": "USDT",
    "trade_type": "BUY",
    "amount": "52.992",
    "rate": "0.4798",
    "fee": 0.0635,
    "fee_currency": "USDT",
    "notes": "Exchange: Liqui"
}'
```

**Current behavior:**
Response: 
400 BAD REQUEST
```
{
    "result": null,
    "message": "{\"quote_asset\": [\"Unknown asset USDT provided.\"], \"fee_currency\": [\"Unknown asset USDT provided.\"]}"
}
```

**Expected behavior**
Response: 200 OK

## Additional Notes
- Can see that USDT is present in http://localhost:4242/api/1/assets/all
- Similar error for USDC
- USD is accepted
- USDJ is also accepted
- adding the entry for USDT via the form in the application UI works without issues (History -> Trades -> +)

## Logs

No significant log even when enabling debug.
`
[15/11/2021 16:54:54 CET] INFO rotkehlchen.api.server.pywsgi 127.0.0.1 - - "PUT /api/1/trades HTTP/1.1" 400 257 0.001192
[15/11/2021 16:54:56 CET] DEBUG rotkehlchen.tasks.manager Greenlet-6: At task scheduling. Current greenlets: 1 Max greenlets: 2. Will schedule.
`

### System Description

Operating system: Arch Linux
Rotki version: 1.22.0

**Comment by LefterisJP** [comment]
Hey @sushilman you are trying to add it with the symbol while the api accepts only the identifiers. So what you need is the USDT identifier. `_ceth_0xdAC17F958D2ee523a2206206994597C13D831ec7`.

You can find the identifiers from looking at the asset manager and pressing the edit of an asset. For ethereum tokens it's `_ceth_` + checksummed ethereum address

**Comment by sushilman** [comment]
Perfect. That makes sense !
I looked at all other properties but missed the key itself :facepalm: 

Thanks for the super quick response !

**Comment by LefterisJP** [comment]
My pleasure @sushilman!

For dev and or usage questions we also have a discord server where we are fairly active (in European timezones): https://discord.com/invite/aGCxHG7

It has a captcha verification system so make sure to have DMs open.

Feel free to hop in there!
