### ISSUE TITLE
Remember User checkbox doesn't work

### ISSUE THREAD

**Issue by faraggi** [rotki/rotki#3718]
## Problem Definition

When opening rotki, user credentials are asked every time, even though `Remember User` is ticked.

## Logs

I can send logs if needed, but I'll have to go through them and purge all identifiers and such.

### System Description

Operating system: (K)ubuntu 20.04
Rotki version: 1.22.0
Platform: linux x64 5.11.0-40-generic
Electron: 14.0.0

**Comment by yabirgb** [comment]
Hello @faraggi ! Rotki doesn't save your password since is the key protecting the database. It will only remember the last username you used.

**Comment by faraggi** [comment]
pfff, i feel dumb now lol
