### ISSUE TITLE
Expanding information for one trade makes all of them show more information

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3722]
## Problem Definition

Clicking on the arrow to display more information

![image](https://user-images.githubusercontent.com/5068010/142023481-3c78083f-8086-4c8b-ab68-648df802c269.png)

Makes all the items in that list to show the detailed information too. Also makes the app lag a bit.

### System Description

Operating system: Docker
Rotki version: 1.22

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3729
