### ISSUE TITLE
Add a user-controlled local-data field for "claimed" tokens

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#3740]
## Abstract
In Rotki v1.22.1, Airdrops that Rotki finds are displayed, but no indication of whether the airdrop has been claimed or not is shown.  My understanding is that this is normal, and there will not be any Rotki software auto-detection of "claimed" tokens.

Still, would be helpful to the end user to be able to track which of their airdrops they've claimed, and which they have not.

Therefore, feature enhancement would be to: 
**Add a user-controlled local-data field--or user-set checkbox--to annotate "claimed" tokens.**  

This would allow the user to be able to track, in their portfolio app, which airdrops they have claimed, and which they have yet to claim.  Moreover, it could potentially leave a user-set record/note of when, or xactionID, of the claim. 

## Motivation

see above

**Comment by LefterisJP** [comment]
Huh that's a nice idea @A2be. I like it.

The claimed tokens detection would be implementing this issue: https://github.com/rotki/rotki/issues/2000  (which is quite hard)

But until that is done (if it's ever possible in a perfect errors-free way) then your suggested approach sounds good and useful.

**Comment by LefterisJP** [comment]
This is superseded by #2000 which is now done.
