### ISSUE TITLE
Mistake for IMX token (Immutable X)

### ISSUE THREAD

**Issue by bitboy99** [rotki/rotki#3745]
**Asset name:** Immutable X
**Asset symbol:** IMX
**Coingecko link:** [Please fill in - if available (either this or cryptocompare must exist)](https://www.coingecko.com/en/coins/immutable-x)

Hey, I have some IMX in my FTX portfolio but rotki identifies them as impermax and not Immutable X.
This might happens because there were a change in the token supply. 
Anyway since it's now in the top 100 it might be great to get the right price associated.

Thanks

![image](https://user-images.githubusercontent.com/81534621/142865954-6a64a6a1-ce36-42aa-ad6c-2af82b1c9f69.png)

**Comment by yabirgb** [comment]
Hello @bitboy99! Thanks for letting us know, will be fixed in the next upgrade for the assets. Sorry for the inconvenience
