### ISSUE TITLE
assets for 1.23

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3747]
Support Osmosis

**Asset name:** Osmosis
**Asset symbol:** OSMO
**Coingecko link:** https://www.coingecko.com/en/coins/osmosis
**Cryptocompare link:**  - ?

**Comment by LefterisJP** [comment]
Add support for BOBA network and map it in the various exchanges.

Apparently it's a new L2 token airdropped to holders of OMG. Even in an exchange.

![2021-11-23_09-23](https://user-images.githubusercontent.com/1658405/142991025-d04258ee-90e0-4cee-97e8-40c97994f96b.png)
![2021-11-23_09-23_1](https://user-images.githubusercontent.com/1658405/142991029-11cde4b4-788a-4db6-a0e1-4263bff1d8c3.png)

**Coingecko:** https://www.coingecko.com/en/coins/boba-network

Should be mapped to at least polo and FTX afaics

**Comment by yabirgb** [comment]
Add https://www.coingecko.com/en/coins/serum and map it in FTX

**Comment by LefterisJP** [comment]
> Add https://www.coingecko.com/en/coins/serum and map it in FTX

This is not needed. Well maybe the FTX mapping would not be bd, but serum is already there.

**Comment by LefterisJP** [comment]
> > Add https://www.coingecko.com/en/coins/serum and map it in FTX
> 
> This is not needed. Well maybe the FTX mapping would not be bad, but serum is already there.

**Comment by LefterisJP** [comment]
> > > Add https://www.coingecko.com/en/coins/serum and map it in FTX


This is not needed. Well maybe the FTX mapping would not be bad, but serum is already there.

**Comment by LefterisJP** [comment]
Add support for EURT (Euro Tether) -> https://www.coingecko.com/en/coins/euro-tether

**Comment by LefterisJP** [comment]
Add Cere Network -> https://www.coingecko.com/en/coins/cere-network

**Comment by LefterisJP** [comment]
Add rocket pool ETH: https://www.coingecko.com/en/coins/rocket-pool-eth

**Comment by yabirgb** [comment]
Check `GENE` on FTX

**Comment by LefterisJP** [comment]
Rename coingecko identifier for the old AAVE (LEND). It's been renamed to `ethlend` ... which is its old id. Lol.

https://www.coingecko.com/en/coins/aave-old

```
sqlite> SELECT * from assets where coingecko='aave-lend';
_ceth_0x7D2D3688Df45Ce7C552E19c27e007673da9204B8|C|Aave Interest bearing LEND|aLEND|1578501530||aave-lend|LEND|0x7D2D3688Df45Ce7C552E19c27e007673da9204B8
```

**Comment by yabirgb** [comment]
Map wluna in gemini

**Comment by LefterisJP** [comment]
Add all fixed forex assets.

There is a curve/convex strategy involving fixed forex assets. Namely the synthentix forex synths: sGBP, sEUR, sKRW, sJPY, sCHF, sAUD and their iron bank equivalents: ibGBP, iEUR, ibKRW, ibJPY, ibCHF, ibAUD

We should also have the various curve and convex pools processed properly eventually but this is off-topic to the pure assets.

**Comment by LefterisJP** [comment]
Add support for Gearbox protocol: 0xBa3335588D9403515223F109EdC4eB7269a9Ab5D

https://www.coingecko.com/en/coins/gearbox

**Comment by LefterisJP** [comment]
Add support for Agora token https://etherscan.io/address/0x3174c1e1bbcfb3fe8e9be3ec9b4177a5cfbe5966

If by the time we look at it it's in coingeko .. otherwise let's think on it

**Comment by LefterisJP** [comment]
Add GIV token by Giveth. It's both in xDAI and mainnet. But I guess we only can show mainnet now.

https://medium.com/giveth/welcome-to-the-giveconomy-b3e372da63dd

https://www.coingecko.com/en/coins/giveth
