### ISSUE TITLE
Query range for exchange only takes into account location

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3749]
## Problem Definition

When querying new trades for exchanges only takes into account the location and ignores if there are multiple exchanges for the same location. This happens at https://github.com/rotki/rotki/blob/ecb603444c693c8bc864aa4dda116554c66aa6b1/rotkehlchen/exchanges/exchange.py#L258

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3757
