### ISSUE TITLE
Introduce a minimal context menu with cut/copy/paste functionality

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3753]
## Problem Definition

This is splitting the context menu part of #864 as a followup

The idea is to introduce a minimal context menu for the application to provide cut/copy/paste functionality

> Consider implementing this package https://github.com/sindresorhus/electron-context-menu or we do it by hand.

_Minimum functionality:_
- [ ] Cut / Copy / Paste

**Comment by isidorosp** [comment]
Could do some really interesting/useful things here (e.g. if you're right-clicking an element that is a recognized blockchain address a context menu option could be "open in block explorer" (of choice, as selected by the user in that blockchain's settings).

Could probably build that right into the "address helper" component (not sure what we call it exactly these days), and then make sure that that's appropriately used in every place that an address is shown (which isn't the case at the moment).

**Comment by kelsos** [comment]
That has to be done in a way that is also available when running on docker in the browser though.

**Comment by isidorosp** [comment]
I mean it doesn't *have* to be... =D

**Comment by LefterisJP** [comment]
So @kelsos for the rest of the idea such as the one that @isidorosp mentioned above we just add more functionality on the context menu on a case by case basis with new issues?

**Comment by kelsos** [comment]
We can give it a try but I am not sure how feasible it would be to keep it on par in both electron and in the browser, especially without completely disabling the browser's context menu and adding our own implementation
