### ISSUE TITLE
Coinberry - Exchange Request

### ISSUE THREAD

**Issue by kavemang** [rotki/rotki#3761]
Just putting this up in case new exchanges are being considered

**Comment by LefterisJP** [comment]
Hell @kavemang! Are you referring to https://www.coinberry.com/?

It seems that they do not have an API yet: https://coinpanda.io/integrations/coinberry/

They seem to have a CSV, but there is no docs or examples.

**Comment by kavemang** [comment]
sorry! I will track manually for now :(

**Comment by LefterisJP** [comment]
Hey @kavemang there is never any need to apologize for requesting a feature. We want to make as many of our users happy as possible. Rotki is a user-focused product.

From the docs it sounds as if they do plan to add an API. When that happens would love to support the exchange like all the others we support.
