### ISSUE TITLE
Add KILT

### ISSUE THREAD

**Issue by mruepp** [rotki/rotki#3778]
**Asset name:** KILT Protocol (KILT)
**Asset symbol:** KILT
**Coingecko link:** https://www.coingecko.com/en/coins/kilt-protocol
**Cryptocompare link:** Please fill in - if available (either this or coingecko must exist)
**Coinmarketcap link:** https://coinmarketcap.com/currencies/kiltprotocol/

**Comment by yabirgb** [comment]
Thank you! We will add it to the next major release. You can always add tokens manually as described here https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset
