### ISSUE TITLE
Allow for easy customisation of backend argument with Docker 

### ISSUE THREAD

**Issue by m-roberts** [rotki/rotki#3792]
## Abstract

Provide a way for the backend behaviour to be controlled without modifying the contents of the container.

## Motivation

Currently, [the precise working of the backend are hard-coded](https://github.com/m-roberts/rotki-unlocked/blob/develop/packaging/docker/docker-entrypoint.sh#L3). This means that it is non-trivial to do even simple things like change the log level for debugging purposes.

This change would allow more non-technical users to give feedback, and brings the same simplicity of config change that native environments enjoy to Docker.

## Specification

It would be great if these were either environment variable parameters for `docker run`.
Alternatively, what if it were possible to pass in a config file via a `/config` volume mount? (e.g. `/config/rotki_config.json`?)

**Comment by LefterisJP** [comment]
I assume it is, so closing the issue. If not please reopen.
