### ISSUE TITLE
Add support for ByBit

### ISSUE THREAD

**Issue by piotryordanov** [rotki/rotki#3810]
Please add support for ByBit exchange!

**Comment by LefterisJP** [comment]
Thank you for the issue Piotr. We will put it in the backlog and see what we can do.

**Comment by piotryordanov** [comment]
Cheers 🕺

**Comment by HydraGene** [comment]
I'd like to see this added too. I am willing to help however I can, I am not a coder though.
And if it helps to speed things up, I'm a premium subscriber to Rotki.

**Comment by LefterisJP** [comment]
Hey @HydraGene thanks alot! We don't know when we are able to find time to schedule this in but what would really help with exchanges such as this is to join our discord and provide us with a test api key with real data to test.

Bybit's api docs are here: https://bybit-exchange.github.io/docs/inverse/#t-introduction but without actually having a test api key to try it out it's really hard to implement. Giving us a test key with real data would help.

**Comment by HydraGene** [comment]
@LefterisJP no problem, I've just now found time to go on with this. I've just entered your discord and will be in touch with you there.

**Comment by robbatt** [comment]
Is there any progress on this? I might be able to help out with coding. Would also be interested in getting the copyTrading account balance integrated, not sure where this would come in though

**Comment by LefterisJP** [comment]
> Is there any progress on this? I might be able to help out with coding. Would also be interested in getting the copyTrading account balance integrated, not sure where this would come in though (regular balance? what about transactions, can they be labeled as executed by the master trader?)

You can help by either coding it out yourself such as Anikulu isdoing with OKX: https://github.com/rotki/rotki/pull/5328 or providing us with a read only api key with real data to see how to implement it.

Nobody from the team uses this CEX so without a key and real data it's quite hard to implement.

**Comment by 0xstochastic** [comment]
Hi! 
Any progress here?

**Comment by nebolax** [comment]
Hi! Nobody is working on this issue right now

**Comment by ndopencode** [comment]
I wouldn't mind working on this issue. How can I start?

**Comment by LefterisJP** [comment]
> I wouldn't mind working on this issue. How can I start?

Same thing I wrote here: https://github.com/rotki/rotki/issues/3810#issuecomment-1369651819

**Comment by ndopencode** [comment]
I guess, more specifically, could you guide me to the specific classes or files that would best facilitate my understanding of the architecture? Furthermore, are there any exemplar implementations within the baseline that you could recommend, particularly pertaining to exchanges? This would greatly assist my familiarization with the system.

**Comment by LefterisJP** [comment]
> I guess, more specifically, could you guide me to the specific classes or files that would best facilitate my understanding of the architecture? Furthermore, are there any exemplar implementations within the baseline that you could recommend, particularly pertaining to exchanges? This would greatly assist my familiarization with the system.

Let's keep the issues clear of explaining how the code works. For such questions feel free to explore the codebase and ask questions in our discord: https://discord.com/invite/aGCxHG7

As an example of a PR that adds an exchange pick any exchange work. For example OKX: https://github.com/rotki/rotki/pull/5328

**Comment by LefterisJP** [comment]
This should be fixed by #7081
