### ISSUE TITLE
"The setup of bitmex failed due to: Bitmex api request for https://www.bitmex.com:443/api/v1/user failed with HTTP status code 403"

### ISSUE THREAD

**Issue by Letiliel** [rotki/rotki#3811]
Getting this error when adding API keys for Bitmex.
I tripled checked the copied keys.

Fresh install of Rotki on Linux.

**Comment by LefterisJP** [comment]
Hey @Letiliel seems you figured it out on your own. For any such problems perhaps it's better to join our discord https://discord.com/invite/aGCxHG7 and ask there too!

There is a captcha challenge so have DMs open.
