### ISSUE TITLE
Support the Iron Bank assets

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3839]
## Abstract

Add integration with the IronBank. This issue also serves as a way to keep information for later.

## Motivation

long yearn

## Specification

- There is a registry contract that can we queried for the fixed forex https://etherscan.io/address/0x5C08bC10F45468F18CbDC65454Cbd1dd2cB1Ac65#readContract

**Comment by LefterisJP** [comment]
So what exactly do you want to support here @yabirgb? Have we not done part of this at least?

**Comment by yabirgb** [comment]
So this issue was to support the iron bank tokens + the lending protocol. The assets are now supported but the protocol not. If someone wants to see it supported another issue can be created later
