### ISSUE TITLE
Cryptocom CSV import inconsistant rate

### ISSUE THREAD

**Issue by CyBHFal** [rotki/rotki#3859]
## Problem Definition

A BTC to CRO crypto exchange transaction(single exchange CSV line) and a BTC to CRO dust conversion transaction (from 2 CSV lines, one debit, one credit) does not have the same computation rule. 

One is inverted

_consume_cryptocom_entry()
rate = Price(abs(**quote_amount_sold** / base_amount_bought))

_import_cryptocom_associated_entries()
rate = Price(abs(base_amount_bought / **quote_amount_sold**))

**Comment by LefterisJP** [comment]
Thank you for opening an issue @CyBHFal!

Do you have an example csv file where these rules are touched along with what you would expect to happen as opposed to what is happening?

**Comment by CyBHFal** [comment]
Timestamp (UTC),Transaction Description,Currency,Amount,To Currency,To Amount,Native Currency,Native Amount,Native Amount (in USD),Transaction Kind
2021-12-23 13:13:03,Convert Dust,CRO,0.686163538568182018,,,EUR,0.33,0.374813076,dust_conversion_credited
2021-12-23 13:13:03,Convert Dust,BTC,-0.00000782,,,EUR,-0.33,-0.374813076,dust_conversion_debited
2021-12-23 11:46:07,BTC -> CRO,BTC,-0.0822767,CRO,7248.8,EUR,3481.74,3954.550543128,crypto_exchange

![image](https://user-images.githubusercontent.com/32815303/147422441-1cb3120e-60a4-43c1-9995-9b2ef052c0f6.png)

Same direction (BTC to CRO) but see rates ...

**Comment by CyBHFal** [comment]
After some thinking, #3864 doesn't change the good one rate computation.

The modification should be done in import_cryptocom_associated_entries() :

rate = Price(abs(base_amount_bought / **quote_amount_sold**))  

to 

rate = Price(abs(**quote_amount_sold** / base_amount_bought))

Like that:

```
diff --git a/rotkehlchen/data/importer.py b/rotkehlchen/data/importer.py
index de233edbb..9b222fb4e 100644
--- a/rotkehlchen/data/importer.py
+++ b/rotkehlchen/data/importer.py
@@ -580,7 +580,7 @@ class DataImporter():
                     base_amount_bought = deserialize_asset_amount(
                         credited_row['Amount'],
                     ) * part_of_total
-                    rate = Price(abs(base_amount_bought / quote_amount_sold))
+                    rate = Price(abs(quote_amount_sold / base_amount_bought))

                     trade = Trade(
                         timestamp=timestamp,

```
The exchange rate is generally (original currency / new currency) so (sold/bought), isn't it ?

To confirm that, it try #3864 and it give huge amounts in events of "Profit And Loss Report"

**Comment by CyBHFal** [comment]
> _consume_cryptocom_entry()
> rate = Price(abs(quote_amount_sold / base_amount_bought))
> 
> _import_cryptocom_associated_entries()
> rate = Price(abs(base_amount_bought / quote_amount_sold))

Was not clear above but it was a copy of the two functions names with the rate computation of each, not a correction before/after

**Comment by yabirgb** [comment]
> After some thinking, #3864 doesn't change the good one rate computation.
> 
> The modification should be done in import_cryptocom_associated_entries() :
> 
> rate = Price(abs(base_amount_bought / **quote_amount_sold**))
> 
> to
> 
> rate = Price(abs(**quote_amount_sold** / base_amount_bought))
> 
> Like that:
> 
> ```
> diff --git a/rotkehlchen/data/importer.py b/rotkehlchen/data/importer.py
> index de233edbb..9b222fb4e 100644
> --- a/rotkehlchen/data/importer.py
> +++ b/rotkehlchen/data/importer.py
> @@ -580,7 +580,7 @@ class DataImporter():
>                      base_amount_bought = deserialize_asset_amount(
>                          credited_row['Amount'],
>                      ) * part_of_total
> -                    rate = Price(abs(base_amount_bought / quote_amount_sold))
> +                    rate = Price(abs(quote_amount_sold / base_amount_bought))
> 
>                      trade = Trade(
>                          timestamp=timestamp,
> ```
> 
> The exchange rate is generally (original currency / new currency) so (sold/bought), isn't it ?
> 
> To confirm that, it try #3864 and it give huge amounts in events of "Profit And Loss Report"

I believe I got it messed. I was comparing to other places but as you said I might got it wrong. So just to double check the rate is different if it is buy or sell.

[Here](https://github.com/rotki/rotki/blob/1893fc6c10919c018137d63e99365e4f45749cb8/rotkehlchen/data/importer.py#L274) It should be calculated differently. if it is buy `base  / quote` and if it is sell `quote / base` and in [here](https://github.com/rotki/rotki/blob/1893fc6c10919c018137d63e99365e4f45749cb8/rotkehlchen/data/importer.py#L583) since is always a buy it should be `quote / base`. Sounds right?

**Comment by CyBHFal** [comment]
> [here ](https://github.com/rotki/rotki/blob/1893fc6c10919c018137d63e99365e4f45749cb8/rotkehlchen/data/importer.py#L583) since is always a buy it should be quote / base

Yes. For now,  quote_amount_sold / base_amount_bought solves my initial issue of huge values in event list of the Profit/loss report


> [here ](https://github.com/rotki/rotki/blob/1893fc6c10919c018137d63e99365e4f45749cb8/rotkehlchen/data/importer.py#L274) It should be calculated differently. if it is buy quote / base and if it is sell base/quote 

Unfortunately, as a newbie, I'm not able to confirm if something should be change here ... And I don't have sells transactions to check if current implementation is correct. For a buy, current implementation seems to give good results.
