### ISSUE TITLE
ShapeShift airdrop showing for newly added accounts as eligible for airdrop

### ISSUE THREAD

**Issue by arosboro** [rotki/rotki#3869]
## Problem Definition

When I claimed the airdrop I had account \#0 eligible to claim and a native wallet on another account eligible for a smaller amount.  Now having lost eligibility to claim (the airdrop is over), I added account \# 1, an additional ethereum account.

Rotki shows this account eligible for an additional amount equal to account \#0.

### System Description
Mac OS X

Operating system: 
Rotki version: 1.22.2

**Comment by LefterisJP** [comment]
How did you lose eligibility? The eligibility for airdrops is based on CSVs and is not time dependent at the moment, unless the CSV has this data.

**Comment by arosboro** [comment]
Maybe the account existed but had not been used for any transactions back when it was eligible.  I guess my hardware wallet has about 10 accounts from the seed phrase but I was only using account 0.  And recently did a transaction on account 1, then my eligible fox increased by 250 (I think the minimum for an account) in rotki.

https://fox.shapeshift.com/airdrop. The airdrop has ended. 

If the airdrop section shows I'm eligible will rotki include it in the PNL?  The address in question was the one I transacted with rotki grants with recently.

**Comment by arosboro** [comment]
I guess I'm still eligible, but I did not think to check every account on my wallet and did not claim it. Meaning I don't want to report an income for a cost basis of ~$352 for that particular address's airdrop of 250 tokens I didn't claim.

**Comment by LefterisJP** [comment]
No rotki does not include as PnL something that you have not claimed. What's more airdrops claiming are not detected automatically yet. You would have to input it on your own.

**Comment by arosboro** [comment]
Ok, It appears I underestimated this assuming the Defi features were covered under the P&L including airdrops.  Thanks for the guidance to create manual ledger entries for those claimed.  I'll close this ticket to reduce the burden on your team.
