### ISSUE TITLE
Refactor how selected binance pairs are queried from database

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3886]
At the moment binance pairs selected by users are queried [here](https://github.com/rotki/rotki/blob/fdd99f73320cfc1466f0304bcae2bbfa42045303/rotkehlchen/exchanges/binance.py#L812). 

As @LefterisJP noticed the function `get_exchange_credentials_extras` is executed at [exchange initialization](https://github.com/rotki/rotki/blob/fdd99f73320cfc1466f0304bcae2bbfa42045303/rotkehlchen/exchanges/manager.py#L282) and queries the same table. Doing a refactor on the logic of how this information is stored/queried we could save one database query on every trade query.

1. The selected pairs are populated at exchange initialization
2. Every time the pairs are updated the binance instance is notified

This way the information is always on sync and we need less queries. Might need a little more think.

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/issues/3886
