### ISSUE TITLE
Add memo text for each ethereum transaction

### ISSUE THREAD

**Issue by shayzluf** [rotki/rotki#3898]
## Abstract

When you preform a blockchain action that can be simple(transfer to account) or complex (execute a governance decision) there is a need to record it and its purpose. 

## Motivation

Looking into the past i can see that there are many txs that i can’t remember their purpuse. having a memo that is coupled with transactions on the blockchain will be a great added feature.

## Specification

On the ethereum transaction tab add a memo field that can be added and edited with an history.

**Comment by LefterisJP** [comment]
We should have an editable "notes/memo" field on most things, including ethereum transactions. Thanks for the issue!

**Comment by shayzluf** [comment]
> We should have an editable "notes/memo" field on most things, including ethereum transactions. Thanks for the issue!
> 
> But we should make this common across all events and not specific only to ethereum transactions.

Thanks for generalizing it 
it will be awesome to have

**Comment by rishav-karanjit** [comment]
Hello, I want to work on this issue. Can I please be assigned to it?

**Comment by yabirgb** [comment]
Hello @rishav-karanjit ! Sure :) If you need anything let us know. We are also on discord https://discord.gg/aGCxHG7 with a support channel for devs

**Comment by LefterisJP** [comment]
With the transaction decoding work this may no longer be useful though. As users can add notes in the decoded events.

**Comment by LefterisJP** [comment]
Closing this as it's now irrelevant due to the possibility to edit transaction notes for any transaction
