### ISSUE TITLE
crypto.com importer: missing 'Transaction Kind's

### ISSUE THREAD

**Issue by mizzitant** [rotki/rotki#3899]
## Problem Definition

Some things I noticed with the crypto.com importer: rotkehlchen/data/importer.py

Two **'Transaction Kind's** seem to be **missing**:
* **supercharger_reward_to_app_credited**: Example line 
Timestamp (UTC) | Transaction Description | Currency | Amount | To Currency | To Amount | Native Currency | Native Amount | Native Amount (in USD) | Transaction Kind
2021-10-28 03:16:37 | Supercharger Reward | AXS | 0.00356292 |   |   | EUR | 0.38 | 0.4430698990794 | supercharger_reward_to_app_credited
* **recurring_buy_order**: probably needs to be handled as Trade: https://github.com/rotki/rotki/blob/develop/rotkehlchen/data/importer.py#L240

Not an issue but maybe worth to mention it: I don't think there is a 'Transaction Kind' reinbursment https://github.com/rotki/rotki/blob/develop/rotkehlchen/data/importer.py#L326. reimbursement does exist though and already is handled as Trade in https://github.com/rotki/rotki/blob/develop/rotkehlchen/data/importer.py#L248

Rotki version: 1.23.0

**Comment by yabirgb** [comment]
Hello! Thanks for reporting them. Could you please provide an example for the `recurring_buy_order`?

**Comment by mizzitant** [comment]
It's pretty much like viban_purchase:

Timestamp (UTC) | Transaction Description | Currency | Amount | To Currency | To Amount | Native Currency | Native Amount | Native Amount (in USD) | Transaction Kind
2021-10-13 21:00:09 | Recurring Buy | EUR | 80 | ETH | 0.0246158182949 | EUR | 80 | 93.2778734904 | recurring_buy_order

**Comment by mizzitant** [comment]
Sorry, it actually differs from viban_purchase: for `recurring_buy_order` the amount value is positive.

**Comment by LefterisJP** [comment]
Hey @mizzitant what's your OR? Want to give you a link to a nightly containing Yabir's fix to confirm it works for you.

**Comment by mizzitant** [comment]
Limux

**Comment by LefterisJP** [comment]
> Linux

Here you go: https://we.tl/t-HNylwIlwus

**Comment by mizzitant** [comment]
`recurring_buy_order` - seems to be correct
`supercharger_reward_to_app_credited` - displayed as Ledger Action of type Income
`viban_purchase` - expected: Trades -> "buy [XYZ] With EUR Rate [x]". Nightly build: "buy EUR with EUR Rate 1.00"

**Comment by yabirgb** [comment]
Hello @mizzitant ! Thanks for reporting the issue to us. Here is another build that should fix the trade issue for the viban_purchase event. Could you test it and let us know if you find any other issue? The commit for the build is https://github.com/rotki/rotki/commit/abde36e783f25385cee0717058b1c13b748d1a7d

https://we.tl/t-lAiQeg7dqq

**Comment by mizzitant** [comment]
looks good, thanks

**Comment by LefterisJP** [comment]
So closing this issue and fix will be included in the next patch release.
