### ISSUE TITLE
Assets for 1.24.0

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3914]
## Abstract

Here is a coverall issue for all assets to add in 1.24.

## Task

Add the Israeli currency as a selectable fiat currency: https://en.wikipedia.org/wiki/Israeli_new_shekel

**Comment by yabirgb** [comment]
ILS is already added for the next release. As it is a FIAT currency needs also to be added in the frontend

**Comment by LefterisJP** [comment]
Add DONUT: https://www.coingecko.com/en/coins/donut

**Comment by yabirgb** [comment]
Add cvxFXS https://etherscan.io/token/0xFEEf77d3f69374f66429C91d732A244f074bdf74

**Comment by LefterisJP** [comment]
Also add the infamous WTF token. MAny people will wanna see how down bad they are: https://www.coingecko.com/en/coins/wtf-token

**Comment by LefterisJP** [comment]
Add support for reddemable Keep3r: https://etherscan.io/address/0xedb67ee1b171c4ec66e6c10ec43edbba20fae8e9
https://andrecronje.medium.com/keep3r-redeemable-kp3r-rkp3r-c200fb8740ef

**Comment by xtc0r** [comment]
Add support for BABL: https://etherscan.io/token/0xF4Dc48D260C93ad6a96c5Ce563E70CA578987c74
https://www.babylon.finance
https://www.coingecko.com/de/munze/babylon-finance

**Comment by lulepu** [comment]
Add xXTKa https://etherscan.io/address/0x314022e24ced941781dc295682634b37bd0d9cfc
its a staked version of XTK. there is no price feed available and the underlying XTK value changes constantly. Would be great to have it as an asset with a price

**Comment by LefterisJP** [comment]
> Add xXTKa https://etherscan.io/address/0x314022e24ced941781dc295682634b37bd0d9cfc its a staked version of XTK. there is no price feed available and the underlying XTK value changes constantly. Would be great to have it as an asset with a price

Adding a price feed for a token is unfortunately different to adding a token. We would need to study the protocol adn figure out how price is determined, and see if it ccan be calculated properly.

**Comment by yabirgb** [comment]
Luna needs to be mapped for crypto.com

**Comment by LefterisJP** [comment]
Add coingeko and cryptocompare mappings to old Aleph token: `_ceth_0xC0134b5B924c2FCA106eFB33C45446c466FBe03e`:  https://www.coingecko.com/en/coins/aleph-im

**Comment by LefterisJP** [comment]
Add support for stkAave. Essentially staked Aave. Price oracles should all point to same as aave: https://etherscan.io/address/0x4da27a545c0c5B758a6BA100e3a049001de870f5

**Comment by LefterisJP** [comment]
Add information for KP4R:
https://etherscan.io/address/0xA89ac6e529aCf391CfbBD377F3aC9D93eae9664e

**Comment by LefterisJP** [comment]
Add information for rHegic:
https://www.coingecko.com/en/coins/rhegic2
https://etherscan.io/address/0x47C0aD2aE6c0Ed4bcf7bc5b380D7205E89436e84
https://etherscan.io/address/0xad7ca17e23f13982796d27d1e6406366def6ee5f

**Comment by LefterisJP** [comment]
Add unit protocol COL token: https://www.coingecko.com/en/coins/unit-protocol

**Comment by LefterisJP** [comment]
Input all info for Bancor governance token: https://www.coingecko.com/en/coins/bancor-governance-token

**Comment by xtc0r** [comment]
The babylon.finance project started their heart of babylon (https://www.babylon.finance/heart). It stakes BABL to receive hBABL

hBABL: https://etherscan.io/token/0xaa2d49a1d66a58b8dd0687e730fefc2823649791

Please add support for hBABL as well.

**Comment by LefterisJP** [comment]
Add support for vCOW: https://github.com/rotki/rotki/issues/4009
