### ISSUE TITLE
0.00% on Generating Profit and Loss Report - please advice

### ISSUE THREAD

**Issue by fire17** [rotki/rotki#3915]
## Problem Definition

Hi there, im checking out rotki for the first time,
have not got a premium yet
trying to generate P/L report
if I understand this correct, it will a good for tax report (this is my main objective)
right now it is frozen on 0.00% , was wondering if this is just because i've not yet got the premium or is it something else?

please let me know if i got this right or what...
thanks a lot, have a good one
![image](https://user-images.githubusercontent.com/9356048/148370224-f2c07da8-108a-4ac8-847d-05ea8d033ff0.png)

Operating system: 
Rotki version: 1.23.0

**Comment by LefterisJP** [comment]
Hey @fire17 please join our discord server to ask questions like this: https://discord.com/invite/aGCxHG7
There is a captcha to join. And we have a #support channel.

Also make sure to read our guide. Specifically on why binance is so slow and what you need to do about it: https://rotki.readthedocs.io/en/latest/usage_guide.html#binance-binance-us

 Github issues are not for general questions like this.

**Comment by fire17** [comment]
@LefterisJP 
Thanks a lot ! this helped , to quote from the doc (to help others)

### Binance / Binance US
Binance API is engineered in a way that makes it really slow to query information for trades since every possible market pair has to be queried. This process can also fail since many requests have to be made to binance servers and rate limits may apply. To avoid having to query all existing trade pairs, **it is possible to select what markets should be queried. This will considerably increase the speed as the amount of queries to binance** will be reduced to only the markets you specify. To select which what markets you want to query edit your binance exchange instance
