### ISSUE TITLE
Impossible to use the same address for both Avalanche and Ethereum

### ISSUE THREAD

**Issue by evilny0** [rotki/rotki#3943]
## Problem Definition

It is impossible to use the same address for both Avalanche and Ethereum.

I noticed it when trying to remove/add my Avalanche account when it was failing to update balances, before I saw #3921 . I waited for 1.23.1 to be released, but it's still not working, so I guess it was not related to the failing balance update. I had it working at some point, I don't quite remember in which version I added the Avalanche account unfortunately.

### Steps to reproduce:

I reproduced it on a clean 1.23.1 install.

- Add an Ethereum account with address A.
- Try to add an Avalanche account with the same address A.

Result: _The selected addresses are already tracked by rotki_

### System Description

Operating system: Linux.
Rotki version: 1.23.1

**Comment by yabirgb** [comment]
Hello @evilny0 ! Thanks for letting us know. I could reproduce the error. As a workaround for now I managed to add them adding it first as avalanche address and then as ethereum address. Would fix it for the next release

**Comment by yabirgb** [comment]
@lukicenturi @kelsos I've reproduced the steps making queries to the backend and can add both chains without issue. Has to be a frontend issue

**Comment by kelsos** [comment]
@yabirgb So we fixed the frontend bug but only for a single account addition, not for multiple

**Comment by yabirgb** [comment]
@kelsos Curious about why inverting the other of chains works

**Comment by kelsos** [comment]
Fixed by #3955
