### ISSUE TITLE
Write UI tests for the navigation and data persistence bugs

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#396]
## Description

Write UI tests for the two bugs having to do with navigation and data persistence.

### Test 1

PR https://github.com/rotkehlchenio/rotkehlchen/pull/393 fixes #325 

ESsentially the problem there was that adding or removing anything in the user settings (an ETH account, a BTC account, tracking a token) did not reflect itself later if you visited the dashboard.

So a test needs to be written that adds/removes data from the user settings as described above and the changes are seen later when visiting the dashboard.

That is essentially 6 sub tests for all the cases.

### Test 2

PR https://github.com/rotkehlchenio/rotkehlchen/pull/394 fixes #392.

The problem is that if you deleted a row from the per account's table in the user settings, either an ETH account or a BTC account you only deleted that row from the user settings page, and sent the api call to the backend to delete it.

But the local copy of the data in the frontend were not altered. So if you navigated away from the user settings and then back again, the deleted account appeared again on the tables.

So the test should simply delete an account from the ETH table, navigate away and come back and make sure it's not there. And then do the same for BTC.

**Comment by kelsos** [comment]
I am closing this issue. This was required with the old architecture before migrating the app to vue.
