### ISSUE TITLE
Liquity: Missing movements for DSProxy Troves

### ISSUE THREAD

**Issue by bingen** [rotki/rotki#3964]
## Liquity: Missing movements for DSProxy Troves

Trove operations show up fine for regular troves, but not for troves owned through a DSProxy (e.g. created on DeFiSaver)

![Screenshot_20220118_172422](https://user-images.githubusercontent.com/701095/149978896-e1b77634-121a-4f76-95cb-cc3b4e6cfcd2.png)

## Motivation

It feels incomplete and inconsistent.

**Comment by yabirgb** [comment]
Thanks for reporting it @bingen! If you have time to test it I can prepare a binary with the fix, only need the OS. We are releasing it soon if everything goes as expected

**Comment by bingen** [comment]
Thanks @yabirgb ! The problem is that I use Rotki on my DAppNode, so I guess it won’t be as easy.
But you can find a bunch of examples to test with here:
https://twitter.com/search?q=DeFiSaverBot%20liquity&src=typed_query

**Comment by LefterisJP** [comment]
Should be fixed by #3969 and will be included in 1.23.2
