### ISSUE TITLE
Add status of the Liquity protocol to the frontend

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3971]
The collateral ratio of the Liquity protocol is important to detect when liquidations in recovery mode can happen. More at https://docs.liquity.org/faq/recovery-mode. It would be nice to have it in rotki since now you have to visit other frontends to know if your position is safe or not

For this to be added the backend needs to call the contracts and inspect the status of the protocol and the frontend needs to properly display this information.

We need to call https://etherscan.io/address/0xA39739EF8b0231DbFA0DcdA07d7e29faAbCf4bb2#readContract for 
![image](https://github.com/rotki/rotki/assets/5068010/0a483d58-faaa-45a4-9ff0-6a4c09d8ce3a)

and do
```
(systemColl * eth price) / (systemDebt * lusd price)
```

**Comment by 3scava1i3r** [comment]
taking this up, @yabirgb
