### ISSUE TITLE
Profit tracking for Liquity

### ISSUE THREAD

**Issue by bingen** [rotki/rotki#3973]
## Abstract

Separate profit trackers for Liquity yield generating modules: LQTY Staking and Stability Pool.

## Motivation

It would be nice to have separate profit trackers for the Stability Pool (when it’s done, see issue #3366) and Staking. Maybe a graph showing total gains and ROI.

- For the Stability Pool it should show LQTY and ETH gains but also how much LUSD has been used for the debt settlement. Maybe LUSD 'lost' vs. ETH gained.
- For staking LUSD and ETH gains, maybe some data on average ROI for the user since he joined as well.

**Comment by thibauld** [comment]
+1 that'd be great :hugs:

**Comment by LefterisJP** [comment]
This is done and in 1.28!
