### ISSUE TITLE
Rendering images hosted by a malicious 3rd party can lead to ip leaks

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3975]
## Problem Definition

The blog post author [here](https://medium.com/@alxlpsc/critical-privacy-vulnerability-getting-exposed-by-metamask-693c63c2ce94) describes a scenario where a malicious actor creates an NFT with an image link that points to an image hosted by a malicious server. That NFT is specially prepared and "donated" to a specific ethereum address.

When the owner of that addressr (or anybody else) goes to render that image from a wallet, NFT viewer, aggregator then the ip is logged. If that rendering is done client side, as for example in metamask or rotki then the logged ip would be the ip of the user. The malicious server can then match ip + timestamp + ethereum address.

That is not a good thing to leak and is quite sensitive info as also explained in the blogpost.

## Task

The way to address this would be:  (if anyone has other ideas all ears!)

1. Only render ipfs links by default. Since that scenario won't work with ipfs. Any other hosting methodology that we can have an exception for?
2. For all others, explicitly ask the user if they trust that url. Put it in some kind of whitelist. Have that list editable by the user at all times. At the popup prompt we should also give them an option to go and set (3)
3. Have a catch-all setting to just blindly trust all 3rd party images. Should be off by default. At the place where this setting is set clearly explain the dangers.

**Comment by yabirgb** [comment]
didn't think about this attack but is very basic and powerful. Maybe in the settings we can have by default a "block NFT images" and block by default everything unless the user states otherwise and then have something similar per NFT. For what I saw with some NFTs opensea downloads and store in their storage the images of the NFTs but would need to check this again

**Comment by LefterisJP** [comment]
> didn't think about this attack but is very basic and powerful. Maybe in the settings we can have by default a "block NFT images" and block by default everything unless the user states otherwise and then have something similar per NFT. For what I saw with some NFTs opensea downloads and store in their storage the images of the NFTs but would need to check this again

Why are the 3 things I wrote not enough?
