### ISSUE TITLE
Add gnosis COW airdrop

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4009]
Data available at https://docs.google.com/spreadsheets/d/1xDjH8xA3hmKCgtEmSTwLSBrNMgK3SOyBeZ1inat2TqE/htmlview?pru=AAABfsGmNOM*x4TcRicfKkNdoSb5wQbI7w#

More info at https://twitter.com/MEVprotection/status/1486821916639903748

**Comment by yabirgb** [comment]
Allocation has been updated as per https://twitter.com/MEVprotection/status/1487140241102319622?s=20&t=RDtNHQl25uK-NYcp3NvigQ

**Comment by LefterisJP** [comment]
Claims open: https://cow-protocol.medium.com/cows-together-strong-welcome-vcow-token-to-the-cow-ecosystem-7689c4391373
