### ISSUE TITLE
User already exists during setup (DAppNode)

### ISSUE THREAD

**Issue by MysticRyuujin** [rotki/rotki#4034]
## Problem Definition

Using DAppNode Package:

1. Install Rotki
2. Setup Rotki using Premium API Key with restore sync'd database option
3. Enter incorrect password
4. Get error that password could not decrypt database
5. Go back
6. Enter correct password
7. "User $USERNAME already exists. User data dir: /data/$USERNAME"

Can't proceed...have to delete and re-create Rotki package

## Logs

None

### System Description

Operating system: DAppNode
Rotki version: DAppNode Package `0.1.9 (v1.23.1 upstream)`

**Comment by LefterisJP** [comment]
Thank you for the report Chase. Let me look at this.

**Comment by LefterisJP** [comment]
I can confirm this happening and it's not only in docker. Will provide a fix in next release.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/4037
