### ISSUE TITLE
Replace zerorpc with normal HTTP Rest API

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#404]
## Problem Definition

Zerorpc is a pain in the ass the way Rotkehlchen has evolved.

1. We need to have a hack in long running API calls to make sure that gevent does at least 1 context switch every 10 seconds to avoid the dreaded heartbeat error: https://github.com/rotkehlchenio/rotkehlchen/blob/605d56edf46d20d090e4d3dad94becd88c8749a5/rotkehlchen/accounting/accountant.py#L397

2. The module used both in python but more importantly in node for zerorpc is outdated and not maintained. Upgrading to a new electron version becomes harder and harder since the package needs to be forked and maintained by me to do so.

3. Dependency to ZeroMQ and ZeroRPC goes away

4. Some bugs that pop up are suspected to be due to the way zerorpc handles communication between backend and client.

## Task

1. Remove zerorpc server from the backend. Replace with a normal rest HTTP API server.

2. Remove zerorpc client from the frontend side. Replace with simple RPC queries.

**Comment by kelsos** [comment]
@LefterisJP are we doing this for v1.0.0 or after the vue rewrite? both should be viable since we have extracted the functionality to the service.

**Comment by LefterisJP** [comment]
100% after.

**Comment by LefterisJP** [comment]
Not completely done. With #526 all of the backend work is done but the replacing of the front-end zerorpc client with an http axios client is still being done in: https://github.com/rotki/rotki/pull/573

**Comment by LefterisJP** [comment]
Done!
