### ISSUE TITLE
Frontend doesn't update loading window when tasks have finished

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4045]
## Problem Definition

When clicking on one section of the app (I triggered it by clicking on staking) if there are pending tasks the UI shows a spinning circle.
When all the tasks have cleared and the content should be visible you still see this spinning circle. To get the information you have
to change the view and click again on what you wanted.

![image](https://user-images.githubusercontent.com/5068010/152337474-86e38cf8-52eb-41d1-9ac3-2c46d58a16b4.png)

### System Description

Operating system: Linux
Rotki version: Develop branch

**Comment by kelsos** [comment]
Just a note, this bug is only on develop so it doesn't require a changelog and it doesn't have to go to bugfixes
