### ISSUE TITLE
Menu has big gap from app bar

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4054]
## Problem Definition

The app bar menus have quite a big gap from the app bar itself.

![image](https://user-images.githubusercontent.com/2269732/152548457-de3f1c1f-b825-4731-80bc-8b8a1e5e754a.png)

The should open closer to the app bar.

![image](https://user-images.githubusercontent.com/2269732/152549086-30bc9178-9d11-4e9b-a95e-6c2c4c8e599f.png)

### System Description

Operating system: windows/linux for sure
Rotki version: 1.23.3

**Comment by LefterisJP** [comment]
Just a small note. This is also for the, currency menu bar.
