### ISSUE TITLE
Crypto.com card cashback appears as "buy", should it not be gift instead?

### ISSUE THREAD

**Issue by AdalLS** [rotki/rotki#4060]
This is with the latest update (1.23.3). All cashback received from using the card appears as a purchase in trades. Should it not be considered a gift instead?

**Comment by yabirgb** [comment]
Hello @AdalLS ! Gift in the app are for gifts that you make to other people, so is not something that you receive

**Comment by AdalLS** [comment]
I see, but still it does not seem right co consider them as a buy. Because those amounts were not bought by me strictly speaking, but deposited in my account by CDC.

I am fairly confident that most countries consider cashback as non-taxable.

**Comment by LefterisJP** [comment]
> I see, but still it does not seem right co consider them as a buy. Because those amounts were not bought by me strictly speaking, but deposited in my account by CDC.
> 
> I am fairly confident that most countries consider cashback as non-taxable.

you can edit the generated ledger actions to whatever you need it for your own jurisdiction

**Comment by AdalLS** [comment]
I understand. But I still think they should be considered as some kind of "deposit" or interest yield, or the category used for staking rewards, but not as a buy, as the purchase price should be 0.

**Comment by LefterisJP** [comment]
> I understand. But I still think they should be considered as some kind of "deposit" or interest yield, or the category used for staking rewards, but not as a buy, as the purchase price should be 0.

Yes that is true. The default here should change.

It should be either Gift or something else. Will think a bit on it.

**Comment by LefterisJP** [comment]
Hey @yabirgb we can easily close this in 1.24.0? Right? Just change the default for this import?
