### ISSUE TITLE
Validation of date for ledger actions

### ISSUE THREAD

**Issue by AuHau** [rotki/rotki#4072]
## Problem Definition

I have accidentally added ledger action with a future date and was very confused because rotki did not complain but could not find the entry anywhere. I assume that adding future ledge actions is not really valid and maybe should be prevented with some validation?

### System Description

App Version: 1.23.3
Frontend Version: 1.23.3
Platform: darwin x64 12.2.0
Electron: 16.0.1

**Comment by yabirgb** [comment]
Thanks for reporting @AuHau ! I can reproduce it. It is saved in the database but not displayed in the UI. I believe the backend also should disallow entering future events

**Comment by kelsos** [comment]
Closed by #4111

**Comment by LefterisJP** [comment]
This issue would also need a backend validation part imo. Can you handle it @yabirgb and also add a backend test?

**Comment by yabirgb** [comment]
Taking this issue for the backend
