### ISSUE TITLE
Coinbase Pro Api error 502 not being properly handled.  causes entire data import to fail.

### ISSUE THREAD

**Issue by SirOsisOfTheLiver** [rotki/rotki#4104]
## Problem Definition

I started with a clean new installation and added my coinbase pro secret etc.
I tried to hit history and it started importing

After a long time  (I went away, so not sure how long but left after 10 minutes)
it failed with the error message :

Failed query for all exchanges: Error: Coinbase Pro GET query at https://api.pro.coinbase.com/orders?

Edit: I removed the Error message because it doesn't display properly and attached it as a file instead

This happened before the UTC time was Febrary 24th   (approximately 10:30 pm on the 24 UTC time)
I beleive the Z means UTC time, so I don't understand why the code would be asking for orders which were submitted after the current time.

This is either a logic error with paginating and not being able to tell when to stop  or starting with time that hasn't yet occurred.
It ran for a long time before failing, so my guess is it can't figure out properly when to stop requesting the next 100 records.

Even if it makes the request, I believe the proper way to handle the 520 response would be to stop asking for new data (presumably we already have everything we are supposed to get) and save the data.

Currently, it aborts without importing any data.

This is preventing me from filing this years taxes on multiple tax sites, so I suspect it is a recent change on Coinbase pro, but that is just a guess

a google for "coinbase pro api error 520" shows a few other people have encountered this, and also a very similar response for the kraken api.

There is nothing in the Coinbase Pro Error codes to explain what 520 means.
 If it helps, we can set up a direct contact with me so I can provide a developer my View only Coinbase Pro secret, passphrase etc.

<title>api.pro.coinbase.com

### System Description
This is on a Windows Binary installation (Windows 10)

Operating system: 
Rotki version: 1.23.3

**Comment by SirOsisOfTheLiver** [comment]
It didn't like my copy paste of the error message from the rotki app.
I will attach a plain text file
[RotkiError520.txt](https://github.com/rotki/rotki/files/8137320/RotkiError520.txt)

**Comment by SirOsisOfTheLiver** [comment]
Update :  now 40 minutes later my data showed up in the app, so this is not a sever bug.

You can close the issue if you want.

I didn't know the data would eventually show up.

Sorry

**Comment by LefterisJP** [comment]
You got a 502 error, which means coinbase's API responded in a completely unexpected way. From your attached .txt it seems coinbase had a problem and responded with html instead of a normal JSON api response. It was temporary as it worked later.
