### ISSUE TITLE
Kucoin query for historical trades is not working anymore

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4122]
## Problem Definition

Kucoin has deprecated the endpoint to query for historical trades. 

![image](https://user-images.githubusercontent.com/5068010/156827772-3edd864f-3222-4482-b16b-fed12f014689.png)

As an alternative as described here https://github.com/Kucoin/kucoin-api-docs/issues/363 we can use the ledger endpoint https://docs.kucoin.com/#get-account-ledgers

### System Description

Operating system: 
Rotki version:

**Comment by LefterisJP** [comment]
Since this is a bug I am adding it to 1.24.1

**Comment by LefterisJP** [comment]
should be fixed by #4410
