### ISSUE TITLE
Evaluate electron's safe storage for auto-login

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4125]
## Abstract

Evaluate electron's [safe storage](https://www.electronjs.org/docs/latest/api/safe-storage) to implement the option for auto-login.

At least from an initial glance, it seems that safe storage uses the systems keychain service to provide storage of secrets.

We could expose this through our electron interop interface and when encryption support is available we could give the user the option to save the password and provide an auto-login mechanism.

**Comment by LefterisJP** [comment]
That would only work for the electron app, right? No way to do this for docker?

**Comment by kelsos** [comment]
> That would only work for the electron app, right? No way to do this for docker?

Yes, this would be for electron, for docker the application runs in the browser. You should have access to a password manager on the other hand. 

There are things we could do in the browser but would probably require changes to the backend.
An approach would be some kind of access token that the backend generates, hands to the frontend, and uses that for validation (better when SSL is used).
