### ISSUE TITLE
Add support for stock tracking

### ISSUE THREAD

**Issue by mortee** [rotki/rotki#4137]
## Abstract

I just discovered Rotki, and at first glance it seemed exactly what I needed: a self-hosted and private browser-based investment tracking solution. But apparently, it really focuses on crypto. 

However, in a [2019 Value Vision blog post](https://blog.rotki.com/2019/08/03/rotkehlchen-value-vision/), there's mention of planned support for other asset classes, like stocks etc.

I wonder if it's just me missing the obvious and those are already part of the portfolio, or this's been somehow left behind?

In that case, do existing users have any recommended way to work around this limitation, like substituting some random crypto assets for my stock portfolio, or something similar?

## Motivation

I may have other investments besides crypto.

## Specification

Add support for stocks etc.

**Comment by LefterisJP** [comment]
Hello mortee this is something we still want to do in the long run but it's not feasible with the way api for stock prices are right now (most of them are not open).

There is a way to solve that problemt now. It's kind of clunky though. You can add manual balance: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-manual-balances and add it in EUR/USD what have your and describe it appropriately. You would unfortunately have to update it and its price manually.

This is how I track my stocks at the moment (I also have some stocks in my portfolio) and am a power user of rotki.

Another step towards full non-crypto asset support would be creation of custom assets + custom price as seen here: https://github.com/rotki/rotki/issues/2021

Does that answer you question? As for an ETA for those two I unfortunately can't give anything right now.

**Comment by mortee** [comment]
Thank you, I'll look into those suggestions. In any case, thus far I've been using a LibreOffice spreadsheet to track this stuff, and (with intermittent interruptions) the [Financials Extension](https://github.com/cmallwitz/Financials-Extension) proved to be useful. Maybe Rotki could do something along these lines in order to provide at least _some_ solution to stocks, lacking a proper one.

**Comment by LefterisJP** [comment]
That extension uses web scraping which is (a) in most cases against the various websites terms & conditions (b) inefficient and in need of constant changing (since websites change).

Ideally a free API should be found.

I will keep the issue open @mortee, specifically for the feature of adding stocks support (along with automatic price pulling) to rotki, as it's a clear cut description and I don't think we have one open yet. #2021 mentions other asset classes but would still require manual price entry.

No promises on dates as this point but yes we want this.

**Comment by LefterisJP** [comment]
Actually there is already an issue for this so closing it in favor of that one: https://github.com/rotki/rotki/issues/700
