### ISSUE TITLE
Nexo CSV has issues with some Types, Currencies and Currency Swaps.

### ISSUE THREAD

**Issue by 3DNut** [rotki/rotki#4138]
I am a new user. I imported the Nexo .csv and there were a bunch of transactions that were not imported and shown to be problematic.

Type: ‘Exchange Cashback’ was not successful.
Currency Swaps: USDC/AVAX, USDC/MATIC, USDC/USDTERC, USDC/DAI, XLM/USDC, USDC/NEXOBNB were not successful.
Currencies BNBN and NEXOBNB were not successful.
[nexo_transactions_import_problems_edited.csv](https://github.com/rotki/rotki/files/8310247/nexo_transactions_import_problems_edited.csv)

**Comment by yabirgb** [comment]
Hello @3DNut ! The importers are very experimental and depend on users reporting us the issues. I'll review the csv that you shared and check whether is possible to handle the cashback information.

Thank you for reporting this issue! If you find any other issue let us know please :)

**Comment by yabirgb** [comment]
Hello @3DNut ! I was checking the available infromation and for the exchanges they seem information about the amounts you receive but not what you gave so is not possible to calculate with this the rate needed for the trade.

Also, do you know the difference between BNBN and NEXOBNB? I couldn't find any information online

**Comment by KingOfSquares** [comment]
To add to this, I get errors for pairs including the following currencies:

BTC/NEXONEXO, EURX/ETH, EURX/LINK, EURX/USDTERC, USDX/USDC, USDC/ETH, and many more. But the key ones seems to be NEXONEXO, EURX, USDTERC, USDX, USDC.

It seems that NEXONEXO is equal to NEXO(just internal trade)

EURX is their EUR(fiat). Whenever you deposit/withdraw EUR Nexo always has two steps. Deposit EUR(They call this "DepositToExchange") and EUR -> EURX (They call this "ExchangeDepositedOn"). It is similar when you withdraw.

USDTERC is Tether

USDX works similarly to EURX

USDC is USDCoin

I have not used GBP in Nexo before but I can imagine it is similar.

**Comment by LefterisJP** [comment]
@yabirgb has this been fixed? Have the users provided example CSVs so we can see how nexo changed their format? They seem to change it all the time. I recall we made quite a fewchanges since this issue was opened.

**Comment by yabirgb** [comment]
For those transactions they were lacking enough information to process them. About the issues with the assets and some other we fixed them here https://github.com/rotki/rotki/commit/eba99df54d56f8a47705b525dc7cc87409683f2a . I'm closing the issue and if something has changed from 1 year ago in the CSV it can be reported again and see how we can handle it
