### ISSUE TITLE
Profit and Loss Report > Export CSV produces location error.

### ISSUE THREAD

**Issue by 3DNut** [rotki/rotki#4139]
## Problem Definition

When I attempt to export a CSV file from a loaded Profit and Loss Report I get '[Errno 13] Permission denied:'. This happens regardless of where I try to save the file.

## Logs

When set the log level to debug I try and export my Profit and Loss report and I get history error
![No History](https://user-images.githubusercontent.com/18043007/159141491-736873ec-b5c5-4bff-a92a-ea98d5812288.png)

I delete the report, generate it again and I get the permission denied error
![Report CSV Export Problem](https://user-images.githubusercontent.com/18043007/159141502-08b301f9-99d8-4647-ba60-29ef02ae54e8.png)

Also, after changing the log level from 'critical' to 'debug', when I try and change the log level back to 'critical' from 'debug, the save option is greyed out.

Hopefully this is enough information. The log seemed to contain information that I would not like to share.

### System Description

Operating system: Windows 10

Rotki version:
App Version: 1.23.3
Frontend Version: 1.23.3
Platform: win32 x64 10.0.19044
Electron: 16.0.1

**Comment by LefterisJP** [comment]
Permission Denied sounds like an Operating system configuration problem and like the logged in user does not have sufficient permissions to save the file anywhere in the system.

Do not share raw log file here. Only any relevant errors. For more information and to share more parts of the log file hop in our discord chat: https://discord.com/invite/aGCxHG7  (there is a Captcha, so have DMs open)

There we have a support channel where our devs will be able to help you (German working hours are the guaranteed online hours). You can share parts of the log there in DMs.


Also the first error, is pretty self-explanatory. It seems no history was processed. So you had no events to process when you got that?

**Comment by kelsos** [comment]
@lukicenturi do you think it would be possible for you to check this on Windows?

**Comment by celkacelka** [comment]
![Inkedcsv export denied_LI](https://user-images.githubusercontent.com/100698769/159685166-21fda038-213f-473b-ac64-418505d72a52.jpg)
.
Blocked by Avast or PCProtect. Followed by a pop-up to allow the app.
The user needs to allow the app and redownload the csv file.
