### ISSUE TITLE
Binance .csv import

### ISSUE THREAD

**Issue by MartinL-MG** [rotki/rotki#4154]
## Abstract

Binance integration today means only the API. The Binance API is a mess so Rotki is missing a bunch of transactions, like Staking, Launchpad and so on

## Motivation

Having Binance as the biggest exchange in Rotki with a good implementation that is no more missing important transactions

## Specification

the key file is the "Transaction History". Binance has so many different export files but this one contains almost all transactions that are important. You can find it here:
* menu >> wallet >> transaction history
* you have to choose a timespan and generate the file
* after some time you can download it as .csv

the file contains
* trades
* start of staking (- balance)
* end of staking (+ balance)
* staking rewards
* start of eth 2.0 staking (- balance eth)
* start of eth 2.0 staking (+ balance beth)
* eth 2.0 staking rewards 
* Launchpad Rewards/Interests
* Withdraw
* Deposit
* buy with fiat balance
* convert small asset balances (dust) into bnb

what is missing:
* credit card buy (menu >> buy crypto >> with credit card)
* fees in withdraw transaction are not listed (see Remark 'Withdraw fee is included')

note:
please be aware that staking has its own transactions for start and end which means that this base currency is substracted and added at the end or when redemption in advance. If the user does it in advance he gets not back 100% of the amount he had spended at the beginning as he had already received the daily rewards and he only should have then 100% of the start amount when he starts redemption in advance. I would recommend to not have a transaction for the start and end as this would cause a "sell" and "buy" resulting in another base cost (?) and would result in extend the 1 year holding duration. But in this case you have to identify with some logic if the user has started the redemption in advance to delete/not import the single reward transactions to not have more than the 100% of the starting amount. I guess this is the biggest challenge here

I would like to share you my detailed original .csv in private instead of uploading it here in public

Thank you

**Comment by LefterisJP** [comment]
I have been provided a CSV by the user and we can use it to implement this feature. So let's see when we find some cycles to spend on this,

**Comment by puiseux** [comment]
Hello,

since 2022-04-28, Binance API propose a lot of staking endpoints (and other endpoints), see [https://binance-docs.github.io/apidocs/spot/en/#change-log]().
Should it be simple or complicated to include staking automatically in Rotki ?
As a programmer, I'm not efficient enough to code it by myself, inside Rotki.
