### ISSUE TITLE
Group all acquisition not found and price not found messages for a PnL report

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#4185]
## Abstract

Especially now with v1.24.0 and the accuracy we get to for acquisition and spends there is going to be a lot of [acquisition not found](https://rotki.readthedocs.io/en/latest/usage_guide.html#no-documented-acquisition-found) errors. Also a lot of 

> Skipping event .. during history processing due to inability to find a price

errors.

This becomes really tiring and hard to navigate for a user.

It would be really beneficial if instead of putting them in the messages aggregator we create a special system for them to be shown independently of the messages at the end of the pnl report.

This is kind of related and perhaps part of https://github.com/rotki/rotki/issues/277

## Task

1. Change the code that adds a message to the messages aggregators whenever there is a problem with missing acquisitions https://github.com/rotki/rotki/blob/629a2d49e1c6ea0aa214d1e6195cc9640465549e/rotkehlchen/accounting/cost_basis/base.py#L244

https://github.com/rotki/rotki/blob/629a2d49e1c6ea0aa214d1e6195cc9640465549e/rotkehlchen/accounting/cost_basis/base.py#L306

2. Instead make it keep the information in a different structure which will be queriable by the frontend at the end of the PnL report and will be shown to the user as part of the report and not as 1000s of "error messages".

### Missing Acquisitions

The structure should at least contain the following:

```python
class MissingAcquisition(NamedTuple):
    asset: Asset
    time: Timestamp
    missing_amount: FVal
```

and be kept in a list at the [CostBasisCalculator](https://github.com/rotki/rotki/blob/5543f832cb0d9c4170940bd3e25977274082c9a3/rotkehlchen/accounting/cost_basis/base.py#L221) object which is part of each PnL run.

### Missing Prices

This is a bit trickier. The accountant skipping an event due to a missing price is caught via an exception. And it's here (let's leave the unsupported asset query for later -- though it may need similar handling):

https://github.com/rotki/rotki/blob/5543f832cb0d9c4170940bd3e25977274082c9a3/rotkehlchen/accounting/accountant.py#L170

#### Getting info from the exception

Now the tricky part comes in getting the information. As the only thing that we get at that point is the exception. 

https://github.com/rotki/rotki/blob/5543f832cb0d9c4170940bd3e25977274082c9a3/rotkehlchen/errors.py#L92-L98

The `NoPriceForGivenTimestamp` error already has all information passed to it at construction. It just needs some adjustment in order to keep the information in the exception's state. So it should keep from the `from_asset`, and `to_asset` in the exception.

What's more it should not get a `date` but a timestamp in the constructor. And that timestamp should also be kept in the exception's state. But it should be converted into a date for the error message when passed to the base exception's constructor.

##### Keeping the information

I guess we should have another list of missing_prices for a pnl report that should be initialized at `reset()` and it should just keep a list of a named tuple like this:

```python
class MissingPrice(NamedTuple):
    from_asset: Asset
    to_asset: Asset
    time: Timestamp
```

### Querying from the API

Now that we will have all this data in nice lists of data structures instead of just error messages for the user we can do very cool stuff. We would need a new api endpoint.

I would probably name it 

`'/history/actionable_items', HistoryActionableItemsResource`

And make it return the list of missing acquisitions and list of missing prices.

### Frontend

Then the frontend would need to query that endpoint once a report is done and it would show all actionable items of that last report.

The frontend can do nice magic here:

- For every missing price take them to the manual historical prices addition with from/to asset and timestamp pre-filled and only thing needed being for the user to input the price. SCOOOOOORE :smile: 
- For missing acquisitions ... hmm wish we could do something similar but perhaps we can just group them by asset or something and present them to the user. I am not sure we can pre-fill actions for them.

**Comment by yabirgb** [comment]
As a user if I had to address 500 errors related to missing acquisitions would be nice to do the work step by step and having persistence of this errors would be nice. Maybe would be a good idea to group them by assets and report that there are missing information for this assets and then having the possibility all the timestamps when this happens

**Comment by yabirgb** [comment]
Also for the missing prices this is something that could be interesting since when the transactions have an automatic asset that is not yet known properlt and no price is found it can give a lot of errors too

**Comment by LefterisJP** [comment]
> As a user if I had to address 500 errors related to missing acquisitions would be nice to do the work step by step and having persistence of this errors would be nice. Maybe would be a good idea to group them by assets and report that there are missing information for this assets and then having the possibility all the timestamps when this happens

Grouping by assets is a good idea. The problem with timestamps is that at the time you get the problem you can't know when something is not registered. This is what most users seemed to think we somehow are able to find out. But we can't. If we could find the missing acquisition we would not have this error.

**Comment by LefterisJP** [comment]
> Also for the missing prices this is something that could be interesting since when the transactions have an automatic asset that is not yet known properlt and no price is found it can give a lot of errors too

Huh yeah I had already edited the subject before seeing this.

**Comment by prettyirrelevant** [comment]
Upon attempting to update the docs to reflect API changes for this issue, grouping response data types proved difficult.
## Why
- The extension that enables documentation was last updated Sept 2021.
- Similar [issue](https://github.com/sphinx-contrib/httpdomain/issues/30#issuecomment-1007860499) received no response from maintainer/community.
## Proposal
- Port API documentation to [Gitbook](https://www.gitbook.com/)

**Comment by LefterisJP** [comment]
> ## Proposal
> * Port API documentation to [Gitbook](https://www.gitbook.com/)

Thanks for the issue. Why Gitbook? I have not seen any projects use it for api documentation. What I have seen flask api being documented with a lot is Swagger: https://flask-restplus.readthedocs.io/en/stable/swagger.html
