### ISSUE TITLE
Loopring User Guide Update

### ISSUE THREAD

**Issue by adam-bro** [rotki/rotki#4195]
To have your Loopring balances detected you will need an API Key from Loopring. To get one visit [https://loopring.io/#/layer2/security]and unlock your account. Once unlocked click Export Account.
<img width="1159" alt="Screen Shot 2022-04-16 at 1 10 36 PM" src="https://user-images.githubusercontent.com/84410897/163684789-74c96998-3443-4357-b23a-98d3470dd024.png">

**Comment by LefterisJP** [comment]
Hello @adam-bro! What is the issue about? I am not sure I understand.

You are quoting our usage guide about loopring but have a different screenshot. Would you like us to update the usage guide with the screenshot you provide since the UI has changed?

**Comment by adam-bro** [comment]
Sorry just saw this now Lefteris. Thanks @yabirgb :)
