### ISSUE TITLE
Rename setting name used for selected binance markets

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4198]
The setting used to store the selected pairs from binance to be synced has a bad name `PAIRS` that should be updated to something more descriptive. Currently is defined as a constant here https://github.com/rotki/rotki/blob/develop/rotkehlchen/db/constants.py#L3

The task to close this issue is:

1. Rename this setting name with something better
2. if this setting is present already in the `user_credentials_mappings` table do an update on that table and use the new name

**Comment by prettyirrelevant** [comment]
Closing this issue as PR #4209 resolves it
