### ISSUE TITLE
Scrollbar on register page isn't visible

### ISSUE THREAD

**Issue by celkacelka** [rotki/rotki#4208]
## Problem Definition

How to recreate: 
Open rotki app in develop in Windows. Try signing up with a new account (I selected not-premium). After selecting your credentials and checking the box it's impossible to go on and set up the account, because the buttons at the bottom are not visible and the scrollbar is lacking. Works in mobile view (see last picture)

![image](https://user-images.githubusercontent.com/100698769/164009375-efaf9e0e-2bff-455f-9567-558edddc96ee.png)

![image](https://user-images.githubusercontent.com/100698769/164010037-e00c40f9-1d31-4795-8d16-00cc0899d327.png)

![image](https://user-images.githubusercontent.com/100698769/164011211-ae73b560-8795-4fab-8b97-3c8a88ef3c63.png)

Should be:
There should be a scrollbar or the content should all be fitted inside the window, since it's just the two buttons missing and scrolling for them is annoying.

Operating system: Windows
Rotki version: 1.23.5.dev535+gd2403067b

**Comment by lukicenturi** [comment]
I can show the scrollbar, but I think I can't ensure that the buttons always showed without scrollbar.
