### ISSUE TITLE
Can't import addresses from metamask

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4212]
## Problem Definition

When trying to add a new address using metamask the process hangs until timeout. To reproduce I did:

1. Click on `Add blockchain account`.
2. Click on metamask
3. Click on save
4. Browser opens (tried brave and firefox)
5. Choose addresses from the metamask UI
6. The app shows the status as loading and doesn't add the addresses

The electron logs doesn't show anything nor does the rotki logs. The browser console is also empty.

![image](https://user-images.githubusercontent.com/5068010/164177263-d22e3b9f-e902-46f4-b341-93cca1d6a2b1.png)

### System Description
Operating system: Tried on LInux
Rotki version: 1.23.4

**Comment by LefterisJP** [comment]
That's in 1.23.4, right? That's weird cause in develop last week Celina also tested it and it worked.

**Comment by yabirgb** [comment]
> That's in 1.23.4, right? That's weird cause in develop last week Celina also tested it and it worked.

Tried also in develop and it works. I got a green message in the UI (in 1.23.4 I wasn't getting it) and then after a while the addresses get added to the app.

**Comment by yabirgb** [comment]
@kelsos @lukicenturi it would be interesting to know what changed in this part of the code before closing the issue at least to know why it got fixed or if it is really fixed. There is a migration of libraries in the frontend but I don't know if this could have any effect

**Comment by lukicenturi** [comment]
I just realized why this is not working. 
I think at some point, metamask change their data structure.
So current version of app won't be able to import the address from metamask.

I already create the fix at [b0bb7da3333073fcb1f5d12a9c61836485a3076f](https://github.com/rotki/rotki/pull/4141) but it is merged to develop. I just didn't think at that time that this will break the functionality

**Comment by yabirgb** [comment]
So I believe we can close this issue as it seems to work in develop
