### ISSUE TITLE
Allow to filter decoded events by different parameters

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4220]
## Abstract

Currently is not possible to filter transactions in the frontend by protocol, timestamp or other params

## Motivation

Improve the quality of the search for ethereum transactions

## Specification

The endpoint to query ethereum transactions should accept parameters for:

- protocol (counterparty)
- timestamp (from and to, we already do this in other places irc)
- address
- asset

at least

**Comment by LefterisJP** [comment]
The reason why they do not get filtered like this by the way is that the order that they appear in is that of the ethereum transacitons the events are in

**Comment by LefterisJP** [comment]
@lukicenturi @kelsos This just needs frontend work and as such would be nice to get it into the release.

With the current implementation you should be able to filter the ethereum transaction and their events right now by:

**These will filter on transactions**

- Time range
- Address

**These will filter on events**

- Asset
- List of counterparties (protocols)
