### ISSUE TITLE
No option to delete deposits added by external CSV.

### ISSUE THREAD

**Issue by pheu** [rotki/rotki#4224]
## Abstract

There is no option to delete deposit entries added by external CSV.

## Motivation

Database is polluted with unwanted data and there is no "delete" option.

## Specification

In the History/Deposits & Withdrawals entries added from CSV should have an "edit" and "delete" icons just like trades in History/Trades that were added by external CSV.

**Comment by LefterisJP** [comment]
There is no way to determine what was added by CSV or an api. If you want to delete data you can delete them by location through the purging data option: https://rotki.readthedocs.io/en/latest/usage_guide.html#purging-data and selecting the appropriate location.

**Comment by pheu** [comment]
> There is no way to determine what was added by CSV or an api.

If so, what makes the difference between trade data that was imported by Cointracking CSV which is delete'able and trade data added by Binance API which is not delete'able?

> If you want to delete data you can delete them by location through the purging data option: https://rotki.readthedocs.io/en/latest/usage_guide.html#purging-data and selecting the appropriate location.

Unfortunately I cannot find location related to this data. I used Cointracking CSV import option. In the purging section I can find every location (from import CSV section) except for Cointracking.

**Comment by LefterisJP** [comment]
> If so, what makes the difference between trade data that was imported by Cointracking CSV which is delete'able and trade data added by Binance API which is not delete'able?

Both are deletable. They are deletable by location. The location is binance. The location of an event is where it happened, not where it was imported from

> Unfortunately I cannot find location related to this data. I used Cointracking CSV import option. In the purging section I can find every location (from import CSV section) except for Cointracking.

That is since cointracking is not a location, but just a type of CSV data. No trade is made in cointracking itself. Location are places like a certain blockchain, an exchange, etc.

Cointracking csv importing would include events from multiple locations.

-----

Reading what you write you are probably asking for the introduction of a new feature. Basically a new attribute in every event type that denotes the source of where it was imported from and then allowing filtering, deletion and other such stuff .

Can't say off the top of my head if or when we can do it as it's probably complicated to introduce in our current system but it would be a valid feature request.

**Comment by pheu** [comment]
> Both are deletable. They are deletable by location. The location is binance. The location of an event is where it happened, not where it was imported from

Ok, I understand now.

> That is since cointracking is not a location, but just a type of CSV data. No trade is made in cointracking itself. Location are places like a certain blockchain, an exchange, etc.

> Cointracking csv importing would include events from multiple locations.

I see. I can also see that location in this case is "External".

> Reading what you write you are probably asking for the introduction of a new feature. Basically a new attribute in every event type that denotes the source of where it was imported from and then allowing filtering, deletion and other such stuff .

> Can't say off the top of my head if or when we can do it as it's probably complicated to introduce in our current system but it would be a valid feature request.

So I can see few options now:
1) "Source of import" attribute + functionality around it
2) Location reflected upon importing data via CSV
3) Being able to delete any data

Let me clarify what I mean, please evaluate their feasibility.

1) I'm not sure if "source of import" is what I need exactly, however I can imagine that it could bring more flexibility with managing data.

2) In case of Cointracking I can see that the CSV format contains "Exchange" column which could be useful to set up a proper location. It would be nice if the import Cointracking CSV tool would reflect "Exchange" column to record relevant location. So e.g. if the trade or deposit was made on Zipmex, the location would be recorded as Zipmex (or something like "External: Zipmex") in Rotki database.

If the location is saved this way does this mean the purging functionality would list this location and let it be deleted?

3) Being able to delete any data. Although it may bring some problems it could give a lot of flexibility. I can imagine that users have an option to delete any data even those imported by API, however that kind of data would always reappear upon sync with API. This is how it works in FTX (former Blockfolio), the annoying thing is that they don't have ignore option, at least I don't see.

Btw. Actually I'm trying to use Cointracking CSV import option as a workaround for importing data from two exchanges that aren't supported by Rotki. I do not really use Cointracking platform itself. I was just planning to parse programmatically tx histories from two exchanges into Cointracking CSV format and import them to Rotki (Yeah. Spend many hours on a parsing tool so I don't need to do 1h of tedious manual recording 🙃).

**Comment by LefterisJP** [comment]
>If the location is saved this way does this mean the purging functionality would list this location and let it be deleted?
 
 We would need to have it as a listed viable location. The locations currently supported are in this enum:
https://github.com/rotki/rotki/blob/89b0100b8bee25c20472bd9ea6dafba1af5f99a5/rotkehlchen/types.py#L399

Anything not related goes to "External" as a generic catch-all location.

Deleting anything "External" is not an option at the moment as this will most probably catch many different events you would not want to delete.

> n case of Cointracking I can see that the CSV format contains "Exchange" column which could be useful to set up a proper location. It would be nice if the import Cointracking CSV tool would reflect "Exchange" column to record relevant location. So e.g. if the trade or deposit was made on Zipmex, the location would be recorded as Zipmex (or something like "External: Zipmex") in Rotki database.

We already do that, but if the location is not known, as for example Zipmex we fall back to "External".

**Comment by LefterisJP** [comment]
All events imported via CSV should now appear in history events and thus be deletable on by one.
