### ISSUE TITLE
Add option to refresh icons

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4243]
## Abstract

Add the possibility when editing an asset to request the deletion of the icon and re-query it

## Motivation

Some projects have updated their token logos and if you don't manually delete the copy of the logo locally you can't query the new one

## Specification

For this a new endpoint should be added that deletes the local copy of the image for the logo and downloads a new one using the current available methods

**Comment by LefterisJP** [comment]
The backend for this is made: https://rotki.readthedocs.io/en/latest/api.html#refreshing-asset-icons
