### ISSUE TITLE
View account balances on a specific date in the past

### ISSUE THREAD

**Issue by cobordism** [rotki/rotki#4292]
## Abstract

Have the ability to display all assets held on a specific date along with their market value at that time.

## Motivation

In order to prepare taxes in my country - which has a wealth tax (instead of realised gains tax for example) - I need to list all my assets with their market value on December 31st. I have been doing this by hand for years and it is a pain in the asset management. I would love if the "History" section of Rotki would allow me to see my portfolio history - i.e. how my portfolio looked in the past. 

## Specification

Information needed:
What were the account balances of all cryptocurrencies at the specified date? 
What were the market values of those assets at that date?

**Comment by LefterisJP** [comment]
Hey @cobordism thanks for the issue. But there is already an issue for this: https://github.com/rotki/rotki/issues/2227

If you have been using rotki on that specific date our next version will also contain an export feature of the balances snapshot of any date for which balances were saved.

So I am closing this as a duplicate.
