### ISSUE TITLE
Add Accointing support

### ISSUE THREAD

**Issue by doromier** [rotki/rotki#4308]
## Abstract

Add support for Accointing.com to Rotki's 'Import Data' options.

## Motivation

By adding Accointing support many users switch to Rotki because it is free to use. 
## Specification

Accointing offers a full csv. export of the trade History.
[history.csv](https://github.com/rotki/rotki/files/8693746/history.csv)

Or is it already possible, sorry if i not did it perfect iam new to coding github

**Comment by LefterisJP** [comment]
> ## Abstract
> Add support for Accointing.com to Rotki's 'Import Data' options.
> 
> ## Motivation
> By adding Accointing support many users switch to Rotki because it is free to use.
> 
> ## Specification
> Accointing offers a full csv. export of the trade History. [history.csv](https://github.com/rotki/rotki/files/8693746/history.csv)
> 
> Or is it already possible, sorry if i not did it perfect iam new to coding github

Hello @doromier. Thanks for the issue! No there is no accointing import support for rotki yet, so making an issue to request it is indeed the right approach!

A more generic approach would be https://github.com/rotki/rotki/issues/2270
but until then a per source CSV would be needed.

**Comment by LefterisJP** [comment]
I am closing this issue since Accointing has been acquired and killed. It no longer exists.
