### ISSUE TITLE
Refactor API cache flags

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#4337]
Currently there are 3 API flags that are used to tell whether cache (database) should be updated:
- `ignore_cache`
- `only_cache`
- `reset_db_data`

But in reality they mean pretty much the same and thus could be refactored.

TODO:

- [ ] Updated backend schemas
- [ ] Update usage of these schemas on frontend

**Comment by LefterisJP** [comment]
I checked all 3 different argument names. They sound similar but they are in fact not. And semantically forcing same name would lead to confusion as in those cases the name would describe something different from what is happening.

resetting db data, does not mean ignoring cache, and returing only cached data does not just mean ignore_cache=False.
