### ISSUE TITLE
Decoded transaction events accounting settings should be configurable

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#4341]
## Abstract

Each module right now has a set of accounting settings for how decoded event should be treated at accounting. An example below for compound:

https://github.com/rotki/rotki/blob/48065dab4297ddcd24061c3a2eda789854782728/rotkehlchen/chain/ethereum/modules/compound/accountant.py#L19

These settings are hard-coded and not configurable by the user at the moment. This has to change.

## Specification

- Make a DB table where these settings reside.
- At `ModuleAccountantInterface` each submodule accountant should check the DB and if there is an entry there, return it. Otherwise return the hard coded defaults.
- Create an endpoint to query all accounting settings for decoded events
- Create an endpoint to edit settings for a decoded event
- UI interface to configure all these.

**Comment by A2be** [comment]
Would the spec you have in mind address the [issue discussed on Discord 21 March 2023](https://discord.com/channels/657906918408585217/745172610240872508/1087750015818145812): ❓ 
```Use case: want to (try to) use Rotki to communicate my blockchain account info, accnt names, etc. activity to my tax professional.  I want T.P. to receive an export of a bunch of my Rotki DB data, but not all. (so, not send the entire DB + my DB decryption key to the T.P.).```

```US tax law allows gifts of under ~$15k/yr to be excluded from ordinary "gift tax" rulz.  Say I want to encode on the Edit event page that the Event type: Spend is a gift to another person, and not a spend where I benefit.  (thus, non taxable).```

Would it allow, for example, an `Evm Transactions/Event Subtype` to be user defined? So one might spec out a subtype of gift?  (or, `gift` or `gift <$nnnnn)?  ❔ 

Would it allow a user-spec'd subset of transactions +Rotki DB info to be exported to a tax professional who is retained to deal with the Rotki user's taxes?
  this could be: ... exported in a generic format (e.g., .csv) ❔  , OR
     ... exported in a Rotki-specific format (where the tax professional might import that data file into a TP-Rotki-instance so that they might see their client's blockchain stuff, WITHOUT the client having to share a snapshot of their entire Rotki DB + their Rotki decryption password) ❔

**Comment by LefterisJP** [comment]
This would work for:

> US tax law allows gifts of under ~$15k/yr to be excluded from ordinary "gift tax" rulz.  Say one wants to encode on the Edit event page that the Event type: Spend is a gift to another person, and not a spend where I benefit.  (thus, non taxable).

For this:

> Say one wants the TaxProf to receive an export of a bunch of Rotki DB data, but not all

I think you would need to just edit the exported spreadsheet and cut out stuff you don't wan ttosend at this point.

**Comment by LefterisJP** [comment]
This has been completed :muscle:
