### ISSUE TITLE
Bitstamp support

### ISSUE THREAD

**Issue by InoMurko** [rotki/rotki#436]
## Abstract

Bitstamp support for trades import. As one of the oldest exchanges it probably has many users.

## Motivation

/

## Specification

/

**Comment by Yamarnez** [comment]
any update on this?

**Comment by dankrad** [comment]
Support for Bitstamp would be great :)

**Comment by LefterisJP** [comment]
Scheduling this as the next exchange addition.

**Comment by Yamarnez** [comment]
Great News!
Thanks for this!!!

Paul

Paul De Cannière
+32 479 557 274

Op 29 nov. 2020 om 15:37 heeft Lefteris Karapetsas <notifications@github.com> het volgende geschreven:

﻿
Scheduling this as the next exchange addition.
