### ISSUE TITLE
In pnl report consider zero as a valid price instead of missing

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4377]
## Problem Definition

![image](https://user-images.githubusercontent.com/2269732/170771520-8723cc49-a900-4ff5-8871-c2056385a45e.png)

An asset can be received before having a market price and the price can be zero.
Currently, when the price is zero it is considered a missing price.

### TODO
We should not consider a zero price as a missing price

**Comment by LefterisJP** [comment]
You tagged this as frontend @kelsos but I am not sure exactly what is the problem. I tried to reproduce by doing the following:

1. New account
2. Add income ledger action of 1 COMP 01/01/2016 (has no price so will be asked)
3. Sell 1 COMP for EUR today.

It worked fine (had a missing acquisition hiccup I have to investigate) as far as accepting a zero missing price though. Here is a video.


https://user-images.githubusercontent.com/1658405/170841998-675f74d7-2187-41d2-bf0b-44e16ced68e7.mp4

**Comment by kelsos** [comment]
@LefterisJP as we discussed only the Mooncat ERC20 seems to still be in this situation. It has been resolved for the other assets with the changes in bugfixes

**Comment by LefterisJP** [comment]
> @LefterisJP as we discussed only the Mooncat ERC20 seems to still be in this situation. It has been resolved for the other assets with the changes in bugfixes

Yes thanks for adding a reminder here. I got it in my TODOs to debug it and figure out why the mooncat thing is special. Oncew figured out I will fix and close this issue.

I will also unlabel frontend as it's not a frontend issue at the moment.

**Comment by kelsos** [comment]
I did one for 2022 but it should not make a difference right? was anything else merged to bugfixes that would affect that since I checked?

**Comment by LefterisJP** [comment]
> I did one for 2022 but it should not make a difference right? was anything else merged to bugfixes that would affect that since I checked?

no it should not. I tried to check and I get the same, no problems once I put $0 price there.

**Comment by kelsos** [comment]
I just recreated everything (virtual env etc) and retried on latest bugfixes on a new account. 

It seems fixed so I am gonna close the issue.
