### ISSUE TITLE
Bitfinex support

### ISSUE THREAD

**Issue by sableweasel** [rotki/rotki#438]
Bitfinex ist a quite old and big exchange.
Support in Rotkehlchen could come in handy for a bunch of users.

**Comment by Michael-A-Heuer** [comment]
I would be willing to fund this on gitcoin grants.

**Comment by LefterisJP** [comment]
Hey @Michael-A-Heuer do you mean a bounty? Or donation? For us any donation helps, especially now. In the coming release (next week) bitstamp support is coming. Bitfinex can be scheduled as the next exchange to be supported.

**Comment by Michael-A-Heuer** [comment]
Hey @LefterisJP. I thought about a bounty but a matched donation makes obviously more sense. I have recently become a premium Rotki user and donated (a smaller amount) in the current gitcoin round already. 
I just saw that services like Cryptotax supporting Bitfinex charge 200€ per tax-year and I think you could use this money more.
I don't know how much work it will be but I would be willing to donate +50€ on gitcoin if this helps. Maybe others could join in too @sableweasel.

**Comment by philhug** [comment]
@LefterisJP bitfinex support would be great, I'm also premium user and am also willing to donate another +50€.
Keep up the great work

**Comment by LefterisJP** [comment]
Hey @philhug. Thanks that would be great. We are gonna try to fit it in the release after the next (v1.11.0).

May need you guys to test stuff when it's being developed as we don't have anyone with a bitfinex account in the team

**Comment by philhug** [comment]
Sure, ping me when you pushed some code. I can test.
