### ISSUE TITLE
Filtering on the price caches does not work

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#4384]
## Problem Definition

If you go to settings -> Data Security and scroll to the bottom you will see the cryptocompare price caches.

There is 2 problems there.

1. There is an always loading progress bar which makes no sense as nothing is actually loading.
2. The filtering functionality does not work. I would expect to be able to filter by symbol or name of the assets but I can't
![2022-05-28_21-43](https://user-images.githubusercontent.com/1658405/170840720-f6e6b421-a830-4bbf-a869-a986ae2161dc.png)
![2022-05-28_21-44](https://user-images.githubusercontent.com/1658405/170840728-a8ba1434-8708-476d-be62-92ad996a85c1.png)

## Task

Figure out why and fix it

**Comment by LefterisJP** [comment]
Also related. The notifications there are using the _ceth_XXX identifier instead of a proper name/symbol

![2022-05-28_21-48](https://user-images.githubusercontent.com/1658405/170840807-ba78c770-2531-48ca-b407-c8c25ca27603.png)

![2022-05-28_21-49](https://user-images.githubusercontent.com/1658405/170840813-be3ae7a2-cbda-44cd-b8bb-f3276f27823d.png)

**Comment by LefterisJP** [comment]
Will leave this open until the problem shown in the screenshots from here is also addressed: https://github.com/rotki/rotki/issues/4384#issuecomment-1140321107

**Comment by kelsos** [comment]
@LefterisJP we can close now right? since this should have been fixed in the macos pr

**Comment by LefterisJP** [comment]
yes we can!
![yes-we-can-yaby2n](https://user-images.githubusercontent.com/1658405/171010822-8968c384-63f9-4b7a-834f-fb60235a327f.jpg)
