### ISSUE TITLE
Asset type selection is disabled for new asset addition

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4398]
## Problem Definition

It is not possible to add assets that are not ethereum tokens because the asset type selection is disabled.

![image](https://user-images.githubusercontent.com/2269732/171134426-cf17ec4d-49cf-4623-9d1a-7a26ee9d4999.png)

**Comment by LefterisJP** [comment]
Should be fixed by: https://github.com/rotki/rotki/pull/4418
