### ISSUE TITLE
Add accounting option for calculating profits in LIFO order

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#44]
At the moment the profit calculation is made in a hard-coded FIFO order as that's how it's required by German taxes. Make this customizable and add an accounting option to switch between different modes.

- [ ] In `accounting.py` add an option for LIFO profit calculation
- [ ] Make `accounting.py` able to switch between those options
- [ ] In the frontend, in the accounting settings page offer a dropdown menu to customize this choice.

**Comment by msagansk** [comment]
It would be useful to also be able to switch the Adjusted Cost Basis (ACB) method of tax accounting, which is used in Canada.

**Comment by LefterisJP** [comment]
> It would be useful to also be able to switch the Adjusted Cost Basis (ACB) method of tax accounting, which is used in Canada.

Hey @msagansk can you make a different issue for that with some links to the description of the methodology?
