### ISSUE TITLE
yay rotki update error

### ISSUE THREAD

**Issue by hitchhooker** [rotki/rotki#4405]
yay rotki ->

```
==> Making package: rotki-bin 1.24.0-1 (2022-05-31T19:08:51 -05)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found rotki-1.24.0.tar.xz
  -> Downloading rotki.png...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  191k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/rotki/rotki/raw/develop/frontend/app/src/assets/images/rotki_1024x1024.png
    Aborting...
 -> error making: rotki-bin


```

**Comment by LefterisJP** [comment]
Yes whoever is managing the rotki AUR package needs to update. You need to report it via the AUR -> https://aur.archlinux.org/packages/rotki-bin

**Comment by LefterisJP** [comment]
Develop should now be fixed.

Please ask the AUR package maintainer to not use anything from develop for a package intended to be used by the end users.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rotki-bin#n17

any references to develop should be replaced by the tag of the release the package is built for.

**Comment by TripleSpeeder** [comment]
This is now fixed in the AUR package.

**Comment by LefterisJP** [comment]
Thank you @TripleSpeeder really appreciate it! Btw @hitchhooker, @TripleSpeeder is the AUR package maintainer and also is in our discord: https://discord.com/invite/aGCxHG7
