### ISSUE TITLE
ETH transactions from Maple Finance not linking, creating assets with no acquisition

### ISSUE THREAD

**Issue by socal434** [rotki/rotki#4412]
## Problem Definition

When running a profit and loss report MPL LP tokens that I used to own are being reported as no acquisition found even though I can find the receive and send transactions in the tab for ETH transactions. For some reason Rotki isn't connecting those two and realizing the receive is when I acquired them. 

## Logs

[rotkehlchen.log](https://github.com/rotki/rotki/files/8815565/rotkehlchen.log)

![rec MPL_LP](https://user-images.githubusercontent.com/29628243/171415100-ce58ee1c-421b-4054-95bf-0053f3dcb453.PNG)
![send MPL_LP](https://user-images.githubusercontent.com/29628243/171415097-f0b0f7e4-11b1-4355-b55b-2aa27bfc8a90.PNG)
![MPL_LP issue](https://user-images.githubusercontent.com/29628243/171415099-d7ee6574-8674-48c5-9e4c-649e3389eed8.PNG)

### System Description

Operating system: Windows 10
Rotki version: 1.24.0

**Comment by LefterisJP** [comment]
Hey @socal434 can you edit your post to have link to the transactions in question and change the title to include the protocol in question?

**Comment by socal434** [comment]
> 

The transactions were from Maple Finance if that is what you mean by the protocol. I updated the title to show that.

**Comment by yabirgb** [comment]
After debugging this error with the user we found that the PnL report was showing the missing acquisition error because the asset didn't had a price at the acquisition time. Maybe this is something that we can improve for the users? @kelsos @LefterisJP

**Comment by LefterisJP** [comment]
If the asset does not have a price at the asset acquisition time you are asked to input a price at the actionable items stage.

**Comment by yabirgb** [comment]
Closing this issue since it was related to the price missing and no action is needed here
