### ISSUE TITLE
Pure ETH transactions not shown when account filter applied

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#4415]
## Problem Definition

Under ETH transactions the pure ETH transactions, or gas events are not shown when an account filter is applied. Only ERC20 transactions are visible. Without the filter the ETH transactions are visible.

### System Description

Operating system: Win10
Rotki version: 1.24.0

**Comment by xtc0r** [comment]
I did some trils with @prettyirrelevant. 

He couldn't replicate the issue when adding my example address. So I created a new account and added the address. The issue was not visivle there. Afterwards I jumped back to an account which had the issue. I remoced the ETH address and added it again. Afterwards all transaction were shown correctly when the filter was applied.

**Comment by LefterisJP** [comment]
I see. So perhaps the transactions were either (1) not pulled properly or (2) not decoded yet. Should we close the issue then?

**Comment by xtc0r** [comment]
> I see. So perhaps the transactions were either (1) not pulled properly or (2) not decoded yet. Should we close the issue then?

If you remember our chat from yesterday. When I removed the filter I could see the transactions. So I think neither (1) or (2) is valid in this case.

**Comment by LefterisJP** [comment]
Some kind of caching made the transaction not properly filterable. If it works on a fresh account it's very hard for us to further debug and reproduce.

**Comment by LefterisJP** [comment]
Closing as not reproducible for now. If we manage to reproduce it in a clean account or if you trust us with your DB and password to see it happen live and debug it then we can investigate further.
