### ISSUE TITLE
Prevent unintended information leaks by using non-gaussian based privacy mode

### ISSUE THREAD

**Issue by luclu** [rotki/rotki#4417]
## Problem 
The current iteraction of the privacy modes aims to hide price information from visual detection but it falls short in two ways:
1. the blured values do not hide the length of the value - thus the amount of numbers is easily guessed
2. the blured values are easily interfered to reveal the hidden value by trained persons or software due to the usage of gaussian blur

## Possible Solution
Perhaps a value-hiding privacy mode can be implemented that prevents information leaks by uniformingly replacing all vulnurable values by certain characters like the common asterisk ("****.**" or "****", etc.).

(Software to achieve 2. is for example http://smartdeblur.net/gallery.html
Some more great examples can be found here: https://www.fips.fi/HDCresults.php#anchor1)
<img width="834" alt="Bildschirmfoto 2022-06-02 um 01 32 02" src="https://user-images.githubusercontent.com/10135872/171523400-e35a966b-b52c-4524-9909-2a682260bb4a.png">

**Comment by LefterisJP** [comment]
Hey @luclu thanks for the issue.

This is intended to be used mostly by someone who wants to temporarily hide it from someone looking over their shoulder in the same room. So the things you point out are less important in such a case.

If we can improve either the length of the blurring or the algorithm itself sure we will. Have you tried to deconstruct the numbers in rotki's blurring btw? I am not sure if we use a destructive or non destructive blurring algo.

PRs are also welcome

**Comment by kelsos** [comment]
@LefterisJP as you suggested in the standup we can combine that with the scrambling so privacy also auto-scrambles values

@lukicenturi can you pick it up? Do you think we can put it in bugfixes?
