### ISSUE TITLE
Balance of accounts shows incorrect amounts

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4422]
## Problem Definition

![image](https://user-images.githubusercontent.com/5068010/171605270-6e2eadf6-a164-4b74-9328-67a5831dec12.png)

## Logs

@kelsos said in discord that the reason is the ignored assets in this getter https://github.com/rotki/rotki/blob/d512cd408d5c83df54647cae3d820a2926055401/frontend/app/src/store/balances/getters.ts#L92

### System Description

Operating system: Linux
Rotki version: 1.24.0

**Comment by kelsos** [comment]
@yabirgb did you check which assets are there? Can you confirm that it was indeed an ignored asset that was causing this?

**Comment by yabirgb** [comment]
> @yabirgb did you check which assets are there? Can you confirm that it was indeed an ignored asset that was causing this?

Yes, it was the ignored asset 
![image](https://user-images.githubusercontent.com/5068010/171610674-b9b5335e-8f96-42a8-992e-a3d323cda1d0.png)

**Comment by LefterisJP** [comment]
Should be fixed by #4430
