### ISSUE TITLE
Swyftx

### ISSUE THREAD

**Issue by wpl123** [rotki/rotki#4450]
## Abstract

I'm looking for a Swyftx exchange integration

## Motivation

According to some, (https://bestcryptoexchangeaustralia.com.au/) Swyftx is the best Australian based Crypto Exchange and I think it would be useful for Australian Rotki users

## Specification

The Swyftx api docs are here --> https://swyftx.docs.apiary.io/

There is a tax report endpoint and a transaction history endpoint that may be useful

**Comment by Zorlin** [comment]
Strong +1 :)

**Comment by solyxius** [comment]
Another +1

**Comment by damian-w** [comment]
Dupe of #3211

**Comment by LefterisJP** [comment]
> Dupe of #3211

Oh you are correct. Then closing this one as duplicate. Thanks for noticing
