### ISSUE TITLE
Make a proper bumpversion.cfg entry for package-lock.json

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#447]
## Problem Definition

At the moment with a bumpversion package-lock.json gets all matching versions of packages updated even if it's not rotkehlchen. That's naturaly bad.

We need to fix this with a proper regexp entry for bumpversion.cfg and package-lock.json.

Docs are here: https://github.com/peritus/bumpversion

**Comment by kelsos** [comment]
@LefterisJP  I am not putting it in a milestone but I will create a simple batch script tomorrow to delegate to bump2version? or bumpversion for the python part and to npm version for the javascript part.

**Comment by LefterisJP** [comment]
> @LefterisJP I am not putting it in a milestone but I will create a simple batch script tomorrow to delegate to bump2version? or bumpversion for the python part and to npm version for the javascript part.

Sure.

My current approach is like this:

1. `bump2version --config-file .bumpversion.cfg [major|minor|patch]`
2. Manually edit package_lock.json
