### ISSUE TITLE
Chrome blocks rotki dmg download

### ISSUE THREAD

**Issue by mikemcdonald** [rotki/rotki#4478]
## Problem Definition

Chrome users that utilize [Advanced Protection](https://landing.google.com/advancedprotection/) (which I'm assuming is a lot in the crypto space) cannot download the dmg from rotki.com. 

![Screen Shot 2022-06-14 at 9 24 38 AM](https://user-images.githubusercontent.com/5049108/173588546-20c79481-4beb-402e-ba8d-80dc42755033.png)

https://support.google.com/webmasters/answer/9044101 generating a report may show why Chrome is flagging it as malware but it can only be done by the domain owner

### System Description

Operating system: MacOS Monterey 12.4
Rotki version:

**Comment by LefterisJP** [comment]
Thank you @mikemcdonald. This is completely new, since the website has had no changes in months and no other ser has reported it so I assume it's on a specific chrome version. Can you give us details on the version of chrome you use?

Also you can ignore this warning I suppose?

**Comment by mikemcdonald** [comment]
Yes I was able to install fine, just thought I'd give a heads up since this means Google is flagging it as malware (and may affect search results and other things)

Chrome Version 102.0.5005.115 - and I'm assuming it will only be blocked when the logged in user has the Advanced Protection feature activated

**Comment by kelsos** [comment]
Hey, @mikemcdonald checking the google search console I found no security issues on the site.

From a quick search, I found this https://github.com/keeweb/keeweb/issues/1452

It seems pretty similar to our case since our downloads are also hosted on GitHub and the website pulls the links.

Do you get the same security warning if you try to download directly through GitHub?

**Comment by mikemcdonald** [comment]
Yea, looks like that may be it. Strange that google wouldn't have more granularity for the github domain. But anyways, feel free to close - this seems to be a pretty isolated scenario

**Comment by LefterisJP** [comment]
> Yea, looks like that may be it. Strange that google wouldn't have more granularity for the github domain. But anyways, feel free to close - this seems to be a pretty isolated scenario

Thank you for reporting it Mike and for being a continuous rotki user. If you are not there join our discord too, to chat with us and other users.: https://discord.com/invite/aGCxHG7

(keep in mind you need to have DMs open since it has a captcha verification challenge)
