### ISSUE TITLE
Customizable priorities of address names' sources

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#4487]
## Abstract

In release 1.25.0 we introduce an address book and a search for names of an ethereum address in various sources (6 in total):

1. private addressbook
2. blockchain account labels
3. global addressbook
4. ethereum tokens
5. hardcoded mappings
6. ENS names

In frontend we can show only one name per address and the problem is that the current order (which you see above) is hard-coded.

## Motivation

Users should be able to set any order that they want.

## Specification

- [ ] Create a database setting for this
- [ ] Use order from settings instead of the hard-coded one
- [ ] Allow to customize order on the fronted side

**Comment by tomvodi** [comment]
hi, I'd like to work on this as it seems to be a perfect fit getting used to the codebase

**Comment by nebolax** [comment]
@tomvodi yeah, sure, go ahead

**Comment by vikas21st** [comment]
very nice , I can contribute in git grant.
