### ISSUE TITLE
Import Data > Nexo

### ISSUE THREAD

**Issue by B0ll3D3rF1ck3r** [rotki/rotki#4502]
## Import Data > Nexo

Error Message in Red > Invalid CSV format, missing required field: 'Currency'

### System Description

Operating system: MacOS 12.3.1
Rotki version: 1.24.1

**Comment by yabirgb** [comment]
Hello @B0ll3D3rF1ck3r This would mean that either the format has changed in the exported CSV or something is bad with the file. We would need that you post the head of the file + some rows (to keep info private you can modify numbers but keeping the real) or you can also sent it to the dev team in discord. Here is the invite https://discord.gg/aGCxHG7 and you can see us with special labels and colors in the top of the persons at the server

**Comment by osouthgate** [comment]
> Transaction,Type,Input Currency,Input Amount,Output Currency,Output Amount,USD Equivalent,Details,Outstanding Loan,Date / Time NXT1isX0Refua,Interest,ETH,0.00178799,ETH,0.00178799,$1.98,"approved / ETH Interest Earned",$0.00,2022-07-14 07:00:07 NXTNru1bVwXqN,ExchangeToWithdraw,GBPX,-1000.00000000,GBP,1000.00000000,$1936.905,"rejected / GBPX to GBP",$0.00,2022-07-13 09:41:49 NXT0holq0qpzw,LockingTermDeposit,MATIC,-3055.00000000,MATIC,3055.00000000,$4641.17433,"approved / Transfer from Savings Wallet to Term Wallet",$0.00,2022-03-22 15:58:56 NXTGjeCTHAXxg,Deposit,MATIC,3050.00000000,MATIC,3050.00000000,$4639.42515,"approved / GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",$0.00,2022-03-22 15:52:33 NXT9aSBjiAOjq,Deposit,MATIC,5.00000000,MATIC,5.00000000,$7.6345,"approved / GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",$0.00,2022-03-22 15:45:25

Just had the same issue and saw the issue was reported but no data, so here is some

**Comment by yabirgb** [comment]
> Transaction,Type,Input Currency,Input Amount,Output Currency,Output Amount,USD Equivalent,Details,Outstanding Loan,Date / Time NXT1isX0Refua,Interest,ETH,0.00178799,ETH,0.00178799,$1.98,"approved / ETH Interest Earned",$0.00,2022-07-14 07:00:07 NXTNru1bVwXqN,ExchangeToWithdraw,GBPX,-1000.00000000,GBP,1000.00000000,$1936.905,"rejected / GBPX to GBP",$0.00,2022-07-13 09:41:49 NXT0holq0qpzw,LockingTermDeposit,MATIC,-3055.00000000,MATIC,3055.00000000,$4641.17433,"approved / Transfer from Savings Wallet to Term Wallet",$0.00,2022-03-22 15:58:56 NXTGjeCTHAXxg,Deposit,MATIC,3050.00000000,MATIC,3050.00000000,$4639.42515,"approved / GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",$0.00,2022-03-22 15:52:33 NXT9aSBjiAOjq,Deposit,MATIC,5.00000000,MATIC,5.00000000,$7.6345,"approved / GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",$0.00,2022-03-22 15:45:25

Hello! Thank you very much for the example. Do you know if there are multiple CSVs files that can be exported from nexo? Or is this the only one?

**Comment by osouthgate** [comment]
A single csv file 

Note: I only have 372 transaction on nexo, so no idea if they split and or at which points.

**Comment by LefterisJP** [comment]
So I guess at this point we have to assume Nexo has completely changed their csv format and we need to adjust?

**Comment by B0ll3D3rF1ck3r** [comment]
Yes.

Daniel CIMA

**Comment by LefterisJP** [comment]
Fixed by #4595

**Comment by yabirgb** [comment]
Hello! @B0ll3D3rF1ck3r 
thanks for coming back to the issue. We have changed the format and should be available already in 1.25.3 if I'm correct. About the attached file seems that it didn't get attached in github where I'm reading your messages. If you could drop it in the github UI it would be great. Thanks!
