### ISSUE TITLE
Toolbar icons overflow in mobile layout 

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4599]
## Problem Definition

During EthCC we met a user who is using rotki from mobile via VPN to his dappnode.
The user reported that the toolbar icons overflow. I have also confirmed it.

We must make sure we condense or hide some of the icons when in mobile layout due to the lack of real estate. We should keep the important actions visible and a menu that allows you to access the rest.

The optimal icon number should be 3 to 4 excluding the side menu hamburger icon. This doesn't need to affect the normal app layout.

**Comment by LefterisJP** [comment]
Should be fixed by #4614
