### ISSUE TITLE
Support CoinbasePro

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#46]
Support CoinbasePro

**Comment by spaceblankey** [comment]
As noted in the other issue please add Coinbanse Pro (formerly GDAX).

**Comment by LefterisJP** [comment]
This has also been prioritized thanks to a premium subscriber ... and has been long overdue.
Even though it's scheduled for v1.2.0 if it's ready before v1.1.0 is out then it will be part of that release.

Work has started.

**Comment by LefterisJP** [comment]
The created
![2020-01-11-105141_671x365_scrot](https://user-images.githubusercontent.com/1658405/72202494-6c7f2c80-3460-11ea-9688-a338ece05fba.png)
 API key needs only the "View" permission

**Comment by LefterisJP** [comment]
Unfortunately it seems API key may also need the "Trade" permission according to the [documentation](https://docs.pro.coinbase.com/#api-key-permissions). Will have to experiment to see.

**Comment by LefterisJP** [comment]
> Unfortunately it seems API key may also need the "Trade" permission according to the documentation. Will have to experiment to see.

That was wrong. You only need "View" permission
