### ISSUE TITLE
Show what ethereum nodes are connected

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4602]
## Abstract

In 1.25 we removed the "connected to own node" icon from the top navbar. Multiple users requested that this should be re-added but since now we have the feature of allowing multiples node the approach requires to list all of them. For that

1. Create a new endpoint that returns the nodes that are currently connected
2. Remove the connected to node key from the periodic resource
3. In the frontend show this information next to the list of nodes or somehow so users can check if they are connected or not. Maybe in addition would be nice to have something like before?

**Comment by LefterisJP** [comment]
> Maybe in addition would be nice to have something like before?

No. Just show it in the settings. In a multichain world does not make sense to have a general connected/not connected icon on the top. Since the question is then connected to whom? And since we have multiple nodes per chain this becomes even more complicated.

**Comment by LefterisJP** [comment]
@nebolax don's write `close ISSUENUM` in a PR if there is still frontend work left to do.
