### ISSUE TITLE
Decimal comma dropped while editing manual balances

### ISSUE THREAD

**Issue by ProkhorZ** [rotki/rotki#4606]
*I'm not asking for support. This is one of the results of a usability test.*

## Problem Definition

Under Manual Balances, my XMR balance was 12.34 (represented as 12,34 according to my settings) but when I edit it, it's shown as 1234 in the form. When I edit the location, the decimal is removed again, and the amount increases by orders of magnitude if I don't re-enter the decimal comma. That's not what I'm paying attention to when I'm editing the location. The same happened for 8.642 Waves, represented as 8,642 and changed to 8642 in the form. (Of course these are not the real amounts.)

This error disappears when I set the decimal separator to a period. It doesn't occur either when editing a custom price for an NFT under Non Fungible Balances.

## Logs

I turned on debugging, but I can't find anything relating to this action in rotkelchen.log. Is there a front-end log?

### System Description

Operating system: Windows 10 Pro version 21H1 & Windows 10 Home 21H2 (locale is NL, decimal commas are the default)
Rotki version: 1.25.0

**Comment by LefterisJP** [comment]
Should be fixed by #4617
