### ISSUE TITLE
UI: Asset icon issues and inconsistant

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#465]
## Problem Definition

Somehow, the DAI icon does not make it :)
![image](https://user-images.githubusercontent.com/738724/62917883-4284e980-bd9e-11e9-94be-57a0ac8ae4ee.png)

You can also notice inconsistency in the display of the assets and balances. `ETH` is displayed on the right while other assets' names are shown below the icon.

**Comment by LefterisJP** [comment]
There is two issues here. I guess one is the display of asset name + centering which I guess is a CSS issue right @kelsos ?

The other is probably a need to update the crypto icons package.

**Comment by kelsos** [comment]
@LefterisJP Probably a css issue yes, and DAI should be available in the latest version of the crypto icons package. I am using it in the rewrite and the DAI icon is there.

**Comment by LefterisJP** [comment]
@kelsos With the different way the owned tokens are displayed to the user in v1.1.0 this issue is essentially handled, right?

**Comment by kelsos** [comment]
Yes since we changed the way we handle the owned tokens this is not a valid issue anymore.

**Comment by LefterisJP** [comment]
Well I would say it is a valid issue but fixed :wink:
