### ISSUE TITLE
Support Coinbase Advanced Trade

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#4663]
## Abstract

Current Coinbase implementation in Rotki does not fetch trades done in the new "Advanced Trade" tool.

## Motivation

Coinbase phases out "Coinbase Pro" and will replace it wilth "Advanced Trade". While there is no timeline for the migration, Advanced Trade is already live and possibly in use by Rotki users.

## Specification

For this to be implemented, we probably need to wait to an API spec from Coinbase. See [this thread](https://twitter.com/LefterisJP/status/1555983232239390728).

**Comment by LefterisJP** [comment]
Thanks for bringing this to our attention @coinyon. We will wait until coinbase pro gives more information on advance trading and creates an api for it. We also need info on how to query CBPro history once it's sunset and becomes part of "advance trading".

The blog post by coinbase is here: https://blog.coinbase.com/hello-advanced-trade-goodbye-coinbase-pro-5b0715b03ef0
Ccxt, the most well know exchange integration library, also has the same open questions so it's something I guess we all are waiting on. https://github.com/ccxt/ccxt/issues/14571

**Comment by LefterisJP** [comment]
Pushing this to 1.27.0

Got this email. I don't like this email.
![2022-10-28_18-02](https://user-images.githubusercontent.com/1658405/198682178-409c66c2-c98a-40be-96b0-0afb81407597.png)

**Comment by pottertech** [comment]
[This](https://www.nerdwallet.com/article/investing/coinbase-vs-coinbase-pro) article indicates that Coinbase Pro is shutting down on November 9, 2022. If you have funds on Coinbase Pro will be moved into the new "Advanced Trade" automatically.

The issue still remains that Coinbase has not provided any indication of when an API would be made available for us to integrate into ccxt.

**Comment by LefterisJP** [comment]
related post showing that nothing is yet clear: https://twitter.com/LefterisJP/status/1588237926634332161

**Comment by LefterisJP** [comment]
New update: https://forums.coinbasecloud.dev/t/about-the-advanced-trade-api-category/1743

**Comment by LefterisJP** [comment]
Api docs: https://docs.cloud.coinbase.com/advanced-trade-api/docs/welcome

**Comment by coinyon** [comment]
I think you do not need to use the "Advanced Trade API". Advanced trade fills do appear in the normal "transactions" endpoint

**Comment by LefterisJP** [comment]
All right then we close this :)
