### ISSUE TITLE
Retrieving nfts fails, even with an OS API key provided

### ISSUE THREAD

**Issue by floAr** [rotki/rotki#4688]
## Problem Definition

Retrieving nfts fails, even with an OS API key provided

`An error occurred while querying the NFT balances: Reached opensea backoff limit after we incrementally backed off for https://api.opensea.io/api/v1/collection/soulz-monogatari/stats?name=soulz-monogatari`

## Logs
This seems to be the relevant section in the logs:

> [12/08/2022 14:27:04 Mitteleuropäische Sommerzeit] DEBUG rotkehlchen.api.server Greenlet-4: start rotki api GET /api/1/tasks/14 view_args={'task_id': 14}, query_string=b''
> [12/08/2022 14:27:04 Mitteleuropäische Sommerzeit] DEBUG rotkehlchen.api.server Greenlet-4: end rotki api GET /api/1/tasks/14 view_args={'task_id': 14}, query_string=b'', status_code=200, result={'result': {'status': 'completed', 'outcome': {'result': None, 'message': 'Reached opensea backoff limit after we incrementally backed off for https://api.opensea.io/api/v1/collection/colorpencil-club-x-bayc-1/stats?name=colorpencil-club-x-bayc-1'}, 'status_code': 502}, 'message': ''}
> [12/08/2022 14:27:04 Mitteleuropäische Sommerzeit] INFO geventwebsocket.handler 127.0.0.1 - - [2022-08-12 14:27:04] "GET /api/1/tasks/14 HTTP/1.1" 200 474 0.003501

After rerunning a few times, the point where it fails changes (so not always the same collection / nft)

### System Description

Operating system: Windows
Rotki version: 1.25.1

**Comment by LefterisJP** [comment]
Yeah that basicaly tells you that opensea is rate limiting you. You probably have too many nfts and the key is not good enough for it.

Generaly opensea and their API is terrible and they said they want to try and fix it ... half a year ago. Nothing yet.

We will try to move away from using their API (but not there yet).

**Comment by floAr** [comment]
Understood, that is indeed unfortunate. Depending on where the work / head at this is: I have heard good things about https://reservoir.tools/ and using their API was pretty hassle free.

**Comment by LefterisJP** [comment]
Closing this as there is nothing we can take action on
