### ISSUE TITLE
Parachain support 

### ISSUE THREAD

**Issue by alexeiZamyatin** [rotki/rotki#4695]
## Abstract

As a user, I would like to be able to import my account balances on different substrate chains...
... so that I can use rotki for my accounting as a Polkadot ecosystem user. 

Interlay, one of the Polkadot parachains, would definitely be interested in adding support. With a high probability, other parachains will also be interested. The two options to approach this, imho, are:
- Rotki adds support and maintains the endpoints (e.g. funded via grants by individual parachains)
- Parachains can add support themselves via PRs. Would need to be decided who runs support. Perhaps parachain teams could make a PR to accelerate development, rotki reviews and, once merged, is offered a grant to run support?

This "Feature Request" can hopefully serve to start conversations around this. If parachain support has already been considered/discussed publicly, then I apologize if I missed it. 

## Motivation
Polkadot is a multi-chain ecosystem, with cross-parachain interaction being one of the main selling points. Today, there is no easy way to track and record transactions on parachains for accounting purposes. 

By supporting parachains, rotki would help a lot of users, and in turn, could increase its user base - considering the lack of similar tooling in the Polkadot ecosystem. There is also the opportunity of receiving grant funding to cover support and development costs. 

## Specification
Rotki already supports Polkadot, which covers a lot of the core implementation steps to read data from parachains. 

The main difficulty will be in supporting different token standards across parachains. While parachain teams try to use the same format, this is not yet properly standardized. 

Polkadot uses the "balances" module, whereas most parachains are switching to orml-tokens (https://github.com/open-web3-stack/open-runtime-module-library/tree/master/tokens) for multi-asset support.

**Comment by LefterisJP** [comment]
Hello Alexey. Thanks a lot for your issue! I am not that familiar with the dotsama ecosystem so this may be wrong, but isn't this essentially the same as: https://github.com/rotki/rotki/issues/3703  ?

**Comment by LefterisJP** [comment]
Closing as duplicated of #3703
