### ISSUE TITLE
Replace caching of all supported assets with subset access from the backend

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4701]
## Abstract

Currently, the frontend keeps the state of the app in the frontend state.

https://github.com/rotki/rotki/blob/1fb9c623457461ca16aa46c01e47ce2b399b3978/frontend/app/src/store/assets/index.ts#L179

This feeds the autocompletion, asset manager, and all the mappings of the identifier to symbol/name.

We need to change this approach as it has a few problems
- All the supported assets are stored in memory
- Sometimes the cache is outdated.

## Motivation

Reduce the memory footprint and improve the overall frontend performance.

## Specification

- For asset manager we need pagination and filtering if not already supported
- For the autocomplete we need filtering (with sorting based on the name/symbol) and figure out if the autocomplete can use pagination.
- Add the ability to get an asset information using the identifier
- Figure a way to get the assets (or identifiers matching a symbol)

**Comment by kelsos** [comment]
@LefterisJP @yabirgb 

- For the pagination/sorting/filtering we also need to unify the endpoint for assets like we discussed on the standup

**Comment by prettyirrelevant** [comment]
The backend should provide the following endpoints as agreed on a call:

1. `/assets`: Accepts a filter query as JSON post data. Filterable fields are `name`, `symbol`, `asset_type`, etc. Returns a list of assets that match the filter query.  Ignored assets are removed from the data returned. The assets returned are sorted using either the `name` or `symbol`.

2. `/assets/mappings`: Accepts a list of asset identifiers as JSON post data. Returns a list of asset information that matches the identifiers.

3. `/assets/search`: Accepts a filter query(namely a substring) that'll be used to search the name & symbol columns of the assets table. Returns a list of assets(identifier, name & symbol) that match the substring. The list returned is sorted by the name and symbol.

**Comment by kelsos** [comment]
Closed by #4873
