### ISSUE TITLE
Uphold File Import Not possible

### ISSUE THREAD

**Issue by MrMimiMe** [rotki/rotki#4710]
## Problem Definition

Importing Uphold Trade History returns: 
{"source": ["Failed to deserialize DataImportSource value uphold"]}

Either using standard date formats or custom: %a %b %d %Y %H:%M:%S %z

## Logs

[18/08/2022 19:07:05 Mitteleuropäische Sommerzeit] DEBUG rotkehlchen.api.server Greenlet-14: start rotki api PUT /api/1/import view_args={}, query_string=b''
[18/08/2022 19:07:05 Mitteleuropäische Sommerzeit] DEBUG rotkehlchen.api.server Greenlet-14: end rotki api PUT /api/1/import view_args={}, query_string=b'', status_code=400, result={'message': '{"source": ["Failed to deserialize DataImportSource value uphold"]}', 'result': None}

### System Description

Operating system: win10
Rotki version: 1.25.2

**Comment by LefterisJP** [comment]
Hey thanks for reporting an issue. 

CSV imports often break since all these services willy nilly change their format. We would need an example file of how their format looks like right now. Please provide the file you are trying to import, only a few lines and you can ofc change numbers for privacy. All we need is to know the new format.

**Comment by MrMimiMe** [comment]
Uphold Late August CSV Export:


> Date,Destination,Destination Amount,Destination Currency,Fee Amount,Fee Currency,Id,Origin,Origin Amount,Origin Currency,Status,Type
> Wed Aug 10 2022 13:39:16 GMT+0000,uphold,0,BAT,,,some-id,uphold,0,BAT,completed,in
> Tue Jul 01 2021 07:36:06 GMT+0000,uphold,0,BAT,,,some-id,uphold,0,BAT,completed,in
> Fri Sep 29 2021 18:27:58 GMT+0000,xrp-ledger,0,XRP,0,XRP,some-id,uphold,0,XRP,completed,out
> Sun Feb 21 2021 01:31:16 GMT+0000,ethereum,0,BAT,0,BAT,some-id,uphold,0,BAT,completed,out

**Comment by LefterisJP** [comment]
Should be addressed by https://github.com/rotki/rotki/pull/4720
