### ISSUE TITLE
Support initial set of Proof of Stake cryptocurrencies as value add service to validators 

### ISSUE THREAD

**Issue by jrmoreau** [rotki/rotki#473]
## Abstract

Validators/Bakers (and delegators as well) have accounting challenges keeping track of what is staked, what is coming in for rewards, what gets re-delegated/staked/baked etc. rotkehlchen would provide a major value to this set of businesses by offering to track account balances on chains such as Cosmos, Tezos (and other popular Proof of Stake chains as they emerge). 

## Motivation

Speaking with lots of different professional validators/bakers on Cosmos/Tezos, tracking what comes in and goes out is difficult and poses a lot of mental/emotional overhead come tax time. This tool would be so useful to us/them.

## Specification

I think Cosmos and Tezos would be the best networks to start with but could imagine many others being good candidates as well.

**Comment by LefterisJP** [comment]
Thank you @jrmoreau for remember to open this issue after our twitter chat. I will consider this. Will also ask around to see how many people would be interested in such a feature.

**Comment by LefterisJP** [comment]
Kraken has added Tezos staking from their website. This seems like a low hanging fruit for supporting one form of staking as early as before end of this year, so may be done soon: https://github.com/rotki/rotki/issues/569

For the rest and for canonical-onchain staking monitoring it will be part of the App and scheduled early next year after 1.1.0.

**Comment by Phistr90** [comment]
Would also love to see canonical-onchain staking monitoring. Will be a huge deal for eth2 as well. Although I assume that the tooling and other monitoring services for eth2 will be better out there than for existing staking chains.

**Comment by LefterisJP** [comment]
Naturally this is something we want to support eventually. We may manage to do something with polkadot staking as we are in talks with them.

Generally at this point prioritizing is based on our limited resources and on potential collaborations/grants we may get for an integration.

But I hear you. I also have tried staking in multiple chains and also will try ETH2 and would love for Rotki to just handle all that eventually.

**Comment by LefterisJP** [comment]
We have added support for ETH2: https://github.com/rotki/rotki/issues/1694
Will add support for Kusama staking: https://github.com/rotki/rotki/issues/1081#issuecomment-746494337

As this issue is a bit too generic and not actionable I will close it.

If you want to request support for a specific staking protocol please open a new issue.
