### ISSUE TITLE
Binance API: sapi/v1/futures/loan/wallet - Error -1000

### ISSUE THREAD

**Issue by CyberDomovoy** [rotki/rotki#4781]
## Problem Definition

Since a few days, the binance API throws error -1000 (Unknown Error) on requests to sapi/v1/futures/loan/wallet.

## Logs

```
Could not save the balance snapshot at Binance. Binance account API request failed.
Could not reach binance due to Binance API request https://api.binance.com/sapi/v1/futures/loan/wallet?[...]
for futures/loan/wallet failed with
HTTP status code: 500,
error code: -1000 and
error message: An unknown error occurred while processing the request.
```

### System Description

Operating system:  LMDE 5, linux x64 5.10.0-16-amd64
Rotki version: 1.25.2

This is most probably a screwup on Binance side, removing API endpoints without warning.

Still, imho, an error on _one_ endpoint should not fail the whole backend. I think it would be better to throw a warning about that endpoint (as it does now), and keep going with the others, in order to get as much info from the backend as possible.

**Comment by isidorosp** [comment]
Seeing same issue as well

**Comment by LefterisJP** [comment]
Yeah I am seeing the same. No idea why. Binance broke something: https://twitter.com/LefterisJP/status/1565449236673662976

The API endpoint is still there in their docs so they did not yolo remove it: https://binance-docs.github.io/apidocs/spot/en/#cross-collateral-repayment-history-user_data

Even if they had it should be a 404 not a 500 error.

**Comment by ustas-eth** [comment]
Looking forward to a fix
Ubuntu 20.04, Rotki 1.25.3 Docker
