### ISSUE TITLE
Failed query for Binance: Deposits & withdrawals for Binance

### ISSUE THREAD

**Issue by pascalalich** [rotki/rotki#4792]
## Problem Definition

After adding Binance into my Rotki account using a read-only API key, an error occured while querying for deposits & withdrawals. By that a few transfers from Kraken to Binance couldn't be detected and the tax report was therefore not correct. 

Failed query for Binance: Error: Binance API request https://api.binance.com/sapi/v1/fiat/orders?timestamp=1662237540581&startTime=1624417199985&endTime=1632193199983&transactionType=0&recvWindow=10000&signature=... for fiat/orders failed with HTTP status code: 500, error code: -1000 and error message: An unknown error occurred while processing the request.

## Logs
can't find the relevant log 

### System Description

Operating system: Mac OS X, Monterey, 12.2.1
Rotki version: 1.25.3

**Comment by LefterisJP** [comment]
Hey @pascalalich this seems like an error on the binance side. For how to get full logs you can check here: https://rotki.readthedocs.io/en/latest/contribute.html#id2

**Comment by PabloCastellano** [comment]
Hi @pascalalich.

Binance broke their API and rotki v1.25.3 fixed it (https://github.com/rotki/rotki/issues/4781).
Are you using the latest released version?

**Comment by pascalalich** [comment]
Yes @PabloCastellano , I used that version. I am pretty sure now that it was a temporary Binance issue. It now has worked.
