### ISSUE TITLE
Replace DeFi protocol events with transaction based view

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4824]
## Abstract

Replace all the supported defi protocol events with a new mechanism that uses the existing decoded transactions/events.

## Motivation

The base motivation is to reduce database size, cleanup and remove legacy code etc.
For the frontend this will also provide a performance gain since we can re-use pagination from the transactions endpoint.

The current event approach caches all the events from all the supported protocols in the frontend state resulting in performance issues.

## Specification

- Make sure that decoders can handle as much as possible of these events.
- Create custom views with partial pre-filtering to replicate the old functionality as much as possible

**Comment by lukicenturi** [comment]
https://github.com/rotki/rotki/pull/5358
