### ISSUE TITLE
Bisq market api is unreliable. Search oracles for BISQ token

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4849]
the api responses from https://bisq.markets/api/ticker?market=bsq_btc are unreliable and failing most of the time. This api is used since was the only place we had to query BISQ token market price.

We need to investigate what is the status of this API or if we can get another source for the price. Until then the test is not running in the CI

**Comment by LefterisJP** [comment]
"Fixed" by https://github.com/rotki/rotki/pull/5579
