### ISSUE TITLE
Reduce eth2 validator footprint in frontend memory

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4870]
## Abstract

Analyze and spec out the changes needed so that we can minimize as much as possible the validator state that the frontend keeps in memory.

> I am creating the issue and I will add more information after I find some time to go through the application to figure out what exactly is needed.

## Motivation

Improve frontend performance

## Specification

- TBD

**Comment by tgerring** [comment]
The front end completely froze up on me as I forgot to run with inspector open. I am watching logs and all processing is completed. Memory footprint of the processes remained within a reasonable number, but the UI will not respond. I will attempt to repeat with inspector open this time

**Comment by kelsos** [comment]
@tgerring thanks I will also have to investigate, probably we either have too much in memory or something we do there causes a lot of redraws, probably a bit of both.

**Comment by LefterisJP** [comment]
I love the fact that @tgerring knows his shit too so feedback is constructive :smile:

**Comment by tgerring** [comment]
With Chrome debugger open, I was able to observe Rotki quickly grow to 4GB system memory before hitting out-of-memory.

This occurred as soon as the Staking view was selected from the menu. The overall task manager continued to animate, but the staking view itself froze almost immediately. Memory grew from approx 600MB (after being open for several hours) to 4000MB

**Comment by LefterisJP** [comment]
Hmm the 4GB memory limit seems to be an electron built-in limit which is a big issue faced by others: https://github.com/electron/electron/issues/31330

If I understand correctly though in latest versions this limit is increasing?

In any case we need to greatly greatly reduce memory usage in the frontend

**Comment by tgerring** [comment]
I tried to create a clean repeatable environment today suitable for testing with the following conditions:

- Virtual Machine with 8GB RAM
- Download and run Rotki
- Set cog wheel settings to Debug
- Initialize Inspector (Ctrl+Shft+I)
- Tail the log
- Open activity monitor of choice

I then attempted to import a large Depositor address (i.e. pick off of top 10 list). When I switched to the Staking module, I was prompted to input a premium key. I didn't want to cross-pollinate anything with my paid premium key, so I am wondering if this is safe to do or preferably you can generate a short-lived testing key for use on debugging this issue?

**Comment by kelsos** [comment]
If you don't enable syncing it should not create any problems.

I don't think we can make it for 1.26 but I will spend some time debugging and investigating after Devcon.

**Comment by kelsos** [comment]
Ok so I did figure out a probable cause for the issue. I have a fix prepared, and @LefterisJP will check to confirm if it improves the situation.

**Comment by LefterisJP** [comment]
The situation is improved a bit. Perhaps not 100% but it's visibly better. So for this iteration I will consider this particular issue addressed.

**Comment by kelsos** [comment]
> The situation is improved a bit. Perhaps not 100% but it's visibly better. So for this iteration I will consider this particular issue addressed.

Sounds good. We can see what else can be improved in the future
