### ISSUE TITLE
Take mev block rewards for ethereum staking into account

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#4886]
## Abstract

At the moment to calculate ethereum staking profit we only count block rewards and attestation payments. That's all given via the beaconchain api. But in reality if the user is using mev-boost they also gain the mev payment by the block builder (but not receive the block fee).

We already see these transactions since we analyze all eth mainnet transactions for the user. They are just not taken into account as part of staking rewards.

Should be quite easy to fix.

## Task

In the ETH staking view:

- take into account all mev profit and show it in as a different total
- take into account block rewards and show them as a different total

**Comment by shayanb** [comment]
How would you differentiate normal deposits from mev-boost deposits? e.g. https://etherscan.io/tx/0x1762e417ecd4763ab8d0541a799b83c014101c8227003b5b588932c086844eef


One way I see is to include a list of MEV payout contracts and consider the incoming transactions from them as staking profit, however I don't see this solution as a comprehensive and sustainable solution.

**Comment by LefterisJP** [comment]
> How would you differentiate normal deposits from mev-boost deposits? e.g. https://etherscan.io/tx/0x1762e417ecd4763ab8d0541a799b83c014101c8227003b5b588932c086844eef
> 
> One way I see is to include a list of MEV payout contracts and consider the incoming transactions from them as staking profit, however I don't see this solution as a comprehensive and sustainable solution.

Since rotki is a portfolio tracker for users the way I picture doing it is .. well exactly what you said. Keep a list of the known builders. A good start is this one from @metachris https://gist.github.com/metachris/a4d10ff59cad5ffe3cf0f2c6e91fc0bc

As long as the known builders keep the same addresses (and I have already seen flashots and bloxroute using ens for this) the vast majority of mev payout will be covered.

> I don't see this solution as a comprehensive and sustainable solution.

Won't be perfect if there is some exotic one we don't cover yet but we can make this editable by the user, so they can manually update the list of known builders until our next releases. If it works for 99% of the users then it's more than enough.

**Comment by shayanb** [comment]
Sounds like a good approach, I haven't seen a better solution yet. 
Thanks for taking the time to explain this further.

**Comment by mrosack** [comment]
I'm not sure if I should open a new ticket or if it fits here, but I'd really like to see block rewards as normal transactions in rotki.  Right now they're getting rolled into the "ETH2 staking daily PnL", and at the very least I'd like them broken out - in my view, block rewards are immediately taxable since I have access to them and I'd like to count them in my PnL while still ignoring all other staking rewards until withdrawals are available.

It just seems weird that my eth account balances are increasing without anything visible in the rotki ledger.

**Comment by LefterisJP** [comment]
> I'm not sure if I should open a new ticket or if it fits here, but I'd really like to see block rewards as normal transactions in rotki. Right now they're getting rolled into the "ETH2 staking daily PnL", and at the very least I'd like them broken out - in my view, block rewards are immediately taxable since I have access to them and I'd like to count them in my PnL while still ignoring all other staking rewards until withdrawals are available.
> 
> It just seems weird that my eth account balances are increasing without anything visible in the rotki ledger.

We should keep this issue. The merge was very recently made. There was no block rewards less than a month ago.

Block rewards are not a transaction. They would indeed be part of the ETH2 staking daily PnL ... but yes we should try to somehow separate them. Will need thinking.

**Comment by LefterisJP** [comment]
Made a follow up issue for the block rewards after all: https://github.com/rotki/rotki/issues/5473

**Comment by LefterisJP** [comment]
This is now completed. And will soon come out with 1.28
