### ISSUE TITLE
Replace all subgraphs asap

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#4891]
## Abstract

The hosted service is coming to an end very soon.

We at rotki, as a local app, are not able to use the decentralized network due to the payment requirements. Can't ask for all our users to pay for subgraph queries, nor can we take the payment on ourselves as api keys can't be hidden in the opensource code.

So they gotta go. Thankfully they are not too many and can all be replaced.

### Yearn v2

We use it to detect all vaults.

- [x] Replace with https://docs.yearn.finance/vaults/yearn-api

### Liquity

- [x] Used to register the events on the troves and the staking events. We can use the decoders to replace this functionality

### Aave

Used to query the events and the user reserves. We can use the decoders for the events and not sure about the reserves but surely we can find the contract to call

- [x] Make a decoder for enable/disable collateral events, deposits/withdrawals, borrows/repays
- [x] Make a decoder for liquidations and redemptions
- [x] Find contracts and call them for reserves info

### Balancer

- [ ] ~~We use the subgraph to query liquity position events (add/remove), mints and the user pool shares~~ We need to remove it for the balances

**Comment by yabirgb** [comment]
Marking this as complete after the merge of https://github.com/rotki/rotki/pull/7936
