### ISSUE TITLE
Issues pre-release

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4903]
## Tokens on price addition
- [x] I had already two accounts and added a new one. After all the tasks have been cleared the price of the tokens is still not shown. Clicking on refresh prices show them

![image](https://user-images.githubusercontent.com/5068010/193234002-d8185202-b391-4533-81f1-3ae107ac5306.png)

## Liabilities

- [x] When entering the liabilities or deposits section in DeFi I see this error in the console and nothing loads

```
vue.runtime.esm.js:4573 [Vue warn]: Error in mounted hook (Promise/async): "TypeError: Cannot read properties of undefined (reading '_tc')"

found in

---> <DecentralizedOverview> at /home/yabirgb/work/rotki/frontend/app/src/views/defi/DecentralizedOverview.vue
       <VTabItem>
         <VTabsItems>
           <VTabs>
             <TabNavigation> at /home/yabirgb/work/rotki/frontend/app/src/components/helper/TabNavigation.vue
               <DecentralizedFinance> at /home/yabirgb/work/rotki/frontend/app/src/views/defi/DecentralizedFinance.vue
                 <VMain>
                   <AppCore> at /home/yabirgb/work/rotki/frontend/app/src/components/app/AppCore.vue
                     <AppMessages> at /home/yabirgb/work/rotki/frontend/app/src/components/app/AppMessages.vue
                       <VApp>
                         <AppHost> at /home/yabirgb/work/rotki/frontend/app/src/components/app/AppHost.vue
                           <App> at /home/yabirgb/work/rotki/frontend/app/src/App.vue
                             <Root>
```

**Comment by yabirgb** [comment]
- [ ] The chain icon is not properly shown for all the assets (multiple accounts in this example). Going from dashboard to accounts and then dashboard shows the expected icon

![image](https://user-images.githubusercontent.com/5068010/193260254-7f2fa65c-2233-42b5-8117-ec88160bf560.png)

**Comment by yabirgb** [comment]
- [ ] Hovering over the usdc icon doesn't show the name/symbol
![image](https://user-images.githubusercontent.com/5068010/193360116-d38275d0-9647-47ed-8d95-d186ecbfe8f2.png)

- [ ] Problem navigating the UI
![image](https://user-images.githubusercontent.com/5068010/193360173-ee877829-33ab-4479-bbe9-0c7c15b4e821.png)

**Comment by nebolax** [comment]
There is an error that frontend passes an ens name to ethereum modules if I check "Enable \<module\> for this account" during account addition instead of the address which results in this error.

![image](https://user-images.githubusercontent.com/63492346/194767346-ba92a0b0-cdad-42e3-b036-ffc9ff2c89e8.png)

**Comment by kelsos** [comment]
@lukicenturi at some point can you put a checkmark to the ones that have been fixed?

**Comment by lukicenturi** [comment]
I think all issues here have been resolved.
