### ISSUE TITLE
Allow ignoring certain NFTs

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#4912]
## Problem Definition

In 1.25.3 I don't think it's possible to ignore any detect NFTs from appearing at all, just their price.

As scammers get more and more annoying scams like the following will appear:
https://twitter.com/LefterisJP/status/1575984197688209409

![2022-10-01_00-56](https://user-images.githubusercontent.com/1658405/193367539-17195ca3-8716-4ff4-a405-383cfcc97b13.png)

We need to at least allow the user to ignore them completely and maybe even auto-detect and bllock?

## Task

- [ ] Allow ignoring NFTs and completely omitting them from dashboard and NFT gallery
- [ ] (Optional) Auto-detect spam NFTs and omit them?

Note: Since for now, for NFTs we heavily rely on the opensea API perhaps the moment they mark it as spam and remove it from the API we also get it removed, which has its positive side (as far as this issue is concerned) -- but also shows that relying solely on opensea for NFTs is a mistake (https://github.com/rotki/rotki/issues/4911)

**Comment by rkalis** [comment]
One potential way is looking at the volume stats you get from the OpenSea API and filter any NFTs with less than a few ETH volume. Of course scammers can fake volume, but a big part of the scams I've seen have 0 volume on OpenSea.

**Comment by LefterisJP** [comment]
Yes that's true if you wanna go with analysis to auto-mark stuff as spam. But this specific issue is to just allow ignoring certain nfts manually.
