### ISSUE TITLE
[FEATURE] Disable Sign-ups on Self-Hosted

### ISSUE THREAD

**Issue by Xosten** [rotki/rotki#4932]
## Abstract

If hosting Rotki on a server and it's accessible through a public URL, anyone can create an account on our self-hosted instance. Some people might not want other people using their instance. 

Today's workaround I found, is using something like Cloudflare Access in front of Rotki, before authenticating in the portfolio manager. I also managed to use the IPWhitelist feature of Traefik.

## Motivation

Have more control over unknown people registering on our self-hosted instance.

**Comment by LefterisJP** [comment]
hey @Xosten thanks for the issue. rotki is not meant to be hosted on a public facing URL. This is unsafe for more reasons than what you are stating here. You would need to put some kind of authentication in front as you mentioned.

@kelsos corrent me if I am wrong

**Comment by kelsos** [comment]
Yes, rotki is not designed to be directly accessible from a public-facing URL.

At the moment the suggested approach is to have another layer of authentication via a proxy such as traefik.

**Comment by Xosten** [comment]
Thanks @LefterisJP & @kelsos for your quick reply. I wasn't aware that Rotki isn't meant to be hosted on a public-facing URL. Seeing the "Register" button on the login screen made me though it was possible. Maybe I should have read the docs 😅.

I will keep Cloudflare Access in front of Rotki (Authentification) and add Traefik IP White List for my VPN. I guess it should be enough.
