### ISSUE TITLE
Eth rpc nodes sorting

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#4937]
## Abstract

When displaying ethereum rpc nodes in settings, there is no particular order right now. 

## Motivation

Having consistent ordering will improve UX

## Specification

Backend needs to sort nodes before sending it to frontend

**Comment by webbdays** [comment]
Yes, It would be easy for users to find a rpc node name by following the alphabetical order.

**Comment by webbdays** [comment]
I would like to work on this.

**Comment by LefterisJP** [comment]
> I would like to work on this.

Sure go ahead

**Comment by yabirgb** [comment]
@webbdays You can join our discord where we have a dev-support channel (https://discord.gg/aGCxHG7) in case you need any help. Also where the rpc endpoints are returned is here https://github.com/rotki/rotki/blob/dfdbcfb8b5e9b376ab44f39f6d09e685dae99d3b/rotkehlchen/rotkehlchen.py#L955 You can check other methods to see how we do the sorting

**Comment by webbdays** [comment]
Thanks for that.

**Comment by webbdays** [comment]
#4993

**Comment by LefterisJP** [comment]
This should be fixed
