### ISSUE TITLE
Think of a way to keep development accounts separately 

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4978]
## Abstract

Between multiple development machines and between `production`/`develop` it becomes harder to keep track of which database has been used by which branch. This can lead to partially updated databases being used.

As a proposal, we could somehow separate where the `develop` accounts and the production accounts are stored so that they are not sharing the same place.

We can always copy accounts from production to develop manually (this can go to the guide).

We should also consider how this affects nightlies and how nightlies are treated. For example we might want to treat nightlies as development to avoid having users mess accidentally with their production accounts.  

## Motivation

Helps better track which accounts are used in `develop`/`production`.

## Specification

- TDB

**Comment by LefterisJP** [comment]
Should be handled by https://github.com/rotki/rotki/pull/5256
