### ISSUE TITLE
Group same multi-evm assets in the frontend

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5015]
## Abstract

As discussed in the past now that we will have multi-evm chain support it would make sense everywhere in the frontend to show all versions of the same asset across various chains as one.

So if you have an asset like DAI in multiple chains it should all appear grouped in the frontend, but with an indicator. When the user presses this indicator it should expand to show the DAI tokens in the different chains along with amount/prices.

In the backend we already have the assets collection table in the global DB which is supposed to represent these kind of connections.

```python
# The asset_collections table allows to set common information for related assets as described in
# the multiasset_mappings table. The reason to have a custom name and symbol is that for some
# tokens those properties are not the same across different chains. For example in gnosis chain
# USDC uses USD//C as symbol for the USDC token. This table addresses this problem by creating a
# common name and symbol for those assets allowing a clean representation for the users and
# working as common row to connect all the related assets.
DB_CREATE_ASSET_COLLECTIONS = """
CREATE TABLE IF NOT EXISTS asset_collections(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    symbol TEXT NOT NULL
);
"""
```

## Task

- Most of the backend work for this exists. But the api would need changes I suppose
- Figure out how to do this properly in the frontend. First guess is that frontend work required here would be the biggest.

Scheduling note: Putting this for a close release, but in reality this should go in along with the first release we have that add support for one more evm chain.

**Comment by kelsos** [comment]
@lukicenturi this is done on the frontend too right? 

Is there anything else remains to be done for this issue?

**Comment by LefterisJP** [comment]
@lukicenturi please answer pings in Github. No answer and no new information makes me assume this is done.
