### ISSUE TITLE
Indepedent Reserve API update incoming

### ISSUE THREAD

**Issue by TheWanderer1983** [rotki/rotki#5017]
## Problem Definition

1. Changing API key access level names

```
Old name:                    New name: 	               Access description:
Read Only                    Read Only                 Cannot trade, withdraw, or make changes
Admin 	                     Trade 	               Trading only, no crypto or fiat withdrawals
Withdrawal Admin 	     Restricted Withdrawals       As per Trade level, 
Full Access 	             Full Access 	       Full access to all API end points
```

2. Reducing rights of the Trade access level

The Trade level (formerly Admin) is changing: currently this level has access to perform fiat withdrawals, but no crypto withdrawals. Going forward this access level will have no access to fiat or crypto withdrawals. Please ensure any application or platform you use with a Trade/Admin API key does not require fiat withdrawal access.

Timing for these changes

We will be performing system maintenance and upgrades on Sunday the 30th of October at 2pm Sydney time, 11am Singapore time. We expect this to last approximately 4 hours and during this time you will not be able to access your Independent Reserve account via the website or API.

**Comment by LefterisJP** [comment]
Hey @TheWanderer1983 thanks for opening an issue. What exactly is it that you want us to do here? You can always change your api keys for any exchange.

**Comment by TheWanderer1983** [comment]
I thought some of the name changes might throw out the Independent reserve implementation in rotki.

**Comment by LefterisJP** [comment]
At the moment I don't see anything actionable here. If something breaks then we can fix it when it happens.
