### ISSUE TITLE
The icon on OSX could afford a few more pixels

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#502]
## Abstract

The resolution of the App icon is visibly low:
![image](https://user-images.githubusercontent.com/738724/64323267-6ebe0f80-cfc4-11e9-9b43-1d804d4c8e01.png)

That makes Rotki somehow look like a black swan :)
![image](https://user-images.githubusercontent.com/738724/64323907-ac6f6800-cfc5-11e9-8c66-c2086c903ab5.png)

## Motivation

Very low prio obviously but that should be easy to fix.

**Comment by LefterisJP** [comment]
Hmm that's strange. For me it looks better ... but I have an old Macbook air to test stuff for mac.

I followed a guide like this: https://elliotekj.com/2014/05/27/how-to-create-high-resolution-icns-files/
to create the [icns](https://github.com/rotkehlchenio/rotkehlchen/blob/master/ui/images/rotki.icns) file.

So it should also contain high resolution versions.

**Comment by chevdor** [comment]
Not sure what to say, this is pretty much the only icon looking like pixel art on my machine :)
It is especially visible when you use a big magnification on hover in the dock.

**Comment by LefterisJP** [comment]
Hmm I will try to find another OSX machine to try then.

What version are you running?

**Comment by chevdor** [comment]
I am running the current official version: macOS Mojave (10.14.6).

**Comment by chevdor** [comment]
I am not sure how icns files are supposed to be.
I see 5 resolutions. The last is very low and I never saw that.
The 2 first are looking good. I also did not see those :)
The 3 and 4 are low res and I guess one is the one we see in this issue.

Now why would macOS pic a lower res when higher is available, I am not sure of that.

**Comment by chevdor** [comment]
Interesting as well:
![image](https://user-images.githubusercontent.com/738724/64622510-bf2fd580-d3e7-11e9-879d-c304e9b8ee29.png)

The screenshot shows that the icon of the icon file (on the right) shows with a good resolution. We see the App icon next to it on the left.

**Comment by MorganGR** [comment]
I wonder if it's a naming convention issue.

**Comment by LefterisJP** [comment]
If any of you have any OSX experience please check this. It would be cool to have this resolved externally :)

 If not, I will when I find some time. Can't be that hard. Some problem with the way the icons are defined, or the way the App icon is chosen is probably the reason.

**Comment by MorganGR** [comment]
@LefterisJP any chance you can upload your original Rotki image? I can create the smaller versions.

**Comment by LefterisJP** [comment]
Here is a zip containing both the svg file from which they were generated but also all icons that are currently inside the DMG file in the form of ICNS
[rotki_pics.zip](https://github.com/rotkehlchenio/rotkehlchen/files/3622710/rotki_pics.zip)
