### ISSUE TITLE
Double conversion at custom asset price if price is denoted in main currency

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5049]
## Problem Definition

If a user has input a custom asset, say an ETF, and wants to track it in rotki in the same currency as the main currency, say EUR, then a double conversion is happening.

To reproduce:
- Set main currency to EUR (or anything other than USD)
- Create a new custom asset, with a custom price in EUR
- Go back to the dashboard and you will see the price is going through double conversion

For example in this case I put `93.75` but it appears as `93.7500775884375`

![2022-10-29-002222_408x143_scrot](https://user-images.githubusercontent.com/1658405/198743837-898657db-bf38-47c2-91b3-2d52329da101.png)

## Task

Fix it

**Comment by LefterisJP** [comment]
Something similar also seems to happen at the input prompt of a manual balance. This  last one is probably frontend?
![2022-10-29_00-32](https://user-images.githubusercontent.com/1658405/198745849-ad0b56af-9320-4246-ab2d-98e0166939cb.png)

Price of 1 EUR should be 1 EUR

@kelsos @lukicenturi

**Comment by kelsos** [comment]
Ok from what I can see we request the prices from `/api/1/assets/prices/latest` with USD as a target which means that the backend converts from EUR to USD and then the frontend converts these prices to EUR back again.

I think that a fix might be a bit complicated here. I don't think we can simply switch from USD to EUR, as that would actually break the price refresh.

Currently, the price refresh in the frontend takes the response of `/api/1/assets/prices/latest` and re-calculates the `usd_value` based on the `amount` and this is why we request the prices in `USD`.

**Comment by LefterisJP** [comment]
Couldn't you ask for the price in the main currency (EUR?) instead? And then the backend should see there is no conversion necessary and just send it to you directly and you use it directly? And do conversion when needed?

**Comment by kelsos** [comment]
We could ask for the main currency, but if I do `main_currency * amount` then we cannot put that in the `usd_value` field because the result is not `usd_value`.

What would make sense in the frontend in that case, would be completely ignoring the `usd_value` field coming from the backend. Keeping track of which asset is in usd/main currency would be way more complicated if this information doesn't come from the backend, so I would prefer to avoid it.

We will also have to change the amount display component because it assumes USD as the fiat currency whenever we display amounts.

This will break a lot of assumptions on how the frontend deals with prices and it is not that it can't be done, but it is not a patch release fix.

**Comment by kelsos** [comment]
So as a temporary solution:

- Backend checks if the latest manual price is the main currency and then returns a flag `1` in the tuple, and returns the price unconverted, and the flag as the third tuple value.
- Frontend will check if this flag exists for a price and don't do a conversion in the UI.

**Comment by LefterisJP** [comment]
Should be fixed by #5069 and #5080 and various other smaller PRs here and there documented in the follow up issue.

Keep in mind this is **NOT** the right solution and is just a temporary step which should be undone when the right solution is implemented.

Issue for the good aproach is here: https://github.com/rotki/rotki/issues/5071

**Comment by nonsense** [comment]
I am pretty sure that this is affecting also `Liabilities` -- I have set some liabilities and denoted them in EUR, for example 248.00 EUR, and they appear summed up to 248.08 EUR

**Comment by LefterisJP** [comment]
> I am pretty sure that this is affecting also `Liabilities` -- I have set some liabilities and denoted them in EUR, for example 248.00 EUR, and they appear summed up to 248.08 EUR

and this still happens in 1.26.1?

**Comment by kelsos** [comment]
> > I am pretty sure that this is affecting also `Liabilities` -- I have set some liabilities and denoted them in EUR, for example 248.00 EUR, and they appear summed up to 248.08 EUR
> 
> and this still happens in 1.26.1?

When we were discussing about it we already noted that the sum might be off in these cases.

**Comment by LefterisJP** [comment]
Ah yes if it's the sum then this is a known side effect. The point is to not have it at individual ones.

**Comment by nonsense** [comment]
Yes, still happening on 1.26.1.

I just refreshed balances and it appears exactly correct (248.00 EUR -> 248.00 EUR), but I can swear that it was showing as 248.08 EUR prior to refreshing. Rotki itself was already on 1.26.1 (since a few days).

**Comment by nonsense** [comment]
Individual values are indeed correct.
