### ISSUE TITLE
Hide asset in information events that don't require it

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5066]
## Problem description

The backend logic is forced to have an asset for all base events returned but for some like ENS informational events it doesn't make much sense to have an asset there 

![image](https://user-images.githubusercontent.com/5068010/199095846-44cb19f9-c27e-4c6b-aa3f-c23c97c5d50b.png)

## Task

- [ ] Allow in the frontend for certain tuples of `(protocol, HistoryEventType, HistoryEventSubtype)` that the asset and the amounts don't show to the user
- [ ] Study the possibility of setting `asset` in `HistoryBaseEntry` that is better semantically with the different cons:
* add many if checks to the code, might be a nightmare and a reason to avoid it
* an additional big db upgrade
* issues with filtering and showing the other events

**Comment by LefterisJP** [comment]
Closing in favor of https://github.com/rotki/rotki/issues/6371 as it's the same issue but that one has more information on how to properly do it
