### ISSUE TITLE
Improve token scanning and balance detection combination

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#5103]
## Problem Definition

your net worth is shown in the main dashboard along with a graph of its value over time.   this major headline number is no longer accurate with the breaking change thats recently been made.

a breaking UI change has been made where Ethereum addresses are now no longer scanned by default for token values.  Whilst this optimisation makes address scanning faster, it does so at a large cost of leaving out major assets (tokens!) from your net worth so the headline net worth figure in the dashboard will no longer represent an accurate picture of your net worth, = clearly, this is undesirable from a UI point of view and defeats an important use case of Rotki, to know a true figure of your net worth and all of your assets that is automatically maintained.

if you really must have this optimisation in there, then I would recommend two UI fixes to make it less onerous.

1.  there should be a 're-detect all tokens' button sitting right next to 'blockchain balances' refresh button on the main dashboard.

2.  make sure that when your 'net worth' is re-scanned every 12 hours (or whatever its set to)... that it not only scans blockchain balances, but also tokens.   otherwise your net worth as shown on the headline is meaningless.

## Logs

no logs required.

-->

### System Description

all rotki versions.

Operating system: MacOS
Rotki version: 1.26.1

**Comment by JezSan** [comment]
3.  I would also have an option whereby when you hit 'blockchain balance' refresh, that it does the tokens as well, even though it will take longer.
4.  ideally, detect 'events' in addresses so that you can optimise the re-scanning of Ethereum addresses and only scan the ones that have changed.

**Comment by LefterisJP** [comment]
Hey @JezSan thanks for taking the time to write an issue.

Anyway so (2) should be done and is an oversight on our part.

(1) and (3) is UI issues which we will discuss


(4) is a separate issue and much harder to do than something quick -- plus this event scanning will give us a lot of other info apart from just what changed.

**Comment by LefterisJP** [comment]
A similar comment from Jez on discord:

>Here’s my suggested UI improvements to make token scanning more usable. It’s unusable and a huge backwards step right now when it comes to token handling 
>
>
>1.   For each address in the database have two tick mark options. One for scan every time and one for scan only during full scan
>
>2.  Users will mark addresses that they change frequently on the scan every time setting.  And addresses that rarely change they can scan on full scan less frequently
>
>3.   In the main dashboard have ‘quick scan’ and ‘full scan’ options for refreshing blockchain values
>
>4.  Long term it’s better if it auto detected events so it knows what to rescan automatically

**Comment by LefterisJP** [comment]
This is not changed in 1.28. Backend still does not query balances for token detection. I remember we looked at it and it would complicate things a lot. So pushign this for now, but may very well end up ignoring the last part ofthe change in favour of the iterative balance query which will anyway change these things,
