### ISSUE TITLE
Allow Grouping of like-tokens, for instance different flavours of Eth

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#5104]
## Abstract

There's various flavours of Eth, some of which are automatically detected and collated, for instance, Eth and Eth staking rewards (misnomer) 

but there's also rETH, stETH, cbETH, WETH etc... these are all shown in the token list, but it would be nice if they could be optionally grouped together under ETH as they are all representations of the ETH underlying asset.

Complicated a little that some of the liquid staking tokens are rebasing tokens (like stETH), and thus their quantity changes over time but their value remains 1:1 with Eth, whereas some of the liquid staking tokens like rETH and cbETH are value changing to represent a claim on the underlying eth and their quantity doesn't change.

## Motivation

If I want to know how many Eth ive got (or will have, at the time when withdrawals are enabled), at present I have to total up various columns of Eth in different places in the asset list.

## Specification

Have an expanding grouping option (eg a + sign next to ETH), so you can see a summary of total underlying Eth, and if clicked to expand, will show the various tokens that make it up.

**Comment by LefterisJP** [comment]
We want to do that for same asset representation in different chains. Issue here: https://github.com/rotki/rotki/issues/5015

Now for what you say perhaps that may also be useful but I would keep it as an option. Maybe even make it user configurable? Defining what is "related" basically.

**Comment by LefterisJP** [comment]
I will close this issue in favor of https://github.com/rotki/rotki/issues/3494 as I think they are the same and something I would like to see in rotki ASAP.
