### ISSUE TITLE
Uniswap v3 transactions decoded wrongly in some cases.

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5127]
## Problem Definition

The uniswap v3 decoder does not work properly in complicated transactions that contain multiple swaps. We need to ensure that a uniswap v3 ETH send to the tracked account is decoded properly when a lot more other events are included in the same transaction.

## Logs

This transaction https://etherscan.io/tx/0xcb8b20f55ababdc8895f26b2216619e810c505968b3dfdacc92abb8f7984d5a6
![image](https://user-images.githubusercontent.com/5068010/201468661-da0b019b-db52-411f-8587-2743f734667e.png)

### System Description

Operating system: All
Rotki version: 1.26.1

**Comment by LefterisJP** [comment]
This should be fixed by #5162
