### ISSUE TITLE
NFT user DB schema incosistency

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5132]
## Problem Definition

The NFT schema in the DB currently has a few fields that are optional which are not considered optional by the codebase. But since the DB allows it, it's easy to miss and create bugs like the one I am fixing here: https://github.com/rotki/rotki/pull/5131

```sql
CREATE TABLE IF NOT EXISTS nfts (
    identifier TEXT NOT NULL PRIMARY KEY,
    name TEXT,
    last_price TEXT,
    last_price_asset TEXT,
    manual_price INTEGER NOT NULL CHECK (manual_price IN (0, 1)),
    owner_address TEXT,
    blockchain TEXT GENERATED ALWAYS AS ("ETH") VIRTUAL,
    is_lp INTEGER NOT NULL CHECK (is_lp IN (0, 1)),
    image_url TEXT,
    collection_name TEXT,
    FOREIGN KEY(blockchain, owner_address) REFERENCES blockchain_accounts(blockchain, account) ON DELETE CASCADE,
    FOREIGN KEY (identifier) REFERENCES assets(identifier) ON UPDATE CASCADE,
    FOREIGN KEY (last_price_asset) REFERENCES assets(identifier) ON UPDATE CASCADE
);
```

Specifically at least `last_price` and `last_price_asset` are optional in the DB schema, but not in the way we use it in the code

```python
class NFT(NamedTuple):
    token_identifier: str
    background_color: Optional[str]
    image_url: Optional[str]
    name: Optional[str]
    external_link: Optional[str]
    permalink: Optional[str]
    price_eth: FVal
    price_usd: FVal
    collection: Optional[Collection]
```

or the way we read it from the DB in at least one place: https://github.com/rotki/rotki/blob/754f6ae7536463d9dc8791182aa616c9f99706fd/rotkehlchen/chain/ethereum/modules/nfts.py#L146-L148

## Task

Fix this incosistency all across the DB and codebase

**Comment by Juyotal** [comment]
So where does the change have to take place, In the DB or in the code?

**Comment by LefterisJP** [comment]
> So where does the change have to take place, In the DB or in the code?

Last price should be also optional in the code, as it is in the DB.
