### ISSUE TITLE
Make oracle penalty info user configurable

### ISSUE THREAD

**Issue by prettyirrelevant** [rotki/rotki#5143]
## Problem
https://github.com/rotki/rotki/pull/5133 introduced a mechanism that penalizes misbehaving oracle(s) in runtime.

However, the approach hardcodes the constants that determine which oracle(s) should be penalized.
This should not be the case, it should be user configurable.

## Specification
Instead of hardcoding it, move it to `DBSettings` so it can be updated/changed from time to time by the user.

**Comment by pratiksinghchauhan** [comment]
Can I work on this one?

**Comment by yabirgb** [comment]
Hello @rishabhRsinghvi. This has not been addressed yet so I can assign you. Come to our discord if you need help or questions and we will able to answer fast https://discord.rotki.com/

**Comment by rishabhRsinghvi** [comment]
Hi @yabirgb I did join.

**Comment by programmer-ke** [comment]
So I've tracked the issue to this TODO comment: https://github.com/rotki/rotki/blob/0329b262d425988469647f77bf7a4acd528f2812/rotkehlchen/utils/mixins/penalizable_oracle.py#L32

It says that the settings to make configurable are `ORACLE_PENALTY_THRESHOLD_COUNT` and `ORACLE_PENALTY_TS`

**Comment by programmer-ke** [comment]
Hey @yabirgb I've opened a linked PR.
