### ISSUE TITLE
Detect all tokens is a no-op

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5158]
## Problem Definition

The detect all tokens button does not do the work it's supposed to do in v1.26.1

![2022-11-23_00-52](https://user-images.githubusercontent.com/1658405/203444734-681c0c71-5c68-4b21-bae6-ab4b9cf0bcef.png)

It's a no-op. The reason is that it's called by the frontend with `only_cache=True` so only the last known detected tokens are returned. The intention was to skip cache and actually detect tokens so it should be `only_cache=False`.

Additionally the backend should not count it as a token detection.

## Task

- [ ] Do not use `only_cache=True` on that button
- [ ] If `detect_tokens` is called with `only_cache=True` the last detection timestamp **should not be** updated

**Comment by yabirgb** [comment]
At the moment the backend doesn't update the `last_queried_ts` when `only_cache is True` https://github.com/rotki/rotki/blob/103fe97dd8e1d44e09e1d9ab8e376e7c47f5d438/rotkehlchen/chain/evm/tokens.py#L224

**Comment by lukicenturi** [comment]
As I said in discord, this Re-Detect Tokens is already called with `only_cache=False`.
So I think we can close this task.

What we have to do for this detect token thing is in https://github.com/rotki/rotki/issues/5103

**Comment by LefterisJP** [comment]
@yabirgb @lukicenturi I don't know exactly what is wrong. If I did indeed not see the correct reason for the bug then you need to figure out what the correct reason is.

As Jez and me and 2 more users have reported. In 1.26.1, if you receive a new token after you have already queried/detected balances, doing a query/detect again DOES not see it. Restarting the app and pressing that button again does not see it.

**Comment by lukicenturi** [comment]
I explained the issue on frontend here https://discord.com/channels/657906918408585217/683245846070165504/1044908140958842970

Not sure if there is any backend issue.

**Comment by LefterisJP** [comment]
I am closing this as a not-reproduced properly and since many changes happened and will happen there no action to do since we investigated

**Comment by kelsos** [comment]
At least from the testing we did for 1.27 there was no problem with the token detection.

Things for me seemed to work fine in all cases
