### ISSUE TITLE
Provide an option not to automatically rescan balances with every modification

### ISSUE THREAD

**Issue by lbeder** [rotki/rotki#5175]
## Abstract

In the current version, whenever I change an address name, or make a new tag, my whole portfolio is rescanned and while it's being rescanned, all options to change names or tags are greyed out until the scan is completed. This makes the app utterly unusable, as to change names or takes for 100+ addresses it can take many hours of waiting time. 

## Motivation

It'd be really great if the automatic rescanning is slightly delayed/postponed. For example, this is how some other crypto tax apps work: they have a grace period of a few minutes until your portfolio is recalculated, giving the user more time to add/update his data before scheduling a complete rescan and tax recalculation.

**Comment by kelsos** [comment]
Hey, @lbeder thanks for the report. This certainly seems like a bug.
