### ISSUE TITLE
Interest Compounding ETH Index - (icETH)

### ISSUE THREAD

**Issue by macguyvar** [rotki/rotki#5189]
can we please add? not automatically picking up the balance. 

**Asset name:** Interest Compounding ETH Index
**Asset symbol:** icETH
**Coingecko link:** https://www.coingecko.com/en/coins/interest-compounding-eth-index)
**Cryptocompare link:** - not listed

**Comment by LefterisJP** [comment]
We can add it sure. @yabirgb include it the next change to the assets repo.

But @macguyvar you can just do it manually for your own rotki instance: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset

Any token rotki does not have on the assets DB you can just manually fill in and it will later be detected

**Comment by macguyvar** [comment]
beautiful! I will do that next time. 

The one I'm having a hard time with is sETHBTC - Synthetix token.. It isn't listed on cryptocompare or coingecko.. 

https://synthetix.io/synths    -  in L1 towards the bottom
