### ISSUE TITLE
NFT balances

### ISSUE THREAD

**Issue by macguyvar** [rotki/rotki#5190]
## Abstract

Is it possible to adjust or filter out the NFT dollar figure from the total on the dashboard on the front page?

## Motivation

I have a silly NFT that I minted and Rotki is picking up the floor price on the NFT which is no where close to the value of the NFT which is over stating my portfolio by 50%

## Specification

a little filter button on the total balance of your portfolio to filter out NFTs

**Comment by LefterisJP** [comment]
This already exists. You have many many options here.

1. Check the settings. There is a setting to ignore all nfts in total net worth and graphs: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset
2. You can ignore that specific nft
3. You can actually add a manual price for that specific nft. No need to agree with the opensea price.


Btw for simple questions like this it's probably better to just ask us in our discord: https://discord.gg/aGCxHG7
(Have DMs open as there is a captcha challenge)

**Comment by macguyvar** [comment]
The NFT balances are not showing up under "manage prices or manage assets" 

I'm trying to get into the discord but its just stuck in the loading screen on the cache, tried 3 different browsers and nothing working.

**Comment by macguyvar** [comment]
yes DMs open, go to cache, click on "i am human" and it just sits there loading. 

kirch#5936

**Comment by LefterisJP** [comment]
That's weird. I verified you manually

**Comment by macguyvar** [comment]
thank you so much!
