### ISSUE TITLE
Balance query for LP positions

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5208]
In https://github.com/rotki/rotki/pull/5207/files#diff-93dd3d2fccb5ce3e2b0a394be8aa37f0c27f48d449b1c61182f07011c0318472L180 we removed the code using the subgraph to query for LP positions in uniswap, sushiswap and balancer. We need  a new way of detecting the LP positions and adding them to the balances.

## Approach proposed

We can use the decoded transactions to detect the pools where the user has deposited assets. We can solve the problem in two ways

- A better approach will be replaying the history and knowing exactly the LPs with non 0 value for each address
- The second approach is to query the deposits in uniswap pools and query balances for all the possible tokens for each address

### Requirements

For this approach we need to add decoders for deposits/withdrawals of LP positions. For Uniswap we don't have them at the moment and for balancer #5197 does it

**Comment by LefterisJP** [comment]
Whenever this is done we also need to figure out where is the `uniswapv2_lp_tokens.json` and its `uniswapv2_lp_tokens.meta` still being used. I see non-premium uniswap v2 balance query but generally this is a method that does not scale (having a manually updated uniswapv2 (and any other amm) token list and querying all ofthem like we do tokens.

**Comment by yabirgb** [comment]
This is what we already do in our new approach to balance detection. Closing it
