### ISSUE TITLE
Create dockerfile for Rotki in Linux

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#521]
## Abstract

Rotki in Linux is easy to install but if we have a Dockerfile that takes care of installing it in a machine then it will be even easier to be integrated by other applications.

## Motivation

The people from Dappnode (https://github.com/dappnode) mentioned that a prerequisite for including Rotki in Dappnode is to have it dockerized.

## Task

Create a dockerfile for Rotki

**Comment by bobkilla** [comment]
I am interested but will not be able to work on it before tomorrow's evening. Is that ok for you?

**Comment by sponnet** [comment]
A DappNode / AVA.DO box just hosts docker containers. Could you explain what the goal is of running it on a headless device ? Or does it have a webserver integrated that you can use ? Just trying to get a high level idea of what you want to do, so maybe I can help as well.

**Comment by LefterisJP** [comment]
> I am interested but will not be able to work on it before tomorrow's evening. Is that ok for you?

@bobkilla No hurry for this issue!

> A DappNode / AVA.DO box just hosts docker containers. Could you explain what the goal is of running it on a headless device ? Or does it have a webserver integrated that you can use ? Just trying to get a high level idea of what you want to do, so maybe I can help as well.

So from what I understand of Dappnode is that it's headless but that you can also connect to it from the outside. At the moment Rotki is a python backend which does all the work and has an API and a user interface written in electron.

It will take some work but it should be possible to also be able to run the UI in one machine and the backend in another. This way it could be bundled with ethereum and other nodes which it needs for data (it can also use etherscan or bitcoin.info e.t.c. but that's not really decentralized) ... and also do the portfolio tracking and accounting.

Just like they also mention in the [Readme](https://github.com/dappnode/DAppNode#dappnode) that also you can run local version of MyCrypto.

Perhaps also @dapplion or @eduadiez from Dappnode can chime in here.

**Comment by sponnet** [comment]
Hey @LefterisJP ,

I rolled the latest version in a AVADO / dappnode package, but as mentioned - it will not work yet because it tries to open a GUI - and that is not available. If you can split the executable so that it can run headless with an API + either a web-app or a standalone client app, this might work & looks very interesting for anyone that needs this functionality, which are a lot of people I would think !

At least now there is a base to work from!

https://github.com/AvadoDServer/rotki.dnp.dappnode.eth

**Comment by LefterisJP** [comment]
Hey @sponnet thank you so much.

I made a meta issue for the enabling of Rotki to run in a headless machine, specifying what needs to be done: https://github.com/rotkehlchenio/rotkehlchen/issues/523

As for the Dockerfile issue you think the Dockerfile maintenance could be moved inside this repo too? I am not sure how it usually works with dappnode packages but It would be much easier to update when new releases happen.

**Comment by bobkilla** [comment]
Sorry I won't have time to work on this but I see you have made some progress ;) Good luck!
