### ISSUE TITLE
Don't ignore exchanges in PnL if API keys are removed

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#5263]
## Problem Definition

If a user removes exchange API keys from the app then trades, ledger actions, etc. from that exchange will no longer be used in PnL reports even though they are still stored in the database. That is a problem and should be fixed. The same problem does not appear for the trades view, as [query_trades](https://github.com/rotki/rotki/blob/c974019abddb4bf01d8742658c45d8fd8c6798bc/rotkehlchen/history/events.py#L135) does not check active exchanges but simply gets paginated trades in the DB.

The way to implement this would probably be by doing something similar like the trades query in the part of gathering history events for the PnL report.

## Task

- [ ] Make it so that trades from an exchange that is not tracked (no key in the app, so not part of the exchange manager) are taken into account in the PnL report.
- [ ] Write a test for it.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/5266
