### ISSUE TITLE
Add adjusted cost base method option - Canada

### ISSUE THREAD

**Issue by MECINC** [rotki/rotki#5419]
## Abstract

Add option for selecting adjusted cost base method (or ACB) for purposes of calculating taxable capital gains. 

## Motivation

The adjusted cost method is required by Canada Revenue Agency when calculating capital gains on crypto. As a Canadian I would not be able to use your service as it only offers FIFO and LIFO cost base methods. 

## Specification 

**Guidance on the adjusted cost base method:**
https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/compliance/digital-currency/cryptocurrency-guide.html
https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/personal-income/line-12700-capital-gains/calculating-reporting-your-capital-gains-losses/adjusted-cost-base.html
https://turbotax.intuit.ca/tips/calculating-adjusted-cost-base-6285
https://coinpanda.io/blog/crypto-taxes-canada-adjusted-cost-base/

**Comment by LefterisJP** [comment]
Hello @MECINC.

Thank you for opening a feature request. I would like some clarifications.

If I read this correctly it works with:

1. Average cost basis strategy
2. And the superficial loss rule on top. Which seems to be a 30 day period within which you can't claim a loss from selling crypto.

So then this is very similar to the UK rules here: https://github.com/rotki/rotki/issues/3941

We have already implemented "average cost basis" strategy and it will be implemented in the next release.

Implementing the special UK rules and the superficial loss rule sounds like a task that can be combined as they are pretty similar and both based on the average cost basis strategy.

Is my understanding correct?

**Comment by MECINC** [comment]
Hi @LefterisJP,

Thank you for your reply. You are correct - appears they are very similar..The example using the average cost base calculation in #1793 (#1783) renders the same result using adjusted cost base method, and the superficial loss rules are as you described, similar to the UK 30 day rules. 

Would have to spend time reviewing the UK rules in more detail to confirm any nuances but definitely sounds like you could leverage off of that as a starting point..

**Comment by MECINC** [comment]
Thanks @LefterisJP .. can you confirm there would be separate selections for each cost base method? You're just combining efforts given the similarities?  Please let me know if you're looking for assistance in any way.
