### ISSUE TITLE
ETH staking rewards show as 'missing acquisition' if you try to sell them

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#5455]
## Problem Definition

When creating a profit/loss report for a Rotki account that just has a beacon node validator generating rewards, and a test transaction to sell just those rewards, then the report will have an error that the ETH rewards don't have a corresponding acquisition.

Expected outcome: the report should not have any errors.

I know this is theoretical at this stage because withdrawals are not enabled but I was just testing it out.

**Comment by LefterisJP** [comment]
Did you enable taxation of rewards before withdrawals?
![2023-01-23_08-53](https://user-images.githubusercontent.com/1658405/213989589-49ee6c24-9ec2-40cf-9ee1-ff8f5a744ab5.png)

**Comment by a7e8** [comment]
> Did you enable taxation of rewards before withdrawals?
> ![2023-01-23_08-53](https://user-images.githubusercontent.com/1658405/213989589-49ee6c24-9ec2-40cf-9ee1-ff8f5a744ab5.png)

That setting is off (same as your screenshot).

**Comment by a7e8** [comment]
Also it's a separate issue but I think the way you're currently calculating rewards should probably change when withdrawals are enabled.

For example if you have a 0x01 withdrawal credential set then I think you'll get automatic partial withdrawals to that address every week. Apparently it won't be a transaction (just a balance change) but I imagine that this is going to be the taxable event (in most cases/countries) rather than the accumulating rewards on the beacon chain every Epoch.

You probably also want to have some option for people that keep 0x00 credentials though (like or similar to the existing functionality).

**Comment by LefterisJP** [comment]
> Also it's a separate issue but I think the way you're currently calculating rewards should probably change when withdrawals are enabled.
> 
> For example if you have a 0x01 withdrawal credential set then I think you'll get automatic partial withdrawals to that address every week. Apparently it won't be a transaction (just a balance change) but I imagine that this is going to be the taxable event (in most cases/countries) rather than the accumulating rewards on the beacon chain every Epoch.
> 
> You probably also want to have some option for people that keep 0x00 credentials though (like or similar to the existing functionality).

This is a different issue and we are aware. Things are gonna be complicated but spec is not yet clear.

**Comment by a7e8** [comment]
This [FAQ](https://notes.ethereum.org/@launchpad/withdrawals-faq#Q-What-is-the-current-proposal-for-daily-withdrawal-limits-post-Shanghai-and-if-the-request-to-withdraw-exceeds-that-limit-what%E2%80%99s-the-rule-to-decide-who-gets-the-chance-on-that-day) answers some of the questions (if the design stays the same).

I'll definitely consider joining Discord. Thanks for reminding me!

**Comment by a7e8** [comment]
Also to fix is the Ethereum transaction that deposits 32 ETH to the beacon chain has the wrong type for the profit loss report. I had to edit it from `send` to `deposit`. Because in its current type of `send` it counts as a disposal (and therefore increases the profit in the P&L).

**Comment by prettyirrelevant** [comment]
Hello @a7e8. The issue you described is expected. 
The reason is that ETH2 is illiquid & locked until withdrawals are open. At this point, they become ETH -- which is liquid and therefore can be sold or traded.

If the above explanation is not clear, there's a detailed thread in our discord explaining this https://discord.com/channels/657906918408585217/1067486965500481546

Closing this issue.

**Comment by a7e8** [comment]
@prettyirrelevant if that's the case then you should remove the rewards from the profit and loss report entirely

**Comment by LefterisJP** [comment]
> @prettyirrelevant if that's the case then you should remove the rewards from the profit and loss report entirely

that's not the case. There is jurisdicions that are taxed even if they can't withdraw. And if you don't want to see it in the PnL there is a setting for this. It won't get mixed with the ETH profit if you don't have "Treat ETH as ETH2 setting on".

**Comment by a7e8** [comment]
@LefterisJP Yes but it's also possible to sell a validator without that being onchain e.g. written contract. I still think you should add the ETH acquired from staking rewards to the accounting if you are also listing it in the P&L no? It seems half-baked in its current state (even if this is a toggle switch).

**Comment by LefterisJP** [comment]
> @LefterisJP Yes but it's also possible to sell a validator without that being onchain e.g. written contract. I still think you should add the ETH acquired from staking rewards to the accounting if you are also listing it in the P&L no? It seems half-baked in its current state (even if this is a toggle switch).

It's not half baked. It's accurate. In that case you sell `ETH2` not `ETH`. Anything other than this approach is half-baked. We distinguish between `ETH` and `ETH2`. One is liquid ETH in the main chain and ETH2 is locked ETH in beacon chain/consensus layer. And in the case you sell a validator OTC you need to not treat those as the same thing.

There has been a long discussion on this in the discord and you were also part of the channel. Feel free to read it.

**Comment by a7e8** [comment]
There is no such thing as ETH2. Listing ETH2 as the asset in the P&L export could lead to confusion.

**Comment by LefterisJP** [comment]
> There is no such thing as ETH2. Listing ETH2 as the asset in the P&L export could lead to confusion.

ETH2 is our identifier for locked ETH. Call it however you want. One is liquid the other is not. It needs to be differentiated. It was called ETH2 originally by the entire community and this is what the identifier was in rotki at genesis and this is the same now. This is not changing. Changing how it looks in the UI or in exports is something we can probably do, but right now exports have the identifiers.

Anyway this discussion is off-topic to the issue at hand. If you have any other questions or suggestions feel free to ask in the discord.
