### ISSUE TITLE
Coinbase API - trade history - error status code: 500 

### ISSUE THREAD

**Issue by ladidan** [rotki/rotki#5517]
## Problem Definition

Can't load trade history from coinbase exchange into rotki via API.
However, withdrawals/deposits/balances are loaded correctly.

Done so far:
- checked coinbase API permissions (all read-enabled).
- waited 24h to repeat procedure for potential rate limiting failure (not sure about coinbase rate limiting policies, though)

## Logs

```
DEBUG rotkehlchen.exchanges.coinbase Greenlet-19: Coinbase API query request_url=/v2/accounts/xxx/transactions?starting_after=xxx
DEBUG rotkehlchen.exchanges.coinbase Greenlet-12: Coinbase API query request_url=/v2/accounts
ERROR rotkehlchen.api.rest Greenlet with id 12345: Greenlet for task 33 dies with exception: Coinbase query https://api.coinbase.com/v2/accounts/xxxx/transactions responded with error status code: 500 and text: {"errors":[{"id":"internal_server_error","message":"An error has occurred. If this problem persists, please visit https://support.coinbase.com for assistance."}]}.
Exception Name: <class 'rotkehlchen.errors.misc.RemoteError'>
Exception Info: Coinbase query https://api.coinbase.com/v2/accounts/xxxx/transactions responded with error status code: 500 and text: {"errors":[{"id":"internal_server_error","message":"An error has occurred. If this problem persists, please visit https://support.coinbase.com for assistance."}]}
Traceback:
   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "rotkehlchen/api/rest.py", line 298, in _do_query_async
  File "rotkehlchen/api/rest.py", line 930, in _get_ledger_actions
  File "rotkehlchen/history/events.py", line 105, in query_ledger_actions
  File "rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
  File "rotkehlchen/exchanges/exchange.py", line 461, in query_income_loss_expense
  File "rotkehlchen/exchanges/coinbase.py", line 840, in query_online_income_loss_expense
  File "rotkehlchen/exchanges/coinbase.py", line 385, in _api_query
```

-->

### System Description

Operating system: ubuntu 22.04
Rotki version: 1.26.3

**Comment by LefterisJP** [comment]
Hey @ladidan, thank you for using rotki! From a first look at the logs this is a coinbase problem as per the error message in the logs (internal server error). I think you need to contact their support.

**Comment by ladidan** [comment]
thanks for your quick response! will try to contact them.
just saw there's been a very recent API version update - potentially related?!

![grafik](https://user-images.githubusercontent.com/46406043/215457351-2844b271-0527-4960-b8da-b59173b93df8.png)

**Comment by LefterisJP** [comment]
> important footnote: the transactions I'm looking for and which won't show up were made via advanced trade
Instead, no cb trades show up at all.

Hey @ladidan
This is a different issue and it's since the new "advanced trade" thing by coinbase is not yet supported: https://github.com/rotki/rotki/issues/4663

**Comment by ladidan** [comment]
> > important footnote: the transactions I'm looking for and which won't show up were made via advanced trade
> > Instead, no cb trades show up at all.
> 
> Hey @ladidan This is a different issue and it's since the new "advanced trade" thing by coinbase is not yet supported: #4663

Appreciate the hint!

Will report back as soon as the API will be supported/fixed

**Comment by LefterisJP** [comment]
So since there is no more information and this is about coibase advanced trade I am closing the issue and refer you to #4663
