### ISSUE TITLE
Differenciate in the UI the selected main currency for currencies with the same icon

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5526]
## Abstract

At the moment if you select a currency like canadian dollar is not possible to know from the dropdown if you are using canadian dollar or any other currency with $ as a symbol

## Motivation

Allow the user to know what currency is being used not leading to confusion

## Specification

Maybe the hover could show it or be marked in the dropdown

**Comment by kelsos** [comment]
@yabirgb there is already a tooltip there in the latest develop.

It has already been added by @lukicenturi with #5493

**Comment by yabirgb** [comment]
@kelsos True thanks! I checked 1.26.3 and didn't in develop. Thank you both
