### ISSUE TITLE
Missing Acquisitions: Options to handle the missing acquisition

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#5546]
## Abstract

I have some missing acquisitions when doing the PnL report. Some of them are staking rewards, some are dust (extremly small), some might be a scammy token I received. I would like to deal with these kind of scenearios directly in the missing acquisitions screen.

## Motivation
Quality of life improvement.

## Specification

Give the user options to deal with missing acquisitions directly in the "missing acquisitions" screen.
Like for example: 
- define it as staking reward
- accept it --> rotki setting a buy price of 0$ (give the user a warning what this means in regards of taxing, but for dust should be ok)
- Ignore token --> put token on ignore list.

**Comment by kelsos** [comment]
It sounds useful. I will initially put a frontend tag since some of them can be done in the frontend without any API changes. I am not so sure about the first one, we will have to check.
