### ISSUE TITLE
Ability to support WSTETH Maker Vaults

### ISSUE THREAD

**Issue by osouthgate** [rotki/rotki#5576]
## Abstract

When moving an ETH vault to a WSTETH vault on Maker, it no longer appears in the app. After a message in the discord group it appears the app does not currently support new vault types.

The requirement is to be able to support other vault types, specifically WSTETH

## Motivation

I would like this to be implemented as it allows any rotki user who has makerdao vaults to see the full details within the defi section of the rotki app as currently these are not visible to users.

**Comment by LefterisJP** [comment]
Shoudl be done with https://github.com/rotki/rotki/pull/5601 and will be in 1.27.1
