### ISSUE TITLE
Allow addition of EVM transaction by hash and association with an address

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5582]
## Abstract

rotki is trying to pull as many relevant transactions for your addresses as possible. It's possible though that some transactions that involve your address can be missed. Especially if there is no value or token transfer directly from or to the address. We need to provide a way for users to correct this.

## Motivation

Find and decode transactions related to an address that rotki does not automatically find. Most notable example are the liquidation transactions for many protocols which are not detected since they contain no identifiable information about the user's address. But if the user has been liquidated they know it, and with this solution they can at least fix it by requesting the transaction directly by hash.

https://github.com/rotki/rotki/issues/5250

## Specification

- New endpoint to add a transaction by: `evm chain`, `tx_hash` and `associated_address`
- In the backend this will simply pull the transaction and associate it with the `associated_address`, get its receipt and decode all logs.
- In the frontend in the UI, not sure where the best place to place it would be. Probaly somewhere in the EVM transactions?

**Comment by kelsos** [comment]
@lukicenturi after the backend part is merged here the frontend work will be up for picking

**Comment by kelsos** [comment]
This is now on @rotki/frontend to pick up
