### ISSUE TITLE
Convert etherscan api key missing warning to separate websocket message

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5611]
## Abstract

At the moment we the etherscan key missing as a legacy warning which is easily missed by the user. If the user does not see it or does not take action on it then they are going to have a terribly slow experience in rotki as we do depend on etherscan for querying transactions.

Multiple times, users have come in rotki and said that it's too slow querying only to find out they never added an etherscan key.

## Motivation

Improve user experience.

### Backend
- [x] Create a new websocket message type as per the specification above
- [x] Replace the etherscan and optimistic etherscan api keys missing messages with usage of the new message

### Frontend
- [ ] In the frontend catch this message and direct the user to take action with as much hand-holding as possible. Perhaps in a menu with steps?
    - Step 1: Point them to the proper etherscan signup page to create the account and get the api key. Include link in our docs where we explain it?
    - Tell them when they have the key to press "Next" ...
    - Take them to the place where it should be input (or perhaps have it input from the same dialog?)

**Comment by yabirgb** [comment]
Issue completed in https://github.com/rotki/rotki/pull/5897
