### ISSUE TITLE
Can't delete custom inactive RPC node

### ISSUE THREAD

**Issue by kolya182** [rotki/rotki#5612]
## Problem Definition
Trying to delete custom inactive Ethereum RPC node gives an error

https://user-images.githubusercontent.com/3277207/219017262-6189d1bd-c518-4cc3-8172-e35c65672718.mov

## Logs

<img width="1059" alt="Screenshot 2023-02-15 at 12 38 29 PM" src="https://user-images.githubusercontent.com/3277207/219017339-ff61ba87-7adc-4cb1-8d73-ae4b761c0132.png">

-->

### System Description

Operating system: 
Rotki version:

**Comment by yabirgb** [comment]
Hello! Thanks for the report. Will check locally to see what is happening

**Comment by yabirgb** [comment]
@kolya182 I've tried to reproduce but with the cases I've tried I can't reproduce the error. Are you in discord so I can request more info from the app? https://discord.gg/aGCxHG7

there you can find me in the rotki team members

**Comment by LefterisJP** [comment]
There has been no contact from the user for over a week. Closing the issue as can't reproduce.
