### ISSUE TITLE
Sign In failed - Heartbeat error

### ISSUE THREAD

**Issue by figofinozeros** [rotki/rotki#563]
## Problem Definition

When trying to setup an account and after defining a username and password I get the message:
Sign In failed 
HeratbeatError: Lost remote after 30000 ms

Also got a Javascript error when closing the application, see:
https://mobile.twitter.com/FigoFinozeros/status/1204424076200206336

I searched for the .log file within the folder using the search function, but couldn't find it.

### System Description
Win10
Rotki 1.0.5

**Comment by LefterisJP** [comment]
Hey @figofinozeros, thank you for trying Rotki! Anything not Linux has a lot of challenges but let's try to debug this together. For my windows machine Rotki 1.0.5 works fine.

Can you go to `C:\Users\YOURUSERNAME\%APPDATA%\rotki\logs` and get the `logsrotki_electron.log` file and inside the `logs` directory the `rotkehlchen.log` ?

**Comment by figofinozeros** [comment]
Hey Lefteris, thanks for the quick reply! I have attached both files. The rotkehlchen log is empty.
[logsrotki.zip](https://github.com/rotki/rotki/files/3946317/logsrotki.zip)

**Comment by LefterisJP** [comment]
Hmmm that's strange. Can you try calling the python backend directly from a windows terminal window? It's here: `C:\Users\Alex\Downloads\rotki-win32-x64-v1.0.5\rotki-win32-x64-v1.0.5\resources\app\rotkehlchen_py_dist\rotkehlchen-1.0.5.dev92+g74a9d11-windows.exe --zerorpc-port 4242 --logfile C:\Users\Alex\AppData\Roaming\rotki\logs/rotkehlchen.log`

**Comment by figofinozeros** [comment]
Got the following: 
![1576001227743234663371010166128](https://user-images.githubusercontent.com/17723746/70555999-4ecc5800-1b80-11ea-883a-6416843c2ee5.jpg)

**Comment by figofinozeros** [comment]
Hey Lefteris, I no longer have the issue, even after restarting. Can you imagine what the issue was?

**Comment by LefterisJP** [comment]
So let me see if I understand correctly.

You run it two times. The first time you ran it you get a path not found error and the second time it runs succesfully. Both commands seem identical when I check them with the eye.

Is that correct?

Have you tried to run the full rotki executable once more to see if it runs succesfully on a second time?

**Comment by LefterisJP** [comment]
> Hey Lefteris, I no longer have the issue, even after restarting. Can you imagine what the issue was?

From this it seems like you tried to do that and Rotki does indeed work sucesfully, right?

Hmm this is strange, but I have a working theory which I will have to test.

**Comment by figofinozeros** [comment]
The "path not found" was due to the fact that I had moved the rotki folder to a different folder temporarily. When I moved it again in the download folder the command line executed successfully.

I now have the folder in C:\program files\... and it runs without the issue.

If I can of any further help please just ask.

Thanks again for your support Lefteris!

**Comment by LefterisJP** [comment]
@figofinozeros my pleasure!

I had the theory that if it's the first time Rotki runs and the `%APPDATA%` logs directory does not exist there may be a crash at first but I just tested this and that seems to not be the case.

So wait, what did you do between the time it failed and the time it properly worked? The rotki.exe must be executed from within the directory it was unzipped in. Did you by any chance move only the executable out?

**Comment by figofinozeros** [comment]
No, always executed it within the folder. Perhaps it had something to do with Avast (Anti Malware). It did check the .exe because it was not known and uploaded it in their cloud. 

.exe was still in the folder but perhaps there was some baclground process from Avast still operating and limiting some function of Rotki.

**Comment by LefterisJP** [comment]
Hey @figofinozeros!

So question. Is all good with you and you can use Rotki properly? If yes then perhaps I can close this issue and reopen if more info can be found or make another issue for a more specific problem?

**Comment by figofinozeros** [comment]
Yes, no further problems regarding this issue, thanks Lefteris!
