### ISSUE TITLE
Create a key-value cache for global DB

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5631]
## Abstract

At the moment the `general_cache` table in the global DB is the only cache table. Its purpose is for multiple key-value combinations which are not unique. So it's an association cache. The primary key **is not** the key but the key-value pair. Allowing for multiple values per key. So it's more like a multu-value cache.

We also have cases like for the ilk_registry, and other, where the cache should really be unique per key but we just use the same table due to lack of another one.

The problem there is that by using the wrong type table for a unique-key cache is we have to clean it if we use general cache before. If we don't we will end up having multiple values per key, with new ones not replacing old one, but just adding on top growing the DB size.

## Task

Add a global DB upgrade (should not affect assets, so it should be included as okay in the asset updates) that adds a new table and moves the cache data that should be unique per key there.

For example:

```
CURVE_POOL_TOKENS0x9f4A88da14F2b6DBc785C1Db3511A53B8F342bde|0x8b921e618dD3Fa5a199b0a8B7901f5530D74EF27|1676727187
CURVE_POOL_TOKENS0x9f4A88da14F2b6DBc785C1Db3511A53B8F342bde|0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490|1676727187
CURVE_POOL_ADDRESS0x04c90C198b2eFF55716079bc06d7CCc4aa4d7512|0x04c90C198b2eFF55716079bc06d7CCc4aa4d7512|1676727187
```

`CURVE_POOL_TOKENS` makes sense to use the multivalue cache as it has one mapping per token, showing which tokens a pool hs.

But `CURVE_POOL_ADDRESS` does not really need to do that. It's just a list of all curve pool addresses.

**Comment by Juyotal** [comment]
Hey @yabirgb this is my git!
