### ISSUE TITLE
Cowswap Trades Integration

### ISSUE THREAD

**Issue by celkacelka** [rotki/rotki#5639]
## Abstract

To integrate Cowswap EVM decoders for Eth Mainnet

## Motivation

Many users have it and we have received partial grant for it

## Specification

- [ ] implement decoders in the backend
- [ ] implement necessary frontend changes

**Comment by LefterisJP** [comment]
Reopened. Not ready yet since the frontend is not done. Handing it over to frontend for changelog + frontend.
