### ISSUE TITLE
Add different tax calculation methods (FIFO/LIFO/HIFO) 

### ISSUE THREAD

**Issue by Buttaa** [rotki/rotki#566]

**Comment by LefterisJP** [comment]
Hey @Buttaa!

- FIFO is the current method.
- For LIFO there is already an issue: https://github.com/rotki/rotki/issues/44

Nobody had asked for HIFO before. Do you mind if I turn this issue into an issue for HIFO?
Is there any other options you would like to see?

**Comment by Buttaa** [comment]
I see. Primary focus was LIFO actually, I don't think there's demand for HIFO tbh.

**Comment by LefterisJP** [comment]
All right. If people ask another issue will be made then! Thank you for your feedback!
