### ISSUE TITLE
Cloudflare Tunnel + Rotki = Square glyphs instead of icons

### ISSUE THREAD

**Issue by rursache** [rotki/rotki#5666]
## Problem Definition

I'm using Cloudflare Tunnels to expose some of my services to my `domain.tld` -> `rotki.domain.tld`
Everything seem to work fine except **all** icons are replaced by blank squares (i think the font is not loading?)

![issue](https://i.imgur.com/7xOSmBd.png)

If I access rotki using the local ip, it works as expected.
It's the first time I'm seeing this error while having around 20 other services using Cloudflare Tunnels without issues.

## Install details
Rotki is installed using docker with the following command:
```sh
docker run -d \
  --name rotki \
  --restart=unless-stopped \
  -p 3355:80 \
  -e TZ=Europe/Bucharest \
  -e ROTKI_ACCEPT_DOCKER_RISK=1 \
  -v /home/USER/.rotki/data:/data \
  -v /home/USER/.rotki/logs:/logs \
  -v /home/USER/.rotki/config:/config \
  rotki/rotki:latest
```

### System Description
**Operating system**: Ubuntu Mate 22.04
**Docker**: 23.0.1, build a5ee5b1
**Rotki version**: 1.27.1 (it also happened on 1.27.0 and possibly earlier too but I didn't test old versions)

**Comment by kelsos** [comment]
Hey, @rursache I have not tried it in such a setup, could you do a quick check in the console on what the error might be? the glyph font should be packaged and shipped in the application. If there is a loading error it would be helpful to see what fails.

**Comment by rursache** [comment]
@kelsos thanks for your quick reply

funny thing is that now trying to open the page again, it seems to all work ok even though i had issues yesterday and 10 minutes ago. same browser, same network, same instance, same everything.

i will update this issue with the chrome logs when i catch the issue again, please let it open for a bit

**Comment by kelsos** [comment]
Sure, let me know if you can get any more information.

**Comment by kelsos** [comment]
@rursache I am gonna close the issue, and if you encounter any issues again we can re-open it.

**Comment by rursache** [comment]
@kelsos its happening again. the console is full of errors and logs:

![errors](https://i.imgur.com/whc6T22.jpg)

it seems to be something cache related as opening the page in incognito fixes it. or clearing cache/cookies for the domain
