### ISSUE TITLE
Apply optimizations to the databases

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5671]
Different optimizations can be applied to the database in order to improve the size of it and other parameters. One of such optimizations is the use of the `vacuum` command that cleans unused pages https://www.sqlite.org/lang_vacuum.html after doing deletions to the database.

There might be other optimizations worth to research and apply.

We should trigger this task periodically to improve the usage of resources in the system

**Comment by LefterisJP** [comment]
This is done with v1.30 upgrade. The VACUUM I mean.
