### ISSUE TITLE
Support curve gauges

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#5676]
## Abstract

Currently rotki does not decode curve gauges. It handles the deposit as "Send".

Example curve gauge:
[Curve.fi: sUSDv2 Liquidity Gauge](https://etherscan.io/address/0xa90996896660decc6e997655e065b23788857849)

## Motivation

Improve features and user friendliness of rotki.

## Specification

Take care of curve gauges to decode them correctly.

- [x] Periodically query and store in general cache all curve gauges.
- [x] Decode deposit in gauge events (note: deposits can be done on behalf of a different address than the caller)
- [x] Decode withdraw from gauge events
- [x] Decode claim rewards events (note: rewards can be claimed to a different address than the caller)

**Comment by LefterisJP** [comment]
We need to do the same for convex also

**Comment by LefterisJP** [comment]
Hey @nebolax have you also done this:

> Decode deposit in gauge events (note: deposits can be done on behalf of a different address than the caller)
