### ISSUE TITLE
Decode curve trades

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5677]
At the moment we provide decoders for curve pool events but not for trades.

## Task

Add decoders for trades made using the curve contracts and add test for them

Decode trades made via curve swap router https://etherscan.io/address/0x99a58482bd75cbab83b27ec03ca68ff489b5788f

**Comment by ajainuary** [comment]
Hi,
I would be interested in taking this one up, I'll create a function in [rotkehlchen/chain/ethereum/modules/curve/decoder.py](https://github.com/rotki/rotki/blob/develop/rotkehlchen/chain/ethereum/modules/curve/decoder.py) to decode the ```TokenExchange``` event emitted in a swap via Curve. If you don't mind me taking 3-4 days, could you assign this PR to me?

**Comment by nebolax** [comment]
Assigned.

Note: this is an issue, not a PR :stuck_out_tongue:
