### ISSUE TITLE
Gather decoding modules capabilities

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#5680]
## Abstract

Currently it is hard for the users to know which protocols are supported by rotki, which parts of the protocols are supported, etc.

We should gather this information in some central places (like website, usage guide, etc.)

## Motivation

When users will have this information accessible they will be more certain on what to expect from rotki.

## Specification

As mentioned above this information should be gathered in some central places like our website.

As for where to store it and how to gather the current idea is to have a dedicated documentation file in each module + a small script that would gather these documentations.

The modules' documentations should probably have a list of bulletpoints with the current capabilities, but this entire issue needs further discussion before getting implemented.

**Comment by nebolax** [comment]
To provide more information to both users and us maybe in each module in addition to the list of current capabilities we can also have a list of things that are not currently supported. This will:
1. Give users more clear perspective
2. Help us to keep in mind what remains to be done for each module

**Comment by LefterisJP** [comment]
We should generalize this for rotki's capabilities/features broken down to the chain/module level but also include all other stuff we allow.

At the moment there is no such master list. We can even simplify it and write it by hand, and then just have it as part of the development process (just like changing the changelog), to update this list.

**Comment by lukicenturi** [comment]
We have scripts in the app to generate the JSON,
and then it's showed in the website in "Integration" page
