### ISSUE TITLE
Support Kraken's staking feature

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#569]
## Description

Kraken has [introduced](https://blog.kraken.com/post/3299/staking-xtz-available-on-kraken/) crypto staking from within its interface.

Rotki should also be able to support it provided there is a way to access this data from their [API](https://www.kraken.com/features/api#private-user-data).

Premium only.

Related to: https://github.com/rotki/rotki/issues/473

## Task

Support staking from inside Kraken

**Comment by LefterisJP** [comment]
A user from twitter +1ed this issue: https://twitter.com/AmryikesName/status/1387748612738850821

Let's try to push it a bit. I don't wanna press it for v1.17.0 but I can see it included in v1.18.0

**Comment by LefterisJP** [comment]
It's not a really hard issue. What needs to be done is:

### Backend


- Either add a new `query_staking()` method in the exchange interface and implement on kraken or make it for now only for Kraken. Perhaps since only kraken has it and we support it we just do the latter. No need to generalize when not needed.
- Create new api endpoint, premium only, to query kraken staking for a given period. This should return:
    * list of staking events: Each event would be a staking earning even for a given asset on a given time
    * total_earned -> a mapping of asset to amount/usd value balances of total earned in the given period

### Frontend

A staking view where user can see all the events and the total earned. User can also filter them by asset or time range.

**Comment by yabirgb** [comment]
@LefterisJP Do they provide information about staking in an existing endpoint? I couldn't find information about it in the docs https://docs.kraken.com/rest/ Also it mentions that is not avaible in the mobile app because they don't have an API (I believe to stake/unstake)

**Comment by LefterisJP** [comment]
We are fortunate in this one as I can test it myself. I have used kraken staking for multiple coins and have active real life data for this. So you could say I have a personal interest in also seeing this implemented.

If I am not mistaken it's  part of their ledgers api: https://docs.kraken.com/rest/#operation/getLedgersInfo

but not 100% sure.
