### ISSUE TITLE
Decode failed transactions + filter for Tx burned gas only

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#5695]
Usually I find none decoded transactions by spotting a TX in rotki with only burned gas. This most likely means something was not decoded at all. The only other case I found was when a transaction failed (e.g. due to low gas).

To easily find these not decoded TX's a filter for transactions with only "burned gas" in the decoder would be useful. And to avoid a false positive the failed transactions could be deocded to exclude them from the filter.

**Comment by LefterisJP** [comment]
> Usually I find none decoded transactions by spotting a TX in rotki with only burned gas. This most likely means something was not decoded at all. The only other case I found was when a transaction failed (e.g. due to low gas).
> 
> To easily find these not decoded TX's a filter for transactions with only "burned gas" in the decoder would be useful. And to avoid a false positive the failed transactions could be deocded to exclude them from the filter.

Exactly. The only reason for a transaction to only burn gas is if it's a failed transaction. Otherwise, probably something did not get decoded.

We can consider a filter for this, that's true.

**Comment by LefterisJP** [comment]
Oh this is done now and it's coming in 1.35.0
