### ISSUE TITLE
Decode deposits to Curve.fi: (Deposit USDN)

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#5696]
Deposit to curve pools should decode and I guess this is a pool not a gauge (which is still WIP).

Deposit to Curve.fi: Deposit USDN are not decoded.
https://etherscan.io/address/0x094d12e5b541784701FD8d65F11fc0598FBC6332

Request: Decode it.

![image](https://user-images.githubusercontent.com/36508484/221869535-7da90605-0b1d-49ea-b390-ea46619f198b.png)

**Comment by LefterisJP** [comment]
Curve pool deposits **should** be decoded. So I would take this as a bug if it does not. Can you give me a transaction hash as the link you gave is for a contract.
