### ISSUE TITLE
Balancer decoding: not deposited assets declared as "Receive wrapped"

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#5697]
When Depositing into balancer the not deposited and received assets are declared as "received wrapped" even they are not wrapped tokens.
See screenshot:
![image](https://user-images.githubusercontent.com/36508484/221887736-a962f093-d406-4300-89e9-db8054774715.png)

I can provide details in discord. PM me.

**Comment by LefterisJP** [comment]
This is not a bug. Receive wrapped is correct here, as any pool token is considered a wrapped token as far as events decoding is concerned.

**Comment by LefterisJP** [comment]
Talked with the user and he explained that it's the  "yellow ones" in the example that are the problem. Which are not a BPT token, but some kind of dust/extra sent back during deposit. And this should be clasified probably as withdrawal

**Comment by xtc0r** [comment]
I found a similar looking transaction but couldn't verify rotki has the same issue here as I just have a rotki live system and don't wnat to mess around with it.
https://etherscan.io/tx/0x22162f5c71261421db82a03ba4ad13725ef4fe9639c62bf6702538f980fbe7ba
