### ISSUE TITLE
Support custom swap events in accounting

### ISSUE THREAD

**Issue by prettyirrelevant** [rotki/rotki#5717]
## Problem

Currently, custom swap events are ignored during accounting because:
1.  there's no default accounting setting to handle it
2. the accountant for the specified counterparty does not support it.

Discussion is here -> https://discord.com/channels/657906918408585217/683245846070165504/1080865282396004423

## Specification

- Create a default accounting setting to handle such cases/scenario(swaps, etc.)

**Comment by nebolax** [comment]
Note: "custom swap events are ignored during accounting" is not true. Only swaps that have incorrect counterparty set get ignored.

> Create a default accounting setting to handle such cases/scenario(swaps, etc.)

There already is a default setting. What needs to change (and I would say to change not only for swaps, but for other events as well) is that if there is no setting found for a particular counterparty -- fallback to default settings.

**Comment by LefterisJP** [comment]
Custom swap events means any counterparty so the description is correct.

For swaps it should fall back to default settings, but for other events it depends on the type of event

**Comment by yabirgb** [comment]
Closed in https://github.com/rotki/rotki/pull/5768
