### ISSUE TITLE
Adding historic price with same `timestamp, toAsset, and fromAsset` doesn't replace the price of old entry.

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#5741]
## Problem Definition

For the add historic price endpoint, adding the new entry with `timestamp`, `toAsset`, and `fromAsset` that already exist, doesn't update the price of the entry.

Can we make it, so that the new entry with the same payload (except the price), updates the already existing entry price?
I see that `adding the latest price` uses this mechanism.

(Why not just use the edit endpoint?) Sometimes the front end cannot make sure if the entry already exists or not.
In doing so, we need to fetch all saved historical prices. By implementing the mechanism I said in the paragraph above, we can prevent unnecessary fetching for all saved historical prices.

This is needed in order to finish #5733, so can this be put on `bugfixes`?

**Comment by LefterisJP** [comment]
Currently it's `INSERT OR IGNORE`. This is why this happens. The idea is if you wanted to edit an entry you just call the edid endpoint. Should not be hard to change though. 

```python
                write_cursor.execute(
                    """INSERT OR IGNORE INTO price_history(
                    from_asset, to_asset, source_type, timestamp, price
                    ) VALUES (?, ?, ?, ?, ?)
                    """,
                    serialized,
                )
```

The code, tests, docs of the functions andthe api would also need changing.

**Comment by LefterisJP** [comment]
This is done by #5756 @lukicenturi, you can carry on with your frontend work
