### ISSUE TITLE
Make sure that Docker image can properly shutdown

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#5757]
## Problem Definition

While trying to set up the proxy I noticed that the proxy didn't exit cleanly. 
Instead, it exited with (code=137). 

This might be because there is an infinite loop (intentional) monitoring the subprocesses, and this loop only exits if one of the subprocesses stops running.

This will cause the script to exit with code 1.

https://github.com/rotki/rotki/blob/53d36bc1f5aa0ff64fcfaf21f0ba6ca005a032eb/packaging/docker/entrypoint.py#L173

## Requirements

- Handle `SIGINT`/`SIGTERM` normally and exit cleanly (code=0)
- Make sure that if the subprocesses die we exit (code=1)

**Comment by yabirgb** [comment]
Closed by https://github.com/rotki/rotki/pull/5777
