### ISSUE TITLE
New endpoint that return all `evm chains`

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#5781]
We need new endpoint that return all `evm chains` so we don't hardcode anything in frontend.
I guess an endpoint that return the data from the `ChainId` struct:
```
[
  {"chain_id": "1", "name": "ethereum"},
  {"chain_id": "10", "name": "optimism"},
  {"chain_id": "56", "name": "binance"},
  {"chain_id": "100", "name": "gnosis"},
  {"chain_id": "137", "name": "matic"},
  {"chain_id": "250", "name": "fantom"},
  {"chain_id": "42161", "name": "arbitrum"},
  {"chain_id": "43114", "name": "avalanche"},
  {"chain_id": "42220", "name": "celo"},
]
```

**Comment by kelsos** [comment]
Any reason why we can't keep the chain id unquoted?

Are we gonna hit the [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)?

**Comment by LefterisJP** [comment]
> Any reason why we can't keep the chain id unquoted?
> 
> Are we gonna hit the [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)?

yeah let's use the int. I don't think we run into any such danger

**Comment by LefterisJP** [comment]
backend part should be done by #5782
