### ISSUE TITLE
Decode curve swap router trades

### ISSUE THREAD

**Issue by thegodfatherbeeearth** [rotki/rotki#5802]
## Abstract

Decode trades made via curve swap router https://etherscan.io/address/0x99a58482bd75cbab83b27ec03ca68ff489b5788f

## Specification

Not sure if #5677 will be sufficient to decode curve swap router trades, so need to make sure that if a user uses this router their trades are decoded correctly.

**Comment by nebolax** [comment]
Will move info from here to #5677
