### ISSUE TITLE
Add github as an alternative docker repository

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#5803]
## Abstract

We have applied for docker's DSOS but in the meanwhile check if we can start having github as an alternative repository for images.

## Motivation

Make sure that we have a documented alternative where users can also access the images just in case anything happens.

## Specification

- CI should push to both repositories

**Comment by azerv1** [comment]
Now that it's sponsored, Is this still needed?

**Comment by kelsos** [comment]
> Now that it's sponsored, Is this still needed?

Since they rolled back the changes that triggered the creation of this issue and we are also sponsored I would say that it's not need. 

I am gonna close the issue.
