### ISSUE TITLE
Add more information for curve and convex pools and gauge addresses

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#5809]
## Abstract

Show names for curve pools, curve gauges and other addresses of protocols where we can give users more information.

In case of curve pools / gauges we should generate the name from symbols of tokens that are used for a pool.

**Comment by LefterisJP** [comment]
This is specific to curve and maybe convex. For each protocol it's a different action that needs to be done so can't have a generic issue.

**Comment by LefterisJP** [comment]
## Information

I will write in this issue stuff that should have been researched and known about curve and which can help us enrich information, for pools and gauges but also for their underlying tokens and more. These information can help both in decoding transactions but also in accounting for them. There you canso find names.

### Metaregistry

Curve has the on-chain metaregistry. It's "one registry to rule them all": https://github.com/curvefi/metaregistry.
Most of the stuff about curve, its pools and gauges can be founde querying it.

### Curve.fi api

Curve has its own api. https://github.com/curvefi/curve-api

Get all gauges on all chains: https://api.curve.fi/api/getAllGauges

Also these endpoints have everything (including gauges) (sorted by chain etc)
api.curve.fi/api/getPools/[chainId]/[main|factory|crypto|factory-crypto]

For example
 https://api.curve.fi/api/getPools/ethereum/factory

## Questions and answers

- There seems to be always 1 pool for 1 gauge, while the code allows multiple. What gives? When can that happen?
- Yes it's possible. Has not happened yet for ethereum mainnet but it can and it has already happened for other chains. A gauge can be killed and replaced by another one, in which case the mapping keeps both old and new.

- What is the source of truth?
- Metaregistry

## What should we do

If curve.fi api is less calls use it, but always be able to fallback to chain queries. Probably meta-registry.

Get all information we need from the registry/api. With a quick look it seems we can get:

- Pool name
- Pool address
- Pool underlying tokens
- Meta pools like LUSD3CRV
- Price of a pool LP token (we actually query those in price queries already)


Utilize as many as we can
