### ISSUE TITLE
Automatically merge vcr cassettes

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#5819]
## Abstract

Currently we tend to often forget to merge vcr cassettes branch when a pr is merged in the main repo. This can be fixed by setting up an automatic cassettes merge.

## Specification

I browsed internet and this seems to be possible to do. We should make a github action that would run on pr merge event, check whether there is a corresponding cassettes branch, and if there is one, merge it.

**Comment by kelsos** [comment]
Yes, this should be doable with a custom action. I have already mentioned this to @LefterisJP before.

Is the only thing required from the custom action to auto-merge?

**Comment by nebolax** [comment]
> Is the only thing required from the custom action to auto-merge?

One awesome feature that I can think of would be to automatically rebase unmerged branches when something is merged to develop/bugfixes. But not sure whether it will be worth doing it.

@yabirgb @prettyirrelevant I don't think we have any other thing that could be needed here, right?

**Comment by prettyirrelevant** [comment]
> One awesome feature that I can think of would be to automatically rebase unmerged branches when something is merged to develop/bugfixes. But not sure whether it will be worth doing it.

Not sure it's worth doing since conflicts might exists in certain cases. 


> I don't think we have any other thing that could be needed here, right?

I think that's sufficient. Keeping it simple ;)

**Comment by kelsos** [comment]
Just for clarification here, the PR branch name and the cassette branch name would match?

**Comment by nebolax** [comment]
Yes, they are always the same

**Comment by kelsos** [comment]
OK I will create the repo and bootstrap the action later today then.

**Comment by kelsos** [comment]
I created the repo [here](https://github.com/rotki/action-cassette-deck) I am gonna setup the initial stuff and then start building the action

**Comment by LefterisJP** [comment]
This is done
