### ISSUE TITLE
Export addresses, blockchain labels and tags

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#5822]
## Abstract

**Problem**:  How to get a tax professional exposed to all one's Rotki addresses, accnts, blockchains, etc. _without_ having to share one's Rotki database plus DB decryption key with them.

## Motivation

As @LefterisJP and @A2be have both noted in previous years, it can be hard to impossible to get a tax professional willing to use (or even try) Rotki.  Thus, a Rotki user with all of their crypto accnts/addresses/names_of_accnts/etc. already input into Rotki would like to simply ask Rotki to spit out a full list so one can give the tax professional an accurate list of all ones addresses/accnts.  These could be in a .csv format, or other if useful.
The tax professional will typically, in this use case, use their own tools for running client addresses/accnts against chain history to determine blockchain activity, and generate taxable gains/losses info for the particular tax jurisdiction.

## Specification

Add a feature to Rotki to _EXPORT_ **all** of the info that the use inputs to Rotki to configure it for use, but none of the on-chain wonderful xaction data that Rotki finds doing its Rotki things on whatever subset of blockchains that Rotki knows about.  

Best of course would be user-configurable (which accnts; which accnt names; which blockchains; which accnt tags; include a list of CEX exchanges used, or not; etc.)

---------------------------

NOTE:  with this feature in place, it would ALSO support the use case of transferring (a subset, or all of) one's Rotki info to a new Rotki instance, without sharing one's entire Rotki database and DB decryption key, and multi-year history, notes, etc..  This might be when one wants a clean start on Rotki, and want to deprecate some of the older historical data, or accnts.  
Or, this might occur when sharing with a spouse whom one would like to become Rotki-literate, and hope would keep their own Rotki instance up and current going forward, but get them a start with various crypto accnts etc. that the couple owns together.  The spouse would conceivably keep their own Rotki DB encryption/decryption key stored away in the spouse's own password manager.

For the latter two use cases, it would be good to have an
**Additional feature**:  Rotki be able to "read" this exported file and _IMPORT_ the accnt nos, names, tags, xpub nos, etc. into a fresh new Rotki instance.

Could also support the Rotki-curious tax professional who might someday want to investigate why their one particular client likes Rotki so much, and wishes their tax professional would become Rotki-ized.  :)

**Comment by LefterisJP** [comment]
The tax professional part is irrelevant. So what you want is a list of:

- Addresses tracked per chain
- Labels
- Tags
- Exchange names (not export api keys I suppose).

Right? I need to as so to keep the specification simple, small and to the point.

**Comment by A2be** [comment]
> The tax professional part is irrelevant. So what you want is a list of:
> 
> * Addresses tracked per chain
> * Labels
> * Tags
> * Exchange names (not export api keys I suppose).
> 
> Right? I need to as so to keep the specification simple, small and to the point.

That would work for me!

I added the tax professional  bit 'cause that is what motivated the use case for me, and moreover, your "Feature add" Github template asks for the motivation explicitly.

**Comment by lukicenturi** [comment]
Done here https://github.com/rotki/rotki/pull/9027
