### ISSUE TITLE
Work with new ENS contracts

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#5824]
## Abstract

ENS upgrades some of their contracts, and thus we should update our code. Related tweet: https://twitter.com/nicksdjohnson/status/1640650011502419971

## Specification

- [ ] One place that will definitely need updating is the ENS decoder https://github.com/rotki/rotki/blob/7d65cb6925c558c962b651d7263ea50506b63553/rotkehlchen/chain/ethereum/modules/ens/decoder.py#L37 . We should support both old an new registar controllers.
- [ ] Check if any other place will need to be touched, but probably decoder is the only place.

**Comment by LefterisJP** [comment]
Addresses are here. Any changesshould also go in 1.28: https://github.com/ensdomains/ens-contracts/pull/236
