### ISSUE TITLE
Support all EVM networks

### ISSUE THREAD

**Issue by froid1911** [rotki/rotki#5833]
## Abstract

Ethereum gets more and more decentralized and transactions are all around the different networks. In 2023 its not enough to track just the mainnet and optimism. Instead rotki should track all configured EVM compatible chains.

## Motivation

This feature should be addressed because its super important to track the entire ecosystem and not only the mainnet (and optimism). More and more defi protocols move to Arbitrum, Polygon and something else in order to be more attractive to user because of cheap gas fees.

## Specification

- Rotki should provide an Interface were EVM compatible chain RPC endpoints can be configured
- Rotki should import all transactions from those chains
- Rotki should show them similar to the current Mainnet/Optimism approach

**Comment by LefterisJP** [comment]
Hey Frank thanks. But such a generic issue does not make sense and is not actionable for us.

We have issues per chain. Follow them to see when we implement those.

Polygon: https://github.com/rotki/rotki/issues/2526
Arbitrum: https://github.com/rotki/rotki/issues/3420

Most probably polygon will come first.
