### ISSUE TITLE
When you have a manual balance + a blockchain balance, /api/1/balances reports infinitely growing money

### ISSUE THREAD

**Issue by Zorlin** [rotki/rotki#5847]
## Problem Definition

I'm writing a simple tool - https://github.com/Zorlin/rotki-balancer - which polls the API for balances.

Weirdly, every time I run it my total value increase by tens of thousands of dollars in the script, despite the script having no memory.

Adding ANY sort of item to Blockchain Balances consistently causes the API to return higher and higher values for anything in Manual Balances.

## Logs

Will provide via DMs.

### System Description
Operating system: Ubuntu 22.04 (amd64) + macOS (Apple Silicon)
Rotki version: 1.27.1

**Comment by Zorlin** [comment]
I've since purged my entire Rotki database and I will re-add assets one by one until I find what triggers this bug.

**Comment by Zorlin** [comment]
...literally just adding ADA as a manual asset and then curling that endpoint:

curl -s http://localhost:4242/api/1/balances | jq '.result.net_usd'

results in an infinitely growing balance...

:/

**Comment by Zorlin** [comment]
Hmm, however, *truly* purging absolutely everything then starting fresh does NOT trigger this when you add Cardano...

**Comment by Zorlin** [comment]
Okay, even more bizarrely, simply adding a Bitcoin wallet via xpub causes this bug too. It looks like ANY wallet added in Blockchain Balances causes the API to wig out :'(

**Comment by Zorlin** [comment]
Revised the original post to remove all the noise, having talked to the Rotki team.

**Comment by LefterisJP** [comment]
Closing this since it is fixed by #5848 and will appear in production either in 1.27.2 or 1.28.0. Most probably we will go directly for 1.28.0 due to the way the branches have developed.
