### ISSUE TITLE
Unable to delete events from Custom Import with "external" staking events in a CSV with incorrect timestamps

### ISSUE THREAD

**Issue by wolfspy** [rotki/rotki#5870]
## Problem Definition

Following the [Rotki Generic Events Import](https://rotki.readthedocs.io/en/stable/usage_guide.html#rotki-generic-events-import) instructions:

I accidentally imported some events with incorrect timestamps and cannot find these events anywhere to delete them. I can't purge the data by location: `external`. I'm not sure if the timestamps have anything to do with being able to delete the events or not.
- I'm hoping I'm just missing something here and I can find and delete the data somehow in the app.
- Also the JSON report output cuts off my imported timestamp (yes it was originally incorrectly formatted to seconds instead of milliseconds), but I'm not sure if this is related or not.

Example csv import:
```
Type,Location,Currency,Amount,Fee,Fee Currency,Description,Timestamp
Staking,external,ADA,100,,,ADA Staking reward,1643579071
```

Top of JSON report output with that event:
```
{
  "events": [
    {
      "identifier": 100,
      "event_identifier": "rotki_events_100",
      "sequence_index": 100,
      "timestamp": 1643579,
      "location": "external",
      "asset": "ADA",
      "balance": {
        "amount": "100",
        "usd_value": "0"
      },
      "event_type": "staking",
      "event_subtype": "reward",
      "location_label": null,
      "notes": "ADA Staking reward",
      "counterparty": null,
      "extra_data": null,
      "accounting_event_type": "history base entry"
    },
...
```

### System Description

Operating system: MacOS 13.3
Rotki version: 1.27.1

**Comment by LefterisJP** [comment]
With 1.28.0 this will be doable as they will appear in the history view.
