### ISSUE TITLE
Failed at global DB upgrade

### ISSUE THREAD

**Issue by camheras** [rotki/rotki#5871]
## Problem Definition

Just installed the last release (1.27.1) to try the soft.
After loading `Connecting to rotki backend`, error comes up : `rotki failed to start`

I might have downloaded a version like 2 years ago, not sure if I ran it.

## Logs

`There is a problem with the backend.`
`
[rotki-core] [rotki-core] Failed to start rotkehlchen backend: Traceback (most recent call last): File "rotkehlchen/globaldb/upgrades/manager.py", line 83, in maybe_upgrade_globaldb File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4 File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table File "rotkehlchen/db/drivers/gevent.py", line 89, in execute sqlite3.OperationalError: no such table: address_book The above exception was the direct cause of the following exception: Traceback (most recent call last): File "rotkehlchen/__main__.py", line 17, in main File "rotkehlchen/server.py", line 32, in __init__ File "rotkehlchen/rotkehlchen.py", line 146, in __init__ File "rotkehlchen/globaldb/handler.py", line 228, in __new__ File "rotkehlchen/globaldb/handler.py", line 181, in _initialize_global_db_directory File "rotkehlchen/globaldb/handler.py", line 149, in initialize_globaldb File "rotkehlchen/globaldb/upgrades/manager.py", line 92, in maybe_upgrade_globaldb ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book`

### System Description

Operating system: MacOS Ventura 13.2.1 (22D68)
Rotki version: 1.27.1

**Comment by LefterisJP** [comment]
Also for such questions it's best to join the discord: https://discord.gg/aGCxHG7. Have DMs open since there is a captcha challenge

**Comment by camheras** [comment]
Yeah it's solved thanks !

**Comment by camheras** [comment]
Deleted ~/Library/Application Support/rotki and installed again

**Comment by LefterisJP** [comment]
> Deleted ~/Library/Application Support/rotki and installed again

Thank you for the confirmaton @camheras! We also added a commit to address this wrong assumption in the specific upgrade path.
