### ISSUE TITLE
Remaining issues for history events

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#5971]
Remaining issues for history events from PR https://github.com/rotki/rotki/pull/5943

- [x] Need to show the tx-hash for MEV reward event (pending) #5993
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/26648140/235618069-b8a50c37-54a3-4493-a212-e235230fde5f.png">

- [ ] Ability to filter out 1 item from all possible item. #5983
 	For example we have filter `entry_types` with 5 options
	Let's say we want to filter by 4 from those 5 options
	It will be better if we an do something like `entry_types != eth_withdrawal_event` in frontend (@lukicenturi working on this)

**Comment by kelsos** [comment]
@lukicenturi did you start with any of these can you provide a bit of more context on what the status is and what is needed?

**Comment by lukicenturi** [comment]
> 



> @lukicenturi did you start with any of these can you provide a bit of more context on what the status is and what is needed?

no 1 is pending.
I'm working on number 2

need to wait for more feedback from @LefterisJP
