### ISSUE TITLE
Websocket from backend to trigger query balances in frontend

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#5975]
## Problem Definition

The issue is that there are some balances that are not queried like tokens, knowing beforehand the token that needs to be queried
What we do is to use the decoded events to say "you deposited tokens in this contract so we have to query it in order to get your deposit balance". This happens for curve and convex atm.
The problem is that in a fresh start since the events are not decoded those balances won’t appear

## Solution proposed
If at some point by navigating to the history events or by the background task that we run, we detect any of those contracts, then we should send a message to the frontend, and the frontend need to `query balances` again.

**Comment by LefterisJP** [comment]
This is in develop and will be in 1.28
