### ISSUE TITLE
Modules section feedback

### ISSUE THREAD

**Issue by dimyG** [rotki/rotki#5976]
## Abstract

As a new user I found the Modules section of the settings a bit confusing to be honest. It's great that the user has such granularity of control on what data to query, but what's confusing to me is the fact that we refer to the same thing with different terms. We use the terms "module" - "protocol" and "address" - "account" interchangeably. I think that when we present information to the user, we should abstract away rotki's internal logic and speak to the user in terms that he already knows and can easily relate to. 

In this case
1. The term module is something internal to rotki while the term protocol is widely used in the space. 
2. Similarly the term account (which refers to the combination of a blockchain and an address if I'm not mistaken) is internal to rotki while the term address is widely used in the space. 

So maybe it would be better in terms of clarity and consistency, to replace the term module with protocol and the term account with address. 

* If we want to mention the combination of a blockchain and an address, we can use the term "blockchain acccount" (as it is used in other parts of the app) to differentiate it from the term address. 

## Motivation

- I think that when we present information to the user, we should abstract away rotki's internal logic and speak to the user in terms that he already knows and can easily relate to. This enhances clarity. 
- We should also be consistent in using those terms across the whole app. This enhances consistency. 
- Clarity and consistency enhance the whole user experience. 

## Specification

In the current implementation we prompt the user to select which modules to activate. Then we say "If no accounts are selected for a protocol, data for all accounts will be queried for that protocol." So we use the term module and protocol to refer to the same thing actually. 
The title of the subsection is "Selected accounts" but when you select a protocol you are prompted to select an address. So we use the term account and address to refer to the same thing. 

![Picture3](https://user-images.githubusercontent.com/12560596/235632815-2e3038e2-b7a7-49c5-bfe7-8046e015663c.png)

As shown in the picture bellow (I just draw it by hand for speed, sorry) I propose a small change to the UI that makes things a bit more clear in my opinion. I'm thinking of just presenting one checkbox to the user with the text: All supported protocols and all connected addresses, which is on by default. So he doesn't need to see anything more by default. If he deactivates the checkbox, the table appears, which lists all supported protocols. He can choose what protocols he wants. Each protocol has a corresponding multiselection filter (as we already have) where he selects which addresses he want to get data for. We can have an "All" selection option so that he can pick all at once. 

![Picture1](https://user-images.githubusercontent.com/12560596/235628963-e74a3d29-ecd1-480a-9f89-c4333c1f6a77.png)

A related issue in the "Add blockchain account" view :

![Picture4](https://user-images.githubusercontent.com/12560596/235633080-a608b115-ad30-4aa4-874e-27c22834483f.png)

Maybe we could remove the term "modules" and as before, show just a checkbox to the user, enabled by default as shown in the picture bellow: 

![Picture2](https://user-images.githubusercontent.com/12560596/235629269-3c957e50-a6d2-4854-a2ab-75374d857407.png)

So the user is presented with two simple active checkboxes:
Get data for 
- All supported protocols 
- All supported EVM chains 

(the user does not need to know the difference between enabling a module and adding an EVM chain)

If the checkbox is deactive, then the existing list appears so that he can select. This way the user only sees a small checkbox but still has the possibility to control the queryed data if he so chooses. 

* Maybe this should be a new issue but I'm adding it here for now, since this whole issue might not be implemented.

**Comment by LefterisJP** [comment]
>So maybe it would be better in terms of clarity and consistency, to replace the term module with protocol

A module is not always a protocol. ETH2 is not a protocol. NFTs is not a protocol. It's a module. Apps having modules is something established. It's nothing new or internal to rotki only.

> Similarly the term account (which refers to the combination of a blockchain and an address if I'm not mistaken) is internal to rotki while the term address is widely used in the space.

You are mistaken on this. The term account does not refer to blockchain + address combination specifically. It's a different word for the same thing. And yes we unfortunately mix those two a lot. But this is unfortunately done a lot in the industry in general. Would indeed have been better to pick one and stick to it. But this is not something specific to only this view. For example: "Blockchains & Accounts" view etc

----

That said using only one term, modules and not protocols all around there and trying to stick to account or address only is a good point.

**Comment by LefterisJP** [comment]
feedback has been noted
