### ISSUE TITLE
Support 0x protocol

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#5978]
## Abstract

Support 0x protocol trades.

## Specification

Support the products that 0x provides, but especially decode swaps made via 0x. Check possible swaps via their router: https://etherscan.io/address/0xdef1c0ded9bec7f1a1670819833240f027b25eff

**Comment by TripleSpeeder** [comment]
We could take some inspiration from https://github.com/DeltaBalances/DeltaBalances.github.io. Looks like they have fully working trransaction decoder/interpretation for 0x protocol.
