### ISSUE TITLE
ARB supporting

### ISSUE THREAD

**Issue by emulatalk1** [rotki/rotki#6010]
I got this error when rotki scan binance wallet: Found unknown Binance 1 asset ARB. Ignoring its lending balance query.

**Asset name:** Arbitrum
**Asset symbol:** ARB
**Coingecko link:** https://www.coingecko.com/en/coins/arbitrum

**Comment by LefterisJP** [comment]
Hey @emulatalk1 thanks, we know ARB is missing from the known tokens list.

We are addin ARB in our next iteration of known assets. In the meantime you can add it also manually following the guide here: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset
