### ISSUE TITLE
Edge case with event type mapping

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#6043]
So endpoint `/history/events/type_mappings` contains a mapping for history `eventType` and `eventSubtype`
There is one field there `exchange_mappings` that use for event type `history events`.
But this field is only filled when there is an exchange registered.

We call this mapping endpoint every time we go to the history events view.
The problem happens when in the middle of adding an exchange, we go to the `history events view`.
The mapping will not have the `exchange_mappings` even if the events for `history events` show up.

But this will happen very rarely, as a user must move very fast from adding an exchange, before it's done and go to history events view.

**Comment by kelsos** [comment]
@lukicenturi do you think after all the changes we did this might still be valid? if not maybe we can close the issue.

**Comment by lukicenturi** [comment]
> @lukicenturi do you think after all the changes we did this might still be valid? if not maybe we can close the issue.

yes we can close it since there's no `exchange_mappings` anymore inside `type_mappings`
