### ISSUE TITLE
Rotki app fails to open after installation

### ISSUE THREAD

**Issue by ch4r10t33r** [rotki/rotki#6052]
## Problem Definition

Application fails to open after installation with the following error.

## Logs

```
[rotki-core] [rotki-core] Failed to start rotki backend:
Traceback (most recent call last):
  File “rotkehlchen/globaldb/upgrades/manager.py”, line 85, in maybe_upgrade_globaldb
  File “rotkehlchen/globaldb/upgrades/v3_v4.py”, line 388, in migrate_to_v4
  File “rotkehlchen/globaldb/upgrades/v3_v4.py”, line 359, in _upgrade_address_book_table
  File “rotkehlchen/db/drivers/gevent.py”, line 89, in execute
sqlite3.OperationalError: no such table: address_book
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File “rotkehlchen/__main__.py”, line 17, in main
  File “rotkehlchen/server.py”, line 32, in __init__
  File “rotkehlchen/rotkehlchen.py”, line 150, in __init__
  File “rotkehlchen/globaldb/handler.py”, line 212, in __new__
  File “rotkehlchen/globaldb/handler.py”, line 178, in _initialize_global_db_directory
  File “rotkehlchen/globaldb/handler.py”, line 143, in initialize_globaldb
  File “rotkehlchen/globaldb/upgrades/manager.py”, line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book
```

### System Description

Operating system: Ventura 13.3.1
Rotki version: 1.27.1

**Comment by ch4r10t33r** [comment]
> There is also a solution posted here in case you want to go with it [#5871 (comment)](https://github.com/rotki/rotki/issues/5871#issuecomment-1498761779). In the case you don't have custom assets is the easiest way to solve the issue and have the app running again. Otherwise you might need to edit the db manually but we can assist
> The fix to avoid such an error on our side in the future is here #5872

Ah, I should have checked that. Thanks for pointing to the workaround. I'll try that.

**Comment by ch4r10t33r** [comment]
I can confirm the work around fixes the issue. Thanks @yabirgb

**Comment by yabirgb** [comment]
Thank you @ch4r10t33r for using rotki and I'm sorry that you had such an experience. We took measures for the future to avoid this issues
