### ISSUE TITLE
Replace ledger actions with history events

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#6096]
This is a sub issue for #2469 

The ledger actions need to be replaced in the code by history events:

- [ ] Migrate all ledger actions to history events
- [ ] Remove endpoints that make use of ledger actions
- [ ] Remove accounting logic for ledger actions
- [ ] Allow to edit/create/delete history events that replace the ledger actions

**Comment by LefterisJP** [comment]
The last bullet point ofthis issue is not directly related and is moved to a note for the same release: https://github.com/orgs/rotki/projects/11?pane=issue&itemId=40691321
