### ISSUE TITLE
Add note in new account creation and in sign-in about where data is stored

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#610]
## Problem Definition

Rotki is a local first application. The fact that it starts by asking the user to create an account can be confusing, especially for first time users. [Case in point twitter thread](https://twitter.com/gregthegreek/status/1213552533261692929)

## Task

Add a note both in the new account creation and in the sign-in pop-up that says:

"Rotki is a local application that respects your privacy. Rotki accounts are encrypted with your password and saved in your local filesystem"

Not sure about the note yet -- but something like that.

**Comment by LefterisJP** [comment]
@kelsos This should be easy to do I guess. What kind of note do you think would carry the point across and be unobtrusive?

**Comment by kelsos** [comment]
we could also add the suggested message in the bottom of the login page. with a smallish font but still readable. I have to do some research though for the best way to do it.

**Comment by LefterisJP** [comment]
@kelsos has to also be visible in the register pop-up. Unless I misunderstand what you meant.

**Comment by kelsos** [comment]
@LefterisJP I don't mean in the popup itself but in the bottom of the screen outside of the popup so it will be visible until you are logged. :D
