### ISSUE TITLE
Smaller chart size in the Statistics view

### ISSUE THREAD

**Issue by dimyG** [rotki/rotki#6109]
## Abstract

Currently there is one column for the charts even in large screen sizes. 

![statistics_smaller](https://github.com/rotki/rotki/assets/12560596/3ebc10b0-c302-422d-815b-e27882746f23)

I think it would be better to have at least 2 columns on medium screen size and up (md and up). Maybe even 3 columns for md+, 2 columns for sm-md and 1 for sm and bellow. 

## Motivation

Currently the whole screen is filled with one chart, for example a pie chart, and it doesn't look good. You can get the information from a much smaller chart.

**Comment by kelsos** [comment]
@dimyG Hey Dimitri, this is on Windows, right? Which screen resolution?

I think this is a bug either in how we implement the breakpoint or related to the screen scaling so the 2 columns only seem to work on fullscreen.

**Comment by kelsos** [comment]
It should be a bit better on the deployed version of the components so I am closing the issues. 
Any further work we can handle as part of the updated design.
