### ISSUE TITLE
Consistent placeholder for views with no table data.

### ISSUE THREAD

**Issue by dimyG** [rotki/rotki#6110]
## Abstract

Currently if you are in a view with a table and no data, you see just an empty table like this:

![ignore_empty_tables](https://github.com/rotki/rotki/assets/12560596/b54ea8e1-39d2-4af1-89ac-5c6628801f82)

It's not someting critical of course, but it's not nice in the eye. Perhaps it would be better to use a common placeholder for these cases. Maybe something like this used in the NFTs view: 

![consistent_view_no_data](https://github.com/rotki/rotki/assets/12560596/14b6c4da-8a8e-4ef5-9286-caab760914fe)

## Motivation

A visual enhancement.

**Comment by originalrfr** [comment]
You can see how it will be the empty state in our tables here: https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=124%3A41054&t=tE6SYtA7aZyUCnrY-1 @dimyG

**Comment by dimyG** [comment]
Yes it's much better. So in this case I guess, it would show "No manual balances found" instead of an empty table. Or this message within an empty table? The former would be better in my opinion because you avoid all the table clutter (next, previous, rows per page etc.)

**Comment by originalrfr** [comment]
In each table, the text will be minimally modified to something like "No ${table_name} data found", and as you said within the table footer

**Comment by kelsos** [comment]
This will also be addressed in the new design so I am gonna close this issue.
