### ISSUE TITLE
Some minor issues with the UI of the input fields. 

### ISSUE THREAD

**Issue by dimyG** [rotki/rotki#6111]
## Abstract

1. The background color of the input fields, for example of the filter field, is the same with the page background color and its not very clear that an input field is open. In the light theme the border of the input field is visible and things are more clear, but in the dark theme the border is not visible and the background colors issue becomes more severe. 

![filter_bg](https://github.com/rotki/rotki/assets/12560596/62be6187-53f8-4b0d-b7f2-8c0cac54659b)

2. When you select a filter, for example "action: sell" the input field remains open and you have to click somewhere else on the screen to close it, or close it directly. Perhaps it would be better if the field closes directly after a filter has been selected. 

## Motivation

Minor UI/UX enhancements

**Comment by dimyG** [comment]
The windows and the main background being slightly different certainly looks better. Maybe also the input fields could have a slightly different bg color, maybe something between the main color and the window color?

**Comment by vednp** [comment]
Hey @dimyG can i work on this?

**Comment by kelsos** [comment]
Hey @vednp thanks, however, we are going to close this issue.

The new design/design system will address the first point, there is better contrast when using dark mode for the input fields there, changing it right now would only need in duplicate effort.

For the second point, we are still discussing how to approach it. If we decide on a change I will open a new issue and link to it.

**Comment by vednp** [comment]
Sure, Great

**Comment by vednp** [comment]
Ok Great
