### ISSUE TITLE
Rename LEDGER ACTIONS?

### ISSUE THREAD

**Issue by dimyG** [rotki/rotki#6112]
## Abstract

As a new user, it was not clear what this tab is about (something to do with the Ledger hardware wallet?). I had to try and create a new entry to understand. Maybe it would be more self-explainable if we renamed it to something else like "Manual Entries" for example?  

![ledger_actions](https://github.com/rotki/rotki/assets/12560596/9d80ad82-bb6e-4451-a58e-97a8e50a350c)

## Motivation

UX enhancement

**Comment by yabirgb** [comment]
Ledger actions will be removed and history events should be used instead https://github.com/rotki/rotki/issues/6096. I'm not sure how hard is to replace the term meanwhile

**Comment by LefterisJP** [comment]
no no it makes no sense to do anything here as they would be replaced by normal history events. Adding a manual history event is what will be happening instead. But this will take time.

If that is enough for you feel free to close.

**Comment by kelsos** [comment]
Since as we discussed we are going to integrate ledger actions into the history view, the name and area will go away.
