### ISSUE TITLE
Re-implement creation of new account with already existing premium key in vue.js

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#612]
## Problem Definition

In Rotki version <= 1.0.7 it was possible to create a new account in a machine, and already have a premium key bought and entered at account creation. This allowed to easily move all data between devices as the new account was syncing with the premium server pulling all data the user had.

## Task

Reimplement that functionality in vue.js. The backend already supports it and should also handle all cases properly.

![2020-01-05-165136_501x398_scrot](https://user-images.githubusercontent.com/1658405/71782587-1df30d80-2fdc-11ea-989e-ed7aa35e5649.png)

So it is just a matter of adding the UI elements and conditionally sending two more arguments to the new user creation API endpoint.

A suggestion on how to implement this would be to add an unchecked checkbox with the label "I already have premium credentials".

If the user checks it then two more text boxes are added in the form. "Premium API Key" and "Premium API Secret".

The contents of these should be passed to the new user creation endpoint.

**Comment by kelsos** [comment]
It should be fairly easy to implement yes.
