### ISSUE TITLE
Vue.js Login and new user creation problems.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#616]
## Problem Definition

1. When logging in your account if a wrong password is provided then the pop up says:
"401 (UNAUTHORIZED) response" instead of using the message of the response.
2. When trying to create a new account and you type the password wrong a 500 error is returned but you are still getting through the account creation page and into the dashboard.

## Task

Fix the problems.

**Comment by kelsos** [comment]
@LefterisJP we definitely need to evaluate the error cases to see what doesn't work as expected

**Comment by LefterisJP** [comment]
@kelsos And have tests for them. I think (1) is just a UX error on what I want to be shown to the user. (2) is strange and am looking into it.

**Comment by kelsos** [comment]
Yes yes, I am actually talking about the UI integration mostly and how the errors are displayed.

**Comment by LefterisJP** [comment]
@kelsos I see. Generally the error I would expect to see in the UI in most cases is the contents of the  `'message':` key of the response.
