### ISSUE TITLE
Error querying Kraken staking events

### ISSUE THREAD

**Issue by timnugent** [rotki/rotki#6205]
Version: 0.1.19 (v1.27.1 upstream), Dappnode

There was an error while querying the kraken staking events:
[
   {
      "received":"fee",
      "code":"invalid_enum_value",
      "options":[
         "reward",
         "receive wrapped",
         "deposit asset",
         "remove asset"
      ],
      "path":[
         "events",
         1,
         "eventType"
      ],
      "message":"Invalid enum value. Expected 'reward' | 'receive wrapped' | 'deposit asset' | 'remove asset', received 'fee'"
   },
   ...........
]

**Comment by LefterisJP** [comment]
Hey @timnugent can you give some more information? When does this happen? When you go to kraken staking events? What assets have you staked in Kraken? What have you used there? Also can you [enable debug logs](https://rotki.readthedocs.io/en/latest/contribute.html#id2), get the error again and then share with us the logs in a private message in discord: https://discord.gg/aGCxHG7  ?

Finally I notice you use an old rotki version (1.27.1). I am not sure if this is related but will ping @yabirgb to check for this.

**Comment by timnugent** [comment]
Hi @LefterisJP - happens as soon as I click on the Staking tab, with Kraken selected as the location. Hmm, I don't have the option to enable logs (I see there's a issue for this on Dappnode) and nothing in the logs dir. Staked assets are ETH, MATIC and ATOM. Last time I tried this and it worked without issue was around 3 weeks ago so perhaps something has changed on the Kraken side since then.

**Comment by timnugent** [comment]
Relevant Dappnode package logs for Rotki when this happens:

xxx.xx.x.xx - - [04/Jun/2023:21:44:25 +0000] "GET /api/1/exchanges/balances/kraken?async_query=true HTTP/1.1" 200 43 "http://rotki.dappnode/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"
xxx.xx.x.xx - - [04/Jun/2023:21:44:26 +0000] "POST /api/1/staking/kraken HTTP/1.1" 200 16507 "http://rotki.dappnode/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"

**Comment by LefterisJP** [comment]
> Hi @LefterisJP - happens as soon as I click on the Staking tab, with Kraken selected as the location. Hmm, I don't have the option to enable logs (I see there's a issue for this on Dappnode) and nothing in the logs dir. Staked assets are ETH, MATIC and ATOM. Last time I tried this and it worked without issue was around 3 weeks ago so perhaps something has changed on the Kraken side since then.

Hmm yeah unfortunately dappnode does not allow us to have logs so debugging is really hard. Do you have the possibility to run the normal binary in your OS (I presume is Windows?) also with just the kraken key and logs enabled so that you can share this information with us?

I used to have XTZ, ETH, DOT, KSM staking. And neither of those hit these problems with 1.28.0. And I also tested with 1.27.1 and still the same.

So there must be some kind of event you have that causes this error. And it if was okay until 3 weeks ago, it must be a new event. Could really use those debug logs as they would probably tell us what the event is.

We could probably chat much easier via discord so if you pop by there (keep in mind DMs should be open as there is a captcha challenge) talk to us there too.

**Comment by timnugent** [comment]
Event type 'fee' seems to be the issue:

[05/06/2023 11:14:24 BST] DEBUG rotkehlchen.api.server Greenlet-0: end rotki api POST /api/1/staking/kraken view_args={}, query_string=b'', status_code=200, result={'result': {'events': [{'event_type': 'reward', 'asset': 'ETH', 'timestamp': 1685849255, 'location': 'kraken', 'amount': 'x.xxxxxxxxxxx', 'usd_value': 'x.xxxxxxxxxxx'}, {'event_type': 'fee', 'asset': 'ETH', 'timestamp': 1685849255, 'location': 'kraken', 'amount': 'x.xxxxxxxxxxx', 'usd_value': 'x.xxxxxxxxxxx'}, {'event_type': 'reward', 'asset': 'ATOM', 'timestamp': 1685590035, 'location': 'kraken', 'amount': 'x.xxxxxxxxxxx', 'usd_value': 'x.xxxxxxxxxxx'}, {'event_type': 'reward', 'asset': 'eip155:1/erc20:0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0', 'timestamp': 1685585895, 'location': 'kraken', 'amount': 'x.xxxxxxxxxxx', 'usd_value': 'x.xxxxxxxxxxx'}, ....

**Comment by yabirgb** [comment]
Hello! @timnugent As lefteris metnioned this is I fear an issue in 1.27.1. If you could update to 1.28 it should be fixed. After the withdrawals were enabled kraken starting to create a new type of event and this made or parsing fail. If you could try the latest version and let us know it would be great

**Comment by timnugent** [comment]
Ah great, will wait for 1.28 on Dappnode in that case. Tried to run latest but hit some dependency issues (need GLIBC_2.29) and my distro is old (Ubuntu 18.04)

**Comment by timnugent** [comment]
Ah great, will wait for 1.28 on Dappnode in that case. Tried to run latest but hit some dependency issues (need GLIBC_2.29) and my distro is old (Ubuntu 18.04)

**Comment by timnugent** [comment]
Working in 1.28, thanks all

**Comment by yabirgb** [comment]
@timnugent cool! Let us know if you find any other issue. Support in our discord server is usually easier https://discord.gg/aGCxHG7

**Comment by timnugent** [comment]
Just joined, will do
