### ISSUE TITLE
Allow manual withdrawals to be added by user to simulate a taxable event to find out potential withdrawal tax.

### ISSUE THREAD

**Issue by tdbe** [rotki/rotki#6207]
Other competing services allow this:

Add a "manual transaction" that you can set as "Withdrawal", so that rotki can calculate for you how much you would need to spend in tax if you were to withdraw now.

I see it is possible to set a manual Trade, but not a manual withdrawal. This distinction is very important because, in many cases / jurisdictions / time frames, a withdrawal and a type of trade are two different things tax wise. 

In the case that you set rotki to ignore crypto-crypto trades from taxable events, then it is impossible to ask it how much tax you would pay, until after you've done the event. Which is ......not great.

**Comment by LefterisJP** [comment]
Please check my other response to your other issue and for questions, just talk to us in discord. Open issues for bug reports.

**Comment by tdbe** [comment]
You're right 👍, but also, please consider the UX confusion in my observation

**Comment by LefterisJP** [comment]
> You're right +1, but also, please consider the UX confusion in my observation

Absolutely. Also the name ledger action is terrible. And they will all be soon consolidated into the "history events" section which will also allow manual addition of any type of event. We want to make these better and your confusion is definitely taken into account.
