### ISSUE TITLE
Discord capcha - Error completing verification: You cannot verify when using a VPN

### ISSUE THREAD

**Issue by OneArb** [rotki/rotki#6272]
One of the exchange I use is yet to be supported.

I am considering contributing that exchange or just add it for myself.

Is it intended for crypto holders to dox their IP to contribute?

**Comment by yabirgb** [comment]
Hello @OneArb . We were not aware of any issue with VPNs and the discord captcha. As far as I know @kelsos is working to replace it soon. If you dm me in discord at yabirgb I can verify your account
