### ISSUE TITLE
Import data from Cointracking: Support Staking

### ISSUE THREAD

**Issue by PabloCastellano** [rotki/rotki#6274]
## Problem Definition

Importing data from a Cointracking CSV csv file with the column Type='Staking' will fail in rotki.

Example file:

```
"Type","Buy","Cur.","Sell","Cur.","Fee","Cur.","Exchange","Group","Comment","Date"
"Staking","1.00000000","AXS","","","","","Binance","","","05.01.2022 12:38:00"
"Staking","2.12000000","ETH","","","","","Binance","","","08.02.2022 11:29:00"
```

## Logs

```
[18/06/2023 17:00:58 CEST] WARNING rotkehlchen.user_messages Greenlet-6: Unknown entrype type "Staking" encountered during cointracking data import. Ignoring entry
[18/06/2023 17:00:58 CEST] WARNING rotkehlchen.user_messages Greenlet-6: Unknown entrype type "Staking" encountered during cointracking data import. Ignoring entry
```

### System Description

Operating system: Linux Mint
Rotki version: v1.28.0

**Comment by palrohitg** [comment]
Hey @PabloCastellano @PabloCastellano : As I'm going through the codebase to understand a bit, was able to figure out that if CSV file containing Type as "Staking" we have an exception block in **cointracking.py** . It would be great if you can a little more details, basically need to pass this condition or perform some action on staking type.

**Comment by LefterisJP** [comment]
> Hey @PabloCastellano @PabloCastellano : As I'm going through the codebase to understand a bit, was able to figure out that if CSV file containing Type as "Staking" we have an exception block in **cointracking.py** . It would be great if you can a little more details, basically need to pass this condition or perform some action on staking type.

The problem Pablo states is that rotki does not seem to understand lines that have "Staking" as their type when importing something from Cointracking.

So these should not be skipped but instead of skipped have a proper staking `HistoryEvent` generated and added to rotki.

**Comment by Jaspreet-singh-1032** [comment]
Hi @palrohitg, Just wants to know if you are still working on this issue. If not then I would like to give it a try.
