### ISSUE TITLE
Support for Bitstamp csv import

### ISSUE THREAD

**Issue by PabloCastellano** [rotki/rotki#6275]
## Abstract

Add support to import Bitstamp transactions csv

## Specification

Write a new parser for Bitstamp csv format.

Format example:

```
Type,Datetime,Account,Amount,Value,Rate,Fee,Sub Type
Deposit,"Jan. 28, 2022, 12:13 AM",Main Account,2.00000000 ETH,,,,
Market,"Jan. 28, 2022, 12:31 AM",Main Account,1.00000000 ETH,2214.01 EUR,2214.01 EUR,10.87005 EUR,Sell
Withdrawal,"Jan. 30, 2022, 11:40 AM",Main Account,2211.01 EUR,,,3.00 EUR,
```

**Comment by ndurumo254** [comment]
hello @LefterisJP i would like to work on this

**Comment by LefterisJP** [comment]
> hello @LefterisJP i would like to work on this

hello! Please come over our discord so you can coordinate with us and other devs who aso want to work on such issues! I saw someone with the same avatar in there who did not go through verification. I assume it's you so I will verify manually.
