### ISSUE TITLE
Binary release 1.0.7 does only show "CoinTracking"

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#628]
When I click on "Import data", only the CoinTracking logo shows up, no other importers.

I think this is a bug because I believe rotki has more importers than that?

This is on Linux.

**Comment by coinyon** [comment]
Sorry, I have to add exchanges first it seems.

**Comment by LefterisJP** [comment]
Yeah indeed, exchanges need to be added from the user settings. Thank you for using Rotki!

**Comment by coinyon** [comment]
Maybe a little note on the import data tab would be helpful :-)

**Comment by LefterisJP** [comment]
Good point. We will think about it! Thank you for your feedback.
