### ISSUE TITLE
Change `CHF` Symbol from `FR.` to `CHF`

### ISSUE THREAD

**Issue by pcaversaccio** [rotki/rotki#6375]
## Problem Definition

Sorry for this nit-picky issue but as a Swiss citizen, I was confused seeing the current symbol `FR.`. The official international [ISO_4217](https://en.wikipedia.org/wiki/ISO_4217) would be `CHF`. The `Fr.` abbreviation (see the small `r`) would be the German-based abbreviation and not the international, English-based one. You can learn more [here](https://fedlex.data.admin.ch/filestore/fedlex.data.admin.ch/eli/cc/2000/194/20210301/de/pdf-a/fedlex-data-admin-ch-eli-cc-2000-194-20210301-de-pdf-a-1.pdf)
![image](https://github.com/rotki/rotki/assets/25297591/b403dfe7-4211-4ed2-a571-45974ca7a50c)
![image](https://github.com/rotki/rotki/assets/25297591/49ffc582-89e8-48ef-b4dc-d1afb4fcaae3)

**Comment by LefterisJP** [comment]
Hey @pcaversaccio the ticker/symbol (ISO 4217) is CHF. The symbol you see up there is taken from the left column of this page: https://en.wikipedia.org/wiki/Currency_symbol

It's supposed to be what `$` is to `USD`. It's the abbreviation/symbol. Is it not supposed to be Fr and should also be CHF?

**Comment by pcaversaccio** [comment]
> It's supposed to be what `$` is to `USD`. It's the abbreviation/symbol. Is it not supposed to be Fr and should also be CHF?

Well the Swiss Franc doesn't have a symbol and the abbreviation used in https://en.wikipedia.org/wiki/Currency_symbol would be SFr. which honestly doesn't exist at all in Switzerland lol. If you check here: https://en.wikipedia.org/wiki/Swiss_franc, you see the abbreviations used: 
![image](https://github.com/rotki/rotki/assets/25297591/b407b52a-f0ca-41c6-8f0e-6cb0a8ad5090)

So in a Swiss newspaper, you would see `Fr.` in a german speaking context, but not in an international-speaking context. Let's say if Rotki would offer a German version I would recommend `Fr.`. In an international context, I would really recommend `CHF` since this is the most used one here in Switzerland.

**Comment by LefterisJP** [comment]
Sure you are Swiss, not us. So we can go with that :)

**Comment by pcaversaccio** [comment]
> Sure you are Swiss, not us. So we can go with that :)

If anyone should complain about this, please re-direct to me :-D
