### ISSUE TITLE
Wallet based cost tracking

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#6378]
## Abstract

Many crypto tax calculators (koinly.io, cointracker.io, cryptotaxcalculator.io) let you enable "wallet based cost tracking".

In addition to FIFO and the other cost basis methods, this additional feature basically separately identifies the coins in different wallets and exchanges. This means that the coins of the same asset can have a different cost basis if they were purchased on a different wallet or exchange.

It's similar to 'Seperate Identification' (where you'd separately identify the cost of each coin) except it pools together the cost in each wallet/exchange.

## Motivation

It should be implemented because it's by far the most realistic and tax efficient method. It's probably also going to become the standard accounting method in many countries. Cointracker switched US customers to this method by default: https://support.cointracker.io/hc/en-us/articles/12407462337937

## Specification

See example here: https://support.cointracker.io/hc/en-us/articles/4413071343889-Cost-Basis-Tracking-Universal-vs-Per-Wallet

## A simple example

Let's say in `Wallet 1` I bought 32 ETH for a price of $1,000 per coin so $32,000 . I then stake this 32 ETH and receive staking rewards to the withdrawal address `Wallet 2`.

Now I receive staking rewards periodically to `Wallet 2` (a new wallet starting with 0 ETH balance). The income for each withdrawal transaction is just the amount at that time. The price of ETH has since risen to $2000.

Here's the problem: When I go to sell the ETH in `Wallet 2` instead of the profit/loss being calculated as the difference between the withdrawal transaction and the sale value, it instead uses the cost of the initial 32 ETH (this is what we're trying to avoid).

In wallet/exchange cost based tracking, the calculation would only consider the cost inside `Wallet 2` and would ignore the cost of the 32 ETH which is still deposited in the staking contract.

**Comment by LefterisJP** [comment]
This is not tax-efficient for most people. It completely depends on how your activity is done.

But isn't what you are asking effectively the same as the multi-depot issue? https://github.com/rotki/rotki/issues/2438

Where the depot size is 1, just a wallet, and you have as many depots as accounts? In that issue the idea is to have configurable selections (depots) of accounts where each depot has its own PnL. You could theoretically make each depot be a single account.

**Comment by a7e8** [comment]
> This is not tax-efficient for most people. It completely depends on how your activity is done.

It definitely depends on the activity yes. It is however the most realistic method because it doesn't mix different activities together. For me personally, it's a must have feature.

> But isn't what you are asking effectively the same as the multi-depot issue? #2438

It looks similar yes, perhaps just a different name? Other services use the terminology 'universal' or 'wallet' based.

> Where the depot size is 1, just a wallet, and you have as many depots as accounts? In that issue the idea is to have configurable selections (depots) of accounts where each depot has its own PnL. You could theoretically make each depot be a single account.

I'm not sure about the 'depot' terminology but basically speaking rather than think of each account with its own PnL (because PnL is the resulting calculation), it's best to think of each asset with it's own separate cost basis per account. For example in the Universal method, which Rotki currently employs, the cost basis for an asset like ETH would be tracked across all exchanges/accounts. Using the wallet/exchange based method, you effectively create a new cost basis for each asset, in each account (like a new virtual ticker just for that account).

Where things get a bit more tricky might be transfers between accounts/exchanges. When coins are sent from wallet A to wallet B they also need to take their cost basis with them.

**Comment by LefterisJP** [comment]
> I'm not sure about the 'depot' terminology but basically speaking rather than think of each account with its own PnL (because PnL is the resulting calculation), it's best to think of each asset with it's own separate cost basis per account.

Yes you are right. This is what I wanted to say. Cost basis which would result in a different PnL for each "pot" at the end.

It's not just wallets as it can be exchanges, banks, paypal etc. And sometimes you would like to combine them.

Anyway I get the request, and it seems the same as that issue. Yeah the name depot is the german one, perhaps a different one would indeed make sense here.

Will close this as duplicate and point it to the other issue. Hope that's fine. This does not mean we don't want to do it. Just need to conslidate requests.
