### ISSUE TITLE
Windows Security Popup

### ISSUE THREAD

**Issue by pcaversaccio** [rotki/rotki#6381]
## Problem Definition

Whenever I open Rotki on my Windows 11 Laptop, I get the following popups:

![image](https://github.com/rotki/rotki/assets/25297591/d6f2c996-53ce-4f2a-aa2b-c66b28b127a8)

![image](https://github.com/rotki/rotki/assets/25297591/633b2469-e284-42b1-ba07-df2fd6099022)

I mean I could whitelist it, but am wondering whether there is an underlying issue that triggers this.

## Logs

N/A.

### System Description

- Operating system: Windows 11 
- App Version: 1.29.0

**Comment by LefterisJP** [comment]
Hey @kelsos can you have a look at this when you can?

@pcaversaccio this is probably some false positive with Windows Defender. There is many such cases unfortunately.

We have in fact bought a quite expensive certificate to satisfy the Windows warnings for "unknown publisher". So we want windows users to feel safe and not have to ignore popups all the time.

**Comment by pcaversaccio** [comment]
> We have in fact bought a quite expensive certificate to satisfy the Windows warnings for "unknown publisher". So we want windows users to feel safe and not have to ignore popups all the time.

Maybe get in touch with Windows directly (if you got a direct line there)?

**Comment by pcaversaccio** [comment]
Ah, also I now also remember when I downloaded it using Edge, it showed me the following message: 
![image](https://github.com/rotki/rotki/assets/25297591/d7e65bc3-afb6-4c2a-af62-0ff2d43d8741)

**Comment by LefterisJP** [comment]
> Ah, also I now also remember when I downloaded it using Edge, it showed me the following message: ![image](https://user-images.githubusercontent.com/25297591/251435846-d7e65bc3-afb6-4c2a-af62-0ff2d43d8741.png)

yeah not much we can do for any of these. I think they remove those warnings once a download has happened enough times, but then the timer resets for each new release. So it's pointless.

**Comment by pcaversaccio** [comment]
![image](https://github.com/rotki/rotki/assets/25297591/a2ef2911-edad-407d-9611-4ed6ae963cfe)

**Comment by kelsos** [comment]
I wonder what is in the cache data folder.

**Comment by pcaversaccio** [comment]
![image](https://github.com/rotki/rotki/assets/25297591/853b2986-0490-4b40-9ebe-1a1b4d1abdd3)

**Comment by kelsos** [comment]
> should be safe to share here imo:
> ![image](https://github.com/rotki/rotki/assets/25297591/853b2986-0490-4b40-9ebe-1a1b4d1abdd3)
> 

Thanks I will have to do some research to see which part. Of the application is responsible for theae.

**Comment by kelsos** [comment]
Ok so I managed to give it a try on my laptop with Windows 11 and I don't get any warnings but the content is different.

I think this contains Chromium's cache so it should be safe to delete or you could try Help -> Clear Cache it should do the same.

Can you check if this stops the problem?

**Comment by kelsos** [comment]
I am kind of lost here as to how to proceed, do you get anything else regarding what is considered suspicious about the file?

**Comment by pcaversaccio** [comment]
No, everything I get is reported in this issue. I mean we can keep this issue open and maybe other folks will report it as well with maybe further information. You don't have a direct line to Windows to ask maybe help from their side?

**Comment by pcaversaccio** [comment]
No, everything I get is reported in this issue. I mean we can keep this issue open and maybe other folks will report it as well with maybe further information. You don't have a direct line to Windows to ask maybe help from their side?

**Comment by kelsos** [comment]
The problem is that we have to understand why and how did this happen.
The file in question is from Chromium's cache data (generated on runtime). I am trying to think why would cache trigger Windows Defender, even after clearing, and what the difference might be between the two instances (this and me trying the same on my laptop). 

Btw did you go to 1.29 by installation or did you auto-update, I wonder if something is related.

Btw just out of curiosity can you try disabling NFT image loading, then clear the cache and login again?. You can find instructions [here](https://rotki.readthedocs.io/en/latest/usage_guide.html#nft-images-rendering-setting)

**Comment by pcaversaccio** [comment]
> The problem is that we have to understand why and how did this happen.
> The file in question is from Chromium's cache data (generated on runtime). I am trying to think why would cache trigger Windows Defender, even after clearing, and what the difference might be between the two instances (this and me trying the same on my laptop).

Any chance that someone else from the team has a Windows computer and may be able to replicate it? I'm also wondering whether it's related to some specific Windows security settings. Do you have this enabled ("Windows Security" -> "Virus & threat protection settings" -> "Manage settings")?

![image](https://github.com/rotki/rotki/assets/25297591/03725250-c18c-48b2-b596-98e7069e6827)


> Btw did you go to 1.29 by installation or did you auto-update, I wonder if something is related.

I used the auto-update, i.e. the notification in Rotki to update the version.

> Btw just out of curiosity can you try disabling NFT image loading, then clear the cache and login again?. You can find instructions [here](https://rotki.readthedocs.io/en/latest/usage_guide.html#nft-images-rendering-setting).

Same result, unfortunately. Now they want me even to submit 3 files lol:

![image](https://github.com/rotki/rotki/assets/25297591/0bc4087f-e472-4bef-ae3f-c4198b5033db)

**Comment by kelsos** [comment]
:'( I really wonder what kind of cache data would this be.

**Comment by LefterisJP** [comment]
Does this still keep happening @pcaversaccio ? We don't know of anybody else getting this and seems that our devs with Windows can't replicate. I wonder how we could get to the bottom of this.

**Comment by pcaversaccio** [comment]
yes, it does... I have no clue how to debug it really :-(; I mean it doesn't bother me that much but maybe someone from Windows can help here?

**Comment by pcaversaccio** [comment]
Ohh wait, it doesn't pop up anymore as it did ~1 week ago and thus closing it. I guess it could be related to the recent update (2 days ago) "2023-10 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5031455)". Anyways, those are the moments where you know that we will never comprehend what went wrong but are simply happy that it works. And yes, I hate software lol.

**Comment by LefterisJP** [comment]
> Ohh wait, it doesn't pop up anymore as it did ~1 week ago and thus closing it. I guess it could be related to the recent update (2 days ago) _2023-10 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5031455)_. Anyways, those are the moments where you know that we will never comprehend what went wrong but are simply happy that it works. And yes, I hate software lol.

Huh interesting! I mean that can happen and could be related. Who knows! Happy you don't see it anymore!

**Comment by pcaversaccio** [comment]
Lol, look what appeared again this morning:
![image](https://github.com/rotki/rotki/assets/25297591/5c474c91-df6a-48d8-8dd3-3c488c92b4ee)
