### ISSUE TITLE
Select ETH tokens to track - search bar

### ISSUE THREAD

**Issue by kdm5126** [rotki/rotki#639]
Having to scroll through the never ending list of erc20 tokens instead of being able to search

easier ux on mac osx

**Comment by kdm5126** [comment]
please and thank you!

**Comment by LefterisJP** [comment]
HAha @kdm5126 I now see what you meant by [this](https://twitter.com/Maverickal_/status/1218536751771373569) tweet. But you can always edit the first post :smile: 

For the problem at hand, I totally agree with you. This is already solved in the `develop` branch. We have a search bar and a totally different way of searching for tokens. You can see a screenshot of it in [this post](https://blog.rotki.com/2019/12/13/rotki-new-years-resolutions/#modern-ui)

**Comment by kdm5126** [comment]
Good to know! Not the best git user that’s for sure! Let’s get you to that goal in the grant!!!

**Comment by LefterisJP** [comment]
Hey @kdm5126 I consider this problem solved after v1.1.0. IF you have any other problems or suggestions please open issue/s.
