### ISSUE TITLE
Explore the possibility of using The Graph for querying ethereum transactions

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#640]
## Problem Definition

Querying transactions for all user accounts is hard. It was suggested to checkout [The Graph](https://thegraph.com/docs). More info on this [Twitter thread](https://twitter.com/nicksdjohnson/status/1219331176189456384).

## Task

- Write a Graph driver to query subgraphs that already exist: https://thegraph.com/explorer/
- (Long running): Query subgraphs as additional source in combination with whatever else we use.
- (Long running - make another issue per graph): Make our own subgraphs?

**Comment by LefterisJP** [comment]
We may experiment with the graph a bit, as long as they have their hosted service. Needs time and experimentation to see what we can use per protocol.

Their current state it that they have introduced a Token, the `GRT` and are trying to create a closed economy around ethereum node historical querying which may not work well with rotki. Information about it can be seen in their blog. Latest post explains the incentivized testnet they are running: https://thegraph.com/blog/testnet-announcement

Notable quote regarding the tokenomics:
> Indexers operate Graph Nodes and stake GRT to index and serve blockchain data; ensuring reliability and uptime, reducing security risks of centralized databases, improving scale and performance, and enabling applications to become fully serverless. Indexers earn query fees and GRT token rewards for their services.
>
>Curators signal on subgraphs and stake GRT to indicate to Indexers which subgraphs are high-quality and should be indexed. Curators also earn a portion of query fees for the subgraphs they signal on, incentivizing them to curate the highest quality data sources.`

**Comment by aspiers** [comment]
FWIW my past experience with The Graph has been really good :-)  They even fixed bugs quickly when we reported them.

**Comment by LefterisJP** [comment]
@aspiers yeah I also had a few calls with Yaniv. My view towards the graph has changed. At least for now their head is in the right place and they plan towards a decentralized future.

We are already integrating with various subgraphs, starting from the next release (compound -- maybe aave if time allows)

That said ... this issue was more like for us to explore integration with the graph. This has now started and we have issues per integration, so I am closing this one.
