### ISSUE TITLE
Support Bittrex csv import

### ISSUE THREAD

**Issue by IanMichaelHarper** [rotki/rotki#6459]
## Motivation

Now that Bittrex has gone bankrupt, [the current exchange integration](https://github.com/rotki/rotki/blob/develop/rotkehlchen/exchanges/bittrex.py) will no longer work. I can't even access the exchange anymore as the website appears to be down.

Existing Rotki users may have their Bittrex data already stored in their DBs, but any Bittrex traders coming to Rotki for the first time may only have their exported trade CSVs.

## Specification

Previous PRs for other exchanges/services are a good template to work off, as the imported csv just needs to be parsed and history events created from its rows.
- [Backend part](https://github.com/rotki/rotki/pull/6157)
- [Frontend part](https://github.com/rotki/rotki/pull/6179)
- [Full implementation](https://github.com/rotki/rotki/pull/6426)

### CSV format
This is the format of the Bittrex trades I was able to export back in 2018. It may have changed since then but this is all I have for now.
```
OrderUuid,Exchange,Type,Quantity,Limit,CommissionPaid,Price,Opened,Closed
eb4a25bd-b2e9-4269-8ee3-fd6a7c0eb00a,BTC-XZC,LIMIT_SELL,2.13156327,0.00414861,0.00002209,0.00884301,11/22/2017 8:30:23 PM,11/22/2017 8:30:52 PM
f467973b-6f61-4ed7-97d5-ee3c9cdb01db,BTC-NEO,LIMIT_BUY,2.12583398,0.00599999,0.00003187,0.01274837,11/18/2017 6:26:53 PM,11/18/2017 7:26:14 PM
2c641118-a286-4180-a5a1-c1e6f7ad12d4,BTC-XRP,LIMIT_SELL,659.54212815,0.00003974,0.00006551,0.02621298,12/16/2017 3:28:42 PM,12/16/2017 3:34:46 PM
```

**Comment by LefterisJP** [comment]
That's weird. Bittrex global still works and API seems to be fine. But sure yes the CSV import is not a bad idea ofc.

**Comment by LefterisJP** [comment]
This is done via https://github.com/rotki/rotki/issues/7119
