### ISSUE TITLE
Allow the editing of custom events in the history view

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#6549]
## Abstract

At the moment it is only possible to edit transaction events. We should make it so that you can also edit other types of events that for example are imported via the generic csv function.

## Motivation

Allow users to edit any event possible 

## Specification

- [ ] Allow editing of all types of events

**Comment by kelsos** [comment]
@lukicenturi I guess we can consider this done and closed? Do we have an entry in the changelog for this?

**Comment by lukicenturi** [comment]
> @lukicenturi I guess we can consider this done and closed? Do we have an entry in the changelog for this?

Yes we have the changelog, Im closing this
