### ISSUE TITLE
Import Data - Custom Import - Import events

### ISSUE THREAD

**Issue by CounterWater** [rotki/rotki#6552]
## Problem Definition

Hi, I used the sample generic events template and while I can see them in the History Events they do not show up in the PnL
[Manual Import - Sheet2.csv](https://github.com/rotki/rotki/files/12448115/Manual.Import.-.Sheet2.csv)

Operating system: Windows
Rotki version: 1.30.1

**Comment by LefterisJP** [comment]
> ## Problem Definition
> Hi, I used the sample generic events template and while I can see them in the History Events they do not show up in the PnL [Manual Import - Sheet2.csv](https://github.com/rotki/rotki/files/12448115/Manual.Import.-.Sheet2.csv)
> 
> Operating system: Windows Rotki version: 1.30.1

Hello, we had this discussion in discord with you and I opened this issue for it: https://github.com/rotki/rotki/issues/6550
