### ISSUE TITLE
Move convex mapping of gauges to the globaldb

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#6555]
At the moment we have a mapping of convex gauges https://github.com/rotki/rotki/blob/7bac350a878e3c9d68b926ee3fd97238888d5585/rotkehlchen/chain/ethereum/modules/convex/constants.py#L46 that needs to be moved to the globaldb and dynamically pull them as we do in this test https://github.com/rotki/rotki/blob/7bac350a878e3c9d68b926ee3fd97238888d5585/rotkehlchen/tests/unit/decoders/test_convex.py#L38

Without them the convex decoders might fail to recognise some pools

**Comment by thormiwa** [comment]
Hi @yabirgb I will like to work on this. 

Going through it, i think what is expected is to Move the Convex pool information from a dictionary to the global database and also a function Retrieves Convex pool information from the global database. So in places where `CONVEX_POOLS[context.tx_log.address]` was previously used, the function will now be used to dynamically fetch Convex pool information.

Is there anything else you would like me to keep in mind while implementing this change, any particular approach you would prefer or any more clarity i would need?

Thank you!

**Comment by yabirgb** [comment]
Hello @thormiwa ! I'm so sorry!!! Completely missed your message. We will take this issue since it will ship in the next release. If you are interested in taking an issue you can visit our discord https://discord.rotki.com/ and I'll help you find one and guide you if needed. Again sorry, I missed your ping
