### ISSUE TITLE
Improve how error message appears on merge assets form

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#6625]
## Problem Definition

![image](https://github.com/rotki/rotki/assets/2269732/9fe3d49f-4ec6-4c6f-aefe-fa1cf832178e)
Use vuelidate to parse the external messages and show the validation error to the proper field

## Tasks

- [ ] display only the message at the proper field

**Comment by LefterisJP** [comment]
Shoudl be fixed by https://github.com/rotki/rotki/pull/6628
