### ISSUE TITLE
Support Aave v3 positions in all chains

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#6636]
## Abstract

Auto detect aave v3 positions in mainnet (and other chains) and show them to the users. That means at least detect borrowed loans and show them as liabilities. The normal v3 tokens that are being lent should also be auto-detected and if they are not we should make sure they are.

Regarding a dedicated view for Aave v3 I am not sure if it is warranted as dedicated views don't scale well, are hard to maintain and for projects that have not paid for them it makes no financial sense for us.

## Motivation

We support v2 positions but v3 not. So we should support them at least in mainnet

## Specification

Figure out what's needed to do and do it.

**Comment by dcbuild3r** [comment]
Thank you for opening up the issue!
