### ISSUE TITLE
No green icon when opening the app with an apikey for an external service 

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#664]
## Problem Definition

When inputting an api key for an external service the api key field becomes green. But when opening the app again after having input an API key the field is not green.

## Task

Make the behavior consistent between both first time addition and any other run of the application.

**Comment by kelsos** [comment]
@LefterisJP after loading does the field has any value inside? can you provide a screenshot of how it appears?

**Comment by LefterisJP** [comment]
![2020-01-30-155303_967x291_scrot](https://user-images.githubusercontent.com/1658405/73460356-a44f0500-4378-11ea-95d9-54011b8b5cf6.png)

This is how it looks like after a restart

**Comment by kelsos** [comment]
@LefterisJP ok seen the cancel icon there it seems that when reloading the component enters edit mode `editMode = true`
