### ISSUE TITLE
Percentage on overall balances isn't accurate becuase small rounding error

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#6644]
## Problem Definition

The percentage in overall balances often showing red badge because of small rounding error.
We find the delta by comparing a variable in `BigNumber` and another variable in js primitive `number` which resulting a small rounding error.

<img width="442" alt="image" src="https://github.com/rotki/rotki/assets/26648140/d0b6a49f-ae97-42f4-8c6c-50b1debd77e3">

**Comment by kraikov** [comment]
Hello. In the last couple of days I'm trying to get familiar with the codebase.

I tried to review the code, but I can't seem to find discrepancy in the comparison of the balance delta.

Are you referring to: https://github.com/rotki/rotki/blob/8a8ff77b991ae2625d613534aaf474a94823efee/frontend/app/src/components/dashboard/OverallBalances.vue#L64-L66

`totalNetWorth` seems to be BN along with `startingValue`

**Comment by lukicenturi** [comment]
> Hello. In the last couple of days I'm trying to get familiar with the codebase.
> 
> I tried to review the code, but I can't seem to find discrepancy in the comparison of the balance delta.
> 
> Are you referring to:
> 
> https://github.com/rotki/rotki/blob/8a8ff77b991ae2625d613534aaf474a94823efee/frontend/app/src/components/dashboard/OverallBalances.vue#L64-L66
> 
> `totalNetWorth` seems to be BN along with `startingValue`

In some case, the starting value is equal to the current `totalNetWorth` https://github.com/rotki/rotki/blob/develop/frontend/app/src/store/statistics/index.ts#L143

The problem is the `startingValue` get double conversion (BN -> number -> BN) and lose the precision

**Comment by lukicenturi** [comment]
@kraikov are you working on this issue? If not, it seems trivial and I can fix it.

**Comment by kraikov** [comment]
@lukicenturi go ahead, I'll take my time to play around with the codebase before contributing.
