### ISSUE TITLE
Periodic client query error in Docker Swarm environment

### ISSUE THREAD

**Issue by hacketaler** [rotki/rotki#6668]
In a Docker Swarm environment, I'm experiencing an error with Rotki. The error message is: "Error at periodic client query: No user is currently logged in". I suspect this issue might be related to the instances in the Docker Swarm, but I'm not entirely sure.

Set up Rotki in a Docker Swarm environment.
Log in to the application.
After a while, the error message "Error at periodic client query: No user is currently logged in" appears. Repeated every minute!
Expected behavior The application should remain logged in and not produce a periodic client query error.

System information:
OS: Raspi OS
Rotki version: latest (1.30.2)
Docker version:  24.0.6
Docker Swarm Information:
Nodes: 5 (Raspi 4)
Manager Nodes: 3
Worker Nodes: 2
Replicas of Rotki: 2
NFS used for shared volume
Additional context The Docker Swarm is set up with 5 nodes (3 managers and 2 workers). We are using NFS for shared volumes across the nodes. The issue seems to persist even after ensuring proper NFS configuration and permissions.

Any help in resolving this issue would be greatly appreciated. Thank you.

**Comment by LefterisJP** [comment]
Hey @hacketaler thanks for opening the issue and trying rotki in a new unique way!

Can you give more information on how exactly you setup rotki and the swarm environment? We are not aware of anyone else trying anything similar so lots of things could be off here. I am not familiar with how swarm is supposed to work so not sure what could go wrong.

In general rotki runs locally in a docker environment and exposes the frontend to be accessed remotely via same machine or other machine in same network (but has to have proper authentication to protect unauthorized access: https://rotki.readthedocs.io/en/latest/usage_guide.html#docker).

If swarm means you are opening multiple rotki images then lots of things could go wrong. You only need 1 image for this. And then make sure backend/connects to frontend (which the docker images does on its own).

Our docker expert @kelsos will be back on Wednesday so answering may take a bit more time. Though we can still try to figure stuff out.

In the meantime also feel free to pop by our discord (has captcha verification) to chat with us and other users: https://discord.rotki.com/

**Comment by hacketaler** [comment]
Hi

I'm not a docker-expert, just making experiments with the pi-cluster ;)

This is the docker inspect log of the service:
(maybe it helps)

****@piCluster01:~ $ sudo docker service inspect rotki
[
    {
        "ID": "hq5ar********",
        "Version": {
            "Index": 1106478
        },
        "CreatedAt": "2023-09-29T20:16:26.439432022Z",
        "UpdatedAt": "2023-09-29T20:52:23.567665835Z",
        "Spec": {
            "Name": "rotki",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "rotki/rotki:latest",
                    "Env": [
                        "TZ=Europe/*****"
                    ],
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "vrotki",
                            "Target": "/data",
                            "VolumeOptions": {
                                "DriverConfig": {
                                    "Name": "local",
                                    "Options": {
                                        "device": ":/mnt/clusterssd/cluster/rotki",
                                        "o": "addr=192.168.1.195,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4",
                                        "type": "nfs"
                                    }
                                }
                            }
                        },
                        {
                            "Type": "volume",
                            "Source": "vrotki",
                            "Target": "/logs"
                        },
                        {
                            "Type": "volume",
                            "Source": "vrotki",
                            "Target": "/config"
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0,
                    "Window": 0
                },
                "Placement": {},
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 2
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 8084,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "PreviousSpec": {
            "Name": "rotki",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "rotki/rotki:latest",
                    "Env": [
                        "TZ=Europe/****"
                    ],
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "vrotki",
                            "Target": "/*",
                            "VolumeOptions": {
                                "DriverConfig": {
                                    "Name": "local",
                                    "Options": {
                                        "device": ":/mnt/clusterssd/cluster/rotki",
                                        "o": "addr=192.168.1.195,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4",
                                        "type": "nfs"
                                    }
                                }
                            }
                        }
                    ],
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0,
                    "Window": 0
                },
                "Placement": {},
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 2
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 8084,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 8084,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 8084,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "mb8*********",
                    "Addr": "10.0.0.30/24"
                }
            ]
        },
        "UpdateStatus": {
            "State": "completed",
            "StartedAt": "2023-09-29T20:51:07.36217815Z",
            "CompletedAt": "2023-09-29T20:52:23.567604651Z",
            "Message": "update completed"
        }
    }
]

**Comment by hacketaler** [comment]
Hi
additional info: Reducing the replicas to 1 solves the error.

**Comment by LefterisJP** [comment]
> Hi additional info: Reducing the replicas to 1 solves the error.

yeah this makes sense. You are trying to run multiple instances of rotki in swarm. This is not possible.

**Comment by kelsos** [comment]
Yes, only 1 replica will work but not more. Our docker image is not designed to run replicated.
