### ISSUE TITLE
Integrate WOO X Exchange 

### ISSUE THREAD

**Issue by xAltsuki** [rotki/rotki#6688]
## Abstract

Add WOO X Exchange connection on Rotki!

## Motivation

1) Increase number of exchanges you can connect to.
2) WOO X has grown a lot in the past 2 years and is now a CEX that is used by a lot of crypto people (especially more native ones).

## Specification

WOO X has a read only API key like all the CEXs integrated on Rotki and it has been integrated in similar apps like CoinMarketMan.

**Comment by LefterisJP** [comment]
> ## Abstract
> Add WOO X Exchange connection on Rotki!
> 
> ## Motivation
> 1. Increase number of exchanges you can connect to.
> 2. WOO X has grown a lot in the past 2 years and is now a CEX that is used by a lot of crypto people (especially more native ones).
> 
> ## Specification
> WOO X has a read only API key like all the CEXs integrated on Rotki and it has been integrated in similar apps like CoinMarketMan.

hey hey thanks for opening the issue. You probably misunderstood what I meant by my comment in the Twitter DM. I meant since we don't have anybody using it we would need someone who uses it to share their api key with us so we can test the implementation we are making.

**Comment by xAltsuki** [comment]
I can do that no problem!

**Comment by xAltsuki** [comment]
Also when integrating WOO X if you could add their native staking for their token $WOO would be amazing!
