### ISSUE TITLE
Add Solana Support (Wallets, Staking, etc)

### ISSUE THREAD

**Issue by xAltsuki** [rotki/rotki#6689]
## Abstract

Please add Solana support to the program! We need to be able to track Solana wallets, SOL liquid staking, etc...

## Motivation

Solana is the second most used blockchain after Ethereum in Staking TVL, NFT trading volume, etc... You must have Solana support, it would be useful to a lot of already existing users and it would help onboard more users. I personally NEED to track Solana wallets (like Phantom wallet) and also my Solana staking through JitoSOL.

**Comment by xAltsuki** [comment]
also add Solscan API support like you have for Etherscan pls!

**Comment by LefterisJP** [comment]
There is already an issue for Solana here: https://github.com/rotki/rotki/issues/2394
