### ISSUE TITLE
Integrate RealT properties assets tokens ?

### ISSUE THREAD

**Issue by anthony-robin** [rotki/rotki#6693]
[RealT](https://realt.co) is a company that provide tokenized real estate for investors.

They deployed properties smart contract into Ethereum and Gnosis blockchains as you could see on any properties details present in their [marketplace](https://realt.co/marketplace).
I would love to be able to visualize properties I own from my Ethereum/Gnosis address directly in the Rotki interface !

For that, it would require !1591 to be done first as Gnosis is not yet supported.

What do you think about it ? :)

**Comment by LefterisJP** [comment]
Hey Anthony! Sure.

#1591 is coming very soon.

Now as for this issue, once gnosis is on, I guess if it's just a token you can add it and track it in rotki normally? Or is there something protocol specific you would like to see tracked by rotki?

If so what? Since we are not familiar with this RealT marketplace some details would help here

**Comment by anthony-robin** [comment]
Hi Lefteris, that's awesome, thank you !

Each property is tokenized in a number of parts, with a dedicated smart contract address on Gnosis/Ethereum:
 
Example with [15824 Cheyenne St, Detroit](https://realt.co/product/15824-cheyenne-st-detroit-mi-48235#tab-title-blockchain_tab) property that is split into 1.400 tokens of around 50$:
- Gnosis contract: https://gnosisscan.io/token/0x4df8c0990e1f02810d6a27c452cd70b39f2e0a2c
- Ethereum contract: https://etherscan.io/token/0x4df8c0990e1f02810d6a27c452cd70b39f2e0a2c

Then, each holders receive the corresponding number of tokens the bought on the marketplace on their Gnosis/Ethereum wallet address.

To resume, I would expect Rotki to detect:
- each properties I do have on my Gnosis/Ethereum address
- the number of token I own for each properties
- the computed price of each properties (number of token owned * token unit price)

So my interrogations are:
- Is it something Rotki could detect automatically from user Gnosis address or each properties contract had to be added manually somewhere in the Rotki code ?
- Are all informations readable directly from the smart contract or Rotki does have to query the RealT API for extra meta information ? (not sure if the API is publicly available)

Thank you :)

**Comment by anthony-robin** [comment]
Closing as last release has automatically detected all RealT tokens on Gnosis chain 💯 🎉 🥳
