### ISSUE TITLE
Graph for multi chain assets is missing historical data

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#6717]
## Problem Definition

I have wstEth in optimism, ethereum and arbitrum but the graph for the asset only contains the last balance that is a virtual point added by the frontend. As it can bee seen in the console the response from the backend is empty.

Clicking in one of the chains shows correctly the graph of balance

## Logs

![image](https://github.com/rotki/rotki/assets/5068010/dc8bfcf2-5647-4f40-8b2b-606f469163bb)

![image](https://github.com/rotki/rotki/assets/5068010/6dc9f7cd-af99-4d8d-87b5-e8ef6eabbcc5)

The payload in the request was

```
{"from_timestamp":0,"to_timestamp":1696855724,"collection_id":217}
```

to http://127.0.0.1:4242/api/1/statistics/balance

### System Description

Operating system: Macos 
Rotki version: Happens in the latest release and too in develop

**Comment by LefterisJP** [comment]
I have USDC across 2 chains in production (1.30.2) and I don't see any problems
