### ISSUE TITLE
Identify all the documentation link urls in the frontend and introduce a mechanism to verify

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#6762]
## Abstract

We need to identify all the links we have in the frontend to our documentation.
Create a task/action to identify all the links probably on CI nightly that checks if the links are valid and not leading to 404 or something.

## Motivation

Ensure that we don't accidentally have broken links because we changed something 

## Specification

- [ ] Identify and move all links to a central place
- [ ] Create some automated way to verify that links are working (nightly would be enough)

**Comment by kisharnath** [comment]
I would like to work on this

**Comment by kelsos** [comment]
Hey @kisharnath as a first step you would have to go through the frontend codebase and identify external urls
and then move them all all to an links.ts file that would look something like:

```typescript
export const externalLinks = {
  documentation: 'url'
} as const;
```

and then in the place where the link is used you will have to do something like `externalLinks.documentation`

for the checking probably a simple script that goes through the keys and checks if the value url gives a 200 or not, for anchors we might have to enhanced it in the future, but as a first step the 200 check would suffice

**Comment by lukicenturi** [comment]
Hi @kisharnath any progress about this issue?
