### ISSUE TITLE
Make it possible to download PnL reports by exchange, wallet or specific asset

### ISSUE THREAD

**Issue by xAltsuki** [rotki/rotki#6793]
The same way you can query through your transfers/actions by exchange, wallet or specific asset, you should be able to specify those options to print out a PnL report.

If I could print the cumulative of all my trades in one specific asset across all connected exchanges and wallets and see my total PnL from all the buys and sells it would be very useful personally & tax wise.

Same for just getting the cumulative PnL of all I've done on 1 exchange.

**Comment by LefterisJP** [comment]
hey @xAltsuki thanks a lot for the issue. So just like with https://github.com/rotki/rotki/issues/2942 I am gonna close and consolidate to https://github.com/rotki/rotki/issues/6427

As the approach we will slowly take is conslidate PnL report into the history events view and using its filters. So what you ask should eventually become possible when this happens. Though keep in mind it's gonna be a big refactoring to do, so not something coming very soon.

But its in our plans.
