### ISSUE TITLE
The backend query task died unexpectedly: local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by 0xbok** [rotki/rotki#6811]
## Problem Definition

Starting up rotki, updated the desktop app, and many background tasks are failing with the same error.

![Screenshot 2023-10-24 at 00 53 36](https://github.com/rotki/rotki/assets/1689531/c11ac3a3-981d-4156-9006-7cfc0280d8ae)

### System Description

Operating system: macOS Monterey
Rotki version: 1.30.2

**Comment by LefterisJP** [comment]
Hey @0xbok can you please provide logs for these errors? And give more details in how the upgrade hapened? From which version to which?

For how to enable and get the logs check here: https://rotki.readthedocs.io/en/latest/contribute.html#id2

Probably best to also join our discord: https://discord.rotki.com/ and chat there in more real time for understanding what's wrong.

**Comment by LefterisJP** [comment]
Closing this issue due to lack of further information/response.

**Comment by LefterisJP** [comment]
A different user who saw a similar error gave us some logs. The fix is here: https://github.com/rotki/rotki/pull/7169

But this just fixes the exception error and make it handle it more elegantly.

The actual error is a network error on the user's side about the inability to contact etherscan due to some network error. In the other user;s case it was inability to resolve the domain

**Comment by 0xbok** [comment]
In my case, it’s not able to connect to any rpc (etherscan for all chains
shows connected). I’ll send my debug logs soon.

I tried deleting the app and all it’s local data, then installing again.
But nothing changed.

**Comment by LefterisJP** [comment]
Hey that's great to hear that you are still looking at it!

For debug logs it;s best to join discord and DM it to someone from the team. Can be me: https://discord.rotki.com/

Sounds like a network problem and we could figure out by looking at logs and doing some back and forth.
