### ISSUE TITLE
Verify if we can add accounts in parallel

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#682]
## Abstract

As part of #677, the account creation is converted to asynchronous using the task infrastructure and the `async_query=true` parameter. Currently, the UI will block (disable the button) and will not allow the user to perform an action if one operation is already running. The button is again enabled as soon as the async task is successfully processed.

## Motivation

We need to verify if the new API can handle adding accounts in parallel and see if this UI blocking makes sense or not. In there is no limit the artificial UI blocking should be removed.

**Comment by LefterisJP** [comment]
Blocking there is good. For many reasons. 

1. We don't have locks there yet
2. Even if we added locks, then we already have logic to add multiple accounts in one go right now, so multiplying that is just gonna make things more complicated.

Does that sound sufficient @kelsos ? Can we close?

**Comment by kelsos** [comment]
yup let's close, We have the multi-account addition so at least that solves the problem a bit.
