### ISSUE TITLE
MCB token price is different from Arbiscan, Zerion, Coingecko

### ISSUE THREAD

**Issue by PerfectSense1** [rotki/rotki#6898]
## Problem Definition

MCB ("MCDEX Token") has a price of about $42, whilst the price listed on Coingecko and Zerion, but ALSO when clicking through to Arbiscan from the link in Rotki, is $12. The contract addresses shown for the token are the same (0x4e352cF164E64ADCBad318C3a1e222E9EBa4Ce42), so that's where my understanding of this issue stops :-). 
This has been like this for at least 1-2 weeks now. 

My impression is that it is just this token that's off. A minor issue AFAIK but maybe worth looking into!

Cheers

## Logs

-->

### System Description

Operating system: Mac Sonoma 14.1
Rotki version:1.30.2

**Comment by lukicenturi** [comment]
Hi @PerfectSense1, you are welcomed to ask this kind of question in discord directly. About the price, there are some possibility:
1. You may (intentionally or unintentionally) set manual latest price to the asset. Can you check if there is  a small orange icon beside the price of the asset?
2. Something wrong with your db. If this is the case, we would need to see your db to help.

**Comment by LefterisJP** [comment]
I am closing this issue due to lack of further information/response.
