### ISSUE TITLE
Create Gitcoin Grant report for grant owners

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#692]
## Feature Description

**Possibly a Premium Only Feature**

Running a Gitcoin grant is cool and if the community values your project and in combination with CLR funding a good amount of funds can flow into an Ethereum account.

It would be really nice if there was a way for users to input an Ethereum account and have it auto-detected that it's a receiving address for a Gitcoin grant.
Once that is done all ERC20 transactions to that grant, along with the USD value of the token at the time can be counted in as profit and reported in a special Grants Tab.

This way later when the owner of the grant uses those tokens elsewhere (say in an exchange) Rotki will know where they came from. Also if the owner needs to report them as income he can use the Rotki grants tab to export all of his inbound transactions into a CSV which can then be imported into a google spreadsheet and share it with their accountant.

### Frontend

- If not yet existing add a left-sidebar top level menu called "Decentralized Finance". Under it should be a sub-menu entry called "Gitcoin Grants".
- This should show a page which will render only if the user has premium. If not it will ask the user to purchase a premium subscription.
- The aforementioned page would show all ethereum accounts that have been detected as grant recipients. For each account it will allow the placing of a label, so that the user can name his grant. (Could we see that from onchain data?). Each account would show a list of all transactions that are grant related, token transferred and USD/EUR/XXX value at the time of transfer. At the end there should be a total of funds received from the grant.
- There should be a date range component which would allow narrowing down the range of the transactions to display.
- There should also be an option with a button to export these data in CSV format.

### Backend

- Only if the user has premium do all the tasks below
- Query all user addresses to see if they own a grant. And then use the gitcoin api endpoint we asked for [here](https://github.com/gitcoinco/web/issues/6493) to get all payment details.
- Add rotki api endpoint to query the data
- Include it in the PnL report

**Comment by isidorosp** [comment]
You could also employ the reverse (scanning the user's accounts for accounts sending tx to gitcoin grants) in order to tag the relevant transactions/events with a desired tag/event classification (e.g. outgoing donation).

**Comment by LefterisJP** [comment]
True, but that would be a different issue. Plus it would require, ability to query zksync transactions.

**Comment by prestonvanloon** [comment]
Interested in this!

**Comment by LefterisJP** [comment]
Hey @prestonvanloon thanks for +1ing this. We will see what we can do. It should be done at some point as we as rotki also need it. But it's good to see someone else also wanting it.

Helps a lot with prioritization

**Comment by LefterisJP** [comment]
I will start this right now with importing the export of the CSV as one way. And then we can also make it via the API whenever that is ready.

**Comment by LefterisJP** [comment]
Okay unfortunately there is a bug in the export that is gonna slow us down: https://github.com/gitcoinco/web/issues/9213

Will see if I can work around it until they fix it with historical price queries and determine amount from usd value + historical price.

**Comment by LefterisJP** [comment]
So @kelsos for the frontend part of this as discussed in the standup today you need a dedicated section in the frontend that does the following:

1. Allows user to specify a grant id (integer) and a period (by default is all time) for which to import gitcoin grant events.
2. Show a table of all grant events. tx_id for ethereum ones should use the exporer option. For zksync, zkscan. Example: https://zkscan.io/explorer/transactions/b75d5a7b7073a8d306492641955106145a16728250243c6ed86c205857b75807
3. Allows user to specify a single grant (or no grant for all) and delete all saved gitcoin event data
4. Generates a report by taking a grant id and a given period. The report (done in the backend) should just sum up the gained assets in the period. Have a total gained in profit currency and an entry per asset. How much was gained per asset and its profit currencty value.
