### ISSUE TITLE
Add new asset: Veno Finance (VNO)

### ISSUE THREAD

**Issue by CodeShakingSheep** [rotki/rotki#6929]
**Asset name:** Veno Finance
**Asset symbol:** VNO
**Coingecko link:** https://www.coingecko.com/en/coins/veno-finance
**Cryptocompare link:** /

**Comment by LefterisJP** [comment]
hey @CodeShakingSheep  now the issues are opened anyway but please if you want to ask for multiple assets just make a single issue.

Also you probably know you can already add them to your local rotki on your own: https://rotki.readthedocs.io/en/stable/usage_guide.html#adding-editing-an-asset

We will add them in next release and close all issues when doing so.

**Comment by CodeShakingSheep** [comment]
Hi @LefterisJP ,
Thank you for the hint. It makes sense. Next time, I will open a single issue for multiple assets. Sorry for the overhead. Glad to hear you'll add the assets. Thanks.
