### ISSUE TITLE
OSX: v1.1.0  - Python backend 'crushed'

### ISSUE THREAD

**Issue by D8N1** [rotki/rotki#693]
## Problem Definition

After v1.10  update. Python backend crashed. 
Sweet, but brief look at the new GUI. Then...

[rotkehlchen.log](https://github.com/rotki/rotki/files/4162402/rotkehlchen.log)

05/02/2020 22:33:28 GMT -- DEBUG:rotkehlchen.server:Shutdown initiated
05/02/2020 22:33:28 GMT -- DEBUG:rotkehlchen.server:Waiting for greenlets
05/02/2020 22:33:28 GMT -- DEBUG:rotkehlchen.server:Waited for greenlets. Killing all other greenlets
05/02/2020 22:33:28 GMT -- DEBUG:rotkehlchen.server:Greenlets killed. Killing zerorpc greenlet
05/02/2020 22:33:28 GMT -- DEBUG:rotkehlchen.server:Killed zerorpc greenlet
05/02/2020 22:33:28 GMT -- DEBUG:rotkehlchen.server:Shutdown completed
![Rotki failed to start ](https://user-images.githubusercontent.com/40266078/73890271-7b8fa980-4869-11ea-910d-758002de2701.png)

### System Description
Vladislavs-MacBook-Pro:~ vladislavsurkov$ uname -a
Darwin Vladislavs-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Dec  1 19:19:56 PST 2019; root:xnu-4570.71.63~1/RELEASE_X86_64 x86_64
Vladislavs-MacBook-Pro:~ vladislavsurkov$ command -v geth && geth version
Vladislavs-MacBook-Pro:~ vladislavsurkov$ command -v parity && parity --version
/usr/local/bin/parity
Parity Ethereum Client.
  version Parity-Ethereum/v2.5.12-stable-29ebddc64f-20191216/x86_64-macos/rustc1.39.0
Copyright 2015-2019 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf/Greeff
   Habermeier/Czaban/Gotchac/Redman/Nikolsky
   Schoedon/Tang/Adolfsson/Silva/Palm/Hirsz et al.

**Comment by LefterisJP** [comment]
Hey @D8N1 thank you for the issue!

I can confirm on my old macbook. It's only on the packaged OSX version. I have a suspicion what it is and why it got missed by our tests. When ready the fix will be included in a hotfix release.

**Comment by LefterisJP** [comment]
This should have been fixed in the hotfix v1.1.1 release: https://github.com/rotki/rotki/releases/tag/v1.1.1

Please re-open or open another issue if this is not the case.
