### ISSUE TITLE
Add ETFs, stocks etc as tracked user assets

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#700]
## Feature Description

Many people who are also into traditional finance trade Exchange Traded Funds (ETFs) and would love to have the data of their holdings in ETFs available along with the rest of the assets shown by Rotki.

The user would simply in a special pane add the ISIN number of the ETF he has purchased, the date and the amount. Same thing for selling events. Rotki would take care of the rest and show him his profits or losses by that ETF depending on its current price.

This would be a **premium** only feature.

## Specification

**Important: 28/05/2022** Whoever implements this check with the team since the specification of the issue was first written more than 2 years ago!!!

### Frontend

- If not yet existing add a left-sidebar top level menu called "Traditional Finance". Under it should be a sub-menu entry called "ETFs".
- This should show a page which will render only if the user has premium. If not it will ask the user to purchase a premium subscription.
- The aforementioned page would show all ETFs owned by the user and the netvalue in total he has in them. Additionally knowing the purchase and sell prices it will display profit/loss until now.
- There will also be a menu to input new buy/sell events for ETFs. The required data will be the date, the ISIN number, the amount, and the type (buy/sell). 
- There should be a date range component which would allow narrowing down the range of the transactions to display.

### Backend

- Create a new location type for ETFs
- Create a new data structure for ETFs
- Take ETFS into account in the tax report and make a separate CSV report for them.
- Add an option to ignore ETFs in the tax report. Some people may not want the extra data, or use another tool.
- Add premium only API endpoint to write ETF data to Rotki
- Add premium only API endpoint to query ETF data from Rotki
- Only if the user has premium do all the tasks below

An API that may allow us to query for these data is: https://iexcloud.io/docs/api/#dividends

**Comment by LefterisJP** [comment]
Related issue: https://github.com/rotki/rotki/issues/2021

**Comment by LefterisJP** [comment]
I am closing this as we kind of have this functionality with #2021 and if we do try automatic price/balance querying that shiould be a per-service issue and not in a generic issue like this.

**Comment by actuallymentor** [comment]
Hello Lefteis!

I'd recomend reopening this. Tradfi assets are a discrete asset class, and manual custom assets do not fit in the Rotki vision as I understand it.

As I understand it there are free APIs available for this information:

- [Alpha Vantage](https://www.alphavantage.co/) has a free tier of 5 RPM, 500 RPD, and has language on the website suggesting partnership options. Rotki could even offer a price proxy for this as a (premium) service
- [Marketstack](https://marketstack.com/) offers free end of day prices, and I don't think Rotki needs intraday prices
- Many others have paid tiers, which Rotki could easily offer as a price proxy (pending license options I guess)

I understand that custom assets are a workaround, but I wouldn't see them as a user friendly solution to the extent of closing this issue.

**Comment by LefterisJP** [comment]
hey @actuallymentor!

We absolutely want this. The reason this got closed is that it's too generic. ETFS, stocks etc. as an issue is huge.

I would go and split them into subissues and address them one by one as my last comment said.

For example from the APIs you mentioned make an example only of stocks/ETF with the marketstack api.

I mean we can also just turn this issue into this one and open more for each different integration.

Extremely generic issues in this repo tend to live forever -- and never be implemented due to scope creep.

Small issues can also be taken by externals. Would you like to try and spec and make this into reality? Then I can reopen this issue with a more concentraded scope.

> manual custom assets 

They are a catch all solution. They match rotki's approach of customizability. You have a painting from you great grandma that's appreciated to be at 100k? Own an apartment? You need to manually input it.
