### ISSUE TITLE
Replace asset movements with history events

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7007]
## Abstract

As part of our push towards having everything in the history events view, the asset movements (deposits & withdrawals) should be removed and consolidated into the history event view.

## Specification

Do it

**Comment by LefterisJP** [comment]
Related to this and part of touching asset movements, deposit withdawals could be https://github.com/rotki/rotki/issues/6206

**Comment by LefterisJP** [comment]
I have a 500+ lines diff branch for this in my local. It's outdated and probably useless by now. Will have to restart :sob:

**Comment by nicholasyoder** [comment]
This should be included in 1.37
