### ISSUE TITLE
Uniswap LP tokens are missing the protocol information

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#7024]
## Abstract

A user reported to me issues querying prices for Uniswap LP tokens. It turns out that the issue was that the asset was missing the `UNI-V2` protocol that is used by the inquierer to execute special logic and query the prices for the LP. In addition is hard to identify the asset since all use the same `UNI-V2` symbol.

## Specification

1. In https://github.com/rotki/rotki/blob/119397e52cc4ea5210fd50093c7e5098fdff16f9/rotkehlchen/chain/ethereum/modules/uniswap/v2/common.py#L297 we are not adding the information about the protocol. In the case of uniswap we have special logic to query prices https://github.com/rotki/rotki/blob/119397e52cc4ea5210fd50093c7e5098fdff16f9/rotkehlchen/inquirer.py#L163C30-L163C30
2. When adding or editing the token since we know the underlying tokens we can add their symbol to the name and symbol of the lp token

**Comment by LefterisJP** [comment]
Hmm so what is the actionable items here? To add it when adding the protocol?

Doesn't this also need a DB upgrade? Also ...  this is a dejavu. Didn't you mention this before and fixed it?

**Comment by yabirgb** [comment]
yes, add the protocol when adding the pool token. 

Ideally we would have one but not sure if it just better to re-decode the events with location=ethereum counterparty=uniswap-v2 eventy_type=deposit and let the decoder edit them

**Comment by LefterisJP** [comment]
> yes, add the protocol when adding the pool token.
> 
> Ideally we would have one but not sure if it just better to re-decode the events with location=ethereum counterparty=uniswap-v2 eventy_type=deposit and let the decoder edit them.
> 
> This exact thing I don't recall it

Let's take it to discord

**Comment by yabirgb** [comment]
Fixed by https://github.com/rotki/rotki/pull/7031
