### ISSUE TITLE
Remove "hacks" in the releases changelog

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#704]
## Problem Definition

To have a normal changelog while using the releases sphinx package we are now doing quite a few hacks.

In order to have all issues under a release included in its changelog we:

1. Specify which bugs/features are included for which release.
2. Add major to most bugs to make them render under the release they
are in
3. For all features without an issue, assign a big number so that it
can be includes in the list of issues addressed by the release.

All this can go away if https://github.com/bitprophet/releases/issues/92 is implemented.

## Task

Watch for implementation of that issue and if complete remove all these hacks.

**Comment by WyseNynja** [comment]
This issue is still referenced in requirements_docs.txt. Is the fork still needed there?

**Comment by LefterisJP** [comment]
> This issue is still referenced in requirements_docs.txt. Is the fork still needed there?

I guess yeah. We never re-visited this and the upstream issue is still open. I think the upstream project is abandoned :sweat_smile:

**Comment by kelsos** [comment]
> > This issue is still referenced in requirements_docs.txt. Is the fork still needed there?
> 
> I guess yeah. We never re-visited this and the upstream issue is still open. I think the upstream project is abandoned 😅

Activity resumed in the summer of 2022 and the last activity/release was a few weeks ago so there may still be hope. 😛
