### ISSUE TITLE
"Could not read blocknumber from etherscan getblocknobytime result Error! No closest block found"

### ISSUE THREAD

**Issue by pcaversaccio** [rotki/rotki#7061]
## Problem Definition

I updated this morning to the latest rotki version `1.31.1` and it looks like the Etherscan API is unstable. Not sure you can do much (maybe a fallback option?), but just wanted to let you know.

## Logs

![image](https://github.com/rotki/rotki/assets/25297591/703480af-3ca1-47f0-b38b-42cf1dcae933)

### System Description

Operating system: Win
Rotki version: `1.31.1`

> PS: Just tried on my Ubuntu machine, and faced the same issue

**Comment by LefterisJP** [comment]
This is not an actionble issue. This is just a warning. If you read the entire error, you will see that etherscan, which is where we get the timestamp -> blocknumber had a problem on their side. We should probably downgrade those errors. To not appear to the user like this.

**Comment by pcaversaccio** [comment]
Closing since resolved via https://github.com/rotki/rotki/pull/7067.
