### ISSUE TITLE
Disabling sync for a exchange disables all the exchanges in the same location

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#7082]
## Problem Definition

Currently we allow do disable sync in a per exchange instance way, that is `location + name` but in the code we are doing

```python
with self.db.conn.read_ctx() as cursor:
    excluded_locations = {exchange.location for exchange in self.db.get_settings(cursor).non_syncing_exchanges}  # noqa: E501

if location is not None:
    if location not in excluded_locations:
        self.query_location_latest_trades(location=location, from_ts=from_ts, to_ts=to_ts)

    return
```

that ignores all the exchanges in the same location and not just the combination `location + name`

![imagen](https://github.com/rotki/rotki/assets/5068010/7f7ecefa-02fb-4900-a202-b42b8ce8451a)

### System Description

Operating system: macOS
Rotki version: 1.31.1

**Comment by LefterisJP** [comment]
Should be closed by #7125
