### ISSUE TITLE
Support Compound V3 in all chains. Mainnet, Arbitrum, Base and Polygon.

### ISSUE THREAD

**Issue by CodeShakingSheep** [rotki/rotki#7084]
## Abstract

In the DeFi Overview I can only see Compound assets on ETH chain. I would love to have support for the following chains on Compound v3.
- Arbitrum
- Base
- Polygon

## Motivation

For example I have supplied an asset (USDC) on Compound on Polygon chain which I would like to see there too. The good thing is that I can see Compound USDC (cUSDCv3) under the blockchain balances in Polygon PoS balances. The value added is that the user has a better overview about how much is borrowed / supplied on Compound on all supported chains.

**Comment by LefterisJP** [comment]
Hey thanks for the issue, the DeFi overview is not meant to be multi-chain and will probably be deprecated in the future as we can't have one dedicated view per protocol, at least the way it's developed right now. Will keep this open though for a bit until we decided what to do with the DeFi overview section

**Comment by CodeShakingSheep** [comment]
Hi @LefterisJP ,
Thanks for your fast reply. I understand that it's not feasible with the current design. Furthermore, I want to point out that my request refers to the whole DeFi menu item including views `Deposits` and `Liabilities`. Would be happy about an implementation of the missing chains soon.

**Comment by LefterisJP** [comment]
I will convert this issue to request for supporting Compound v3 in all chains with:

- Decoding of all related transactions properly
- Automatic detection of balances
- Detection of liabilities (if possible)
