### ISSUE TITLE
When using the custom import functionality to import trades, and unix timestamp format is in seconds, rotki dates a trade 1970

### ISSUE THREAD

**Issue by TimDaub** [rotki/rotki#7114]
- crypto hasn't existed in 1970
- when When using the custom import functionality to import trades, and unix timestamp format is in seconds (instead of milliseconds), then rotki dates a trade around 1970, which cannot be
- It should throw or at least warn when any trade is before the invention of bitcoin

**Comment by LefterisJP** [comment]
> * crypto hasn't existed in 1970
> * when When using the custom import functionality to import trades, and unix timestamp format is in seconds (instead of milliseconds), then rotki dates a trade around 1970, which cannot be
> * It should throw or at least warn when any trade is before the invention of bitcoin

Hey Tim for such things better ask us in discord. This is not an issue as the timestamp in that CSV is supposed to be in milliseconds.

**Comment by TimDaub** [comment]
I think this is a bug as the program should warn or error in case the transaction was made in 1970

**Comment by LefterisJP** [comment]
> I think this is a bug as the program should warn or error in case the transaction was made in 1970

The timestamp is in millseconds. IF you provide wrong data to the program you will get wrong results.
