### ISSUE TITLE
Decimal point gets removed when editing decimal value

### ISSUE THREAD

**Issue by rkalis** [rotki/rotki#7115]
## Problem Definition

When I want to add an amount in my manual balances, eg 1.4 to 1.6, rotki loses the decimal point when I remove the final decimal digit. See attached video. I'd expect the decimal point to be retained so I can easily change 1.4 to 1.6.

https://github.com/rotki/rotki/assets/9142187/69dbb243-e99b-44a0-b4c1-b4ac9f8d6649

### System Description
Operating system: macOS 13.2.1
Rotki version: 1.31.1

**Comment by kelsos** [comment]
Thanks @rkalis we will have a look at it
