### ISSUE TITLE
Remove bittrex and allow CSV import

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7119]
## Problem Definition

Bittrex is finally completely dead. Today the API stopped responding. https://twitter.com/LefterisJP/status/1735800944225300522

![2023-12-16_00-09](https://github.com/rotki/rotki/assets/1658405/aae3ac66-17cf-4701-a517-34e1181152f7)

## Task

So let's remove the exchange completely.

### Task 1 - Remove

Remove bittrex and anything related to its API from the app. Keep the bittrex location.
### Task 2 - Allow importing bittrex data via CSV

![2023-12-16_00-18](https://github.com/rotki/rotki/assets/1658405/a075f3cf-fd32-4e2d-bd52-e21f3e5c361e)

There is 2 types of files that people can get from the website right now.

**transactions history.csv**

```csv
Date,Currency,Type,Address,Memo/Tag,TxId,Amount
2023-03-09 01:46:42.043,BTC,WITHDRAWAL,"ADDRESS","","TXID",-0.0001234
```

**order history per year.csv**

```csv
TXID,Time (UTC),Transaction,Order Type,Market,Base,Quote,Price,Quantity (Base),Fees (Quote),Total (Quote),Approx Value (USD),Time In Force,Notes
xx-yy-zz-dd,2017-09-01T12:03:05,Bought,Limit,SWT/BTC,SWT,BTC,0.00034100,731.28354007,0.00062343,0.24999841,,Good til cancelled,"Bought 431.18354007 SWT for 0.16999841 BTC"
```

-> Also in next develop upgrade go through the credentials of all removed exchanges and remove them since they are no longer possible to be used anyway and shouldn't stay in the DB. That is FTX, Bittrex and what's more? Note here: https://github.com/orgs/rotki/projects/11?pane=issue&itemId=47743438

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/7121

**Comment by DeLo1585** [comment]
.reopen

> Invalid CSV format: The given bittrex CSV file format can not be recognized

today i recieved my history through the bittrex.Zendesk Support. history contains data from about 2018 to 2020

actual format that was given from the csv are (just each 2 lines from whole csv)

<closed_Deposit>.csv
 
```
Deposit Uuid,Currency,Amount,State,Confirmations,Last Updated (UTC),TxId,Crypto Address
e7cbba5c-xxxx-xxxx-xxxx-6db9bd4f99c8,BSV,2.28890000,CONFIRMED,21,YYYY/MM/DD 23:50:27,a73bbe6be75xxxxdc62f6b2fcxxxcbfe628110a57409xxx194a96683c9311c83,bitcoincash:qqkwwjxxxxgffu56xxxxwuanx0xxxxhulsk9wnx9xw
6d5690bf-xxxx-xxxx-xxxx-95d05abfaea5,LTC,10.50909447,CONFIRMED,9,YYYY/MM/DD 13:37:11,05f17addc3a17d44f2cxxxx2856938exxxx7b5d220fa4cf2597599faaxxxxb11,LSivdxxxxLcXjxxxxKofNnyxxxxY43xi9b
```

<closed_Withdrawals>.csv
```
Payment Uuid,Currency,Amount,Address,Opened (UTC),Provider,Authorized,Canceled,Tx Fee,TxId`
a2a2ba7b-xxxx-xxxx-xxxx-77408537ffcc,BTC,0.14950000,14qAy2QF9dTdaxXGwGbzCzCCej4zFEeyVr,YYYY/MM/DD 10:14:36,,true,,0.00050000,53422345e9c90d0ec6f5c388dc1d77bcbb3d85b2fc3b9819287de15c175ec169`
eed949d0-xxxx-xxxx-xxxx-335aa2db0d39,LTC,10.89000000,MJcNMwqeL1eykCgq2EYvNv2UybbgJv2yJe,YYYY/MM/DD 13:39:20,,,true,0.01000000,`
```

<closed_orders>.csv

```
Uuid,Exchange,Closed (UTC),Opened (UTC),Side,Type,Time In Force,Bid/Ask,Quantity,Remaining,Total,Avg. Price per Share,Commissions Paid`
98ac1703-xxxx-xxxx-xxxx-e99686c526d2,COVAL-BTC,YYYY/MM/DD 10:49:19,YYYY/MM/DD 10:49:19,BOUGHT,LIMIT,GOOD_TIL_CANCELLED,0.00000101,"2,000.00000000",0.00000000,0.00202000,0.00000101,0.00000505`
414bded1-xxxx-xxxx-xxxx-f61bfbf526f2,MCO-BTC,YYYY/MM/DD 10:52:47,YYYY/MM/DD 10:52:46,BOUGHT,LIMIT,GOOD_TIL_CANCELLED,0.00129687,15.00000000,0.00000000,0.01945303,0.00129686,0.00004862`
```

**Comment by DeLo1585** [comment]
I can imagine that any export processed individually might also have varying formats.

It might therefore be useful to offer an option to manually select—from the comma-separated CSV file—the specific data records required by Rotki.

**Comment by LefterisJP** [comment]
hey @DeLo1585 bittrex is a dead exchange. We are not going to readd yet another csv import if they changed it again. This would break imports for users who already have had csvs from bittrex and they are the majority.

You will have to follow the process to import a generic CSV and adapt your current ones to the generic format: https://docs.rotki.com/usage-guides/history/import-data#rotki-generic-import
