### ISSUE TITLE
Allow to mark assets as spam instead of just ignoring them

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#7124]
## Abstract

Marking an asset as spam works when the global db is shared between multiple users. At the moment we allow to ignore an asset easily but not to mark it as spam

## Specification

1. In the list of newly detected tokens we should allow to mark as spam instead of just ignoring it
2. In the asset view we should allow both: ignore and mark as spam

The endpoint for ignoring assets should take an additional argument to mark an asset as spam. The endpoint currently handling this is `/api/1/assets/ignored`

**Comment by kelsos** [comment]
@lukicenturi this we can consider done right? can you close the issue?
