### ISSUE TITLE
BTC - xpub incorrect balance after tx 

### ISSUE THREAD

**Issue by kyodhin** [rotki/rotki#7133]
## Problem Definition

When making a BTC tx, the balance of my addresses are incorrect, after the tx. It doesn't display the old balance or the updated balance, the balance is completely off. 

The balance of any other chain is correct, the BTC balance is correct again after I delete & import the xpub. 

Refreshing the balances, closing/re-opening the app won't change the "off balance".

Every time I open rotki without having made a BTC tx, everything is displayed okay & correct. As soon I make a BTC tx, the bug comes up in the same way.

### System Description

Operating system: Ubuntu 23.10
Rotki version: 1.31.1

**Comment by yabirgb** [comment]
Hello @kyodhin ! When doing the transactions does it generate a new address from the xpub? or is it the same address not getting the balances updated

**Comment by kyodhin** [comment]
Hello @yabirgb, 
Ah, Ic. You're right, a new address is generated & might not be included then.

**Comment by yabirgb** [comment]
> Hello @yabirgb, Ah, Ic. You're right, a new address is generated & might not be included then.

We have a periodic task that automatically queries them. It runs every hour and should pick the new addresses

**Comment by kyodhin** [comment]
okay, I can't remember if I waited that long in one of the instances. I'll close the topic for now & see how it goes. 

Thank you for your time :)
