### ISSUE TITLE
Add support for Cointracker.io data import

### ISSUE THREAD

**Issue by dsupport** [rotki/rotki#714]
## Abstract

Add support for Cointracker.io to Rotki's 'Import Data' options.

## Motivation

To ease migration for current users of Cointracker.io to Rotki
After Cointracking.info, Cointracker.io is of the next most trusted and widely used crypto-tax and portfolio tracking SAAS platforms judging by Twitter follower counts.

## Specification

Cointracker.io allows for export to .csv similar to Cointracking.info
The Cointracker logo could appear alongside the existing Cointracking logo.

**Comment by LefterisJP** [comment]
Hey @dsupport can you provide example CSV files with valid data for this service so we have data to implement it?

**Comment by LefterisJP** [comment]
Since no CSV data has been provided as examples we are closing the issue. We can re-open if example data is provided.
