### ISSUE TITLE
Figure out way to import  multiple addresses to the address book

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#7144]
## Abstract

Currently there is no way to add multiple addresses to the address book at once. 
We need to figure it out, maybe make it like how we add multiple addresses.

**Comment by kelsos** [comment]
@lukicenturi what do you think makes sense for this? CSV import on the frontend?

**Comment by lukicenturi** [comment]
> @lukicenturi what do you think makes sense for this? CSV import on the frontend?

Yes CSV import makes sense
