### ISSUE TITLE
Uniswap v2 support

### ISSUE THREAD

**Issue by ChristophSiegenthaler** [rotki/rotki#717]
## Abstract

It would be great if Rotki could also keep track of the ERC20 tokens and ETH provided as liquidity to uniswap v1.

## Motivation

Since providing liquidity on uniswap basically consists of the user account having an ERC20 and ETH balance in the exchange contract, it should be "fairly easy" to include in rotki.

## Specification

It requires the implementation of a new submodule for ethereum for uniswap, querying the subgraph for all the user's accounts, saving the trades in the DB, implementing API endpoints so that the frontend can access that data and finally implementing the frontend display of said data.

### Subgraphs

- Uniswap v1: https://api.thegraph.com/subgraphs/name/graphprotocol/uniswap/
- Uniswap v2: https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2

**Comment by LefterisJP** [comment]
Hey thank you for your interest in Rotki and for taking the time to write up an issue!

Uniswap support is definitely in the plans. I just can't say when yet but we want to add it, along with a lot of the other ethereum DeFi options.

**Comment by levelboy** [comment]
An alternative implementation is to keep track of the UNI-V1 tokens, and express the value based on the percentage of the Uniswap Liquidity Pool.

**Comment by LefterisJP** [comment]
Hey @levelboy! Thanks for pitching in. How would that work exactly? Any docs explaining the idea? I have not looked into the technical details of Uniswap yet.

**Comment by levelboy** [comment]
Here's a good explanation of how Uniswap returns are tracked: https://medium.com/@pintail/understanding-uniswap-returns-cc593f3499ef
and also, an explainer on what are the implications to be a liquidity provider: https://medium.com/@pintail/uniswap-a-good-deal-for-liquidity-providers-104c0b6816f2

I do believe that once you're a liquidity provider, you shouldn't consider holding a certain amount of ETH and the paired token that corresponds to the pool you contributed to, but as a piece of pie as a whole. (just like a different token)

**Comment by LefterisJP** [comment]
Hey @levelboy I just realized I never responded to your nice comments. Apologies!

Thanks a lot for the information! We will take it into account when implementing.

**Comment by philhug** [comment]
Please also add uniswap v2

**Comment by lullis** [comment]
Just to add to the feedback provided: I started providing some liquidity on Uniswap and I was hoping rotki would help me (a) track the amount I had pooled there and (b) have some breakdown of how much I earned in fees and how much was earned/lost due to token appreciation/depreciation.

I saw that zerion can track the pooled amounts, but does not provide the amount accrued by fees. *Perhaps* the second is not so important and one can simply have the tax being calculated as the transactions related to adding and removing to the pool.

**Comment by LefterisJP** [comment]
Thanks for the feedback @lullis. We will probably start with uniswap v2 and then add v1 since v2 was released.

(a) would be easy

(b) the fees - if there are events for them we can be showing them. Token appreciation/depreciation is not really a loss or a gain until a taxable action occurs.

**Comment by LefterisJP** [comment]
Turning this issue as an issue for uniswap v2. For uniswap v1 we will just do another one, if resources allow.

**Comment by LefterisJP** [comment]
Adding this here as some extra info on how to address the LP detection task per address.

### Method 1- Graph

Use the uniswap subgraph and query the pairs each address has

### Method 2

Get all uniswap pair token contracts and save them locally. Either via the graph:

```
step = 1000
querystr = """
  pairs(first:$first, skip: $skip) {
    id
  }
}
"""
param_types = {'$first': 'Int!', '$skip': 'Int!'}
param_values = {'first': step, 'skip': 0}
graph = Graph('https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2')


pairs_num = 0
while True:
    print(f'Querying pairs batch {param_values["skip"]} - {param_values["skip"] + step}')
    result = graph.query(querystr, param_types=param_types, param_values=param_values)
    returned_pairs = len(result['pairs'])
    pairs_num += returned_pairs
    if returned_pairs < step:
        break
    param_values['skip'] = pairs_num


print(f'Found: {pairs_num} Uniswap v2 contracts')
```

Or by actually querying the Uniswap Factory [contract](https://etherscan.io/address/0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f) to get `allPairs()` via a multicall.

Then via multicall get current balance of all token pools.

### Use logs

Another idea to also see sort of historical balances is to use a log query in the 2nd step from the previous solution. As mentioned by banteg here: https://twitter.com/bantg/status/1323653991662800899

A small gist he made on it:

https://gist.github.com/banteg/9f3c6ae9b7c3f32f58007978759ccd61

**Comment by vnavascues** [comment]
wow @LefterisJP much appreciated!

**Comment by FIXERMAN** [comment]
Hello everyone, guys, I wrote to almost everyone by mail, but no one answers and does not help me return my 0.3 ETH how to be and how to get my money back?
https://etherscan.io/tx/0xc862d68f1b507e03fbb9cb5a1e40e83c20bf02381a8a9b126c44710f266b85f8

**Comment by LefterisJP** [comment]
Hey @FIXERMAN this is not a uniswap support forum. Perhaps try in their discord: https://discord.gg/XErMcTq

**Comment by magic990619** [comment]
> Adding this here as some extra info on how to address the LP detection task per address.
> 
> ### Method 1- Graph
> Use the uniswap subgraph and query the pairs each address has
> 
> ### Method 2 - Batched calls on all LP tokens
> Get all uniswap pair token contracts and save them locally. Either via the graph:
> 
> ```
> step = 1000
> querystr = """
>   pairs(first:$first, skip: $skip) {
>     id
>   }
> }
> """
> param_types = {'$first': 'Int!', '$skip': 'Int!'}
> param_values = {'first': step, 'skip': 0}
> graph = Graph('https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2')
> 
> 
> pairs_num = 0
> while True:
>     print(f'Querying pairs batch {param_values["skip"]} - {param_values["skip"] + step}')
>     result = graph.query(querystr, param_types=param_types, param_values=param_values)
>     returned_pairs = len(result['pairs'])
>     pairs_num += returned_pairs
>     if returned_pairs < step:
>         break
>     param_values['skip'] = pairs_num
> 
> 
> print(f'Found: {pairs_num} Uniswap v2 contracts')
> ```
> 
> Or by actually querying the Uniswap Factory [contract](https://etherscan.io/address/0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f) to get `allPairs()` via a multicall.
> 
> Then via multicall get current balance of all token pools.
> 
> ### Method 3 - Use logs
> Another idea to also see sort of historical balances is to use a log query in the 2nd step from the previous solution. As mentioned by banteg here: https://twitter.com/bantg/status/1323653991662800899
> 
> A small gist he made on it:
> 
> https://gist.github.com/banteg/9f3c6ae9b7c3f32f58007978759ccd61

Once 'skip' value overflows 5000, it shows me the error.
Error: The `skip` argument must be between 0 and 5000, but is 6000

How to solve it?

**Comment by LefterisJP** [comment]
> How to solve it?

You should avoid using huge skip values as it performs poorly. This is also in the docs and advice is to filter through attributes: https://thegraph.com/docs/developer/graphql-api#pagination

**Comment by magic990619** [comment]
Thanks for your help
