### ISSUE TITLE
Allow users to add/remove exchanges from tax report

### ISSUE THREAD

**Issue by spaceblankey** [rotki/rotki#718]
## Abstract

Generating a tax report queries (apparently) all API connected exchanges. I would like the option to only generate tax reports for certain exchanges which I would like to report on. 

## Motivation

Add an option to choose which exchanges or course to pull trade data from by highlighting the connected APIs.

## Specification

I do not know.

**Comment by LefterisJP** [comment]
That's a nice request. Will consider it! At the moment you can achieve that by temporarily removing an exchange's API keys and then generating a report.

**Comment by LefterisJP** [comment]
Closing this as it's fixed in 1.24.0 as part of the same functionality as the sync with exchanges toggle. If you toggle an exchange to off, then it also won't be counted in the PnL report.
