### ISSUE TITLE
Upload data to server died with exception: database plaintext is already in use

### ISSUE THREAD

**Issue by 7ql** [rotki/rotki#7197]
## Problem Definition

Syncing stopped working somewhen between August (last sync) and two weeks ago (when I noticed it). The error message is found beneath. It is probably related to the issue https://github.com/rotki/rotki/issues/5038 and the timely commit https://github.com/rotki/rotki/commit/2835aaf34d7d3120afa9df3aaba3b596f5a74292

I'm running Dappnode with roti.dnp.dappnode.eth. The error likely came with rotki-1.30.0 which was shipped for Dappnode on August, 20th: https://github.com/dappnode/DAppNodePackage-rotki/releases/tag/v0.1.23 but it's still present with rotki-1.31.1

## Logs

> There was an error while performing the sync: The backend query task died unexpectedly: database plaintext is already in use

### System Description

Operating system: Debian 5.10.149-2 (x86_64)
Rotki version: 1.31.1 from [roti.dnp.dappnode.eth](https://github.com/dappnode/DAppNodePackage-rotki/releases/tag/v0.1.24)

**Comment by LefterisJP** [comment]
Did you try restarting rotki? I don't know how this would work in dappnode but this would need to be done.

Also what you posted is not the log file. We would need rotki's logs to help further: https://rotki.readthedocs.io/en/latest/contribute.html#id2

**Comment by 7ql** [comment]
Dear Lefteris,

on Dappnode Rotki runs within a docker container. A restart via `docker-compose restart` didn't help however `docker-compose stop && docker-compose up -d` did. For anyone stumbling across this, the directory you're looking for is
`/var/lib/docker/volumes/dncore_dappmanagerdnpdappnodeeth_data/_data/rotki.dnp.dappnode.eth`. 

> DEBUG rotkehlchen.premium.sync Greenlet-2: upload to server -- success

Thank you for your quick reply and help 💛
Happy new year

Ps.: Having had a look at the debug output, I cannot help but point to https://github.com/rotki/rotki/issues/2472. This is really still the default? :(

**Comment by LefterisJP** [comment]
> Dear Lefteris,
> 
> on Dappnode Rotki runs within a docker container. A restart via `docker-compose restart` didn't help however `docker-compose stop && docker-compose up -d` did. For anyone stumbling across this, the directory you're looking for is `/var/lib/docker/volumes/dncore_dappmanagerdnpdappnodeeth_data/_data/rotki.dnp.dappnode.eth`.
> 
> > DEBUG rotkehlchen.premium.sync Greenlet-2: upload to server -- success
> 
> Thank you for your quick reply and help 💛 Happy new year
> 
> Ps.: Having had a look at the debug output, I cannot help but point to #2472. This is really still the default? :(

Happy it helped. I don't understand the question or the connection between this and that issue. For chat and such questions please join our discord: https://discord.rotki.com/
