### ISSUE TITLE
Startup fails w/ err msg: "The backend query task died unexpectedly: Tried to initialize unknown exchange bittrex. Should not happen"

### ISSUE THREAD

**Issue by keebeegee** [rotki/rotki#7203]
## Problem Definition

Rotki does not start. Error shown on login page is: "The backend query task died unexpectedly: Tried to initialize unknown exchange bittrex. Should not happen"

## Log

    ------------------
    | Starting rotki |
    ------------------
2024-01-01T11:33:59.001Z: Determining if we are packaged by seeing if C:\Users\X\AppData\Local\Programs\rotki\resources\backend exists
2024-01-01T11:33:59.003Z: Starting packaged rotki-core: C:\Users\X\AppData\Local\Programs\rotki\resources\backend\rotki-core-1.31.2-windows.exe --rest-api-port 4242 --loglevel critical --api-cors app://* --logfile C:\Users\X\AppData\Roaming\rotki\logs\rotkehlchen.log
2024-01-01T11:33:59.031Z: rotki-core started on port: 4242 (PID: 13220)
2024-01-01T11:33:59.075Z: output: [colibri] 42

### System Description

Operating system: WIN 10
Rotki version: 1.31.2

**Comment by LefterisJP** [comment]
Hey @keebeegee happy new year!

This is something that happened due to bittrex closing down just now in December.

The solution is mentioned in the release notes: 

> Important Info: If you had Bittrex or FTX api keys, or had any of the two exchanges in the non-syncing exchanges list, before  upgrading make sure to do the following things in order:
> 
>1. Toggle both exchanges back to being syncing
> 2. Once you do (1) remove the api key of both exchanges.
> Then you can upgrade to 1.31.2. If you already upgraded to 1.31.2, no problem. You can open rotki with 1.31.1 again and do the 2 steps and then open with 1.31.2 again.

https://github.com/rotki/rotki/releases/tag/v1.31.2

If you have more questions hop on to our discord: https://discord.rotki.com/

**Comment by keebeegee** [comment]
Hey @LefterisJP , 
thanks for the quick answer , ... no new-years marathon in Berlin today ? :) 

Too bad I missed this release note. I am not able to login. Once the message appears, with both form fields (user/pw) filled, I get "No user is currently logged in" wenn I ignore the message

Any chance to tweak some config files, etc. so that I can skip the check for Bittrex? 
Checked already some of the files w/o success.

**Comment by keebeegee** [comment]
Thanks @LefterisJP , will try to fix this as instructed. Happy new year to you as well and thanks for your support and ongoing efforts. Will consider a donation.
