### ISSUE TITLE
Add "Last Balance Refresh" Counter At The Top

### ISSUE THREAD

**Issue by nikp79** [rotki/rotki#7230]
## Abstract

Add a counter at at the top of the application that shows when:
1) Last time and date a price refresh happened across the portfolio
2) Last time and date a new token detection happened across the portfolio

## Motivation

Having this will help with frequent manual updates

## Specification

Having it in the persistent bar up top would be ideal

<img width="1551" alt="image" src="https://github.com/rotki/rotki/assets/62769909/dd57d7f0-5265-4f66-adc1-adb7f03a021d">

**Comment by LefterisJP** [comment]
Hmm but @nikp79  price refresh and token detection is not something that happens across the entire portfolio. They happen for specific assets and addresses specifically.

I saw you asked in discord but perhaps better way to figure out a feature request is discuss it with us in `general` channel of discord and then when properly fleshed out to move into an issue.

As discussion in an issue is harder :wink:

**Comment by LefterisJP** [comment]
As explained above, this is not something that's a global setting.
