### ISSUE TITLE
Improve staking per validator view

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#7244]
![Image](https://github.com/rotki/rotki/assets/26648140/6717ed0b-ad84-4dcc-8671-d6cb1077607e)

1. Add divider, and add striped background to the list.
2. Show the number of validators on the title.
3. Add numbering for the validator list.
4. Sort by amount or usd value, descendingly.

**Comment by LefterisJP** [comment]
Thanks for the issue. Just add it to develop though as no need to do this is bugfixes. But ... remember you said note ;). It's fine since you opened an issue, but this could have been a note :)
