### ISSUE TITLE
Add support for Solana

### ISSUE THREAD

**Issue by martriay** [rotki/rotki#7274]
I could not find this supported, let me know otherwise! Thanks.

## Abstract

Add support for Solana chain assets. More specifically, the native SOL token and SPL tokens.

**Comment by LefterisJP** [comment]
Hey @martriay thanks for the interest in rotki! We already have a Solana issue here: https://github.com/rotki/rotki/issues/2394 so will close this as a duplicate.

We would also love to support Solana. It would help if you could convince the solana community to help us with development grants.
