### ISSUE TITLE
Failure running package.sh on Arch Linux

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#733]
## Problem Definition

I'm looking at making an AUR package of rotki.
Looks like the `package.sh` file is the right way to go to create a binary.
However, running it fails, seemingly due to the following lines:

```py
    dist = pkg_resources.get_distribution(package_name)
    metadata_dir = dist.egg_info
```

When the package name is `"pytz"`, this fails.
The `egg_info` attribute is `None`.

```py
import pkg_resources

pkg_resources.get_distribution("pytz")
> pytz 2019.3 (/usr/lib/python3.8/site-packages)

dist = pkg_resources.get_distribution("pytz")
str(dist.egg_info)
> 'None'
```

There is no `rotkehlchen.log` anywhere I can find (with `find`).
Attaching the output of running `./package.sh`.
The output contains an exception early on due to the `packaging` package, it seems.
I don't know if it's related.

### System Description

Output of the suggested script:

```
uname -a
command -v geth && geth version
command -v parity && parity --version
command -v rotkehlchen && rotkehlchen version
[ -d .git ] && git rev-parse HEAD
[package.log](https://github.com/rotki/rotki/files/4230683/package.log)

Linux alladin 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000 x86_64 GNU/Linux
/usr/bin/geth
Geth
Version: 1.9.9-stable
Git Commit: 017449971e1e9e220efcd97d3313a0e27f47003b
Git Commit Date: 20191206
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.13.5
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/home/hjort/.local/bin/rotkehlchen
1.1.2.dev0+g42481b5.d20200220
42481b5f2ef28f25c99663a092f5c85157285379
```

**Comment by LefterisJP** [comment]
You need python 3.7 to build Rotki, it does not work with python 3.8

**Comment by kelsos** [comment]
Reading the title I was "How can it be? Both I and @LefterisJP develop on Arch we would have noticed something!"

**Comment by hjorthjort** [comment]
Thanks! I was confused because I saw a recent commit that added 3.8 support, and there was no mention of version in the docs for Linux, just for OSX and Windows.

How do you two use python 3.7 on Arch?
Is there a better option than a global downgrade?

**Comment by LefterisJP** [comment]
@hjorthjort it's quite easy. Get the old python package form AUR: https://aur.archlinux.org/packages/python37/

I have all pythons after 3.5 in my system.

And then when you make a new python virtual environment specify the python binary to be 3.7.

**Comment by LefterisJP** [comment]
Hey @hjorthjort did you manage to run package.sh in Arch? Can we close this issue? If you need any more help I am here.

**Comment by hjorthjort** [comment]
> Hey @hjorthjort did you manage to run package.sh in Arch? Can we close this issue? If you need any more help I am here.

Yep, finally got around to it. Turns out the issue was me not knowing how to work properly in python on Arch. I had a big mix of pip-installed and pacman-installed packages, user level and system level.. Wish I knew about virtualenv before, and to never use `sudo` with `pip`.

Also, took me a while to figure out that I need to activate `venv` and how. So good learning experience!
