### ISSUE TITLE
rotkehlchen.io is down

### ISSUE THREAD

**Issue by jlopp** [rotki/rotki#735]
Is this still the official web site URL or has it moved?

**Comment by jlopp** [comment]
Never mind, I see it's now https://rotki.com/

**Comment by LefterisJP** [comment]
Hey @jlopp yep that is correct! Sorry for the confusion. We were torn between keeping the old domain name with redirect for 1 more year or not renewing and letting it die and went with the latter! Forces us all to update links as dead links are noticed easily.
