### ISSUE TITLE
NFT queries no longer work - switch to opensea v2

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7359]
## Problem Definition

It seems that Opensea which was the sole provider of NFT data for us has dev-rugged us: https://twitter.com/LefterisJP/status/1751561509929369940

It was probably not noticed fast enough due to the fact we query cached DB nft data: https://github.com/rotki/rotki/blob/3d267d0591a342f53a5a1110f0e25f1cd10bb6ab/rotkehlchen/rotkehlchen.py#L947

So it only got noticed after a user reporting seeing an NFT they sold, still show in rotki even after a restart.

We generally need to not rely only on opensea for NFT data: https://github.com/rotki/rotki/issues/4911

## Task

For the purpose of this issue we should keep it simple and just switch to using opensea v2: https://docs.opensea.io/reference/list_nfts_by_account so that NFT detection works properly again

**Comment by yabirgb** [comment]
This has been already done in https://github.com/rotki/rotki/pull/7360
