### ISSUE TITLE
Failed Import from Cointracking.info

### ISSUE THREAD

**Issue by Codonyat** [rotki/rotki#737]
I exported cointracking.info trades in the form of CSV file. I did it by going to the Enter Coins tab, selecting all trades, Export button, and selecting CSV.

However, when I import such file to Rotki through Import Data, I get:

> Import failed
> {'source': ['Must be one of: cointracking.info.']}

**Comment by LefterisJP** [comment]
Hello @Codonyat! Thank you for trying Rotki out.

This is a known issue and a fix has already been implemented and will be included in the next release: https://github.com/rotki/rotki/issues/731

**Comment by Codonyat** [comment]
Glad to hear that!
