### ISSUE TITLE
Support balancer pools in gnosis chain and more

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7405]
## Abstract

Support balancer pool decoding in gnosis chain and all other chains we don't support yet. A related issue is to automatically detect LP positions and their value: https://github.com/rotki/rotki/issues/5208

## Motivation

Gnosis chain is getting a lot of traction right now and we should support more protocols there.

**Comment by mendesfabio** [comment]
hey folks - I'm Fábio from Balancer's Data team. Just wanted to chime in and say we're happy to answer questions and support you guys to have Balancer properly integrated with rotki. I see you generally opted to not query Subgraphs, but if you have any feedback to our contracts and/or Subgraphs, we're happy to hear them so we can make V3 better.

At Balancer, I'm responsible for our Subgraphs and have developed some of our Dune dashboards so should be able to help you to understand our events, decode their data, etc. I've also joined rotki's Discord (my handler is mendesfabio there) if you want to reach out, cheers!
