### ISSUE TITLE
Support Aura pools in gnosis chain (and more?)

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7406]
## Abstract

Aura is a restaking (lke convex is to curve) for balancer pool tokens. With gnosis chain getting more traction the sDAI/EURe pool is quite heavily utilized: https://app.balancer.fi/#/gnosis-chain/pool/0xdd439304a77f54b1f7854751ac1169b279591ef7000000000000000000000064/a
https://app.aura.finance/#/100/pool/18

Would be nice to be able to decode and understand these transactions properly in gnosis chain and other chains too. Also detect balances just like we do with curve/convex.

A requirement would be to detect balancer properly in gnosis (and every chain aura is used) first: https://github.com/rotki/rotki/issues/7405

## Task

Do it

**Comment by yabirgb** [comment]
I believe we can do it without balancer first since you only deposit the BPT token. +1 heavy on this one since I use it in multiple chains too
