### ISSUE TITLE
Tag selection menu doesn't open when pressing arrow

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#741]
## Problem Definition

![2020-02-24-131723_582x134_scrot](https://user-images.githubusercontent.com/1658405/75152443-4f997280-5709-11ea-9790-7e4adce523e4.png)

Pressing the red area pops up the tags selection menu, but pressing the arrow (blue area) does not. I would expect pressing the arrow would also work.

**Comment by LefterisJP** [comment]
Isn't this fixed y https://github.com/rotki/rotki/pull/1247 @kelsos? If yes can you then please close the issue?

**Comment by kelsos** [comment]
Not sure, I will check it

**Comment by kelsos** [comment]
Ok I checked and it doesn't happen anymore, it only took half a year :rofl:
