### ISSUE TITLE
A JavaScript error occurred in the main process occurs anytime rotki comes or goes out of focus on the screen

### ISSUE THREAD

**Issue by mruepp** [rotki/rotki#7435]
## Problem Definition
A JavaScript error occurred in the main process

Uncaught Exception:
AssertionError: AssertionError
at _n (/Applications/rotki.app/Contents/Resources/app.asar/dist/background.js:70:31894)
at get tray [as tray] (/Applications/rotki.app/Contents/Resources/app.asar/dist/background.js:70:41791)
at BrowserWindow.hidden (/Applications/rotki.app/Contents/Resources/app.asar/dist/background.js:70:41570)
at BrowserWindow.emit (node:events:526:35)

![Screenshot 2024-02-09 at 15 48 08](https://github.com/rotki/rotki/assets/10906913/b27147e4-49c2-4346-b026-192ed82af796)

### System Description
App Version: 1.31.3
Frontend Version: Frontend Version:
Platform: darwin arm64 14.3.1
Electron: 27.0.1
Premium Version: 7.0.1
Build: 1701857296807

**Comment by kelsos** [comment]
Hey @mruepp could you provide a bit more information here? what were you trying to do when this happened?

**Comment by mruepp** [comment]
Hi, out of the blue. Suddenly this error started. I assume it started after the last rotki update. I dont do anything with rotki except looking at my balances once in a while. Macos is Sonoma 14.3.1

**Comment by mruepp** [comment]
So as I wrote, the Error pops up always when maximizing or minimizing the rotki window in macos using the yellow button top left. It also pops up when pressing CMD+H - hide the window.

**Comment by mruepp** [comment]
Also what happens is the premium Database sync does not start since the error appeared. When attempting to push manually, rotki gives contradictory messages. See the both screenshots.

![Screenshot 2024-02-10 at 09 36 11](https://github.com/rotki/rotki/assets/10906913/20733b84-cb00-4885-8069-aff369458f57)
![Screenshot 2024-02-10 at 09 35 55](https://github.com/rotki/rotki/assets/10906913/0f7d1b05-fb6c-4f84-a0e8-8a56d609f4c0)

**Comment by mruepp** [comment]
I can report, it happens with both, the macos ARM and the macos Intel build. I reinstalled both.

**Comment by LefterisJP** [comment]
This may make sense to need logs in discord as nobody has seen this kind of error before. Please hop on discord: https://discord.rotki.com/ and DM logs (https://rotki.readthedocs.io/en/latest/contribute.html#id2) of when this is happening to either me or someone else from the team.

Someone from the frtontend team will have to look at it.

As for the remote DB it's probably two different upload attempts. It's not an error. It's continuously trying to upload the DB and when it can't for some reason (size differences) to be on the same side it tells you so.

**Comment by lukicenturi** [comment]
Hi @mruepp, I finally managed to reproduce the issue.
For the temporary fix, can you enable the tray icon (View > Display Tray Icon), and check if the popup still appear?

**Comment by mruepp** [comment]
Hey, yes thats the solution. The error disappears if Display Tray Icon is checked.
