### ISSUE TITLE
Error loading NFT balances using OpenSea API key

### ISSUE THREAD

**Issue by krisjpi** [rotki/rotki#7469]
## Problem Definition
I have an OpenSea API key configured, but my balances continue to error out without loading. Recently updated to version 1.31.3, and the asset balances were loading the last time I used the older version.

Not an urgent fix, but would be nice to figure out 😃 

Rotki Notification Error Message:
NFT balance querying [date]
An error occurred while querying the NFT balances: The backend query task died unexpectedly: 'next'

## Logs
The only line in the logs that seems to be relevant is here:
2024-02-15T04:35:16.530Z: (error): Error: The backend query task died unexpectedly: 'next'

If there are other relevant lines to check, I can report back. It appears all other lines complete successfully (websocket connected, components registered, etc).

### System Description
Operating system: Windows 11 Education Version 23H2
Rotki version: 1.31.3

**Comment by LefterisJP** [comment]
hey thanks for opening an issue. Can you maybe open full debug logs: https://rotki.readthedocs.io/en/latest/contribute.html#id2
join our discord: https://discord.rotki.com/ and send the logs to us?

**Comment by LefterisJP** [comment]
So @krisjpi this "should" be fixed in 1.32.0. Try it and let us know. We had to take a guess since we don't have logs.

If it is not then please reopen this but with logs as I asked above.

**Comment by krisjpi** [comment]
Can confirm @LefterisJP, I updated to 1.32.0 this morning and all NFT balances are loading again for me. Thank you!
