### ISSUE TITLE
Add functionality/checkbox for "Hide assets <1 USD"

### ISSUE THREAD

**Issue by nonsense** [rotki/rotki#7498]
## Abstract

Heavy users normally have a lot of dust tokens in their accounts, from reputable currencies that they don't want to blacklist, such as:
<0.01 BNB
<0.01 WETH
<0.01 stETH
etc.

I'd be nice if there is a checkbox on Rotki, similar to the one found on many exchanges, that says "Hide assets <1 USD", so that one doesn't have 300 tokens under Assets.

## Motivation

Nobody cares at a given point in time that they have 0.01 from a certain asset, so hiding these assets would clean up Rotki interface and make it nicer.

## Nice to have

Ideally make the `hide threshold value` configurable, i.e. some folks might want 1 USD, some might want 10 USD or 100 USD, etc.

**Comment by LefterisJP** [comment]
Thanks @nonsense. Absolutely we need this. I also felt the need for such a switch when I use my rotki.

 @kelsos how do you think we should do this? Just frontend? Or would be more beneficial to do the potential filtering on the api at the backend?
