### ISSUE TITLE
Frontend: Think a bit on the usage of notifications versus popups

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#751]
## Problem Definition

At the moment in the frontend a lot of actions are background tasks that run and return answers after an indeterminate amount of time. Which is why we use notifications for many errors.

But e.g. if this is a user's first ethereum account and he tries to add it as non-checksummed and has no tokens tracked, the error response will be near instantanteous. And still no popup that there was a problem will appear. Instead user has to notice that there is a notification. Even I missed it and spent a few seconds wondering what was wrong.

Some of these tasks which are interactive like the above example need to be handled by pop ups.

**Comment by isidorosp** [comment]
I noticed a similar thing. One way to increase the "noticeability" of notifications is to show a toast notification, which when fades goes to the notification area. 

There is also the inverse sometimes. For example in the Settings Menu toggling a setting on/off will always result in a popup, which is also tedious to constantly dismiss (clicking outside the modal does not make it go away).

**Comment by kelsos** [comment]
We should keep a list of the places that require improvement. For starter we can include a toast message as @isidorosp suggested. It would certainly make things easier. 

Then we need to decide which places should block further user action, and where we don't. 
Making the `MessageDialog` dismissable when clicking outside makes sense. 

Also making the settings show a toast and notification would probably make more sense too.

**Comment by kelsos** [comment]
Closing this issue. We are doing a notification/modal/form case by case nowadays. If any specific places require a change we can only open an issue for these.
