### ISSUE TITLE
Allow for customization of CSV file delimiter

### ISSUE THREAD

**Issue by MichaelRyom** [rotki/rotki#7536]
## Abstract

To make it easier for everyone to use the exported data please allow for customization of the CSV delimiter for CSV exporting.

## Motivation

Comma and full stop/period is used differently as separator in different languages ( mostly English vs rest of the world ). Some places comma is used for decimal number and other places as the thousands separator. 

More on this can be found here https://en.wikipedia.org/wiki/Decimal_separator

## Specification

- Allow for customization of the delimiter for CSV files.
- Make sure the delimiter does not conflict with any formulas if the CSV has any.

**Comment by LefterisJP** [comment]
For which CSV do you mean Michael?

All CSV importers, say google spreadsheets can customize the delimiter when importing so this is something individual users customize depending on their needs when consuming the exported CSV.

Changing it from a comma to semicolon is not something we will do, since also some of the CSVs contains formilas, which use semicolons to separate the arguments.

But we could have it customizable at some point. And changing it should also make sure to adjust the formulas.

PRs are welcome.

I will keep this issue for this and edit your description.

**Comment by LefterisJP** [comment]
Edited original description to the following

## Abstract

To make it easier for everyone to use the exported data please allow for customization of the CSV delimiter for CSV exporting.

## Motivation

Comma and full stop/period is used differently as separator in different languages ( mostly English vs rest of the world ). Some places comma is used for decimal number and other places as the thousands separator. 

More on this can be found here https://en.wikipedia.org/wiki/Decimal_separator

## Specification

- Allow for customization of the delimiter for CSV files.
- Make sure the delimiter does not conflict with any formulas if the CSV has any.

**Comment by MichaelRyom** [comment]
To answer your first question it an export of "Profit and loss report".

I understand your reason for not changing it to semicolon if that conflicts ( my export does not contain semicolons why i suggested it ) , but at the same time that is nothing different from how it is conflicting today IMHO.

I have previously tested only using Excel. Just tried google sheet, seem the same to me, same errors, same behavior. So, not sure I understand your remark about google sheet.

Here is an example of how data looks before ( as a csv string ) and after import ( with comma as delimiter ) and third is how it should look ( When I change the delimiter manually for this one line ) .

1)
transaction event,https://etherscan.io/tx/0x75f4f468d96e9c30eb61dc017983d6a23229a72e847f6f747de96f8e93919094  ->  Receive 33.56511079 STORJ from 0x303EDCD8DbE1607fe512D45CC15d3E41fa4db44B to 0xE7F95B04404BC6809F2D53F2C341E62c0bF5fe96 [Storj],ethereum,06/04/2023 19:29:59 Romance Daylight Time,eip155:1/erc20:0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC,0,33.56511079,0.4022,"=IF(K1580="""",G1580*H1580,G1580*H1580-K1580)",0.0000,,,STORJ

2) ( Copied from Excel after import with comma as delimiter - Excel changes the delimiter when copying to pipe it seems )
transaction event | https://etherscan.io/tx/0x75f4f468d96e9c30eb61dc017983d6a23229a72e847f6f747de96f8e93919094  ->    Receive 33.56511079 STORJ from   0x303EDCD8DbE1607fe512D45CC15d3E41fa4db44B to 0xE7F95B04404BC6809F2D53F2C341E62c0bF5fe96   [Storj] | ethereum | 06/04/2023 19:29:59 Romance Daylight Time | eip155:1/erc20:0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC | 0 | 3.356.511.079 | 0.4022 | =IF(K1580="",G1580*H1580,G1580*H1580-K1580) | 0.0000 |   |   | STORJ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

if you look at the "notes" field is says 33.56511079 tokens received, but the "taxable_amount" is 3356511079 - This is due to comma/period difference between countries.

3) With semicolon and local use of seperator
transaction event;https://etherscan.io/tx/0x75f4f468d96e9c30eb61dc017983d6a23229a72e847f6f747de96f8e93919094  ->  Receive 33,56511079 STORJ from 0x303EDCD8DbE1607fe512D45CC15d3E41fa4db44B to 0xE7F95B04404BC6809F2D53F2C341E62c0bF5fe96 [Storj];ethereum;06/04/2023 19:29:59 Romance Daylight Time;eip155:1/erc20:0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC;0;33,56511079;0,4022;"=IF(K1580="""";G1580*H1580;G1580*H1580-K1580)";0,0000;;;STORJ

And how it looks in excel:
transaction event | https://etherscan.io/tx/0x75f4f468d96e9c30eb61dc017983d6a23229a72e847f6f747de96f8e93919094  ->    Receive 33,56511079 STORJ from   0x303EDCD8DbE1607fe512D45CC15d3E41fa4db44B to 0xE7F95B04404BC6809F2D53F2C341E62c0bF5fe96   [Storj] | ethereum | 06/04/2023 19:29:59 Romance Daylight Time | eip155:1/erc20:0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC | 0 | 33,56511 | 0,4022 | 0 | 0 |   |   | STORJ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Notice how the "notes" field and "taxable_amount" field are not the same and formula calculations have been executed ( Which they did not due in example 2 )

Hope this clarifies things

**Comment by LefterisJP** [comment]
Hey @MichaelRyom you can customize how delimiters, and thousands separators are treated in google sheets. And excel. And basically all other spreadsheet tools. Please search how to achieve this online. It depends on your locale settings for many of those tools.

As I said I will keep the issue open for the ability to customize it on the export side from rotki too.
