### ISSUE TITLE
Premium DB syncing allow choice of automatic handling sync errors

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7570]
## Abstract

Quite often rotki may inform users it has not uploaded the local DB to the rotki server due to a size discrepancy. And ask user to confirm they want to push it.

This is how rotki syncing works with the server. We just give a message as an fyi. Since the database is nothing but a blob of encrypted data.

We know nothing else about it apart from its size and last time of upload. We can't see what's in there. So out of abundance of caution we just do not upload automatically to the server if there is a size difference and ask for action from you.

The size discrepancies can happen for various reasons, as periodic tasks run underneath either adding more data or cleaning up data

## Motivation

Some users have asked for the ability to automatically choose a strategy of uploading there via a setting and not to have to manually press force push whenever such a size discrepancy happens.

It's a bit less safe option as automatically overwriting data of bigger size can lead to loss of data if the local is an old DB from an older machine.

But if the users are aware of the dangers (say they only use one machine) then it's a positive quality of life change.

## Specification

- Add a setting to ignore size discrepancies in premium DB upload
- Use the value of this setting when syncing to decide what to do. Whether to force push or ask user for input
- Frontend; When asking user to force push due to size discrepancy, also have a checkbox dialog to "Do this action every time size discrepancy occurs" or something like that.

**Comment by Mithil467** [comment]
Hello 👋,
I'd like to take this up, if no one else is already working on it.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/7879
