### ISSUE TITLE
Coinbase api validation error: Unknown currency

### ISSUE THREAD

**Issue by smashkins** [rotki/rotki#7572]
Problem Definition
When I try to display Coinbase Exchange Deposits & Withdrawals, this notification appears:
"Failed query for Coinbase: Coinbase query https://api.coinbase.com/v2/accounts/<some_alphanumerics_hidden_for_privacy>/transactions?=starting_after=None responded with error status code: 400 and text: {"errors":[{"id":"validation_error","message":"Unknown currency"}]}"

Logs
Check error message in description above.

System Description
Operating system: Docker
Rotki version: 1.32.1

**Comment by LefterisJP** [comment]
Hey @smashkins thanks for the report!

Can you join discord and maybe contact one of the developers to give us logs via a DM? Not sure if logs would help but maybe they will contain more information.
Discord link: https://discord.rotki.com/

How to enable debug logs: https://rotki.readthedocs.io/en/latest/contribute.html#id2

The error is weird. There is no currency given as a parameter in that api query. The starting_after=None looks wrong and not sure how it got in there as it's protected against, at least in 1.32.0 and on. So maybe that?

**Comment by smashkins** [comment]
I saw from the logs that the API call refers to the one related to the ETC Wallet.
Ok I'll contact developers in discord

**Comment by LefterisJP** [comment]
Without further user input we went with the solution OJ came up with and it's now released with 1.32.2.
