### ISSUE TITLE
Failed to read balance for asset USDT at Bitcoin.de

### ISSUE THREAD

**Issue by seismographix** [rotki/rotki#7611]
## Problem Definition

In the UI the Backend notified: Failed to read balance for asset USDT at Bitcoin.de. Please report this error.

## Logs

I cannot deliver any relevant logs. I am using Docker and shared /logs with the host system. There was a rotki.log created on the host system, but it is empty. The command "docker logs <container>" gave also no hint what went wrong. The config level was adjusted from "info" to "debug" in the rotki_config.json. 

### System Description

Operating system: Ubuntu 23.10 / Docker
Rotki version: 1.32.1

**Comment by LefterisJP** [comment]
For logs: You would need to setup debug logs. Read here: https://rotki.readthedocs.io/en/latest/contribute.html#id2

But I think I can see why the error happens. Could you join our discord to chat more there? Could also send you a test binary to confirm a fix: https://discord.rotki.com/

**Comment by seismographix** [comment]
> For logs: You would need to setup debug logs. Read here: https://rotki.readthedocs.io/en/latest/contribute.html#id2
> 
> But I think I can see why the error happens. Could you join our discord to chat more there? Could also send you a test binary to confirm a fix: https://discord.rotki.com/

I apologize for the delay in my response, as I am not a frequent user of Github. I have updated the Docker container to the latest version 1.32.2, and it is working now. The message has not shown up again.

**Comment by LefterisJP** [comment]
> > For logs: You would need to setup debug logs. Read here: https://rotki.readthedocs.io/en/latest/contribute.html#id2
> > But I think I can see why the error happens. Could you join our discord to chat more there? Could also send you a test binary to confirm a fix: https://discord.rotki.com/
> 
> I apologize for the delay in my response, as I am not a frequent user of Github. I have updated the Docker container to the latest version 1.32.2, and it is working now. The message has not shown up again.

Perfect, happy to hear.
