### ISSUE TITLE
Think about better UX on DSR decimals

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#762]
## Problem Definition

At the moment we show around 8 decimal digits in the DSR calculations in the UI. That is because DSR calculations show interest rate earned in the DSR which is, as of now, 8% and as such accumulates slowly and in the lower decimal digits. The thinking behind the current design is to offer similar UX with Oasis and Compound apps which do the same.

The topic got discussed a bit in [this]](https://twitter.com/Ivshti/status/1234252949586612225) twitter thread.

## Task

Think on what, if any changes, should be done for a better approach. From the thread linked above @pepae suggested something nice [here](https://twitter.com/bezzenberger/status/1234425369048076289). Essentially to make the configured digits bolder and the rest of the decimal digits less significant but still visible.

![ESGPU7-XUAU2YEj](https://user-images.githubusercontent.com/1658405/75822493-57f44c00-5da0-11ea-9a4b-3519ef90aafe.jpeg)

But still not sure on what approach to follow

**Comment by isidorosp** [comment]
Personally from a UX perspective I think it's inconsistent, leads to bad UI (you will have elements that ostensibly show the same data as other elements that are way wider / wrap / etc.), and doesn't make a lot of sense (what does viewing this level of detail really offer the user)? 

That said, consider the functionality to offer the user the ability to easily access it if they want to (e.g. hide it behind a mechanism that reveals granularity when invoked such as on:hover, "alt" key, detailed vs dashboard/summary views, etc.).

**Comment by LefterisJP** [comment]
@isidorosp this is not a binding issue, more of a kind of thinking on how to proceed from here and on about the concernes that were raised.

**Comment by kelsos** [comment]
@LefterisJP for me it would make sense to have everything as part of the settings and let the users decide on how many decimals they require. Maybe also introduce some kind of tooltip, on hover as @isidorosp mentioned. This way the user will still be able to see the full amount if needed.

**Comment by LefterisJP** [comment]
sounds like too much work to offer all these options without any more user feedback on requirements. Also here defaults matter.  Whatever the default ends up being would be what people would end up using and also criticizing us for since they would not know they can change it.

**Comment by LefterisJP** [comment]
Closing this as it's too DSR specific. And we have already implemented multiple other protocols that have many trailing decimals in their frontend components.

If we want to do any changes/customization they need to be global for the entire app.
