### ISSUE TITLE
Allow users to change the password

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#763]
## Problem definition

Users can't currently change their password. We should allow them to be able to do so.

### New API endpoint

Create a new API endpoint: `http:patch:: /api/(version)/users/(username)/password`
It should only accept one parameter `password` which should be the new password to add. The endpoint should only work if user with `username` is logged in.

For this you should add docs here: https://github.com/rotki/rotki/blob/develop/docs/api.rst#handling-user-creation-sign-in-log-out-and-querying

The definition of endpoints is in these two files:

Schema Encodings: https://github.com/rotki/rotki/blob/develop/rotkehlchen/api/v1/encoding.py
Endpoints: https://github.com/rotki/rotki/blob/develop/rotkehlchen/api/v1/resources.py

The new endpoint should be added in the server here:

https://github.com/rotki/rotki/blob/develop/rotkehlchen/api/server.py#L59

And the implementation somewhere around here:

https://github.com/rotki/rotki/blob/develop/rotkehlchen/api/rest.py#L908

### Changing the password in the DB

The implementation should simply call the database and change the password. To change a password in sqlcipher it's really easy, you just need to do a [rekey](https://www.zetetic.net/sqlcipher/sqlcipher-api/#rekey).

A new function to change the password should be added to the DB handler around here: https://github.com/rotki/rotki/blob/c43e1931e0151c44d67533a4a87e1b2b43c86a3a/rotkehlchen/db/dbhandler.py#L296 and it should be called by the rest API implementation that should be done above.

### Testing

Add a test with a user logging in, changing his password, logging out and then logging in with the new password. Tests should be added here: https://github.com/rotki/rotki/blob/c43e1931e0151c44d67533a4a87e1b2b43c86a3a/rotkehlchen/tests/api/test_users.py#L476

Check that test file to see how to write simple test for users

### Frontend

Add the newly added REST API endpoint to the front-end here: https://github.com/rotki/rotki/blob/develop/electron-app/src/services/rotkehlchen-api.ts

Call it via the general account settings view in order to change the password here: https://github.com/rotki/rotki/blob/develop/electron-app/src/views/settings/General.vue

The fields should be: 
- old password
- new password
- password confirmation 

For the fields, the https://github.com/rotki/rotki/blob/develop/electron-app/src/components/inputs/RevealableInput.vue should be used to support the reveal/hide functionality.

**Comment by LefterisJP** [comment]
I updated the issue description with more newcomer friendly details on what things need changing and where.

@kelsos Can you please check the front-end part and write a few more details?

**Comment by kelsos** [comment]
Some minor details: fields should be old password/new password/password confirmation and for the fields the https://github.com/rotki/rotki/blob/develop/electron-app/src/components/inputs/RevealableInput.vue should be used to support the reveal/hide functionality.
