### ISSUE TITLE
Smart Layer Network, $SLN

### ISSUE THREAD

**Issue by zhangzhongnan928** [rotki/rotki#7630]
**Asset name:** Smart Layer Network
**Asset symbol:** SLN
**Coingecko link:** https://www.coingecko.com/en/coins/smart-layer-network
**Cryptocompare link:** https://www.cryptocompare.com/coins/sln/overview

SLN token contract on Ethereum and Layer2s 
Ethereum | 0xDb82c0d91E057E05600C8F8dc836bEb41da6df14
Linea | 0x5e15E8afc627397075ebe0A7C9DC14177429BBFF
ARB | 0x3a65C4cBd896c3681C471EBa8dA44828c8912043
Polygon zkEVM | 0x62e2ea221e8fE0233Ccabc0297B542b16EF3e8Fa
zkSync | 0x14c64A6E09511207B7746f1B6a76F9D8Fa4f695f
Scroll | 0x4fb487cc0C9164a52e11E781d8c597bE43f56f87
Polygon PoS | 0x1Fe78e67Ad10ba3a9583e672Cac0480737D1B9f7

**Comment by LefterisJP** [comment]
Hello @zhangzhongnan928 thank you for the issue. There is no need to ask us to add a token, though we can include it in the official list in next release.

If you need it in your local application you can add it for your rotki instance manually: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-editing-an-asset

**Comment by zhangzhongnan928** [comment]
Thanks, 
you are so fast.

**Comment by LefterisJP** [comment]
Feel free to join our discord too: There you can get answers to many questions easily and in real time (mostly active weekdays in European working hours)
