### ISSUE TITLE
Importing Binance Trade History CSV fails parsing

### ISSUE THREAD

**Issue by Spenhouet** [rotki/rotki#7647]
## Problem Definition

I made a CSV export of my trading history on Binance.
The import fails with parsing the entries.

The CSV has these columns: "Date(UTC)","Pair","Side","Price","Executed","Amount","Fee"

Example entry:
```json
{"Date(UTC)": "2023-12-31 18:12:45", "Pair": "ETHUSDT", "Side": "BUY", "Price": "2297.0600000000", "Executed": "0.0010000000ETH", "Amount": "2.29774000USDT", "Fee": "0.0004790000ETH"}
```

## Logs

```
[20/03/2024 20:43:03 W. Europe Standard Time] ERROR rotkehlchen.data_import.importers.binance Greenlet-6: Malformed binance csv columns! Broke on row {'Date(UTC)': '2023-12-31 18:12:45', 'Pair': 'ETHUSDT', 'Side': 'BUY', 'Price': '2297.0600000000', 'Executed': '0.0010000000ETH', 'Amount': '2.29774000USDT', 'Fee': '0.0004790000ETH'}. 'UTC_Time'
[20/03/2024 20:43:03 W. Europe Standard Time] WARNING rotkehlchen.user_messages Greenlet-6: 94 Binance rows have bad format. Check logs for details.
```
_I changed shown values._

### System Description

Operating system: Windows
Rotki version: 1.32.2

**Comment by LefterisJP** [comment]
Hey @Spenhouet thank you for the issue. The binance CSV import as per the original request [here]https://github.com/rotki/rotki/issues/4154) supports the "transaction export".

Binance has many different CSV exports and the transaction export is the only one that contains all events. Please use that one.

**Comment by Spenhouet** [comment]
Hey @LefterisJP,

I wasn't aware. Thanks for the info. I also downloaded the transaction history but it seems they massively reduced the exporter information. It only contains time, asset and amount (and some useless columns). No price, no trading pair, no fees paid, ...
Specifically, there are the current columns of the transaction history export: User_ID,"UTC_Time","Account","Operation","Coin","Change","Remark"
I tried importing the current transaction history export but the imported entries weren't usable as the display wrong pricing.
I'm not sure if the current format matches the expected level of detail?

I have some old Binance exports from 2021 and they contained much more information.

It seems to me the trade history export contains more usable information.

**Comment by Spenhouet** [comment]
Hey @LefterisJP,

I wasn't aware. Thanks for the info. I also downloaded the transaction history but it seems they massively reduced the exporter information. It only contains time, asset and amount (and some useless columns). No price, no trading pair, no fees paid, ...
Specifically, there are the current columns of the transaction history export: User_ID,"UTC_Time","Account","Operation","Coin","Change","Remark"
I tried importing the current transaction history export but the imported entries weren't usable as the display wrong pricing.
I'm not sure if the current format matches the expected level of detail?

I have some old Binance exports from 2021 and they contained much more information.

It seems to me the trade history export contains more usable information.

Edit: I see that the transaction history also contains information on staking etc. which the trade history doesn't.

**Comment by LefterisJP** [comment]
These are the columsn: `User_ID,UTC_Time,Account,Operation,Coin,Change,Remark` we process.

From them we can get the trade history too. Fees are in another entry than the buy. 

You can also simply use the api which is up to date but just needs care to specify pairs otherwise you end up getting rate limited: https://rotki.readthedocs.io/en/latest/usage_guide.html#binance-binance-us

The CSV is mostly for events that are not covered well y the api.

**Comment by Spenhouet** [comment]
Okay, sound like the format is as expected. I'm off for today but will try again. Thanks for the very quick response. Appreciated!

**Comment by LefterisJP** [comment]
Thanks!

Also always open for chatting up in German working days/hours in our discord. Both myself, our devs and other users! https://discord.rotki.com/
