### ISSUE TITLE
"Show Issues" button disappears from a PnL after restarting the app

### ISSUE THREAD

**Issue by maurelian** [rotki/rotki#7656]
## Problem Definition

After generating a new PnL, I see the "Show Issues" button.

<img width="1296" alt="image" src="https://github.com/rotki/rotki/assets/23033765/cc278003-12d3-4012-abc4-3e3564445587">

But if I restart the app it disappears: 

<img width="1197" alt="image" src="https://github.com/rotki/rotki/assets/23033765/f2c9c84d-bedf-4946-8b7a-a60c65e1deaa">

I have to regenerate the report to get it back.

## Logs

Not sure that would help in this case? LMK in discord if so.

### System Description

Operating system: MacOS Sonoma 14.2.1
Rotki version: 1.32.2

**Comment by LefterisJP** [comment]
Hey @maurelian this is a known issue. Those issues are in memory and do not persist over a restart. I don't think we plan to fix this as we will do many changes in the way accounting/PnL works and any fix would already be really hard.
