### ISSUE TITLE
Make Accounting Rules Exportable/Importable

### ISSUE THREAD

**Issue by jakubikan** [rotki/rotki#7675]
## Abstract

The Idea here would be to have an export button for the accounting rules so you could save them if you change them. 
With the import button you could actually restore the accounting rules again.

## Motivation

This would allow to firstly store & restore the accounting rules as well as you would be able to create different accounting rules that could also be shareable. 

Lastly an reset button could make sense to also restore the defaults 

## Specification

I guess from  a technical side it should not be a too complex thing to do :smiley:

**Comment by LefterisJP** [comment]
That should not be super hard to do. Let us think about it. They are already in the DB.
