### ISSUE TITLE
Add historical prices via API call

### ISSUE THREAD

**Issue by jakubikan** [rotki/rotki#7676]
## Abstract

Add an API endpoint to add History Prices via API call 

as far as I can tell this endpoint here https://rotki.readthedocs.io/en/latest/api.html#query-the-historical-price-of-assets
is only there the query the prices via apis that where implemented in rotki. 

## Motivation

The idea would be to have some where you could add something like this via api call 
![Screenshot from 2024-03-26 23-37-00](https://github.com/rotki/rotki/assets/174327/158c014e-fbed-429d-8142-49a7d869741a)

The motivation behind this is that I actually have the whole prices data already available on my computer - since I have exported most of this already from binance. 

I think if you already have the data then this could speedup the tax report generation

**Comment by LefterisJP** [comment]
Hey @jakubikan this API endpoint already exists: https://rotki.readthedocs.io/en/latest/api.html#put--api-(version)-assets-prices-historical

Essentially everything the frontend does it does by contacting the backend via the Rest API seen here: https://rotki.readthedocs.io/en/latest/api.html

Lots of stuff in there

**Comment by jakubikan** [comment]
Nice thanks - sorry did not see that I assumed that POST is mostly the "create" endpoint
