### ISSUE TITLE
Network Error when logging in too fast at app startup

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#770]
## Problem Definition

Sometimes when the application loads and you try to log in too fast (before the python backend is fully operational), you get a Network Error. If you wait a few seconds, then you can log in successfully. A good indicator of when "it's safe" to login is when the rotki client version is now showing in the background of the app.

Screenshots below:
![image](https://user-images.githubusercontent.com/27592/76159714-84eb8a80-6123-11ea-858a-3189290402f5.png)
![image](https://user-images.githubusercontent.com/27592/76159726-992f8780-6123-11ea-89d9-3f87080806fc.png)
![image](https://user-images.githubusercontent.com/27592/76159745-ca0fbc80-6123-11ea-8f22-aee1e2b78cda.png)

And if you wait until the version shows:
![image](https://user-images.githubusercontent.com/27592/76159709-7a30f580-6123-11ea-9865-f39a3abcfbd9.png)

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
* Windows 10 64-bit
* Rotki 1.2.0 packaged binary (also noticed it in 1.1.0). It seems to happen less often in the electron:serve version
```

### Possible Fix
a) Do not allow the user to log in (e.g. show loading screen) until the backend is fully operational.
b) Allow the user to key in their information but hold the login attempt until a "ping back" from the API can be verified.

**Comment by LefterisJP** [comment]
@kelsos have we not already handled this?

**Comment by kelsos** [comment]
@LefterisJP not exactly. We are not preventing anyone from trying to login while the backend is still not initialized. So if a user is really fast when trying to login then this will happen. We can disable and show some message until the version API returns 200. usually is the first to run.

**Comment by isidorosp** [comment]
Are API calls placed into a queue? If so, you could initialize the queue beforehand, slot the login call in, and then start processing the queue only after the first successful version API call (which wouldn't be via the queue). That said, blocking login / showing a loading screen is probably easier.

**Comment by kelsos** [comment]
@isidorosp no there is no queue of API calls.

**Comment by LefterisJP** [comment]
@kelsos Hey kelsos so as discussed via whatsapp this should be pretty simple. Just keep retrying until the API (version endpoint?) responds with a 200. I guess if there is no API response from the backend after X seconds/tries we can assume something is wrong and fail showing the backend logs to figure out why the backend failed to start.
