### ISSUE TITLE
Add PulseChain to "Chain" dropdown menu in "Add a new Asset" form

### ISSUE THREAD

**Issue by bakkdoor** [rotki/rotki#7702]
## Abstract

#7577 added PulseChain rotki. But it does not yet show up in the dropdown menu when adding a new Asset in the UI.
It would be great if it could be selected as the Chain for an EVM token.

## Motivation

Since rotki knows about that chain, it should also be exposed from within the UI so tokens on PulseChain can be added for portfolio tracking and manually entered trades etc.

**Comment by kelsos** [comment]
Hey @bakkdoor this will be available in the next release, with the addition to the backend it is already properly picked in the UI. 

![image](https://github.com/rotki/rotki/assets/2269732/987c9487-ba5c-4d28-b570-f553fb252054)
