### ISSUE TITLE
History Events CSV Export does not respect profit currency in event value

### ISSUE THREAD

**Issue by nisdas** [rotki/rotki#7722]
## Problem Definition

When exporting a CSV file of filtered historical events, the balance value is always in `USD` even if your Profit Currency has been set as something else ex: `SGD`.

## Logs

N.A

### System Description

Operating system: Linux
Rotki version: v1.32.2

**Comment by LefterisJP** [comment]
Yes this is a known limitation. The events export is an export of the events as they are saved. The value is always in USD. The profit currency is respected on the PnL export but not there.

The export would become a lot slower if we did the conversion, and it may also fail if either a USD/SGD (or whatever) conversion rate is not found for that event or if we can't find historical price of the amount of that event. Or it could just have 0 value.

**Comment by yabirgb** [comment]
Regarding this issue we were discussing about the scenario where the user doesn't have the prices for the events. The ones rendered in the UI are ensured to have them but there might be events without prices that we need to query before exporting. One issue with this is that we can get rate limited or the process can be slow so we mentioned about sending periodic ws messages with the status so the frontend can show them to the user and have feedback that something is being done
