### ISSUE TITLE
To add support for CEX Future account

### ISSUE THREAD

**Issue by phd2018eth** [rotki/rotki#7753]
## Abstract

Many exchanges now separate the spot/margin account from the futures account. e.g. OKX and Kraken

## Motivation
It's important to have a complete picture of the portfolio account. If only supporting the spot portion, it is useless for people also trade perps and future contracts. It will be a larger addressable user base potentially including institutional users.

**Comment by LefterisJP** [comment]
hey @phd2018eth there is already an issue for this: https://github.com/rotki/rotki/issues/7715
