### ISSUE TITLE
Privacy Notice does not correctly close if you do not "Close" the Upgrade Dialog

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#776]
## Problem Definition

The normal user flow for a user without Rotki Premium is:
1. Log in
2. In the Rotki Premium dialog, click either "Upgrade" or "Close"
3. Use rotki

In between 2. and 3., clicking either button should also close the Privacy Notice. However, if you click "Upgrade" instead of "Close", the privacy notice does not disappear. You need to log back in and click "Close" to fix this.

![image](https://user-images.githubusercontent.com/27592/76302493-6242a880-62c0-11ea-8d2a-5332c570fcea.png)
![image](https://user-images.githubusercontent.com/27592/76302496-640c6c00-62c0-11ea-8400-6909bb733435.png)

**Comment by LefterisJP** [comment]
Solved by #777. Thank you!
