### ISSUE TITLE
Add option to totalize/do quick PnL on selected exchange trades

### ISSUE THREAD

**Issue by allthegoodnamesweret4ken** [rotki/rotki#7769]
## Abstract

I would really like the option to get the totals (currency bought/currency spent/average price) on selected (or filtered) exchange trades (in History/Exchange Trades).

## Motivation

I think it would be greatly helpful to easily get a summary of all your buys and/or sells of a particular asset (on a particular exchange). This could help you determine: how much you invested already, what your average price has been so far, and (in case of buys and sells) what your profit was. Poloniex used to have this functionality and it worked by simply clicking checkboxes for the trades you wanted to include in the calculation and clicking "Analyze" (or something like that). It would then show a summary of total bought, total spent, total sold, total received, average buy price, average sell price and total profit/loss. A limitation used to be that it only really worked as long as you didn't deposit/withdraw assets (and for most cases, that is fine with me), but since you can track your assets across multiple exchanges with Rotki, maybe that limitation doesn't apply here.

**Comment by LefterisJP** [comment]
Hey thanks for the issue!

Indeed it would be really helpful to get smaller analysis than the monolithic huge PnL that has to go through all the history.

For this reason we have a lot of issues and plans pointing towards this, with this as the main one: https://github.com/rotki/rotki/issues/6427

The idea being to slowly get away from a big monolithic PnL but allowing PnL and other type of queries on a selection of events by arbitrary filters in history events view.

As I think that supersedes this issue I will just close this with a link there.
