### ISSUE TITLE
Update indicator does not work

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#781]
## Problem Definition

The update indicator doesn't work properly. 
The reason is that there is a mismatch between the API response and the expected property

```bash
curl -X GET http://localhost:4242/api/1/version
```
```json
{
  "result": {
    "our_version": "1.2.0",
    "latest_version": "v1.2.1",
    "download_url": "https://github.com/rotki/rotki/releases/tag/v1.2.1"
  },
  "message": ""
}
```

The electron app instead checks for `url`
https://github.com/rotki/rotki/blob/5e7cf1947e287479c5de6008adc7e7660b549a44/electron-app/src/model/version-check.ts#L4

which is always empty.

The front-end should be updated to reflect the API schema.

In order to test it in development mode a change in this check might be needed:
https://github.com/rotki/rotki/blob/d7b3f06e8f17a654ac2aa4a96575458bac448728/electron-app/src/store/store.ts#L71

**Comment by LefterisJP** [comment]
Fixed by #783.

@isidorosp next time in the PR write "Fix" or "Close" or "Fixes" or "Closes" in order to automatically close the issue when the PR is merged.
