### ISSUE TITLE
Support coinbase developer portal API keys

### ISSUE THREAD

**Issue by m-roberts** [rotki/rotki#7815]
## Problem Definition

I am unable to connect to Coinbase as I have no legacy keys that I can use, nor can I create any.

When I create an API key via [Coinbase Development Platform portal](https://portal.cdp.coinbase.com/access/api) (which seems to be the only way to do this now), I get key and secret that don't work with rotki.

According to the [Coinbase docs](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-key-authentication), a JWT needs to be generated and from a glance at [the code](https://github.com/rotki/rotki/blob/develop/rotkehlchen/exchanges/coinbase.py), this isn't what is done currently - it seems like the rotki implementation only supports signing in with Coinbase's [legacy keys](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-key-auth-legacy).

### System Description

Operating system: macOS
Rotki version: v1.32.2

**Comment by LefterisJP** [comment]
Thanks for the response and the info @m-roberts! We will see what we can do to speed this up.

Still contact support of coinbase maybe they can help. This is on them. i have two accounts with them and both allow me to still create normal api keys. So maybe there is something they can switch for your account to make it appear?

It makes sense too, as most apps, us included have those integrated. Can't just cut off so many different apps for their users by cutting off the api keys we know so far.

**Comment by scottshapiro** [comment]
Coinbase product team here. Looking into this.

**Comment by bjeavons-cb** [comment]
@m-roberts Some of our Coinbase Eng team is working to address these issues, will you contact me on email too? benjamin.jeavons@coinbase.com

Here's what we're doing

1. Bringing back creation of the old API keys, temporarily
2. Authoring the PR in rotki to also support new API keys
3. Publishing and promoting a guide for other apps and developers on how to upgrade their integration to use CDP API keys too

**Comment by bjeavons-cb** [comment]
@m-roberts legacy API keys can be created again now on coinbase.com/settings/api

**Comment by bjeavons-cb** [comment]
PR to add CDP key support: https://github.com/rotki/rotki/pull/7902

**Comment by LefterisJP** [comment]
Should be addressed by https://github.com/rotki/rotki/pull/7903 and will be in 1.33.1
