### ISSUE TITLE
OKEx support

### ISSUE THREAD

**Issue by tim-does-code** [rotki/rotki#784]
I just prefer exchanges with the most amount of pairs. OKEx has a lot of them.

**Comment by adrien-be** [comment]
+1

**Comment by wokawoka** [comment]
+1

**Comment by wokawoka** [comment]
+1

**Comment by qqq-jump** [comment]
+1

**Comment by daffoxdev** [comment]
+1

**Comment by starise** [comment]
+1

**Comment by LefterisJP** [comment]
Is anyone available who could share with us a read-only api key for OKEX so we can test the implementation as we develop it?

**Comment by akurach** [comment]
@LefterisJP  I can

**Comment by LefterisJP** [comment]
Hey @akurach! Thanks.

Perhaps you can join our discord and DM me when you find time: https://discord.com/invite/aGCxHG7  (has a captcha challenge, so have DMs open)

The implementation will probably not make it for 1.24, but we can definitely push it for next if we have a key to test with.

**Comment by LefterisJP** [comment]
@akurach we tried to use the key but it has expired. Would you be able to ping me again in discord for this?

**Comment by LefterisJP** [comment]
Due to lack of support from users this gets moved

**Comment by yabirgb** [comment]
This will be in 1.27 thanks to https://github.com/rotki/rotki/pull/5328
