### ISSUE TITLE
Website / Readme update

### ISSUE THREAD

**Issue by rakanalh** [rotki/rotki#803]
Currently, when looking at the readme it's hard to see what features it supports being a portofolio tracking software. The website does mention these so it's nice if the readme does that as well so that people who find rotki app through github can get the full picture. 

Also, the readme & website lack 2 more things:
- Screenshot(s) of the app show casing certain features
- A feature matrix describing what exchanges are supported and what features from these exchanges that Rotki needs are implemented.

I might be wrong and everything i just described exists somewhere but these are things i should be able to find on the products homepages (github & rotki.com)

**Comment by LefterisJP** [comment]
Hey @rakanalh!

Thanks for the issue.

> Screenshot(s) of the app show casing certain features

We got that in the usage guide: https://rotki.readthedocs.io/en/latest/usage_guide.html


> A feature matrix describing what exchanges are supported and what features from these exchanges that Rotki needs are implemented.

That we don't have in an obvious place. The only place we state the supported exchanges is here: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-an-exchange

Does not need to be a matrix, just a list of exchanges. For each exchange the same set of features are supported. Trades history, balances and deposit/withdrawal history.

The readme contains links to the usage guide where all this info is given. I don't like duplicating information so I am not sure what is the best way to nicely show them in both the readme and the website? Do you have any ideas/suggestions?

**Comment by rakanalh** [comment]
The reason i created this issue is basically because i looked at the readme / website as if i am looking at it for the first time. It would be very beneficial from a user-acquisition point of view that the most important aspects of the product are stated as soon as the users hit the landing pages (main page on the website & the readme on github).

> The only place we state the supported exchanges is here: https://rotki.readthedocs.io/en/latest/usage_guide.html#adding-an-exchange

I think it would be very important to list supported exchanges as it's a deciding factor for people.

> > Screenshot(s) of the app show casing certain featuresk
> We got that in the usage guide: https://rotki.readthedocs.io/en/latest/usage_guide.html

Sure, some on the readme won't hurt IMO

**Comment by LefterisJP** [comment]
> The reason i created this issue is basically because i looked at the readme / website as if i am looking at it for the first time. It would be very beneficial from a user-acquisition point of view that the most important aspects of the product are stated as soon as the users hit the landing pages (main page on the website & the readme on github).

I see and I agree. I will see what I can do and ping you here to have a look once some improvements are implemented.

Additionally since you have the ability to look at these with the eyes of an external observer it would be **really** beneficial if you could also go in and see if there are specific changes you can do that would make things easier to understand and most importantly help with user acquisition.

PRs on that (and anything else :smile: ) are more than welcome!

**Comment by LefterisJP** [comment]
Closing this since we are redoing the website and the readme points to the website and the usage guide. No need duplicating info.
