### ISSUE TITLE
Avoid querying prices for approvals

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#8043]
At the moment we query prices for all the history events but approvals don't really need it. Same for all the informational event. In my database approvals where 13% of all the events

## Task

- [ ] When querying prices for history events skip informational events

**Comment by RogueCode007** [comment]
hi, is this a frontend bug ?

**Comment by yabirgb** [comment]
> hi, is this a frontend bug ?

Hello! I've asked and the frontend doens't query the price for approvals, it is only the backend in the task before returning them https://discord.com/channels/657906918408585217/683245846070165504/1266016650147135508

**Comment by Dozie2001** [comment]
Hello, Is this issue still up? interested in tackling it.

**Comment by yabirgb** [comment]
Hello! Sorry missed the comment. This issue afaik is still open @Dozie2001 . If I'm not mistaken with a quick look is the function `get_base_entries_missing_prices` the one that needs to add the extra filter and the change should have a test
