### ISSUE TITLE
Enable labels for FIAT currency accounts, enable multiple accounts per currency

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#806]
## Abstract

Enable labels for FIAT currency accounts, enable multiple accounts per currency

## Motivation

Track e.g. a savings and an exchange account separately.

## Specification

Enable existing labels for FIAT currency accounts, enable multiple accounts per currency.

**Comment by LefterisJP** [comment]
Hey @kilrau that's an interesting feature request.

Ideally, if banks ever allowed it, we could be able to pull data directly from the user's banks, but I am not aware of any such APIs at the moment.

Just to make sure I understand:

You are asking to:

- Introduce the concept of an account for FIAT currencies too.
- Enable labels and tags for those accounts too.

The question I would then have is what kind of attributes would such accounts have? Account type? Possible values you say are "savings" and "exchange". What is exchange? Do you mean having FIAT in an exchange? That is actually auto-detected by Rotki, if you for example have EUR in Kraken.

What is the benefit of having multiple accounts per FIAT currency in general? I am not saying there isn't, but at a first though I am not sure I can see it clearly.

**Comment by kilrau** [comment]
Id forget about trying to integrate bank APIs. ETH 2.0 will be faster than banks agreeing on an API standard.


Just enable labels for FIAT and let me create more than one balance for e.g. EUR. Done.

**Comment by kilrau** [comment]
> Just to make sure I understand:
> 
> You are asking to:
> 
> - Introduce the concept of an account for FIAT currencies too.
> - Enable labels and tags for those accounts too.

Not sure our understanding of account is the same. Just let me have multiple balances for e.g. with different tags.


> The question I would then have is what kind of attributes would such accounts have? Account type? Possible values you say are "savings" and "exchange". What is exchange? Do you mean having FIAT in an exchange? That is actually auto-detected by Rotki, if you for example have EUR in Kraken.

No other attributes, I wouldn't force any other attributes. Labels are just fine. Exchange is just an example and can be a stock exchange or anything else Im holding FIAT in, like my "Bausparer" ;)

> What is the benefit of having multiple accounts per FIAT currency in general? I am not saying there isn't, but at a first though I am not sure I can see it clearly. 

I am holding FIAT in various different places and platforms.. Some change frequently, some not. I want to see it and manage it that way.

**Comment by LefterisJP** [comment]
So @kilrau if we implement #807 for all types of assets including FIAT this would be a good solution for this issue request too, right?

**Comment by kilrau** [comment]
Yes, I would say so.

**Comment by LefterisJP** [comment]
This is also done then with the same solution as #807 

PRs: #847 #869

**Comment by kilrau** [comment]
Nice work! Watching out for a new release!

**Comment by LefterisJP** [comment]
> Nice work! Watching out for a new release!

@kilrau: https://github.com/rotki/rotki/releases/tag/v1.4.0
