### ISSUE TITLE
Allow tracking without "account"

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#807]
## Abstract

Allow tracking of funds without specifying an account. E.g. some users might have physical coins where the public address is unknown and would only be revealed once the hologram is pulled off

## Motivation

Allow tracking of funds without account

## Specification

Above.

**Comment by LefterisJP** [comment]
> would only be revealed once the hologram is pulled off

Hmmm .. what do you mean here? What hologram?

**Comment by kilrau** [comment]
Forget about that holo comment, in hindsight it is confusing.

The request is: let me enter "0.25 BTC", " "label: physical bitcoin" without specifying account/pubkey or anything else. Thats it.


Use cases:
- track funds in physical coins
- track funds in lightning channels
- track funds in HD wallets (temporary solution for https://github.com/rotki/rotki/issues/808)
-track funds in L-BTC or anything you dont have in integration for yet

**Comment by LefterisJP** [comment]
Ah I see, yeah that makes sense. This way we would also support blockchains that we can't directly integrate with yet. Like Monero, or ZCash or whatnot.

**Comment by kilrau** [comment]
Exactly

**Comment by LefterisJP** [comment]
This should be fairly easy to implement and we could even push it into the next release.
@kelsos can you help with the frontend for this? I will just simply make some new api endpoints and they will allow you to add to "manually tracked blockchain accounts" and to query them.

Their balances would be added to all others in the dashboard but also shown in a different table in the accounts and balances tab. That should be easy, right?

**Comment by kelsos** [comment]
Sure sounds easy to add let me know when you have the api ready

**Comment by LefterisJP** [comment]
Still not totally done. UI is left. Should be done with #861.

The backend work is done with #847
