### ISSUE TITLE
Wrong date names in the calendar

### ISSUE THREAD

**Issue by LucLeduc** [rotki/rotki#8088]
After an update, i notice that the calendar do not reflect the right day.

Today's date is friday june, 14.   But calendar show thursday.

Rotki 1.33.1
OS
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.2
DISTRIB_CODENAME=victoria
DISTRIB_DESCRIPTION="Linux Mint 21.2 Victoria"

thanks

**Comment by LefterisJP** [comment]
Hey @LucLeduc can you post a screenshot? What timezone are you in? And what is the exact time you checked? Is your clock ofthe local system set correctly?


This is how it looks for me in Germany with Linux right now.

![2024-06-14_13-47](https://github.com/rotki/rotki/assets/1658405/d3192887-8730-4a84-a4a2-eb518104c6a2)

**Comment by LucLeduc** [comment]
Yes.. i'm in the New York timezone...    My OS show Friday, 14 june at 08:00 AM
![Capture d’écran_2024-06-14_07-59-03](https://github.com/rotki/rotki/assets/32939373/b4fab15f-a2fc-467a-802f-f59e44955e0c)

**Comment by LucLeduc** [comment]
![Capture d’écran_2024-06-14_08-02-23](https://github.com/rotki/rotki/assets/32939373/36ccaed4-9e5c-40db-b1c9-97159117fec8)
