### ISSUE TITLE
Test out and maybe migrate to either Circle or Github actions for CI and binary generation.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#809]
## Problem Definition

TravisCI has served both us and the opensource world very well in the past years. But unfortunately it has really become a pain to work with recently.

Random failures, obviously due to VM resources, very slow VMs and so on and so forth actually end up taking a toll on the time we end up using when developing. Especially on the OSX VMs.

It's time to try and find an alternative

## CI Requirements

- Free for opensource
- Fast (er than Travis)
- Consistent, without random hiccups
- Both Linux and OSX VMs.
- Ability to generate our binaries from the CI when we push a tag, just like it happens right now with Travis.
- Windows VMs would be a big plus, so we don't have to use Appveyor to duplicate work.

## Task

Try out both [CircleCI](https://circleci.com/) and/or [Github actions](https://github.com/rotki/rotki/actions/new).

See which one is easier to use and which one satisfies all or most of the above requirements.

**Comment by LefterisJP** [comment]
@kelsos I recall you had a look in this issue, right?

**Comment by kelsos** [comment]
Yes I started playing a bit with github actions

**Comment by LefterisJP** [comment]
We should also play with Circle and see what's better. We lose nothing by having all 3 activated for a while.

**Comment by kelsos** [comment]
@LefterisJP do we still need this issue open?

**Comment by LefterisJP** [comment]
Naah you can close it.
