### ISSUE TITLE
Link to Pro Version broken / 404

### ISSUE THREAD

**Issue by sh0nuff** [rotki/rotki#8096]
## Problem Definition

From Overview section on main github page:

The [Pro Version](https://rotki.com/checkout/plan) of Rotki also supports additional and advanced features. You can find a comprehensive list of them on ☑️ [Feature Coverage Page](https://rotki.com/products/details).

Link for Pro Version leads to : https://rotki.com/checkout/plan, and serves up a 404 error

**Comment by LefterisJP** [comment]
Thanks! Fixed. For such small stuff you can also just open PRs yourself as there is a POAP for contributors :smile:

**Comment by sh0nuff** [comment]
Cheers!

I've never done any work like this myself, so I am a bit intimidated, but
if I see something in the future I will perhaps try my hand at it!

[image: photo]
*Jon Moore*

613.276.0077

***@***.***
<http://www.linkedin.com/in/jon-moore-1263589/>
<http://about.me/jonathanmoore> *About me <http://about.me/jonathanmoore>*
<http://bookme.theasset.ca/lite/hangouts> *Click here to hang out!
<https://bookme.theasset.ca/lite/hangouts>*
