### ISSUE TITLE
Pro Version should be easier to evaluate, pricing easier to find

### ISSUE THREAD

**Issue by sh0nuff** [rotki/rotki#8097]
## Abstract

From Rotki's .com URL, pricing for premium is difficult to find.
- Button at top right should read "Premium Details" or "Why Premium?" for visitors when not logged in (related to #6167 and #1258 )
	- When not logged in, button should redirect to "[Premium](https://rotki.com/products/)" page, but also include a comparison table that displays features of free vs premium, or compares increased values such as "Higher Limits" 
		- this "Higher Limits" paragraph also refers to different tiers, which aren't discussed elsewhere ("With premium these limits are increasing *depending on the tier you have bought*").. are there more than one premium plans?) 
- This Premium page should have the "10.79€/month" pricing at the top of the table under the Premium column header

## Motivation

From Rotki's .com URL, pricing for premium is difficult to find:
- There is no "Pricing" or "Premium" menu, and clicking the "Manage Premium" button brings users to login page, and choosing "First time premium? Sign up now" starts users on journey to sign up without any pricing or information provided as to the costs
- Digging around for the benefits of premium, and finding them at the bottom of the home page displays "Premium Plan
10.79€" without any mention of this is a one time fee, monthly, or anually. Clicking "Get Premium" from this page displays a [new page](https://rotki.com/products/) that cannot be navigated to from anywhere else, and from this page, clicking "Subscribe Now" launches another [new page](https://rotki.com/checkout/pay) with full pricing details/breakdown

**Comment by sh0nuff** [comment]
Much of the English copy is written in a confusing manner - not sure if English isn't the dev's first language, but I am happy to assist in improving aforesaid copy to clarify the wording and intent

**Comment by LefterisJP** [comment]
Hello thanks for the feedback! English is not the first language of anybody here. 

Since this is not an actionable issue I will just forward it to our frontend/design team and close.

Unless you wanted to open a PR with some suggestions. The website design is in https://github.com/rotki/rotki.com

We are in the middle of a redesign right now so things are changing.

Appreciate the insight and we will see what we can do.
