### ISSUE TITLE
Replace beaconcha.in daily stats scraping with API

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#8120]
## Abstract

We are currently taking the ETH2 validator daily stats by scraping since at the time there was no way to get it via API: https://github.com/rotki/rotki/blob/cb8549028040d7457a7aa5fcbf2e2ec2ddcec3a3/rotkehlchen/chain/ethereum/eth2_utils.py#L50

Now there is an API that we can use: https://beaconcha.in/api/v1/docs/index.html#/Validator/get_api_v1_validator_stats__index_

## Task

- [x] Create a setting if the user wants the daly stats queried. Since this would considerably increase rate limiting depending on amount of validators it needs to be configurable
- [x] Replace the scraping logic with the API

**Comment by yabirgb** [comment]
Finished in https://github.com/rotki/rotki/pull/8158
