### ISSUE TITLE
zkSync ZK Token Displayed as Polyhedra ZK Token on Binance Portfolio

### ISSUE THREAD

**Issue by izzetemredemir** [rotki/rotki#8131]
## Problem Definition

I am using Rotki version 1.33.1 and I have encountered an issue with the token display. The ZK token from zkSync is being confused with the ZK token from Polyhedra, resulting in incorrect price displays. Although I hold zkSync's ZK token, it is being shown as Polyhedra's ZK token. This issue is affecting my portfolio on the Binance exchange.

### System Description
Rotki version: 1.33.1

**Comment by moxw** [comment]
Hello @izzetemredemir,

Thank you for bringing this issue to our attention.

To correctly map exchange assets, please refer to our usage guide here: https://rotki.readthedocs.io/en/latest/usage_guide.html#manage-cex-centralized-exchange-mapping

For your specific case, you should use the Add Mapping option with the following details:
![Screenshot_20240620_170439](https://github.com/rotki/rotki/assets/10359228/84c51c70-72c5-4e7e-856d-c45dbe7e3dea)

We will ensure this mapping is included in our next release.

**Comment by izzetemredemir** [comment]
> Hello @izzetemredemir,
> 
> Thank you for bringing this issue to our attention.
> 
> To correctly map exchange assets, please refer to our usage guide here: https://rotki.readthedocs.io/en/latest/usage_guide.html#manage-cex-centralized-exchange-mapping
> 
> For your specific case, you should use the Add Mapping option with the following details: ![Screenshot_20240620_170439](https://private-user-images.githubusercontent.com/10359228/341394765-84c51c70-72c5-4e7e-856d-c45dbe7e3dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjkwMDgsIm5iZiI6MTcxODkyODcwOCwicGF0aCI6Ii8xMDM1OTIyOC8zNDEzOTQ3NjUtODRjNTFjNzAtNzJjNS00ZTdlLTg1NmQtYzQ1ZGJlN2UzZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAwMTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTdmMzMyMjNkZTlkNTE1ODk2MjRjNmMwZmZiNTIyYmVkNjQxOTllOTg1NTFmMmYxMmYxZTMxYzlkODgxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3wW7LGEnrrxNqQZ6KcFRbNW-NO-tsbGtUB1KWiDFggA)
> 
> We will ensure this mapping is included in our next release.

What is your rotki version?

**Comment by LefterisJP** [comment]
> What is your rotki version?

Always latest version. 1.33.1. If you are not at latest version, first thing would be to upgrade to latest.

**Comment by izzetemredemir** [comment]
> > What is your rotki version?
> 
> Always latest version. 1.33.1. If you are not at latest version, first thing would be to upgrade to latest.

I don't see ZKsync networking among the options.

**Comment by LefterisJP** [comment]
> > > What is your rotki version?
> > 
> > 
> > Always latest version. 1.33.1. If you are not at latest version, first thing would be to upgrade to latest.
> 
> I don't see ZKsync networking among the options.

It's going to be added in next release.

**Comment by LefterisJP** [comment]
But @izzetemredemir you don't need to choose the network. Jsut the token in the mapping. And the token should be there if you ever visited the airdrops section. For more questions please come in our discord: https://discord.rotki.com/
