### ISSUE TITLE
Add Blockpit in data importer

### ISSUE THREAD

**Issue by Adventurousdonut** [rotki/rotki#8147]
## Motivation
Blockpit allows you do easily export yearly csv files for free, it would be great if you could just import those into rotki.

**Comment by LefterisJP** [comment]
> ## Motivation
> Blockpit allows you do easily export yearly csv files for free, it would be great if you could just import those into rotki.

Hey @Adventurousdonut welcome!

We don't mind adding more CSVs.

But we would need a sample file for each type you want us and a bit more information. Like what is this blockpit, a link to the project etc.

But the most important is the sample CSV file as we would base the implementation on it.

**Comment by Adventurousdonut** [comment]
Hey, thanks.

Sure, no problem. Here's a link to [Blockpit](https://www.blockpit.io/).

And here's a sample CSV export [Transactions_2023.csv](https://github.com/user-attachments/files/15937513/Transactions_2023.csv).

**Comment by nicholasyoder** [comment]
Hey @Adventurousdonut , I'm working on this and I'm not totally sure what the `NonTaxableIn` and `NonTaxableOut` events are (See lines 26, 31, and 32 of the CSV file you provided above).

Could you provide a few more details about them? Like what kind of event triggers them? and would it make sense to import them as if they are Deposit/Withdrawal events?
