### ISSUE TITLE
Refresh token balances causes exception "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by pyggie** [rotki/rotki#8169]
## Problem Definition

On the Accounts & Balances / Blockchain Balances page, in the Ethereum balances section, when I click on "Re-detect tokens" or click the circular refresh icon for a specific account, the logs show many queries and after 30-60 seconds show this failure: `Exception Info: maximum recursion depth exceeded`. In the UI the account then shows 0 tokens have been detected. This happens repeatedly and consistently.

## Logs
```
[25/06/2024 18:17:39 UTC] ERROR rotkehlchen.api.rest Greenlet with id xxxxxx: Greenlet for task 170 dies with exception: maximum recursion depth exceeded.
Exception Name: <class 'RecursionError'>
Exception Info: maximum recursion depth exceeded
Traceback:
```

Earlier in the logs a search for task 170 shows the following matches:
```
[25/06/2024 18:16:54 UTC] DEBUG rotkehlchen.api.server Greenlet-46: end rotki api GET /api/1/balances/blockchains/eth view_args={'blockchain': 'eth'}, query_string=b'async_query=true&ignore_cache=true', status_code=200, result={'result': {'task_id': 170}, 'message': ''}
[25/06/2024 18:16:54 UTC] DEBUG rotkehlchen.api.rest Greenlet-51: Async task with task id 170 started
```

### System Description

Operating system: Windows 10 running Docker Desktop 4.29.0
Rotki version: 1.33.1 inside docker container with repo digest id `rotki/rotki@sha256:4cd602f51a60e4db4f816ea7a48abd00d5e4692fe961e40b55e2fbe529ecfef9`

Other details:
  - Rotki premium subscription
  - using local Dappnode Nethermind instance for Ethereum RPC
  - using Alchemy subscription for other chain RPCs

**Comment by LefterisJP** [comment]
Hello @pyggie. This is not a problem we can reproduce as it most probaly depends on exactly the address and history you are querying for. 

Something weird must be there.

To reproduce we would need a lot more information about the particular address/es this happen. Please join our discord https://discord.rotki.com/ and provide the required information to someone from our team. Will also probably need some back and forth until the issue can be reproduced.

Discord here: https://discord.rotki.com/

**Comment by pyggie** [comment]
Will do, thanks.

**Comment by yabirgb** [comment]
Done in this issue scheduled for 1.35.0 https://github.com/rotki/rotki/pull/8341
