### ISSUE TITLE
Support for Coinbase Prime

### ISSUE THREAD

**Issue by dacoldest** [rotki/rotki#8170]
There is no API support for Coinbase Prime accounts: https://docs.cdp.coinbase.com/prime/docs/welcome/

I'd really appreciate adding API support for Coinbase Prime which is different from Coinbase Pro and Coinbase.

**Comment by ccerv1** [comment]
+1 please 🙏

**Comment by yabirgb** [comment]
@dacoldest @ccerv1 next release 1.36.0 will have support for coinbase prime. The user that helped us had events but not an example for all of them. At the moment of trying it if you find anything missing please report it to us and we can fix it
