### ISSUE TITLE
CurrencyDropdown should replace font-awesome icon with unicode character

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#818]
## Abstract

Currently, for the logo of the currency on the CurrencyDropdown we use icons from FontAwesome
https://github.com/rotki/rotki/blob/8c700bde92d78cf3bbf46cd5e5c0dca8d3716896/electron-app/src/components/CurrencyDropDown.vue#L16

Currencies already include a Unicode character for the currency icon.
https://github.com/rotki/rotki/blob/6339a229c9239580c0c70c5379d896505e0795b4/electron-app/src/model/currency.ts#L6

The Unicode character should be used instead to display the currency icon, and the icon property should be removed from the Currency class. https://github.com/rotki/rotki/blob/8c700bde92d78cf3bbf46cd5e5c0dca8d3716896/electron-app/src/model/currency.ts#L4

## Motivation

Font-awesome currency support is limited but this is not the same for Unicode characters. There is not a specific reason to keep icons only for a few cases since there is Unicode support already.

**Comment by isidorosp** [comment]
Closing this as it was closed by #844
