### ISSUE TITLE
Use additional sources for ethereum data when user does not have his own node

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#820]
## Abstract

We can use the following open nodes as additional ethereum data sources:

- mycrypto https://twitter.com/hitchcott/status/1244544268619915264
- Igo Barinov's from POA node: https://twitter.com/barinov/status/1253984090975600640
- Pool of Avado nodes: https://status.cloud.ava.do/
## Task

Along with etherscan use the above as a source of ethereum data for Rotki users if they don't run their own node.

**Comment by MrLuit** [comment]
Although this project is Python, and `eth-scan` implementation is TypeScript, the eth-scan contracts can still be used to batch calls. I'm not too familiar with Python but let me know if I can help you with anything!

**Comment by LefterisJP** [comment]
Hey @MrLuit we will keep this issue for utilizing mycrypto as another source and made https://github.com/rotki/rotki/issues/922 for `eth-scan`.
