### ISSUE TITLE
Fetch and display contract info from Kleros Curate ATR

### ISSUE THREAD

**Issue by EricGaia** [rotki/rotki#8213]
## Abstract

Currently, Rotki does not fetch or display contract information from external registries like Kleros' Address Tag Registry (ATR). Adding this feature would provide users with more detailed information about the contract addresses they interact with, directly within the application.

## Motivation

Fetching and displaying contract information from Kleros Curate's ATR would provide users with detailed insights directly within Rotki. This would enhance user experience by informing users about the contract addresses they are seeing and giving them accurate and secure information about the contracts they are interacting with.

## Specification

Specification

- Integrate functionality to fetch and display contract information from Curate's ATR.
- Use `graphql-request` or a similar library to handle GraphQL queries.
- Display relevant information such as the address, project name, public note, description, and link.

I've implemented the functionality to fetch and display contract information from Curate's ATR in `HashLink.vue` by querying the subgraph.
The implementation is working, but I am open to feedback and suggestions for improvements. You can view my implementation here: [https://github.com/y86993/rotki](https://github.com/y86993/rotki).

Would it be okay to open a PR for this feature? Thank you.
![curate_rotki](https://github.com/rotki/rotki/assets/153207335/40d1a1b3-78a8-42b4-9c75-519607d68c45)

**Comment by LefterisJP** [comment]
Why did you close the issue? It's a good thing to have at some point.

But the implementation is wrong as this should not be done on the frontend.

Feel free to join our discord to chat with us about this though keep in mind this week is hectic:  https://discord.rotki.com/

**Comment by y86993** [comment]
Sorry, I've made it from the wrong, account. I've opened a new one and joined the Discord.
