### ISSUE TITLE
Adding Harvest as a DeFi protocol

### ISSUE THREAD

**Issue by timfong888** [rotki/rotki#8215]
## Abstract

I use harvest.finance, and when I look under `DeFi` I don't see my auto compounding farms/vaults there.

## Motivation

Harvest is an easy to use auto compounding solution for DeFi.  I am moving many of my DeFi positions there, myself.

## Specification

I'm not sure what this would mean, I suspect it is perhaps a list of the contracts for their various vaults?

https://docs.harvest.finance/how-it-works/contract-addresses-1

**Comment by LefterisJP** [comment]
Hey thank you for opening an issue but this is already on our sight and an issue exists: https://github.com/rotki/rotki/issues/1617

**Comment by timfong888** [comment]
Would it involve adding the subgraph (not the hosted version but the one on
the network)?


Inline image

Tim Fong

p: 415-508-6888

e: ***@***.***
