### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by pcaversaccio** [rotki/rotki#8261]
## Problem Definition

I just upgraded to the latest `v1.34.0` version on my Windows machine, and I keep getting the following error whenever I close Rotki:

![image](https://github.com/user-attachments/assets/e00a4c92-c4eb-4173-b533-3053ed728790)

This has not been the case in the previous versions. I also I have to click always through two of this errors (after I click `OK` the same message appears again and I click again `OK` and everything is fine).

I haven't upgraded it on my Linux machine yet, so not sure if something similar happens on Ubuntu, but maybe you can test already.

**Comment by yabirgb** [comment]
Hello! Thanks for reporting it. We will check
