### ISSUE TITLE
MakerDao DSR portal does not detect vaults

### ISSUE THREAD

**Issue by spaceblankey** [rotki/rotki#833]
The menu bar on the left says "De...Fi" --> "Loans" which suggests that the integration is not just DSR tracking but ETH locked in vaults and Dai generated as well. Though these features do not appear, it only shows the DSR Dai locked. This would be great to see this as it can give a very distorted picture of ones financial situation if unaccounted for.

**Comment by LefterisJP** [comment]
Hey @spaceblankey thanks for the issue and the grant support!

We will add support for Vaults. We already have an issue for it. It won't be the same tab as DSR though as it's not lending but borrowing. The issue to follow is here: https://github.com/rotki/rotki/issues/707
