### ISSUE TITLE
Prevent addressbook duplication addition

### ISSUE THREAD

**Issue by lukicenturi** [rotki/rotki#8350]
So for endpoint <PUT> names/addressbook/private or global
I am not prohibited to put multiple entries with same blockchain and address

<img width="1143" alt="image" src="https://github.com/user-attachments/assets/03365bb1-85fc-4f4f-b252-fcb72d63ea5b">

This should not happen,
If I add new entry with a blockchain and address, the previous entry with same blockchain & address should be deleted.

**Comment by yabirgb** [comment]
Is probably my old friend: nullable column in composed primary key https://github.com/rotki/rotki/blob/a8bdd0db91d4f3b6060127dc7a0adba383e4e999/rotkehlchen/globaldb/schema.py#L247

**Comment by yabirgb** [comment]
for this task:

- In bugfixes create a data migration that uses a constant instead of NULL in the db to avoid the unique check with the NULL constant
- In develop create a db upgrade to change the type of the column to `NOT NULL` to avoid having this issue in the future
