### ISSUE TITLE
wrong "Node not connected" notice

### ISSUE THREAD

**Issue by koeppelmann** [rotki/rotki#837]
![Screen Shot 2020-04-04 at 14 18 21](https://user-images.githubusercontent.com/2594089/78450628-455f8200-7680-11ea-83ce-0809078fd632.png)
![Screen Shot 2020-04-04 at 14 18 12](https://user-images.githubusercontent.com/2594089/78450629-45f81880-7680-11ea-9c5c-c890e841d362.png)

Everything works fine, I can query the blockchain - the App nevertheless says - "Node not connected".
I can send the log fine (if helpful) privately.

**Comment by LefterisJP** [comment]
Thanks for the issue report @koeppelmann!

No need for logs. I can reproduce locally. Not sure when this UI element broke but should be easy to figure out what's wrong and include a fix for the next release.
