### ISSUE TITLE
Add information for what functionality API keys are needed.

### ISSUE THREAD

**Issue by koeppelmann** [rotki/rotki#838]
It is not clear what keys are needed for the application to work fully, or what features will not work without.

![Screen Shot 2020-04-04 at 14 28 17](https://user-images.githubusercontent.com/2594089/78450688-b737cb80-7680-11ea-868b-29ee5b090beb.png)

**Comment by LefterisJP** [comment]
That's true. I think we may have something in the docs, but need to make sure of it.

Regardless it should be explained in the UI what everything is for. At the moment you only need etherscan. All other are optional.
