### ISSUE TITLE
Detected tokens randomly dissapear in 1.34.2

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#8414]
## Problem Definition

For addresses that have recently received new tokens the detected tokens randomly disappear and this is only fixed by redetecting tokens for the address. This started happening in 1.34.2. I suspect it's due to https://github.com/rotki/rotki/pull/8340

The `maybe_detect_new_tokens()` method introduced in that PR may be the culprit.

It does exactly that ... it maybe detects new tokens from events, if there is new events for the address.

But ... ehm ... here: https://github.com/rotki/rotki/blob/6634f7154bf670d36c5a05511e82bc14b3fc5e3c/rotkehlchen/tasks/assets.py#L410C9-L411C42

```python
detected_tokens = defaultdict(list)
```

Initializes the detected tokens as an empty list. Then runs the logic to detect IN token events to the given address.

and then .. here: https://github.com/rotki/rotki/blob/6634f7154bf670d36c5a05511e82bc14b3fc5e3c/rotkehlchen/tasks/assets.py#L445

```python
    with database.conn.write_ctx() as write_cursor:
        for (chain, location_label), tokens in detected_tokens.items():
            database.save_tokens_for_address(
                write_cursor=write_cursor,
                address=string_to_evm_address(location_label),
                blockchain=chain,
                tokens=tokens,
            )
```

saves the detected tokens per address

So it saves only whatever tokens may have come in via new IN events for an address since last time the function ran. Replacing whatever previous detected tokens were before.

Which would explain the bug I am seeing exactly.

## Task

Fix it.

Things I can imagine need doing is:

1. Make it only append to the already detected tokens. Not overwrite them. (yes in the future we can be smarter and check both in/out events and also remove tokens but that's out of scope)
2. In the migration, schedule a full redetect of tokens for all evm chains? This will take A LONG time. For me ~30 mins. So I would not want this to be done during the loading time of the migration. So not sure how to handle this. Another solution would be to tell users to manually redetect but asking user action is never a good idea as 90% of them won't see it.

**Comment by yabirgb** [comment]
Done at https://github.com/rotki/rotki/pull/8419
