### ISSUE TITLE
Handle monerium v2 contract upgrade

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#8452]
## Problem Definition

Monerium has made a contract upgrade: https://monerium.dev/docs/tokens. This has introduced many improvements but has also created some problems.

The way that it works now is that:
1. Approvals have been reset
2. For each v1 transfer both v1 and v2 token events are emitted.
3. For each v2 transfer only v2 token events are emitted.
4. Balances of both are mirrored.

The problem for rotki is:
- Which token to show as balance and which oracle to use.
- How to stop showing duplicate events in history
- How to do proper accounting

## Task

To handle the problems probably the best way would be:

1. Always use the v2 contract for balance queries. Ignore v1. Handle it as ignored asset even for balances so as to not double count balances or show more tokens owned
2. For history events let's say `T`  is the timestamp of the upgrade, `X` the old contract and `Y`  the new.  For every event involving either `X` or `Y` contracts after `T` count only `Y` and completely ignore `X` events and state changes.
3. For accounting do same as you would do for display problems in (2)
4. We also have to edit our minting/burning logic which searches for the mint/burn transactions and decorates them with the SEPA data. To search for mint/burn of v2 after the `T` time.

**Comment by gislik** [comment]
Hi @LefterisJP 

With regards to proposed the solution, I have a few comments that I hope are helpful.

1. You can use either [V1](https://gnosisscan.io/token/0xcB444e90D8198415266c6a2724b7900fb12FC56E) or [V2](https://gnosisscan.io/token/0x420CA0f9B9b604cE0fd9C18EF134C705e5Fa3430) to query balances.  They will always show the same balance. V2 will be more future proof as we'll put all our effort to migrate wallets, explorers, etc to use that version.
2. `X` will contain all the event logs to reconstruct the state of EURE up until `T` and `Y` will contain the events after `T`. Note that before `T`, `Y` only has "checkpoint", i.e. one event per address representing the state at `T`. 

`T` = [35656951](https://gnosisscan.io/block/35656951)  for EURe on Gnosischain
`T` = [60733237](https://polygonscan.com/block/60733237) for EURe on Polygon

**Comment by yabirgb** [comment]
Example of v2 token being sent and not emitting the v1 event https://gnosisscan.io/tx/0x67df15bb6abe97817548dcf2591c6015e4a7e35c143a90099718bab91421fa0e

**Comment by yabirgb** [comment]
Fixed on https://github.com/rotki/rotki/pull/8496
