### ISSUE TITLE
Add back the Exchange Trades UI panel

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#846]
## Abstract

At some point we had an exchange trades menu option that did not do anything. See: #284
That was removed.

But the need to see our historical exchange trades somewhere outside of the profit/loss report still remains. So we need to properly implement it and add the UI element again.

### Backend

- Allow querying of historical trades per exchange. Save them in the DB. This should already be implemented and done. But need to double check
- Do not query exchange trades only if user requests a tax report but do it in the background if we have API keys for an exchange.
- Make sure this functionality is also accessible via the API.

### Frontend

- Add a UI page for trades per exchange. For now it should only be historical trades. In the future we will also show open trades in a "Latest Activity" table.
- All trades the user has done should be shown there in a table. Format is the same as in the OTC trades.

**Comment by LefterisJP** [comment]
Related: Related: https://github.com/rotki/rotki/issues/1106, https://github.com/rotki/rotki/issues/968 and https://github.com/rotki/rotki/issues/216

**Comment by kelsos** [comment]
This issue seems irrelevant now. Reading the description it seems like this is what we do with the history/trades view. For the future part, we have an issue about the latest activity so it should be sufficient.

**Comment by LefterisJP** [comment]
yes ... but! Importan thing to note is that we could allow ability to perform trades from such a UI
