### ISSUE TITLE
Use assert_proper_response_with_result in all tests

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#849]
## Task

In [this](https://github.com/rotki/rotki/pull/847/files#diff-1e92ec9b9e1535f1e9539aad6ee78e63R68) PR we are introducing a new testing convenience function for API calls.

In most of the api tests it should replace the `assert_proper_response()`, checking message is empty and fetching result call.

For example here: 
https://github.com/rotki/rotki/blob/42296b585e46acdde195883b77b13f9d2da803b8/rotkehlchen/tests/api/test_periodic.py#L30-L33

This would be rewritten as:
```python
result = assert_proper_response_with_result(response)
```

Do the above in all of the api tests: https://github.com/rotki/rotki/tree/develop/rotkehlchen/tests/api

**Comment by Aragar199** [comment]
Seems like a straightforward issue. I'd like to take this.

**Comment by LefterisJP** [comment]
Hey @Aragar199 feel free to! It's one of those easy "todo later" notes that we made and never got to it :)
Will make the test code cleaner!
