### ISSUE TITLE
NFTs counted twice?

### ISSUE THREAD

**Issue by rkalis** [rotki/rotki#8535]
## Problem Definition

Since some time I've noticed that many NFTs now show up both under "Assets" *and* in the separate NFT section. I'm not entirely sure what is happening here, but it looks like this is inflating the total asset balance.

### Example

Under NFTs:

<img width="1043" alt="CleanShot 2024-09-12 at 11 23 29@2x" src="https://github.com/user-attachments/assets/3980dec4-7a36-4a4a-9495-6d914f6172ca">

Under Assets:

<img width="984" alt="CleanShot 2024-09-12 at 11 23 06@2x" src="https://github.com/user-attachments/assets/d8160e17-8ff1-4886-a889-a7a4ccfd2185">

### System Description
Operating system: macOS 13.6.9
Rotki version: 1.34.3

**Comment by lukicenturi** [comment]
hi @rkalis thanks for reporting, can you click the asset icon, and then copy the asset identifier? and paste it here?

**Comment by rkalis** [comment]
For LilPudgys it's this: eip155:1/erc721:0x524cAB2ec69124574082676e6F654a18df49A048

<img width="883" alt="CleanShot 2024-09-12 at 13 31 39@2x" src="https://github.com/user-attachments/assets/3e86c3bb-f95a-4507-afb6-ae1a2ef89957">
