### ISSUE TITLE
Enable windows testing in Github actions for nightly runs

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#855]
Enable windows testing and packaging in Github actions

Followup after https://github.com/rotki/rotki/pull/853/

**Comment by kelsos** [comment]
@LefterisJP Do we plan to generate nightly windows builds? (at the moment we only do osx/linux)

**Comment by LefterisJP** [comment]
I would say unless it's super easy we don't currently need it, right?

**Comment by kelsos** [comment]
It is super easy
