### ISSUE TITLE
Customize default electron front-end UI to increase end-user quality of life

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#864]
## Abstract

Investigate how easy it is to replace existing menu options in Rotki frontend, as they could be more useful for the end-user.

## Motivation

We should modify the Application Menu and Context Menu (does not exist by default in Electron) to improve the end-user experience. Eventually we could even put the menu bar in the title bar to save vertical space (like in VSCode, example below)
![image](https://user-images.githubusercontent.com/27592/79050806-c2649b80-7c2c-11ea-8c36-431e5f4f85bc.png)

## Specification
**App Menu modification proposals:**
- _File_ TBD
- _Edit_ TBD
- _View_ TBD
- _Window_ Redundant?
- _Help_ get rid of electron defaults and replace with:
- [x] Usage Guide --> https://rotki.readthedocs.io/en/latest/usage_guide.html
- [x] FAQ --> https://rotki.readthedocs.io/en/latest/faq.html
- [x] Changelog --> https://rotki.readthedocs.io/en/latest/changelog.html
- [x] Bug Reports & Feature Requests --> https://github.com/rotki/rotki/issues
- [x] Rotki Logs --> opens local directory where logs are (differs per OS but in Windows it's standard, what about linux / OSX?)

--- EDIT: The above has been addressed by #869 .

**Context menu (i.e. rightclick)**
Consider implementing this package https://github.com/sindresorhus/electron-context-menu or we do it by hand.

_Minimum functionality:_
- [ ] Cut / Copy / Paste

_Further functionality:_

Possibly context-sensitive options? For example: right clicking mentions of ETH / BTC could allow for a context menu option to open https://www.coingecko.com/en/coins/ethereum? Same for a wallet address (open it a blockchain explorer etc.). In data tables we could highlight relevant rows and rightclick -> export, etc.

**Comment by LefterisJP** [comment]
Very nice idea @isidorosp 
@kelsos what do you think?

**Comment by isidorosp** [comment]
> Very nice idea @isidorosp
> @kelsos what do you think?

Eventually I think it would be nice to integrate the menubar into the titlebar (like vscode) but from what I see that either requires nodeIntegration or some more complicated work via preload. In the meantime I have already got this working on windows:
![image](https://user-images.githubusercontent.com/27592/79071759-bab0ff80-7cdd-11ea-93e5-a7eb80faa84c.png)

**Comment by kelsos** [comment]
We already discussed that with @isidorosp and I like the idea. It certainly is a nice improvement

**Comment by kelsos** [comment]
The only thing that is missing from the description of this PR is the context menu.

The context menu is tricky since we are both in electron and on the browser. We could do a cut/paste/copy menu for only electron, since the web browsers would provide their own context menus but going context-aware would require us to be able to somehow implement the same functionality in an electron agnostic way.
