### ISSUE TITLE
Include a link to transactions on the "issues found with generated report" screen

### ISSUE THREAD

**Issue by TimTinkers** [rotki/rotki#8690]
## Abstract

Hello, I am a first-time Rotki user attempting to get it accurately tracking my portfolio so I can do taxes. I've years and years of cruft to get sorted first so naturally, when I went to generate a tax report, I have many issues that I need to manually resolve. In this screen there is a Date/Time reference for presumably when I received the asset with the missing price, but it would also be very nice to have a link to the transaction being referenced for that time as well.

![2024-10-07-223338_980x330_scrot](https://github.com/user-attachments/assets/6d36bca2-f4db-40a4-b011-78cd34377c1d)

## Motivation

Having a convenient link to the block explorer for these transactions would make it much easier for the user to remember what they were doing and may make it easier to figure out the price they should input, particularly if they were swapping stablecoins for the asset in question.

## Specification

Presumably the Date/Time of the asset is being pulled from the time of a particular transaction and Rotki could insert the link here, like it does on the "newly detected tokens" screen.

**Comment by TimTinkers** [comment]
Also not to muddy the waters on this feature request (I'd be happy to open another issue once I confirm it's not something wrong on my end) but this is especially needed for me because the Rotki price detection in resolving these missing prices seems to not be working and getting rate-limited 100% of the time on anything that is not Ether (including some very popular DeFi coins that should be definitely retrievable). I will look for logs to confirm what might be happening there tomorrow.

**Comment by LefterisJP** [comment]
> In this screen there is a Date/Time reference for presumably when I received the asset with the missing price, but it would also be very nice to have a link to the transaction being referenced for that time as well.

This screen has 2 possibilities.

1. Missing acquisition, in which case it's an event that sees you try to spend something you don't have. So we need you to tell us where that something was acquired and at what price
2. Missing price for an event. Means rotki can't query it in any of the given oracles. (rate limiting is also possible as you said)

Adding a link here should be possible technically. Let us think a bit and we may be able to improve here. Thanks!

**Comment by TimTinkers** [comment]
Thanks! I also dug into the rate limiting issue further and found it was due to missing CryptoCompare information, #8696.

**Comment by kelsos** [comment]
@lukicenturi do you remember what is needed for this to be implemented?

**Comment by LefterisJP** [comment]
Made it so the backend also returns the originating event identifier, if existing, for any missing acquisition
