### ISSUE TITLE
Let me specify API keys for CoinGecko and DefiLlama

### ISSUE THREAD

**Issue by TimTinkers** [rotki/rotki#8696]
## Abstract

Currently Rotki lets me specify an API key for CryptoCompare, but not for the fallback CoinGecko or DefiLlama price oracles.

## Motivation

I am a first-time user of Rotki performing a big import to try and prepare a tax report. Rotki cannot detect my cost basis for some coins because CryptoCompare is missing the data and a rate limit is being enforced by CoinGecko and DefiLlama.

I have my own CoinGecko and DefiLlama API keys and wish that I could use these to avoid the rate limit in case CryptoCompare does not have the information I need.

I turned on debug mode to check the logs and see what was happening in my specific case. For example, CryptoCompare is missing the early history of the Compound token whereas this data is available on the other oracles where I remain constantly rate-limited.

![2024-10-08-133538_719x580_scrot](https://github.com/user-attachments/assets/cd246ee4-bdd9-4740-ab88-884d93ccae23)

## Specification

I have not done any digging into this, but presumably Rotki would be able to surface the ability to specify these API keys given that it already does so for CryptoCompare in the "External Services" setting.

**Comment by LefterisJP** [comment]
That is because at the time of creation of those oracles there was no api key possibility. Adding them should be easy so we will do it.

**Comment by LefterisJP** [comment]
This is now implemented in the bugfixes branch and will roll out in 1.35.1
