### ISSUE TITLE
Cryptocompare query failed with "You are over your rate limit, please upgrade your account"

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#873]
## Problem Definition

This happened in the tests here: https://github.com/rotki/rotki/pull/872/checks?check_run_id=581306979

```
>                   raise RemoteError(error_message)
E                   rotkehlchen.errors.RemoteError: Failed to query cryptocompare for: "https://min-api.cryptocompare.com/data/v2/histohour?fsym=DASH&tsym=EUR&limit=2000&toTs=1434470400". Error: You are over your rate limit please upgrade your account!
```

## Task

Find out what's this new error from cryptocompare and handle accordingly.

Edit: What happened is that all 4 retries during the backing off were used up and then Rotki gave up querying cryptocompare. Perhaps ... increase the number of retries?

**Comment by LefterisJP** [comment]
Okay more information. This seems to happen only in Github actions. In Travis we cache the location where the price information are queried `$HOME/.cache/.rotkehlchen-test-dir`

https://github.com/rotki/rotki/blob/19154b14ef2f6225b0a4f1b7744ac85d64363fae/.travis.yml#L79-L87

and it's also given as a test fixture:
https://github.com/rotki/rotki/blob/19154b14ef2f6225b0a4f1b7744ac85d64363fae/rotkehlchen/tests/fixtures/accounting.py#L28-L29

In the github-actions workflow I don't see this directory cached. Is this observation correct @kelsos ?

Then the solution is twofold:

1. Increase the number of retries ... don't want this to ever happen in reality
2. Cache that directory so that for tests we have reduced cryptocompare queries.

**Comment by kelsos** [comment]
Yes it seems that I missed that directory during the migration (Seen the issue my comment on the PR for OSX doesn't make sense)
