### ISSUE TITLE
Adding an exchange with invalid inputs creates an invalid exchange and does not allow the user to replace it as it already exists

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#874]
## Problem Definition
Trying to add an exchange with no/invalid keys specified errors but also creates an exchange entry for the user. This leads to the user being unable to edit/delete/correctly set the API key for this exchange.

_This only seems to happen with specific exchanges:_
Poloniex
Bittrex
Bitmex
Binance

_Steps to reproduce:_

* A user with no exchanges set up wants to add a new exchange so they go to create one:
![image](https://user-images.githubusercontent.com/27592/79249312-5af15a80-7e7d-11ea-87ac-d952e023b125.png)

![image](https://user-images.githubusercontent.com/27592/79249107-106fde00-7e7d-11ea-971d-f1738e72659e.png)
* They leave the key fields blank and click Setup
* This returns a 500 error from the API
![image](https://user-images.githubusercontent.com/27592/79249350-70ff1b00-7e7d-11ea-83b6-c43175c32371.png)
* However in the background the exchange has been added to the user, 
![image](https://user-images.githubusercontent.com/27592/79249421-896f3580-7e7d-11ea-9ba2-e588afa8c8b0.png)
But in the front-end it still looks like it is not set up, which means that the user is unable to edit or delete it.
![image](https://user-images.githubusercontent.com/27592/79249491-a0158c80-7e7d-11ea-80df-d3cab63c208e.png)

_Log:_
[rotkehlchen.log](https://github.com/rotki/rotki/files/4476534/rotkehlchen.log)

### System Description

```
Windows 10
Rotki 1.3.1 develop
```

**Comment by LefterisJP** [comment]
> But in the front-end it still looks like it is not set up, which means that the user is unable to edit or delete it.

@kelsos Any idea why at a 500 Error it's still considered setup for the frontend?

**Comment by kelsos** [comment]
@LefterisJP can't tell if I don't look at the code first.
