### ISSUE TITLE
Binance CSV not imported correctly.

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#8807]
User @ jesse274523 reported in discord that the Binance CSV that we have to test doesn't work when imported in the app

> Hi Everyone. I am testing out Rotki and trying to import binance CSV files however the import seems to fail on lines will sell, buy or fee operations. I have tried testing with lines from https://github.com/rotki/rotki/blob/develop/rotkehlchen/tests/data/binance_history.csv on version Rotki 1.35.1 rather than my file and the issue still occurs. Is this a known issue?

The logs show

```
DEBUG rotkehlchen.data_import.utils Greenlet-1: Failed to import row 1 {'User_ID': '1', 'UTC_Time': '2020-10-30 14:21:20', 'Account': 'Spot', 'Operation': 'Buy', 'Coin': <Asset identifier:ETH name:Ethereum symbol:ETH>, 'Change': FVal(0.03605), 'Remark': '', '_index': 1} of Binance CSV file. Could not process CSV entry.
DEBUG rotkehlchen.data_import.importers.binance Greenlet-1: Skipped Binance trade rows: [[1604067680, [{'User_ID': '1', 'UTC_Time': '2020-10-30 14:21:20', 'Account': 'Spot', 'Operation': 'Buy', 'Coin': <Asset identifier:ETH name:Ethereum symbol:ETH>, 'Change': FVal(0.03605), 'Remark': '', '_index': 1}]]]
DEBUG rotkehlchen.data_import.importers.binance Greenlet-1: Skipped Binance non-trade rows []
DEBUG rotkehlchen.data_import.importers.binance Greenlet-1: Total found Binance entries: 0
DEBUG rotkehlchen.data_import.importers.binance Greenlet-1: Total skipped Binance csv rows: 1
DEBUG rotkehlchen.data_import.importers.binance Greenlet-1: Binance import stats: []
DEBUG rotkehlchen.data_import.utils Greenlet-1: Imported 0/1 entries.
```

and he also changed the timestamp format `Yes sorry my bad, using  "%Y-%m-%d %H:%M:%S" produced the same results as default`

## Tasks
1. We need to check the logs, why we don't get information about what is going wrong. We need to have logs about the error
2. Check if our CSV can be imported
3. Contact the user if we can't reproduce the error
4. FInd possible reasons to not have the CSV imported correct

He added
![imagen](https://github.com/user-attachments/assets/ebdea5ae-dc06-4734-b626-829ed82800fc)

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/8817
