### ISSUE TITLE
Can't edit a Bitcoin account

### ISSUE THREAD

**Issue by v-almonacid** [rotki/rotki#8882]
## Problem Definition

When trying to edit a Bitcoin account, the "Choose blockchain" field shows Ethereum and is disabled, so can't be corrected by the user. Trying to edit the account name or its tags, results in an error.

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/b37796d2-df0e-48f5-b7de-55ff2f8f92f3">

## Logs
Haven't checked the logs but the UI error is: `Error while adding account: Blockchain name eth is not allowed in this endpoint`

### System Description

Operating system:  MacOS
Rotki version: 1.36.0

**Comment by yabirgb** [comment]
Thanks for the report! The team is looking at it

**Comment by kelsos** [comment]
Hey @v-almonacid can you provide some more information?

Is the account BTC or BCH? also can you give me the xpub prefix (`xpub`, `zpub` or whatever) along with the value that was chosen on the `Select` field depending the chain?

It seems to work fine with my xpub and normal accounts but there is a high change we are missing something here in the detection and your case falls through.

**Comment by v-almonacid** [comment]
@kelsos sure. It's a BTC account, using a WPKH key. Prefix is `xpub`. FWIW, asset detection works well for that account.

**Comment by kelsos** [comment]
> @kelsos sure. It's a BTC account, using a WPKH key. Prefix is `xpub`. FWIW, asset detection works well for that account.

Hmm @v-almonacid I have also a WPKH xpub and it works fine here. Can you maybe try option+cmd+i this should open the developer tools, and check the console for any errors?

![image](https://github.com/user-attachments/assets/3913d744-7592-4b07-88b3-28b517ec06c0)

If there are any errors there it might help us identify the problem

**Comment by lukicenturi** [comment]
@v-almonacid, does it happen persistently, or did you only see it once?

**Comment by lukicenturi** [comment]
Hi @v-almonacid, I can replicate it. This will be fixed in the next patch release. Thanks for reporting!

**Comment by lukicenturi** [comment]
@v-almonacid While waiting for the patch release, what you can do for now to make it work is set the Etherscan (Ethereum) key.

**Comment by v-almonacid** [comment]
Thank you all for actively looking into it ❤️ 

@lukicenturi can confirm adding an API key fixes the issue, thanks!
