### ISSUE TITLE
Starknet/STRK - Switch crypto compare to the new API

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#8892]
## Am I affected ?

if Rotki shows you any price for the Starknet token (STRK) above ~2.5 €, you need to read below. 

## Problem Definition

The matter was discussed on Discord and the summary is that CC changed the ticker for Starknet from STARK to STRK on 9.5.24.
So query before 9.5.24 for STRK should return values but they have nothing to do with Starknet (and are an order of magnitude higher...). And actually, when using their "Min-API" does not even return any data.

One immediate workaround for users atm is to **disable** cryptocompare from their historical list of oracle.
I tried bumping the oracle down instead but it did not work.

The proper solution, as suggested by CC is:

> Unfortunately, data is updated on our new V2 API (Data-API) and at the moment we do not have a way to update Min-API to reflect the same.
> We recommend that all our users switch to Data-API as it is a newer version of our API and offers a wider range of possibilities.
> You can explore all Data-API endpoints here: 
> https://developers.cryptocompare.com/documentation/data-api/introduction
>  
> Data from before the switch is still available using our CADLI index, as mentioned previously: https://data-api.cryptocompare.com/index/cc/v1/historical/days?market=cadli&instrument=STARK-EUR&limit=100&aggregate=1&fill=true&apply_mapping=true&response_format=JSON&to_ts=1715212800
>  
> Please note that we maintain unique tickers for each asset. When two assets share the same ticker, the more popular asset retains the original ticker, and an alternative is assigned to the other asset. This change was implemented based on multiple enterprise client requests, particularly due to the popularity of the Starknet token.
>

**Comment by LefterisJP** [comment]
Should be handled by #8896 and be part of next release
