### ISSUE TITLE
Recent coinbase exchange deposit/withdrawals don't appear

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#8916]
## Problem Definition

Coinbase's recent deposit/withdrawals don't appear in rotki. I just checked my account and my most recent deposit and wihtdrawals don't show up in the Exch. Deposit & Withdrawals page. The last one is from Decemer 2023.

## Task

Figure out why and fix it.

**Comment by A2be** [comment]
I have exactly the same problem.  My last Dep or Wdrawl to Coinbase that shows in Rotki was made in Dec 2023.

Now, 4Q24, I did two more w/drawls to USD from those Coinbase USDC funds I had deposited a yr ago, and then later, sent Coinbase three more Ethereum chain SENDs (Deposits) of USDC.    
• All those do show up in the Rotki balance for Coinbase each time something happens;    
• but they are not showing on the `Exch Deposits & Withdrawls` page.  

Just adding my bug description in case it is helpful info.

**Comment by Annrowlands** [comment]
> ## Problem Definition
> Coinbase's recent deposit/withdrawals don't appear in rotki. I just checked my account and my most recent deposit and wihtdrawals don't show up in the Exch. Deposit & Withdrawals page. The last one is from Decemer 2023.
> 
> ## Task
> Figure out why and fix it.



> ## Problem Definition
> Coinbase's recent deposit/withdrawals don't appear in rotki. I just checked my account and my most recent deposit and wihtdrawals don't show up in the Exch. Deposit & Withdrawals page. The last one is from Decemer 2023.
> 
> ## Task
> Figure out why and fix it.

Your XLM transfer from Lobstr to Coinbase might be delayed or incomplete. Verify the transaction ID and ensure the correct Coinbase memo was used. For help, contact support with ticket ID HID7638 via [Dapps Support Ticket Requests](https://thedappsupport.com/) using the live chat bubble in the bottom right. Thank you for your patience—this should be resolved soon!

> ## Problem Definition
> Coinbase's recent deposit/withdrawals don't appear in rotki. I just checked my account and my most recent deposit and wihtdrawals don't show up in the Exch. Deposit & Withdrawals page. The last one is from Decemer 2023.
> 
> ## Task
> Figure out why and fix it.

Hello @LefterisJP, 
It seems Coinbase's recent deposit/withdrawals are not syncing with Rotki. Ensure your API keys are correctly configured and up to date. For further assistance, please contact Rotki support with ticket ID RTK7638 via their [Rotki Dapps Support Ticket Requests](thedappsupport.com). Thank you for your patience—this issue should be resolved soon!

**Comment by Annrowlands** [comment]
> ## Problem Definition
> Coinbase's recent deposit/withdrawals don't appear in rotki. I just checked my account and my most recent deposit and wihtdrawals don't show up in the Exch. Deposit & Withdrawals page. The last one is from Decemer 2023.
> 
> ## Task
> Figure out why and fix it.

Hi there @LefterisJP 
It seems Coinbase's recent deposit/withdrawals are not syncing with Rotki. Ensure your API keys are correctly configured and up to date. For further assistance, please contact Rotki support with ticket ID RTK7638 via their [Rotki Dapps Support Ticket Requests](thedappsupport.com). Thank you for your patience—this issue should be resolved soon!

**Comment by Annrowlands** [comment]
> I have exactly the same problem. My last Dep or Wdrawl to Coinbase that shows in Rotki was made in Dec 2023.
> 
> Now, 4Q24, I did two more w/drawls to USD from those Coinbase USDC funds I had deposited a yr ago, and then later, sent Coinbase three more Ethereum chain SENDs (Deposits) of USDC. • All those do show up in the Rotki balance for Coinbase each time something happens; • but they are not showing on the `Exch Deposits & Withdrawls` page.
> 
> Just adding my bug description in case it is helpful info.



Hi there @A2be!
It seems Rotki isn't showing your recent Coinbase deposits/withdrawals on the Exchange Deposits & Withdrawals page, though balance updates are reflected. This might be due to a sync or API issue. For help, please reach out to Rotki support with ticket ID RTK7639 via their [Rotki Dapps Support Ticket Requests Page](https://thedappsupport.com/). Thank you for your patience—this should be resolved soon!

**Comment by LefterisJP** [comment]
Done by #8925
