### ISSUE TITLE
semi-private view mode doesn't work

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#8927]
## Problem Definition

When I switch between private and semi-private viewing modes:

![image](https://github.com/user-attachments/assets/dad060ce-20f5-4b2c-b5cd-ea97a048348e)

there is no visible difference in the UI - everything remains blurred.

## Logs

Not sure they're needed but can provide if so.

### System Description

Operating system: openSUSE Tumbleweed
Rotki version: 1.36.0

**Comment by kelsos** [comment]
- We need to reward the semi-private to make clear that amounts will be blurred but percentages will not be.

**Comment by aspiers** [comment]
I think the existing wording is good, it just creates too high expectations about existing functionality.  But #8929 will fix that.
