### ISSUE TITLE
blank tooltip in private mode

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#8990]
## Problem Definition

In private or semi-private mode, when I go to `Accounts & Balances / Blockchain Balances`, expand ETH, and hover the mouse over one of the asset icons in the expanded table (i.e. ETH or WETH icons), it shows 

1. a blank grey tooltip
2. a separate white-on-black tooltip saying "Blockchain Balances per asset" (now tracked separately in #8992)

![image](https://github.com/user-attachments/assets/a2557128-a924-435c-98ce-ad0490a8be2b)

Clearly neither of these are useful, and I don't think either should appear.  To avoid overlap between issues, this issue could focus on the former, whereas #8992 covers the latter.

## Logs

Available on request if needed

### System Description

Operating system: openSUSE Tumbleweed Linux
Rotki version: v1.36.1 AppImage

**Comment by lukicenturi** [comment]
A blank grey tooltip appear because you activated the private mode.

**Comment by aspiers** [comment]
[**@Luki Centuri**](https://github.com/lukicenturi) commented on [December 2, 2024 6:10 AM](https://github.com/rotki/rotki/issues/8990#issuecomment-2510659987 "Mon Dec 02 2024 06:10:04 GMT+0000 - Replied by Github Reply Comments"):
> A blank grey tooltip appears because you activated the private mode (It supposed to show the amount)

Yes, I realise that (hence the issue description containing "in private mode").

> Do you think that anything under tooltip shouldn't be blurred?

No, as I wrote above I think the tooltip shouldn't be shown at all.  Showing a tooltip which contains no useful info is both redundant and confusing for users.
