### ISSUE TITLE
mouseover asset icons shows confusing tooltips

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#8992]
## Problem Definition

In `Accounts & Balances / Blockchain Balances`, if I mouse over the ETH icon, I see this:

![image](https://github.com/user-attachments/assets/f4dfb14b-3853-4c9a-852a-d616161ad71f)

There are two problems here:

1. One tooltip repeats "ETH" three times, which makes no real sense to the user.  Even if it showed "ETH" just once, this would not be telling the user anything helpful since they can already see the ETH icon.
2. Another tooltip says "Blockchain Balances per asset", which also seems more confusing than helpful.  (Also mentioned in #8990).

If we mouse over a different asset, it becomes clearer why ETH is repeated three times:

![image](https://github.com/user-attachments/assets/4ee5bb99-a933-4360-944f-4276bf03af29)

So presumably one is the ticker symbol, one is a human-readable description, and I guess the third one is the onchain identifier? i.e. either the token's smart contract address or in the case of the chain's native coin, just the symbol again.  But the code which generates this tooltip should only generate information which is

1. useful
2. additional on top of what the user already knows

So it seems this needs a bit of a rethink.

## Logs

Available on request but presumably not necessary as easy to reproduce.

### System Description

Operating system: openSUSE Tumbleweed Linux
Rotki version: v1.36.1 AppImage

**Comment by aspiers** [comment]
I traced this `title` attribute all the way back to 2019:

https://github.com/rotki/rotki/commit/bf968ed788aba#diff-4ecba2a6e01bbc90865ffe6ffe70b9531e2ca61f462c53cf0de66753cb36dd91R27

@kelsos Perhaps you can comment on whether there's still a reason to keep it?

**Comment by kelsos** [comment]
> I traced this `title` attribute all the way back to 2019:
> 
> [bf968ed788aba#diff-4ecba2a6e01bbc90865ffe6ffe70b9531e2ca61f462c53cf0de66753cb36dd91R27](https://github.com/rotki/rotki/commit/bf968ed788aba#diff-4ecba2a6e01bbc90865ffe6ffe70b9531e2ca61f462c53cf0de66753cb36dd91R27)
> 
> @kelsos Perhaps you can comment on whether there's still a reason to keep it?

I would say probably not, that commit seems to be part of the migration from JQuery to Vue. So my guess is that I just moved it over from the previous implementation.

**Comment by aspiers** [comment]
[**@kelsos**](https://github.com/kelsos) commented on [Dec 3, 2024, 9:15 AM GMT](https://github.com/rotki/rotki/issues/8992#issuecomment-2513956723 "2024-12-03T09:15:58Z - Replied by Github Reply Comments"):
> I guess with the fix in this is closed now right?

No, my fix was only for the second item.

**Comment by kelsos** [comment]
OK I see. I guess the same approach we have with the rest {symbol, name, address/identifier} doesn't make sense with ETH.
