### ISSUE TITLE
Credit Card Tax Settings

### ISSUE THREAD

**Issue by vincenttaglia** [rotki/rotki#9007]
## Abstract

Related to #9006, if Gemini's credit card rewards are supported, the next problem is that credit card rewards have a special tax status in the US and don't accrue income taxes. It would be great to be able to set that in your tax settings.

## Motivation

It would be great to have the cost basis of my credit card rewards tracked by Rotki. The difference is starting to add up after a few years of using the credit card.

## Specification

This will likely require a new receive sub-event type for credit card rewards as well as a setting for credit card reward taxes in the tax configuration.

**Comment by LefterisJP** [comment]
Hey Vincent, so you want to be able to customize a rule for credit card rewards. What do you mean by credit card rewards though? Cashback/payback? 

Because we already have this subtype: `HistoryEventSubType.CASHBACK` which we use for example for Gnosis Pay cashback. Would that work?

**Comment by LefterisJP** [comment]
Closing due to lack of an answer
