### ISSUE TITLE
Export all assets including current price, amount and value from rotki dashboard to a csv

### ISSUE THREAD

**Issue by flighter18** [rotki/rotki#9021]
## Abstract

Currently, the Rotki dashboard provides a detailed view of all assets, including their current price, amount, and $ value. However, there is no direct option to export this information to a CSV file. Users who wish to analyze or manage their data outside Rotki, such as in spreadsheet tools, must manually copy the information, which is time-consuming and prone to errors.

## Motivation

Providing a feature to export asset data to a CSV file will add significant value to users by:

- Allowing them to easily analyze, or share their asset data.
- Saving time and reducing manual errors in data transcription.
- Enhancing the overall usability of Rotki for professional and personal asset management.

## Specification

**Export Button:**

Add an "Export to CSV" button on the dashboard, ideally placed near the existing search bar or at the top-right of the assets table.

**Data Fields:**

The exported CSV should include the following fields for each asset:
Asset Name
Symbol
Current Price (in CHF or selected base currency)
Amount
Total Value (in CHF or selected base currency)
Percentage of Net Value

**File Format:**

The export should produce a CSV file with the first row as a header.

**Comment by LefterisJP** [comment]
Hey @flighter18 thanks for taking the time to open an issue!

You can export a snapshot balance. Which is exactly what you are asking. You can also force a balance snapshot to create a snapshot of current balance.

Read here:
https://docs.rotki.com/usage-guides/accounts-and-balances.html#snapshots

That should probably solve your issue. If not let us know here or in discord: https://discord.rotki.com/
