### ISSUE TITLE
UI: If number of zeros after decimal >= shown decimal points let the user know

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#908]
## Abstract

Using the default 2 decimals points rendered for any asset if a user has something like `0.00085810 ETH` the UI will render like seen below:

![2020-04-21-124050_1012x150_scrot](https://user-images.githubusercontent.com/1658405/79856970-5d980680-83cd-11ea-87db-29a5ded562f8.png)

At first look, if the user does not even know they have `0.00085810 ETH` somewhere this will look like some kind of bug with rounding. `0 ETH` having a value of `0.15$`.

We need to avoid this kind of scenario and make it obvious to the user that the actual amount is not zero. Same thing with all other numbers. Not only amounts, but also value columns.

## Task

Find a nice way in the UI to show to the user the actual number is not 0. I am not sure what is the best way, from a UX perspective and also what is easy to implement.

Some thoughts below. If number is not zero and if number of zeros after decimal >= shown decimal points:

1. Show at least up to the first non-zero digit
2. Add an * next to the amount and make it hover-able. If the user hovers over it then he sees the full amount.

## Misc comments

From the above I prefer (2) but not sure how feasible it is. Are there any other ways to do it that would be nice from a UX point of view?

**Comment by isidorosp** [comment]
I also like (2) more. I think it's feasible to do it from a UI point of view (I remember we had a similar discussion about also possibly showing more decimal points when displaying certain types of values such as accrued interest). We're already using tooltip functionality in some UI elements like the trashcan icon for deleting assets.

**Comment by kelsos** [comment]
I think a tooltip showing the full amount would be the best approach.
Also it would be good to extract this as a component and use it at every place.

**Comment by LefterisJP** [comment]
@kelsos Great. Do you think it's easy? Should we schedule it for v1.5.0?

**Comment by kelsos** [comment]
> @kelsos Great. Do you think it's easy? Should we schedule it for v1.5.0?
yes and yes :)
