### ISSUE TITLE
Optimism 0x swap with amount returned not seen correctly

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#9122]
## Problem Definition

There is an extra receival of OP, perhaps some kind of return of remaining from the swap?

https://optimistic.etherscan.io/tx/0x0745615163e01c8a446f2520d5fa008dd69f308f24bcc3d2fec2466c1a2bc25c

![2024-12-20_12-07](https://github.com/user-attachments/assets/2edb8104-076e-4c89-a291-bfef4ce3ab4a)

Reminder to self: Fix/adjust the customized event once it's fixed in production rotki.

## TODO

Fix it, use the transaction hash as a test.

The fix would be to make it so that if there is a return, disregard the return event and reduce the original amount by the returned amount. Looking like this basically

![2024-12-20_12-11](https://github.com/user-attachments/assets/41e30df8-0d32-420c-ac82-fd07a29a1000)

The reason for this is for easier accounting and cost basic.

**Comment by yabirgb** [comment]
Fixed in 9134
