### ISSUE TITLE
As long as "All balances" may still change add strobing effect in Dashboard's All Balances table

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#913]
## Abstract

Many times when opening Rotki app the dashboard loads fast with all the exchange balances. The blockchain balances tend to take more time to be queried and added into the "All Balances" table of the dashboard which may lead to confusion for users.

## Task

Solve the above by adding a strobing effect in the "All balances" dashboard table as long as any query that may still affect it is active.

**Comment by isidorosp** [comment]
This should be addressed by #976, as the "all balances" dashboard component has been updated to display a loading indicator whenever either Exchanges or Blockchain Balances tasks are running.

**Comment by isidorosp** [comment]
@LefterisJP can you confirm that this addressed as per your expectations in the New Dashboard UI PR? If so we I close and mark as done in the release.

**Comment by LefterisJP** [comment]
Yes it's definitely addressed. Thanks!
