### ISSUE TITLE
Refresh some master data from the backend periodically

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#916]
## Motivation

Because users do not always close/re-open their apps, certain backend data should be refreshed periodically. 

## Specification

Let's make a list of data that is grabbed from the backend that needs to be refreshed periodically:

- [x] Currency Exchange Rates (every 30 mins / 1 hr?)
- [x] Blockchain Balances
- [x] Exchange balances 
- [ ] Trades

**Comment by LefterisJP** [comment]
I guess the balance queries should also be redone at some point. But not too often as they are expensive and take a lot of time (blockchain ones especially).

@kelsos is there anything else?

**Comment by kelsos** [comment]
Do you poll the data periodically in the backend? or does this need to be called by the frontend? 
For a lot of them we already have refresh buttons, but not for the dashboard so the user can theoretically do it manually. But I am not opposed to adding an option for an automatic refresh every 30m/1h/2h intervals. I would say blockchain and exchange makes sense.

**Comment by LefterisJP** [comment]
The data is not polled periodically (yet) in the backend. If we need them we will add that.

But if requested from the frontend they would be renewed.

**Comment by kelsos** [comment]
I was thinking mostly about if you do the polling in the backend and we add WebSockets you can also notify the frontend for changes. But that depends on if there is any need to add the polling in the backend instead.

**Comment by LefterisJP** [comment]
We should actually implement this. Had a discussion with a user who reminded me of this issue and that it's missing. Need to think a bit more on implementation details, but putting it in a milestone.

End result should be:

Automatic updates of at least:

price data every X mins.
balances every Y mins.

Needs thinking on how this should happen in the backend but it's a must have for a portfolio tracker.
