### ISSUE TITLE
Add support for all the Aave v3 markets in Ethereum mainnet

### ISSUE THREAD

**Issue by gianluca-pub-dev** [rotki/rotki#9160]
## Abstract

Recently Aave introduced multiple separate markets in Ethereum mainnet:
https://aave.com/docs/resources/addresses
![immagine](https://github.com/user-attachments/assets/b631dd9c-fcde-416e-ac93-b27a6679e6d8)

## Motivation

Currently Rotki supports only the original Aave-v3 market on Ethereum L1 network, that now was renamed as "Ethereum V3 Core Market"
## Specification

Support the additional markets on Ethereum L1 network. Currently: Ethereum V3 Prime and Ethereum V3 EtherFi.

**Comment by yabirgb** [comment]
Done in https://github.com/rotki/rotki/pull/9158 and confirmed that it works.
