### ISSUE TITLE
Dashboard Improvements (overall balances, etc.)

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#917]
## Abstract

Dashboard could be a little more "dashboard-y".

## Motivation

Let's arrange and present data in order to give users a better "at a glance" information on their portfolio. 

## Specification

- We should have an "overall balances" section that displays the user's total net worth prominently along with some interesting statistics (change over time perhaps). More detailed statistics are available in Premium and we should link to that.
- We can try to think of what accompanying graphics we can provide that would increase user value but not detract from the premium offerings.
- overall balances elements would need a clear loading indicator like all assets to reduce user confusion while blockchain balances are being queried (as they are quite slow compared to other queries)
- Let's think about how it best makes sense to break up the sections and what makes sense to be grouped together

**Comment by LefterisJP** [comment]
Hey @isidorosp thanks for the issue!

As discussed in the discord chat let's keep this issue open up for discussion for some of the parts but also consider it as definitely needing the "total net value balance in Bold" in the top of the dashboard. And maybe the graph tease but @kelsos would need to chime in there.

**Comment by kelsos** [comment]
I would like to add some simple graphs in the open-source version, we need to discuss what would make sense and would be good to know. But I agree we need to update the structure and layout :)

**Comment by LefterisJP** [comment]
For start the total netvalue in the past week would make sense? So a limited version of the full time range?
