### ISSUE TITLE
Add watcher service for Premium users who maintain MakerVaults

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#918]
## Abstract

Depends on https://github.com/rotki/rotki/issues/707

Once we support MakerVaults we can offer real value to our premium users by helping protect them from liquidations.

The premium users will be able to mark each Vault for watching and the corresponding collateralization ratio to watch for. If the collateralization ratio falls below that then they will get an email to the email address they registered premium with warning them to take action.

## Privacy Guarantees

The automated watching system will happen in our own Rotki server so there may be privacy concerns. For each Vault that is marked as watching, an entry of the Vault's  id will be made in the server's DB and associated with the user's email.

There is no way around this if the user wants to opt-in for automatic watching (it's going to be off by default). But we guarantee that when the user stops watching a vault then the corresponding mapping is also deleted from our server.

### Backend

The backend would query the Rotki server for premium users watching info. We would expose the queried information allow editing of watching info via some API endpoints

#### API Endpoints

Provide the following API endpoints. They would only be usable by users with an active premium key.

##### GET /api/1/watchers

This should return all active watchers for the account of the user. The format of the response should be as follows:

```json
{
    "result": [{
            "identifier": "323213",
            "type": "makervault_collateralization_ratio",
            "args": {"ratio": "200.5", "op": "gt", "vault_id": 24}
            }, {
             "identifier: "asdsa23",
             "type": "makervault_collateralization_ratio",
             "args": {"ratio": "185.55", "op": "lt","vault_id": 456}
             }]
},
    "message": ""
}
```

##### DELETE /api/1/watchers

Argument would be a list of unique watcher identifiers to delete.

```json
{
"watchers" :["dsa982", "7jhajsk9"],
}

Response will be the list of all watchers, excluding the ones that were deleted
```json
{
    "result": :[],
    "message": ""
}
```

##### PUT /api/1/watchers

Argument would be a list of new watchers to add.

```json
{
"watchers" :[{
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "200.5", "op": "gt", "vault_id": 24}
    }, {
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "175.15", "op": "le", "vault_id": 842}
}]
}

Response will be the list of all watchers, including the ones that were added

```json
{
    "result": :[{
    "identifier": "jksa892",
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "200.5", "op": "gt", "vault_id": 24}
    }, {
    "identifier": "dsj3298djk",
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "175.15", "op": "le", "vault_id": 842}
}],
    "message": ""
}
```

```

#### PATCH /api/1/watchers/

Argument would be a list of watchers to edit.

```json
{
"watchers": [{
    "identifier": "as659",
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "200.5", "op": "gt", "vault_id": 24}
     }, {
    "identifier": "asjd39802",
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "175.15", "op": "le", "vault_id": 842}
}]
}
```

Response would be the list of all watchers including the edited watchers

```json
{
"result": [{
    "identifier": "as659",
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "200.5", "op": "gt", "vault_id": 24}
     }, {
    "identifier": "asjd39802",
    "type":  "makervault_collateralization_ratio",
    "args": {"ratio": "175.15", "op": "le", "vault_id": 842}
}],
    "message": ""
}
```

### Rotki Server

Implement the premium API endpoint which will mirror the above calls and add the watching to the DB. In the recurring task every 5 mins query status of each watched vaults and get the current collateralization ratio. If it's equal or below the provided ratio send an email to the user and consider the watching complete.

But keep watching. If the collateralization ratio increases again above a certain percentage consider the watching as resumed.

### Frontend

Add a UI component for each Maker Vault. Somewhere visible. It should exist for both premium and non-premium users. But for non-premium it should be locked and direct users to buy premium for it.

I am not sure how it should look but it should just be a simple component that:
- Allows watching for that vault turned on/off
- Has some input component, perhaps a text field?, that allows the user to specify the collateralization ratio at which to send the email. Valid value should be from 155% and up. Vaults get liquidated below 150%.

**Comment by isidorosp** [comment]
I can pick up implementing this very basically in the UI since I'm already doing changes to the Lending components if @kelsos can then grab it to finish it off in terms of integrating with the UI and finalizing.

**Comment by LefterisJP** [comment]
Hey @isidorosp that would be awesome! The web site part is progressing nicely. Already done in the website repo with tests included. Now only need to expose it in the premium API.
