### ISSUE TITLE
Utilize Zerion DeFi SDK

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#921]
## Abstract

Thanks a lot to @isidorosp for bringing the Zerion SDK to our attention!

Integrating each new DeFi protocol with Rotki is time consuming. There are many facets to such integration. UI components, backend work and naturally ethereum chain querying.

Zerio has an opensource SDK for querying multiple DeFi protocols with fewer RPC calls.

- https://blog.zerion.io/defi-sdk-making-money-lego-work-1dc08b8982cf
- https://github.com/zeriontech/defi-sdk

They have deployed verified smart contracts to the ethereum mainnet that aggregate queries to different DeFi protocols and return results all in one (or just fewer calls).

This would be useful for Rotki since it would greatly reduce the number of RPC calls made for ethereum DeFi querying. And that is really important, especially if the user does not have his own node and relies on external services such as etherscan for those queries.

They have a javascript SDK, but we would need a python wrapper, which we can create ourselves if it does not exist.

## Task

- Figure out if there is a python wrapper. If not write it ourselves.
- Adapt MakerDAO DSR calls (if supported to use it)
- Use it in MakerDAO Vault calls
- As more DeFi protocols are added utilize the aggregator instead of querying each protocol individually.

**Comment by rockfridrich** [comment]
Hey @LefterisJP 
I am happy that your team finds our SDK useful for your product. We don’t have JS & Python libraries yet. However you can query [AdaterRegistry](https://etherscan.io/address/0x06fe76b2f432fdfecaef1a7d4f6c3d41b5861672) (api.zerion.eth ENS) smart contract directly using web3.py and [ABI](http://api.etherscan.io/api?module=contract&action=getabi&address=0x06fe76b2f432fdfecaef1a7d4f6c3d41b5861672&format=raw) published on Etherscan.

**Comment by rockfridrich** [comment]
We released a simple wrapper for Python — https://pypi.org/project/defisdk/

**Comment by LefterisJP** [comment]
Hey @rockfridrich any news on when can the python adapter be opensource?

We can't use a closed source package.

But as you said we can call the adapter registry directly which is going to work for some things. We can experiment with it for now.
