### ISSUE TITLE
"Manually Tracked Balance" doesn't sum on the grand total at the dashboard

### ISSUE THREAD

**Issue by mrkimchi** [rotki/rotki#923]
## Problem Definition
I added Cosmos tokens as an external balance. But it's not added at the grand total.

**Comment by LefterisJP** [comment]
Hey @mrkimchi, let me see if I understand the problem.

1. You added Cosmos token as manually tracked balance
2. After adding it it did not appear in the "All balances" table in the dashboard ?

**Comment by mrkimchi** [comment]
Sorry for late response. It works! I see the total now. Thanks.
