### ISSUE TITLE
create account UI is not completely shown if the user has high % size of text

### ISSUE THREAD

**Issue by synagonism** [rotki/rotki#928]
# Problem Definition

I can not see create buttons.

### System Description

rotki 1.4.1, windows 10

![rotki141](https://user-images.githubusercontent.com/4649364/80287713-8147ad80-873b-11ea-8b9f-54f6e05a198a.jpg)

**Comment by isidorosp** [comment]
Can you resize the window to make it bigger?

**Comment by synagonism** [comment]
this happens on a maximized window.

**Comment by isidorosp** [comment]
Try to zoom out (in the View menu or CTRL -)

**Comment by kelsos** [comment]
@synagonism can you confirm the resolution of the window in your case? at 800x600 resolution without any zoom, the message should not cover the buttons. Is it safe to assume that you are using a laptop with a 15.6" monitor that has a `1366 x 768` resolution?

**Comment by synagonism** [comment]
my resolution is 1920x1080 in a 27" monitor.

BUT I am an old man guys and I have "the size of texts, apps"=175% and this
is the problem I think.

also zoom-out works.

But it is good the-app to work on my extreme case!

thanks konstantinos!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by isidorosp** [comment]
@kelsos just in case to avoid this I guess we can make the popups in modals have a higher z-order value than anything else?

**Comment by kelsos** [comment]
We just need to move the z-index of this message a bit lower than the one used by modals. And make sure we don't add anything with higher z-index. This should be fine. @synagonism thank you for the information.

**Comment by LefterisJP** [comment]
Thank you for the nice bug report @synagonism!

We will schedule this fix in the upcoming v1.4.2 release.
