### ISSUE TITLE
Introduce configurable rounding for amounts displayed on the UI

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#929]
## Abstract

Currently, all the amounts displayed in the UI use rounding. More specifically it uses [`BigNumber.ROUND_HALF_UP`](https://mikemcl.github.io/bignumber.js/#round-half-up) which is BigNumber.js's default mode. 

It would be desirable to provide an option so the users can select the preferred rounding mode.

**Comment by LefterisJP** [comment]
Any plan to include this at any point @kelsos? Not sure how hard it would be. Not really needed. But maybe one of those very very low priority nice to haves?

**Comment by kelsos** [comment]
@LefterisJP Let's put it for 1.16
