### ISSUE TITLE
Browsing to certain pages alters the look of certain app UI elements

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#939]
## Problem Definition

Browsing to certain pages in Rotki (Statistics, Defi) causes some of the app CSS rules to be corrupted. The navbar turns white and the currency selector changes size.

Example:
![image](https://user-images.githubusercontent.com/27592/80352870-ce7b6a80-8874-11ea-97e2-9cff9ce5cbd9.png)

![image](https://user-images.githubusercontent.com/27592/80352887-d5a27880-8874-11ea-9a78-425557af3c39.png)

**Comment by kelsos** [comment]
I am looking into that in the premium components. It seems that some rules that are embedded in the premium components overwrite the app rules.

**Comment by LefterisJP** [comment]
I am probably color blind and can't judge if this is fixed or not. Can you guys tell me if it is? If not we are pushing further. In which case you think it can be in next patch release v1.5.1 (very soon?) or v1.6.0 (soon) ?

**Comment by kelsos** [comment]
It is there, yes let's move it to 1.5.1

**Comment by LefterisJP** [comment]
Pushing this one again. If it's not something you guys can do or if you no longer care about it please close the issue.

**Comment by kelsos** [comment]
it is a bit tricky to fix. basically we need a way to namespace the css on the premium components so that it does not overwrite the theme on the app.

**Comment by LefterisJP** [comment]
Please just schedule it when you can handle it then. I don't consider this a necessity. If you recall I did not notice it until you pointed it out :stuck_out_tongue:

**Comment by kelsos** [comment]
Sure, I have a few hacky ideas I want to try :P

**Comment by kelsos** [comment]
With the v0.3.0 of the premium components, this seems to be solved. Before the bordered v-cards would change to having shadow as soon as the premium components where loaded. This doesn't seem to be the case anymore.
