### ISSUE TITLE
Blockchain per account balances total is not bold during the first load

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#952]
## Problem Definition

It seems that during the first loading of the blockchain accounts for some weird reason the CSS for the Total row doesn' t load properly. If you navigate back and forth of the Accounts page the CSS will load properly and the Total will be properly bold.

**Comment by LefterisJP** [comment]
@kelsos @isidorosp Is this still a problem? I actually can't see it when navigating to the blockchain balances for the first time. The total is properly bold.

If it's not a problem we can close this.

**Comment by isidorosp** [comment]
I can't reproduce on current develop either.

**Comment by LefterisJP** [comment]
All right so we close. Great to see issues closing :smile:

**Comment by kelsos** [comment]
> All right so we close. Great to see issues closing smile

It is always fun when you accidentally fix issues :P
