### ISSUE TITLE
Deduct VAT on premium subscription

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#977]
Figured a GitHub issue is as good a way as any to ask for this.

## Abstract

It currently isn't possible to remove the VAT from the invoice for Rotki Premium. I would like it if I could give my VAT number and pay the invoice without VAT.

## Motivation

I use Rotki in my company. For some reason, I'm told Estonian regulation doesn't allow you to just get your outstanding VAT back at the end of the year. Instead, I need to get it taken off the invoices directly.

## Specification

I'm no regulation expert, but it may be possible to just trust the buyer, accept their given VAT number, and not add VAT to the invoice, so it's the buyer's duty to make sure that what they are doing is alright. If it is necessary to validate the VAT number, the official service for that in the EU is https://ec.europa.eu/taxation_customs/vies/ 
There is also a nicer service for which I can see an API: https://www.vatcheck.eu/en/check-vat-number

**Comment by LefterisJP** [comment]
Hey @hjorthjort thanks for the issue!

That is true. There exists a posibility to accept a VAT number and if it is valid, do what is known as a VAT backcharge.

But as you said we would need to verify that the provided VAT number is correct. The API you mentioned was not very trustworthy when I made the shop for Rotki's subscriptions. Also the current checkout/shop logic would need changes.

I don't think we can handle this issue right now. In the future when Rotki grows probably yes. But now it's a lot of extra hassle, extra work and risk for Rotki. If we do a VAT backcharge for a company that we mis-verified we would need to cover the VAT costs ourselves, and even pay a fine.

With the current number of subscribers it's not worth the hassle.

> For some reason, I'm told Estonian regulation doesn't allow you to just get your outstanding VAT back at the end of the year. Instead, I need to get it taken off the invoices directly.

 Plus it should **always** be possible to get the VAT back if you own a company. I would try to clarify this with the Estonian tax authority. The whole point of VAT is that at the end of the year as a company you do a VAT declaration of your expenses and income and either they wire you back the difference or you wire it to them, depending on expenses/income with VAT.

---

That said I will leave the issue open as a reminder (and make a corresponding one to our private website repo) to handle it when it does make sense.

**Comment by hjorthjort** [comment]
I figured that was the case, but I still wanted to register the feature request, in case someone else agrees.

I thought it was weird that I couldn't get it back, too, since that's standard practice as far as I know. I dug deeper and it turns out what they (my Estonian bookkeeper) meant was that the VAT number **needs to be on the invoice** for the company to be able to get the VAT back. It does not need to be backcharged.

So, would that be possible? Or would you still need to verify the VAT number?

**Comment by LefterisJP** [comment]
> meant was that the VAT number needs to be on the invoice for the company to be able to get the VAT back

@hjorthjort  Naturally! That's a nice find. I thought we were including the VAT in our invoices. This is a must-have.

> So, would that be possible? Or would you still need to verify the VAT number?

Let me do that right now. Will ping you when it's done.

**Comment by LefterisJP** [comment]
@hjorthjort It's done.

 I think you can get the amended invoice by going to your control panel in the website and downloading it from there. If it does not work I can also just email it to you, or ping you in discord. Just let me know. And thanks a lot for pointing the missing VAT ID.

**Comment by hjorthjort** [comment]
Slight misunderstanding. I need to have *my* VAT number and company address on the receipt.

**Comment by LefterisJP** [comment]
@hjorthjort I see. That is going to be a bit more complicated. But probably doable. Give me more time for this. I will ping here when I think of or implement something.

**Comment by hjorthjort** [comment]
How are the PDFs generated? I was thinking about just putting my VAT number in the "Address 2" field as a hack. Is there anything stopping just adding another line under the recipient, the same way you just added your VAT number under the sender?

**Comment by LefterisJP** [comment]
That would work but look hacky. It would include your VAT ID as the extended address. Here is the django template:

```django
<td>
    {% if customer_company %}
    {{ customer_company }}<br>
    {% endif %}
    {% if customer_fullname %}
    {{ customer_fullname }}<br>
    {% endif %}
    {% if customer_address %}
    {{ customer_address }}<br>
    {% endif %}
    {% if customer_extended_address %}
    {{ customer_extended_address }}<br>
    {% endif %}
    {% if customer_postal_code %}
    {{ customer_postal_code }}<br>
    {% endif %}
    {% if customer_country %}
    {{ customer_country }}<br>
    {% endif %}
</td>
```

But the real solution would be to allow users to also input a VAT ID in their DB. Probably we would have to evaluate that ID. As printing an invoice with a fake VAT ID is not ideal.

Even though no backcharging happens and all responsibility is with the customer here.

Let me think a bit.

**Comment by hjorthjort** [comment]
Not sure what about the legal implications, but in many orgs it's nice if invoices can contain some extra information, like a payment reference or similar. So a free-text field may be a more general and nice solution.

**Comment by hjorthjort** [comment]
It wouldn't need to be stored in the DB indefinitely either, necessarily, it could be added to the invoice directly with a separate field. That makes for an ugly UI, though.

Either way, nothing is stopping me from putting any data at all into most of the fields. Like, I could put your info as the payer, or the data of another company, etc. I find it hard to believe that would put you on the hook. But you know, #notlegaladvice.

**Comment by LefterisJP** [comment]
Yeah that is true. I have checked that with our accountant that verifying that someone's address or name is correct e.t.c. is not really possible or needed. For the amounts we are dealing with.
For much bigger amounts that would be adviced but still no real way to enforce. Business are not required to do KYC. Thank god.

I think adding it as an optional field in the user for now may be a good solution. Would that be satisfactory for you?

>  in many orgs it's nice if invoices can contain some extra information

Interesting. I have never seen that

**Comment by hjorthjort** [comment]
> I think adding it as an optional field in the user for now may be a good solution. Would that be satisfactory for you?

Sounds good.

**Comment by LefterisJP** [comment]
@hjorthjort It should now be done

You should now be able to log in to your account and where you edit your address details add a VAT ID.

IF you regenerate the invoice it should now be included there.

Tell me if that works for you and if it's sufficient to close the issue.

**Comment by hjorthjort** [comment]
It works, thanks!

Nit: some of the hints under the fields are missing a final ".". Like:
"Required. Will only be used for invoice of payments."And the second field uses ":" instead of ".", like:
"Optional: Provide Github username for in-Github support"

**Comment by LefterisJP** [comment]
@hjorthjort thank you for getting a premium subscription!

Anything else you need we are here. Also in discord as you know. 

As for the nitpicks, heh. Good eye. Will address them :smiley:
