### ISSUE TITLE
Monitor ENS domain names for renewal and warn user if they are about to expire

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#982]
## Abstract

This depends on the ENS support issue: https://github.com/rotki/rotki/issues/530

Once a user registers an ENS name he will also need to renew it at some point. If the user does not renew it within the grace period they lose it.

Having a service for users to be notified when one of their ENS domains is about to expire would be really lifesaving in such a case.

## Task

For premium users allow them to monitor up to a certain number of ENS addresses for expiration. If any address is close to expiring they will be notified by email.

**Comment by emansipater** [comment]
Strongly in support of this feature, and more support for tracking ENS events in general (purchases, sales, renewals, etc.)

**Comment by LefterisJP** [comment]
I consider this closed thanks to the calendar reminders that went into rotki in 1.33.0. They do exactly that for ENS names and more.
