### ISSUE TITLE
Settings should be consolidated in the frontend

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#988]
## Abstract & Motivation

Settings are currently split (General Settings, Accounting Settings). They should be consolidated into one page and logically grouped (e.g. using tabs). This will enhance user experience by consolidating similar information and minimizing the number of clicks needed to reach related information and functionality in the application.

## Specification

* Each specific tab should work organically within the app and be treated as a separate page. For example, using the back/forward functionality of the app (e.g. with mouse buttons) should work as expected
* Settings should be logically grouped (e.g. move the "change user password" functionality from "General Settings" to "User & Security". 
* Total tabs should be kept to a reasonable maximum taking into account UI considerations (i.e. 3-4 tabs maximum so that they all fit horizontally).
* In the future, additions to settings can then be appropriately categorized or sub-grouped (e.g. another laying of groupings within each tab).

**Comment by isidorosp** [comment]
TBD if this goes in 1.5.0 or 1.6.0

**Comment by LefterisJP** [comment]
if it can be done by v1.5.0 I don't see why it should not go in there, right?

**Comment by LefterisJP** [comment]
Talking about frontend only.

**Comment by isidorosp** [comment]
> if it can be done by v1.5.0 I don't see why it should not go in there, right?

Sure! Just don't necessarily want to commit to a milestone before checking with you guys as I know you have in mind what we want done by 1.5.0 and reviewing this might take time from kelsos to focus on that.

**Comment by kelsos** [comment]
@isidorosp 1.5.0 sounds good. And the proposal seems good :+1:
