### ISSUE TITLE
Bug Import CSV cointracking

### ISSUE THREAD

**Issue by vchatela** [rotki/rotki#995]
Dear,
I have exported my cointracking CSV and tried to import it.
For every line I have : 
`Error during cointracking CSV import deserialization. Error was Failed to deserialize a timestamp from a null entry in cointracking.info. Ignoring entry`

I have used v1.4.2 (and also tried on v1.4.1).
Thank you
Valentin

**Comment by vchatela** [comment]
[rotkehlchen.log](https://github.com/rotki/rotki/files/4627768/rotkehlchen.log)

Exported CSV : 
`"Type","Buy","Cur.","Sell","Cur.","Fee","Cur.","Exchange","Group","Comment","Date"
"Trade","3300.00000000","CRO","197.01000000","EUR","","","Crypto.com","","EUR -> CRO","2020-05-14 11:46:20"
"Deposit","197.01000000","EUR","","","","","Crypto.com","","EUR Deposit (Via SEPA)","2020-05-14 11:44:20"
"Trade","4784.80000000","CRO","286.57000000","EUR","","","Crypto.com","","EUR -> CRO","2020-05-14 10:54:20"
"Trade","0.00120200","BTC","80.00000000","CRO","","","Crypto.com","","Syndicate 50% BTC","2020-05-14 10:44:20"
"Trade","2000.00000000","CRO","117.54000000","EUR","","","Crypto.com","","EUR->CRO","2020-05-11 21:58:34"
"Deposit","117.54000000","EUR","","","","","Crypto.com","","EUR Deposit (Via SEPA)","2020-05-11 21:06:27"
"Trade","197.17000000","EUR","0.02300000","BTC","","","Crypto.com","","BTC -> EUR","2020-05-06 23:32:11"
"Trade","89.40000000","EUR","18.51000000","MCO","","","Crypto.com","","MCO -> EUR","2020-05-02 13:51:11"
"Withdrawal","","","0.57000000","EUR","","","Crypto.com","","EUR Withdrawal (via SEPA)","2020-03-29 11:20:38"
"Trade","0.01310000","BTC","80.30000000","EUR","","","Crypto.com","","EUR -> BTC","2020-03-25 12:15:34"
"Trade","1.00000000","ETH","119.13000000","EUR","","","Crypto.com","","EUR -> ETH","2020-03-19 13:22:25"
"Deposit","200.00000000","EUR","","","","","Crypto.com","","EUR Deposit (Via SEPA)","2020-03-19 08:10:02"
"Trade","0.05000000","BTC","259.96000000","EUR","","","Crypto.com","","Buy BTC","2020-03-13 15:44:01"
"Income","18.51347874","MCO","","","","","Crypto.com","","Sign-up Bonus Unlocked","2020-03-13 15:23:01"
"Trade","50.00000000","MCO","128.54000000","EUR","","","Crypto.com","","Buy MCO","2020-03-13 15:22:01"
"Deposit","128.54000000","EUR","","","4.50000000","EUR","","","","2020-03-13 14:21:25"
"Deposit","259.96000000","EUR","","","9.10000000","EUR","","","","2020-03-13 14:21:25"`

**Comment by LefterisJP** [comment]
Thank you for the issue @vchatela. We are going to take a look.

Cointracking CSV import is experimental since very few people use it, the format of the data changes often and they are missing important data from trades

Also from looking at the CSV you provided I see Crypto.com was used as an exchange which we don't support yet. But we definitely could consider it as "other" source and still add the trades.

**Comment by vchatela** [comment]
Hi @LefterisJP 
I did the import from Crypto.com to Cointracking and now I wanted to move it to Rotki.
I will import them manually I done have a lot of transactions :)
Thank you !

**Comment by vchatela** [comment]
If it can help I have made this one worked : 
```"","Type","Buy","Cur.","Sell","Cur.","Fee","Cur.","Exchange","Date"
"","Trade","3300.00000000","CRO","197.01000000","EUR","no exchange","","","14.05.2020 11:46"```
Which was previsouly : 
``` "Type","Buy","Cur.","Sell","Cur.","Fee","Cur.","Exchange","Group","Comment","Date"
"Trade","3300.00000000","CRO","197.01000000","EUR","","","Crypto.com","","EUR -> CRO","2020-05-14 11:46:20" ```

So removed 'Comment' and 'Group' and added no exchange because "" not matched/accepted. 
Then date changed from - to . and display to EN mode.

**Comment by LefterisJP** [comment]
All right so I see what's wrong. They changed the import format again. The timestamp key used to be `Date` and now it's `Trade Date`.

We will fix it and include the fix in the next release, but yeah as I mentioned this feature is really experimental since they just change their data format all the time.

Also we don't support crypto.com yet, but yeah using "no exchange" should work :)

Thanks for the report. Your test data help a lot to support the latest version of their export.

**Comment by vchatela** [comment]
Thank you very much for your help and future changes.
Very nice job ! 👍

**Comment by LefterisJP** [comment]
@vchatela The new cointracking.info format should be properly read in latest develop now since we fixed it in https://github.com/rotki/rotki/pull/998

It will be included in the next release (v.1.5.0 or v1.4.3).
